<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 21.01.2010 20:29
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'models/app_school/staff/StaffDBAccess.php';
require_once 'models/app_school/schedule/ScheduleDBAccess.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$academicId = isset($_GET["academicId"])? (int) $_GET["academicId"]:"";
$current_instructor = isset($_GET["current_instructor"])? addText($_GET["current_instructor"]):"";
$teacherId = isset($_GET["teacherId"])?addText($_GET["teacherId"]):"";
$schoolyearId = isset($_GET["schoolyearId"])?addText($_GET["schoolyearId"]):"";

?>
<script>
Ext.onReady(function() {
	
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    //$registry = Zend_Registry::getInstance();
    ?>
    var parameters = '?'
    + 'academicId=<?=$academicId;?>'
    + '&objectId=<?=$academicId;?>'
    + '&teacherId=<?=$teacherId;?>'
    + '&current_instructor=<?=$current_instructor;?>'
    + '&schoolyearId=<?=$schoolyearId;?>';

    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'fit'
            ,border: false
            ,items:[new Ext.ux.IFrameComponent({ id: 'SCHEDULE', url: '/schedule/teacherschedule/' + parameters})]
        }]
    });
});
</script>
<?
//$registry = Zend_Registry::getInstance();
print$CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>