<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("STAFF");
$OBJECT_FORM->setLoadUrl('/staff/jsonload/');
$OBJECT_FORM->setSaveUrl('/staff/jsonsave/');

$OBJECT_GRID = new CamemisGrid("STAFF", "SEARCH");
$OBJECT_GRID->setLoadUrl('/staff/jsonload/');
$OBJECT_GRID->setSaveUrl('/staff/jsonsave/');

$personType = isset($_GET["personType"])?$_GET["personType"]:"STAFF";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$columndata = Utiles::getGridColumnData("STAFF_SEARCH_ID")

?>
<style>
    .filter-row-grid .x-grid3-header {
    background: #f9f9f9 url(/public/images/filter-row-hrow.gif) repeat-x left top;
}

.filter-row-grid .filter-row-header {
    height: 26px;
}

tr.filter-row-header .filter-row-icon input {
    background-image: url(/public/images/filter-row-icon.png);
    background-repeat: no-repeat;
    padding-left: 16px;
}
</style>
<script>

Ext.apply(Ext.form.VTypes, {
    daterange : function(val, field) {
        var date = field.parseDate(val);
        if(!date){
            return false;
        }
        if (field.startDateField) {
            var start = Ext.getCmp(field.startDateField);
            if (!start.maxValue || (date.getTime() !== start.maxValue.getTime())) {
                start.setMaxValue(date);
                start.validate();
            }
        }
        else if (field.endDateField) {
            var end = Ext.getCmp(field.endDateField);
            if (!end.minValue || (date.getTime() !== end.minValue.getTime())) {
                end.setMinValue(date);
                end.validate();
            }
        }
        return true;
    }
});
Ext.onReady(function() {

    Ext.Ajax.timeout = 600000;

    function myAjaxRequest(formObject, gridObject){
        var fieldValue = formObject.getForm().getFieldValues();
        if(plsEnterKey(fieldValue)){
            <?=CamemisPage::alertPleaseSelect(NOTES,PLS_ENTER_KEYWORD)?>
        }else{
            var myMask = new Ext.LoadMask(Ext.getBody(), {msg:'<b>CAMEMIS <?=LOADING?></b>', msgCls:'x-mask-loading-camemis'});
            myMask.show();
            Ext.Ajax.request({
                url: '/staff/jsonload'
                ,method: 'POST'
                ,params:{cmd:'searchStaff'}
                ,form: formObject.getForm().getEl().dom
                ,success: function(response, options) {
                    jsonData = Ext.util.JSON.decode(response.responseText);
                    var myform=<?=$OBJECT_FORM->ExtgetCmp();?>;
                    for(var i=0;i<myform.getForm().getEl().dom.length;i++){
                        if(myform.getForm().getEl().dom[i].value){
                            Ext.getCmp('<?=$OBJECT_GRID->getObjectId();?>').getStore().setBaseParam(myform.getForm().getEl().dom[i].name,myform.getForm().getEl().dom[i].value);
                        }
                    }
                    gridObject.getStore().loadData(jsonData);
                    myMask.hide();
                }
            });
        }
    }

    function plsEnterKey(obj){
        var s;
        if(obj.LASTNAME || obj.FIRSTNAME || obj.GENDER
            || obj.CODE || obj.STAFF_SCHOOL_ID || obj.RELIGION
            || obj.ETHNIC || obj.NATIONALITY || obj.START_DATE
        ){
            s = 0;
        }else{
            s = 1;
        }
        return s;
    }

    function keyEnter(){
        var formObject = Ext.getCmp('<?=$OBJECT_FORM->getObjectId()?>');
        var gridObject = Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>');
        myAjaxRequest(formObject, gridObject);
    }

    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#333; padding: 5px;">' + value + '</div>';
    }
    function cssStatus(v, p, record){
        return String.format('<div style=\"font-weight:bold;padding:4px;background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['BG_COLOR']
            ,record.data['BG_COLOR_FONT']
        );
    }
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    $OBJECT_SCHOOLYEAR = new CamemisDynCombo("ACADEMICDATE","COMBO");
    $OBJECT_SCHOOLYEAR->setLoadUrl('/academicdate/jsonload/');
    $OBJECT_SCHOOLYEAR->objectTitle = false;
    $OBJECT_SCHOOLYEAR->allowBlank = "true";
    $OBJECT_SCHOOLYEAR->varName = "SCHOOLYEAR";
    $OBJECT_SCHOOLYEAR->setLoadParams("cmd: 'allSchoolyearCombo'");
    $OBJECT_SCHOOLYEAR->renderJS();

    $OBJECT_LOCATION_PARENT = new CamemisDynCombo("DATASET","PROVINCE");
    $OBJECT_LOCATION_PARENT->setLoadUrl('/dataset/jsonload/');
    $OBJECT_LOCATION_PARENT->objectTitle = CITY_PROVINCE;
    $OBJECT_LOCATION_PARENT->allowBlank = "true";
    $OBJECT_LOCATION_PARENT->width = 150;
    $OBJECT_LOCATION_PARENT->varName = "COUNTRY_PROVINCE";
    $OBJECT_LOCATION_PARENT->setLoadParams("cmd: 'jsonAllLocation',parentId:0");
    $OBJECT_LOCATION_PARENT->renderJS();

    $OBJECT_LOCATION_CHILD = new CamemisDynCombo("DATASET","TWON");
    $OBJECT_LOCATION_CHILD->setLoadUrl('/dataset/jsonload/');
    $OBJECT_LOCATION_CHILD->objectTitle = TOWN_CITY;
    $OBJECT_LOCATION_CHILD->allowBlank = "true";
    $OBJECT_LOCATION_CHILD->width = 150;
    $OBJECT_LOCATION_CHILD->varName = "TOWN_CITY";
    $OBJECT_LOCATION_CHILD->setLoadParams("cmd: 'jsonAllLocation',parentId:'1010101010'");
    $OBJECT_LOCATION_CHILD->renderJS();

    $CAMEMIS_PAGE_OBJECT->setAddTab();

    $PERSONAL_INFORMATION = "{
        xtype:'fieldset'
        ,checkboxToggle:true
        ,title: '".PERSONAL_INFORMATION."'
        ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
        ,width: 310
        ,items:[
            {".CamemisField::Textfield("STAFF_SCHOOL_ID", "STAFF_SCHOOL_ID", STAFF_SCHOOL_ID, false, false, false, 150)."}
            ,{".CamemisField::Textfield("CODE_ID", "CODE", CODE_ID, false, false, false, 150)."}
            ,{".CamemisField::Textfield("LASTNAME_ID", "LASTNAME", LASTNAME, false, false, false, 150)."}
            ,{".CamemisField::Textfield("FIRSTNAME_ID", "FIRSTNAME", FIRSTNAME, false, false, false, 150)."}
            ,{".CamemisField::ComboGender(GENDER, false, false, 150)."}
            ,{".CamemisField::comboOrganization(true, false, false, 150)."}
            ,{".CamemisField::comboReligion(false, false, 150)."}
            ,{".CamemisField::comboEthnic(false, false, 150)."}
            ,{".CamemisField::comboNationality(false,false, 150)."}
            ,{".CamemisField::ComboUserRole(USER_ROLE, false, false, 150)."}
        ]
    }";
    
    $EDUCATION_BACKGROUND = "{
        xtype:'fieldset'
        ,checkboxToggle:true
        ,collapsed:true
        ,title: '".EDUCATION_BACKGROUND."'
        ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
        ,width: 310
        ,items:[
            {".CamemisField::comboMajor(false,false, 150)."}
            , {".CamemisField::comboQualitycationDegree(false,false, 150)."}
        ]
    }";
    $REGISTRATION = "{
        xtype:'fieldset'
        ,checkboxToggle:true
        ,collapsed: true
        ,title: '".REGISTRATION."'
        ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;padding:10px'
        ,width: 310
        ,items:[{
            name: 'START_DATE'
            ,hidden: false
            ,width: 150
            ,fieldLabel: '" . START_DATE . "'
            ,xtype: 'datefield'
            ,id: 'START_DATE'
            ,vtype: 'daterange'
            ,endDateField: 'END_DATE'
            ,format: '" . setExtDatafieldFormat() . "'
            ,allowBlank: true
        },{
            name: 'END_DATE'
            ,hidden: false
            ,width: 150
            ,fieldLabel: '" . END_DATE . "'
            ,xtype: 'datefield'
            ,id: 'END_DATE'
            ,vtype: 'daterange'
            ,format: '" . setExtDatafieldFormat() . "'
            ,startDateField: 'START_DATE'
            ,allowBlank: true
        }]
    }";

    $ADDRESS = "{
        xtype:'fieldset'
        ,checkboxToggle:true
        ,collapsed: true
        ,title: '".ADDRESS."'
        ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
        ,width: 310
        ,items:[
            {".CamemisField::Textfield("PHONE_ID", "PHONE", PHONE, false, false, false, 150)."}
            ,{".CamemisField::Textfield("EMAIL_ID", "EMAIL", EMAIL, false, false, false, 150)."}
            ,{xtype: '".$OBJECT_LOCATION_PARENT->getObjectXType()."'}
            ,{xtype: '".$OBJECT_LOCATION_CHILD->getObjectXType()."'}
        ]
    }";

    $OBJECT_FORM->addObjectItems(CamemisField::Hidden("CHOOSE_DESCRIPTION",false));

    $OBJECT_FORM->addTBarItems("
        text: '".RESET."'
        ,iconCls:'icon-arrow_undo'
        ,handler: function(){
            ".CamemisPage::setRequestURI(false)."
        }
    ");

    $OBJECT_FORM->addTBarItems("
        text: '".FIND."'
        ,id: 'FIND_ID'
        ,formBind:true
        ,iconCls:'icon-magnifier'
        ,scope:this
        ,handler: function(){
            var formObject = Ext.getCmp('".$OBJECT_FORM->getObjectId()."');
            var gridObject = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');
            myAjaxRequest(formObject, gridObject);
        }
    ");

    $FORM_ITEMS = "[";
    $FORM_ITEMS .= "".$PERSONAL_INFORMATION;
    $FORM_ITEMS .= ",".$EDUCATION_BACKGROUND;
    $FORM_ITEMS .= ",".$REGISTRATION;
    $FORM_ITEMS .= ",".$ADDRESS;
    $FORM_ITEMS .= ",".Utiles::personalDescriptionDisplayFields("STAFF",310);
    $FORM_ITEMS .= "]";

    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'background:".CamemisPage::userFormBgColor().";'
        ,items: ".$FORM_ITEMS."
    ";
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->setBodyStyle("padding:10px;background:".CamemisPage::userFormBgColor().";");
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->isKeys = false;
    $OBJECT_FORM->renderJS();

    ///////////////////////////////////////////////////////
    $OBJECT_GRID->addReadField("name: 'ID'");
    $OBJECT_GRID->addReadField("name: 'CODE'");
    $OBJECT_GRID->addReadField("name: 'STAFF'");
    $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
    $OBJECT_GRID->addReadField("name: 'LASTNAME'");
    $OBJECT_GRID->addReadField("name: 'FIRSTNAME_LATIN'");
    $OBJECT_GRID->addReadField("name: 'LASTNAME_LATIN'");
    $OBJECT_GRID->addReadField("name: 'GENDER'");
    $OBJECT_GRID->addReadField("name: 'BG_COLOR'");
    $OBJECT_GRID->addReadField("name: 'BG_COLOR_FONT'");
    $OBJECT_GRID->addReadField("name: 'STATUS_KEY'");
    $OBJECT_GRID->addReadField("name: 'PHONE'");
    $OBJECT_GRID->addReadField("name: 'EMAIL'");
    $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");

    switch(Zend_Registry::get('SYSTEM_LANGUAGE')){
        case "VIETNAMESE": $width = 125;break;
        default: $width = 85;break;
    }

    $OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: ".$width.", hidden:".checkColHidden(1, $columndata).", renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY',filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".CODE_ID."</b>', width: 80,hidden:".checkColHidden(2, $columndata).", renderer: cssText, sortable: true, dataIndex: 'CODE',filter:{}");

    if(!SchoolDBAccess::displayPersonNameInGrid()){

        $OBJECT_GRID->addColumn("header: '<b>".LASTNAME."</b>', width: 120,hidden:".checkColHidden(3, $columndata).", renderer: cssText, sortable: true, dataIndex: 'LASTNAME',filter:{}");
        $OBJECT_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', width: 120,hidden:".checkColHidden(4, $columndata).", renderer: cssText, sortable: true, dataIndex: 'FIRSTNAME',filter:{}");

        $OBJECT_GRID->addColumn("header: '<b>".LASTNAME_LATIN."</b>', width: 120,hidden:".checkColHidden(6, $columndata).", renderer: cssText, sortable: true, dataIndex: 'LASTNAME_LATIN',filter:{}");
        $OBJECT_GRID->addColumn("header: '<b>".FIRSTNAME_LATIN."</b>', width: 120,hidden:".checkColHidden(5, $columndata).", renderer: cssText, sortable: true, dataIndex: 'FIRSTNAME_LATIN',filter:{}");

    }else{

        $OBJECT_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', width: 120,hidden:".checkColHidden(3, $columndata).", renderer: cssText, sortable: true, dataIndex: 'FIRSTNAME',filter:{}");
        $OBJECT_GRID->addColumn("header: '<b>".LASTNAME."</b>', width: 120,hidden:".checkColHidden(4, $columndata).", renderer: cssText, sortable: true, dataIndex: 'LASTNAME',filter:{}");

        $OBJECT_GRID->addColumn("header: '<b>".FIRSTNAME_LATIN."</b>', width: 120,hidden:".checkColHidden(5, $columndata).", renderer: cssText, sortable: true, dataIndex: 'FIRSTNAME_LATIN',filter:{}");
        $OBJECT_GRID->addColumn("header: '<b>".LASTNAME_LATIN."</b>', width: 120,hidden:".checkColHidden(6, $columndata).", renderer: cssText, sortable: true, dataIndex: 'LASTNAME_LATIN',filter:{}");
    }

    $OBJECT_GRID->addColumn("header: '<b>".GENDER."</b>', width: 100,hidden:".checkColHidden(7, $columndata).", renderer: cssText, sortable: false, dataIndex: 'GENDER',filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".PHONE."</b>', width: 150,hidden:".checkColHidden(8, $columndata).", renderer: cssText, sortable: false, dataIndex: 'PHONE',filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".EMAIL."</b>', width: 150,hidden:".checkColHidden(9, $columndata).", renderer: cssText, sortable: false, dataIndex: 'EMAIL',filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_DATE."</b>', width: 150,hidden:".checkColHidden(10, $columndata).", renderer: cssText, sortable: true, dataIndex: 'CREATED_DATE',filter:{}");

    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'searchStaff'
    ";

    if(UserAuth::getACLValue("STAFF_SEARCH_EXECUTE_RIGHT")){
        $OBJECT_GRID->addTBarItems("
            tbar.add([{
                text: '" . EXPORT_TO_EXCEL . "'
                ,id: 'EXPORT_TO_EXCEL'
                ,iconCls:'icon-page_excel'
                ,handler: function(){
                    Ext.MessageBox.show({
                        msg: '".SAVING_YOUR_DATA_PLEASE_WAIT."',
                        progressText: 'Saving...',
                        width:300,
                        wait:true,
                        waitConfig: {interval:200},
                        icon:'ext-mb-download'
                    });
                    myForm = Ext.getCmp('".$OBJECT_FORM->getObjectId()."').getForm();
                    Ext.Ajax.request({
                        url: '/export/jsonexcel/'
                        ,method: 'POST'
                        ,timeout: 600000
                        ,params:{cmd: 'staffSearch',objectId:'STAFF_SEARCH_ID'}
                        ,form: myForm.getEl().dom
                        ,success: function(response, options) {
                            Ext.MessageBox.hide();
                            window.location='/export/openstafflist/'
                        }
                    });
                }
            }]);
        ");
    }

    $OBJECT_GRID->addTBarItems("
        tbar.add('->');
    ");
    $OBJECT_GRID->loadMask = true;
    $OBJECT_GRID->isPagingToolbar = true;
    $OBJECT_GRID->isQuickySearch = true;
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->setUserColumn = true;
    $OBJECT_GRID->isFilterRow = true;
    $OBJECT_GRID->renderJS();

    ////////////////////////////////////////////////////////////////////////////

    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout: 'card'
            ,border: false
            ,activeItem: 0
            ,id: 'CONTENT'
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    title: ''
                    ,region:'west'
                    ,id: 'WEST_ID'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width:350
                    ,minSize:350
                    ,maxSize:350
                    ,keys:{
                        key:[13]
                        ,fn: keyEnter
                        ,scope:this
                    }
                    ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                },{
                    title: ''
                    ,collapsible: false
                    ,id: 'center'
                    ,region:'center'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,margins: '3 3 3 0'
                    ,items:[{
                        layout:'fit'
                        ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                        ,border: false
                        ,items:[{
                            xtype: 'tabpanel'
                            ,id:'TABPANEL_ID'
                            ,tabPosition: 'top'
                            ,plain:true
                            ,activeTab: 0
                            ,enableTabScroll:true
                            ,items:[{
                                title:'<?= SEARCH_RESULT;?>'
                                ,layout:'fit'
                                ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}]
                            }]
                        }]
                    }]
                }]
            }]
        }]
    });

    var comboParent = Ext.getCmp('PROVINCE_ID');
    var comboChild = Ext.getCmp('TWON_ID');

    if(comboParent){
        comboParent.on('select', function() {
            comboChild.setValue('');
            comboChild.store.baseParams = {
                cmd: 'jsonAllLocation'
                ,parentId: comboParent.getValue()
            };
            comboChild.store.reload();
        });
    }

    <?
    $CONTEXTMENU_ITEMS = array();

    $SHOW_DETAIL ="{";
        $SHOW_DETAIL .="text: '".SHOW_DETAIL." &raquo; ' + record.data.STAFF";
        $SHOW_DETAIL .=",iconCls: 'icon-user'";
        $SHOW_DETAIL .=",handler: function(){";
        $SHOW_DETAIL .="contextMenu.hide();clickOpenPage('center','','/staff/staffmonitor/?&target=".camemisId()."&objectId=' + record.data.ID);";
        $SHOW_DETAIL .="Ext.getCmp('WEST_ID').collapse();";
        $SHOW_DETAIL .="}";
    $SHOW_DETAIL .="}";

    if (UserAuth::getACLValue("STAFF_PERSONAL_INFORMATION_READ_RIGHT"))
    $CONTEXTMENU_ITEMS[] = $SHOW_DETAIL;
    $SEND_SMS ="{";
        $SEND_SMS .="text: '".SEND." &raquo; ' + record.data.STAFF";
        $SEND_SMS .=",iconCls: 'icon-email_add'";
        $SEND_SMS .=",handler: function(){";
        $SEND_SMS .="contextMenu.hide();openWinIFrame('Mail &raquo; ' + record.data.STAFF, '/dataset/sendemail/?objectId=' + record.data.ID,550,percentHeight(85))";
        $SEND_SMS .="}";
    $SEND_SMS .="}";

    if (UserAuth::getACLValue("STAFF_SEARCH_EXECUTE_RIGHT"))
    $CONTEXTMENU_ITEMS[] = $SEND_SMS;

    $PAYMENT_INFORMATION ="{";
        $PAYMENT_INFORMATION .="text: '".PAYMENT_INFORMATION." &raquo; ' + record.data.STAFF";
        $PAYMENT_INFORMATION .=",iconCls: 'icon-cashier'";
        $PAYMENT_INFORMATION .=",handler: function(){";
        $PAYMENT_INFORMATION .="contextMenu.hide();clickOpenPage('center',record.data.STUDENT,'/finance/staffaccounthistory/?&target=".camemisId()."&objectId=' + record.data.ID);";
        $PAYMENT_INFORMATION .="}";
    $PAYMENT_INFORMATION .="}";

    if (UserAuth::getACLValue("STAFF_SEARCH_EXECUTE_RIGHT"))
    $CONTEXTMENU_ITEMS[] = $PAYMENT_INFORMATION;

    $CHOOSE_CONTEXTMENU_ITEMS = implode(",", $CONTEXTMENU_ITEMS);

    $html ="var grid = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');";
    $html .="if (grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {";
        $html .="var record = grid.store.getAt(rowIndex);";
        $html .="var contextMenu = new Ext.menu.Menu({";
        $html .="items: [".$CHOOSE_CONTEXTMENU_ITEMS."]";
        $html .="});";
        $html .="event.stopEvent();";
        $html .="contextMenu.showAt(event.xy);";
    $html .="});";
    echo $html;
    ?>
    Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>