<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 05.02.2014
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$ANSWER_TREE = new CamemisTree("ANSWER","LIST");
$ANSWER_TREE->setURL('/camemisevaluation/jsontree/');
$ANSWER_TREE->setSaveUrl('/camemisevaluation/jsonsave/');

$OBJECT_FORM = new CamemisForm("QUESTION");
$OBJECT_FORM->setSaveUrl("/camemisevaluation/jsonsave/");
$OBJECT_FORM->setLoadUrl("/camemisevaluation/jsonload/");

$answerId = '';
if($this->facette) $answerId = $this->facette->ANSWERID;    

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $ANSWER_TREE->setBaseParams("
        cmd: 'jsonTreeAllEvaluationAnswer'
        ,showCheck:0
    ");
    
    $ANSWER_TREE->isAsyncTreeNode = false;
    $ANSWER_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));
    $ANSWER_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $ANSWER_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    $ANSWER_TREE->backgroundColor = "#F9F9F9";
    $ANSWER_TREE->renderJS();
    
    $triggerOnClick = "
        openWinXType('ANSWER','".ANSWER."', '".$ANSWER_TREE->getObjectXType()."', 500, percentHeight(85));
        var answerTree = Ext.getCmp('".$ANSWER_TREE->getObjectId()."');
        answerTree.on('click', function(node, e){
            if(!node.isLeaf()){
                Ext.getCmp('ANSWERID').setValue(node.id);
                Ext.getCmp('ANSWER_NAME_ID').setValue(node.text);
                Ext.getCmp('ANSWER').close(); 
            }        
        });
    ";
    
    $OBJECT_FORM->addObjectItems("
        title: '".NAME."'
        ,autoHeight: true
        ,style: 'padding-bottom:5px'
        ,collapsible: true
        ,collapsed: false
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Textfield("QUESTION_NAME", "NAME", NAME, false, false, false, false)."}
            ]
        }]   
    ");
    
    if($this->objectId != "new")
    $OBJECT_FORM->addObjectItems("
        title: '".ANSWER."'
        ,autoHeight: true
        ,style: 'padding-bottom:5px'
        ,collapsible: true
        ,collapsed: false
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Trigger("ANSWER_NAME",ANSWER,$triggerOnClick,true, false, false)."}
                ,{".CamemisField::Hidden("ANSWERID",$answerId)."}
            ]
        }]   
    ");
    
    $OBJECT_FORM->addObjectItems("
        title: '".DESCRIPTION."'
        ,collapsible: true
        ,collapsed: false
        ,width:550
        ,style: 'padding-bottom: 5px'
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'padding:5px'
            ,items:[{".CamemisField::Textarea("DESCRIPTION",DESCRIPTION,200,false,false)."}]
        }]   
    ");
    
    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);
        }
    ");
    
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'jsonSaveEvaluationQuestion'
        ,objectId: '".$this->objectId."'
    ");
    
    $OBJECT_FORM->setonEmbeddedEvents("
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
        var result = Ext.util.JSON.decode(action.response.responseText);
        window.parent.Ext.getCmp('QUESTION_LIST_ID').store.reload();
        window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
     ");
     
     if($this->objectId != "new"){
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleRemove());
        
        $OBJECT_FORM->setRemoveParams("
            cmd: 'jsonRemoveEvaluationQuestion'
            ,objectId: '".$this->objectId."'
        ");
        
        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            XMsg('".STATUS."','".MSG_ACTION_REMOVED_ITEM."'); 
            window.parent.Ext.getCmp('QUESTION_LIST_ID').store.reload();
            window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);
        ");
        
        $OBJECT_FORM->setLoadParams("
            cmd: 'jsonLoadEvaluationQuestion'
            ,objectId: '".$this->objectId."'
        ");    
     }
    
    $OBJECT_FORM->isObjectDefaultOnLoad = ($this->objectId=="new")?false:true; 
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>