<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("ACADEMIC");
$OBJECT_FORM->setLoadUrl('/academic/jsonload/');
$OBJECT_FORM->setSaveUrl('/academic/jsonsave/');

$OBJECT_TREE = new CamemisTree("SUBJECT", "LIST");
$OBJECT_TREE->setURL('/subject/jsontree/');
$OBJECT_TREE->setSaveUrl('/subject/jsonsave/');

$parentId = isset($_GET["parentId"])?addText($_GET["parentId"]):"";

$facette = AcademicDBAccess::findGradeFromId($parentId);

if(!$facette) {header("Location: /main/permission/");}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_TREE->isAsyncTreeNode = false;

        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());

        $OBJECT_TREE->setBaseParams("
            cmd: 'treeAllSubjects'
        ");

        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isTreeExpand = true;
        $OBJECT_TREE->isOnClickContextMenu = false;
        $OBJECT_TREE->renderJS();
        ////////////////////////////////////////////////////////////////////////
        $triggerOnClick = "
            openWinXType('SUBJECT_WIN','".SUBJECT."', '".$OBJECT_TREE->getObjectXType()."',500, percentHeight(85));
            var myTree = Ext.getCmp('".$OBJECT_TREE->getObjectId()."');
            myTree.on('click', function(node, e){
                Ext.getCmp('CHOOSE_SUBJECT_NAME_ID').setValue(node.text);
                Ext.getCmp('CHOOSE_SUBJECT').setValue(node.id);
                Ext.getCmp('SUBJECT_WIN').close();
            });
        ";
        ////////////////////////////////////////////////////////////////////////
        
        $FORM_ITEMS = "[";
        
        $FORM_ITEMS .= "{".CamemisField::Textfield("NAME_ID", "NAME", NAME, true)."}";
        $FORM_ITEMS .= ",{" . CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false) . "}";
        
        $FORM_ITEMS .= "]";
        
        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: ".$FORM_ITEMS."
            }]
        }
        ";

        $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: [
            ".$DETAIL_INFORMATION."
        ]
        ";
        $OBJECT_FORM->addObjectItems($items);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('ACADEMIC_ID').expand();
            }
        ");
        
        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());

        if($facette->EDUCATION_SYSTEM){
            $objecttype = "SUBJECT";
        }else{
            $objecttype = "CLASS";
        }
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'addClass'
            ,objecttype: '".$objecttype."'
            ,parentId: '".$parentId."'
        ");

        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            myNode = myTree.getNodeById('".$parentId."');
            myNode.reload();
            myNode.expand(true, false); 
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 160;
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>