<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("ACADEMIC");
$OBJECT_FORM->setLoadUrl('/academic/jsonload/');
$OBJECT_FORM->setSaveUrl('/academic/jsonsave/');

$parentId = isset($_GET["parentId"])?addText($_GET["parentId"]):"";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
	
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    $DETAIL_INFORMATION = "
    {
        title: '".DETAIL_INFORMATION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF;padding:10px'
            ,items: [
                {".CamemisField::Textfield("NAME_ID", "NAME", NAME, true)."}
                ,{".CamemisField::Numberfield("LEVEL_ID", "LEVEL", GRADE_LEVEL, false)."}
                ,{" . CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false) . "}
            ]
        }]
    }
    ";
    
    $COPY_SETTINGS = "
    {
        title: '".COPY_SETTINGS."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
        }]
    }
    ";
    
    $COPY_SETTINGS = "
    {
        title: '".COPY_SETTINGS."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::ComboGrade(GRADE,false)."}
                ,{".CamemisField::Checkbox("COPY_PERIOD_SCHEDULE", "COPY_PERIOD_SCHEDULE", PERIOD_SCHEDULE, false, true)."}
            ]
        }]
    }
    ";
    
    $formItems = "[";
    $formItems .= $DETAIL_INFORMATION;
    //$formItems .= ",".$COPY_SETTINGS;
    $formItems .= "]";
    
    $OBJECT_FORM->addObjectItems("
    	xtype: 'panel'
    	,border: false
        ,bodyStyle: 'padding:0px'
    	,layout: 'form'
    	,items: ".$formItems."
    ");
    
    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            window.parent.Ext.getCmp('ACADEMIC_ID').expand();
        }
    ");
    
    if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT"))
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());

    $OBJECT_FORM->setSaveParams("
        cmd: 'addGrade'
        ,objecttype: 'GRADE'
        ,parentId: '".$parentId."'
    ");
	
    $OBJECT_FORM->setonEmbeddedEvents("

        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
        myNode = myTree.getNodeById('".$parentId."');
        myNode.reload();
        myNode.expand(true, false); 
        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        
    ");

    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>