<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_school/AcademicDateDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("ACADEMIC");
$OBJECT_FORM->setLoadUrl('/academic/jsonload/');
$OBJECT_FORM->setSaveUrl('/academic/jsonsave/');

$OBJECT_TREE = new CamemisTree("ACADEMICDATE", "LIST");
$OBJECT_TREE->setURL('/academicdate/jsontree/');
$OBJECT_TREE->setSaveUrl('/academicdate/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */

        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('ACADEMIC_ID').expand();
            }
        ");
        
        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        $OBJECT_TREE->setBaseParams("
            cmd: 'jsonTreeAllAcademicDate'
            ,target: '".$this->parentId."'
        ");
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isOnClickContextMenu = false;
        $OBJECT_TREE->isTreeExpand = true;
        $OBJECT_TREE->renderJS();
    
        $triggerOnClick = "
            openWinXType('SCHOOL_YEAR','".SCHOOL_YEAR."', '".$OBJECT_TREE->getObjectXType()."', 500, percentHeight(85));
            var myTree = ".$OBJECT_TREE->ExtgetCmp().";
            myTree.on('click', function(node, e){   
                Ext.getCmp('CHOOSE_SCHOOLYEAR_NAME_ID').setValue(node.text);
                Ext.getCmp('HIDDEN_SCHOOLYEAR').setValue(node.id);
                Ext.getCmp('SCHOOL_YEAR').close();
            });
        ";
        
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        $OBJECT_FORM->setSaveParams("
            cmd: 'addSchoolYear'
            ,objecttype: 'SCHOOLYEAR'
            ,parentId: '".$this->parentId."'
        ");
        
        $FORM_ITEMS = "[
            {".CamemisField::Trigger("CHOOSE_SCHOOLYEAR_NAME",SCHOOL_YEAR,$triggerOnClick, true)."}
            ,{".CamemisField::Hidden("HIDDEN_SCHOOLYEAR", false)."}
            ,{" . CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false) . "}
        ]"; 

        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: ".$FORM_ITEMS."
            }]
        }
        ";
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: [
                ".$DETAIL_INFORMATION."
            ]
        ";
        $OBJECT_FORM->addObjectItems($items);
        
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            myNode = myTree.getNodeById('".$this->parentId."');
            myNode.reload();
            myNode.expand(true, false); 
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->renderJS();
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
        });
    });
    //alert('<?=Zend_Registry::get('TERM_NUMBER')?>');
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>