<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'models/app_school/AcademicDateDBAccess.php';
require_once 'models/app_school/academic/AcademicDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$DB_SCHOOLYEAR = AcademicDateDBAccess::getInstance();

$OBJECT_FORM = new CamemisForm("ACADEMIC");
$OBJECT_FORM->setLoadUrl('/academic/jsonload/');
$OBJECT_FORM->setSaveUrl('/academic/jsonsave/');

$INSTRUCTOR_GRID = new CamemisGrid("INSTRUCTOR", "LIST");
$INSTRUCTOR_GRID->setLoadUrl('/academic/jsonload/');
$INSTRUCTOR_GRID->setSaveUrl('/academic/jsonsave/');

if(!$this->facette) {header("Location: /main/permission/");exit;}

print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>

<script>
    <?
    camemisPage::ExtformVTypes();
    ?>
    Ext.onReady(function() {
        
        function cssText(value, metadata, record){
            return '<div style="font-weight:normal; color:#333; padding:3px;">' + value + '</div>';
        }
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        ////////////////////////////////////////////////////////////////////////
        $INSTRUCTOR_GRID->addReadField("name: 'ID'");
        $INSTRUCTOR_GRID->addReadField("name: 'CHECKED'");
        $INSTRUCTOR_GRID->addReadField("name: 'CODE'");
        $INSTRUCTOR_GRID->addReadField("name: 'LASTNAME'");
        $INSTRUCTOR_GRID->addReadField("name: 'FIRSTNAME'");
        
        $INSTRUCTOR_GRID->addColumn("
            xtype: 'checkboxcolumn'
            ,align:'center'
            ,header: '<b>" . APPLY . "</b>'
            ,dataIndex: 'CHECKED'
            ,width: 80
            ,on: 1
            ,off: 0
            ,renderer: cssText
        ");
        
        $INSTRUCTOR_GRID->addColumn("
            header: '<b>" . CODE_ID . "</b>'
            , align:'left'
            , sortable: false
            , dataIndex: 'CODE'
            , width: 80
            ,renderer: cssText
        ");
        
        if(!SchoolDBAccess::displayPersonNameInGrid()){
            $INSTRUCTOR_GRID->addColumn("
                header: '<b>" . LASTNAME . "</b>'
                , align:'left'
                , sortable: false
                , dataIndex: 'LASTNAME'
                , width: 120
                ,renderer: cssText
            ");
            
            $INSTRUCTOR_GRID->addColumn("
                header: '<b>" . FIRSTNAME . "</b>'
                , align:'left'
                , sortable: false
                , dataIndex: 'FIRSTNAME'
                , width: 120
                ,renderer: cssText
            ");
        }else{
            $INSTRUCTOR_GRID->addColumn("
                header: '<b>" . FIRSTNAME . "</b>'
                , align:'left'
                , sortable: false
                , dataIndex: 'FIRSTNAME'
                , width: 120
                ,renderer: cssText
            ");
            
            $INSTRUCTOR_GRID->addColumn("
                header: '<b>" . LASTNAME . "</b>'
                , align:'left'
                , sortable: false
                , dataIndex: 'LASTNAME'
                , width: 120
                ,renderer: cssText
            "); 
        }
                
        $INSTRUCTOR_GRID->baseParams = "
            start:0
            ,limit:100
            ,objectId: '" . $this->objectId . "'
            ,cmd: 'jsonInstructorsByClass'
        ";
        $INSTRUCTOR_GRID->setSaveParams("
            cmd: 'actionClassInstructor'
            ,objectId: '" . $this->objectId . "'
        ");
        $INSTRUCTOR_GRID->setEditEmbeddedEvents("
             XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        ");
        $INSTRUCTOR_GRID->isGridEditing = true;
        $INSTRUCTOR_GRID->loadMask = false;
        $INSTRUCTOR_GRID->isPagingToolbar = true;
        $INSTRUCTOR_GRID->isQuickySearch = true;
        $INSTRUCTOR_GRID->isObjectDefaultOnLoad = true;
        $INSTRUCTOR_GRID->forceFit = "false";
        $INSTRUCTOR_GRID->renderJS();
        ////////////////////////////////////////////////////////////////////////
        
        $INSTRUCTOR_GRID = "
        {
            title: '".INSTRUCTOR_IN."'
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,height: 350
            ,layout: 'fit'
            ,items:[{xtype: '".$INSTRUCTOR_GRID->getObjectXtype()."'}]
        }";

        $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '" . $this->objectId . "'");
        $OBJECT_FORM->setSaveParams("
            cmd: 'updateObject'
            ,objecttype: 'CLASS'
            ,objectId: '" . $this->objectId . "'
        ");
        $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '" . $this->objectId . "'");

        $DETAIL_INFORMATION_ITEMS = "[";
        $DETAIL_INFORMATION_ITEMS .= "{" . CamemisField::Textfield("CODE", "CODE", CODE_ID, false, true) . "}";
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Textfield("NAME", "NAME", NAME) . "}";
        
        if($this->facette->EDUCATION_SYSTEM){
            $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Textfield("NUMBER_CREDIT", "NUMBER_CREDIT", CREDITS, false, false) . "}";
        }
        
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false) . "}";
        $DETAIL_INFORMATION_ITEMS .= "]";
        
        $DETAIL_INFORMATION = "
        {
            title: '" . DETAIL_INFORMATION . "'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: ".$DETAIL_INFORMATION_ITEMS."
            }]
        }
        ";
        
        $WORKING_DAYS = "
        {
            title: '".WORKING_DAYS."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,autoHeight: true
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: [
                    {".CamemisField::Displayfield("SHOW_MO", MONDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_TU", TUESDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_WE", WEDNESDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_TH", THURSDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_FR", FRIDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_SA", SATURDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_SU", SUNDAY)."}
                ]
            }]
        }";
        
        ///////////////////////////////////////////////////
        $CREATED = "
        {
            title: '".CREATED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("CREATED_DATE",CREATED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("CREATED_BY",CREATED_BY,false)."
                }]
            }]
        }";
        
        $MODIFIED = "
        {
            title: '".MODIFIED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("MODIFY_DATE",MODIFY_DATE,false)."
                },{
                    ".CamemisField::Displayfield("MODIFY_BY",MODIFY_BY,false)."
                }]
            }]
        }";
        
        $DISABLED = "
        {
            title: '".DISABLED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("DISABLED_DATE",DISABLED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("DISABLED_BY",DISABLED_BY,false)."
                }]
            }]
        }";
        ///////////////////////////////////////////////////
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:10px'
            ,items: [
                " . $DETAIL_INFORMATION . "  
                ," . $WORKING_DAYS . "
                ," . $INSTRUCTOR_GRID . "     
                ," . $CREATED . "
                ," . $MODIFIED . "
                ," . $DISABLED . "
            ]
        ";
        
        $OBJECT_FORM->addObjectItems($items);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('ACADEMIC_ID').expand();
            }
        ");
        
        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
        
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 150;
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            myNode = myTree.getNodeById('".$this->facette->PARENT."');
            myNode.reload();
            myNode.expand(true, false); 
        ");

        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            myNode = myTree.getNodeById('".$this->facette->PARENT."');
            myNode.reload();
            myNode.expand(true, false); 
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");

        $OBJECT_FORM->bodyStyle = "padding:0px";
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,id: 'content'
                ,layout: 'card'
                ,activeItem: 0
                ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
            }]
        });
    });
</script>
<?
print$CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>