<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'models/app_school/AcademicDateDBAccess.php';
require_once 'models/app_school/academic/AcademicDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$DB_SCHOOLYEAR = AcademicDateDBAccess::getInstance();

$OBJECT_FORM = new CamemisForm("ACADEMIC");
$OBJECT_FORM->setLoadUrl('/academic/jsonload/');
$OBJECT_FORM->setSaveUrl('/academic/jsonsave/');

//@veasna

$PREREQUISITE_TREE = new CamemisTree("SUBJECT", "LIST");
$PREREQUISITE_TREE->setURL("/subject/jsontree/");
//

if(!$this->facette) {header("Location: /main/permission/");exit;}

print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>

<script>
    <?
    camemisPage::ExtformVTypes();
    ?>
    Ext.onReady(function() {
        
        function cssText(value, metadata, record){
            return '<div style="font-weight:normal; color:#333; padding:3px;">' + value + '</div>';
        }
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '" . $this->objectId . "'");
        $OBJECT_FORM->setSaveParams("
            cmd: 'updateObject'
            ,objecttype: 'SUBJECT'
            ,objectId: '" . $this->objectId . "'
        ");
        $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '" . $this->objectId . "'");

        $DETAIL_INFORMATION_ITEMS = "[";
        $DETAIL_INFORMATION_ITEMS .= "{" . CamemisField::Textfield("CODE", "CODE", CODE_ID, false, true) . "}";
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Textfield("NAME", "NAME", NAME) . "}";
        
        if($this->facette->EDUCATION_SYSTEM){
            $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Textfield("NUMBER_CREDIT", "NUMBER_CREDIT", CREDITS, false, false) . "}";
        }
        
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false) . "}";
        $DETAIL_INFORMATION_ITEMS .= "]";
        
        $DETAIL_INFORMATION = "
        {
            title: '" . DETAIL_INFORMATION . "'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: ".$DETAIL_INFORMATION_ITEMS."
            }]
        }
        ";
        
        //@veasna 
       ////////////////////////////////////////////////////////////////////////
        $PREREQUISITE_TREE->isAsyncTreeNode = false;
        $PREREQUISITE_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $PREREQUISITE_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $PREREQUISITE_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        $PREREQUISITE_TREE->setBaseParams("
            cmd: 'treeAllSubjects'
            ,requisiteId:'".$this->facette->SUBJECT_ID."'
            ,gradeSubjectGradId: '".$this->facette->CAMPUS_ID."'
            ,schoolyear: '".$this->facette->SCHOOL_YEAR."'
        ");
        
        //$PREREQUISITE_TREE->backgroundColor = "#F9F9F9";
        $PREREQUISITE_TREE->isTreeExpand = true;
        $PREREQUISITE_TREE->isOnClickContextMenu = false;
        $PREREQUISITE_TREE->renderJS();
        ////////////////////////////////////////////////////////////////////////
        
        $PRE_REQUISITE_COURSE = "
        {
            title: '".PRE_REQUISITE_COURSE."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,height:450
            ,layout:'fit'
            ,items:[{xtype: '".$PREREQUISITE_TREE->getObjectXtype()."'}]
        }";
       //
        
        $WORKING_DAYS = "
        {
            title: '".WORKING_DAYS."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,height: true
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: [
                    {".CamemisField::Checkbox("ID1","MO", MONDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID2","TU", TUESDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID3","WE", WEDNESDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID4","TH", THURSDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID5","FR", FRIDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID6","SA", SATURDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID7","SU", SUNDAY, 1, false)."}
                ]
            }]
        }";
        
        ///////////////////////////////////////////////////
        $CREATED = "
        {
            title: '".CREATED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("CREATED_DATE",CREATED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("CREATED_BY",CREATED_BY,false)."
                }]
            }]
        }";
        
        $MODIFIED = "
        {
            title: '".MODIFIED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("MODIFY_DATE",MODIFY_DATE,false)."
                },{
                    ".CamemisField::Displayfield("MODIFY_BY",MODIFY_BY,false)."
                }]
            }]
        }";
        
        $DISABLED = "
        {
            title: '".DISABLED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("DISABLED_DATE",DISABLED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("DISABLED_BY",DISABLED_BY,false)."
                }]
            }]
        }";
        ///////////////////////////////////////////////////
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:10px'
            ,items: [
                " . $DETAIL_INFORMATION . " 
                ," . $WORKING_DAYS . "
                ," . $PRE_REQUISITE_COURSE . "
                ," . $CREATED . "
                ," . $MODIFIED . "
                ," . $DISABLED . "
            ]
        ";
        
        $OBJECT_FORM->addObjectItems($items);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('ACADEMIC_ID').expand();
            }
        ");
        
        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
        
        $OBJECT_FORM->addTBarItems("
            text:''
            ,tooltip:'".CAMEMIS_HELP."'
            ,iconCls: 'icon-help'
            ,handler:function(){
                ".CamemisPage::setEmbeddedHelp("5F43-3846")."
            }
        ");
        
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 150;
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            myNode = myTree.getNodeById('".$this->facette->PARENT."');
            myNode.reload();
            myNode.expand(true, false); 
        ");

        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            myNode = myTree.getNodeById('".$this->facette->PARENT."');
            myNode.reload();
            myNode.expand(true, false); 
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");

        $OBJECT_FORM->bodyStyle = "padding:0px";
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,id: 'content'
                ,layout: 'card'
                ,activeItem: 0
                ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
            }]
        });
        
        
        var tree = Ext.getCmp('<?=$PREREQUISITE_TREE->getObjectId()?>');
        tree.on('checkchange', function(node, checked){
            
            var selecteds = '', selNodes = tree.getChecked();
            Ext.each(selNodes, function(node){
                if(selecteds.length > 0){
                    selecteds += ',';
                }
                selecteds += node.id;
            });
            Ext.Ajax.request({
                url: '/subject/jsonsave/'
                ,method: 'POST'
                ,scope:this
                ,params: {
                    cmd: 'actionPreRequisite2GradeSubject'
                    ,selecteds: selecteds
                    ,objectId: '<?=$this->facette->SUBJECT_ID;?>'
                    ,academicId: '<?=$this->facette->CAMPUS_ID;?>'
                    ,schoolyear: '<?=$this->facette->SCHOOL_YEAR;?>'
                }
                ,success: function(response, options) {
                    XMsg('<?=STATUS?>','<?=ACTION_SUCCESSFULLY_SAVED?>'); 
                }
            });
        });
        
        
    });
</script>
<?
print$CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>