<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 25.11.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$listSubjects = GradeSubjectDBAccess::getListSubjectsFromAcademic($this->objectId,false);

?>

<style>
 @media screen and (-webkit-min-device-pixel-ratio:0) { 
    .x-grid3-cell, /* Normal grid cell */
    .x-grid3-gcell /* Grouped grid cell (esp. in head)*/
    {
        box-sizing: border-box;
    }
}
</style>

<script>
var comboValue;
Ext.onReady(function() {
    
    Ext.QuickTips.init();
    
    function cssStatus(v, p, record){
        return String.format('<div style=\"font-weight:normal;padding:4px;height:18px;background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['BG_COLOR']
            ,record.data['BG_COLOR_FONT']
        );
    }
    
    function cssDefault(value, metadata, record){
        var name = record.data.FULL_NAME;
        metadata.attr = 'ext:qtip="' + name + '"';
        return '<div style="font-weight:normal; color:#333; padding:4px;height:18px;">' + value + '</div>';
    }
    
    function cssFirst(value, metadata, record){
        var name = record.data.FULL_NAME;
        metadata.attr = 'ext:qtip="' + name + '"';
        return '<div style="font-weight:bold; color:#000; padding:4px;height:18px;background:#b8cfee">' + value + '</div>';
    }
    
    function cssSecond(value, metadata, record){
        var name = record.data.FULL_NAME;
        metadata.attr = 'ext:qtip="' + name + '"';
        return '<div style="font-weight:bold; color:#000; padding:4px;height:18px;background:#fff">' + value + '</div>';
    }
    
    <?
    
    $GROUP_ROW = "";
    $GROUP_ROW .= "{header: '&nbsp;', colspan: 1, align: 'center'}";
    $GROUP_ROW .= ",{header: '&nbsp;', colspan: 1, align: 'center'}";
    $GROUP_ROW .= ",{header: '&nbsp;', colspan: 1, align: 'center'}";
    $GROUP_ROW .= ",{header: '&nbsp;', colspan: 1, align: 'center'}";
    
    /**
     * Subject List
     */
    if($listSubjects){
        foreach($listSubjects as $value){
            $GROUP_ROW .= ",{header: '<b>".stripcslashes($value->SUBJECT_NAME)."</b>', colspan: 2, align: 'center'}";
        }
    }
    
    $FIELDS = "";
    $FIELDS .= "{name: 'ID'}";
    $FIELDS .= ",{name: 'STATUS_KEY'}";
    $FIELDS .= ",{name: 'BG_COLOR'}";
    $FIELDS .= ",{name: 'BG_COLOR_FONT'}";
    $FIELDS .= ",{name: 'STATUS_KEY'}";
    $FIELDS .= ",{name: 'FULL_NAME'}";
    $FIELDS .= ",{name: 'GENDER'}";

    if($listSubjects){
        foreach($listSubjects as $value){
            $FIELDS .= ",{name: 'FIRST_SEMESTER__".$value->SUBJECT_ID."'}";
            $FIELDS .= ",{name: 'SECOND_SEMESTER__".$value->SUBJECT_ID."'}";
        }
    }
    
    $COLUMNS = "";
    $COLUMNS .= "new Ext.grid.RowNumberer()";
    $COLUMNS .= ",{dataIndex: 'STATUS_KEY', header: '<b>".STATUS."</b>', width:90, renderer:cssStatus, align:'center',sortable: true}";
    $COLUMNS .= ",{dataIndex: 'FULL_NAME', header: '<b>".FULL_NAME."</b>', width:150,sortable: true, renderer:cssDefault}";
    $COLUMNS .= ",{dataIndex: 'GENDER', header: '<b>".GENDER."</b>', width:80,sortable: true,align:'center',renderer:cssDefault}";
    
    if($listSubjects){
        foreach($listSubjects as $value){
            
             $COLUMNS .= ",{
                header: '<b>1S</b>'
                ,dataIndex: 'FIRST_SEMESTER__".$value->SUBJECT_ID."'
                ,width:60,align: 'center',renderer:cssFirst
                ,editor: new Ext.form.ComboBox({
                    triggerAction:'all'
                    ,mode:'local'
                    ,store: new Ext.data.JsonStore({
                        autoDestroy: true
                        ,fields: ['chooseValue', 'chooseDisplay']
                        ,data:[{chooseValue: '0', chooseDisplay: '---'},{chooseValue: '1', chooseDisplay: 'X'}]
                    })
                    ,valueField: 'chooseValue'
                    ,displayField: 'chooseDisplay'
                    ,editable: false
                    ,listeners: {
                        select: function(combo, record, index) {
                            replaceValue = combo.getValue();
                            var newDisplay = record.get('chooseDisplay');
                            combo.setValue(newDisplay);
                            comboValue = record.get('chooseValue');
                        }
                    }
                })
            }";
             
            $COLUMNS .= ",{
                header: '<b>2S</b>'
                ,dataIndex: 'SECOND_SEMESTER__".$value->SUBJECT_ID."'
                ,width:60,align: 'center',renderer:cssFirst
                ,editor: new Ext.form.ComboBox({
                    triggerAction:'all'
                    ,mode:'local'
                    ,store: new Ext.data.JsonStore({
                        autoDestroy: true
                        ,fields: ['chooseValue', 'chooseDisplay']
                        ,data:[{chooseValue: '0', chooseDisplay: '---'},{chooseValue: '1', chooseDisplay: 'X'}]
                    })
                    ,valueField: 'chooseValue'
                    ,displayField: 'chooseDisplay'
                    ,editable: false
                    ,listeners: {
                        select: function(combo, record, index) {
                            replaceValue = combo.getValue();
                            var newDisplay = record.get('chooseDisplay');
                            combo.setValue(newDisplay);
                            comboValue = record.get('chooseValue');
                        }
                    }
                })
           }";
        }
    }
    
    $setParams = "1111";
    
    $html = "";
    $html .= "var groupRow = [".$GROUP_ROW."];";
    $html .= "var fields =  [".$FIELDS."];";
    $html .= "var columns = [".$COLUMNS."];";
    
    $html .= "var group = new Ext.ux.grid.ColumnHeaderGroup({rows: [groupRow]});";
    
    $html .= "var myStore = new Ext.data.Store({";
        $html .= "proxy: new Ext.data.HttpProxy({url:'/student/jsonload/', method: 'POST'})";
        $html .= ",baseParams:{";
            $html .= "start:0";
            $html .= ",limit:100";
            $html .= ",cmd:'enrollStudentsSubjectTerm'";
            $html .= ",classId: '".$this->facette->ID."'";
        $html .= "}";
        $html .= ",reader:new Ext.data.JsonReader({";
            $html .= "id:'NAME'";
            $html .= ",totalProperty:'totalCount'";
            $html .= ",root:'rows'";
            $html .= ",fields:fields";
        $html .= "})";
    $html .= "});";
    
    $html .= "var grid = new Ext.grid.EditorGridPanel({";
        $html .= "tbar:[{";
            $html .= "text: '<b>".REFRESH."</b>'";
            $html .= ",iconCls:'icon-reload'";
            $html .= ",handler: function(){";
                $html .= "".CamemisPage::setRequestURI(false)."";
            $html .= "}";
        
        $html .= "}]";
        
        $html .= ",loadMask: new Ext.LoadMask(Ext.getBody(), {msg:'<b>CAMEMIS " . LOADING . "</b>', msgCls:'x-mask-loading-camemis'})";
        $html .= ",clicksToEdit:1";
        $html .= ",border:false";
        $html .= ",store: myStore";
        $html .= ",columns: columns";
        $html .= ",viewConfig: {";
            $html .= "forceFit: false";
        $html .= "}";
        
        $html .= ",plugins: group";
        
        $html .= ",listeners: {";
            $html .= "afteredit: function (e){";
                $html .= "Ext.Ajax.request({";
                    $html .= "url: '/student/jsonsave/'";
                    $html .= ",method: 'POST'";
                    $html .= ",params: {";
                        $html .= "cmd:'jsonActionEnrollStudentSubjectTerm'";
                        $html .= ",academicId: '".$this->facette->ID."'";
                        $html .= ",id:e.record.get('ID')";
                        $html .= ",field: e.field";
                        $html .= ",newValue: e.value";
                        $html .= ",comboValue:comboValue";
                    $html .= "}";
                    $html .= ",success: function (result, request ) {";
                        $html .= "XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');";
                        $html .= "jsonData = Ext.util.JSON.decode(result.responseText);";
                        $html .= "grid.getStore().commitChanges();";
                    $html .= "}";
                $html .= "});";
            $html .= "}";
        $html .= "}";
        
        $html .= ",bbar:new Ext.PagingToolbar({";
            $html .= "store:myStore";
            $html .= ",displayInfo:true";
            $html .= ",pageSize:100";
        $html .= "})";
    $html .= "});";
    
    $html .= "grid.store.reload();";
    
    $html .= "viewport = new Ext.Viewport({";
        $html .= "layout: 'fit'";
        $html .= ",border: false";
        $html .= ",items:[{";
            $html .= "layout:'fit'";
            $html .= ",border: false";
            $html .= ",items:[grid]";
        $html .= "}]";
    $html .= "});";
    
    echo $html;
    ?>
});

</script>

<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>