<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 19.02.2012
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisGrid.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$LIST_OF_STUDENTS_GIRD = new CamemisGrid("LIST_OF_STUDENTS", "LIST_OF_STUDENTS");
$LIST_OF_STUDENTS_GIRD->setLoadUrl("/student/jsonload/");
$LIST_OF_STUDENTS_GIRD->setSaveUrl("/student/jsonsave/");
$ASSIGNED_STUDENTS_GRID = new CamemisGrid("STUDENT", "LIST_CLASS");
$ASSIGNED_STUDENTS_GRID->setLoadUrl("/student/jsonload/");
$ASSIGNED_STUDENTS_GRID->setSaveUrl("/student/jsonsave/");

if(!$this->facette) {header("Location: /main/permission/");exit;}

$TERM_NUMBER = AcademicDBAccess::findAcademicTerm($this->facette->SCHOOL_YEAR);

function deleteStudent($ASSIGNED_STUDENTS_GRID, $academicId){
    
    $js = "";
    $js .= "window.parent.Ext.MessageBox.show({";
    $js .= "title:'" . STATUS . "'";
    $js .= ",width: 350";
    $js .= ",msg: '" . DELETE_THIS_ITEM . "'";
    $js .= ",buttons: Ext.MessageBox.YESNO";
    $js .= ",icon: Ext.MessageBox.WARNING";
    $js .= ",fn: function(btn, text){
        if (btn == 'yes'){
            Ext.Ajax.request({
                url: '/student/jsonsave/'
                ,method: 'POST'
                ,params: {cmd: 'jsonRemoveEnrolledStudentClass',academicId:'".$academicId."',removeId:record.data.ID}
                ,success: function(response, options) {
                    XMsg('".STATUS."','".WAR_REMOVED_SUCCESSFULLY."');
                    Ext.getCmp('" . $ASSIGNED_STUDENTS_GRID->getObjectId() . "').store.reload();
                }
                ,failure: function(response, options) {}
            });
        }
    }";
    $js .= "});";
    
    return $js;
}
         
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
var studentId;
Ext.onReady(function() {
	
    Ext.Ajax.timeout = 600000;
    
    function cssStatus(v, p, record){
        return String.format('<div style=\"font-weight:bold;padding:4px;background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['BG_COLOR']
            ,record.data['BG_COLOR_FONT']
        );
    }
    
    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#333; padding:3px;">' + value + '</div>';
    }
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    ///////////////////////////////////////////////////////
    $LIST_OF_STUDENTS_GIRD->addReadField("name: 'CODE'");
    $LIST_OF_STUDENTS_GIRD->addReadField("name: 'STUDENT_SCHOOL_ID'");
    $LIST_OF_STUDENTS_GIRD->addReadField("name: 'LASTNAME'");
    $LIST_OF_STUDENTS_GIRD->addReadField("name: 'FIRSTNAME'");
    $LIST_OF_STUDENTS_GIRD->addReadField("name: 'GENDER'");
    $LIST_OF_STUDENTS_GIRD->addReadField("name: 'DATE_BIRTH'");
    $LIST_OF_STUDENTS_GIRD->addReadField("name: 'BG_COLOR'");
    $LIST_OF_STUDENTS_GIRD->addReadField("name: 'BG_COLOR_FONT'");
    $LIST_OF_STUDENTS_GIRD->addReadField("name: 'STATUS_KEY'");
    
    switch(Zend_Registry::get('SYSTEM_LANGUAGE')){
        case "VIETNAMESE": $width = 100;break;
        default: $width = 85;break;
    }
    
    $LIST_OF_STUDENTS_GIRD->addColumn("header: '<b>".STATUS."</b>', align:'center', width: ".$width.",renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY'");
    $LIST_OF_STUDENTS_GIRD->addColumn("header: '<b>".CODE_ID."</b>', align:'left', renderer:cssText, sortable: true, width: 80,dataIndex: 'CODE'");
    
    if(!SchoolDBAccess::displayPersonNameInGrid()){
        $LIST_OF_STUDENTS_GIRD->addColumn("header: '<b>".LASTNAME."</b>', width: 100,renderer:cssText, sortable: true, dataIndex: 'LASTNAME'");
        $LIST_OF_STUDENTS_GIRD->addColumn("header: '<b>".FIRSTNAME."</b>', width: 100,renderer:cssText, sortable: true, dataIndex: 'FIRSTNAME'");
    }else{
        $LIST_OF_STUDENTS_GIRD->addColumn("header: '<b>".FIRSTNAME."</b>', width: 100,renderer:cssText, sortable: true, dataIndex: 'FIRSTNAME'");
        $LIST_OF_STUDENTS_GIRD->addColumn("header: '<b>".LASTNAME."</b>', width: 100,renderer:cssText, sortable: true, dataIndex: 'LASTNAME'");
    }
    
    $LIST_OF_STUDENTS_GIRD->addColumn("header: '<b>".GENDER."</b>', width: 100,renderer: cssText, sortable: true, dataIndex: 'GENDER'");
    $LIST_OF_STUDENTS_GIRD->addColumn("header: '<b>".DATE_BIRTH."</b>', width: 120,renderer: cssText, sortable: true, dataIndex: 'DATE_BIRTH'");
    
    $LIST_OF_STUDENTS_GIRD->isQuickySearch = true;
    $LIST_OF_STUDENTS_GIRD->isCheckboxSelect = true;

    if(UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT")){
        $LIST_OF_STUDENTS_GIRD->addTBarItems("
            tbar.add('-');
        ");
        $LIST_OF_STUDENTS_GIRD->addTBarItems("
            tbar.add([{
                id: 'LIST_ADD_ENROLLMENT_RECORD_ID'
                ,text: '<b>".APPLY_INTO_LIST_OF_STUDENTS."</b>'
                ,iconCls:'icon-disk'
                ,scope:this
                ,handler: this.onSelection
            }]);
        ");
    }
    
    $LIST_OF_STUDENTS_GIRD->baseParams = "
        start:0
        ,limit:100
        ,academicId: '".$this->facette->GUID."'
        ,cmd: 'jsonUnassignedStudentsByClass'
    ";

    $LIST_OF_STUDENTS_GIRD->setSelectionParams("
        cmd: 'jsonAddEnrollStudentClass'
        ,academicId: '".$this->facette->GUID."'
    ");

    $LIST_OF_STUDENTS_GIRD->setSelectionEmbeddedEvents("
        Ext.getCmp('".$ASSIGNED_STUDENTS_GRID->getObjectId()."').store.reload();
    ");

    $LIST_OF_STUDENTS_GIRD->forceFit = "false";
    $LIST_OF_STUDENTS_GIRD->renderJS();
    
    ///////////////////////////////////////////////////////
    $ASSIGNED_STUDENTS_GRID->addTBarItems("
        tbar.add('-');
    ");
    
    $ASSIGNED_STUDENTS_GRID->addTBarItems("
        tbar.add([{
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            }
        }]);
    ");
    
    $ASSIGNED_STUDENTS_GRID->addTBarItems("
        tbar.add('-',[{
            id: 'GRID_REFRESH_ID'
            ,text: '".REFRESH."'
            ,iconCls:'icon-reload'
            ,scope:this
            ,disabled: false
            ,handler: function(){
                Ext.getCmp('".$ASSIGNED_STUDENTS_GRID->getObjectId()."').store.reload();
            }
        }]);
    ");
    
    $ASSIGNED_STUDENTS_GRID->addTBarItems("tbar.add('-');");

    if(UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT")){
        $ASSIGNED_STUDENTS_GRID->addTBarItems("
            tbar.add(['-',{
                id: 'ADD_STUDENTS'
                ,iconCls:'icon-application_form_add'
                ,text: '".ADD_STUDENTS." '
                ,handler: function(){
                    openWinXType('WinXType','".ADD_STUDENTS."', '".$LIST_OF_STUDENTS_GIRD->getObjectXType()."',percentWidth(80), percentHeight(85));
                }
            }]);
        ");
    }
    
    if(UserAuth::getACLValue("STUDENT_SEARCH_EXECUTE_RIGHT")){
        $ASSIGNED_STUDENTS_GRID->addTBarItems("
            tbar.add(['->',{
                text: '" . EXPORT_TO_EXCEL . "'
                ,id: 'EXPORT_TO_EXCEL'
                ,iconCls:'icon-page_excel'
                ,handler: function(){
                    Ext.MessageBox.show({
                        msg: '".SAVING_YOUR_DATA_PLEASE_WAIT."',
                        progressText: 'Saving...',
                        width:300,
                        wait:true,
                        waitConfig: {interval:200},
                        icon:'ext-mb-download'
                    });
                    Ext.Ajax.request({
                        url: '/export/jsonexcel/'
                        ,method: 'POST'
                        ,params:{cmd: 'studentSearch',objectId:'STUDENT_LIST_CLASS_ID',classId:'".$this->facette->ID."'}
                        ,success: function(response, options) {
                            Ext.MessageBox.hide();
                            window.location='/export/openstudentlist/'
                        }
                    });
                }
            }]);
        ");
    }
    
    ////////////////////////////////////////////////////////////////////////////
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'ID'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'CODE'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'FULL_NAME'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'STUDENT_SCHOOL_ID'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'STUDENT'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'FIRSTNAME'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'LASTNAME'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'GENDER'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'DATE_BIRTH'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'BG_COLOR'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'BG_COLOR_FONT'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'STATUS_KEY'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'STATUS'");
    
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'FIRST_ACADEMIC'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'SECOND_ACADEMIC'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'THIRD_ACADEMIC'");
    $ASSIGNED_STUDENTS_GRID->addReadField("name: 'FOURTH_ACADEMIC'");
    
    switch(Zend_Registry::get('SYSTEM_LANGUAGE')){
        case "VIETNAMESE": $width = 100;break;
        default: $width = 85;break;
    }
    
    $ASSIGNED_STUDENTS_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: ".$width.", renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY'");
    $ASSIGNED_STUDENTS_GRID->addColumn("header: '<b>".CODE_ID."</b>', align:'center', width: 80, renderer: cssText, sortable: true, dataIndex: 'CODE'");
    
    if(!SchoolDBAccess::displayPersonNameInGrid()){
        $ASSIGNED_STUDENTS_GRID->addColumn("
            header: '<b>".LASTNAME."</b>'
            , width: 110
            , sortable: true
            , dataIndex: 'LASTNAME'
            , editor: new Ext.form.TextField({
                allowBlank: false
                ,name: 'LASTNAME'
            })
        ");
        
        $ASSIGNED_STUDENTS_GRID->addColumn("
            header: '<b>".FIRSTNAME."</b>'
            , width: 110
            , sortable: true
            , dataIndex: 'FIRSTNAME'
            , editor: new Ext.form.TextField({
                allowBlank: false
                ,name: 'FIRSTNAME'
            })
        ");
        
    }else{
        
        $ASSIGNED_STUDENTS_GRID->addColumn("
            header: '<b>".FIRSTNAME."</b>'
            , width: 110
            , sortable: true
            , dataIndex: 'FIRSTNAME'
            , editor: new Ext.form.TextField({
                allowBlank: false
                ,name: 'FIRSTNAME'
            })
        ");
        
        $ASSIGNED_STUDENTS_GRID->addColumn("
            header: '<b>".LASTNAME."</b>'
            , width: 110
            , sortable: true
            , dataIndex: 'LASTNAME'
            , editor: new Ext.form.TextField({
                allowBlank: false
                ,name: 'LASTNAME'
            })
        ");
    }
    
    $ASSIGNED_STUDENTS_GRID->addColumn("header: '<b>".GENDER."</b>', align:'center',  width: 100, renderer: cssText, sortable: true, dataIndex: 'GENDER'");
    $ASSIGNED_STUDENTS_GRID->addColumn("
        header: '<b>".DATE_BIRTH."</b>'
        , width: 110
        , sortable: true
        , dataIndex: 'DATE_BIRTH'
        , editor: new Ext.form.TextField({
            allowBlank: false
            ,name: 'DATE_BIRTH'
        })
    ");
    
    if($this->facette->ENROLLMENT_TYPE == 1){
        switch($TERM_NUMBER){
            case 1:
                $ASSIGNED_STUDENTS_GRID->addColumn("
                    xtype: 'checkboxcolumn'
                    ,align: 'center'
                    ,header: '<b>".FIRST_TERM."</b>'
                    ,dataIndex: 'FIRST_ACADEMIC'
                    ,disabled: true
                    ,width: 100
                    ,on: 1
                    ,off: 0
                ");
                $ASSIGNED_STUDENTS_GRID->addColumn("
                    xtype: 'checkboxcolumn'
                    ,align: 'center'
                    ,header: '<b>".SECOND_TERM."</b>'
                    ,dataIndex: 'SECOND_ACADEMIC'
                    ,disabled: true
                    ,width: 100
                    ,on: 1
                    ,off: 0
                ");
                $ASSIGNED_STUDENTS_GRID->addColumn("
                    xtype: 'checkboxcolumn'
                    ,align: 'center'
                    ,header: '<b>".THIRD_TERM."</b>'
                    ,dataIndex: 'THIRD_ACADEMIC'
                    ,disabled: true
                    ,width: 100
                    ,on: 1
                    ,off: 0
                ");
                break;
            case 2:
                $ASSIGNED_STUDENTS_GRID->addColumn("
                    xtype: 'checkboxcolumn'
                    ,align: 'center'
                    ,header: '<b>".FIRST_QUARTER."</b>'
                    ,dataIndex: 'FIRST_ACADEMIC'
                    ,disabled: true
                    ,width: 100
                    ,on: 1
                    ,off: 0
                ");
                $ASSIGNED_STUDENTS_GRID->addColumn("
                    xtype: 'checkboxcolumn'
                    ,align: 'center'
                    ,header: '<b>".SECOND_QUARTER."</b>'
                    ,dataIndex: 'SECOND_ACADEMIC'
                    ,disabled: true
                    ,width: 100
                    ,on: 1
                    ,off: 0
                ");
                $ASSIGNED_STUDENTS_GRID->addColumn("
                    xtype: 'checkboxcolumn'
                    ,align: 'center'
                    ,header: '<b>".THIRD_QUARTER."</b>'
                    ,dataIndex: 'THIRD_ACADEMIC'
                    ,disabled: true
                    ,width: 100
                    ,on: 1
                    ,off: 0
                ");
                $ASSIGNED_STUDENTS_GRID->addColumn("
                    xtype: 'checkboxcolumn'
                    ,align: 'center'
                    ,header: '<b>".FOURTH_QUARTER."</b>'
                    ,dataIndex: 'FOURTH_ACADEMIC'
                    ,disabled: true
                    ,width: 100
                    ,on: 1
                    ,off: 0
                ");
                break;
            default:
                $ASSIGNED_STUDENTS_GRID->addColumn("
                    xtype: 'checkboxcolumn'
                    ,align: 'center'
                    ,header: '<b>".FIRST_SEMESTER."</b>'
                    ,dataIndex: 'FIRST_ACADEMIC'
                    ,disabled: true
                    ,width: 100
                    ,on: 1
                    ,off: 0
                ");
                $ASSIGNED_STUDENTS_GRID->addColumn("
                    xtype: 'checkboxcolumn'
                    ,align: 'center'
                    ,header: '<b>".SECOND_SEMESTER."</b>'
                    ,dataIndex: 'SECOND_ACADEMIC'
                    ,disabled: true
                    ,width: 100
                    ,on: 1
                    ,off: 0
                ");
                break;
        }
    }
    
    $ASSIGNED_STUDENTS_GRID->baseParams = "
        start:0
        ,limit:100
        ,classId: '".$this->facette->ID."'
        ,cmd: 'enrollStudentsByClassTerm'
    ";
    
    $ASSIGNED_STUDENTS_GRID->setRemoveEmbeddedEvents("
        Ext.getCmp('".$ASSIGNED_STUDENTS_GRID->getObjectId()."').store.reload();
    ");
    
    switch(UserAuth::getUserType()){
        case "ADMIN":
        case "SUPERADMIN":
            $ASSIGNED_STUDENTS_GRID->setSaveParams("
                cmd: 'actionStudentSchoolYear'
                ,academicId: '".$this->facette->GUID."'
            ");
            $ASSIGNED_STUDENTS_GRID->setAftereditCallback("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            ");
            $ASSIGNED_STUDENTS_GRID->isGridEditing = true;
            break;
    }
    
    $ASSIGNED_STUDENTS_GRID->removeNAME = "STUDENT";
    $ASSIGNED_STUDENTS_GRID->loadMask = true;
    $ASSIGNED_STUDENTS_GRID->isQuickySearch = true;
    $ASSIGNED_STUDENTS_GRID->isObjectDefaultOnLoad = true;
    $ASSIGNED_STUDENTS_GRID->forceFit = "false";
    $ASSIGNED_STUDENTS_GRID->setUserColumn = true;
    $ASSIGNED_STUDENTS_GRID->renderJS();
    ///////////////////////////////////////////////////////
    
    ?>
            
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,layout: 'card'
            ,id: 'center'
            ,activeItem: 0
            ,items:[{
                border: false
                ,layout: 'fit'
                ,items: [{xtype: '<?=$ASSIGNED_STUDENTS_GRID->getObjectXType()?>'}]
            }]
        }]
    });

    <?
        $CONTEXT_ITEMS = array();
                                                           
        $DETAIL_INFORMATION = "
        {
            text: '".SHOW_DETAIL." &raquo; ' + record.data.FULL_NAME
            ,iconCls: 'icon-user'
            ,disabled:false
            ,handler: function(){
                clickOpenPage('center','".SHOW_DETAIL." &raquo; ' + record.data.FULL_NAME,'/student/studentmonitor/?target=".camemisId()."&objectId=' + record.data.ID);
            }
        }
        ";
        
        $CONTEXT_ITEMS[] = $DETAIL_INFORMATION;

        $STUDENT_REMOVE_FROM_CLASS = "
        {
            text: '".REMOVE." &raquo; ' + record.data.FULL_NAME
            ,iconCls:'icon-delete'
            ,handler:function(){".deleteStudent($ASSIGNED_STUDENTS_GRID,$this->facette->GUID)."}
        }
        ";
        
        $CONTEXT_ITEMS[] = $STUDENT_REMOVE_FROM_CLASS;
        $CHOOSE_CONTEXT_ITEMS = implode(',', $CONTEXT_ITEMS);
        
        if($CONTEXT_ITEMS){
            $js = "";
            $js .="var grid = Ext.getCmp('".$ASSIGNED_STUDENTS_GRID->getObjectId()."');";
            $js .="if (grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {";
                $js .="var record = grid.store.getAt(rowIndex);";
                $js .= "if(columnIndex==1 || columnIndex==2){ ";
                    $js .="var contextMenu = new Ext.menu.Menu({";
                        $js .="items: [".$CHOOSE_CONTEXT_ITEMS."]";
                    $js .="});";
                    $js .="contextMenu.showAt(event.xy);";
                    $js .="event.stopEvent();";
                $js .="}";
            $js .="});";
            echo $js;
        } 
    ?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>