<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$LIST_OF_STUDENTS = new CamemisGrid("STUDENT", "LIST_OF_STUDENTS");
$LIST_OF_STUDENTS->setLoadUrl("/student/jsonload/");
$LIST_OF_STUDENTS->setSaveUrl("/student/jsonsave/");

$OBJECT_DATA = $this->objectData;

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<div id="initCenter" class="x-hide-display" style="border:0px silver solid;margin:5px;padding:5px;height:140px">
    <h3 class="header"><?=ADD_INTO_NEW_CLASS;?></h3>
</div>
<script>
    var chooseClassId;
    Ext.chart.Chart.CHART_URL = '../public/<?=Zend_Registry::get('EXTJS_VERSION')?>/resources/charts.swf';
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $LIST_OF_STUDENTS->addCellRenderer("
        function renderText(v, p, record, rowIndex){
            var str = '<span class=spanText>' + v + '</span>';
            return str;
        }
        ");

        $LIST_OF_STUDENTS->addReadField("name: 'CODE'");
        $LIST_OF_STUDENTS->addReadField("name: 'STUDENT_NAME'");
        $LIST_OF_STUDENTS->addReadField("name: 'LASTNAME'");
        $LIST_OF_STUDENTS->addReadField("name: 'FIRSTNAME'");
        $LIST_OF_STUDENTS->addReadField("name: 'GENDER'");
        $LIST_OF_STUDENTS->addReadField("name: 'DATE_BIRTH'");
        $LIST_OF_STUDENTS->addReadField("name: 'CLASS_NAME'");
        $LIST_OF_STUDENTS->addReadField("name: 'GRADE_NAME'");
        $LIST_OF_STUDENTS->addReadField("name: 'SCHOOLYEAR_NAME'");

        $LIST_OF_STUDENTS->addColumn("header: '".CODE_ID."', align:'left', renderer:renderText, sortable: true, width: 100, dataIndex: 'CODE'");
        $LIST_OF_STUDENTS->addColumn("header: '".NAME."', width: 150, renderer:renderText, sortable: true, dataIndex: 'STUDENT_NAME'");
        //$LIST_OF_STUDENTS->addColumn("header: '".FIRSTNAME."', width: 150, renderer:renderText, sortable: false, dataIndex: 'FIRSTNAME'");
        $LIST_OF_STUDENTS->addColumn("header: '".GRADE_CLASS."', renderer:renderText, width: 110, sortable: true, dataIndex: 'CLASS_NAME'");
        $LIST_OF_STUDENTS->addColumn("header: '".GRADE."', renderer:renderText, width: 120, sortable: true, dataIndex: 'GRADE_NAME'");
        $LIST_OF_STUDENTS->addColumn("header: '".SCHOOL_YEAR."', renderer:renderText, width: 110, sortable: true, dataIndex: 'SCHOOLYEAR_NAME'");
        $LIST_OF_STUDENTS->addColumn("header: '".GENDER."', width: 100, renderer:renderText, sortable: true, dataIndex: 'GENDER'");
        $LIST_OF_STUDENTS->addColumn("header: '".DATE_BIRTH."', width: 120, renderer:renderText, sortable: true, dataIndex: 'DATE_BIRTH'");

        if ($this->radioBoxItems !="[]"){

            $disabledButton = "false";
            $westItems = "
            [{
                layout:'form'
                ,labelWidth: 20
                ,border: false
                ,bodyStyle: 'padding:10px'
                ,items: ".$this->radioBoxItems."
            }]
            ";

        }else{
            $disabledButton = "true";
            $westItems = "
            [{
                layout: 'fit'
                ,border: false
                ,contentEl: 'initCenter'
            }]
            ";
        }
        
        $LIST_OF_STUDENTS->addTBarItems("
            tbar.add([{
                id: 'ENROLLMENT_ID'
                ,text: '".ENROLLMENT."'
                ,disabled: ".$disabledButton."
                ,iconCls:'icon-disk'
                ,scope:this
                ,handler: function(){
                    var chooseObject = document.getElementsByName('CLASS');
                    for (var i=0; i<chooseObject.length; i++) {
                       if (chooseObject[i].checked == true) {
                          chooseClassId = chooseObject[i].value;
                          break;
                       }
                    }
                    if (chooseClassId){
                        this.onSelection();
                    }else{
                        Ext.MessageBox.alert('" . WARNING . "', '" . PLEASE_CHOOSE . "');
                    }
                }
            }]);
        ");
        
        $LIST_OF_STUDENTS->isQuickySearch = false;
        $LIST_OF_STUDENTS->isCheckboxSelect = true;
        
        $LIST_OF_STUDENTS->baseParams = "
            start:0
            ,limit:100
            ,classId: '".$this->classId."'
            ,chooseSchoolyearId: '".$this->chosseSchoolyearId."'
            ,nextSchoolyearId: '".$this->nextSchoolyearId."'
            ,cmd: 'enrolledStudentByNextYear'
        ";

        $LIST_OF_STUDENTS->setSelectionParams("
            cmd: 'actionEnrolledStudentByNextYear'
            ,chooseClassId: chooseClassId
            ,nextSchoolyearId: '".$this->nextSchoolyearId."'
        ");

        $LIST_OF_STUDENTS->setSelectionEmbeddedEvents("
            Ext.getCmp('".$LIST_OF_STUDENTS->getObjectId()."').store.reload();
        ");
        
        $LIST_OF_STUDENTS->forceFit = "false";
        $LIST_OF_STUDENTS->renderJS();

        $items = "
        [{
            title: '".GRADE_CLASS." &raquo; ".$this->nextSchoolyear."'
            ,region:'west'
            ,margins: '3 0 3 3'
            ,cmargins: '3 3 3 3'
            ,width: 270
            ,minSize: 270
            ,maxSize: 270
            ,items:[{
                layout:'form'
                ,labelWidth: 20
                ,border: false
                ,bodyStyle: 'padding:10px'
                ,items: ".$westItems."
            }]
        },{
            title: '".$this->chosseSchoolyear." &raquo; ".LIST_OF_STUDENTS."'
            ,collapsible: false
            ,region:'center'
            ,margins: '3 3 3 0'
            ,layout: 'fit'
            ,items:[{
                border: false
                ,layout: 'fit'
                ,items: [{xtype: '".$LIST_OF_STUDENTS->getObjectXType()."'}]
            }]
        }]
        ";

        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                },
                items: <?=$items?>
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>