<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'models/app_school/AcademicDateDBAccess.php';
require_once 'models/app_school/academic/AcademicDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$DB_SCHOOLYEAR = AcademicDateDBAccess::getInstance();

$OBJECT_FORM = new CamemisForm("ACADEMIC");
$OBJECT_FORM->setLoadUrl('/academic/jsonload/');
$OBJECT_FORM->setSaveUrl('/academic/jsonsave/');

$INSTRUCTOR_GRID = new CamemisGrid("INSTRUCTOR", "LIST");
$INSTRUCTOR_GRID->setLoadUrl('/academic/jsonload/');
$INSTRUCTOR_GRID->setSaveUrl('/academic/jsonsave/');

$OBJECT_DATA = $this->objectData;

$schoolyearId = isset($OBJECT_DATA["SCHOOL_YEAR"])?$OBJECT_DATA["SCHOOL_YEAR"]:"";
$CURRENT_SCHOOLYEAR = $DB_SCHOOLYEAR->isCurrentSchoolyear($schoolyearId);

print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    <?
    camemisPage::ExtformVTypes();
    ?>
    Ext.onReady(function() {
        
        function cssText(value, metadata, record){
            return '<div style="font-weight:normal; color:#333; padding:3px;">' + value + '</div>';
        }
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '" . $this->facette->GUID . "'");
        $OBJECT_FORM->setSaveParams("
            cmd: 'updateObject'
            ,objecttype: 'CLASS'
            ,objectId: '" . $this->facette->GUID . "'
        ");
        $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '" . $this->facette->GUID . "'");
        
        $DETAIL_INFORMATION_ITEMS = "[";
        $DETAIL_INFORMATION_ITEMS .= "{" . CamemisField::Displayfield("SHORT_CODE",SHORT_CODE,false) . "}";
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Displayfield("SUBJECT_NAME",SUBJECT,false) . "}";
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Numberfield("NUMBER_CREDIT", "NUMBER_CREDIT", CREDIT, false, false, false) . "}";
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Numberfield("NUMBER_OF_STUDENTS", "NUMBER_OF_STUDENTS", NUMBER_OF_STUDENTS, false, false, false) . "}";
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false) . "}";
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Hidden("SUBJECT_ID",false) . "}    ";
        $DETAIL_INFORMATION_ITEMS .= "]";
        $DETAIL_INFORMATION = "
        {
            title: '" . DETAIL_INFORMATION . "'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width:550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: ".$DETAIL_INFORMATION_ITEMS."
            }]
        }";
        
        $WORKING_DAYS = "
        {
            title: '".WORKING_DAYS."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,autoHeight: true
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: [
                    {".CamemisField::Checkbox("ID1","MO", MONDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID2","TU", TUESDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID3","WE", WEDNESDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID4","TH", THURSDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID5","FR", FRIDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID6","SA", SATURDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID7","SU", SUNDAY, 1, false)."}
                ]
            }]
        }
        ";
        
        $DESCRIPTION = "
        {
            title: '".DESCRIPTION."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:5px'
                ,items: [[{".CamemisField::Textarea("REMARK", false,200)."}]]
            }]
        }";
        
        ////////////////////////////////////////////////////////////////////////
        $CREATED = "
        {
            title: '".CREATED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("CREATED_DATE",CREATED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("CREATED_BY",CREATED_BY,false)."
                }]
            }]
        }";
        
        $MODIFIED = "
        {
            title: '".MODIFIED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("MODIFY_DATE",MODIFY_DATE,false)."
                },{
                    ".CamemisField::Displayfield("MODIFY_BY",MODIFY_BY,false)."
                }]
            }]
        }";
        
        $DISABLED = "
        {
            title: '".DISABLED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("DISABLED_DATE",DISABLED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("DISABLED_BY",DISABLED_BY,false)."
                }]
            }]
        }";
        ////////////////////////////////////////////////////////////////////////
        
        $DISPLAY_ITEMS = "[";
        $DISPLAY_ITEMS .= "".$DETAIL_INFORMATION;
        $DISPLAY_ITEMS .= ",".$WORKING_DAYS;
        $DISPLAY_ITEMS .= ",".$DESCRIPTION;
        $DISPLAY_ITEMS .= ",".$CREATED;
        $DISPLAY_ITEMS .= ",".$MODIFIED;
        $DISPLAY_ITEMS .= ",".$DISABLED;
        $DISPLAY_ITEMS .= "]";
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:10px'
            ,items: ".$DISPLAY_ITEMS."
        ";
        
        $OBJECT_FORM->addObjectItems($items);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        ");
        
        if ($CURRENT_SCHOOLYEAR){
            if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT"))
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
            if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT"))
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
        }
        
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 150;
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            myNode = myTree.getNodeById('".$this->facette->PARENT."');
            myNode.reload();
            myNode.expand(true, false); 
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");

        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            myNode = myTree.getNodeById('".$this->facette->PARENT."');
            myNode.reload();
            myNode.expand(true, false); 
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");

        $OBJECT_FORM->bodyStyle = "padding:0px";
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border:false
            ,items:[{
                layout: 'fit'
                ,border:false
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,items:[{
                    xtype: 'tabpanel'
                    ,plain:true
                    ,activeTab: 0
                    ,items:[{
                        title: '<?=MAIN_CONTENT?>'
                        ,layout: 'fit'
                        ,border: false
                        ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
                    },{
                        title: '<?=ENROLLED_STUDENTS?>'
                        ,layout:'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'ENROLLED_STUDNETS', url: '/academic/enrollmentbysubject/?objectId=<?=$this->facette->GUID?>'})]
                    }]
                }]
            }]
        });
    });
</script>
<?
print$CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>