<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 08.07.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("FILE_SYSTEM", "LIST");
$OBJECT_TREE->setURL("/file/jsontree/");
$parentId = $this->facette?$this->facette->PARENT:'';

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
    switch (UserAuth::getUserType()) {
        case 'STUDENT':
            $OBJECT_TREE->setBaseParams("cmd: 'jsonTreeAllFiles',studentId: '".$this->studentId."'");
            break;
        
        case "TEACHER":
        case 'INSTRUCTOR':
            $OBJECT_TREE->setBaseParams("cmd: 'jsonTreeAllFiles',teacherId: '".$this->teacherId."'");
            break;
            
        case 'SUPERADMIN':
            $OBJECT_TREE->setBaseParams("cmd: 'jsonTreeAllFiles'");
            $OBJECT_TREE->addTBarItems("
                id: 'SCHOOL_DOCUMENTATION'
                ,tooltip:'".SCHOOL_DOCUMENTATION."'
                ,scope:this
                ,iconCls:'icon-application_form_add'
                ,handler: function(){
                    clickOpenPage('center','".SCHOOL_DOCUMENTATION."', '".$this->URL_SHOWITEM."&parentId=0&objectId=new');    
                }
            "); 
            break;                    
    }
    
    $OBJECT_TREE->isTreeExpand = true;
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: false
                ,split: true
            }
            ,items: [{
               	region:'west'
                ,title:'<?=SCHOOL_DOCUMENTATION;?>'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width:280
                ,minSize:280
                ,maxSize:280
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    border: false
                    ,layout: 'anchor'
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items: [{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                    }]
                }]
            }]
        }]
    });
    
    <?
        $js = "";
        $js .= "var myTree = ".$OBJECT_TREE->ExtgetCmp().";";
        $js .= "myTree.on('click', function(node, e){";
            $js .= "parentId = node.attributes.parentId;";
            $js .= "if(node.attributes.uploadFile>0 || node.attributes.fileRecipient>0){";
                $js .= "clickOpenPage('center','".SHOW_DETAIL." &raquo; ' + node.text, '".$this->URL_SHOWITEM."objectId=' + node.attributes.guid);";
            $js .= "}";
            $js .= "else{";
                $js .= "var contextMenu = new Ext.menu.Menu({";
                    $js .= "items: [{";
                        $js .= "text: '".SHOW_DETAIL."'";
                        $js .= ",iconCls:'icon-application_form_magnify'";
                        $js .= ",handler:function(){";
                            $js .= "clickOpenPage('center','".SHOW_DETAIL." &raquo; ' + node.text, '".$this->URL_SHOWITEM."objectId=' + node.attributes.guid);";
                        $js .= "}";
                    $js .= "},{";
                        $js .= "text: '".ADD_A_NEW_ITEM."'";
                        $js .= ",iconCls:'icon-application_form_add'";
                        $js .= ",disabled:false";
                        $js .= ",handler: function(){";
                            $js .= "clickOpenPage('center','".ADD_A_NEW_ITEM."', '".$this->URL_EDIT_FILE."objectId=new&parentId=' + node.id);";
                        $js .= "}";
                    $js .= "}]";
                $js .= "});";
                $js .= "}";
            
            $js .= "e.stopEvent();";
            $js .= "if (contextMenu) contextMenu.showAt(e.xy);";
        $js .= "});";
        
        print $js;
    ?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>