<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("SCHEDULE", "LIST");
$OBJECT_GRID->setLoadUrl("/schedule/jsonload/");
$OBJECT_GRID->setSaveUrl("/schedule/jsonsave/");

$trainingObject =TrainingDBAccess::findTrainingFromId($this->trainingId);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$setParams = "";
$setParams .= "trainingId=".$this->trainingId."";
$setParams .= "&teacherId=".$this->teacherId."";
?>
<script>
    
    <?
    $js = "";
    $js .= "var UrlShowClassEvent = '".$this->URL_SHOW_CLASS_EVENT."';";
    $js .= "function jsDeleteDayClassEvent(shortday){";
        $js .= "Ext.MessageBox.show({";
            $js .= "title:'".WARNING."'";
            $js .= ",width: 350";
            $js .= ",msg:'".MSG_WANT_PERFORM_ACTION."'";
            $js .= ",buttons: Ext.MessageBox.YESNO";
            $js .= ",icon: Ext.MessageBox.WARNING";
            $js .= ",fn: function(btn, text){";
                $js .= "if (btn == 'yes'){";
                    $js .= "Ext.Ajax.request({";
                        $js .= "url: '/schedule/jsonsave/'";
                        $js .= ",method: 'POST'";
                        $js .= ",params: {";
                            $js .= "cmd: 'jsonDeleteAllClassEventByDay'";
                            $js .= ",trainingId: '".$this->trainingId."'";
                            $js .= ",shortday: shortday";
                        $js .= "}";
                        $js .= ",success: function(response, options) {";
                            $js .= "Ext.getCmp('SCHEDULE_LIST_ID').store.load();";
                        $js .= "}";
                        $js .= ",failure: function(response, options) {}";
                    $js .= "});";
                $js .= "}";
            $js .= "}";
        $js .= "});";
    $js .= "}";
    
    $js .= "function jsCopyDayClassEvent(sourceshortday, targetshortday){";   
        $js .= "Ext.MessageBox.show({";
            $js .= "title:'".WARNING."'";
            $js .= ",width: 350";
            $js .= ",msg:'".MSG_WANT_PERFORM_ACTION."'";
            $js .= ",buttons: Ext.MessageBox.YESNO";
            $js .= ",icon: Ext.MessageBox.QUESTION";
            $js .= ",fn: function(btn, text){";
                $js .= "if (btn == 'yes'){";
                    $js .= "Ext.Ajax.request({";
                        $js .= "url: '/schedule/jsonsave/'";
                        $js .= ",method: 'POST'";
                        $js .= ",params: {";
                            $js .= "cmd: 'jsonCopyDayClassEvent'";
                            $js .= ",trainingId: '".$this->trainingId."'";
                            $js .= ",targetshortday: targetshortday";
                            $js .= ",sourceshortday: sourceshortday";
                        $js .= "}";
                        $js .= ",success: function(response, options) {";
                            $js .= "Ext.getCmp('SCHEDULE_LIST_ID').store.reload();";
                        $js .= "}";
                        $js .= ",failure: function(response, options) {}";
                    $js .= "});";
                $js .= "}";
            $js .= "}";
        $js .= "});";
    $js .= "}";
    
    print $js;
    ?>   
    Ext.onReady(function() {
        
        function styleTime(v, p, record, rowIndex){

            return String.format('<div style=\"font-weight:bold; padding: 10px; height: 65px; color:#333; background:#FFF;\">{0}</div>'
                ,v
            );
        }
    
        function cssMO(v, p, record, rowIndex){
            return String.format('<div style=\"white-space:normal; font-weight:bold; padding: 10px; height: 65px; background:{1};color:{2};\">{0}</div>'
                ,v
                ,record.data['MO_COLOR']
                ,record.data['MO_COLOR_FONT']
            );
        }
       
        function cssTU(v, p, record, rowIndex){
            return String.format('<div style=\"white-space:normal; font-weight:bold; padding: 10px; height: 65px; background:{1};color:{2};\">{0}</div>'
                ,v
                ,record.data['TU_COLOR']
                ,record.data['TU_COLOR_FONT']
            );
        }
        
        function cssWE(v, p, record, rowIndex){
            return String.format('<div style=\"white-space:normal; font-weight:bold; padding: 10px; height: 65px; background:{1};color:{2};\">{0}</div>'
                ,v
                ,record.data['WE_COLOR']
                ,record.data['WE_COLOR_FONT']
            );
        }
        
        function cssTH(v, p, record, rowIndex){
            return String.format('<div style=\"white-space:normal; font-weight:bold; padding: 10px; height: 65px; background:{1};color:{2};\">{0}</div>'
                ,v
                ,record.data['TH_COLOR']
                ,record.data['TH_COLOR_FONT']
            );
        }
        
        function cssFR(v, p, record, rowIndex){
            return String.format('<div style=\"white-space:normal; font-weight:bold; padding: 10px; height: 65px; background:{1};color:{2};\">{0}</div>'
                ,v
                ,record.data['FR_COLOR']
                ,record.data['FR_COLOR_FONT']
            );
        }
        
        function cssSA(v, p, record, rowIndex){
            return String.format('<div style=\"white-space:normal; font-weight:bold; padding: 10px; height: 65px; background:{1};color:{2};\">{0}</div>'
                ,v
                ,record.data['SA_COLOR']
                ,record.data['SA_COLOR_FONT']
            );
        }
        
        function cssSU(v, p, record, rowIndex){
            return String.format('<div style=\"white-space:normal; font-weight:bold; padding: 10px; height: 65px; background:{1};color:{2};\">{0}</div>'
                ,v
                ,record.data['SU_COLOR']
                ,record.data['SU_COLOR_FONT']
            );
        }
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $OBJECT_GRID->addReadField("name: 'ID'");
        $OBJECT_GRID->addReadField("name: 'MO_GUID'");
        $OBJECT_GRID->addReadField("name: 'TU_GUID'");
        $OBJECT_GRID->addReadField("name: 'WE_GUID'");
        $OBJECT_GRID->addReadField("name: 'TH_GUID'");
        $OBJECT_GRID->addReadField("name: 'FR_GUID'");
        $OBJECT_GRID->addReadField("name: 'SA_GUID'");
        $OBJECT_GRID->addReadField("name: 'SU_GUID'");
        $OBJECT_GRID->addReadField("name: 'TIME'");
        $OBJECT_GRID->addReadField("name: 'MO'");
        $OBJECT_GRID->addReadField("name: 'TU'");
        $OBJECT_GRID->addReadField("name: 'WE'");
        $OBJECT_GRID->addReadField("name: 'TH'");
        $OBJECT_GRID->addReadField("name: 'FR'");
        $OBJECT_GRID->addReadField("name: 'SA'");
        $OBJECT_GRID->addReadField("name: 'SU'");
        $OBJECT_GRID->addReadField("name: 'SCHEDULE_TYPE'");
        $OBJECT_GRID->addReadField("name: 'MO_COLOR'");
        $OBJECT_GRID->addReadField("name: 'TU_COLOR'");
        $OBJECT_GRID->addReadField("name: 'WE_COLOR'");
        $OBJECT_GRID->addReadField("name: 'TH_COLOR'");
        $OBJECT_GRID->addReadField("name: 'FR_COLOR'");
        $OBJECT_GRID->addReadField("name: 'SA_COLOR'");
        $OBJECT_GRID->addReadField("name: 'SU_COLOR'");
        $OBJECT_GRID->addReadField("name: 'MO_EVENT'");
        $OBJECT_GRID->addReadField("name: 'TU_EVENT'");
        $OBJECT_GRID->addReadField("name: 'WE_EVENT'");
        $OBJECT_GRID->addReadField("name: 'TH_EVENT'");
        $OBJECT_GRID->addReadField("name: 'FR_EVENT'");
        $OBJECT_GRID->addReadField("name: 'SA_EVENT'");
        $OBJECT_GRID->addReadField("name: 'SU_EVENT'");
        $OBJECT_GRID->addReadField("name: 'MO_COLOR_FONT'");
        $OBJECT_GRID->addReadField("name: 'TU_COLOR_FONT'");
        $OBJECT_GRID->addReadField("name: 'WE_COLOR_FONT'");
        $OBJECT_GRID->addReadField("name: 'TH_COLOR_FONT'");
        $OBJECT_GRID->addReadField("name: 'FR_COLOR_FONT'");
        $OBJECT_GRID->addReadField("name: 'SA_COLOR_FONT'");
        $OBJECT_GRID->addReadField("name: 'SU_COLOR_FONT'");
        $OBJECT_GRID->addReadField("name: 'CODE'");
        $OBJECT_GRID->addReadField("name: 'STATUS'");    

        $OBJECT_GRID->addColumn("
            header: '<b>" . TIME . "</b>'
            , align:'center'
            ,renderer: styleTime
            , sortable: false
            , dataIndex: 'TIME'
            , width: 120
        ");

        $OBJECT_GRID->addColumn("
            header: '<b>" . MONDAY . "</b>'
            ,renderer: cssMO
            , align:'center'
            , sortable: false
            , dataIndex: 'MO'
            , width: 180
        ");
        
        $OBJECT_GRID->addColumn("
            header: '<b>" . TUESDAY . "</b>'
            ,renderer: cssTU
            , align:'center'
            , sortable: false
            , dataIndex: 'TU'
            , width: 180
        ");
        
        $OBJECT_GRID->addColumn("
            header: '<b>" . WEDNESDAY . "</b>'
            ,renderer: cssWE
            , align:'center'
            , sortable: false
            , dataIndex: 'WE'
            , width: 180
        ");
        
        $OBJECT_GRID->addColumn("
            header: '<b>" . THURSDAY . "</b>'
            ,renderer: cssTH
            , align:'center'
            , sortable: false
            , dataIndex: 'TH'
            , width: 180
        ");
        
        $OBJECT_GRID->addColumn("
            header: '<b>" . FRIDAY . "</b>'
            ,renderer: cssFR
            , align:'center'
            , sortable: false
            , dataIndex: 'FR'
            , width: 180
        ");
        
        $OBJECT_GRID->addColumn("
            header: '<b>" . SATURDAY . "</b>'
            ,renderer: cssSA
            , align:'center'
            , sortable: false
            , dataIndex: 'SA'
            , width: 180
        ");
        
        $OBJECT_GRID->addColumn("
            header: '<b>" . SUNDAY . "</b>'
            ,renderer: cssSU
            , align:'center'
            , sortable: false
            , dataIndex: 'SU'
            , width: 180
        ");
        
        $OBJECT_GRID->baseParams = "
            start:0
            ,limit:100
            ,trainingId: '" . $this->trainingId . "'
            ,cmd: 'loadClassEvents'
            ,teacherId: '" . $this->teacherId . "'
            ,target: 'TRAINING'
        ";
        
        $HIDDEN_MO = $trainingObject->MO?"false":"true";
        $HIDDEN_TU = $trainingObject->TU?"false":"true";
        $HIDDEN_WE = $trainingObject->WE?"false":"true";
        $HIDDEN_TH = $trainingObject->TH?"false":"true";
        $HIDDEN_FR = $trainingObject->FR?"false":"true";
        $HIDDEN_SA = $trainingObject->SA?"false":"true";
        $HIDDEN_SU = $trainingObject->SU?"false":"true";
        
        $OBJECT_GRID->addTBarItems("
            tbar.add(['-',{
                id: 'REFRESH_ID'
                ,text: '".REFRESH."'
                ,iconCls:'icon-reload'
                ,scope:this
                ,disabled: false
                ,handler: function(){
                    Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
                }
            }]);
        ");
        
        if(UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT") || UserAuth::getACLValue("TRAINING_PROGRAMS_EDIT_RIGHT"))
        $OBJECT_GRID->addTBarItems("
            tbar.add(['-',{
                id: 'DAY'
                ,text: '".DAY."'
                ,disabled: false
                ,iconCls:'icon-list-items'
                ,menu:[{
                    text:'".MONDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_MO."
                    ,menu:[{
                        text:'".ADD_ENTRY."'
                        ,iconCls:'icon-application_form_add'
                        ,hidden:".$HIDDEN_MO."
                        ,handler:function(){
                            clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=new&trainingId=".$this->trainingId."&shortday=MO');  
                        }
                    },{
                        text:'".DELETE."'
                        ,iconCls:'icon-delete'
                        ,hidden:".$HIDDEN_MO."
                        ,handler:function(){
                            jsDeleteDayClassEvent('MO')
                        }
                    }]
                },{
                    text:'".TUESDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_TU."
                    ,menu:[{
                        text:'".ADD_ENTRY."'
                        ,iconCls:'icon-application_form_add'
                        ,hidden:".$HIDDEN_TU."
                        ,handler:function(){
                            clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=new&trainingId=".$this->trainingId."&shortday=TU');  
                        }
                    },{
                        text:'".DELETE."'
                        ,iconCls:'icon-delete'
                        ,hidden:".$HIDDEN_TU."
                        ,handler:function(){
                            jsDeleteDayClassEvent('TU')
                        }
                    }]
                },{
                    text:'".WEDNESDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_WE."
                    ,menu:[{
                        text:'".ADD_ENTRY."'
                        ,iconCls:'icon-application_form_add'
                        ,hidden:".$HIDDEN_WE."
                        ,handler:function(){
                            clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=new&trainingId=".$this->trainingId."&shortday=WE');  
                        }
                    },{
                        text:'".DELETE."'
                        ,iconCls:'icon-delete'
                        ,hidden:".$HIDDEN_WE."
                        ,handler:function(){
                            jsDeleteDayClassEvent('WE')
                        }
                    }]
                },{
                    text:'".THURSDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_TH."
                    ,menu:[{
                        text:'".ADD_ENTRY."'
                        ,iconCls:'icon-application_form_add'
                        ,hidden:".$HIDDEN_TH."
                        ,handler:function(){
                            clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=new&trainingId=".$this->trainingId."&shortday=TH');  
                        }
                    },{
                        text:'".DELETE."'
                        ,iconCls:'icon-delete'
                        ,hidden:".$HIDDEN_TH."
                        ,handler:function(){
                            jsDeleteDayClassEvent('TH')
                        }
                    }]
                },{
                    text:'".FRIDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_FR."
                    ,menu:[{
                        text:'".ADD_ENTRY."'
                        ,iconCls:'icon-application_form_add'
                        ,hidden:".$HIDDEN_FR."
                        ,handler:function(){
                            clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=new&trainingId=".$this->trainingId."&shortday=FR');  
                        }
                    },{
                        text:'".DELETE."'
                        ,iconCls:'icon-delete'
                        ,hidden:".$HIDDEN_FR."
                        ,handler:function(){
                            jsDeleteDayClassEvent('FR')
                        }
                    }]
                },{
                    text:'".SATURDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_SA."
                    ,menu:[{
                        text:'".ADD_ENTRY."'
                        ,iconCls:'icon-application_form_add'
                        ,hidden:".$HIDDEN_SA."
                        ,handler:function(){
                            clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=new&trainingId=".$this->trainingId."&shortday=SA');  
                        }
                    },{
                        text:'".DELETE."'
                        ,iconCls:'icon-delete'
                        ,hidden:".$HIDDEN_SA."
                        ,handler:function(){
                            jsDeleteDayClassEvent('SA')
                        }
                    }]
                },{
                    text:'".SUNDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_SU."
                    ,menu:[{
                        text:'".ADD_ENTRY."'
                        ,iconCls:'icon-application_form_add'
                        ,hidden:".$HIDDEN_SU."
                        ,handler:function(){
                            clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=new&trainingId=".$this->trainingId."&shortday=SU');  
                        }
                    },{
                        text:'".DELETE."'
                        ,iconCls:'icon-delete'
                        ,hidden:".$HIDDEN_SU."
                        ,handler:function(){
                            jsDeleteDayClassEvent('SU')
                        }
                    }]
                }]
            }]);
        ");
        
        if(UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT") || UserAuth::getACLValue("TRAINING_PROGRAMS_EDIT_RIGHT"))
        $OBJECT_GRID->addTBarItems("
            tbar.add(['-',{
                id: 'COPY'
                ,text: '".COPY."'
                ,disabled: false
                ,iconCls:'icon-list-items'
                ,menu:[{
                    text:'".TUESDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_TU."
                    ,menu:[{
                        text:'".COPY_FROM_MO."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('MO','TU');
                        }
                    }]
                },{
                    text:'".WEDNESDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_WE."
                    ,menu:[{
                        text:'".COPY_FROM_MO."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('MO','WE');    
                        }
                    },{
                        text:'".COPY_FROM_TU."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('TU','WE');        
                        }
                    }]
                },{
                    text:'".THURSDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_TH."
                    ,menu:[{
                        text:'".COPY_FROM_MO."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('MO','TH');    
                        }
                    },{
                        text:'".COPY_FROM_TU."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('TU','TH');        
                        }
                    },{
                        text:'".COPY_FROM_WE."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('WE','TH');        
                        }
                    }]
                },{
                    text:'".FRIDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_FR."
                    ,menu:[{
                        text:'".COPY_FROM_MO."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('MO','FR');    
                        }
                    },{
                        text:'".COPY_FROM_TU."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('TU','FR');        
                        }
                    },{
                        text:'".COPY_FROM_WE."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('WE','FR');        
                        }
                    },{
                        text:'".COPY_FROM_TH."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('TH','FR');        
                        }
                    }]
                },{
                    text:'".SATURDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_SA."
                    ,menu:[{
                        text:'".COPY_FROM_MO."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('MO','SA');    
                        }
                    },{
                        text:'".COPY_FROM_TU."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('TU','SA');        
                        }
                    },{
                        text:'".COPY_FROM_WE."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('WE','SA');        
                        }
                    },{
                        text:'".COPY_FROM_TH."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('TH','SA');        
                        }
                    },{
                        text:'".COPY_FROM_FR."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('FR','SA');        
                        }
                    }]
                },{
                    text:'".SUNDAY."'
                    ,iconCls:'icon-date'
                    ,hidden:".$HIDDEN_SU."
                    ,menu:[{
                        text:'".COPY_FROM_MO."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('MO','SU');    
                        }
                    },{
                        text:'".COPY_FROM_TU."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('TU','SU');        
                        }
                    },{
                        text:'".COPY_FROM_WE."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('WE','SU');        
                        }
                    },{
                        text:'".COPY_FROM_TH."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('TH','SU');        
                        }
                    },{
                        text:'".COPY_FROM_FR."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('FR','SU');        
                        }
                    },{
                        text:'".COPY_FROM_SA."'
                        ,iconCls:'icon-disk_multiple'
                        ,handler:function(){
                            jsCopyDayClassEvent('SA','SU');        
                        }
                    }]
                }]
            }]);
        ");
        
        ////////////////////////////////////////////////////////////////////////
        //EXPORT IN TO EXCEL...
        ////////////////////////////////////////////////////////////////////////
        switch(UserAuth::getUserType()){
            case "SUPERADMIN":
            case "ADMIN":
            case "TEACHER":
            case "INSTRUCTOR":
                $OBJECT_GRID->addTBarItems("
                    tbar.add(['->',{
                        text: '" . EXPORT_TO_EXCEL . "'
                        ,id: 'WEEK_EXPORT_TO_EXCEL'
                        ,iconCls:'icon-page_excel'
                        ,handler: function(){
                            Ext.MessageBox.show({
                                msg: '".SAVING_YOUR_DATA_PLEASE_WAIT."',
                                progressText: 'Saving...',
                                width:300,
                                wait:true,
                                waitConfig: {interval:200},
                                icon:'ext-mb-download'
                            });
                            Ext.Ajax.request({
                                url: '/export/jsonexcel/'
                                ,method: 'POST'
                                ,params:{cmd: 'loadClassEvents',camIds:'".$this->urlEncryp->encryptedGet($setParams)."'}
                                ,success: function(response, options) {
                                    Ext.MessageBox.hide();
                                    window.location='/export/openweekschedule/'
                                }
                            });
                        }
                    }]);        
                ");
            break;
        }

        $OBJECT_GRID->loadMask = false;
        $OBJECT_GRID->isObjectDefaultOnLoad = true;
        $OBJECT_GRID->forceFit = "false";
        $OBJECT_GRID->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'panel'
                ,id: 'content'
                ,border: true
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
                }]
            }]
        });
        var myGrid = <?=$OBJECT_GRID->ExtgetCmp();?>;
        <?
        
        if (!$trainingObject->MO) echo "myGrid.getColumnModel().setHidden(2, true);";
        if (!$trainingObject->TU) echo "myGrid.getColumnModel().setHidden(3, true);";
        if (!$trainingObject->WE) echo "myGrid.getColumnModel().setHidden(4, true);";
        if (!$trainingObject->TH) echo "myGrid.getColumnModel().setHidden(5, true);";
        if (!$trainingObject->FR) echo "myGrid.getColumnModel().setHidden(6, true);";
        if (!$trainingObject->SA) echo "myGrid.getColumnModel().setHidden(7, true);";
        if (!$trainingObject->SU) echo "myGrid.getColumnModel().setHidden(8, true);";
        
        $html = "";
        $html .= "if (myGrid) myGrid.on('cellclick', function(grid, rowIndex, columnIndex, event) {"; 
            $html .= "var record = grid.store.getAt(rowIndex);";
            $html .= "switch(columnIndex){";
                $html .= "case 2:";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".SHOW_DETAIL." &raquo; ' + record.data.MO_EVENT";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=' + record.data.MO_GUID + '&trainingId=".$this->trainingId."&shortday=MO');";        
                            $html .= "}";
                        $html .= "}]";
                    $html .= "});";
                    $html .= "if (record.data.MO_GUID){";
                        $html .= "event.stopEvent();";
                        $html .= "contextMenu.showAt(event.xy);";
                    $html .= "}"; 
                $html .= "break;";
                $html .= "case 3:";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".SHOW_DETAIL." &raquo; ' + record.data.TU_EVENT";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=' + record.data.TU_GUID + '&trainingId=".$this->trainingId."&shortday=TU');";        
                            $html .= "}";
                        $html .= "}]";
                    $html .= "});";
                    $html .= "if (record.data.TU_GUID){";
                        $html .= "event.stopEvent();";
                        $html .= "contextMenu.showAt(event.xy);";
                    $html .= "}";
                $html .= "break;";
                $html .= "case 4:";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".SHOW_DETAIL." &raquo; ' + record.data.WE_EVENT";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=' + record.data.WE_GUID + '&trainingId=".$this->trainingId."&shortday=WE');";        
                            $html .= "}";
                        $html .= "}]";
                    $html .= "});";
                    $html .= "if (record.data.WE_GUID){";
                        $html .= "event.stopEvent();";
                        $html .= "contextMenu.showAt(event.xy);";
                    $html .= "}"; 
                $html .= "break;";
                $html .= "case 5:";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".SHOW_DETAIL." &raquo; ' + record.data.TH_EVENT";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "if (record.data.TH_GUID) clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=' + record.data.TH_GUID + '&trainingId=".$this->trainingId."&shortday=TH');";        
                            $html .= "}";
                        $html .= "}]";
                    $html .= "});";
                    $html .= "if (record.data.TH_GUID){";
                        $html .= "event.stopEvent();";
                        $html .= "contextMenu.showAt(event.xy);";
                    $html .= "}"; 
                $html .= "break;";
                $html .= "case 6:";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".SHOW_DETAIL." &raquo; ' + record.data.FR_EVENT";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "if (record.data.FR_GUID) clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=' + record.data.FR_GUID + '&trainingId=".$this->trainingId."&shortday=FR');";       
                            $html .= "}";
                        $html .= "}]";
                    $html .= "});";
                    $html .= "if (record.data.FR_GUID){";
                        $html .= "event.stopEvent();";
                        $html .= "contextMenu.showAt(event.xy);";
                    $html .= "}";
                $html .= "break;";
                $html .= "case 7:";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".SHOW_DETAIL." &raquo; ' + record.data.SA_EVENT";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=' + record.data.SA_GUID + '&trainingId=".$this->trainingId."&shortday=SA');";        
                            $html .= "}";
                        $html .= "}]";
                    $html .= "});";
                    $html .= "if (record.data.SA_GUID){";
                        $html .= "event.stopEvent();";
                        $html .= "contextMenu.showAt(event.xy);";
                    $html .= "}";  
                $html .= "break;";
                $html .= "case 8:";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".SHOW_DETAIL." &raquo; ' + record.data.SU_EVENT";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "if (record.data.SU_GUID) clickOpenPage('content','', '/schedule/showclassevent/?scheduleId=' + record.data.SU_GUID + '&trainingId=".$this->trainingId."&shortday=SU');";        
                            $html .= "}";
                        $html .= "}]";
                    $html .= "});";
                    $html .= "if (record.data.SU_GUID){";
                        $html .= "event.stopEvent();";
                        $html .= "contextMenu.showAt(event.xy);";
                    $html .= "}"; 
                $html .= "break;";
            $html .= "}";
        $html .= "})";
        if(UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT") || UserAuth::getACLValue("TRAINING_PROGRAMS_EDIT_RIGHT"))
        print $html;
        ?>
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>