<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("ATTENDANCE");
$OBJECT_FORM->setLoadUrl('/attendance/jsonload/');
$OBJECT_FORM->setSaveUrl('/attendance/jsonsave/');

$TRAINING_TREE = new CamemisTree("TRAINING","LIST");
$TRAINING_TREE->setURL('/training/jsontree/');
$TRAINING_TREE->setSaveUrl('/training/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $TRAINING_TREE->isAsyncTreeNode = false;
        $TRAINING_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $TRAINING_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $TRAINING_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());

        $TRAINING_TREE->setBaseParams("
            cmd: 'jsonTreeAllTrainings'
            ,children:'TERM'  
        ");
        $TRAINING_TREE->backgroundColor = "#F9F9F9";
        $TRAINING_TREE->isTreeExpand = false;
        $TRAINING_TREE->renderJS();
        $triggerOnClickTraining = "
            openWinXType('XTYPE_TRAINING','".TRAINING_PROGRAMS."', '".$TRAINING_TREE->getObjectXType()."', 500, percentHeight(85));
            var trainingTree = Ext.getCmp('".$TRAINING_TREE->getObjectId()."');
            trainingTree.getRootNode().expand(true, false);    
            trainingTree.on('click', function(node, e){   
                Ext.getCmp('CHOOSE_TRAINING').setValue('');
                if(node.attributes.objecttype == 'TERM'){
                    //////////////////////////
                    //Choose Term
                    //////////////////////////
                    if(node.attributes.objecttype == 'TERM'){
                        Ext.getCmp('CHOOSE_TRAINING').setValue(node.id);
                        Ext.getCmp('CHOOSE_GRADE_NAME_ID').setValue(node.text);
                    }
                    Ext.getCmp('XTYPE_TRAINING').close();                
                }
            });
         ";
        
        $OBJECT_FORM->addObjectItems("
            xtype:'fieldset'
            ,collapsible:true,collapsed:false
            ,title: '".DETAIL_INFORMATION."'
            ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; padding:10px'
            ,width: 250
            ,items:[
                {".CamemisField::Textfield("CODE", "CODE", SHORT." (FEE-)", false, false, false, 200)."}
                ,{".CamemisField::Textfield("NAME", "NAME", FEE_NAME, false, false, false, 200)."}
                ,{".CamemisField::Trigger("CHOOSE_GRADE_NAME",TRAINING_PROGRAMS,$triggerOnClickTraining,false, false, false, 200)."}
            ]
        ");
        //Hidden Field campus
        $OBJECT_FORM->addObjectItems(CamemisField::Hidden("CHOOSE_TRAINING",false));
        $OBJECT_FORM->addTBarItems("
            text: '".RESET."'
            ,iconCls:'icon-arrow_undo'
            ,scope:this
            ,handler: function(){".CamemisPage::setRequestURI()."}
        ");
        
        $FINANCIAL_MANAGEMENT_READ_RIGHT = UserAuth::getACLValue("FINANCIAL_MANAGEMENT_READ_RIGHT")?"false":"true";
        $OBJECT_FORM->addTBarItems("
            text: '".FIND."'
            ,hidden: ".$FINANCIAL_MANAGEMENT_READ_RIGHT."
            ,formBind:true
            ,iconCls:'icon-magnifier'
            ,scope:this
            ,handler:function(){
                name = this.getForm().findField('NAME').getValue();
                code = this.getForm().findField('CODE').getValue();
                trainingId = this.getForm().findField('CHOOSE_TRAINING').getValue();
                searchString = 'name=' + name
                + '&code=' + code
                + '&trainingId=' + trainingId
                clickOpenPage('center','', '/finance/searchfeecourse/?' + searchString);
                Ext.getCmp('WEST_ID').collapse();
            }
        ");
        if( UserAuth::getACLValue("FINANCIAL_MANAGEMENT_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems("
            text: '".ADD_NEW_ITEM."'
            ,iconCls:'icon-application_form_add'
            ,scope:this
            ,handler: function(){
                Ext.getCmp('WEST_ID').collapse();
                clickOpenPage('center','', '/finance/showfeecourse/?objectId=new');
            }
        ");
        
        $OBJECT_FORM->setBodyStyle("padding:10px;background:".CamemisPage::userFormBgColor().";");
        $OBJECT_FORM->labelAlign = "top";
        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->isKeys = true;
        $OBJECT_FORM->renderJS();

        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout: 'fit'
                ,border: false
                ,id: 'CONTENT'
                ,items:[{
                    layout:'border'
                    ,border: false
                    ,defaults: {
                        collapsible: true
                        ,split: true
                    }
                    ,items: [{
                        title: '<?=TRAINING_PROGRAMS;?>'
                        ,region:'west'
                        ,id: 'WEST_ID'
                        ,margins: '3 0 3 3'
                        ,cmargins: '3 3 3 3'
                        ,width: 270
                        ,minSize: 270
                        ,maxSize: 270
                        ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                    },{
                        title: ''
                        ,collapsible: false
                        ,id: 'center'
                        ,region:'center'
                        ,layout: 'card'
                        ,activeItem: 0
                        ,margins: '3 3 3 0'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'URL_SEARCH', url: '/finance/searchfeecourse/'})]
                    }]
                }]
            }]
        });
        
        //Ext.getCmp('WEST_ID').toggleCollapse(true);
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>