<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 19.02.2012
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("DASHBOARD");
$OBJECT_FORM->setLoadUrl("/student/jsonload/");
$OBJECT_FORM->setSaveUrl("/student/jsonsave/");

$SCHOLARSHIP_TREE = new CamemisTree("SCHOLARSHIP", "LIST");
$SCHOLARSHIP_TREE->setURL('/dataset/jsontree/');

$classObject = AcademicDBAccess::findGradeFromId($this->academicId);

if(!$classObject){
    header("Location: /main/permission/");
}

switch(UserAuth::getUserType()){
    case "SUPERADMIN":
    case "ADMIN":
        $hasRight = true;
        break;
    default:
        $hasRight = false;
        break;
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
         
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $SCHOLARSHIP_TREE->isAsyncTreeNode = false;
        $SCHOLARSHIP_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $SCHOLARSHIP_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $SCHOLARSHIP_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());

        $SCHOLARSHIP_TREE->setBaseParams("
            cmd: 'jsonTreeAllScholarship'
        ");

        $SCHOLARSHIP_TREE->backgroundColor = "#F9F9F9";
        $SCHOLARSHIP_TREE->isTreeExpand = true;
        $SCHOLARSHIP_TREE->isOnClickContextMenu = false;
        $SCHOLARSHIP_TREE->renderJS();

        ////////////////////////////////////////////////////////////////////////
        $DETAIL_INFORMATION = "
        {
            title: '".NAME."'
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#E0FFFF;padding:10px'
                ,items: [
                    {".CamemisField::Displayfield("CODE", CODE_ID)."}
                    ,{".CamemisField::Displayfield("NAME", NAME)."}
                ]
            }]
        }
        ";
        
        $TBAR_SCHOLARSHIP = "['->',";
        $TBAR_SCHOLARSHIP .= "'-',{
            text:'".SCHOLARSHIP."'
            ,iconCls:'icon-zoom'
            ,disabled:true
        }";
        
        switch(UserAuth::getUserType()){
            case "SUPERADMIN":
            case "ADMIN":
                $TBAR_SCHOLARSHIP .= ",'-',{
                    text:'".REMOVE."'
                    ,iconCls:'icon-delete'
                    ,handler:function(){
                        Ext.getCmp('SCHOLARSHIP_NAME_ID').setValue('---');
                        Ext.getCmp('SCHOLARSHIP_ID').setValue('---');
                    }
                }";
                $TBAR_SCHOLARSHIP .= ",'-',{
                    text:'".ADD_ENTRY."'
                    ,iconCls:'icon-lightning_add'
                    ,handler:function(){
                        openWinXType('SCHOLARSHIP','".SCHOLARSHIP."', '".$SCHOLARSHIP_TREE->getObjectXType()."', 500, percentHeight(85));
                        var subjectTree = Ext.getCmp('".$SCHOLARSHIP_TREE->getObjectId()."');
                        subjectTree.on('click', function(node, e){
                            if(node.isLeaf()){
                                Ext.getCmp('SCHOLARSHIP_NAME_ID').setValue(node.text);
                                Ext.getCmp('SCHOLARSHIP_ID').setValue(node.id);
                                Ext.getCmp('SCHOLARSHIP').close(); 
                            }        
                        });
                    }
                }";
            break;
        }
        
        $TBAR_SCHOLARSHIP .= "]";
        $SCHOLARSHIP_INFO = "
        {
            title: '".SCHOLARSHIP."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,tbar:".$TBAR_SCHOLARSHIP."
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {".CamemisField::Displayfield("SCHOLARSHIP_NAME", NAME)."}
                    ,{".CamemisField::Hidden("SCHOLARSHIP_ID",false)."}   
                ]
            }]
        }
        ";
        
        $WORKING_DAYS = "
        {
            title: '".WORKING_DAYS."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,autoHeight: true
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#E0FFFF;padding:10px'
                ,items: [
                    {".CamemisField::Displayfield("SHOW_MO", MONDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_TU", TUESDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_WE", WEDNESDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_TH", THURSDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_FR", FRIDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_SA", SATURDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_SU", SUNDAY)."}
                ]
            }]
        }
        ";
        
        $PENEL_ITEMS=array();
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        
        $DISPLAY_ITEMS = Array();
        $SHOW_ITEMS = "[";
        if (Utiles::studentAcademicDisplayFields($this->objectId,$classObject->GUID)) 
            $SHOW_ITEMS .= Utiles::studentAcademicDisplayFields($this->objectId, $classObject->GUID);
        $SHOW_ITEMS .= "]";
        ////////////////////////////////////////////////////////////////////////
        
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: [
                ".$DETAIL_INFORMATION."
                ,".$SCHOLARSHIP_INFO."
                ,".$SHOW_ITEMS."
                ,".$WORKING_DAYS."
            ]
        ";
        $OBJECT_FORM->addObjectItems($items);
        $OBJECT_FORM->setLoadParams("
            cmd: 'jsonStudentAcademicTraditional'
            ,academicId: '".$classObject->GUID."'
            ,objectId: '".$this->objectId."'
            ,schoolyearId:'".$this->schoolyearId."'
        ");
        
        if ($hasRight){
            $OBJECT_FORM->setSaveParams("
                cmd: 'jsonActionStudentAcademicTraditional'
                ,academicId: '".$classObject->GUID."'
                ,objectId: '".$this->objectId."'
                ,schoolyearId:'".$this->schoolyearId."'
            ");
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            ");
        }
        
        $OBJECT_FORM->isObjectDefaultOnLoad = true;
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>