<?php
    ///////////////////////////////////////////////////////////
    // @sor veasna
    // Date: 12/17/2012
    // Adress
    ///////////////////////////////////////////////////////////
    require_once 'excel/phpexcel/Classes/PHPExcel.php';
    require_once 'excel/phpexcel/Classes/PHPExcel/IOFactory.php';
    require_once 'clients/CamemisExcelReport.php';
    require_once 'clients/CamemisExportToExcel.php';
    require_once 'models/app_school/examination/ExaminationDBAccess.php';
    require_once 'models/app_school/examination/StudentExaminationDBAccess.php';
    require_once 'models/app_school/subject/SubjectDBAccess.php'; 
    require_once 'models/app_school/academic/AcademicDBAccess.php';
    require_once 'models/app_school/student/StudentImportDBAccess.php';
    require_once 'models/app_school/examination/StaffExaminationDBAccess.php';
    require_once 'models/app_school/AcademicDateDBAccess.php';
    require_once 'models/app_school/room/RoomDBAccess.php';
    
    $objectId = isset($_GET["objectId"]) ? addText($_GET["objectId"]) : "";
    $bnt=isset($_GET["bnt"])?$_GET["bnt"]:"";
    $header=false;
    $footer=false;
    $exportToExcel=new CamemisExportToExcel();
    
    //school information
    $schoolObject = $exportToExcel->getSchoolInfo();
    $SchoolName = $schoolObject->NAME;
    $SchoolAdress=$schoolObject->ADDRESS;
    $schoolInfo= $SchoolName."\n".$SchoolAdress;
    $facette='';
    $char=array("A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","AA","AB","AC","AD","AE","AF","AG","AH","AI",'AJ',"AK","AL","AM","AN","AO","AP","AQ","AR","AS","AT","AU","AV","AW","AY","AZ");
    
    $filds=array();
    $entries = array();
    $filds[0] = "NA";
    $showfilds[0] = "N°";
    $i = 1;
    $j = 0;
    
    
    switch ($bnt) {
        case "1": 
                ////
                //Exam Object   
                $acdemicId=isset($_GET["academicId"])? (int) $_GET["academicId"]:'';
                $academicObject='';
                if($acdemicId){
                    $academicObject = AcademicDBAccess::findGradeFromId($acdemicId);
                }
                
                $facette = ExaminationDBAccess::findExamFromId($objectId);
                
                if (!$facette) {header("Location: /main/permission/");}
                if($facette){
                  
                    $exam=EXAM.": ".$facette->NAME;
                    $startDate=START_DATE.': '.$facette->START_DATE;
                    $examTime=START_END_TIME.': '.$facette->START_TIME.' - '.$facette->END_TIME;   
                    //study year
                    $subjectObject=SubjectDBAccess::findSubjectFromId($facette->SUBJECT_ID);
                    $subject=SUBJECT.": ".$subjectObject->NAME;
                    //room
                    $classInfo='';
                    if($facette->ROOM_ID){
                        $roomObject=RoomDBAccess::findRoomFromId($facette->ROOM_ID);
                        $classInfo=ROOM.': '.$roomObject->NAME; 
                    } 
                    //exam info
                    $examinfo=$classInfo."\n".$exam."\n".$subject."\n".$startDate."\n".$examTime; 
                    if($facette->PARENT){//have parents or chile room
                        $parentObject = ExaminationDBAccess::findExamParentFromId($objectId);   
                        $params["objectId"] =  $parentObject->GUID;
                        $params["roomId"]= $facette->ROOM_ID;
                        $results = StudentExaminationDBAccess::getQueryAssignedStudentTmpExamination($params);   
                    }else{//parents all students

                        $params["objectId"] = $facette->GUID; 
                        $results = StudentExaminationDBAccess::getQueryAssignedStudentTmpExamination($params,false);  
                                     
                    }
                }
                ///
                $filename="List Of Students Results"; 
                $STUDENT = array('CANDIDATE_CODE', 'FULL_NAME', 'FIRSTNAME', 'LASTNAME', 'LASTNAME_LATIN', 'FIRSTNAME_LATIN','GENDER','ROOM','EXAM_RESULT', 'DATE_BIRTH', 'PHONE', 'EMAIL','SIGNATURE_STUDENT_SUBMISSION','HEAD_NAME','SIGNATURE');              
                $STUDENT_RESULT_FILDS = array(
                                'CANDIDATE_CODE'=>'STUDENT_CODE'
                                , 'FULL_NAME'=>'FULL_NAME'
                                , 'FIRSTNAME'=>'FIRSTNAME'
                                , 'LASTNAME'=>'LASTNAME'
                                , 'LASTNAME_LATIN'=>'LASTNAME_LATIN'
                                , 'FIRSTNAME_LATIN'=>'FIRSTNAME_LATIN'
                                , 'GENDER'=>'GENDER'
                                , 'DATE_BIRTH'=>'DATE_BIRTH'
                                , 'PHONE'=>'PHONE'
                                , 'EMAIL'=>'EMAIL'
                                , 'ROOM'=>'ROOM_NAME'
                                , 'EXAM_RESULT'=>'POINTS'
                                , 'SIGNATURE_STUDENT_SUBMISSION'=>'SIGNATURE_STUDENT_SUBMISSION'
                );
                
                
                foreach ($STUDENT as $index) {
                    $CHECK = isset($_GET[$index]) ? $_GET[$index] : 0;
                    if ($CHECK) {
                       switch ($index){                                        
                            case 'HEAD_NAME':
                                $header=true;          
                            break;
                            case 'SIGNATURE':
                                $footer=true;          
                            break;
                            default:
                                $filds[$i] = $STUDENT_RESULT_FILDS[$index];
                                $showfilds[$i] = defined($index) ? constant($index) : $index; 
                                ++$i;
                            break;
                       }
                       
                    }
                    $j++;
                }                
                
                $endCharExcel = $char[$i - 1];
                if($header){
                    $exportToExcel->objExcel($results,$filds,$showfilds,3);
                    $info['SCHOOL_INFO']=$schoolInfo;
                    $info['CLASS_INFO']='';
                    if($academicObject){
                        $campusInfo=explode("&raquo;",$academicObject->TITLE);
                        
                        $info['CLASS_INFO'].=CAMPUS_INFORMATION.': '.$campusInfo[0]."\n";
                        $info['CLASS_INFO'].=GRADE.': '.$campusInfo[1]."\n";
                        $info['CLASS_INFO'].=ACADEMIC_DATE.': '.$campusInfo[2]."\n";
                    }
                    $info['CLASS_INFO'].=$examinfo; 
                    $exportToExcel->excelHeader($info,1,$endCharExcel);
                }else{
                    $exportToExcel->objExcel($results,$filds,$showfilds,1);        
                }
               
                if($footer){
                     $exportToExcel->excelFooter();    
                }   
            break;
                 
        case "5":///studnet enrollment exam result
           ///filds result
           $filename="List Of Students";
           $STUDENT = array('CANDIDATE_CODE', 'FULL_NAME', 'FIRSTNAME', 'LASTNAME', 'LASTNAME_LATIN', 'FIRSTNAME_LATIN', 'GENDER', 'DATE_BIRTH', 'PHONE', 'EMAIL','SUBJECT','AVERAGE','EXAM_RESULT','HEAD_NAME','SIGNATURE','SIGNATURE_STUDENT_SUBMISSION');
           $STUDENT_RESULT_FILDS = array(
                            'CANDIDATE_CODE'=>'STUDENT_SCHOOL_ID'
                            , 'FULL_NAME'=>'FULL_NAME'
                            , 'FIRSTNAME'=>'FIRSTNAME'
                            , 'LASTNAME'=>'LASTNAME'
                            , 'LASTNAME_LATIN'=>'LASTNAME_LATIN'
                            , 'FIRSTNAME_LATIN'=>'FIRSTNAME_LATIN'
                            , 'GENDER'=>'GENDER'
                            , 'DATE_BIRTH'=>'DATE_BIRTH'
                            , 'PHONE'=>'PHONE'
                            , 'EMAIL'=>'EMAIL'
                            , 'AVERAGE'=>'ENROLL_AVG'
                            , 'EXAM_RESULT'=>'RESULT'
                            , 'SIGNATURE_STUDENT_SUBMISSION'=>'SIGNATURE_STUDENT_SUBMISSION'
                            );
            
            $myParams=array();
            $myParams["type"]=isset($_GET["enrollExamType"]) ? $_GET["enrollExamType"] : "";
            $myParams["objectType"]=isset($_GET["objectType"]) ? addText($_GET["objectType"]) : "";
            $myParams["campus"]=isset($_GET["campus"]) ? $_GET["campus"] : "";
            $myParams["gender"]=isset($_GET["gender"]) ? $_GET["gender"] : "";
            $myParams["examResult"]=isset($_GET["examResult"]) ? $_GET["examResult"] : "";
            if($myParams["campus"]){
                $academicObject = AcademicDBAccess::findGradeFromId($myParams["campus"]);   
            }
            ////subject of exam
            
            $arr["type"]=6;
            $arr["schoolyearId"]=$academicObject->SCHOOL_YEAR;
            $arr["gradeId"]=$academicObject->GRADE_ID;
            $subjectExam=ExaminationDBAccess::getSQLExamination($arr);
            
            //// resultset
            
            $studentImport=new StudentImportDBAccess();
       
            $results=$studentImport->importStudents($myParams,false);
            if (!$results) 
            exit;
    
            foreach ($STUDENT as $index) {
                $CHECK = isset($_GET[$index]) ? $_GET[$index] : 0;
                if ($CHECK) {
                   switch ($index){                                        
                        case 'SUBJECT':
                            foreach ($subjectExam as $subject){
                                $filds[$i] = $subject->EXM_ID;
                                $showfilds[$i] = $subject->SUBJECT_NAME; 
                                ++$i;            
                            }        
                        break;
                        case 'HEAD_NAME':
                            $header=true;          
                        break;
                        case 'SIGNATURE':
                            $footer=true;          
                        break;
                        default:
                            $filds[$i] = $STUDENT_RESULT_FILDS[$index];
                            $showfilds[$i] = defined($index) ? constant($index) : $index; 
                            ++$i;
                        break;
                   }
                   
                }
                $j++;
            }
            
            $endCharExcel = $char[$i - 1];   
            /// control header and footer
            if($header){
                $exportToExcel->objExcel($results,$filds,$showfilds,3);
                   
                $info['SCHOOL_INFO']=$schoolInfo;
                $info['CLASS_INFO']='';
                if($academicObject){
                    $campusInfo=explode("&raquo;",$academicObject->TITLE);
                    $info['CLASS_INFO'].=CAMPUS_INFORMATION.': '.$campusInfo[0]."\n";
                    $info['CLASS_INFO'].=GRADE.': '.$campusInfo[1]."\n";
                    $info['CLASS_INFO'].=ACADEMIC_DATE.': '.$campusInfo[2]."\n"; 
                }
                $info['CLASS_INFO'].=EXAM.': '.$results[0]['ENROLL_EXAM_NAME']; 
                $exportToExcel->excelHeader($info,1,$endCharExcel); 
            }else{
                $exportToExcel->objExcel($results,$filds,$showfilds,1);    
            }
            if($footer){
                 $exportToExcel->excelFooter();    
            }
            /////////////////////////////////////
            
            break;
            

    } 
    $exportToExcel->save($filename);

?>

