<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 03.03.2012
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTrainingTree.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTrainingTree("TRAINING","LIST");
$OBJECT_TREE->setURL("/training/jsontree/");
$OBJECT_TREE->setSaveUrl("/training/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    
    var choosedate = '<?=date('m-d-Y');?>';
    Ext.onReady(function() {
        var tabs =  new Ext.TabPanel({
            autoTabs:true
            ,border:false
            ,tabPosition: 'top'
            ,enableTabScroll:true
            ,activeTab:0
            ,items:[{
                title: '&nbsp;'
                ,id: 'TAB_DEFAULT'
                ,layout: 'fit'
                ,items: [{
                    layout:'anchor'
                    ,border:false
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items:[{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class=\"header\"><?=PLEASE_MAKE_YOUR_SELECTIONS?></h1>'    
                    }]
                }]
            }]
        });
        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $CAMEMIS_PAGE_OBJECT->setAddTab();
        
        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        if (UserAuth::getACLValue("ACADEMIC_TRAINING_PROGRAMS_EDIT_RIGHT"))
        $OBJECT_TREE->addTBarItems("
            id: 'ADD_PROGRAM_ID' 
            ,tooltip:'".PROGRAM."'
            ,scope:this
            ,iconCls:'icon-application_form_add'
            ,handler: function() {
                 clickOpenPage('center', '".PROGRAM."', '/training/addprogram/?template=PROGRAM');
            }
        ");
        
        $OBJECT_TREE->addTBarItems("
            xtype: 'buttongroup'
            ,items:[{
                xtype:'datefield'
                ,format: '" . setExtDatafieldFormat() . "'
                ,width:120
                ,name:'choosedate'
                ,value:'".getShowDate(date('d-m-Y'))."'
                ,listeners: {
                    'select' : function(dp, date) {
                        myTree = ".$OBJECT_TREE->ExtgetCmp().";
                        myTree.loader.baseParams.choosedate = date.format('Y-m-j');
                        myTree.root.reload();
                    }
                }
            }]
        ");
        
        $OBJECT_TREE->setBaseParams("
            cmd: 'jsonTreeAllTrainings'
            ,choosedate:choosedate
        ");
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isTreeExpand = false;
        $OBJECT_TREE->renderJS();
        ?>
        
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    region:'west'
                    ,id: 'WEST_ID'
                    ,title: '&nbsp;'
                    ,autoScroll: true
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width:350
                    ,minSize:350
                    ,maxSize:350
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                },{
                    collapsible: false
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,bodyStyle: 'padding:1px'
                    ,items:tabs
                }]
            }]
        });
        
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node, event){
            <?
            $html = "";
            $html .= "switch(node.attributes.objecttype){";
                $html .= "case 'PROGRAM':";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".EXPAND."'";
                            $html .= ",iconCls: 'icon-expand-all'";
                            $html .= ",handler: function(){";
                                $html .= "myNode = myTree.getNodeById(node.id);";
                                $html .= "myNode.reload();";
                                $html .= "myNode.expand(true, false);";
                            $html .= "}"; 
                            
                        $html .= "},{"; 
                            $html .= "text: '".COLLAPSE."'";
                            $html .= ",iconCls: 'icon-collapse-all'";
                            $html .= ",handler: function(){";
                                $html .= "myNode = myTree.getNodeById(node.id);";
                                $html .= "myNode.collapse(true, false);";
                            $html .= "}";  
                            
                        $html .= "},{"; 
                        $html .= "text: '".MAIN_CONTENT."'";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','".$this->URL_PROGRAM."objectId=' + node.id);";
                            $html .= "}";  
                        $html .= "}]"; 
                    $html .= "});";
                $html .= "break;";
                $html .= "case 'LEVEL':";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".EXPAND."'";
                            $html .= ",iconCls: 'icon-expand-all'";
                            $html .= ",handler: function(){";
                                $html .= "myNode = myTree.getNodeById(node.id);";
                                $html .= "myNode.reload();";
                                $html .= "myNode.expand(true, false);";
                            $html .= "}";  
                            
                        $html .= "},{"; 
                            $html .= "text: '".COLLAPSE."'";
                            $html .= ",iconCls: 'icon-collapse-all'";
                            $html .= ",handler: function(){";
                                $html .= "myNode = myTree.getNodeById(node.id);";
                                $html .= "myNode.collapse(true, false);";
                            $html .= "}";  
                            
                        $html .= "},{";  
                        $html .= "text: '".MAIN_CONTENT."'";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','".$this->URL_LEVEL."objectId=' + node.id);";
                            $html .= "}"; 
                            
                        $html .= "}]"; 
                    $html .= "});";
                $html .= "break;";
                $html .= "case 'TERM':";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".EXPAND."'";
                            $html .= ",iconCls: 'icon-expand-all'";
                            $html .= ",handler: function(){";
                                $html .= "myNode = myTree.getNodeById(node.id);";
                                $html .= "myNode.reload();";
                                $html .= "myNode.expand(true, false);";
                            $html .= "}";  
                            
                        $html .= "},{"; 
                            $html .= "text: '".COLLAPSE."'";
                            $html .= ",iconCls: 'icon-collapse-all'";
                            $html .= ",handler: function(){";
                                $html .= "myNode = myTree.getNodeById(node.id);";
                                $html .= "myNode.collapse(true, false);";
                            $html .= "}";  
                            
                        $html .= "},{"; 
                        $html .= "text: '".MAIN_CONTENT."'";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','".$this->URL_TERM."objectId=' + node.id);";
                            $html .= "}";
                            
                        $html .= "},{"; 
                        $html .= "text: '".SUBJECT_AND_ASSIGNMENT."'";
                            $html .= ",iconCls: 'icon-flag_blue'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center',node.text + ' &raquo; ".SUBJECT_AND_ASSIGNMENT."','/training/subjectlist/?target=TERM&objectId=' + node.id);";
                            $html .= "}"; 
                            
                        $html .= "},{"; 
                        $html .= "text: '".ENROLLED_STUDENTS."'";
                            $html .= ",iconCls: 'icon-group'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/training/studentlist/?target=TERM&objectId=' + node.id);";
                            $html .= "}";  
                            
                        $html .= "},{"; 
                        $html .= "text: '".ASSIGNED_TEACHERS."'";
                            $html .= ",iconCls: 'icon-group'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/training/teacherlist/?objectId=' + node.id);";
                            $html .= "}";  
                        $html .= "}]"; 
                    $html .= "});";
                $html .= "break;";
                $html .= "case 'CLASS':";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                        $html .= "text: '".DETAILS."'";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','".$this->URL_CLASS."objectId=' + node.id);";
                            $html .= "}";
                            
                        $html .= "},{"; 
                        $html .= "text: '".SUBJECT_AND_ASSIGNMENT."'";
                            $html .= ",iconCls: 'icon-flag_blue'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center',node.text + ' &raquo; ".SUBJECT_AND_ASSIGNMENT."','/training/subjectlist/?target=TERM&objectId=' + node.id);";
                            $html .= "}";
                            
                        $html .= "},{"; 
                        $html .= "text: '".ENROLLED_STUDENTS."'";
                            $html .= ",iconCls: 'icon-group'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/training/studentlist/?target=TERM&objectId=' + node.id);";
                            $html .= "}";
                            
                        $html .= "},{"; 
                        $html .= "text: '".ASSIGNED_TEACHERS."'";
                            $html .= ",iconCls: 'icon-group'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/training/teacherlist/?objectId=' + node.id);";
                            $html .= "}"; 
                        $html .= "},{"; 
                        $html .= "text: '".SCHEDULE."'";
                            $html .= ",iconCls: 'icon-date'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/schedule/byclass/?target=TRAINING&trainingId=' + node.id);";
                            $html .= "}";   
                        $html .= "},{"; 
                        $html .= "text: '".ASSESSMENT."'";
                            $html .= ",iconCls: 'icon-wand'"; 
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/training/trainingassessment/?objectId=' + node.id);";
                            $html .= "}";
                       $html .= "},{"; 
                        $html .= "text: '".TEACHER_ENTER_SCORE."'";
                            $html .= ",iconCls: 'icon-table_gear'"; 
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/training/scoremonitortraining/?classId=' + node.id);";
                            $html .= "}"; 
                        $html .= "},{"; 
                        $html .= "text: '".LIST_OF_ATTENDANCE."'";
                            $html .= ",iconCls: 'icon-date-time'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/attendance/studentclassmain/?target=training&trainingId=' + node.id);";
                            $html .= "}";
                        $html .= "}]"; 
                    $html .= "});";
                $html .= "break;";
            $html .= "}";
            $html .= "event.stopEvent();";
            $html .= "contextMenu.showAt(event.xy);";
            
            echo $html;
            ?>
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>