<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTrainingTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTrainingTree("TRAINING","LIST");
$OBJECT_TREE->setURL("/training/jsontree/");
$OBJECT_TREE->setSaveUrl("/training/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>

<script>
    var choosedate = '<?=date('m-d-Y');?>';
    Ext.onReady(function() {

        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        $OBJECT_TREE->addTBarItems("
            xtype: 'buttongroup'
            ,items:[{
                xtype:'textfield'
                ,width:120
                ,value:'".getShowDate(date('d.m.Y'))."'
                ,emptyText:'".getSystemDateFormat()."'
                ,listeners: {
                    specialkey: function(f,e){
                        if (e.getKey() == e.ENTER) {
                            myTree = ".$OBJECT_TREE->ExtgetCmp().";
                            myTree.loader.baseParams.choosedate = this.getValue();
                            myTree.root.reload();
                        }
                    }
                }
            }]
        ");
        
        $OBJECT_TREE->setBaseParams("
            cmd: 'jsonTreeAllTrainings'
            ,choosedate:choosedate
        ");
        
        $OBJECT_TREE->isOnClickContextMenu = false;
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isTreeExpand = false;
        $OBJECT_TREE->renderJS();

        $js = "";
        $js .= "viewport = new Ext.Viewport({";
            $js .= "layout: 'fit'";
            $js .= ",border: false";
            $js .= ",items:[{";
                $js .= "layout:'border'";
                $js .= ",border: false";
                $js .= ",defaults: {";
                    $js .= "collapsible: true";
                    $js .= ",split: true";
                $js .= "}";
                $js .= ",items: [{";
                    $js .= "region:'west'";
                    $js .= ",id: 'TRAINING_ID'";
                    $js .= ",title: '&nbsp;'";
                    $js .= ",autoScroll: true";
                    $js .= ",margins: '3 0 3 3'";
                    $js .= ",cmargins: '3 3 3 3'";
                    $js .= ",width:300";
                    $js .= ",minSize:300";
                    $js .= ",maxSize:300";
                    $js .= ",layout: 'fit'";
                    $js .= ",items:[{xtype: '".$OBJECT_TREE->getObjectXtype()."'}]";
                $js .= "},{";
                    $js .= "collapsible: false";
                    $js .= ",id: 'center'";
                    $js .= ",region:'center'";
                    $js .= ",margins: '3 3 3 0'";
                    $js .= ",layout: 'card'";
                    $js .= ",activeItem: 0";
                    $js .= ",bodyStyle: 'padding:1px'";
                    
                    $js .= ",items: [{";
                        $js .= "border: false";
                        $js .= ",layout: 'anchor'";
                        $js .= ",bodyStyle: 'background:#FFFFFF; padding:25px;'";
                        $js .= ",items: [{";
                            $js .= "title: ''";
                            $js .= ",height:60";
                            $js .= ",width:500";
                            $js .= ",bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'";
                            $js .= ",html:'<h1 class=\"header\">".PLEASE_MAKE_YOUR_SELECTIONS."</h1>'";
                        $js .= "}]";
                    $js .= "}]";
                    
                $js .= "}]";
            $js .= "}]";
        $js .= "});";
        $js .= "var myTree = ".$OBJECT_TREE->ExtgetCmp().";";
        $js .= "myTree.on('click', function(node, event){";
            $js .= "if(node.isLeaf()){";
                
                $CONTEXTMENU_ITEMS = array();
                
                $MENU1 ="{";
                    $MENU1 .="text: '".TEACHER_ENTER_SCORE."'";
                    $MENU1 .=",iconCls: 'icon-application_form_magnify'";
                    $MENU1 .=",disabled:false";
                    $MENU1 .=",handler: function(){";
                        $MENU1 .= "clickOpenPage('center','', '/training/scoremonitortraining/?trainingId=' + node.id);";
                        $MENU1 .= "Ext.getCmp('TRAINING_ID').collapse();";
                    $MENU1 .="}";
                $MENU1 .="}";
                $CONTEXTMENU_ITEMS[] = $MENU1;
                
                $MENU2 ="{";
                    $MENU2 .="text: '".ACADEMIC_PERFORMANCES."'";
                    $MENU2 .=",iconCls: 'icon-application_form_magnify'";
                    $MENU2 .=",disabled:false";
                    $MENU2 .=",handler: function(){";
                        $MENU2 .= "clickOpenPage('center','".ACADEMIC_PERFORMANCES." &raquo; ' + node.text, '/training/trainingperformance/?objectId=' + node.id);";
                        $MENU2 .= "Ext.getCmp('TRAINING_ID').collapse();";
                    $MENU2 .="}";
                $MENU2 .="}";
                $CONTEXTMENU_ITEMS[] = $MENU2;
                
                $CHOOSE_CONTEXTMENU_ITEMS = implode(",",$CONTEXTMENU_ITEMS);
                
                if($CONTEXTMENU_ITEMS){
                    $js .="var contextMenu = new Ext.menu.Menu({";
                        $js .="items: [".$CHOOSE_CONTEXTMENU_ITEMS."]";
                    $js .="});";
                    $js .="event.stopEvent();";
                    $js .="contextMenu.showAt(event.xy);"; 
                }
                
            $js .= "}";
        $js .= "});"; 
        
        echo $js;
        ?>
    });
</script>
<div id="initCenter" class="x-hidden" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>
</div>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>