<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("TRAINING");
$OBJECT_FORM->setLoadUrl("/training/jsonload/");
$OBJECT_FORM->setSaveUrl("/training/jsonsave/");

TrainingDBAccess::updateChildTerm($this->objectId);
$OBJECT_DATA = $this->objectData;

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
Ext.onReady(function() {
    
    <?
    /**
     * Extjs: s.gif
     */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $DETAIL_ITEMS = "
    [
        {".CamemisField::Box("CODE", CODE_ID, $OBJECT_DATA["CODE"])."}
        ,{".CamemisField::Datefield("START_DATE", DATE_FROM, true, false)."}
        ,{".CamemisField::Datefield("END_DATE", DATE_TO, true, false)."}
    ]
    ";
    
    $OBJECT_FORM->setLoadParams("cmd: 'jsonLoadObject',objectId: '".$this->objectId."'");
    $OBJECT_FORM->setSaveParams("
        cmd: 'jsonSaveObject'
        ,objectId: '".$this->objectId."'
    ");
    
    $OBJECT_FORM->setReleaseParams("cmd: 'jsonReleaseObject',objectId: '".$this->objectId."'");
    
    $DETAIL_INFORMATION = "
    {
        title: '".DETAIL_INFORMATION."'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: ".$DETAIL_ITEMS."
        }]
    }
    ";
    
    $EVALUATION_TYPE_STORE = "[
        [0, '" . NUMBER . "']
        ,[1, '".PERCENTAGE."']
    ]";
    $EVALUATION_TYPE="{
        title:'".EVALUATION_TYPE."'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:15px'
            ,items:[
                {".CamemisField::Combo('EVALUATION_TYPE', EVALUATION_TYPE, $EVALUATION_TYPE_STORE, false, false, false, false,false)."} 
            ]
        }]
    }";
    
    $SCHEDULE_SETTING = "
    {
        title: 'Schedule Setting'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,autoHeight: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {
                    xtype:'radiogroup'
                    ,fieldLabel : 'Schedule Setting'
                    ,items      : [
                        { boxLabel : 'Week Setting', name : 'SCHEDULE_SETTING', inputValue : 0 },
                        { boxLabel : 'Day Setting', name : 'SCHEDULE_SETTING', inputValue : 1 },
                        
                    ]   
                }
            ]
        }]
    }
    ";
    
    $DEFINE_TIME_BLOCKS = "
    {
        title: '".DEFINE_TIME_BLOCKS."'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width:550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                 {".CamemisField::TextTimefield("ENDTIME_BLOCK_MORNING", TIME_BLOCK_MORNING, true, "12:00")."}
                ,{".CamemisField::TextTimefield("ENDTIME_BLOCK_AFTERNOON", TIME_BLOCK_AFTERNOON, true, "18:00")."}
                ,{border: false, html:'".TIME_BLOCK_INFO."', style: 'padding-top: 10px; padding-bottom: 5px'}
                ,{border: false, html:'".TIME_BLOCK_INFO_2."', style: 'padding-bottom: 5px'}
            ]
        }]
    }
    ";
    
    $REGISTRATION = "
    {
        title: '".STUDENT_REGISTRATION."'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width:550
        ,autoHeight: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Datefield("REGISTRATION_START", DATE_FROM, false, false)."}
                ,{".CamemisField::Datefield("REGISTRATION_END", DATE_TO, false, false)."}
            ]
        }]
    }
    ";
    
    $CONTACT_INFORMATION = "
    {
        title: '".CONTACT_INFORMATION."'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width:550
        ,autoHeight: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Textfield("CONTACT_PERSON","CONTACT_PERSON",CONTACT_PERSON)."}
                ,{".CamemisField::EMailfield("CONTACT_EMAIL",CONTACT_EMAIL, false, false)."}
                ,{".CamemisField::Textfield("CONTACT_PHONE","CONTACT_PHONE",CONTACT_PHONE)."}
            ]
        }]
    }
    ";
    
    $WORKING_DAYS = "
    {
        title: '".WORKING_DAYS."'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,autoHeight: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Checkbox("MO","MO", MONDAY, 1, false)."}
                ,{".CamemisField::Checkbox("TU","TU", TUESDAY, 1, false)."}
                ,{".CamemisField::Checkbox("WE","WE", WEDNESDAY, 1, false)."}
                ,{".CamemisField::Checkbox("TH","TH", THURSDAY, 1, false)."}
                ,{".CamemisField::Checkbox("FR","FR", FRIDAY, 1, false)."}
                ,{".CamemisField::Checkbox("SA","SA", SATURDAY, 1, false)."}
                ,{".CamemisField::Checkbox("SU","SU", SUNDAY, 1, false)."}
            ]
        }]
    }
    ";

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        }
    ");
    
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
    
    $OBJECT_FORM->setonEmbeddedEvents("

        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');     
        myTree = window.parent.Ext.getCmp('TRAINING_TREE_ID');
        myNode = myTree.getNodeById('".$this->facette->PARENT."');
        myNode.reload();
        myNode.expand(true, false);
        ".camemisPage::setRequestURI()."
    ");

    $OBJECT_FORM->setOnEmbeddedReleaseEvents("

        ".camemisPage::setRequestURI()."
        
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');     
        myTree = window.parent.Ext.getCmp('TRAINING_TREE_ID');
        myNode = myTree.getNodeById('".$this->facette->PARENT."');
        myNode.reload();
        myNode.expand(true, false);
    ");
    
    $OBJECT_FORM->setOnEmbeddedRemoveEvents("
        
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');     
        myTree = window.parent.Ext.getCmp('TRAINING_TREE_ID');
        myNode = myTree.getNodeById('".$this->facette->PARENT."');
        myNode.reload();
        myNode.expand(true, false);
        myNode.setText(action.result.text);
        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
    ");
    
    ////////////////////////////////////////////////////////////////////////////
    $CREATED = "
    {
        title: '".CREATED."'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,autoHeight: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#E0E7F7; padding:10px'
            ,items:[{
                ".CamemisField::Displayfield("CREATED_DATE",CREATED_DATE,false)."
            },{
                ".CamemisField::Displayfield("CREATED_BY",CREATED_BY,false)."
            }]
        }]
    }";

    $MODIFIED = "
    {
        title: '".MODIFIED."'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,autoHeight: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#E0E7F7; padding:10px'
            ,items:[{
                ".CamemisField::Displayfield("MODIFY_DATE",MODIFY_DATE,false)."
            },{
                ".CamemisField::Displayfield("MODIFY_BY",MODIFY_BY,false)."
            }]
        }]
    }";

    $DISABLED = "
    {
        title: '".DISABLED."'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,autoHeight: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#E0E7F7; padding:10px'
            ,items:[{
                ".CamemisField::Displayfield("DISABLED_DATE",DISABLED_DATE,false)."
            },{
                ".CamemisField::Displayfield("DISABLED_BY",DISABLED_BY,false)."
            }]
        }]
    }";
    ////////////////////////////////////////////////////////////////////////////
    
    $ITEMS = $DETAIL_INFORMATION;
    $ITEMS .= ",".$EVALUATION_TYPE;
    $ITEMS .= ",".$SCHEDULE_SETTING;
    $ITEMS .= ",".$DEFINE_TIME_BLOCKS;
    $ITEMS .= ",".$WORKING_DAYS;
    $ITEMS .= ",".$REGISTRATION;
    $ITEMS .= ",".$CONTACT_INFORMATION;
    $ITEMS .= ",".$CREATED;
    $ITEMS .= ",".$MODIFIED;
    $ITEMS .= ",".$DISABLED;
    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,autoScroll: true
        ,bodyStyle: 'padding:10px'
        ,items: [".$ITEMS."]
    ";
    $OBJECT_FORM->addObjectItems($items);
    
    $OBJECT_FORM->bodyStyle = "padding:0px";
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 150;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,id: 'content'
            ,layout: 'card'
            ,activeItem: 0
            ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>