<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTree("EXAMINAION_MANAGEMENT","LIST");
$OBJECT_TREE->setURL('/examination/jsontree/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
$examType = 5;
?>
<script>
    
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems("
            id: 'REFRESH'
            ,scope:this
            ,text:'".REFRESH."'
            ,iconCls:'icon-arrow_refresh'
            ,handler: function(){
                ".CamemisPage::setRequestURI(false)."
            }
        ");
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        $OBJECT_TREE->isTreeExpand = false;
        $OBJECT_TREE->setBaseParams("
            cmd: 'jsonTreeAllExaminations'
            ,type:'5'
        ");
        
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout: 'fit'
                ,border: false
                ,id: 'CONTENT'
                ,items:[{
                    layout:'border'
                    ,border: false
                    ,defaults: {
                        collapsible: true
                        ,split: true
                    }
                    ,items: [{
                        title:'<?=SEMESTER_TEST?>'
                        ,layout:'fit'
                        ,region:'west'
                        ,id: 'WEST_ID'
                        ,margins: '3 0 3 3'
                        ,cmargins: '3 3 3 3'
                        ,width: percentWidth(20)
                        ,minSize: percentWidth(20)
                        ,maxSize: percentWidth(20)
                        ,bodyStyle: 'background-color:#E0E7F7'
                        ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                    },{
                        title: ''
                        ,collapsible: false
                        ,id: 'center'
                        ,region:'center'
                        ,layout: 'card'
                        ,activeItem: 0
                        ,margins: '3 3 3 0'
                        ,items: [{
                            border: false
                            ,layout: 'anchor'
                            ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                            ,items: [{
                                title: ''
                                ,height:60
                                ,width:500
                                ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                                ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                            }]
                        }]
                    }]
                }]
            }]
        });
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node, e){
            if(node.attributes.schoolyearId){
                
                var menuItem = [{
                    text: '<?=SUBJECT;?>'
                    ,iconCls:'icon-application_form_add'
                    ,handler: function(){
                        clickOpenPage('center','', '/examination/showsubject/?objectId=new&type=<?=$examType;?>&academicId=' + node.attributes.academicId);
                    }
                }]
            }else if(node.attributes.subjectId){
                var menuItem = [{
                    text: '<?=DETAIL_INFORMATION;?>'
                    ,iconCls:'icon-application_form_magnify'
                    ,handler: function(){
                        clickOpenPage('center',node.text, '/examination/showsubject/?type=<?=$examType;?>&objectId=' + node.attributes.objectId);
                    }
                },{
                    text: '<?=LIST_OF_CANDIDATES;?>'
                    ,iconCls:'icon-group'
                    ,handler: function(){
                        clickOpenPage('center',node.text, '/examination/bysubject/?type=<?=$examType;?>&objectId=' + node.attributes.objectId);    
                    }
                },{
                    text: '<?=ROOM;?>'
                    ,iconCls:'icon-application_form_add'
                    ,handler: function(){
                        clickOpenPage('center','', '/examination/showroom/?type=<?=$examType;?>&objectId=new&parentId=' + node.attributes.parentId + '&schoolyear_Id=' + node.attributes.schoolyear_Id + '&startDate=' + node.attributes.startDate + '&startTime=' + node.attributes.startTime + '&endTime=' + node.attributes.endTime);
                    }
                }]
            }
            
            if(node.isLeaf()){
                var menuItem = [{
                    text: '<?=DETAIL_INFORMATION;?>'
                    ,iconCls:'icon-application_form_magnify'
                    ,handler: function(){
                        clickOpenPage('center',node.text, '/examination/showroom/?type=<?=$examType;?>&objectId=' + node.attributes.objectId); 
                    }
                },{
                    text: '<?=LIST_OF_CANDIDATES;?>'
                    ,iconCls:'icon-group'
                    ,handler: function(){
                        clickOpenPage('center',node.text, '/examination/byroom/?type=<?=$examType;?>&objectId=' + node.attributes.objectId);     
                    }
                }]
            }
            
            if(menuItem){
                var contextMenu = new Ext.menu.Menu({
                    items:menuItem
                });
                e.stopEvent();
                contextMenu.showAt(e.xy);
            }
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>