<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("EXAMINATION_MANAGEMENT");
$OBJECT_FORM->setLoadUrl('/examination/jsonload/');
$OBJECT_FORM->setSaveUrl('/examination/jsonsave/');

$OBJECT_TREE = new CamemisTree("SUBJECT", "LIST");
$OBJECT_TREE->setURL("/subject/jsontree/");

$ASSIGNMENT_GRID = new CamemisGrid("EXAMINATION_MANAGEMENT", "ASSIGNMENTS");
$ASSIGNMENT_GRID->setLoadUrl('/assignment/jsonload/');

$STAFF_GRID = new CamemisGrid("EXAM_MANAGEMENT", "ASSIGNED");
$STAFF_GRID->setLoadUrl("/examination/jsonload/");
$STAFF_GRID->setSaveUrl("/examination/jsonsave/");

$UNASSIGNED_STAFF_GRID = new CamemisGrid("EXAM_MANAGEMENT", "UNASSIGNED");
$UNASSIGNED_STAFF_GRID->setLoadUrl("/examination/jsonload/");
$UNASSIGNED_STAFF_GRID->setSaveUrl("/examination/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$type = isset($_GET['type'])?addText($_GET['type']):"";

?>
<script>
var chooseSubject;
Ext.onReady(function() {
	
    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#333; padding:3px;">' + value + '</div>';
    }
    
    Ext.form.Field.prototype.msgTarget = 'side';
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    ////////////////////////////////////////////////////////////////////////////
    $OBJECT_TREE->isAsyncTreeNode = false;
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));

    $OBJECT_TREE->setBaseParams("
        cmd: 'treeAllSubjects'
    ");

    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->isTreeExpand = true;
    $OBJECT_TREE->isOnClickContextMenu = false;
    $OBJECT_TREE->renderJS();

    $triggerOnClickSubject = "
        openWinXType('WIN_ADD_SUBJECT','".SUBJECT."', '".$OBJECT_TREE->getObjectXType()."', 500, percentHeight(85));
        var myTree = Ext.getCmp('".$OBJECT_TREE->getObjectId()."');
        myTree.on('click', function(node, e){
            if(node.isLeaf()){
                Ext.getCmp('CHOOSE_SUBJECT_NAME_ID').setValue(node.text);
                Ext.getCmp('CHOOSE_SUBJECT').setValue(node.id);  
                Ext.getCmp('WIN_ADD_SUBJECT').close();
            }
        });
    ";
    ////////////////////////////////////////////////////////////////////////////
    
    $FORM_ITEMS = "[
        {".CamemisField::Textfield("NAME", "NAME", NAME, true)."}
        ,{".CamemisField::Trigger("CHOOSE_SUBJECT_NAME",SUBJECT,$triggerOnClickSubject, true)."}
        ,{".CamemisField::Numberfield("COUNT","COUNT", MAX_STUDENTS, true, false)."} 
        ,{".CamemisField::Hidden("CHOOSE_SUBJECT",false)."}
        ,{".CamemisField::Hidden("CHOOSE_ASSIGNMENT",false)."}      
    ]"; 

    $EXAM_DATE = "
    {
        title: '".EXAM_DATE."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
            ,items: [{
                fieldLabel: '" . EXAM_DATE . "'
                ,name: 'START_DATE'
                ,xtype: 'datefield'
                ,id: 'START_DATE'
                ,width: 250
                ,format: '" . setExtDatafieldFormat() . "'
                ,allowBlank: false
            },{
                xtype: 'textfield'
                ,emptyText: 'HH:MM'
                ,name: 'START_TIME'
                ,fieldLabel: '".START_TIME."'
                ,width: 250
                ,allowBlank: false
            },{
                xtype: 'textfield'
                ,emptyText: 'HH:MM'
                ,name: 'END_TIME'
                ,fieldLabel: '".END_TIME."'
                ,width: 250
                ,allowBlank: false
            }]
        }]
    }
    ";
    
    $DETAIL_INFORMATION = "
    {
        title: '".DETAIL_INFORMATION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
            ,items: ".$FORM_ITEMS."
        }]
    }
    ";
    
    $DESCRIPTION = "
    {
        title: '".DESCRIPTION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,height: 100
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'background:#FFF; color:#000;padding:5px'
            ,items: [{".CamemisField::Textarea("DESCRIPTION", false,200)."}]
        }]
    }
    ";
    ///////////////////////////////////////////////////////
    //Staff...
    ///////////////////////////////////////////////////////
    $UNASSIGNED_STAFF_GRID->addReadField("name: 'CODE'");
    $UNASSIGNED_STAFF_GRID->addReadField("name: 'LASTNAME'");
    $UNASSIGNED_STAFF_GRID->addReadField("name: 'FIRSTNAME'");
    $UNASSIGNED_STAFF_GRID->addReadField("name: 'STUDENT_NAME'");
    $UNASSIGNED_STAFF_GRID->addReadField("name: 'GENDER'");
    
    $UNASSIGNED_STAFF_GRID->addColumn("header: '<b>".CODE_ID."</b>', renderer:cssText, align:'left', sortable: true, width: 80, dataIndex: 'CODE'");
    if(!SchoolDBAccess::displayPersonNameInGrid()){
        $UNASSIGNED_STAFF_GRID->addColumn("header: '<b>".LASTNAME."</b>', renderer:cssText, width: 120, sortable: false, dataIndex: 'LASTNAME'");
        $UNASSIGNED_STAFF_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', renderer:cssText, width: 120, sortable: false, dataIndex: 'FIRSTNAME'");
    }else{
        $UNASSIGNED_STAFF_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', renderer:cssText, width: 120, sortable: false, dataIndex: 'FIRSTNAME'");
        $UNASSIGNED_STAFF_GRID->addColumn("header: '<b>".LASTNAME."</b>', renderer:cssText, width: 120, sortable: false, dataIndex: 'LASTNAME'");
    }
    
    if($this->facette)
    $UNASSIGNED_STAFF_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonUnassignedStaffExamination'
        ,objectId: '" . $this->facette->GUID . "'
    ";

    if($this->facette)
    $UNASSIGNED_STAFF_GRID->setSelectionParams("
        cmd: 'jsonActionChooseStaffToExamination'
        ,objectId: '" . $this->facette->GUID . "'
    ");

    $UNASSIGNED_STAFF_GRID->setSelectionEmbeddedEvents("
        Ext.getCmp('" . $STAFF_GRID->getObjectId() . "').store.sortInfo = null;
        Ext.getCmp('" . $STAFF_GRID->getObjectId() . "').store.reload();
        Ext.getCmp('" . $UNASSIGNED_STAFF_GRID->getObjectId() . "').store.reload();
    ");

    $UNASSIGNED_STAFF_GRID->addTBarItems("
        tbar.add([{
            id: 'APLY_ID'
            ,text: '<b>" . APPLY . "</b>'
            ,iconCls:'icon-disk'
            ,scope:this
            ,handler: this.onSelection
        }]);
    ");
        
    $UNASSIGNED_STAFF_GRID->isQuickySearch = true;
    $UNASSIGNED_STAFF_GRID->isCheckboxSelect = true;
    $UNASSIGNED_STAFF_GRID->forceFit = "false";
    $UNASSIGNED_STAFF_GRID->renderJS();
    ///////////////////////////////////////////////////////   
    $STAFF_GRID->addReadField("name: 'CODE'");
    $STAFF_GRID->addReadField("name: 'LASTNAME'");
    $STAFF_GRID->addReadField("name: 'FIRSTNAME'");
    $STAFF_GRID->addReadField("name: 'CHECKED'");
    $STAFF_GRID->addReadField("name: 'ROOM_NAME'");
    
    $STAFF_GRID->addColumn("
        xtype: 'checkboxcolumn'
        ,header: ''
        ,dataIndex: 'CHECKED'
        ,width: 50
        ,on: 1
        ,off: 0
    ");
    
    $STAFF_GRID->addColumn("header: '<b>".CODE_ID."</b>', align:'left', renderer:cssText, sortable: true, width: 80, dataIndex: 'CODE'");
    if(!SchoolDBAccess::displayPersonNameInGrid()){
        $STAFF_GRID->addColumn("header: '<b>".LASTNAME."</b>', width: 120, renderer:cssText, sortable: false, dataIndex: 'LASTNAME'");
        $STAFF_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', width: 120, renderer:cssText, sortable: false, dataIndex: 'FIRSTNAME'");
    }else{
        $STAFF_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', width: 120, renderer:cssText, sortable: false, dataIndex: 'FIRSTNAME'");
        $STAFF_GRID->addColumn("header: '<b>".LASTNAME."</b>', width: 120, renderer:cssText, sortable: false, dataIndex: 'LASTNAME'");
    }
    $STAFF_GRID->addColumn("header: '<b>".ROOM."</b>', width: 150, renderer:cssText, sortable: true, dataIndex: 'ROOM_NAME'");
    
    if($this->facette){
        
        $STAFF_GRID->setSaveParams("
            cmd: 'jsonActionRemoveStaffFromExamination'
            ,objectId: '" . $this->facette->GUID . "'
        ");
        
        $STAFF_GRID->baseParams = "
            start:0
            ,limit:100
            ,cmd: 'jsonAssignedStaffExamination'
            ,objectId: '" . $this->facette->GUID . "'
        ";
        
        $STAFF_GRID->setEditEmbeddedEvents("
            Ext.getCmp('" . $STAFF_GRID->getObjectId() . "').store.sortInfo = null;
            Ext.getCmp('" . $STAFF_GRID->getObjectId() . "').store.reload();
        ");
    }
    
    $STAFF_GRID->addTBarItems("
        tbar.add('->',[{
            id: 'APLY_ID'
            ,text: '<b>" . STAFF . "</b>'
            ,iconCls:'icon-group_add'
            ,scope:this
            ,handler:function(){
                openWinXType('WinXType','" . LIST_OF_STAFFS . "', '" . $UNASSIGNED_STAFF_GRID->getObjectXType() . "',500, percentHeight(85));
            }
        }]);
    ");
    
    $STAFF_GRID->loadMask = false;
    $STAFF_GRID->isGridEditing = true;
    $STAFF_GRID->forceFit = "false";
    $STAFF_GRID->renderJS();
    $LIST_OF_STAFFS = "
    {
        title: '".LIST_OF_STAFFS."'
        ,layout:'fit'
        ,style: 'padding-bottom: 5px'
        ,width:550
        ,height:300
        ,items:[{xtype: '".$STAFF_GRID->getObjectXtype()."'}]
    }
    ";
    
    $DISPLAY_ITEMS = "[";
    $DISPLAY_ITEMS .= $DETAIL_INFORMATION;
    $DISPLAY_ITEMS .= ",".$EXAM_DATE;
    
    if($this->facette){
        $DISPLAY_ITEMS .= ",".$LIST_OF_STAFFS;    
    }
    
    $DISPLAY_ITEMS .= ",".$DESCRIPTION;
    $DISPLAY_ITEMS .= "]";
    
    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: ".$DISPLAY_ITEMS."
    ";
    
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'WEST_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            window.parent.Ext.getCmp('WEST_ID').expand();
        }
    ");
    
    $OBJECT_FORM->setLoadParams("cmd: 'loadExamination',objectId: '".$this->objectId."'");
    
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
    
    if($this->objectId == "new"){
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonActionSaveExamination'
            ,type: '".$type."'
            ,gradeId:'".$this->gradeId."'
            ,schoolyearId:'".$this->schoolyearId."'
            ,objectId:'".$this->objectId."'
        ");
        
        $OBJECT_FORM->setonEmbeddedEvents("
            myTree = window.parent.Ext.getCmp('TREE.EXAMINAION_MANAGEMENT_LIST_ID');
            myNode = myTree.getNodeById(".$this->academicObject->PARENT.");
            myNode.reload();
            myNode.expand(true, false);
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                var result = Ext.util.JSON.decode(action.response.responseText);
                var objectId = result.objectId;
                window.location='".$_SERVER["REQUEST_URI"]."&objectId='+objectId;
            ");
    }else{
        
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormRemoveObject($this->removeStatus));
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonActionSaveExamination'
            ,type: '1'
            ,objectId: '".$this->objectId."'
        ");
        
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('TREE.EXAMINAION_MANAGEMENT_LIST_ID');
            myNode = myTree.getNodeById(".$this->facette->GRADE_ID.");
            myNode.reload();
            myNode.expand(true, false);
            ".camemisPage::setRequestURI()."
        ");
        
        $OBJECT_FORM->setReleaseParams("cmd: 'jsonActionReleaseExam',objectId: '".$this->objectId."'");
        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('TREE.EXAMINAION_MANAGEMENT_LIST_ID');
            myNode = myTree.getNodeById(".$this->facette->GRADE_ID.");
            myNode.reload();
            myNode.expand(true, false);
            ".camemisPage::setRequestURI()."
        ");
    
        $OBJECT_FORM->setRemoveParams("
            cmd: 'removeExamination'
            ,objectId: '".$this->objectId."'
        ");

        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            myTree = window.parent.Ext.getCmp('TREE.EXAMINAION_MANAGEMENT_LIST_ID');
            myNode = myTree.getNodeById(".$this->facette->GRADE_ID.");
            myNode.reload();
            myNode.expand(true, false);
        ");
    }
    
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>