<?
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'models/app_school/AcademicDateDBAccess.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$term = AcademicDBAccess::getNameOfSchoolTermByDate(date('Y-m-d'), $this->academicId);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$DB_ACCESS = Zend_Registry::get('DB_ACCESS');
$SQL = $DB_ACCESS->select();
$SQL->from("t_grade", array('*'));
$SQL->where("PARENT='".$this->academicId."'");
$SQL->order("SORTKEY ASC");
$result = $DB_ACCESS->fetchAll($SQL);

$ITEMS = "[";
$data = array();
if($result){
    $i = 0;
    foreach($result as $value){
        if($i==0){
            $collapsed = "false";
        }else{
            $collapsed = "true";
        }
        $data[]= "{
            border:true
            ,xtype: 'panel'
            ,collapsible: true
            ,collapsed: ".$collapsed."
            ,title:'".SCHEDULE." &raquo; ".$value->NAME."'
            ,layout:'fit'
            ,width:percentWidth(95)
            ,style: 'padding-bottom: 5px'
            ,height:800
            ,items: [new Ext.ux.IFrameComponent({ id: '".$value->GUID."', url:'/schedule/weekclassevents/?&display=".camemisId()."&academicId=".$value->ID."&term=".$term."&target=general'})]
        }";
        
        $i++;
    }
}
$ITEMS .= implode(",",$data);
$ITEMS .= "]";

?>
<script>

Ext.onReady(function() {
    
    <?
    /////////////////////////////
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'content'
            ,autoScroll: true
            ,border: false
            ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px;'
            ,items: [{
                border: false
                ,items: <?=$ITEMS;?>
            }]
        }]
    });
});

</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>