<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisSchoolTree.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisSchoolTree("ACADEMIC");
$OBJECT_TREE->setURL("/academic/jsontree/");
$OBJECT_TREE->setSaveUrl("/academic/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$GENERAL_EDUCATION = UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION")?"false":"true";

$entries = UserAuth::dbAccess()->fetchAll("SELECT * FROM t_grade WHERE PARENT=0 AND EDUCATION_SYSTEM=1");
if($entries){
    foreach($entries as $value){
        UserAuth::dbAccess()->query("UPDATE t_grade SET EDUCATION_SYSTEM='".$value->EDUCATION_SYSTEM."' WHERE CAMPUS_ID='".$value->ID."'");
    }
}

?>
<script>
    var firstId;
    Ext.onReady(function() {
        var tabs =  new Ext.TabPanel({
            autoTabs:true
            ,border:false
            ,tabPosition: 'top'
            ,enableTabScroll:true
            ,activeTab:0
            ,items:[{
                title: '&nbsp;'
                ,id: 'TAB_DEFAULT'
                ,layout: 'fit'
                ,items: [{
                    layout:'anchor'
                    ,border:false
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items:[{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class=\"header\"><?=PLEASE_MAKE_YOUR_SELECTIONS?></h1>'
                    }]
                }]
            }]
        });
        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $CAMEMIS_PAGE_OBJECT->setAddTab();

        $currentSchoolyearId = AcademicDateDBAccess::loadCurrentSchoolyear()?AcademicDateDBAccess::loadCurrentSchoolyear()->ID:"";
        $STORE_SCHOOLYEAR = "[";
        if(AcademicDateDBAccess::getAllSchoolyear()){
            $i = 0;
            foreach(AcademicDateDBAccess::getAllSchoolyear() as $value){
                $DATA[$i] = $value->ID;
                $STORE_SCHOOLYEAR .= $i?",":"";
                $STORE_SCHOOLYEAR .= "['" . $value->ID . "', '" . setShowText($value->NAME) ."', 'icon-date']";
                $i++;
            }
        }

        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());

        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT")){
            $OBJECT_TREE->addTBarItems("
                id: 'CAMPUS_ID'
                ,tooltip:'".ADD_NEW_QUALIFICATION."'
                ,scope:this
                ,iconCls:'icon-application_form_add'
                ,handler: this.onAddQualification
            ");
        }

        $STORE_SCHOOLYEAR .= "]";
        $OBJECT_TREE->addTBarItems("
            xtype: 'buttongroup'
            ,items:[{
                xtype:'combo'
                ,id:'COMO_SCHOOLYEAR_ID'
                ,width:170
                ,fieldLabel:'IconCombo'
                ,store: new Ext.data.SimpleStore({
                    fields: ['comboCode', 'comboName', 'comboIcon'],
                    data: ".$STORE_SCHOOLYEAR."
                })
                ,plugins:new Ext.ux.plugins.IconCombo()
                ,valueField: 'comboCode'
                ,displayField: 'comboName'
                ,iconClsField: 'comboIcon'
                ,triggerAction: 'all'
                ,mode: 'local'
                ,value:'".$currentSchoolyearId."'
            }]
        ");

        $OBJECT_TREE->addTBarItems("
            text:''
            ,tooltip:'".CAMEMIS_HELP."'
            ,iconCls: 'icon-help'
            ,handler:function(){
                openWinIFrame('".CAMEMIS_HELP."', '/help/?key=GENERAL_EDUCATION',700, percentHeight(85));
            }
        ");

        $OBJECT_TREE->setBaseParams("
            cmd: 'getTreeCreditEducationSystem'
            ,educationSystem:1
            ,SCHOOLYEAR:'".$currentSchoolyearId."'
        ");

        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isCrediSystem = true;
        $OBJECT_TREE->isTreeExpand = false;
        $OBJECT_TREE->renderJS();

        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    region:'west'
                    ,id: 'ACADEMIC_ID'
                    ,title: '&nbsp;'
                    ,autoScroll: true
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width:350
                    ,minSize:350
                    ,maxSize:350
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                },{
                    collapsible: false
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,bodyStyle: 'padding:1px'
                    ,items: tabs
                }]
            }]
        });

        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        var myCombo = Ext.getCmp('COMBO_ID');
        if (myCombo)
        myCombo.on('select', function() {
            myTree.loader.baseParams.SCHOOLYEAR = Ext.getCmp('COMBO_ID').getValue();
            myTree.root.reload();
            //myTree.getRootNode().expand(true, false);
            Ext.getCmp('center').getLayout().setActiveItem(0);
        });

        myTree.on('click', function(node, event){
            <?
            $html = "";
            $html .= "if (node.attributes.educationSystem == 1) {hiddMenu = true;}";
            $html .= "else hiddMenu = false;";
            $html .= "switch(node.attributes.objecttype){";
                $html .= "case 'CAMPUS':";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".EXPAND."'";
                            $html .= ",iconCls: 'icon-expand-all'";
                            $html .= ",handler: function(){";
                                $html .= "myNode = myTree.getNodeById(node.id);";
                                $html .= "myNode.reload();";
                                $html .= "myNode.expand(true, false);";
                            $html .= "}";

                        $html .= "},{";
                            $html .= "text: '".MAIN_CONTENT."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/editcampus/?objectId=' + node.attributes.guId);";
                                //$html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";
                        $html .= "}]";
                    $html .= "});";
                $html .= "break;";
                $html .= "case 'SCHOOLYEAR':";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".EXPAND."'";
                            $html .= ",iconCls: 'icon-expand-all'";
                            $html .= ",handler: function(){";
                                $html .= "myNode = myTree.getNodeById(node.id);";
                                $html .= "myNode.reload();";
                                $html .= "myNode.expand(true, false);";
                            $html .= "}";

                        $html .= "},{";
                            $html .= "text: '".MAIN_CONTENT."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/editschoolyear/?objectId=' + node.attributes.guId);";
                                //$html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";

                        $html .= "},{";
                            $html .= "text: '".SUBJECT_AND_ASSIGNMENT."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-flag_blue'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/creditsubjectassignment/?objectId=' + node.id);";
                                $html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";
                        //$veasna
                        $html .= "},{";
                            $html .= "text: '".ENROLLED_STUDENTS."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-group'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/creditenrolledstudent/?display=target&objectId=' + node.attributes.guId);";
                                $html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";
                         $html .= "},{";
                            $html .= "text: '".ASSIGNED_TEACHERS."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-group'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/creditassignedteacher/?objectId=' +  node.attributes.guId);";
                                $html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";
                        $html .= "},{";
                            $html .= "text: '".ADDITIONAL_INFORMATION."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-application_form_add'";
                            $html .= ",handler: function(){";
                                //$html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/additionalinformation/?objectId=' + node.id);";
                                $html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";
                        $html .= "}]";
                        ////
                    $html .= "});";
                $html .= "break;";
                ////////////////////////////////////////////////////////////////
                $html .= "case 'SUBJECT':";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".MAIN_CONTENT."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/editsubject/?objectId=' + node.attributes.guId);";
                                //$html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";

                        $html .= "},{";
                            $html .= "text: '".ENROLLED_STUDENTS."'";
                            //$html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-group'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/creditenrolledstudent/?display=target&objectId=' + node.attributes.guId);";
                                //$html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";

                        $html .= "},{";
                            $html .= "text: '".ASSIGNED_TEACHERS."'";
                            $html .= ",iconCls: 'icon-group'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/creditassignedteacher/?objectId=' +  node.id);";
                                //$html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";
                       $html .= "},{";
                            $html .= "text: '".SCHEDULE_MANAGEMENT."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-date'";
                            $html .= ",menu:[{";
                                $html .= "text: '".DAY_SCHEDULE."'";
                                $html .= ",iconCls: 'icon-date_magnify'";
                                $html .= ",handler: function(){";
                                    $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                    $html .= "clickOpenPage('center','".DAY_SCHEDULE."','/schedule/dayeventlist/?academicId=' + node.id);";
                                $html .= "}";
                            $html .= "},{";
                                $html .= "text: '".WEEK_SCHEDULE."'";
                                $html .= ",iconCls: 'icon-date_magnify'";
                                $html .= ",handler: function(){";
                                    $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                    $html .= "clickOpenPage('center','".WEEK_SCHEDULE."','/schedule/classeventsetting/?academicId=' + node.id);";
                                $html .= "}";
                            $html .= "},{";
                                $html .= "text: '".EXTRA_TEACHING_SESSION."'";
                                $html .= ",iconCls: 'icon-date_magnify'";
                                $html .= ",handler: function(){";
                                    $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                    $html .= "clickOpenPage('center','".EXTRA_TEACHING_SESSION."','/schedule/trainingscheduleweek/?academicId=' + node.id);";
                                $html .= "}";
                            $html .= "}]";
                       $html .= "},{";
                            $html .= "text: '".PRE_REQUISITE_COURSE."'";
                            //$html .= ",disabled: true";
                            $html .= ",iconCls: 'icon-basket_put'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/evaluation/creditsubjectstatus/?academicId=' +  node.id);";
                                $html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";

                        $html .= "}]";
                    $html .= "});";
                $html .= "break;";
                ////////////////////////////////////////////////////////////////
                $html .= "case 'CLASS':";
                    $html .= "var contextMenu = new Ext.menu.Menu({";
                        $html .= "items: [{";
                            $html .= "text: '".MAIN_CONTENT."'";
                            $html .= ",iconCls: 'icon-application_form_magnify'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/editgroup/?objectId=' + node.attributes.guId);";
                                //$html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";

                        $html .= "},{";
                            $html .= "text: '".ENROLLED_STUDENTS."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-group'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/creditenrolledstudent/?display=target&objectId=' + node.id);";
                                //$html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";
                        $html .= "},{";
                            $html .= "text: '".ASSIGNED_TEACHERS."'";
                            $html .= ",iconCls: 'icon-group'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/academic/creditassignedteacher/?objectId=' + node.id);";
                                //$html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";
                            //@THORN Visal
                        $html .= "},{";
                            $html .= "text: '".SUBJECT."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-flag_blue'";
                            $html .= ",handler: function(){";
                                $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                $html .= "clickOpenPage('center','','/subject/gradesubject/?classId='+ node.id+'&parentId='+node.attributes.parentId);";
                                $html .="Ext.getCmp('ACADEMIC_ID').collapse();";
                            $html .= "}";
                        $html .= "},{";
                            $html .= "text: '".SCHEDULE_MANAGEMENT."'";
                            $html .= ",disabled: ".$GENERAL_EDUCATION."";
                            $html .= ",iconCls: 'icon-date'";
                            $html .= ",menu:[{";
                                $html .= "text: '".DAY_SCHEDULE."'";
                                $html .= ",iconCls: 'icon-date_magnify'";
                                $html .= ",handler: function(){";
                                    $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                    $html .= "clickOpenPage('center','".DAY_SCHEDULE."','/schedule/dayeventlist/?academicId=' + node.id);";
                                $html .= "}";
                            $html .= "},{";
                                $html .= "text: '".WEEK_SCHEDULE."'";
                                $html .= ",iconCls: 'icon-date_magnify'";
                                $html .= ",handler: function(){";
                                    $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                    $html .= "clickOpenPage('center','".WEEK_SCHEDULE."','/schedule/classeventsetting/?academicId=' + node.id);";
                                $html .= "}";
                            $html .= "},{";
                                $html .= "text: '".EXTRA_TEACHING_SESSION."'";
                                $html .= ",iconCls: 'icon-date_magnify'";
                                $html .= ",handler: function(){";
                                    $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                                    $html .= "clickOpenPage('center','".EXTRA_TEACHING_SESSION."','/schedule/trainingscheduleweek/?academicId=' + node.id);";
                                $html .= "}";
                            $html .= "}]";
                        $html .= "}]";
                    $html .= "});";
                $html .= "break;";
            $html .= "}";
            $html .= "event.stopEvent();";
            $html .= "contextMenu.showAt(event.xy);";
            echo $html;
            ?>
        });
    });

</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>