<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisSchoolTree.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisSchoolTree("ACADEMIC");
$OBJECT_TREE->setURL("/academic/jsontree/");
$OBJECT_TREE->setSaveUrl("/academic/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>

<script>
    var firstId;
    Ext.onReady(function() {

        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $currentSchoolyearId = AcademicDateDBAccess::loadCurrentSchoolyear()?AcademicDateDBAccess::loadCurrentSchoolyear()->ID:"";
        
        $STORE_SCHOOLYEAR = "[";
        if(AcademicDateDBAccess::getAllSchoolyear()){
            $i = 0;
            foreach(AcademicDateDBAccess::getAllSchoolyear() as $value){
                $DATA[$i] = $value->ID;
                $STORE_SCHOOLYEAR .= $i?",":"";
                $STORE_SCHOOLYEAR .= "['" . $value->ID . "', '" . setShowText($value->NAME) ."', 'icon-date']";
                $i++;
            }
        }

        $OBJECT_TREE->isAsyncTreeNode = false;

        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());

        $STORE_SCHOOLYEAR .= "]";
        $OBJECT_TREE->addTBarItems("
            xtype: 'buttongroup'
            ,items:[{
                xtype:'combo'
                ,id:'COMO_SCHOOLYEAR_ID'
                ,width:120
                ,fieldLabel:'IconCombo'
                ,store: new Ext.data.SimpleStore({
                    fields: ['comboCode', 'comboName', 'comboIcon'],
                    data: ".$STORE_SCHOOLYEAR."
                })
                ,plugins:new Ext.ux.plugins.IconCombo()
                ,valueField: 'comboCode'
                ,displayField: 'comboName'
                ,iconClsField: 'comboIcon'
                ,triggerAction: 'all'
                ,mode: 'local'
                ,value:'".$currentSchoolyearId."'
            }]
        ");

        $OBJECT_TREE->addTBarItems("
            text:''
            ,tooltip:'".CAMEMIS_HELP."'
            ,iconCls: 'icon-help'
            ,handler:function(){
                ".CamemisPage::setEmbeddedHelp("475E-E899")."
            }
        ");
        
        $OBJECT_TREE->setBaseParams("
            cmd: 'getTreeCreditEducationSystem'
            ,educationSystem:1
            ,SCHOOLYEAR:'".$currentSchoolyearId."'
        ");

        $OBJECT_TREE->isOnClickContextMenu = false;
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isTreeExpand = false;
        $OBJECT_TREE->renderJS();

        $js ="";
        $js .="viewport = new Ext.Viewport({";
            $js .="layout: 'fit'";
            $js .=",border: false";
            $js .=",items:[{";
                $js .="layout:'border'";
                $js .=",border: false";
                $js .=",defaults: {";
                    $js .="collapsible: true";
                    $js .=",split: true";
                $js .="}";
                $js .=",items: [{";
                    $js .="region:'west'";
                    $js .=",id: 'ACADEMIC_ID'";
                    $js .=",title: '&nbsp;'";
                    $js .=",autoScroll: true";
                    $js .=",margins: '3 0 3 3'";
                    $js .=",cmargins: '3 3 3 3'";
                    $js .=",width:300";
                    $js .=",minSize:300";
                    $js .=",maxSize:300";
                    $js .=",layout: 'fit'";
                    $js .=",items:[{xtype: '".$OBJECT_TREE->getObjectXtype()."'}]";
                $js .="},{";
                    $js .="collapsible: false";
                    $js .=",id: 'center'";
                    $js .=",region:'center'";
                    $js .=",margins: '3 3 3 0'";
                    $js .=",layout: 'card'";
                    $js .=",activeItem: 0";
                    $js .=",items: [{";
                        $js .="border: false";
                        $js .=",layout: 'anchor'";
                        $js .=",bodyStyle: 'background:#FFFFFF; padding:25px;'";
                        $js .=",items: [{";
                            $js .="title: ''";
                            $js .=",height:60";
                            $js .=",width:500";
                            $js .=",bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'";
                            $js .=",html:'<h1 class=\"header\">".PLEASE_MAKE_YOUR_SELECTIONS."</h1>'";
                        $js .="}]";
                    $js .="}]";
                $js .="}]";
            $js .="}]";
        $js .="});";

        $js .="var myTree = ".$OBJECT_TREE->ExtgetCmp().";";
        $js .="var myCombo = Ext.getCmp('COMBO_ID');";
        $js .="if (myCombo)";
        $js .="myCombo.on('select', function() {";
            $js .="myTree.loader.baseParams.SCHOOLYEAR = Ext.getCmp('COMBO_ID').getValue();";
            $js .="myTree.root.reload();";
            $js .="myTree.getRootNode().expand(true, false);";
            $js .="Ext.getCmp('center').getLayout().setActiveItem(0);";
        $js .="});";
        $js .="var myTree = ".$OBJECT_TREE->ExtgetCmp().";";

        $js .="myTree.on('click', function(node, event){";
            $js .="if(node.isLeaf()){";
                $js .="var contextMenu = new Ext.menu.Menu({";
                    $js .="items: [{";
                        $js .="text: '".TEACHER_ENTER_SCORE." &raquo; ' + node.attributes.title";
                        $js .=",iconCls:'icon-note_edit'";
                        $js .=",disabled:false";
                        $js .=",handler: function(){";
                             $js .="clickOpenPage('center','".TEACHER_ENTER_SCORE." &raquo; ' + node.attributes.title, '/evaluation/subjectassignments/?academicId=' + node.id);";
                             $js .="Ext.getCmp('ACADEMIC_ID').collapse();";
                        $js .="}";
                    $js .="},{";
                        $js .="text: '".CREDIT_INFORMATION." &raquo; ' + node.attributes.title";
                        $js .=",iconCls:'icon-application_form_magnify'";
                        $js .=",disabled:false";
                        $js .=",handler: function(){";
                             $js .="clickOpenPage('center','".CREDIT_INFORMATION." &raquo; ' + node.attributes.title, '/evaluation/creditsubjectstatus/?academicId=' + node.id);";
                             $js .="Ext.getCmp('ACADEMIC_ID').collapse();";
                        $js .="}";
                    $js .="}]";
                $js .="});";
                $js .="event.stopEvent();";
                $js .="contextMenu.showAt(event.xy);";
            $js .="}";
        $js .="});";
    $js .="});";
    
    echo $js;
    ?>
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>