<html>
    <head>
    <title><?= Zend_Registry::get('TITLE');?></title>
    <link rel="stylesheet" type="text/css" href="../public/css/index.css" />
    <link rel="stylesheet" type="text/css" href="../public/css/main.css" />
    <link rel="stylesheet" type="text/css" href="../public/css/login.css" />
    <link rel="stylesheet" type="text/css" href="../public/<?= Zend_Registry::get('EXTJS_VERSION');?>/resources/css/ext-all.css" />
    <script type="text/javascript" src="../public/plugin/Cookies.js"></script>
    <script type="text/javascript" src="../public/<?= Zend_Registry::get('EXTJS_VERSION');?>/adapter/ext/ext-base.js"></script>
    <script type="text/javascript" src="../public/<?= Zend_Registry::get('EXTJS_VERSION');?>/ext-all.js"></script>
    </head>
    <body bgcolor="#FFFFFF">
    <div id="initCenter" class="x-hide-display" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="headerError">Error SQL Stamment!</h1>
    <br>
    </div>
	<script>
	Ext.onReady(function() {
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                layout: 'fit'
                ,border: false
                ,contentEl: 'initCenter'
            }]
         });
	});
	</script>
    </body>
</html>