<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 01.08.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("ATTENDANCE_TYPE");
$OBJECT_FORM->setSaveUrl("/attendance/jsonsave/");
$OBJECT_FORM->setLoadUrl("/attendance/jsonload/");
$userObject = UserMemberDBAccess::findUserFromId($this->staffId);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<script>
    Ext.onReady(function() {
        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $entries = AbsentTypeDBAccess::allAbsentType('STAFF', 2);
    
        $data = array();
        
        if($entries){
            $i = 0;
            foreach($entries as $value){
                $data[$i] = "[\"$value->ID\",\"$value->NAME\"]";
                $i++;
            }
        }
        
        $ABSENT_TYPE_STORE = "[" . implode(",", $data) . "]";
        $DETAIL_INFORMATION_ITEMS = "[";
            $DETAIL_INFORMATION_ITEMS .= "{".CamemisField::Combo("ABSENT_TYPE", ATTENDANCE_TYPE, $ABSENT_TYPE_STORE,false, false, false)."}";
        $DETAIL_INFORMATION_ITEMS .= "]";
        
        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,frame:false
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#F9F9F9;padding:10px'
                ,items:$DETAIL_INFORMATION_ITEMS
            }]
        }";
        
        
        $DOUBLE_DATE = "
        {
            title: '".DATE."'
            ,id:'DOUBLE_DATE_ID'
            ,hidden:false
            ,autoHeight: true
            ,frame:false
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#F9F9F9;padding:15px'
                ,items:[{
                    xtype:'datefield'
                    ,fieldLabel: '".START_DATE."'
                    ,name: 'START_DATE'
                    ,id: 'START_DATE'
                    ,width: 250
                    ,allowBlank:false
                    ,format: '".setExtDatafieldFormat()."'
                },{
                    xtype:'datefield'
                    ,fieldLabel: '".END_DATE."'
                    ,name: 'END_DATE'
                    ,id: 'END_DATE'
                    ,width: 250
                    ,allowBlank:false
                    ,format: '".setExtDatafieldFormat()."'
                }]
            }]
        }";
        
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: [
                ".$DETAIL_INFORMATION." 
                ,".$DOUBLE_DATE."
            ]
        ";
        
        $OBJECT_FORM->addObjectItems($items);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            }
        ");
        
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonActonStaffAttendance'
            ,objectId: '".$this->objectId."'
            ,staffId:'".$this->staffId."'
            ,actionType:2
        ");

        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
            if(window.parent.Ext.getCmp('BLOCK_ATTENDANCE_LIST_ID'))
            window.parent.Ext.getCmp('BLOCK_ATTENDANCE_LIST_ID').store.reload();
            var result = Ext.util.JSON.decode(action.response.responseText);
            window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
        ");
        
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->renderJS();
        ?>
            
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'panel'
                ,id: 'panel'
                ,border: false
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                }]
            }]
        }); 
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>