<?

require_once 'clients/CamemisChart.php';
require_once 'models/statistic/FacilityStatisticsDBAccess.php';

$objectType = isset($_GET["objectType"])?addText($_GET["objectType"]):"";

$dataSet = "[";
$dataSet .= "{'key' : '".CHECK_OUT."','color':'#FFDEDE','values':".FacilityStatisticsDBAccess::getFacilityItemByDayType('CHECK-OUT')."}";
$dataSet .= ",{'key' : '".CHECK_IN."','color':'#99BBE8','values':".FacilityStatisticsDBAccess::getFacilityItemByDayType('CHECK-IN')."}";
$dataSet .= "]";

switch($objectType){
    case "WEEKLY":
        $dataSet = "[";
        $dataSet .= "{'key' : '".CHECK_OUT."','color':'#FFDEDE','values':".FacilityStatisticsDBAccess::getFacilityItemByDayType('CHECK-OUT')."}";
        $dataSet .= ",{'key' : '".CHECK_IN."','color':'#99BBE8','values':".FacilityStatisticsDBAccess::getFacilityItemByDayType('CHECK-IN')."}";
        $dataSet .= "]";
        break;
    case "MONTHLY":
        $dataSet = "[";
        $dataSet .= "{'key' : '".CHECK_OUT."','color':'#FFDEDE','values':".FacilityStatisticsDBAccess::getFacilityItemByWeekType('CHECK-OUT')."}";
        $dataSet .= ",{'key' : '".CHECK_IN."','color':'#99BBE8','values':".FacilityStatisticsDBAccess::getFacilityItemByWeekType('CHECK-IN')."}";
        $dataSet .= "]";
        break;
    case "YEARLY":
        $dataSet = "[";
        $dataSet .= "{'key' : '".CHECK_OUT."','color':'#FFDEDE','values':".FacilityStatisticsDBAccess::getFacilityItemByMonthType('CHECK-OUT')."}";
        $dataSet .= ",{'key' : '".CHECK_IN."','color':'#99BBE8','values':".FacilityStatisticsDBAccess::getFacilityItemByMonthType('CHECK-IN')."}";
        $dataSet .= "]";
        break;
}

$chart = new CamemisChart("MULTI_BAR_CHART", 'chart1', $dataSet);
$chart->chartSVG = "display";
$chart->height = 230;
?>
<!DOCTYPE html>
<meta charset="utf-8">
<link href="http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer" rel="stylesheet" type="text/css">
<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">
<body>
    <script src="/public/nvd3/nvd3-camemis.php"></script>
    <div><?= $chart->setChartDisplay(); ?></div>
    <script><?= $chart->setChartScript(); ?></script>
</body>
</html>
