<?

require_once 'clients/CamemisChart.php';
require_once 'models/statistic/StaffStatisticsDBAccess.php';

$objectType = isset($_GET["objectType"])?addText($_GET["objectType"]):"ALL";

switch($objectType){
    case "ALL":
        $dataSet = StaffStatisticsDBAccess::getDataSetStaff();
        break;
}

$chart = new CamemisChart("MULTIBARCHART", 'chart1', $dataSet);
$chart->chartSVG = "display";
$chart->height = 230;
?>
<!DOCTYPE html>
<meta charset="utf-8">
<link href="http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer" rel="stylesheet" type="text/css">
<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">
<body>
    <script src="/public/nvd3/nvd3-camemis.php"></script>
    <div><?= $chart->setChartDisplay(); ?></div>
    <script><?= $chart->setChartScript(); ?></script>
</body>
</html>
