<?
require_once 'models/statistic/StudentStatisticsDBAccess.php';

$objectType = isset($_GET["objectType"])?$_GET["objectType"]:"";
$academicId = isset($_GET["academicId"])?$_GET["academicId"]:"";
$studentId = isset($_GET["studentId"])?$_GET["studentId"]:"";
$target =  isset($_GET["target"])?addText($_GET["target"]):"";

$dataSet = StudentStatisticsDBAccess::getDataSetStudentAttendance("WEEKLY", $studentId, $academicId, $target);

switch($objectType){
    case "WEEKLY":
        $dataSet = StudentStatisticsDBAccess::getDataSetStudentAttendance("WEEKLY", $studentId, $academicId, $target);
        break;
    case "MONTHLY":
        $dataSet = StudentStatisticsDBAccess::getDataSetStudentAttendance("MONTHLY", $studentId, $academicId, $target);
        break;
    case "YEARLY":
        $dataSet = StudentStatisticsDBAccess::getDataSetStudentAttendance("YEARLY", $studentId, $academicId, $target);
        break;
}

?>
<!DOCTYPE html>
<meta charset="utf-8">

<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">

<style>

body {
    overflow-y:scroll;
}

text {
    font: 11px tahoma,verdana,arial,sans-serif,Hanuman;
}

#chart1 {
    height:230px; 
    margin: 10px;
    min-width: 100px;
    min-height: 100px;
    /*
    Minimum height and width is a good idea to prevent negative SVG dimensions...
    For example width should be =< margin.left + margin.right + 1,
    of course 1 pixel for the entire chart would not be very useful, BUT should not have errors
    */
}

</style>
<body>

<div id="chart1"><svg></svg></div>
<script src="/public/nvd3/nvd3-camemis.php"></script>
<script>

var chart;
nv.addGraph(function() {
    chart = nv.models.multiBarChart()
    .showLegend(false)
    .stacked(true)
    .barColor(d3.scale.category20().range())
    .margin({bottom: 50})
    .transitionDuration(300)
    .delay(0)
    .rotateLabels(0)
    .groupSpacing(0.1)
    ;
    chart.multibar
    .hideable(true);
    chart.reduceXTicks(false).staggerLabels(true);
    chart.xAxis
    .showMaxMin(false)
    .tickFormat(function(d){ return d;});
    chart.yAxis
    .tickFormat(function(d){ return d;});
    d3.select('#chart1 svg')
    .datum(<?=$dataSet?>)
    .call(chart);
    nv.utils.windowResize(chart.update);
    chart.dispatch.on('stateChange', function(e) { nv.log('New State:', JSON.stringify(e)); });
    return chart;
});
</script>
