<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("DATASET", "LIST");
$OBJECT_TREE->setURL("/dataset/jsontree/");
$OBJECT_TREE->setSaveUrl("/dataset/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$READ_RIGHT=UserAuth::getACLValue("FINANCIAL_MANAGEMENT_READ_RIGHT")?"false":"true";
$EDIT_RIGHT= UserAuth::getACLValue("FINANCIAL_MANAGEMENT_EDIT_RIGHT")?"false":"true";

?>
<script>
var parentId;
Ext.onReady(function() {
	
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    
    $OBJECT_TREE->addTBarItems("
        id: 'REFRESH'
        ,scope:this
        ,text:'".REFRESH."'
        ,iconCls:'icon-arrow_refresh'
        ,handler: function(){
            ".CamemisPage::setRequestURI(false)."
        }
    ");
    
    $OBJECT_TREE->setSaveParams("
    	cmd: 'addObject'
        ,type:'income_category'
        ,parentId:parentId
    ");
    
    $OBJECT_TREE->setOnEmbeddedEvents("
        myTree = Ext.getCmp('TREE.DATASET_LIST_ID');
        myNode = myTree.getNodeById(parentId);
        myNode.reload();
        myNode.expand(true, false);
    ");
    
    $OBJECT_TREE->setBaseParams("
    	cmd: 'jsonTreeAllIncomeCategories'
    ");
    if( UserAuth::getACLValue("FINANCIAL_MANAGEMENT_EDIT_RIGHT"))
    $OBJECT_TREE->addTBarItems("
        id: 'ADD_A_NEW_FOLDER'
        ,scope:this
        ,text:'".ADD_A_NEW_FOLDER."'
        ,tooltip:'".ADD_A_NEW_FOLDER."'
        ,iconCls:'icon-application_form_add'
        ,handler: function(){
            clickOpenPage('center','', '/finance/showincomecategory/?objectId=new&parentId=0');
        }
    ");
    
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->objectTitle = INCOME_CATEGORY;
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: false
                ,split: true
            }
            ,items: [{
               	region:'west'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width: 350
                ,minSize: 350
                ,maxSize: 350
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    border: false
                    ,layout: 'anchor'
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items: [{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                    }]
                }]
            }]
        }]
    });
    
    var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('click', function(node, e){
        parentId = node.attributes.parent;
        if(node.isLeaf()){
            var lastNode = 1;
        }else{
            var lastNode = 0;
        }
        var contextMenu = new Ext.menu.Menu({
            items: [{
                text: '<?=SHOW_DETAIL;?>'
                ,hidden:<?=$READ_RIGHT;?>
                ,iconCls:'icon-application_form_magnify'
                ,handler:function(){
                    clickOpenPage('center','', '/finance/showincomecategory/?objectId=' + node.id);
                }
            },{
                text: '<?=ADD_A_NEW_ITEM;?>'
                ,iconCls:'icon-application_form_add'
                ,hidden:<?=$EDIT_RIGHT;?>
                ,handler: function(){
                    clickOpenPage('center','', '/finance/showincomecategory/?objectId=new&parentId=' + node.id + '&lastNode=' + lastNode);
                }
            }]
        });
        e.stopEvent();
        contextMenu.showAt(e.xy);
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>