<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("DATASET");
$OBJECT_FORM->setSaveUrl("/dataset/jsonsave/");
$OBJECT_FORM->setLoadUrl("/dataset/jsonload/");

$CATEGORY_TREE = new CamemisTree("FINANCE", "TAX");
$CATEGORY_TREE ->setURL("/dataset/jsontree/");

$parentId = isset($_GET["parentId"])?$_GET["parentId"]:"";

$parentObject = IncomeCategoryDBAccess::findObjectFromId($parentId);
$lastNode = isset($_GET["lastNode"])?$_GET["lastNode"]:"";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    Ext.form.Field.prototype.msgTarget = 'side';
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $CATEGORY_TREE->isAsyncTreeNode = false;
    $CATEGORY_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
    $CATEGORY_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $CATEGORY_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());

    $CATEGORY_TREE->setBaseParams("
        cmd: 'jsonTreeAllTaxes'
    ");

    $CATEGORY_TREE->backgroundColor = "#F9F9F9";
    $CATEGORY_TREE->isTreeExpand = true;
    $CATEGORY_TREE->renderJS();
    
    $triggerOnClickCategory = "
        openWinXType('TAX','".TAX_CATEGORY."', '".$CATEGORY_TREE->getObjectXType()."', 500, percentHeight(85));
        var myTree = Ext.getCmp('".$CATEGORY_TREE->getObjectId()."');
        myTree.on('click', function(node, e){
        Ext.getCmp('CHOOSE_TAX_NAME_ID').setValue(node.attributes.text);
        Ext.getCmp('HIDDEN_TAX').setValue(node.attributes.id);
        Ext.getCmp('TAX').close();
    });
    ";
    
    $FORM_ITEMS = "[
        {".CamemisField::Textfield("NAME_ID", "NAME", ACCOUNT_NAME)."}
        ,{".CamemisField::Textfield("ACCOUNT_NUMBER", "ACCOUNT_NUMBER", ACCOUNT_NUMBER,true)."}
        ,{".CamemisField::Trigger("CHOOSE_TAX_NAME",TAX_CATEGORY,$triggerOnClickCategory,false, false, false)."}
        ,{".CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false, false)."}
        ,{".CamemisField::Hidden("HIDDEN_TAX", false)."}
    ]"; 

    $DETAIL_INFORMATION = "
    {
        title: '".DETAIL_INFORMATION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: ".$FORM_ITEMS."
        }]
    }
    ";
    
    $DESCRIPTION = "
    {
        title: '".DESCRIPTION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,height: 100
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'padding:5px'
            ,items: [{".CamemisField::Textarea("DESCRIPTION", false,100)."}]
        }]
    }
    ";

    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: [
            ".$DETAIL_INFORMATION."
            ,".$DESCRIPTION."
        ]
    ";
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        }
    ");
    if( UserAuth::getACLValue("FINANCIAL_MANAGEMENT_EDIT_RIGHT"))
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '".$this->objectId."',type:'income_category'");
    if($this->objectId == "new"){
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'updateObject'
            ,type:'income_category'
            ,objectId: '".$this->objectId."'
            ,parentId: '".$parentId."'
        ");
        
        if($lastNode){
            if($parentObject){
                if($parentObject->PARENT){
                    $OBJECT_FORM->setonEmbeddedEvents("
                        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                        myTree = window.parent.Ext.getCmp('TREE.DATASET_LIST_ID');
                        myNode = myTree.getNodeById('".$parentObject->PARENT."');
                        myNode.reload();
                        myNode.expand(true, false);
                    ");
                }else{
                    $OBJECT_FORM->setonEmbeddedEvents("
                        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                        window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.reload();
                        window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.expand(true, false);
                    "); 
                }
            }
        }else{
            if($parentId){
                $OBJECT_FORM->setonEmbeddedEvents("
                    window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                    XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                    myTree = window.parent.Ext.getCmp('TREE.DATASET_LIST_ID');
                    myNode = myTree.getNodeById('".$parentId."');
                    myNode.reload();
                    myNode.expand(true, false);
                ");
            }else{
                $OBJECT_FORM->setonEmbeddedEvents("
                    window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                    window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.reload();
                    window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.expand(true, false);
                "); 
            }
        }
        
    }else{
        if(!$this->check){
            if( UserAuth::getACLValue("FINANCIAL_MANAGEMENT_REMOVE_RIGHT"))
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormEasyRemoveObject());
        }
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'updateObject'
            ,type:'income_category'
            ,objectId: '".$this->objectId."'
        ");
        
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('TREE.DATASET_LIST_ID');
            myNode = myTree.getNodeById('".$this->facette->PARENT."');
            myNode.reload();
            myNode.expand(true, false);
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");
        
        $OBJECT_FORM->setRemoveParams("
            cmd: 'removeObject'
            ,type:'income_category'
            ,objectId: '".$this->objectId."'
        ");

        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.reload();
            window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.expand(true, false);
        ");
    }
    
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>