<?
///////////////////////////////////////////////////////////
// @chungveng
// Date: 11.26.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        $ADVENCED_SEARCH = "{
            title: '".SEARCH."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SEARCH', url: '/facility/searchitems/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $ADVENCED_SEARCH;
        
        $SETTING = "{
            title: '".SETTING."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SETTING', url: '/facility/manageitem/?key=".camemisId()."'})]      
        }";
        $PENEL_ITEMS[] = $SETTING;
    
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true   
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>