<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $LESSONS = "{
            title: 'Lessons'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'LESSONS', url: '/elearning/lesson/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $LESSONS;
        
        $COURSES = "{
            title: 'Courses'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'COURSES', url: '/elearning/course/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $COURSES;
        
        $CATEGORIES = "{
            title: 'Categories'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'CATEGORIES', url: '/elearning/category/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $CATEGORIES;
        
        $FORUM = "{
            title: 'Forum'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'FORUM', url: '/elearning/forum/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $FORUM;
        
        $SETTINGS = "{
            title: 'Settings'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SETTINGS', url: '/elearning/setting/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $SETTINGS;
        
        $REPORTS = "{
            title: 'Reports'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'REPORTS', url: '/elearning/report/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $REPORTS;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>