<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 13.03.2012
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$OBJECT_TREE = new CamemisTree("STAFFS", "LIST");
$OBJECT_TREE->setURL('/staff/jsontree/');

?>
<script>

Ext.onReady(function() {
	
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $TREE_ITEMS = Array();
    
    $SCHEDULE = "{";
        $SCHEDULE .= "text:'".SCHEDULE."'";
        $SCHEDULE .= ",leaf:true";
        $SCHEDULE .= ",url:'/schedule/byclass/?target=training&trainingId=".$this->trainingId."'";
        $SCHEDULE .= ",cls:'nodeTextBold'";
        $SCHEDULE .= ",iconCls: 'icon-component'";
    $SCHEDULE .= "}";
    $TREE_ITEMS[] = $SCHEDULE;
    
    $EVENTS = "{";
        $EVENTS .= "text:'".EVENTS."'";
        $EVENTS .= ",leaf:true";
        $EVENTS .= ",url:'/schoolevent/classevents/?target=training&trainingId=".$this->trainingId."'";
        $EVENTS .= ",cls:'nodeTextBold'";
        $EVENTS .= ",iconCls: 'icon-component_yellow'";
    $EVENTS .= "}";
    $TREE_ITEMS[] = $EVENTS;
    
    $HOMEWORK = "{";
        $HOMEWORK .= "text:'".HOMEWORK."'";
        $HOMEWORK .= ",leaf:true";
        $HOMEWORK .= ",url:'/homework/homeworkmaintraining/?objectId=".$this->objectId."&trainingId=".$this->trainingId."'";
        $HOMEWORK .= ",cls:'nodeTextBold'";
        $HOMEWORK .= ",iconCls: 'icon-component'";
    $HOMEWORK .= "}";
    $TREE_ITEMS[] = $HOMEWORK;
    
    $LIST_OF_STUDENTS = "{";
        $LIST_OF_STUDENTS .= "text:'".LIST_OF_STUDENTS."'";
        $LIST_OF_STUDENTS .= ",leaf:true";
        $LIST_OF_STUDENTS .= ",url:'/training/studentlist/?target=TERM&objectId=".$this->trainingId."'";
        $LIST_OF_STUDENTS .= ",cls:'nodeTextBold'";
        $LIST_OF_STUDENTS .= ",iconCls: 'icon-component_yellow'";
    $LIST_OF_STUDENTS .= "}";
    $TREE_ITEMS[] = $LIST_OF_STUDENTS;
    
    $LIST_OF_TEACHERS = "{";
        $LIST_OF_TEACHERS .= "text:'".LIST_OF_TEACHERS."'";
        $LIST_OF_TEACHERS .= ",leaf:true";
        $LIST_OF_TEACHERS .= ",url:'/training/teacherlist/?objectId=".$this->trainingId."'";
        $LIST_OF_TEACHERS .= ",cls:'nodeTextBold'";
        $LIST_OF_TEACHERS .= ",iconCls: 'icon-component'";
    $LIST_OF_TEACHERS .= "}";
    $TREE_ITEMS[] = $LIST_OF_TEACHERS;
    
    $ASSESSMENT = "{";
        $ASSESSMENT .= "text:'".ASSESSMENT."'";
        $ASSESSMENT .= ",leaf:true";
        $ASSESSMENT .= ",url:'/training/scoremonitortraining/?trainingId=".$this->trainingId."'";
        $ASSESSMENT .= ",cls:'nodeTextBold'";
        $ASSESSMENT .= ",iconCls: 'icon-component_yellow'";
    $ASSESSMENT .= "}";
    $TREE_ITEMS[] = $ASSESSMENT;
    
    $ATTENDANCE_INFORMATION = "{";
        $ATTENDANCE_INFORMATION .= "text:'".ATTENDANCE_INFORMATION."'";
        $ATTENDANCE_INFORMATION .= ",leaf:true";
        $ATTENDANCE_INFORMATION .= ",url:'/attendance/studentclassmain/?target=training&trainingId=".$this->trainingId."'";
        $ATTENDANCE_INFORMATION .= ",cls:'nodeTextBold'";
        $ATTENDANCE_INFORMATION .= ",iconCls: 'icon-component'";
    $ATTENDANCE_INFORMATION .= "}";
    $TREE_ITEMS[] = $ATTENDANCE_INFORMATION;
    
    $DISCIPLINE_INFORMATION = "{";
        $DISCIPLINE_INFORMATION .= "text:'".DISCIPLINE_INFORMATION."'";
        $DISCIPLINE_INFORMATION .= ",leaf:true";
        $DISCIPLINE_INFORMATION .= ",url:'/discipline/byclass/?target=training&trainingId=".$this->trainingId."'";
        $DISCIPLINE_INFORMATION .= ",cls:'nodeTextBold'";
        $DISCIPLINE_INFORMATION .= ",iconCls: 'icon-component_yellow'";
    $DISCIPLINE_INFORMATION .= "}";
    $TREE_ITEMS[] = $DISCIPLINE_INFORMATION;
    
    $CHOOSE_ITEMS = "[".implode(',',$TREE_ITEMS)."]";

    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->isAsyncTreeNode = true;
    $OBJECT_TREE->setAsyncTreeNode($CHOOSE_ITEMS);
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible:true
                ,split: true
            }
            ,items: [{
                title: ''
                ,id:'WEST_ID'
                ,region:'west'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width:200
                ,minSize:200
                ,maxSize:200
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
            },{
                title: ''
                ,border:true
                ,collapsible: false
                ,region:'center'
                ,id: 'center'
                ,layout: 'card'
                ,activeItem: 0
                ,margins: '3 3 3 0'
                ,items: [new Ext.ux.IFrameComponent({ id: 'MAIN_CONTENT', url:'/schedule/byclass/?target=training&trainingId=<?=$this->trainingId?>'})]
            }]
        }]
    });

    var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('click', function(node, event){
        clickOpenPage('center','',node.attributes.url);
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>