<?
///////////////////////////////////////////////////////////
//@Chung veng Web Developer
//Date: 22.06.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("CLUB");

$OBJECT_FORM->setLoadUrl("/club/jsonload/");
$OBJECT_FORM->setSaveUrl("/club/jsonsave/");

if(!$this->facette){
    $reloadId = isset($_GET['parentId'])?$_GET['parentId']:0;
}else{
    $reloadId = $this->facette?$this->facette->PARENT:0; 
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script> 
    
    Ext.onReady(function() {
        function cssText(value, metadata, record){
            return '<div style="font-weight:normal; color:#333; padding: 5px;">' + value + '</div>';
        }
        <?
       
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();  
        
        $DETAIL_INFORMATION = "
        {
            title: '".NAME."'
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {".CamemisField::Textfield("NAME", "NAME", NAME, true)."}
                ]
            }]
        }";     
        $DESCRIPTION = "
        {
            title: '".DESCRIPTION."'
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,bodyStyle: 'padding:5px'
                ,items: [{".CamemisField::Textarea('DESCRIPTION', false, 150, false, false, false)."}]
            }]
        }";       
        $ITEMS = "[";
        $ITEMS .= $DETAIL_INFORMATION;
        $ITEMS .= ",".$DESCRIPTION; 
        $ITEMS .= "]";    
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,autoScroll: true
            ,bodyStyle: 'background:#FFF; padding:10px'
            ,items: [".$ITEMS."]
        ";
         
        $OBJECT_FORM->addObjectItems($items);
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        ");
        $OBJECT_FORM->setLoadParams("cmd: 'jsonLoadClub',objectId: '".$this->objectId."'");
        switch(UserAuth::getUserType()){
            case "ADMIN":
            case "SUPERADMIN":
               
                $OBJECT_FORM->setReleaseParams("cmd: 'jsonReleaseClub',objectId: '".$this->objectId."'");
                $OBJECT_FORM->setSaveParams("
                    cmd: 'jsonSaveClub'
                    ,objectId: '".$this->objectId."'
                    ,parentId: '".$this->parentId."'
                ");
                
                if($this->facette){
                    
                    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
                    if($this->facette->STATUS){
                        $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormRemoveObject(false));
                    }else{
                        $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormRemoveObject(true));
                    } 
                   
                    $OBJECT_FORM->setRemoveParams("
                        cmd: 'jsonRemoveClub'
                        ,objectId: '".$this->objectId."'
                    ");
                    $OBJECT_FORM->setOnEmbeddedReleaseEvents("
                        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');     
                        myTree = window.parent.Ext.getCmp('TREE.CLUB_LIST_ID');
                        myNode = myTree.getNodeById('".$this->facette->PARENT."');
                        myNode.reload();
                        myNode.expand(true, false);
                        //myNode.setText(action.result.text);
                        ".camemisPage::setRequestURI()."
                    ");
                }
               
                if($reloadId){
                    $OBJECT_FORM->setonEmbeddedEvents("
                        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                        myTree = window.parent.Ext.getCmp('TREE.CLUB_LIST_ID');
                        myNode = myTree.getNodeById('".$reloadId."');
                        if(myNode.parentNode==null){
                            myTree.root.reload();
                        }else{
                            var parentId = myNode.parentNode.id
                            myPerentNode = myTree.getNodeById(parentId);
                            if(myNode.isLeaf()){
                                if(myPerentNode){
                                    myPerentNode.reload();
                                    myPerentNode.expand(true, false);
                                }else{
                                    myTree.root.reload();
                                }
                            }else{
                                if (myNode.hasChildNodes()) {
                                    myNode.reload();
                                    myNode.expand(true, false);
                                }
                            }
                        }
                        var result = Ext.util.JSON.decode(action.response.responseText);
                        window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
                    ");
                    
                    $OBJECT_FORM->setOnEmbeddedRemoveEvents("
                        myTree = window.parent.Ext.getCmp('TREE.CLUB_LIST_ID');
                        myNode = myTree.getNodeById('".$reloadId."');
                        myNode.reload();
                        myNode.expand(true, false);
                        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                    ");
                }else{
                    $OBJECT_FORM->setonEmbeddedEvents("
                        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                        myTree = window.parent.Ext.getCmp('TREE.CLUB_LIST_ID');
                        myNode = myTree.getNodeById('".$reloadId."');
                        if(myNode.parentNode==null){
                            myNode.root.reload();
                        }else{
                            myNode.reload();
                            myNode.expand(true, false);
                        }

                        var result = Ext.util.JSON.decode(action.response.responseText);
                        window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
                    ");

                    $OBJECT_FORM->setOnEmbeddedRemoveEvents("
                        myTree = window.parent.Ext.getCmp('TREE.CLUB_LIST_ID');
                        myTree.root.reload();
                        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                    "); 
                }  
                $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
            break;
        }
        $OBJECT_FORM->isObjectDefaultOnLoad = true;
        $OBJECT_FORM->bodyStyle = "padding:0px";
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->renderJS();
        
        if($this->facette){
            $VIEWPORT_ITEMS = "";
            $VIEWPORT_ITEMS .= "[{";
                $VIEWPORT_ITEMS .= "layout:'fit'";
                $VIEWPORT_ITEMS .= ",bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px;'";
                $VIEWPORT_ITEMS .= ",border:false";
                $VIEWPORT_ITEMS .= ",items:[{";
                    $VIEWPORT_ITEMS .= "layout: 'fit'"; 
                    $VIEWPORT_ITEMS .= ",items:[{xtype: '".$OBJECT_FORM->getObjectXtype()."'}]"; 
                $VIEWPORT_ITEMS .= "}]";     
            $VIEWPORT_ITEMS .= "}]";    
            
        }else{
            $VIEWPORT_ITEMS = "";
            $VIEWPORT_ITEMS .= "[{";
                $VIEWPORT_ITEMS .= "border: false";
                $VIEWPORT_ITEMS .= ",id: 'content'";
                $VIEWPORT_ITEMS .= ",layout: 'card'";
                $VIEWPORT_ITEMS .= ",activeItem: 0";
                $VIEWPORT_ITEMS .= ",items:[{xtype: '".$OBJECT_FORM->getObjectXtype()."'}]"; 
            $VIEWPORT_ITEMS .= "}]";
        }
        ?> 
         viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px;'
                ,border:false
                ,items:[{
                    layout: 'fit' 
                    ,items:<?=$VIEWPORT_ITEMS?>
                }]     
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>