<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'include/Common.inc.php';
require_once 'models/app_school/bulletin/BulletinDBAccess.php';
require_once 'models/CAMEMISUploadDBAccess.php';
require_once 'models/CAMEMISYoutubeDBAccess.php';
require_once setUserLoacalization();

$objectId = isset($_GET["objectId"]) ? $_GET["objectId"] : '';

$facette = BulletinDBAccess::findBulletinFromId($objectId);

$BLOB_1 = CAMEMISUploadDBAccess::getFileFromObjectId($facette->GUID, 1, "BULLETIN");
$BLOB_2 = CAMEMISUploadDBAccess::getFileFromObjectId($facette->GUID, 2, "BULLETIN");;
$BLOB_3 = CAMEMISUploadDBAccess::getFileFromObjectId($facette->GUID, 3, "BULLETIN");

function showFile($id, $blobName, $blobSize){
    $js = "
        html: '<span class=Text>".$blobName." ".$blobSize."</span>'
        ,id: '".$id."'
        ,bodyStyle: 'padding:5px; background-color:#FFFFFF'
        ,border: false
    ";
    
    return $js;
}

if($BLOB_1){
    $SHOW_FILE_1 = $BLOB_1->FILE_SHOW;
    $DISABLED_SHOW_FILE_1 = "false";
    $DISABLED_DELETE_FILE_1 = "false";
}else{
    $SHOW_FILE_1 = "";
    $DISABLED_SHOW_FILE_1 = "true";
    $DISABLED_DELETE_FILE_1 = "true";
}

if($BLOB_2){
    $SHOW_FILE_2 = $BLOB_2->FILE_SHOW;
    $DISABLED_SHOW_FILE_2 = "false";
    $DISABLED_DELETE_FILE_2 = "false";
}else{
    $SHOW_FILE_2 = "";
    $DISABLED_SHOW_FILE_2 = "true";
    $DISABLED_DELETE_FILE_2 = "true";
}

if($BLOB_3){
    $SHOW_FILE_3 = $BLOB_3->FILE_SHOW;
    $DISABLED_SHOW_FILE_3 = "false";
    $DISABLED_DELETE_FILE_3 = "false";
}else{
    $SHOW_FILE_3 = "";
    $DISABLED_SHOW_FILE_3 = "true";
    $DISABLED_DELETE_FILE_3 = "true";
}

$BLOB_NAME_1 = isset($BLOB_1->FILE_NAME)?$BLOB_1->FILE_NAME:"---";
$BLOB_NAME_2 = isset($BLOB_2->FILE_NAME)?$BLOB_2->FILE_NAME:"---";
$BLOB_NAME_3 = isset($BLOB_3->FILE_NAME)?$BLOB_3->FILE_NAME:"---";

$BLOB_SIZE_1 = isset($BLOB_1->FILE_SIZE)?""._format_bytes($BLOB_1->FILE_SIZE)."":"";
$BLOB_SIZE_2 = isset($BLOB_2->FILE_SIZE)?""._format_bytes($BLOB_2->FILE_SIZE)."":"";
$BLOB_SIZE_3 = isset($BLOB_3->FILE_SIZE)?""._format_bytes($BLOB_3->FILE_SIZE)."":"";

$params["objectId"] = $objectId;
$videos = CAMEMISYoutubeDBAccess::sqlVideos($params);

function showVideo($key){
    $html = "
    <div style=\"padding-top:20px;\">
        <object width=\"640\" height=\"385\"><param name=\"movie\" value=\"http://www.youtube.com/v/".$key."\"></param><param name=\"allowscriptaccess\" value=\"always\"></param><embed src=\"http://www.youtube.com/v/".$key."\" type=\"application/x-shockwave-flash\" allowscriptaccess=\"always\" width=\"640\" height=\"385\"></embed></object>
    </div>
    ";
    return $html;
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/></meta></head>
<title>CAMEMIS Easy and Efficient Education Management</title>
<link href="http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer" rel="stylesheet" type="text/css">
<body style="background-color: #FFFFFF;">
    <style>
    body{
        font:normal 11px Tahoma, Arial, sans-serif,Hanuman;
    }
    </style>
    <h1><?=isset($facette)?showNewlineText($facette->SUBJECT_BULLETIN):"---"?></h1>
    <?=isset($facette)?$facette->CONTENT:"---"?>
    <?
    if($videos) foreach($videos as $value){
        echo showVideo($value->YOUTUBE);
    }
    
    if($BLOB_NAME_1!="---"){
        echo "<p><a href=\"/dataset/showblob/?blobId=".$SHOW_FILE_1."\" target=\"_blank\">".$BLOB_NAME_1." (".$BLOB_SIZE_1.")</a></p>";
    }
    if($BLOB_NAME_2!="---"){
        echo "<p><a href=\"/dataset/showblob/?blobId=".$SHOW_FILE_2."\" target=\"_blank\">".$BLOB_NAME_2." (".$BLOB_SIZE_2.")</a></p>";
    }
    if($BLOB_NAME_3!="---"){
        echo "<p><a href=\"/dataset/showblob/?blobId=".$SHOW_FILE_3."\" target=\"_blank\">".$BLOB_NAME_3." (".$BLOB_SIZE_3.")</a></p>";
    }
    ?>
</body>
</html>

