<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("FINANCE", "LIST");

$READ_RIGHT = UserAuth::getACLValue("FINANCIAL_MANAGEMENT_READ_RIGHT")?"true":"false";

print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();

//@veasna
$param['objectType']='objectType';
$param["node"]='';
$object=AcademicLevelDBAccess::getSQLAllAcademics($param);
$objectTraining=StudentFeePrepaidDBAccess::getTrainingPrograme();
$training="";
$campus="";

if($objectTraining){
    
    $j=0;
    foreach($objectTraining as $value){
        
        if($j){
            $training.=",";    
        }
        $training.="{";
            $training .= "text:'".$value->NAME."'";
            $training .= ",iconCls:'icon-plugin'";
            $training .= ",leaf:true";
            $training .= ",url:'/finance/studentprepaidtraining/?objectId=".$value->ID."'";
            $training .= ",cls:'nodeTextBlue'";
            $training .= ",isClick:".$READ_RIGHT."";   
        $training.="}";
        
        $j++;
    }
        
}

if($object){
    $i=0;
    foreach($object as $values){
        if($i){
            $campus.=",";    
        }
        $campus.="{";
            $campus .= "text:'".$values->NAME."'";
            $campus .= ",iconCls:'icon-plugin'";
            $campus .= ",leaf:true";
            $campus .= ",url:'/finance/studentprepaidgeneral/?objectId=".$values->ID."'";
            $campus .= ",cls:'nodeTextBlue'";
            $campus .= ",isClick:".$READ_RIGHT."";
        $campus.="}";
        
        $i++;
    }        
}
//

?>
<script>
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        /////
         $FEE_MANAGEMENT_ITEM = array();
         
         $GENERAL_EDUCATION= "{
            text:'".HIGHER_EDUCATION."'
            ,iconCls:'icon-folder_magnify'
            ,leaf:false
            ,cls:'nodeTextBold'
            ,isClick:false
            ,expanded:true
            ,children:[
             {
                text:'".FEES."'
                ,iconCls:'icon-plugin'
                ,leaf:true
                ,url:'/finance/feeenrollment/'
                ,cls:'nodeTextBlue'
                ,isClick:".$READ_RIGHT."
           },{
               text:'".STUDENT_SERVICES."'
                ,iconCls:'icon-plugin'
                ,leaf:true
                ,url:'/finance/feeservices/?type=GENERAL_EDU'
                ,cls:'nodeTextBlue'
                ,isClick:".$READ_RIGHT."
           },{
                text:'".PREPAY_FEE."'
                ,iconCls:'icon-folder_magnify'
                ,leaf:false
                ,cls:'nodeTextBold'
                ,isClick:false
                ,expanded:false
                ,children:[".$campus."]
           }]
        }";
        
        
        $TRAINING_PROGRAMS= "{
            text:'".TRAINING_PROGRAMS."'
            ,iconCls:'icon-folder_magnify'
            ,leaf:false
            ,cls:'nodeTextBold'
            ,isClick:false
            ,expanded:true
            ,children:[
            {
                text:'".FEES."'
                ,iconCls:'icon-plugin'
                ,leaf:true
                ,url:'/finance/feecourse/'
                ,cls:'nodeTextBlue'
                ,isClick:".$READ_RIGHT."
            },{
                text:'".STUDENT_SERVICES."'
                ,iconCls:'icon-plugin'
                ,leaf:true
                ,url:'/finance/feeservices/?type=COURSE'
                ,cls:'nodeTextBlue'
                ,isClick:".$READ_RIGHT."
            },{
                text:'".PREPAY_FEE."'
                ,iconCls:'icon-folder_magnify'
                ,leaf:false
                ,cls:'nodeTextBold'
                ,isClick:false
                ,expanded:false
                ,children:[".$training."]
            }]
        }";
        
        if(UserAuth::displayRoleGeneralEducation())
            $FEE_MANAGEMENT_ITEM[]=$GENERAL_EDUCATION;
        if(UserAuth::displayRoleTrainingEducation())
            $FEE_MANAGEMENT_ITEM[]=$TRAINING_PROGRAMS;
        $CHOOSE_FEE_MANAGEMENT_ITEM = implode(",", $FEE_MANAGEMENT_ITEM);
        /////
        $TREE_ITEM = "";
        $TREE_ITEM .= "[{";
        $TREE_ITEM .= "text:'".FEE_MANAGEMENT."'";
        $TREE_ITEM .= ",iconCls:'icon-folder_magnify'";
        $TREE_ITEM .= ",cls:'nodeTextBold'";
        $TREE_ITEM .= ",expanded:true";
        $TREE_ITEM .= ",isClick:false";
        $TREE_ITEM .= ",children:[".$CHOOSE_FEE_MANAGEMENT_ITEM."]";
      
        $TREE_ITEM .= "},{";
        $TREE_ITEM .= "text:'".INCOME_TRANSACTION."'";
        $TREE_ITEM .= ",iconCls:'icon-folder_magnify'";
        $TREE_ITEM .= ",cls:'nodeTextBold'";
        $TREE_ITEM .= ",expanded:true";
        $TREE_ITEM .= ",isClick:".$READ_RIGHT."";
        $TREE_ITEM .= ",url:'/finance/income/'";
        $TREE_ITEM .= ",children:[";
            $TREE_ITEM .= "{";
                $TREE_ITEM .= "text:'".INCOME_CATEGORY."'";
                $TREE_ITEM .= ",iconCls:'icon-plugin'";
                $TREE_ITEM .= ",leaf:true";
                $TREE_ITEM .= ",url:'/finance/incomecategory/'";
                $TREE_ITEM .= ",cls:'nodeTextBlue'";
                $TREE_ITEM .= ",isClick:".$READ_RIGHT."";
            $TREE_ITEM .= "}";
        $TREE_ITEM .= "]";
        
        $TREE_ITEM .= "},{";
        $TREE_ITEM .= "text:'".EXPENSE_TRANSACTION."'";
        $TREE_ITEM .= ",iconCls:'icon-folder_magnify'";
        $TREE_ITEM .= ",cls:'nodeTextBold'";
        $TREE_ITEM .= ",expanded:true";
        $TREE_ITEM .= ",isClick:".$READ_RIGHT."";
        $TREE_ITEM .= ",url:'/finance/expense/'";
        $TREE_ITEM .= ",children:[";
            $TREE_ITEM .= "{";
                $TREE_ITEM .= "text:'".EXPENSE_CATEGORY."'";
                $TREE_ITEM .= ",iconCls:'icon-plugin'";
                $TREE_ITEM .= ",leaf:true";
                $TREE_ITEM .= ",url:'/finance/expensecategory/'";
                $TREE_ITEM .= ",cls:'nodeTextBlue'";
                $TREE_ITEM .= ",isClick:".$READ_RIGHT."";
            $TREE_ITEM .= "}";
        $TREE_ITEM .= "]";
        
        $TREE_ITEM .= "},{";
        $TREE_ITEM .= "text:'".FINANCIAL_SETTING."'";
        $TREE_ITEM .= ",iconCls:'icon-folder_magnify'";
        $TREE_ITEM .= ",cls:'nodeTextBold'";
        $TREE_ITEM .= ",expanded:true";
        $TREE_ITEM .= ",isClick:false";
        $TREE_ITEM .= ",children:[";
            $TREE_ITEM .= "{";
                $TREE_ITEM .= "text:'".TAX_CATEGORY."'";
                $TREE_ITEM .= ",iconCls:'icon-plugin'";
                $TREE_ITEM .= ",leaf:true";
                $TREE_ITEM .= ",url:'/finance/tax/'";
                $TREE_ITEM .= ",cls:'nodeTextBlue'";
                $TREE_ITEM .= ",isClick:".$READ_RIGHT."";
            $TREE_ITEM .= "}";
            $TREE_ITEM .= ",{";
             $TREE_ITEM .= "text:'".FINANCE_DESCRIPTION."'";
                $TREE_ITEM .= ",iconCls:'icon-plugin'";
                $TREE_ITEM .= ",leaf:true";
                $TREE_ITEM .= ",url:'/finance/financedescription/'";
                $TREE_ITEM .= ",cls:'nodeTextBlue'";
                $TREE_ITEM .= ",isClick:".$READ_RIGHT."";
                $TREE_ITEM .= "}";
        $TREE_ITEM .= "]";
        
        $TREE_ITEM .= "}]";
        
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        $OBJECT_TREE->isAsyncTreeNode = true;
        $OBJECT_TREE->setAsyncTreeNode($TREE_ITEM);
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    region:'west'
                    ,title:'<?=FINANCIAL_MANAGEMENT?>'
                    ,id: 'WEST_ID'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width: 250
                    ,minSize: 250
                    ,maxSize: 250
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                },{
                    collapsible: false
                    ,title:''
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,items: [new Ext.ux.IFrameComponent({ id: 'URL_FEE', url: '/finance/feeenrollment/'})]
                }]
            }]
        });
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node, e){
            if(node.attributes.isClick) clickOpenPage('center','', node.attributes.url);
        });
    });
</script>
<?
print$CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>