<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_GRID = new CamemisGrid("GRADINGSYSTEM", "EDUCATION");
$OBJECT_GRID->setLoadUrl('/academicsetting/jsonload/');
$OBJECT_GRID->setSaveUrl('/academicsetting/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$eduSystem = isset($_GET["eduSystem"])? addText($_GET["eduSystem"]):"";
?>
<script>
Ext.onReady(function() {
	
    function showText(v){
        return String.format('<div style=\"font-weight:normal;color:#333;\">{0}</div>'
            ,v
        );
    }
    
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    ////////////////////////////////////////////////////////////////////////////
    $OBJECT_GRID->addReadField("name: 'ID'");
    $OBJECT_GRID->addReadField("name: 'ENGLISH'");
    $OBJECT_GRID->addReadField("name: 'LETTER_GRADE'");
    $OBJECT_GRID->addReadField("name: 'GRADE_POINTS'");
    $OBJECT_GRID->addReadField("name: 'MARK'");
    $OBJECT_GRID->addReadField("name: 'DESCRIPTION'");
    $OBJECT_GRID->addReadField("name: 'SCORE_TYPE'");
    
    $OBJECT_GRID->addColumn("
        editor: new Ext.form.TextField({
            allowBlank: false
        })
        ,align: 'center'
        ,renderer: showText
        ,header: '<b>".LETTER_GRADE."</b>'
        ,dataIndex: 'LETTER_GRADE'
        ,width: 120
    ");
    
    $OBJECT_GRID->addColumn("
        align: 'center'
        ,renderer: showText
        ,header: '<b>".GRADE_POINTS."</b>'
        ,dataIndex: 'GRADE_POINTS'
        ,width: 120
    ");
    
    $OBJECT_GRID->addColumn("
        align: 'center'
        ,renderer: showText
        ,header: '<b>".MARK." (%)</b>'
        ,dataIndex: 'MARK'
        ,width: 120
    ");
    
    $OBJECT_GRID->addColumn("
        align: 'center'
        ,renderer: showText
        ,header: '<b>".DESCRIPTION."</b>'
        ,dataIndex: 'DESCRIPTION'
        ,width: 120
    ");
    
    $OBJECT_GRID->addColumn("
        align: 'center'
        ,renderer: showText
        ,header: '<b>".ENGLISH."</b>'
        ,dataIndex: 'ENGLISH'
        ,width: 120
    ");
    
    $OBJECT_GRID->addColumn("
        align: 'center'
        ,renderer: showText
        ,header: '<b>".SCORE_TYPE."</b>'
        ,dataIndex: 'SCORE_TYPE'
        ,width: 200
    ");
    
    $OBJECT_GRID->setSaveParams("
        cmd: 'actionGradingSystem'
        ,eduSystem: '".$eduSystem."'
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonListGradingSystems'
        ,eduSystem: '".$eduSystem."'
    ";
    
    $OBJECT_GRID->addTBarItems("
        tbar.add(['-',{
            text: '<b>" . REFRESH . "</b>'
            ,iconCls:'icon-arrow_refresh'
            ,handler: function(){
                Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
            }
        }]);
    ");
    
    //if (UserAuth::getACLValue("ACADEMIC_SETTING_EDIT_RIGHT"))
    $OBJECT_GRID->addTBarItems("
        tbar.add(['-',{
            text: '" . ADD_NEW_ITEM . "'
            ,iconCls:'icon-application_form_add'
            ,handler: function(){
                clickOpenPage('content','" . ADD_NEW_ITEM . "','/academicsetting/showgradingsystem/?&target=".camemisId()."&objectId=new&eduSystem=".$eduSystem."');
            }
        }]);
    ");

    $OBJECT_GRID->addTBarItems("
        tbar.add(['-', {
            text:''
            ,tooltip:'".CAMEMIS_HELP."'
            ,iconCls: 'icon-help'
            ,handler:function(){
                ".CamemisPage::setEmbeddedHelp("7FB3-3AC3")."
            }
        }]);    
      ");

    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    //if (UserAuth::getACLValue("ACADEMIC_SETTING_EDIT_RIGHT"))
    $OBJECT_GRID->isGridEditing = false;
    $OBJECT_GRID->renderJS();
    
    ////////////////////////////////////////////////////////////////////////////
    $html = "";
    $html .="viewport = new Ext.Viewport({";
        $html .="layout: 'fit'";
        $html .=",border: false";
        $html .=",items:[{";
            $html .="id:'content'";
            $html .=",layout:'card'";
            $html .=",border:false";
            $html .=",activeItem: 0";
            $html .=",items:[{xtype: '".$OBJECT_GRID->getObjectXtype()."'}]";
        $html .="}]";
    $html .="});";
    
    $SHOW_DETAIL ="{";
    $SHOW_DETAIL .="text: '".SHOW_DETAIL." &raquo; ' + record.data.LETTER_GRADE";
    $SHOW_DETAIL .=",iconCls: 'icon-application_form_magnify'";
    $SHOW_DETAIL .=",handler: function(){"; 
    $SHOW_DETAIL .="clickOpenPage('content',record.data.LETTER_GRADE,'/academicsetting/showgradingsystem/?&target=".camemisId()."&objectId=' + record.data.ID);";
    $SHOW_DETAIL .="}";
    $SHOW_DETAIL .="}";
    
    $CONTEXTMENU_ITEMS[] = $SHOW_DETAIL;
    $CHOOSE_CONTEXTMENU_ITEMS = implode(",", $CONTEXTMENU_ITEMS);
    
    if($CONTEXTMENU_ITEMS){
        
        $html .="var grid = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');";
        $html .="if (grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {";
            $html .="var record = grid.store.getAt(rowIndex);";
            $html .="var contextMenu = new Ext.menu.Menu({";
            $html .="items: [".$CHOOSE_CONTEXTMENU_ITEMS."]";
            $html .="});";
            $html .="event.stopEvent();";
            $html .="contextMenu.showAt(event.xy);"; 
        $html .="});";
        echo $html;
    }
    ?>
    Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>