<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTrainingTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTrainingTree("TRAINING","LIST");
$OBJECT_TREE->setURL("/training/jsontree/");
$OBJECT_TREE->setSaveUrl("/training/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        $OBJECT_TREE->setBaseParams("
            cmd: 'jsonTreeAllTrainings'
        ");
        $OBJECT_TREE->isOnClickContextMenu = false;
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isTreeExpand = false;
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout: 'card'
                ,border: false
                ,activeItem: 0
                ,id: 'CONTENT'
                ,items:[{
                    layout:'border'
                    ,border: false
                    ,defaults: {
                        collapsible: true
                        ,split: true
                    }
                    ,items: [{
                        id: 'TRAINING_ID'
                        ,region:'west'
                        ,title: '&nbsp;'
                        ,autoScroll: true
                        ,margins: '3 0 3 3'
                        ,cmargins: '3 3 3 3'
                        ,width:280
                        ,minSize:280
                        ,maxSize:280
                        ,layout: 'fit'
                        ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                    },{
                        collapsible: false
                        ,id: 'center'
                        ,region:'center'
                        ,margins: '3 3 3 0'
                        ,layout: 'card'
                        ,activeItem: 0
                        ,bodyStyle: 'padding:1px'
                        ,items: [{
                            border: false
                            ,layout: 'anchor'
                            ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                            ,items: [{
                                title: ''
                                ,height:60
                                ,width:500
                                ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                                ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                            }]
                        }]
                    }]
                }]
            }]
        });
        
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node){
            if(node.isLeaf()){
                clickOpenPage('center',node.text, '/attendance/studentclassmain/?target=training&trainingId=' + node.id);
                Ext.getCmp('TRAINING_ID').collapse();
            }
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>