<?
////////////////////////////////////////////////////////////////////////////////
// @Sea Peng
// Date: 27.08.2013
////////////////////////////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$params = "";
if($this->studentId) $params .= "&studentId=".$this->studentId."";
if($this->classId) $params .= "&classId=".$this->classId."";
if($this->target) $params .= "&target=".$this->target."";

?>
<script>
    ////////////////////////////////////////////////////////////////////////////
    //@Viewport
    ////////////////////////////////////////////////////////////////////////////
    Ext.onReady(function() {
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,layout: 'fit'
                ,tbar:[{
                    text:'<?=REFRESH?>'
                    ,iconCls:'icon-arrow_refresh'
                    ,handler: function(){
                        window.location="<?=CamemisPage::setRequestURI()?>";
                    }
                }]
                ,items:[{
                    layout:'column'
                    ,height:percentHeight(100)
                    ,autoScroll:true
                    ,border:false
                    ,defaults: {
                        layout: 'anchor'
                        ,defaults: {anchor: '100%'}
                    }
                    ,items: [{
                        columnWidth: 1
                        ,baseCls:'x-plain'
                        ,bodyStyle:'padding:5px 5px 5px 5px'
                        ,items:[{
                            title: '<?=WEEK?>'
                            ,layout: 'fit'
                            ,collapsible: true
                            ,collapsed: false
                            ,height:350
                            ,items: [new Ext.ux.IFrameComponent({ id: 'STUDENT_ATTENDANCE_WEEKLY', url:'/chart/studentattendance/?camIds=<?=$this->urlEncryp->encryptedGet("".$params."&objectType=WEEKLY")?>'})]
                        }]
                    },{
                        columnWidth: 1
                        ,baseCls:'x-plain'
                        ,bodyStyle:'padding:0px 5px 5px 5px'
                        ,items:[{
                            title: '<?=MONTH?>'
                            ,layout: 'fit'
                            ,collapsible: true
                            ,collapsed: false
                            ,height:350
                            ,items: [new Ext.ux.IFrameComponent({ id: 'STUDENT_ATTENDANCE_MONTHLY', url:'/chart/studentattendance/?camIds=<?=$this->urlEncryp->encryptedGet("".$params."&objectType=MONTHLY")?>'})]
                        }]    
                    },{
                        columnWidth: 1
                        ,baseCls:'x-plain'
                        ,bodyStyle:'padding:0px 5px 5px 5px'
                        ,items:[{
                            title: '<?=YEAR?>'
                            ,layout: 'fit'
                            ,collapsible: true
                            ,collapsed: false
                            ,height:350
                            ,items: [new Ext.ux.IFrameComponent({ id: 'STUDENT_ATTENDANCE_YEARLY', url:'/chart/studentattendance/?camIds=<?=$this->urlEncryp->encryptedGet("".$params."&objectType=YEARLY")?>'})]
                        }]    
                    }]///////////////////be continune
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>
