<?
///////////////////////////////////////////////////////////
// @Chuy Thong Senior Software Developer
// Date: 08.08.2014
// Phnom Penh, Cambodia
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("TRANSLATION", "LIST");
$OBJECT_GRID->setLoadUrl('/log/jsonload/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>

    Ext.onReady(function() {

    <?
    /**
     * Extjs: s.gif
     */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    $OBJECT_GRID->addCellRenderer("
        function renderText(v, p, record, rowIndex){
            return String.format('<div style=\"font-weight:normal;white-space:normal;padding:5px;\">{0}</div>'
                ,v
            );
        }
    ");

    $OBJECT_GRID->addReadField("name: 'ID'");
    $OBJECT_GRID->addReadField("name: 'ACCESSED_DATE'");
    $OBJECT_GRID->addReadField("name: 'ACCESSED_BY'");    
    $OBJECT_GRID->addReadField("name: 'TABLE_NAME'");
    $OBJECT_GRID->addReadField("name: 'FIELD_NOTE'");

    if (Zend_Registry::get('SYSTEM_LANGUAGE')!="ENGLISH")
    $OBJECT_GRID->addReadField("name: '".Zend_Registry::get('SYSTEM_LANGUAGE')."'");

    $OBJECT_GRID->addColumn("header: 'ID', renderer: renderText, hidden: true,align:'left', width: 250, dataIndex: 'ID'");
    $OBJECT_GRID->addColumn("header: '".ACCESSED_DATE."', renderer: renderText, align:'left', width: 125, dataIndex: 'ACCESSED_DATE'");
    $OBJECT_GRID->addColumn("header: '".ACCESSED_BY."', renderer: renderText, align:'left', width: 125, dataIndex: 'ACCESSED_BY'");
    $OBJECT_GRID->addColumn("header: '".TABLE_NAME."', renderer: renderText, align:'left', width: 150, dataIndex: 'TABLE_NAME'");
    $OBJECT_GRID->addColumn("header: '".FIELD_NOTE."', renderer: renderText, align:'left', width: 250, dataIndex: 'FIELD_NOTE'");

    if (Zend_Registry::get('SYSTEM_LANGUAGE')!="ENGLISH")
    $OBJECT_GRID->addColumn("header: '".Zend_Registry::get('SYSTEM_LANGUAGE')."', renderer: renderText,align:'left', width: 450, dataIndex: '".constant(UserAuth::systemLanguage())."'");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'getLogs'
    ";
    
    $OBJECT_GRID->addTBarItems("
        tbar.add('->');
    ");
    
    $OBJECT_GRID->isQuickySearch = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();

    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,id:'content'
            ,layout: 'card'
            ,activeItem: 0
            ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}]
        }]
    });
    
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>