<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $FACILITY_DASHBOARD = "{
            title: '".FACILItY_DASHBOARD."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'FACILITY_DASHBOARD', url: '/facility/main/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $FACILITY_DASHBOARD;
        
               
        $CHECK_OUT_ITEM = "{
            title: '".CHECK_OUT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'CHECK_OUT_ITEM', url: '/facility/checkoutmain/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $CHECK_OUT_ITEM;
        
        $CHECK_IN_ITEM = "{
            title: '".CHECK_IN."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'CHECK_IN_ITEM', url: '/facility/checkinmain/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $CHECK_IN_ITEM;
        
         $FACILITY = "{
            title: '".ITEM."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ITEMS', url: '/facility/facilityitemtabs/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $FACILITY;
        
        $FACILITY_CATEGORY = "{
            title: '".FACILITY_CATEGORY."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'FACILITY_CATEGORY', url: '/facility/managetype/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $FACILITY_CATEGORY;
        
        $FIELD_SETTING = "{
            title: '".FACILITY_FIELD_SETTINGS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'FIELD_SETTING', url: '/facility/fieldsetting/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $FIELD_SETTING;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>