<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 10.07.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_school/FileDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("FILE_SYSTEM");
$OBJECT_FORM->setLoadUrl("/file/jsonload/");
$OBJECT_FORM->setSaveUrl("/file/jsonsave/");

if($this->objectId == "new"){
    $parentId = isset($_GET['parentId'])?addText($_GET['parentId']):0;
}else{
    $parentId = $this->facette?$this->facette->PARENT:0;
    $checkChild = FileDBAccess::checkChild($this->objectId); 
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $DETAIL_INFORMATION = "
        {
            title: '".NAME."'
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: [
                    {".CamemisField::Textfield("NAME", "NAME", NAME, true)."}
                ]
            }]
        }
        ";
        
        $DESCRIPTION = "
        {
            title: '".DESCRIPTION."'
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,bodyStyle: 'padding:5px'
                ,items: [{".CamemisField::Textarea('DESCRIPTION', false, 150, false, false, false)."}]
            }]
        }
        ";
        
        if($this->facette){
            $items = "
                border: false
                ,id: 'FORM_ITEMS'
                ,bodyStyle: 'padding:0px'
                ,items: [
                    ".$DETAIL_INFORMATION."
                    ,".$DESCRIPTION."
                ]
            ";
        }else{
            $items = "
                border: false
                ,id: 'FORM_ITEMS'
                ,bodyStyle: 'padding:0px'
                ,items: [
                    ".$DETAIL_INFORMATION."
                ]
            ";
        }
        
        $OBJECT_FORM->addObjectItems($items);

        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        ");
        
        if($this->facette){
            $OBJECT_FORM->setLoadParams("cmd: 'jsonLoadFile',objectId: '".$this->objectId."'");
        }
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonSaveFile'
            ,objectId: '".$this->objectId."'
            ,parentId: '".$parentId."'
        ");
        
        ////////////////////////////////////////////////////////////////////////
        // Refresh tree node and buttons...
        ////////////////////////////////////////////////////////////////////////
        if($this->objectId == "new"){
            
            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                myTree = window.parent.Ext.getCmp('TREE.FILE_SYSTEM_LIST_ID');
                myNode = myTree.getNodeById('".$parentId."');
                if (myNode) if(myNode.parentNode==null){
                    myTree.root.reload();
                }else{
                    var parentId = myNode.parentNode.id
                    myPerentNode = myTree.getNodeById(parentId);
                    if(myNode.isLeaf()){
                        if(myPerentNode){
                            myPerentNode.reload();
                            myPerentNode.expand(true, false);
                        }else{
                            myTree.root.reload();
                        }
                    }else{
                        if (myNode.hasChildNodes()) {
                            myNode.reload();
                            myNode.expand(true, false);
                        }
                    }
                }
                var result = Ext.util.JSON.decode(action.response.responseText);
                window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
            ");
            
        }else{
            if(!$checkChild){
                $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleRemove());   
            }
            
            $OBJECT_FORM->setRemoveParams("
                cmd: 'jsonRemoveFile'
                ,objectId: '".$this->objectId."'
            ");
            
            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                myTree = window.parent.Ext.getCmp('TREE.FILE_SYSTEM_LIST_ID');
                myNode = myTree.getNodeById('".$parentId."');
                if(myNode.parentNode==null){
                    myTree.root.reload();
                }else{
                    var parentId = myNode.parentNode.id
                    myPerentNode = myTree.getNodeById(parentId);
                    if(myNode.isLeaf()){
                        if(myPerentNode){
                            myPerentNode.reload();
                            myPerentNode.expand(true, false);
                        }else{
                            myTree.root.reload();
                        }
                    }else{
                        if (myNode.hasChildNodes()) {
                            myNode.reload();
                            myNode.expand(true, false);
                        }
                    }
                }
                ".camemisPage::setRequestURI()."
            ");
            
            $OBJECT_FORM->setOnEmbeddedRemoveEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                myTree = window.parent.Ext.getCmp('TREE.FILE_SYSTEM_LIST_ID');
                myNode = myTree.getNodeById('".$parentId."');
                if(myNode.parentNode==null){
                    myTree.root.reload();
                }else{
                    var parentId = myNode.parentNode.id
                    myPerentNode = myTree.getNodeById(parentId);
                    if(myNode.isLeaf()){
                        if(myPerentNode){
                            myPerentNode.reload();
                            myPerentNode.expand(true, false);
                        }else{
                            myTree.root.reload();
                        }
                    }else{
                        if (myNode.hasChildNodes()) {
                            myNode.reload();
                            myNode.expand(true, false);
                        }
                    }
                }
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            ");
        }
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        ////////////////////////////////////////////////////////////////////////
        
        if($this->facette){
            $OBJECT_FORM->isObjectDefaultOnLoad = true;
        }else{
            $OBJECT_FORM->isObjectDefaultOnLoad = false;
        }
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>