<?
require_once 'clients/app_admin/AdminPage.php';
require_once 'clients/app_admin/AdminForm.php';
require_once 'clients/app_admin/AdminGrid.php';
require_once 'clients/app_admin/AdminField.php';
require_once 'clients/app_admin/AdminBar.php';
require_once 'clients/app_admin/AdminPage.php';

$OBJECT_ADMIN_PAGE = AdminPage::getInstance();
$OBJECT_ADMIN_PAGE->setLoadingMask = true;
print $OBJECT_ADMIN_PAGE->showCamemisHeader();
?>
<style>
    h1{
        font-size: 18px;
        color:#55555;
        font-weight: bold;
    }
</style>
<script>
Ext.onReady(function() {
    
    <?
    $OBJECT_FORM = new AdminForm("REGISTRATION");
    $OBJECT_FORM->setURL("/registration/");
    $OBJECT_FORM->setonEmbeddedEvents("
        
    ");
    
    $DETAIL_INFORMATION = "
    {
        title: 'Registration'
        ,autoHeight: true
        ,style: 'padding-bottom: 10px'
        ,width: 620
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".AdminField::Displayfield("CONENT",false,'<b>The Registration of CAMEMIS Education Management System is FREE.</b>')."}
            ]
        }]
    }
    ";
    
    $FORM_INFORMATION = "
    {
        title: 'Registration Form'
        ,autoHeight: true
        ,style: 'padding-bottom: 10px'
        ,width: 620
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".AdminField::Textfield("SCHOOL_NAME", "SCHOOL_NAME", '<b>Full School Name</b>',true)."}
                ,{".AdminField::Textfield("LASTNAME", "LASTNAME", '<b>Last Name</b>',true)."}
                ,{".AdminField::Textfield("FIRSTAME", "FIRSTNAME", '<b>Firstname</b>',true)."}
                ,{".AdminField::ComboSchulTemplate('<b>Type of School</b>')."}
                ,{".AdminField::Textarea("ADDRESS", '<b>Address of School</b>', 100)."}
                ,{".AdminField::Textfield("CONTACT_PHONE", "CONTACT_PHONE", '<b>Phone Numbe</b>')."}
                ,{".AdminField::EMailfield("CONTACT_EMAIL", "<b>EMail</b>", false, true)."}
                ,{".AdminField::ComboCountry("<b>Country</b>")."}    
                ,{".AdminField::Textarea("COMMENT", '<b>Any additional questions or information you would like to provide?</b>', 150)."}
            ]
        }]
    }
    ";
    
    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: [
            ".$DETAIL_INFORMATION."
            ,".$FORM_INFORMATION."
        ]
    ";
    
    $OBJECT_FORM->addTBarItems("
        text: 'Save'
        ,id: 'SINGLE_SAVE_ID'
        ,formBind:true
        ,iconCls:'icon-disk'
        ,scope:this
        ,disabled: true
        ,tooltip:'Save'
        ,handler:this.onSubmit
    ");
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'actionRegistration'
    ");
    
    $OBJECT_FORM->addObjectItems($items);
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 200;
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->renderJS();
    ?>
            
    Ext.QuickTips.init();
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'fit'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: true
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $OBJECT_ADMIN_PAGE->showCamemisFooter();
?>