<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$academicId = isset($_GET["academicId"])? (int) $_GET["academicId"]:"";
$academicObject = AcademicDBAccess::findGradeFromId($academicId);

if(!$academicObject) {header("Location: /main/permission/");exit;}

$setParams = "";
$setParams .= "&academicId=".$academicId."";

?>
<style>
    .x-vr-tab-panel-bwrap {
        background: none repeat scroll 0 0 <?=CamemisPage::userBgColor();?>;
        border-left: 1px solid #99BBE8;
        float: right;
        padding: 3px;
    }
</style>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        $PENEL_ITEMS = Array();
        
        $setDayParams = $setParams;
        $setDayParams .= "&target=DAY_SCHEDULE";
        $DAY_SCHEDULE = "{
            title: '".DAY_SCHEDULE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'DAY_SCHEDULE', url: '/academic/schoolyearschedule/?camIds=".$this->urlEncryp->encryptedGet($setDayParams)."'})]
        }";
        $PENEL_ITEMS[] = $DAY_SCHEDULE;
        
        $setWeekParams = $setParams;
        $setWeekParams .= "&target=WEEK_SCHEDULE";
        $WEEK_SCHEDULE = "{
            title: '".WEEK_SCHEDULE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'WEEK_SCHEDULE', url: '/academic/schoolyearschedule/?camIds=".$this->urlEncryp->encryptedGet($setWeekParams)."'})]
        }";
        $PENEL_ITEMS[] = $WEEK_SCHEDULE;
        
        $setExtraParams = $setParams;
        $setExtraParams .= "&target=EXTRA_TEACHING_SESSION";
        $EXTRA_TEACHING_SESSION = "{
            title: '".EXTRA_TEACHING_SESSION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'EXTRA_TEACHING_SESSION', url: '/academic/schoolyearschedule/?camIds=".$this->urlEncryp->encryptedGet($setExtraParams)."'})]
        }";
        $PENEL_ITEMS[] = $EXTRA_TEACHING_SESSION;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'vrtabpanel'
                ,activeTab: 0
                ,tabMarginTop:100
                ,enableTabScroll:true       
                ,defaults: {autoScroll:true}
                ,items:<?=$CHOOSE_ITEMS?>
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>