<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();
require_once 'models/HealthSettingDBAccess.php';

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$entries = HealthSettingDBAccess:: sqlHealthSetting(false, false);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<style>
    .x-vr-tab-panel-bwrap {
        background: none repeat scroll 0 0 <?=CamemisPage::userBgColor();?>;
        border-left: 1px solid #99BBE8;
        float: right;
        padding: 3px;
    }
</style>
<script>

    Ext.onReady(function() {

        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $PENEL_ITEMS = Array();

        if($entries){
            foreach($entries as $value){
                
                if($value->OBJECT_DISPLAY){
                    $params = "objectId=".$this->objectId."";
                    $params .= "&settingId=".$value->ID."";
                    $params .= "&target=".$value->OBJECT_INDEX."";
                    $url = "/student/studenthealthsetting/?camIds=".$this->urlEncryp->encryptedGet($params)."";

                    switch(UserAuth::systemLanguage()){
                        case "ENGLISH":
                            $item = "{
                                title: '".setShowText($value->NAME_EN)."'
                                ,layout: 'fit'
                                ,items:[new Ext.ux.IFrameComponent({ id: '".$value->ID."', url: '".$url."'})]
                            }";
                            break;
                        default:
                            $item = "{
                                title: '".setShowText($value->NAME)."'
                                ,layout: 'fit'
                                ,items:[new Ext.ux.IFrameComponent({ id: '".$value->ID."', url: '".$url."'})]
                            }";
                            break;
                    }
                    
                    $PENEL_ITEMS[] = $item;
                }
            }
        }
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";

        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,border:false
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>