<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_GRID = new CamemisGrid("ASSIGNMENT", "LIST");

$OBJECT_FORM = new CamemisForm("ASSIGNMENT");
$OBJECT_FORM->setLoadUrl('/assignment/jsonload/');
$OBJECT_FORM->setSaveUrl('/assignment/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<script>
var objectId = '';
Ext.onReady(function() {

    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    ///////////////////////////////////////////////////////
	// ASSIGNMENT...
	///////////////////////////////////////////////////////
	$objectFiled1 = "name: 'OBJECT_NAME'";
	$objectFiled2 = "name: 'POINTS'";
	$objectFiled3 = "name: 'GRADINGTERM'";
	$objectFiled4 = "name: 'CATEGORY'";
	$objectFiled5 = "name: 'DESCRIPTION'";
	$objectFiled6 = "name: 'WEIGHT'";
	$objectFiled7 = "name: 'STATUS'";
	$objectFiled8 = "name: 'STATUS_KEY'";

	$objectCol1 = "header: '".NAME."', width: percentWidth(20), dataIndex: 'OBJECT_NAME'";
	$objectCol2 = "header: '".POINTS."', width: percentWidth(10), dataIndex: 'POINTS'";
	$objectCol3 = "header: '".GRADING_TERM."', width: percentWidth(15), dataIndex: 'GRADINGTERM'";
	$objectCol4 = "header: '".GRADING_CATEGORY."', width: percentWidth(18), dataIndex: 'CATEGORY'";
	$objectCol5 = "header: '".WEIGHT."', width: percentWidth(10), dataIndex: 'WEIGHT'";
	$objectCol6 = "header: '".DESCRIPTION."', width: percentWidth(20), dataIndex: 'DESCRIPTION'";
	$objectCol7 = "header: '".STATUS."', align:'center', width: 60, sortable: false, dataIndex: 'STATUS_KEY'";

	$OBJECT_GRID->addReadField($objectFiled1);
	$OBJECT_GRID->addReadField($objectFiled2);
	$OBJECT_GRID->addReadField($objectFiled3);
	$OBJECT_GRID->addReadField($objectFiled4);
	$OBJECT_GRID->addReadField($objectFiled5);
	$OBJECT_GRID->addReadField($objectFiled6);
	$OBJECT_GRID->addReadField($objectFiled7);
	$OBJECT_GRID->addReadField($objectFiled8);

	$OBJECT_GRID->addColumn($objectCol1);
	$OBJECT_GRID->addColumn($objectCol2);
	$OBJECT_GRID->addColumn($objectCol3);
	$OBJECT_GRID->addColumn($objectCol4);
	$OBJECT_GRID->addColumn($objectCol5);
	$OBJECT_GRID->addColumn($objectCol6);
	$OBJECT_GRID->addColumn($objectCol7);

        $OBJECT_GRID->addTBarItems(
            CamemisBar::tbarGridAdd("
                function (){
                    openWinXType('WinXType','".ADD_ENTRY."', '".$OBJECT_FORM->getObjectXtype()."', 500,percentHeight(85));
                    objectId = 0;
                }
            ")
        );

        $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'SHOW_DETAIL_ID'
            ,text: '".SHOW_DETAIL."'
            ,iconCls:'icon-magnifier'
            ,scope:this
            ,handler: function(){
                var sm = this.getSelectionModel();
                var record = sm.getSelected();
                if(record){
                    var clickName = record.data.OBJECT_NAME;
                    objectId = record.data.ID;
                    openWinXType('WinXType',clickName, '".$OBJECT_FORM->getObjectXtype()."', 500,percentHeight(85));
                    Ext.getCmp('".$OBJECT_FORM->getObjectId()."').load({
                        url: '/assignment/jsonload/'
                        ,waitMsg:'Loading...'
                        ,params:{cmd: 'loadObject',objectId: objectId}
                        ,success: function(form, action) {
                            ".CamemisBar::tbarReleaseStatus()."
                        }
                    });
                }else{
                ".camemisPage::alertPleaseSelect()."
                }
            }
        }]);
        ");

    if (UserAuth::getACLValue("ACADEMIC_SETTING_REMOVE_RIGHT"))
    $OBJECT_GRID->addTBarItems(CamemisBar::tbarGridRemove("this.onRemove"));

    $OBJECT_GRID->setSaveParams("
        cmd: 'actionAssignment'
        ,subjectId: '".$this->subjectId."'
        ,gradeId: '".$this->gradeId."'
    ");

    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,subjectId: '".$this->subjectId."'
        ,gradeId: '".$this->gradeId."'
        ,cmd: 'jsonAssignmentsByGrade'
    ";

    $OBJECT_GRID->setRemoveParams("
        cmd: 'removeObject'
    ");

	$OBJECT_GRID->removeNAME = "OBJECT_NAME";
	$OBJECT_GRID->renderJS();

    $items = "
    border: false
    ,autoScroll: true
    ,bodyStyle: 'padding:5px'
    ,height: percentHeight(60)
    ,items:[{
        layout: 'anchor'
        ,border: false
        ,width: 550
        ,autoScroll: true
        ,items: [{
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,collapsed: false
            ,collapsible: true
            ,style: 'padding-bottom: 5px'
            ,anchor: '95%'
            ,items:[{
                width: 450
                ,layout: 'form'
                ,border: false
                ,bodyStyle: 'padding:10px'
                ,items:[
                    {".CamemisField::Textfield("NAME_ID", "NAME", NAME, true)."}
                ]
            }]
        },{
            title: '".SETTING."'
            ,autoHeight: true
            ,collapsed: false
            ,collapsible: true
            ,style: 'padding-bottom: 5px'
            ,anchor: '95%'
            ,items:[{
                width: 450
                ,layout: 'form'
                ,border: false
                ,bodyStyle: 'padding:10px'
                ,items:[
                    {".CamemisField::ComboCategoryGradebook("CATEGORY_ID", CATEGORY)."}
                    ,{".CamemisField::Numberfield("WEIGHT_ID", "WEIGHT", WEIGHT)."}
                    ,{".CamemisField::Numberfield("POINTS_ID", "POINTS", POINTS_POSSIBLE)."}
                ]
            }]
        }]
    }]
	";
	$OBJECT_FORM->addObjectItems($items);

    //if (UserAuth::getACLValue("ACADEMIC_SETTING_EXECUTE_RIGHT"))
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease(false,false));
    //if (UserAuth::getACLValue("ACADEMIC_SETTING_EDIT_RIGHT"))
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave(false));

    $OBJECT_FORM->setSaveParams("
        cmd: 'actionAssignment'
        ,objectId: objectId
        ,gradeId: '".$this->gradeId."'
        ,subjectId: '".$this->subjectId."'
    ");
    $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: objectId");

    $OBJECT_FORM->setonEmbeddedEvents("
        Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
    ");

    $OBJECT_FORM->setOnEmbeddedReleaseEvents("
        Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
    ");

    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,layout: 'fit'
            ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}]
        }]
    });
});
</script>
<?

print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>