<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';

require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("ASSIGNMENT");
$OBJECT_FORM->setLoadUrl('/assignment/jsonload/');
$OBJECT_FORM->setSaveUrl('/assignment/jsonsave/');

$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";
$educationType = isset($_GET["educationType"])?addText($_GET["educationType"]):"";

$facette = $this->facette;

if($facette){
    $educationType = $facette->EDUCATION_TYPE;
}

print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<script>
Ext.onReady(function() {

    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $DETAIL_ITEMS = "[";
    $DETAIL_ITEMS .= "{".CamemisField::Textfield("SHORT_ID", "SHORT", SHORT, true)."}";
    $DETAIL_ITEMS .= ",{".CamemisField::Textfield("NAME_ID", "NAME", NAME, true)."}";
    $DETAIL_ITEMS .= ",{".CamemisField::Combo(
            'SUBJECT'
            , SUBJECT
            , SubjectDBAccess::comboSubjectByEducationType($educationType)
            , false
            , false
            , false
            , false
            ,false)."}";
    $DETAIL_ITEMS .= ",{".CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false)."}";
    $DETAIL_ITEMS .= "]";
    
    $DETAIL_INFORMATION = "
    {
    title: '".DETAIL_INFORMATION."'
    ,autoHeight: true
    ,style: 'padding-bottom: 5px'
    ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: ".$DETAIL_ITEMS."
        }]
    }
    ";
    
    switch(strtoupper($this->target)){
        case "GENERAL":
            $EVALUATION_SETTINGS_ITEMS = "[";
            
            $INCLUDE_IN_EVALUATION_STORE = "[
                [1, '" . INCLUDE_MONTHLY_EVALUATION . "']
                ,[2, '".INCLUDE_MIDTERM_EVALUATION."']
                ,[3, '".INCLUDE_SEMESTER_EVALUATION."']
            ]";
            
            $EVALUATION_TYPE_STORE = "[
                [0, '" . NUMBER . "']
                ,[1, '".PERCENTAGE."']
            ]";
            
            $EVALUATION_SETTINGS_ITEMS .= "{".CamemisField::Combo('INCLUDE_IN_EVALUATION', CATEGORY, $INCLUDE_IN_EVALUATION_STORE, false, false, false, false,false)."}";
            $EVALUATION_SETTINGS_ITEMS .= ",{".CamemisField::Combo('EVALUATION_TYPE', EVALUATION_TYPE, $EVALUATION_TYPE_STORE, false, false, false, false,false)."}";
            $EVALUATION_SETTINGS_ITEMS .= ",{".CamemisField::Numberfield("COEFF_VALUE", "COEFF_VALUE", VALUE." / ".COEFFICIENT, false, false, false, false)."}";
            $EVALUATION_SETTINGS_ITEMS .= ",{".CamemisField::Numberfield("POINTS_POSSIBLE", "POINTS_POSSIBLE", POINTS_POSSIBLE, false, false, false, false)."}";
            $EVALUATION_SETTINGS_ITEMS .= "]";

            $EVALUATION_SETTINGS = "
            {
                title: '".EVALUATION_SETTINGS."'
                ,autoHeight: true
                ,style: 'padding-bottom: 5px'
                ,width: 550
                    ,items:[{
                        layout: 'form'
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle: 'padding:10px'
                        ,items: ".$EVALUATION_SETTINGS_ITEMS."
                    }]
                }
            ";
            $items = "
                border: false
                ,id: 'FORM_ITEMS'
                ,bodyStyle: 'padding:0px'
                ,items: [
                    ".$DETAIL_INFORMATION."
                    ,".$EVALUATION_SETTINGS."
                ]
            ";
            break;
        default:
            $EVALUATION_SETTINGS_ITEMS = "[";
            $EVALUATION_TYPE_STORE = "[
                [0, '" . NUMBER . "']
                ,[1, '".PERCENTAGE."']
            ]";
            $EVALUATION_SETTINGS_ITEMS .= "{".CamemisField::Combo('EVALUATION_TYPE', EVALUATION_TYPE, $EVALUATION_TYPE_STORE, false, false, false, false,false)."}";
            $EVALUATION_SETTINGS_ITEMS .= ",{".CamemisField::Numberfield("COEFF_VALUE", "COEFF_VALUE", VALUE." / ".COEFFICIENT, false, false, false, false)."}";
            $EVALUATION_SETTINGS_ITEMS .= ",{".CamemisField::Numberfield("POINTS_POSSIBLE", "POINTS_POSSIBLE", POINTS_POSSIBLE, false, false, false, false)."}";
            $EVALUATION_SETTINGS_ITEMS .= "]";

            $EVALUATION_SETTINGS = "
            {
                title: '".EVALUATION_SETTINGS."'
                ,autoHeight: true
                ,style: 'padding-bottom: 5px'
                ,width: 550
                    ,items:[{
                        layout: 'form'
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle: 'padding:10px'
                        ,items: ".$EVALUATION_SETTINGS_ITEMS."
                    }]
                }
            ";
            $items = "
                border: false
                ,id: 'FORM_ITEMS'
                ,bodyStyle: 'padding:0px'
                ,items: [
                    ".$DETAIL_INFORMATION."
                    ,".$EVALUATION_SETTINGS."
                ]
            ";
            break;
    }
    
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
    ");
    
    if ($objectId !="new") {
        
        switch(strtoupper($this->target)){
            case "GENERAL":
                if (UserAuth::getACLValue("ACADEMIC_SETTING_REMOVE_RIGHT"))
                $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleRemove());
                $OBJECT_FORM->setRemoveParams("cmd: 'jsonRemoveAssignmentTemp',objectId: '".$objectId."'");

                $OBJECT_FORM->setOnEmbeddedRemoveEvents("
                    window.parent.Ext.getCmp('TREE.ASSIGNMENT_ASSIGNMENT_ID').root.reload();
                    window.parent.Ext.getCmp('TREE.ASSIGNMENT_ASSIGNMENT_ID').getRootNode().expand(true, false);
                    window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                ");

                if($facette->SUBJECT){
                    $OBJECT_FORM->setonEmbeddedEvents("
                        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                        myTree = window.parent.Ext.getCmp('TREE.ASSIGNMENT_ASSIGNMENT_ID');
                        myNode = myTree.getNodeById('SUBJECT_".$facette->SUBJECT."');
                        myNode.reload();
                        myNode.expand(true, false); 
                    ");
                }else{
                    $OBJECT_FORM->setonEmbeddedEvents("
                        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                        myTree = window.parent.Ext.getCmp('TREE.ASSIGNMENT_ASSIGNMENT_ID');
                        myNode = myTree.getNodeById('QUALIFICATION_".$facette->EDUCATION_TYPE."');
                        myNode.reload();
                        myNode.expand(true, false); 
                    ");
                }
                break;
            default:
                $OBJECT_FORM->setonEmbeddedEvents("
                    myTree = window.parent.Ext.getCmp('TREE.ASSIGNMENT_ASSIGNMENT_ID');
                    myTree.root.reload();
                    window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                "); 
                break;
        }
        
    }else{
        
        if($educationType){
            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                myTree = window.parent.Ext.getCmp('TREE.ASSIGNMENT_ASSIGNMENT_ID');
                myNode = myTree.getNodeById('QUALIFICATION_".$educationType."');
                myNode.reload();
                myNode.expand(true, false); 
                var result = Ext.util.JSON.decode(action.response.responseText);
                window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
            "); 
        }else{
            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                myTree = window.parent.Ext.getCmp('TREE.ASSIGNMENT_ASSIGNMENT_ID');
                myTree.root.reload();
                myTree.expand(true, false); 
                var result = Ext.util.JSON.decode(action.response.responseText);
                window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
            "); 
        }
    }
    
    if (UserAuth::getACLValue("ACADEMIC_SETTING_EDIT_RIGHT"))
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'jsonSaveAssignmentTemp'
        ,objectId: '".$objectId."'
        ,target:'".$this->target."'
        ,educationType:'".$educationType."'    
    ");

    $OBJECT_FORM->setLoadParams("
        cmd: 'jsonLoadAssignmentTemp'
        ,objectId: '".$objectId."'
    ");
    
    $OBJECT_FORM->isObjectDefaultOnLoad = $this->facette?true:false;

    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 150;
    $OBJECT_FORM->renderJS();

    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,layout: 'fit'
            ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>