<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("ASSIGNMENT");
$OBJECT_FORM->setLoadUrl('/assignment/jsonload/');
$OBJECT_FORM->setSaveUrl('/assignment/jsonsave/');

$academicId = isset($_GET["academicId"])?$_GET["academicId"]:"";
$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$academicObject = AcademicDBAccess::findGradeFromId($academicId);

if(!$academicObject) {header("Location: /main/permission/");}

$TERM_NUMBER = AcademicDBAccess::findAcademicTerm(false,$academicId);
AssignmentDBAccess::mappingAcademicEvaluationType($academicObject->EVALUATION_TYPE, $objectId);

?>

<script>
Ext.onReady(function() {

    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $DETAIL_ITEMS = "[";
        $DETAIL_ITEMS .= "{".CamemisField::Textfield("SHORT_ID", "SHORT", SHORT, true)."}";
        $DETAIL_ITEMS .= ",{".CamemisField::Textfield("NAME_ID", "NAME", NAME, true)."}";
        $DETAIL_ITEMS .= ",{".CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false)."}";
    $DETAIL_ITEMS .= "]";
    
    $DETAIL_INFORMATION = "
    {
    title: '".DETAIL_INFORMATION."'
    ,autoHeight: true
    ,style: 'padding-bottom: 5px'
    ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: ".$DETAIL_ITEMS."
        }]
    }
    ";
    
    $EVALUATION_SETTINGS_ITEMS = "[";
    
    $EVALUATION_TYPE_STORE = "[
        [0, '" . NUMBER . "']
        ,[1, '".PERCENT."']
    ]";
    
    switch ($TERM_NUMBER) {
        case 1:
            $INCLUDE_IN_EVALUATION_STORE = "[
                [1, '" . INCLUDE_MONTHLY_EVALUATION . "']
                ,[2, '".INCLUDE_TERM_EVALUATION."']
            ]";
        break;
        case 2:
            $INCLUDE_IN_EVALUATION_STORE = "[
                [1, '" . INCLUDE_MONTHLY_EVALUATION . "']
                ,[2, '".INCLUDE_QUARTER_EVALUATION."']
            ]";
        break;
        default:
            $INCLUDE_IN_EVALUATION_STORE = "[
                [1, '" . INCLUDE_MONTHLY_EVALUATION . "']
                ,[2, '".INCLUDE_SEMESTER_EVALUATION."']
            ]";
        break;
    }
    
    $EVALUATION_SETTINGS_ITEMS .= ",{".CamemisField::Combo('INCLUDE_IN_EVALUATION', EVALUATION, $INCLUDE_IN_EVALUATION_STORE, false, false, false, false,false)."}";
    $EVALUATION_SETTINGS_ITEMS .= ",{".CamemisField::Combo('EVALUATION_TYPE', EVALUATION_TYPE, $EVALUATION_TYPE_STORE, true, false, false, false,false)."}";
    $EVALUATION_SETTINGS_ITEMS .= ",{".CamemisField::Numberfield("COEFF_VALUE", "COEFF_VALUE", COEFFICIENT_SETTING, false, false, false, false)."}";
    
    $EVALUATION_SETTINGS_ITEMS .= "]";
    
    $EVALUATION_SETTINGS = "
    {
    title: '".EVALUATION_SETTINGS."'
    ,autoHeight: true
    ,style: 'padding-bottom: 5px'
    ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: ".$EVALUATION_SETTINGS_ITEMS."
        }]
    }
    ";
    
    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: [
            ".$DETAIL_INFORMATION."
            ,".$EVALUATION_SETTINGS."
        ]
    ";
    
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
    ");
    
    if ($objectId !="new") {
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormRemoveObject($this->remove_status));
    }else{
        if (UserAuth::getACLValue("ACADEMIC_SETTING_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    }
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'actionAssignment'
        ,objectId: '".$objectId."'
        ,academicId: '".$academicId."'
    ");

    $OBJECT_FORM->setLoadParams("
        cmd: 'loadObject'
        ,objectId: '".$objectId."'
        ,academicId: '".$academicId."'
    ");
    $OBJECT_FORM->setRemoveParams("cmd: 'removeObject',objectId: '".$objectId."'");
    $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '".$objectId."'");

    $OBJECT_FORM->setonEmbeddedEvents("
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        myTree = window.parent.Ext.getCmp('TREE.SUBJECT_ASSIGNMENT_ID');
        myNode = myTree.getNodeById('SUBJECT_".$this->subjectId."');
        myNode.reload();
        myNode.expand(true, false); 
        window.location='".$_SERVER["REQUEST_URI"]."';
    ");

    $OBJECT_FORM->setOnEmbeddedReleaseEvents("
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        myTree = window.parent.Ext.getCmp('TREE.SUBJECT_ASSIGNMENT_ID');
        myNode = myTree.getNodeById('SUBJECT_".$this->subjectId."');
        myNode.reload();
        myNode.expand(true, false); 
        window.location='".$_SERVER["REQUEST_URI"]."';
    ");

    $OBJECT_FORM->setOnEmbeddedRemoveEvents("
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        myTree = window.parent.Ext.getCmp('TREE.SUBJECT_ASSIGNMENT_ID');
        myNode = myTree.getNodeById('SUBJECT_".$this->subjectId."');
        myNode.reload();
        myNode.expand(true, false); 
        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
    ");

    $OBJECT_FORM->isObjectDefaultOnLoad = true;

    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 150;
    $OBJECT_FORM->renderJS();

    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,layout: 'fit'
            ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>