<?
//////////////////////
/// @Sor Veasna
///Date : 26-02-2014
///
///////////////////
require_once 'clients/CamemisPage.php';

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    ////////////////////////////////////////////////////////////////////////////
    //@Viewport
    ////////////////////////////////////////////////////////////////////////////
    Ext.onReady(function() {
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,items:[{
                border: true
                ,layout: 'fit'
                ,tbar:[{
                    text:'<?=REFRESH?>'
                    ,iconCls:'icon-arrow_refresh'
                    ,handler: function(){
                        window.location="<?=CamemisPage::setRequestURI()?>";
                    }
                }]
                ,items:[{
                    layout:'column'
                    ,height:percentHeight(100)
                    ,autoScroll:true
                    ,border:false
                    ,defaults: {
                        layout: 'anchor'
                        ,defaults: {anchor: '100%'}
                    }
                    ,items: [{
                        columnWidth: 1
                        ,baseCls:'x-plain'
                        ,bodyStyle:'padding:5px 5px 5px 5px'
                        ,items:[{
                            title: 'Body Mass Index'
                            ,layout:'fit'
                            ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                            ,collapsible: true
                            ,collapsed: false
                            ,height:280
                            ,items:[{
                                xtype: 'tabpanel'
                                ,tabPosition: 'top'
                                ,plain:true
                                ,activeTab: 0
                                ,enableTabScroll:true
                                ,items:[{
                                    title: 'BMI-for-age (5-19 years)'
                                    ,layout: 'fit'
                                    ,height:300
                                    ,items: [new Ext.ux.IFrameComponent({ id: 'BMI_AGE', url:'/chart/studenthealth/?camIds=<?=$this->urlEncryp->encryptedGet("target=BMI_AGE")?>'})]
                                },{
                                    title: 'Height-for-age (5-19 years)'
                                    ,layout: 'fit'
                                    ,height:300
                                    ,items: [new Ext.ux.IFrameComponent({ id: 'BMI_HEIGHT_AGE', url:'/chart/studenthealth/?camIds=<?=$this->urlEncryp->encryptedGet("target=BMI_HEIGHT_AGE")?>'})]
                                },{
                                    title: 'Weight-for-age (5-10 years)'
                                    ,layout: 'fit'
                                    ,height:300
                                    ,items: [new Ext.ux.IFrameComponent({ id: 'BMI_WEIGHT_AGE', url:'/chart/studenthealth/?camIds=<?=$this->urlEncryp->encryptedGet("target=BMI_WEIGHT_AGE")?>'})]
                                }]
                            }]
                        }]   
                    },{
                        columnWidth: 1
                        ,baseCls:'x-plain'
                        ,bodyStyle:'padding:5px 5px 5px 5px'
                        ,items:[{
                            title: 'Medical Visit'
                            ,layout: 'fit'
                            ,collapsible: true
                            ,collapsed: false
                            ,height:300
                            ,items: [new Ext.ux.IFrameComponent({ id: 'MEDICAL_VISIT', url:'/chart/studenthealth/?camIds=<?=$this->urlEncryp->encryptedGet("target=MEDICAL_VISIT")?>'})]
                        }]    
                    },{
                        columnWidth: 1
                        ,baseCls:'x-plain'
                        ,bodyStyle:'padding:5px 5px 5px 5px'
                        ,items:[{
                            title: 'Growth Chart'
                            ,layout: 'fit'
                            ,collapsible: true
                            ,collapsed: false
                            ,height:300
                            ,items: [new Ext.ux.IFrameComponent({ id: 'GROWTH_CHART', url:'/chart/studenthealth/?camIds=<?=$this->urlEncryp->encryptedGet("target=GROWTH_CHART")?>'})]
                        }]    
                    },{
                        columnWidth: 1
                        ,baseCls:'x-plain'
                        ,bodyStyle:'padding:5px 5px 5px 5px'
                        ,items:[{
                            title: 'Vaccination'
                            ,layout: 'fit'
                            ,collapsible: true
                            ,collapsed: false
                            ,height:280
                            ,items: [new Ext.ux.IFrameComponent({ id: 'VACCINATION', url:'/chart/studenthealth/?camIds=<?=$this->urlEncryp->encryptedGet("target=VACCINATION")?>'})]
                        }]   
                    }]
                }]
            }]
        });
    });
</script>
    
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>
