<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisSchoolTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("HEALTH");
$OBJECT_FORM->setLoadUrl('/health/jsonload/');
$OBJECT_FORM->setSaveUrl('/health/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>

    Ext.apply(Ext.form.VTypes, {
        daterange : function(val, field) {
            var date = field.parseDate(val);
            if(!date){
                return false;
            }
            if (field.startDateField) {
                var start = Ext.getCmp(field.startDateField);
                if (!start.maxValue || (date.getTime() !== start.maxValue.getTime())) {
                    start.setMaxValue(date);
                    start.validate();
                }
            }
            else if (field.endDateField) {
                var end = Ext.getCmp(field.endDateField);
                if (!end.minValue || (date.getTime() !== end.minValue.getTime())) {
                    end.setMinValue(date);
                    end.validate();
                }
            }
            return true;
        }
    });

    Ext.onReady(function() {
        
        var tabs =  new Ext.TabPanel({
            autoTabs:true
            ,plain:true
            ,tabPosition: 'top'
            ,enableTabScroll:true
            ,activeTab:0,bodyStyle: 'background:".CamemisPage::userBgColor()."'
            ,items:[{
                title: '<?=ACADEMIC_DASHBOARD?>'
                ,id: 'ACADEMIC_DASHBOARD'
                ,layout: 'fit',bodyStyle:'background:".CamemisPage::userBgColor().";padding:3px'
                ,items: [new Ext.ux.IFrameComponent({ id: 'DASHBOARD', url:'/health/chartreport/'})]
            }]
        });
        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        $CAMEMIS_PAGE_OBJECT->setAddTab();
        
        $OBJECT_FORM->addObjectItems("
            xtype:'fieldset'
            ,checkboxToggle:true
            ,collapsed: false
            ,title: '".HEALTH."'
            ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;padding:10px'
            ,width: 310
            ,items:[{".CamemisField::Combo('HEALTH_TYPE', TYPE, HealthSettingDBAccess::comboHealth(), false, false, 150, false,false)."}]
        ");
        
        $OBJECT_FORM->addObjectItems("
            xtype:'fieldset'
            ,id: 'START_AND_END_DATE'
            ,checkboxToggle:true
            ,title: '" . DATE . "'
            ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
            ,width: 320
            ,items:[{
                name: 'START_DATE'
                ,hidden: false
                ,width: 150
                ,fieldLabel: '" . START_DATE . "'
                ,xtype: 'datefield'
                ,id: 'START_DATE'
                ,vtype: 'daterange'
                ,endDateField: 'END_DATE'
                ,format: '" . setExtDatafieldFormat() . "'
                ,allowBlank: true
            },{
                name: 'END_DATE'
                ,hidden: false
                ,width: 150
                ,fieldLabel: '" . END_DATE . "'
                ,xtype: 'datefield'
                ,id: 'END_DATE'
                ,vtype: 'daterange'
                ,format: '" . setExtDatafieldFormat() . "'
                ,startDateField: 'START_DATE'
                ,allowBlank: true
            }]
        "); 
        
        $OBJECT_FORM->addObjectItems("
            xtype:'fieldset'
            ,id: 'MEDICAL_VISIT'
            ,hidden:true
            ,checkboxToggle:true
            ,title: 'Next visit (" . DATE . ")'
            ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
            ,width: 320
            ,items:[{
                name: 'EXT_VISIT_START_DATE'
                ,hidden: false
                ,width: 150
                ,fieldLabel: '" . START_DATE . "'
                ,xtype: 'datefield'
                ,id: 'EXT_VISIT_START_DATE'
                ,vtype: 'daterange'
                ,endDateField: 'EXT_VISIT_END_DATE'
                ,format: '" . setExtDatafieldFormat() . "'
                ,allowBlank: true
            },{
                name: 'EXT_VISIT_END_DATE'
                ,hidden: false
                ,width: 150
                ,fieldLabel: '" . END_DATE . "'
                ,xtype: 'datefield'
                ,id: 'EXT_VISIT_END_DATE'
                ,vtype: 'daterange'
                ,format: '" . setExtDatafieldFormat() . "'
                ,startDateField: 'EXT_VISIT_START_DATE'
                ,allowBlank: true
            }]
        "); 
        
        $OBJECT_FORM->addTBarItems("
            text: '".RESET."'
            ,iconCls:'icon-arrow_undo'
            ,scope:this
            ,handler: function(){".CamemisPage::setRequestURI()."}
        ");

        $OBJECT_FORM->addTBarItems("
            text: '".FIND."'
            ,id: 'FIND_ID'
            ,formBind:true
            ,iconCls:'icon-magnifier'
            ,scope:this
            ,handler: function(){
                addTab('ENROLLMENT_EXAMINATION','" . SEARCH_RESULT . "','')
            }
        ");
        
        $OBJECT_FORM->setBodyStyle("padding:10px;background:".CamemisPage::userFormBgColor().";");
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->isKeys = true;
        $OBJECT_FORM->renderJS();
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    title: '&nbsp;'
                    ,region:'west'
                    ,id: 'WEST_ID'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width: 350
                    ,minSize: 350
                    ,maxSize: 350
                    ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                },{
                    title: ''
                    ,border:false
                    ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px;'
                    ,collapsible: false
                    ,region:'center'
                    ,id: 'center'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,margins: '0 3 3 0'
                    ,items: tabs
                }]
            }]
        });
        
        Ext.getCmp('HEALTH_TYPE_ID').on('select', function() {
            var type = Ext.getCmp('HEALTH_TYPE_ID').getValue();
            switch(type){
                case 'MEDICAL_VISIT':
                    Ext.getCmp('MEDICAL_VISIT').show();
                break;
            default:
                Ext.getCmp('MEDICAL_VISIT').hide();
                break;
            }
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>