<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'clients/CamemisViewport.php';
require_once 'models/UserAuth.php';
require_once 'models/app_university/LocationDBAccess.php';
require_once 'models/app_university/student/StudentDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("BULLETIN");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$READ_RIGHT = UserAuth::getACLValue("BULLETIN_BOARD_READ_RIGHT")?"false":"true";
$EDIT_RIGHT = UserAuth::getACLValue("BULLETIN_BOARD_EDIT_RIGHT")?"false":"true";

$OBJECT_GRID = new CamemisGrid("BULLETIN", "LIST");
$OBJECT_GRID->setLoadUrl("/bulletin/jsonload/");
?>
<script>
var choose_status;
Ext.onReady(function() {
	
    function cssContent(value, metadata, record){
        return '<div style="padding: 5px;"><span style="font-weight:bold; white-space:normal; color:#061f83;">' 
        + value + '</span><br><span style="font-weight:normal; white-space:normal; color:#333;">' 
        + record.data.CONTENT + '</span></div>';
    }
    
    function cssNumber(value, metadata, record){
        return '<div style="font-weight:normal; color:#061f83; padding: 5px;">' + value + '</div>';
    }
    
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
	
    $CAMEMIS_PAGE_OBJECT->setAddTab();
	
    $OBJECT_FORM->addObjectItems("
        xtype:'fieldset'
        ,checkboxToggle:true
        ,collapsed: false
        ,title: '".BULLETIN_BOARD."'
        ,bodyStyle: 'background:#D1DDEF; padding:10px'
        ,width: 310
        ,items:[
            {".CamemisField::Textarea("SUBJECT_BULLETIN", TITLE, 50,false,false,false,150)."}
            ,{".CamemisField::ComboUserType(RECIPIENT,false,false, 150)."}		
            ,{".CamemisField::ComboReleaseStatus(false,false,true, 150)."}
            ,{".CamemisField::Datefield("START_DATE",START_DATE, false, false, 150)."}
            ,{".CamemisField::Datefield("END_DATE",END_DATE, false, false, 150)."}	
        ]
    ");   
    
    $OBJECT_FORM->addTBarItems("
        text: '".RESET."'
        ,iconCls:'icon-arrow_undo'
        ,handler: function(){
            ".CamemisPage::setRequestURI(false)."
        }
    ");
    
    $OBJECT_FORM->addTBarItems("
        text: '".FIND."'
        ,id: 'FIND_ID'
        ,disabled: ".$EDIT_RIGHT."
        ,formBind:true
        ,iconCls:'icon-magnifier'
        ,scope:this
        ,handler: function(){
        
            form = this.getForm();
            
            var choose_status = form.findField('STATUS_ID').getValue();
            var subject_bulletin = form.findField('SUBJECT_BULLETIN').getValue();
            var recipient = form.findField('RECIPIENT').getValue();

            var _startDate = form.findField('START_DATE').getValue();
            var _endDate = form.findField('END_DATE').getValue();

            if(_startDate){
                startDate = _startDate.getFullYear() + '-' + (parseInt(_startDate.getMonth()) + 1) + '-' + _startDate.getDate();
            }else{
                startDate = '';
            }

            if(_endDate){
                endDate = _endDate.getFullYear() + '-' + (parseInt(_endDate.getMonth()) + 1) + '-' + _endDate.getDate();
            }else{
                endDate = ''; 
            }
			
            Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.baseParams = {
                start:0
                ,limit:100
                ,cmd: 'searchBulletins'
                ,subject_bulletin:subject_bulletin
                ,recipient:recipient
                ,choose_status:choose_status
                ,startDate:startDate
                ,endDate:endDate
            };
            Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.load();
        }
    ");
    
	$OBJECT_FORM->addTBarItems("
        text: '".ADD_A_NEW_ITEM."'
        ,id: 'ADD_ID'
        ,disabled: ".$EDIT_RIGHT."
        ,formBind:true
        ,iconCls:'icon-application_form_add'
        ,scope:this
        ,handler: function(){
            clickOpenPage('center','', '/bulletin/editbulletin/?objectId=new');
        }
    ");

    $OBJECT_FORM->setBodyStyle("padding:10px;background:".CamemisPage::userFormBgColor().";");
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->isKeys = false;
    $OBJECT_FORM->renderJS();
  
    ////////////////////////////////////////////////////////////////////////////
    $OBJECT_GRID->addReadField("name: 'STATUS'");
    $OBJECT_GRID->addReadField("name: 'SUBJECT_BULLETIN'");
    $OBJECT_GRID->addReadField("name: 'CONTENT'");
    $OBJECT_GRID->addReadField("name: 'POSTED_DATE'");
    $OBJECT_GRID->addReadField("name: 'STATUS_KEY'");
    $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");

    $OBJECT_GRID->addColumn("header: '".STATUS."', align:'center', width: 80, sortable: false, dataIndex: 'STATUS_KEY'");
    $OBJECT_GRID->addColumn("header: '".TITLE."', width:300, renderer:cssContent, sortable: true, dataIndex: 'SUBJECT_BULLETIN'");
    $OBJECT_GRID->addColumn("header: '".POSTED_DATE."', width: 150, renderer:cssNumber, sortable: true, dataIndex: 'POSTED_DATE'");
    $OBJECT_GRID->addColumn("header: '".CREATED_DATE."', width: 150, renderer:cssNumber, sortable: true, dataIndex: 'CREATED_DATE'");

    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'searchBulletins'
    ";

    $OBJECT_GRID->loadMask = true;
    $OBJECT_GRID->isPagingToolbar = true;
    $OBJECT_GRID->isQuickySearch = true;
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{
               	region:'west'
                ,id:'WEST_ID'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width:350
                ,minSize:350
                ,maxSize:350
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}]
                }]
            }]
        }]
    });
	
    <?
    $html ="var grid = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');";
    $html .="if (grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {";
        $html .="var record = grid.store.getAt(rowIndex);";
        $html .="Ext.getCmp('center').getLayout().setActiveItem(0);";
        $html .="var contextMenu = new Ext.menu.Menu({";
            $html .="items: [{";
                $html .="text: '".EDIT." &raquo; ' + record.data.POSTED_DATE";
            $html .=",iconCls: 'icon-comment_edit'";
            $html .=",handler: function(){";  
                $html .="clickOpenPage('center','','/bulletin/editbulletin/?target=".camemisId()."&objectId=' + record.data.ID);";
                $html .="}";
            $html .="},{";
            $html .="text: '".SHOW_DETAIL." &raquo; ' + record.data.POSTED_DATE";
                $html .=",iconCls: 'icon-application_form_magnify'";
                $html .=",handler: function(){";
                    $html .="openWinIFrame('".SHOW_DETAIL." &raquo; ' + record.data.POSTED_DATE, '/bulletin/showbulletin/?target=".camemisId()."&objectId=' + record.data.ID,600,percentHeight(85))";
                  $html .="}";
            $html .="}]";
        $html .="});";
        $html .="event.stopEvent();";
        $html .="contextMenu.showAt(event.xy);"; 
    $html .="});";
    echo $html;
    ?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>