<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_university/academic/AcademicDBAccess.php';
require_once 'models/CAMEMISUploadDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";

$facette = $this->facette;

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
var chapterId;
Ext.onReady(function() {
    
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    if (UserAuth::getACLValue("BULLETIN_BOARD")){
        
        if ($facette->CREATED_BY == Zend_Registry::get('USER')->CODE){
            $TABR_ITEMS = "[{
                text: '".BULLETIN_BOARD."'
                ,iconCls:'icon-page'
                ,handler: function(){
                    window.parent.openWinIFrame('".BULLETIN_BOARD."', '/bulletin/showbulletin/?objectId=".$objectId."', 750, percentHeight(75));
                }
            }]
            ";
            $IFRAM = "[new Ext.ux.IFrameComponent({ id: 'URL_EDIT_BULLETIN', url: '/bulletin/editbulletin/?objectId=".$objectId."'})]";
        }else{
            $TABR_ITEMS = "[]";
            $IFRAM = "[new Ext.ux.IFrameComponent({ id: 'URL_VIEW_BULLETIN', url: '/bulletin/showbulletin/?objectId=".$objectId."'})]";
        }
        
    }else{
        $TABR_ITEMS = "[]";
        $IFRAM = "[new Ext.ux.IFrameComponent({ id: 'URL_VIEW_BULLETIN', url: '/bulletin/showbulletin/?objectId=".$objectId."'})]";
    }
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            border: false
            ,id: 'content'
            ,layout: 'card'
            ,activeItem: 0
            ,tbar: <?=$TABR_ITEMS;?>
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: <?=$IFRAM;?>
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>