<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/CAMEMISUploadDBAccess.php';
require_once 'models/app_university/student/StudentDBAccess.php';
require_once 'models/CAMEMISYoutubeDBAccess.php';

require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$facette = $this->facette;

$params["objectId"] = $this->facette->GUID;
$VIDEOS  = CAMEMISYoutubeDBAccess::sqlVideos($params);

$BULLETIN_ATTACHMENTS = CAMEMISUploadDBAccess::getAllFileFromObjectId($facette->GUID);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/></meta>
	<style type="text/css">
		a.bulletin{text-decoration:underline;color:#000;}
		a.bulletin:hover{text-decoration:none;}
	</style>
</head>
<title>CAMEMIS Easy and Efficient Education Management</title>
<link href="http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer" rel="stylesheet" type="text/css">
<script type="text/javascript" src="http://www.youtube.com/player_api"></script>
<body style="background-color: #FFFFFF;">
    <style>
    body{
        font:normal 12px Tahoma, Arial, sans-serif,Hanuman;
    }
    </style>
    
    <div id="content" class="x-hide-display">
        <div style="border:0px silver solid;margin:10px;padding:10px;">
            <span style="font-weight:bold;font-size:14px; color:#333;"><?=isset($facette)?showNewlineText($facette->SUBJECT_BULLETIN):"---"?></span>
        </div>
        
        <div style="border:0px silver solid;margin:10px;padding:10px;">
        <span style="font-size:12px; color:#333;">
            <?=isset($facette)?$facette->CONTENT:"---"?>
        </span>
        <br/>
        <?
        if($VIDEOS){
            $KEYS = array();
            foreach($VIDEOS as $value){
                if ($value->YOUTUBE){
                    parse_str( parse_url( $value->YOUTUBE, PHP_URL_QUERY ), $KEYS); 
                    echo "<div style=\"text-align: center;padding:10px; margin: auto\">";
                        echo "
                        <embed id='".$value->ID."' width=\"640px\" height=\"385px\" allowfullscreen=\"true\" allowscriptaccess=\"always\" quality=\"high\" bgcolor=\"#000000\" name=\"".$value->ID."\" style=\"\" src=\"http://www.youtube.com/v/".$KEYS['v']."?enablejsapi=1&version=3&playerapiid=ytplayer\" type=\"application/x-shockwave-flash\">
                        ";
                    echo "</div>";
                    
                }
            }
        }
        ?>
        
	</div>
        <div id="attachments" class="x-hide-display">
        <?
        if($BULLETIN_ATTACHMENTS){
            $i=1;
            foreach($BULLETIN_ATTACHMENTS as $value){
                print_r("".$i++.""."."." <a class='bulletin' target='_blank' href='/public/".CAMEMISUploadDBAccess::getMyFolder()."".$value->FILE_SHOW."'>".$value->FILE_NAME."</a><br/>");
            }
        }
        ?>
    </div>
</body>
</html>

<script>

    Ext.onReady(function() {
        <?		
        $ATTACHMENT_FILES = "
        [{
            extype: 'panel'
            ,iconCls:'icon-attach'
            ,title: '".ATTACHMENT."'
            ,border: true
            ,autoHeight: true
            ,layout: 'form'
            ,bodyStyle: 'padding:10px'
            ,style: 'padding-bottom: 5px'
            ,items:[{
                border:false
                ,contentEl: 'attachments'
            }]
        }]
        ";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,tbar:[{
                    text: '<?=CANCEL?>'
                    ,id: 'CANCEL_ID'
                    ,formBind:true
                    ,iconCls:'icon-cancel'
                    ,scope:this
                    ,handler: function(){
                        <?
                        foreach($VIDEOS as $value){
                            echo "var myPlayer".$value->ID." = document.getElementById('".$value->ID."'); if(myPlayer".$value->ID.") myPlayer".$value->ID.".stopVideo();";
                        }
                        ?>
                        window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);
                    }
                }]
                ,id: 'CONTENT'
                ,title: '<?=BULLETIN_BOARD;?>'
                ,xtype: 'panel'
                ,layout: 'card'
                ,enableTabScroll:true
                ,activeItem: 0
                ,items:[{
                    layout:'border'
                    ,border: false
                    ,defaults: {
                        collapsible: false
                        ,split: true
                    }
                    ,items: [{
                        region:'east'
                        ,margins: '3 3 3 0'
                        ,cmargins: '3 3 3 3'
                        ,width: 250
                        ,minSize: 250
                        ,maxSize: 250
                        ,layout: 'fit'
                        ,items:[{
                            xtype: 'form'
                            ,border: false
                            ,bodyStyle: 'background:<?=CamemisPage::userFormBgColor();?>; padding:10px'
                            ,labelWidth: 145
                            ,items: <?=$ATTACHMENT_FILES?>
                        }]
                    },{
                        collapsible: false
                        ,id: 'center'
                        ,region:'center'
                        ,margins: '3 0 3 3'
                        ,layout: 'fit'
                        ,bodyStyle: 'padding:10px'
                        ,autoScroll: true
                        ,contentEl:'content'
                    }]
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>