<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 27.04.2011
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$SQL = "SELECT * FROM t_academicdate WHERE STATUS=1";
$resultRows = Zend_Registry::get('DB_ACCESS')->fetchAll($SQL);

function countSendSMSSemester($startData, $endDate){
    $SQL = "SELECT COUNT(*) AS C FROM t_user_sms WHERE SEND_DATE>='".$startData."' AND SEND_DATE<='".$endDate."' AND SMS_ID<>0 AND SEND_DATE<>'0000-00-00'";
    $resultRows = Zend_Registry::get('DB_ACCESS')->fetchRow($SQL);
    return $resultRows?$resultRows->C:0;
}
?>


<!--
<script type="text/javascript" src="https://www.google.com/jsapi"></script>

 <script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', '<?=YEAR?>');
        data.addColumn('number', '<?=FIRST_SEMESTER?>');
        data.addColumn('number', '<?=SECOND_SEMESTER?>');
        data.addRows(4);
        data.setValue(0, 0, '2004');
        data.setValue(0, 1, 1000);
        data.setValue(0, 2, 400);
        data.setValue(1, 0, '2005');
        data.setValue(1, 1, 1170);
        data.setValue(1, 2, 460);
        data.setValue(2, 0, '2006');
        data.setValue(2, 1, 660);
        data.setValue(2, 2, 1120);
        data.setValue(3, 0, '2007');
        data.setValue(3, 1, 1030);
        data.setValue(3, 2, 540);

        var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
        chart.draw(data, {width: 400, height: 240, title: 'Company Performance',
        vAxis: {title: 'Year', titleTextStyle: {color: 'red'}}
        });
    }
</script>

<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', '<?=YEAR?>');
        data.addColumn('number', '<?=FIRST_SEMESTER?>');
        data.addColumn('number', '<?=SECOND_SEMESTER?>');
        data.addRows(4);
        <?
        /*
        if ($resultRows){
            $i=0;
            foreach($resultRows as $value){
                
                $COUNT_FIRST_SEMESTER = countSendSMSSemester(
                    $value->SEMESTER1_START
                    , $value->SEMESTER1_END
                );
                
                $COUNT_SECOND_SEMESTER = countSendSMSSemester(
                    $value->SEMESTER2_START
                    , $value->SEMESTER2_END
                );
                
                echo "data.setValue($i, 0, '".addslashes($value->NAME)."');\n";
                echo "data.setValue($i, 1, $COUNT_FIRST_SEMESTER);\n";
                echo "data.setValue($i, 2, $COUNT_SECOND_SEMESTER);\n";
                
                $i++;
            }
        }
        */
        ?>

        var chart = new google.visualization.BarChart(document.getElementById('chart_div1'));
        chart.draw(
        data, {
            width: percentWidth(100)
            ,height: 300
            ,title: '<?=STATUS?>'
            ,vAxis: {
                title: '<?=YEAR?>'
                , titleTextStyle: {color: 'red', size: 11}, width: 150}
            }
        );
    }
</script>
<script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Task');
        data.addColumn('number', 'Hours per Day');
        data.addRows(5);
        data.setValue(0, 0, '<?=TOTAL?>');
        data.setValue(0, 1, <?=$this->countSMSCredits;?>);
        data.setValue(1, 0, '<?=USED?>');
        data.setValue(1, 1, <?=$this->countSMSUsed;?>);
        var chart = new google.visualization.PieChart(document.getElementById('chart_div2'));
        chart.draw(data, {width: 450, height: 300, title: '<?=STATUS?>'});
      }
    </script>
<div id="chart_div1"></div>
<div id="chart_div2"></div>
-->

<html>
  <head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['<?=MONTH?>', 'Successfully', 'Not Successfully'],
          ['<?=FEBRUARY?>',  1000,  400],
          ['<?=MARCH?>',  1170,      460],
          ['<?=APRIL?>',  660,       1120],
          ['<?=MAY?>',  1030,      730],
          ['<?=JUNE?>',  750,      540],
          ['<?=JULY?>',  1030,      45],
          ['<?=AUGUST?>',  160,      540],
          ['<?=SEPTEMBER?>',  1030,      540],
          ['<?=OCTOBER?>',  1030,      540],
          ['<?=NOVEMBER?>',  1030,      158],
          ['<?=DECEMBER?>',  1030,      30]
        ]);

        var options = {
          title: 'CAMEMIS SMS Send Status',
          hAxis: {title: '<?=MONTH?>', titleTextStyle: {color: 'red'}}
        };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="chart_div" style="width: 900px; height: 500px;"></div>
  </body>
</html>


<?
//print_r($resultRows);
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>