<?php

    require_once 'excel/phpexcel/Classes/PHPExcel.php';
    require_once 'excel/phpexcel/Classes/PHPExcel/IOFactory.php';
    require_once 'clients/CamemisExcelReport.php';
    require_once 'models/app_university/examination/ExaminationDBAccess.php';
    require_once 'models/app_university/examination/StudentExaminationDBAccess.php';                         
    
    $params["objectId"] = isset($_GET["objectId"]) ? addText($_GET["objectId"]) : "";
           
    $entries = array(); 
     
    $columns[] = "STT";
    $columns[] = "TEACHER_NAME";
    $columns[] = "NAME";
    $columns[] = "CLASS";
    $columns[] = "TERM";
    $columns[] = "PHONE";
    $columns[] = "EMAIL";

    $ShowColumns[] = "N°";
    $ShowColumns[] = TEACHER;
    $ShowColumns[] = SUBJECT;
    $ShowColumns[] = CURRENT_CLASS;
    $ShowColumns[] = TERM;
    $ShowColumns[] = PHONE;
    $ShowColumns[] = EMAIL;  

    $CamemisExcelReport = CamemisExcelReport::GetInstance();
    $CamemisExcelReport->iHeaderRowStart = 4;
    $CamemisExcelReport->iRowStart = 5;
    $objPHPExcel = $CamemisExcelReport->createExcelObject($columns, $ShowColumns, $entries, null, false, true);
     
    $CamemisExcelReport->createTitle('CAMEMIS', "G", 2, "A");

    $objPHPExcel->getActiveSheet()->setCellValue("A1", 'SCHOOL INFORMATION');
    $objPHPExcel->getActiveSheet()->mergeCells("A1:D1");
    $objPHPExcel->getActiveSheet()->setCellValue("A3", 'CLASS INFORMATION');
    $objPHPExcel->getActiveSheet()->setCellValue("E3", 'HALLO1');
    $objPHPExcel->getActiveSheet()->mergeCells("E3:F3");
    $objPHPExcel->getActiveSheet()->mergeCells("A3:D3");

    $objPHPExcel->getActiveSheet()->setCellValue("G3", 'HALLO2');
 
    $objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(70);
    $objPHPExcel->getActiveSheet()->getRowDimension(2)->setRowHeight(70);
    $objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(70);

    $style = array(
        'alignment' => array(
            'vertical' => PHPExcel_Style_Alignment::VERTICAL_TOP
        )
    );
    $objPHPExcel->getActiveSheet()->getStyle("A3:G3")->applyFromArray($style);
    $filename = "List of teachers";
    $CamemisExcelReport->createSignatureField();
    header("Content-Type: application/x-msexcel; name=\"" . $filename . ".xls\"");
    header("Content-Disposition: attachment; filename=\"" . $filename . ".xls\"");
    // IE <= 6 cache fix
    header('Expires: 0');
    header('Pragma: cache');
    header('Cache-Control: private');
    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');

    $objWriter->save('php://output');
?>

