<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$studentId = isset($_GET["studentId"])? addText($_GET["studentId"]):$this->studentId;
$schoolyearId = isset($_GET["schoolyearId"])?addText($_GET["schoolyearId"]):$this->schoolyearId;
$academicId = isset($_GET["academicId"])? (int) $_GET["academicId"]:$this->academicId;
$campusId = isset($_GET["campusId"])?addText($_GET["campusId"]):$this->campusId;

$setParams = "&objectId={$studentId}&academicId={$academicId}&schoolyearId={$schoolyearId}&campusId={$campusId}";

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>

	Ext.onReady(function() {
		
		<?
		/**
		 * Extjs: s.gif
		 */
		$CAMEMIS_PAGE_OBJECT->setCostumerCSS();
		$CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

		$PENEL_ITEMS = Array();

		$SCHOOL = "{
			title: '".MAIN_CONTENT."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'MAIN_CONTENT', url: '/student/creditstudentdashboard/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
		}";
		$PENEL_ITEMS[] = $SCHOOL;

		//Schedule for all subjects
		$SCHEDULE = "{
			title: '".SCHEDULE."'
			,layout: 'fit'
			,disabled: true
			,items:[new Ext.ux.IFrameComponent({ id: 'SCHEDULE', url: '/student/creditstudentschedule/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
		}";
		$PENEL_ITEMS[] = $SCHEDULE;

		$SCHOOL_EVENTS = "{
			title: '".EVENT."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'SCHOOL_EVENTS', url: '/student/creditstudentschoolevent/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
		}";
		$PENEL_ITEMS[] = $SCHOOL_EVENTS;

		$ASSESSMENT = "{
			title: '".ASSESSMENT."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'ASSESSMENT', url: '/evaluation/gradebookcredit/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
		}";
		$PENEL_ITEMS[] = $ASSESSMENT;

		$ATTENDANCE = "{
			title: '".ATTENDANCE."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'ATTENDANCE', url: '/student/creditstudentattendance/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
		}";
		$PENEL_ITEMS[] = $ATTENDANCE;

		$DISCIPLINE = "{
			title: '".DISCIPLINE."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'DISCIPLINE', url: '/student/creditstudentdiscipline/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
		}";
		$PENEL_ITEMS[] = $DISCIPLINE;

		$SUBJECT_LIST = "{
			title: '".SUBJECT_LIST."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'SUBJECT_LIST', url: '/student/creditstudentsubject/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
		}";
		$PENEL_ITEMS[] = $SUBJECT_LIST;

		$CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
		?>
		viewport = new Ext.Viewport({
			layout: 'fit'
			,border: false
			,items:[{
				layout:'fit'
				,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
				,border: false
				,items:[{
					xtype: 'tabpanel'
					,tabPosition: 'top'
					,plain:true
					,activeTab: 0
					,enableTabScroll:true
					,items:<?=$CHOOSE_ITEMS;?>
				}]
			}]
		});
	});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>