<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_GRID = new CamemisGrid("SUBJECT", "LIST");  
$OBJECT_GRID->setLoadUrl('/subject/jsonload/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>

<script>
Ext.onReady(function() {

	function cssText(value){
		return '<div style="font-weight:normal; color:#333;background:#FFF;">' + value + '</div>';
	}
	<?
	$CAMEMIS_PAGE_OBJECT->setCostumerCSS();
	$CAMEMIS_PAGE_OBJECT->setExtDefaultGif(); 

	$OBJECT_GRID->addReadField("name: 'SUBJECT_SHORT'");
	$OBJECT_GRID->addReadField("name: 'SUBJECT_NAME'");
	$OBJECT_GRID->addReadField("name: 'FIRST_SEMESTER'");
	$OBJECT_GRID->addReadField("name: 'SECOND_SEMESTER'");
	$OBJECT_GRID->addReadField("name: 'CREDIT_NUMBER'");
	$OBJECT_GRID->addReadField("name: 'SESSION'");
	$OBJECT_GRID->addReadField("name: 'ID'");
	$OBJECT_GRID->addReadField("name: 'CLASS_ID'");
	$OBJECT_GRID->addReadField("name: 'SUBJECT_ID'");
	$OBJECT_GRID->addReadField("name: 'STATUS'");

	$OBJECT_GRID->addColumn("header: '<b>".SHORT."</b>',hidden: false, align:'left', menuDisabled : true, sortable: true, renderer:cssText, width:100, dataIndex: 'SUBJECT_SHORT'");
	$OBJECT_GRID->addColumn("header: '<b>".SUBJECT."</b>',hidden: false, align:'left', menuDisabled : true, sortable: true, renderer:cssText, width:180, dataIndex: 'SUBJECT_NAME'");
	$OBJECT_GRID->addColumn("header: '<b>".NUMBER_CREDIT."</b>',hidden: false, align:'left', menuDisabled : true, sortable: true, renderer:cssText, width:180, dataIndex: 'CREDIT_NUMBER'");
	$OBJECT_GRID->addColumn("header: '<b>".TOTAL_SESSION."</b>',hidden: false, align:'left', menuDisabled : true, sortable: true, renderer:cssText, width:180, dataIndex: 'SESSION'");
	$OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>',hidden: false, align:'left', menuDisabled : true, sortable: true, renderer:cssText, width:100, dataIndex: 'STATUS'");

    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonStudentSubjectCredit'  
        ,schoolyearId: '".$this->schoolyearId."'
        ,studentId: '".$this->objectId."'
    ";

	$OBJECT_GRID->addTBarItems("
		tbar.add([{
			id: 'REGISTRATION_ID'
			,text: '".REGISTRATION."'
			,iconCls:'icon-add'
			,scope:this
			,disabled: true
			,handler: function(){
				Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
			}
		}]);
	");

	$SHOW_ITEMS = array();

	$SHOW_SUBJECT ="{
		text: 'Show Subject'
		,iconCls: 'icon-application_form_magnify'
		,disabled: true
		,handler: function(){
			//contextMenu.hide();clickOpenPage('content','','/schoolevent/showitem/?&objectId=' + record.data.ID);
		}
	}";
	$SHOW_ITEMS[] = $SHOW_SUBJECT;

	$SHOW_ACADEMIC_INFO ="{
		text: 'Show Credit Information'
		,iconCls: 'icon-application_form_magnify'
		,disabled: true
		,handler: function(){
			//contextMenu.hide();clickOpenPage('content','','/schoolevent/showitem/?&objectId=' + record.data.ID);
		}
	}";
	$SHOW_ITEMS[] = $SHOW_ACADEMIC_INFO;

	$SHOW_ASSESSEMENT ="{
		text: 'Show Assessement'
		,iconCls: 'icon-application_form_magnify'
		,disabled: true
		,handler: function(){
			//contextMenu.hide();clickOpenPage('content','','/schoolevent/showitem/?&objectId=' + record.data.ID);
		}
	}";
	$SHOW_ITEMS[] = $SHOW_ASSESSEMENT;

	$SHOW_HOMEWORK ="{
		text: 'Show Homework'
		,iconCls: 'icon-application_form_magnify'
		,disabled: true
		,handler: function(){
			//contextMenu.hide();clickOpenPage('content','','/schoolevent/showitem/?&objectId=' + record.data.ID);
		}
	}";
	$SHOW_ITEMS[] = $SHOW_HOMEWORK;

	$SHOW_PANEL_ITEMS = "[".implode(',',$SHOW_ITEMS)."]";

	$OBJECT_GRID->loadMask = false;
	$OBJECT_GRID->isQuickySearch = false;
	$OBJECT_GRID->isObjectDefaultOnLoad = true;

	$OBJECT_GRID->forceFit = "false";
	$OBJECT_GRID->renderJS();

	?>
	viewport = new Ext.Viewport({
		layout: 'fit'
		,border: false
		,items:[{
			border: false
			,id:'content'
			,layout: 'card'
			,activeItem: 0
			,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType()?>'}]
		}]
	});

	var grid = Ext.getCmp('<?=$OBJECT_GRID->getObjectId();?>');
	if (grid)
	grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {
		var record = grid.store.getAt(rowIndex);
		var contextMenu = new Ext.menu.Menu({
			items: <?=$SHOW_PANEL_ITEMS;?>
		});
		event.stopEvent();
		contextMenu.showAt(event.xy);
	});
    /*Ext.getCmp('SUBJECT_LIST_ID').on('cellclick', function(grid, rowIndex, columnIndex, event) {
        var record = grid.store.getAt(rowIndex);
        clickOpenPage('content','','/subject/subjectdisplaymain/?setId='+record.data.CLASS_ID+'-' + record.data.SUBJECT_ID);
    });*/
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>