<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 26.02.2011
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("ORGANIZATION_CHART");
$OBJECT_FORM->setLoadUrl('/organization/jsonload/');
$OBJECT_FORM->setSaveUrl('/organization/jsonsave/');

$OBJECT_DATA = $this->objectData;

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {".CamemisField::Textfield("NAME", "NAME", NAME)."}
                    ,{".CamemisField::Textarea("DESCRIPTION", DESCRIPTION, 150)."}
                ]
            }]
        }
        ";

        $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,items: [
            ".$DETAIL_INFORMATION."
        ]
        ";
        $OBJECT_FORM->addObjectItems($items);

        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        ");
        if(UserAuth::getACLValue("ORGANIZATION_CHART_REMOVE_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormRemoveObject($this->remove_status));
        if(UserAuth::getACLValue("ORGANIZATION_CHART_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease());
        if(UserAuth::getACLValue("ORGANIZATION_CHART_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());

        $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '".$this->objectId."'");
        $OBJECT_FORM->setSaveParams("
        cmd: 'updateObject'
            ,objectId: '".$this->objectId."'
        ");
        $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '".$this->objectId."'");

        $OBJECT_FORM->setonEmbeddedEvents("
            window.parent.Ext.getCmp('TREE.ORGANIZATION_CHART_LIST_ID').root.reload();
            ".camemisPage::setRequestURI()."
        ");
        
        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            window.parent.Ext.getCmp('TREE.ORGANIZATION_CHART_LIST_ID').root.reload();
            ".camemisPage::setRequestURI()."
        ");
        
        $OBJECT_FORM->setRemoveParams("
            cmd: 'removeObject'
            ,objectId: '".$this->objectId."'
        ");

        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            window.parent.Ext.getCmp('TREE.ORGANIZATION_CHART_LIST_ID').root.reload();
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'panel'
                ,id: 'panel'
                ,border: false
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>