<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 27.04.2011
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("USER_ONLINE");  
$OBJECT_FORM->setLoadUrl('/sms/jsonload/');

$OBJECT_GRID = new CamemisGrid("SMS", "UNIT");
$OBJECT_GRID->setLoadUrl('/sms/jsonload/');
$OBJECT_GRID->setSaveUrl('sms/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$FORM_ITEMS_CHECKBOX = "[";
    $FORM_ITEMS_CHECKBOX .= "{".CamemisField::Checkbox("TEACHER_EVENT", "TEACHER_EVENT", IF_TEACHER_ENTER_EVENT, false, false)."}";
    $FORM_ITEMS_CHECKBOX .= ",{".CamemisField::Checkbox("TEACHER_DISCIPLINE", "TEACHER_DISCIPLINE", IF_TEACHER_ENTER_DISCIPLINE, false, false)."}";
    $FORM_ITEMS_CHECKBOX .= ",{".CamemisField::Checkbox("TEACHER_ABSENCE", "TEACHER_ABSENCE", IF_TEACHER_ENTER_ABSENCE, false, false)."}";
    $FORM_ITEMS_CHECKBOX .= ",{border: false,style: 'padding-bottom: 5px'}";
    $FORM_ITEMS_CHECKBOX .= ",{
        flex: 1
        ,border:false
        ,defaultType: 'checkbox'
        ,layout: 'form'
        ,labelWidth:250
        ,items: [{
            fieldLabel: '".IF_TEACHER_ENTER_SCORE."',
            boxLabel: '".REGULAR_TEST."',
            name: 'IF_TEACHER_ENTER_SCORE_RT'
        },{
            boxLabel: '".PERIODICAL_TEST."',
            name: 'IF_TEACHER_ENTER_SCORE_PT'
        },{
            checked: true,
            boxLabel: '".SEMESTER_TEST."',
            name: 'IF_TEACHER_ENTER_SCORE_ST'
        }]
    }    
    ";
$FORM_ITEMS_CHECKBOX .= "]";

$FORM_SMS_TEXT_ABSENCE = "[";
    $FORM_SMS_TEXT_ABSENCE .= "{".CamemisField::Textarea("SMS_TEXT_ABSENCE", false,35)."}";
$FORM_SMS_TEXT_ABSENCE .= "]";

$FORM_SMS_SMS_TEXT_DISCIPLINE = "[";
    $FORM_SMS_SMS_TEXT_DISCIPLINE .= "{".CamemisField::Textarea("SMS_TEXT_DISCIPLINE", false,35)."}";
$FORM_SMS_SMS_TEXT_DISCIPLINE .= "]";

$FORM_SMS_TEXT_ASSESSMENT = "[";
    $FORM_SMS_TEXT_ASSESSMENT .= "{".CamemisField::Textarea("SMS_TEXT_ASSESSMENT", false,35)."}";
$FORM_SMS_TEXT_ASSESSMENT .= "]";
?>
<style>
    span.textSMS{
        font-size:14px;font-weight: bold;color:#000000;
    }
    span.textSMSValue{
        font-size:18px;font-weight: bold;color:#CC0000;
    }
</style>
<script>
    var startDate;
    var endDate;
    Ext.apply(Ext.form.VTypes, {
        daterange : function(val, field) {
            var date = field.parseDate(val);
            if(!date){
                return false;
            }
            if (field.startDateField) {
                var start = Ext.getCmp(field.startDateField);
                if (!start.maxValue || (date.getTime() !== start.maxValue.getTime())) {
                    start.setMaxValue(date);
                    start.validate();
                }
            }
            else if (field.endDateField) {
                var end = Ext.getCmp(field.endDateField);
                if (!end.minValue || (date.getTime() !== end.minValue.getTime())) {
                    end.setMinValue(date);
                    end.validate();
                }
            }
            return true;
        }
    });
    var formSetting = new Ext.FormPanel({
        id: 'MYFORM'
        ,frame: false
        ,border: true
        ,width: 550
        ,labelAlign: 'left'
        ,items:[{
            border: false
            ,layout: 'form'
            ,title: '<?=SETTING;?>'
            ,items:[{
                layout: 'anchor'
                ,border: false
                ,items:[{
                    layout: 'anchor'
                    ,border: false
                    ,bodyStyle: 'padding:10px'
                    ,items: <?=$FORM_ITEMS_CHECKBOX;?>
                },{
                    layout: 'anchor'
                    ,border: false
                    ,bodyStyle: 'padding:10px'
                    ,items:[{
                        layout: 'fit'
                        ,title:'<?=SMS_TEXT_ABSENCE?>'
                        ,style: 'padding-bottom: 5px'
                        ,bodyStyle: 'padding:3px'
                        ,items: <?=$FORM_SMS_TEXT_ABSENCE;?>
                    },{
                        layout: 'fit'
                        ,title:'<?=SMS_TEXT_DISCIPLINE?>'
                        ,style: 'padding-bottom: 5px'
                        ,bodyStyle: 'padding:3px'
                        ,items: <?=$FORM_SMS_SMS_TEXT_DISCIPLINE;?>
                    },{
                        layout: 'fit'
                        ,title:'<?=SMS_TEXT_SUBJECT_SCORE?>'
                        ,style: 'padding-bottom: 5px'
                        ,bodyStyle: 'padding:3px'
                        ,items: <?=$FORM_SMS_TEXT_ASSESSMENT;?>
                    }]
                }]
            }]
            ,tbar:['->',{
                text: '<?=SAVE?>'
                ,iconCls:'icon-disk'
                ,handler: function(){
                    Ext.getCmp('MYFORM').getForm().submit({
                        url: '/school/jsonsave/'
                        ,scope:this
                        ,success: function(result){
                            XMsg('<?=STATUS?>','<?=ACTION_SUCCESSFULLY_SAVED?>'); 
                        }
                        ,failure: function(result){}
                        ,params:{
                            cmd: 'updateObject'
                        }
                    });
                }
            }]
        }]
    });
    Ext.onReady(function() {
    
        function renderTextSMS(value, metadata, record){
            return '<div style="font-weight:bold; color: #333;">' + value + '</div>';
        }
        <?
        $CAMEMIS_PAGE_OBJECT->setAddTab();

        $OBJECT_FORM->addObjectItems("
            xtype:'fieldset'
            ,collapsible:true,collapsed:false
            ,collapsed: false
            ,title: '".DATELINE."'
            ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;padding:10px'
            ,width: 310
            ,items:[{
                name: 'START_DATE'
                ,hidden: false
                ,width: 150
                ,fieldLabel: '" . START_DATE . "'
                ,xtype: 'datefield'
                ,id: 'START_DATE'
                ,vtype: 'daterange'
                ,endDateField: 'END_DATE'
                ,format: '" . setExtDatafieldFormat() . "'
                ,allowBlank: false
            },{
                name: 'END_DATE'
                ,hidden: false
                ,width: 150
                ,fieldLabel: '" . END_DATE . "'
                ,xtype: 'datefield'
                ,id: 'END_DATE'
                ,vtype: 'daterange'
                ,format: '" . setExtDatafieldFormat() . "'
                ,startDateField: 'START_DATE'
                ,allowBlank: false
            }]
        ");   
        
        $OBJECT_FORM->addTBarItems("
            text: '".RESET."'
            ,iconCls:'icon-arrow_undo'
            ,handler: function(){
                ".CamemisPage::setRequestURI()."
            }
        ");
        
        $OBJECT_FORM->addTBarItems("
            text: '".FIND."'
            ,id: 'FIND_ID'
            ,formBind:true
            ,iconCls:'icon-magnifier'
            ,scope:this
            ,handler: function(){
                form = this.getForm();
                _startDate = form.findField('START_DATE').getValue();
                _endDate = form.findField('END_DATE').getValue();
                startDate = _startDate?_startDate.format('Y-m-d'):'';
                endDate =_endDate? _endDate.format('Y-m-d'):'';
                
                title = startDate + ' - ' +endDate;
                
                if (_startDate && _endDate) addTab(title,title,'/sms/chartsent/?objectId=111');
            }
        ");
    
        $OBJECT_FORM->setBodyStyle("padding:10px;background:".CamemisPage::userFormBgColor().";");
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->isKeys = false;
        $OBJECT_FORM->renderJS();
        ////////////////////////////////////////////////////////////////////////
        
        $OBJECT_GRID->addReadField("name: 'SUBSCRIPTION_COUNT'");
        $OBJECT_GRID->addReadField("name: 'PRICING'");
        $OBJECT_GRID->addReadField("name: 'SUBSCRIPTION_DATE'");
        $OBJECT_GRID->addReadField("name: 'STATUS'");

        $OBJECT_GRID->addColumn("header: '<b>Unit</b>', width: 130, renderer: renderTextSMS, sortable: true, dataIndex: 'SUBSCRIPTION_COUNT'");
        $OBJECT_GRID->addColumn("header: '<b>Pricing</b>', width: 130, renderer: renderTextSMS, sortable: true, dataIndex: 'PRICING'");
        $OBJECT_GRID->addColumn("header: '<b>".DATE."</b>', width: 130, renderer: renderTextSMS, sortable: true, dataIndex: 'SUBSCRIPTION_DATE'");
        $OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>', width: 120, renderer: renderTextSMS, sortable: true, dataIndex: 'STATUS'");

        $OBJECT_GRID->isObjectDefaultOnLoad = true;
        $OBJECT_GRID->baseParams = "
            start:0
            ,limit:100
            ,cmd: 'jsonListSubscriptons'
        ";
        $OBJECT_GRID->loadMask = true;
        $OBJECT_GRID->isQuickySearch = false;
        $OBJECT_GRID->removeNAME = "STUDENT";
        $OBJECT_GRID->forceFit = "false";
        $OBJECT_GRID->renderJS();
        
        ?>
        var tabs =  new Ext.TabPanel({
            autoTabs:true
            ,border:false
            ,tabPosition: 'top'
            ,enableTabScroll:true
            ,activeTab:0
            ,items:[{
                title: '<?=SETTINGS?>'
                ,id: 'TAB_DEFAULT'
                ,layout: 'fit'
                /*,iconCls: 'icon-tabs'*/
                ,items: [{
                    layout:'anchor'
                    ,autoScroll: true
                    ,border:false
                    ,items:[{
                        layout: 'anchor'
                        ,border: false
                        ,bodyStyle: 'padding:10px'
                        ,items: [{
                            title: '<?=TOTAL;?>'
                            ,style: 'padding-bottom: 5px'
                            ,bodyStyle: 'font-weight:bold; font-size: 16px; color: #333;background:#FFF; padding:10px'
                            ,autoHeight: true
                            ,width: 550
                            ,html:'100 Units'
                        },{
                            title: '<?=USED;?>'
                            ,style: 'padding-bottom: 5px'
                            ,bodyStyle: 'font-weight:bold; font-size: 16px; color: #CC0000;background:#FFF; padding:10px'
                            ,autoHeight: true
                            ,width: 550
                            ,html:'0 Units'
                        },{
                            border:false
                            ,style: 'padding-bottom: 5px'
                            ,autoHeight: true
                            ,width: 550
                            ,items:[formSetting]
                        },{
                            title: ''
                            ,style: 'padding-bottom: 5px'
                            ,height:350
                            ,width: 550
                            ,layout:'fit'
                            ,tbar:['->',{
                                text:'<?=SMS_SUBSCRIPTION?>'
                                ,iconCls: 'icon-application_form_add'
                                ,handler:function(){
                                    openWinIFrame('<?=SMS_SUBSCRIPTION?>', '/sms/smssubscription/?subscriptionId=new', 600,250);
                                }
                            }]
                            ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}]
                        }]
                    }]
                }]
            }]
        });
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    region:'west'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width: 350
                    ,minSize: 350
                    ,maxSize: 350
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
                },{
                    collapsible: false
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,items: tabs
                }]
            }]
        });
        
        <?=$OBJECT_GRID->ExtgetCmp();?>.on('cellclick', function(grid, rowIndex, columnIndex, event) {
            var record = grid.store.getAt(rowIndex);
            openWinIFrame('<?=SMS_SUBSCRIPTION?>', '/sms/smssubscription/?subscriptionId=' + record.data.ID, 600,250);
        });
        Ext.getCmp('MYFORM').load({
            url: '/school/jsonload/'
            ,params:{cmd:'loadObject'}
            ,success: function(form, action) {
                //
            }
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>