<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 19.02.2012
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("SMS");
$OBJECT_FORM->setLoadUrl("/sms/jsonload/");
$OBJECT_FORM->setSaveUrl("/sms/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $DETAIL_INFORMATION = "
        {
            title: '".NAME."'
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {".CamemisField::Numberfield("SUBSCRIPTION_COUNT", "SUBSCRIPTION_COUNT", COUNT, true, false, false, false)."}
                    ,{".CamemisField::Checkbox("ACTIVE", "ACTIVE", ACTIVE, false, false)."}
                ]
            }]
        }
        ";
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: [
                ".$DETAIL_INFORMATION."
            ]
        ";
        $OBJECT_FORM->addObjectItems($items);

        $OBJECT_FORM->setLoadParams("cmd: 'jsonLoadSMSSubscription',subscriptionId: '".$this->subscriptionId."'");
        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonActionSMSSubscription'
            ,subscriptionId: '".$this->subscriptionId."'
        ");
        
        if($this->subscriptionId !="new"){
            
            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                ".camemisPage::setRequestURI()."
                window.parent.Ext.getCmp('SMS_UNIT_ID').store.reload();
                
            ");
            
        }else{
            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                var result = Ext.util.JSON.decode(action.response.responseText);
                var subscriptionId = result.subscriptionId;
                window.location='".$_SERVER["REQUEST_URI"]."&subscriptionId='+subscriptionId;
                window.parent.Ext.getCmp('SMS_UNIT_ID').store.reload();
            ");
        }
        
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        
        $OBJECT_FORM->isObjectDefaultOnLoad = true;
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>