<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 22.04.2011
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisSchoolTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("SMS", "LIST");
$OBJECT_GRID->setLoadUrl('/sms/jsonload/');
$OBJECT_GRID->setSaveUrl('sms/jsonsave/');

$academicId = isset($_GET['academicId'])?$_GET['academicId']:"";
$OBJECT_DATA = $this->OBJECT_DATA;

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    
    <?
    
    switch($this->priority){
        case 0:
        case 1:
        case 2:
            $DISABLED_ONLY_REGISTERED_PERSONS = 'false';
            $DISABLED_ALL_PERSONS = 'true';
            break;
        case 3:
            $DISABLED_ONLY_REGISTERED_PERSONS = 'false';
            $DISABLED_ALL_PERSONS = 'false';
            break;
    }
    
    $OBJECT_GRID->addReadField("name: 'ICON_SMS_SERVICES'");
    $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
    $OBJECT_GRID->addReadField("name: 'LASTNAME'");
    $OBJECT_GRID->addReadField("name: 'GENDER'");
    $OBJECT_GRID->addReadField("name: 'DATE_BIRTH'");
    $OBJECT_GRID->addReadField("name: 'CLASS_NAME'");
    
    $OBJECT_GRID->addColumn("header: '".SMS_SERVICES."', align:'center', width: 100, sortable: true, dataIndex: 'ICON_SMS_SERVICES'");
    if(!SchoolDBAccess::displayPersonNameInGrid()){
        $OBJECT_GRID->addColumn("header: '".LASTNAME."', align:'left', width: 120, sortable: false, dataIndex: 'LASTNAME'");
        $OBJECT_GRID->addColumn("header: '".FIRSTNAME."', align:'left', width: 120, sortable: false, dataIndex: 'FIRSTNAME'");
    }else{
        $OBJECT_GRID->addColumn("header: '".FIRSTNAME."', align:'left', width: 120, sortable: false, dataIndex: 'FIRSTNAME'");
        $OBJECT_GRID->addColumn("header: '".LASTNAME."', align:'left', width: 120, sortable: false, dataIndex: 'LASTNAME'"); 
    } 
    $OBJECT_GRID->addColumn("header: '".GENDER."', align:'left', width: 100, sortable: true, dataIndex: 'GENDER'");
    $OBJECT_GRID->addColumn("header: '".DATE_BIRTH."', align:'left', width: 120, sortable: true, dataIndex: 'DATE_BIRTH'");
    
    if (!$academicId){
        $OBJECT_GRID->addColumn("header: '".GRADE_CLASS."', align:'left', width: 120, sortable: true, dataIndex: 'CLASS_NAME'");
    }
    
    $OBJECT_GRID->isObjectDefaultOnLoad = false;
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,objectId: '".$this->objectId."'
        ,academicId: '".$academicId."'
        ,cmd: 'jsonUnassignedStudentsSMS'
    ";
    
    $OBJECT_GRID->addTBarItems("
        tbar.add(['-',{
            id: 'APPLY_ID'
            ,text: '".APPLY."'
            ,iconCls:'icon-disk'
            ,scope:this
            ,disabled: false
            ,handler: function(){
               var sm = this.getSelectionModel();
                var record = sm.getSelected();
                if(record){
                    var clickId = record.data.ID;
                    var futureacademicId = record.data.FUTURE_CLASS_ID;
                    var clickName = record.data.STUDENT_NAME;   
                    Ext.MessageBox.show({
                        title:'".STATUS."'
                        ,msg: '".MSG_ACCEPT_CHOICE."'
                        ,buttons: Ext.MessageBox.YESNO
                        ,fn: function(btn){
                            if (btn == 'yes'){
                                var selids = '';
                                var seltexts = '';
                                var sels = Ext.getCmp('".$OBJECT_GRID->getObjectId()."').getSelectionModel().getSelections();
                                for( var i = 0; i < sels.length; i++ ) {
                                    if (i >0) selids += ',';
                                    selids += sels[i].get('ID');
                                    if (i >0) seltexts += '\\n';
                                    seltexts += i+1 + ') ' + sels[i].get('LASTNAME') +' '+ sels[i].get('FIRSTNAME');
                                }
                                Ext.Ajax.request({
                                    url: '/sms/jsonsave/'
                                    ,method: 'POST'
                                    ,params: {
                                        cmd: 'actionAddStudentsToSMSSevices'
                                        ,selectionIds: selids
                                        ,objectId: '".$this->objectId."'
                                    }
                                    ,success: function(result) {
                                        Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
                                        window.parent.Ext.getCmp('SMS_PERSONS_ID').store.reload();
                                    }
                                });
                            }
                        }
                        ,icon: Ext.MessageBox.QUESTION
                    });
                }else{
                    ".camemisPage::alertPleaseSelect()."
                } 
            }
        }]);
    ");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add(['-',{
            id: 'ONLY_REGISTERED_PERSONS'
            ,disabled: ".$DISABLED_ONLY_REGISTERED_PERSONS."
            ,text: '".ONLY_REGISTERED_PERSONS."'
            ,iconCls:'icon-user'
            ,scope:this
            ,disabled: false
            ,handler: function(){
                myGrid.store.baseParams = {
                    start:0
                    ,limit:100
                    ,cmd: 'jsonUnassignedStudentsSMS'
                    ,searchSMSServices: 1
                    ,objectId: '".$this->objectId."'
                    ,academicId: '".$academicId."'
                    ,isMobilphone: 1
                };
                myGrid.store.load();
            }
        }]);
    ");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add(['-',{
            id: 'ALL_PERSONS'
            ,disabled: ".$DISABLED_ALL_PERSONS."
            ,text: '".ALL_PERSONS."'
            ,iconCls:'icon-user'
            ,scope:this
            ,disabled: false
            ,handler: function(){
                myGrid.store.baseParams = {
                    start:0
                    ,limit:100
                    ,cmd: 'jsonUnassignedStudentsSMS'
                    ,objectId: '".$this->objectId."'
                    ,academicId: '".$academicId."'
                    ,isMobilphone: 1
                };
                myGrid.store.load();
            }
        }]);
    ");
    
    $OBJECT_GRID->isCheckboxSelect = true;
    $OBJECT_GRID->loadMask = true;
    $OBJECT_GRID->isQuickySearch = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    ?>
    
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'fit'
            ,border: false
            ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}]
        }]
    });
    
    var myGrid = <?=$OBJECT_GRID->ExtgetCmp();?>;
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>