<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 22.04.2011
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisSchoolTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("SMS");
$OBJECT_FORM->setLoadUrl('/sms/jsonload/');
$OBJECT_FORM->setSaveUrl('/sms/jsonsave/');

$OBJECT_GRID = new CamemisGrid("SMS", "SEARCH");
$OBJECT_GRID->setLoadUrl('/sms/jsonload/');
$OBJECT_GRID->setSaveUrl('sms/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addReadField("name: 'CODE'");
    $OBJECT_GRID->addReadField("name: 'USER'");
    $OBJECT_GRID->addReadField("name: 'LASTNAME'");
    $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
    $OBJECT_GRID->addReadField("name: 'SEND_DATE'");
    $OBJECT_GRID->addReadField("name: 'SEND_BY'");
    
    $OBJECT_GRID->addColumn("header: '<b>".CODE_ID."</b>', width: 100, sortable: true, dataIndex: 'CODE'");
    $OBJECT_GRID->addColumn("header: '<b>".STAFF."</b>', width: 240, sortable: true, dataIndex: 'USER'");
    $OBJECT_GRID->addColumn("header: '<b>".SENT_ON."</b>', width: 150, sortable: true, dataIndex: 'SEND_DATE'");
    $OBJECT_GRID->addColumn("header: '<b>".SENT_BY."</b>', width: 150, sortable: true, dataIndex: 'SEND_BY'");
    
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonListUserSMS'
        ,type: 'STAFF'
    ";
    $OBJECT_GRID->objectTitle = LOGBOOK;
    $OBJECT_GRID->loadMask = true;
    $OBJECT_GRID->isQuickySearch = false;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    
    ?>
    
    viewport = new Ext.Viewport({
        border: false
        ,layout: 'fit'
        ,items:[{
            border: false
            ,layout: 'fit'
            ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>