<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$READ_RIGHT = UserAuth::getACLValue("ACADEMIC_SETTING_READ_RIGHT")?"false":"true";

function setItem($name, $url, $read_right){
    $js = "title: '<b>" . $name . "</b>'";
    $js .= ",layout: 'fit'";
    $js .= ",disabled:".$read_right."";
    $js .= ",items: [new Ext.ux.IFrameComponent({ id: '".strtoupper($name)."', url: '".$url."'})]";
    return $js;
}

print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $ITEMS ="
        [{
            ".setItem(LIST_OF_TEACHERS,"/training/teacherlist/?objectId=".$this->objectId."", $READ_RIGHT)."
        },{
            ".setItem(TEACHER_SELECTION,"/training/teacherselection/?objectId=".$this->objectId."", $READ_RIGHT)."
        }]";
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'panel'
                ,layout: 'fit'
                ,border: false
                ,items:[{
                    xtype: 'vrtabpanel'
                    ,tabWidth: 170
                    ,border: false			
                    ,activeTab: 0
                    ,plain:true
                    ,width:170
                    ,defaults:{autoScroll: true, border: false}
                    ,items: <?=$ITEMS;?>      
                }]
            }]
        });
    });
</script>
<?
print$CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>