<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 13.03.2012
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisViewport.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTree("TRAINING", "LIST");
$OBJECT_TREE->setURL('/training/jsontree/');
$OBJECT_TREE->setSaveUrl('/training/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

Ext.onReady(function() {
	
    var tabs =  new Ext.TabPanel({
        autoTabs:true
        ,border:false
        ,tabPosition: 'top'
        ,enableTabScroll:true
        ,activeTab:0
        ,items:[{
            title: '&nbsp;'
            ,id: 'TAB_DEFAULT'
            ,layout: 'fit'
            /*,iconCls: 'icon-tabs'*/
            ,items: [{
                layout:'anchor'
                ,border:false
                ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                ,items:[{
                    title: ''
                    ,height:60
                    ,width:500
                    ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                    ,html:'<h1 class=\"header\"><?=PLEASE_MAKE_YOUR_SELECTIONS?></h1>'    
                }]
            }]
        }]
    });
    
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $CAMEMIS_PAGE_OBJECT->setAddTab();
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    $OBJECT_TREE->isTreeExpand = true;
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse(false));
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand(false));
    
    $OBJECT_TREE->setBaseParams("
    	cmd: 'jsonTreeTeacherTrainings'
    ");
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        border: false
        ,layout:'fit'
        ,items:[{
            layout:'border'
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,border: false
            ,items: [{
                title: '&nbsp;'
                ,region:'west'
                ,id: 'WEST_ID'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width: 280
                ,minSize: 280
                ,maxSize: 280
                ,layout: 'fit'
                ,items: [{xtype: '<?=$OBJECT_TREE->getObjectXType();?>'}]
            },{
                title: ''
                ,collapsible: false
                ,region:'center'
                ,margins: '3 3 3 0'
                ,id: 'center'
                ,layout:'card'
                ,activeItem: 0
                ,items: tabs
            }]
        }]
    });
    var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node, e){
        if(node.isLeaf()){
            addTab(node.id,node.attributes.classname+'&raquo; '+node.text,'<?=$this->URL_STUDENT_SUBJECT_ASSIGNMENT;?>subjectId=' + node.attributes.subjectId + '&objectId=' + node.attributes.objectId);
        }else{
            switch(node.attributes.objectType){
                case "CLASS":
                    addTab(node.id,node.text,'/staff/classdetails/?target=training&trainingId=' + node.id);
                    //addTab(node.id,node.text,'<?=$this->URL_SCHEDULE;?>trainingId=' + node.id);
                break;
            }
        }
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>