<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$classObject = AcademicDBAccess::findGradeFromId($this->academicId);

if(!$classObject) {header("Location: /main/permission/");exit;}

$schoolyearObject = AcademicDateDBAccess::findAcademicDateFromId($classObject->SCHOOL_YEAR);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    
    Ext.onReady(function() {
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                title:'<?=$classObject->NAME;?> (<?=$schoolyearObject->NAME;?>)'
                ,bodyStyle: 'padding:5px'
                ,layout:'fit'
                ,items:[{
                    xtype: 'tabpanel'
                    ,border:true
                    ,plain:true
                    //,tabPosition: 'bottom'
                    ,activeTab: 0
                    ,items:[{
                        title: '<?=LIST_OF_STUDENTS?>'
                        /*,iconCls: 'icon-tabs'*/
                        ,layout:'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'LIST_OF_STUDENTS', url: '/academic/studentlist?objectId=<?=$classObject->ID;?>&gradeId=<?=$classObject->GRADE_ID;?>&schoolyearId=<?=$classObject->SCHOOL_YEAR;?>'})]
                    },{
                        title: '<?=SCHEDULE?>'
                        /*,iconCls: 'icon-tabs'*/
                        ,layout:'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'SCHEDULE', url:'/schedule/byclass/?target=general&academicId=<?=$classObject->ID;?>&gradeId=<?=$classObject->GRADE_ID;?>&schoolyearId=<?=$classObject->SCHOOL_YEAR;?>'})]
                    },{
                        title: '<?=LIST_OF_ATTENDANCE?>'
                        /*,iconCls: 'icon-tabs'*/
                        ,layout:'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'LIST_OF_ATTENDANCE', url: '/attendance/byclass/?target=general&academicId=<?=$classObject->ID;?>&gradeId=<?=$classObject->GRADE_ID;?>&schoolyearId=<?=$classObject->SCHOOL_YEAR;?>&teacherId=<?=$this->objectId;?>'})]
                    },{
                        title: '<?=LIST_BY_DISCIPLINE?>'
                        /*,iconCls: 'icon-tabs'*/
                        ,layout:'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'LIST_BY_DISCIPLINE', url: '/discipline/byclass/?target=general&academicId=<?=$classObject->ID;?>&gradeId=<?=$classObject->GRADE_ID;?>&schoolyearId=<?=$classObject->SCHOOL_YEAR;?>&teacherId=<?=$this->objectId;?>'})]
                    },{
                        title: '<?=LIST_OF_TEACHERS?>'
                        /*,iconCls: 'icon-tabs'*/
                        ,layout:'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'LIST_OF_TEACHERS', url: '/academic/teachersbyclass/?objectId=<?=$classObject->ID;?>&gradeId=<?=$classObject->GRADE_ID;?>&schoolyearId=<?=$classObject->SCHOOL_YEAR;?>&teacherId=<?=$this->objectId;?>'})]
                    },{
                        title: '<?=EVENTS?>'
                        /*,iconCls: 'icon-tabs'*/
                        ,layout:'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'EVENTS', url: '/schoolevent/classevents/?target=general&academicId=<?=$classObject->ID;?>&gradeId=<?=$classObject->GRADE_ID;?>&schoolyearId=<?=$classObject->SCHOOL_YEAR;?>&teacherId=<?=$this->objectId;?>'})]
                    },{
                        title: '<?=SUBJECT_LIST?>'
                        /*,iconCls: 'icon-tabs'*/
                        ,layout:'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'SUBJECT_LIST', url: '/subject/byclass/?target=general&academicId=<?=$classObject->ID;?>&gradeId=<?=$classObject->GRADE_ID;?>&schoolyearId=<?=$classObject->SCHOOL_YEAR;?>&teacherId=<?=$this->objectId;?>'})]
                    },{
                        title: '<?=ACADEMIC_PERFORMANCES?>'
                        /*,iconCls: 'icon-tabs'*/
                        ,layout:'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'ACADEMIC_PERFORMANCES', url: ''})]
                    }]
                }]
                
            }]
        });      
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>