<?
require_once 'clients/app_admin/AdminPage.php';
require_once 'clients/app_admin/AdminForm.php';
require_once 'clients/app_admin/AdminGrid.php';
require_once 'clients/app_admin/AdminField.php';
require_once 'clients/app_admin/AdminBar.php';
require_once 'clients/app_admin/AdminPage.php';

$OBJECT_ADMIN_PAGE = AdminPage::getInstance();
$OBJECT_ADMIN_PAGE->setLoadingMask = true;
print $OBJECT_ADMIN_PAGE->showCamemisHeader();

$OBJECT_GRID = new AdminGrid("MAIN", "LOCALIZATIONS");

$language = isset($_GET["language"])?addText($_GET["language"]):"ENGLISH";
$languageName = isset($_GET["languageName"])?$_GET["languageName"]:"English";

?>
<div id="iniContent" class="x-hidden" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="header">Please make your selection...</h1>
</div>
<script>
var chooseConst;
Ext.onReady(function() {

    Ext.QuickTips.init();
    
    function fiterLocalization(language, status){
        Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>').store.baseParams = {
            start:0
            ,limit:100
            ,cmd: 'jsonAllLocalizations'
            ,show_all: 'false'
            ,language: language
            ,not_translated: status
        };
        Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>').store.load();
    }
        
    function showText(v, p, record, rowIndex){
        return String.format('<div style=\"font-weight:normal;white-space:normal;padding:5px;\">{0}</div>'
            ,v
        );
    }
    <?
    $OBJECT_GRID->addReadField("name: 'ID'");
    $OBJECT_GRID->addReadField("name: 'CONST'");
    $OBJECT_GRID->addReadField("name: 'ENGLISH'");
    $OBJECT_GRID->addReadField("name: 'CHOOSE_LANGUAGE'");
    if($language=="ENGLISH")
    $OBJECT_GRID->addColumn("header: 'Const', renderer: showText, align:'left', width: 250, sortable: true, dataIndex: 'CONST'");
    
    if($language!="ENGLISH")
    $OBJECT_GRID->addColumn("header: '".$languageName."', renderer: showText, align:'left', width: 300, sortable: false,dataIndex: 'CHOOSE_LANGUAGE'");

    $OBJECT_GRID->addColumn("header: 'English', renderer: showText, align:'left', width: 300, sortable: false,dataIndex: 'ENGLISH'");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonAllLocalizations'
        ,language: '".$language."'
    ";
    if($language == "ENGLISH")
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'ADD_LOCALIZATION'
            ,text: '<b>Add new Localization</b>'
            ,iconCls:'icon-application_form_add'
            ,scope:this
            ,handler: function(){
                Ext.getCmp('center').getLayout().setActiveItem(1);
                Ext.getCmp('SINGLE_SAVE_ID').show();
                Ext.getCmp('MY_FORM').show();
                Ext.getCmp('CONST').setValue('');
                Ext.getCmp('ENGLISH_ID').setValue('');
                Ext.getCmp('CHOOSE_LANGUAGE_ID').setValue('');
                Ext.getCmp('FORM_ENGLISH_LANGUAGE').hide();
            }
        }]);
    ");
    
    if($language != "ENGLISH"){
        $OBJECT_GRID->addTBarItems("
            tbar.add([{
                id: 'NOT_TRANSLATED'
                ,text: '<b>Not translated</b>'
                /*,iconCls: 'icon-tabs'*/
                ,scope:this
                ,handler: function(){
                    fiterLocalization('".$language."',1);
                }
            }]);
        ");
        
        $OBJECT_GRID->addTBarItems("
            tbar.add([{
                id: 'SHOW_ALL'
                ,text: '<b>Show All</b>'
                /*,iconCls: 'icon-tabs'*/
                ,scope:this
                ,handler: function(){
                    fiterLocalization('".$language."',0);
                }
            }]);
        ");
    }
    $OBJECT_GRID->setURL('/main/jsonload/');
    $OBJECT_GRID->isQuickySearch = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    $OBJECT_GRID->renderJS();

    $OBJECT_FORM = new AdminForm("MAIN");
    $OBJECT_FORM->setURL("/main/");
    $OBJECT_FORM->setonEmbeddedEvents("
        if (Ext.getCmp('".$OBJECT_GRID->getObjectId()."')) Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
    ");
    
    $FORM_ITEMS = "
    {
        title: 'System information'
        ,autoHeight: true
        ,id: 'MY_FORM'
        ,width: 550
        ,hidden: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFFFFF;padding:10px; color:#000000;font-weight: bold;'
            ,items: [
                {".AdminField::Textfield("CONST", "CONST", 'Const', true, false)."}
            ]
        },{
            layout: 'form'
            ,id: 'FORM_ENGLISH_LANGUAGE'
            ,border: false
            ,hidden: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFFFFF;padding:10px; color:#000000;font-weight: bold;'
            ,items: [
                {".AdminField::Textarea("ENGLISH", "Default Language", 120, true, false, false)."}
            ]
        },{
            layout: 'form'
            ,id: 'FORM_CHOOSE_LANGUAGE'
            ,border: false
            ,hidden: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFFFFF;padding:10px; color:#000000;font-weight: bold;'
            ,items: [
                {".AdminField::Textarea("CHOOSE_LANGUAGE", "Choose Language", 120, false, false)."}
            ]
        }]
    }
    ";
    
    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: ".$FORM_ITEMS."
    ";
    $OBJECT_FORM->addObjectItems($items);
    
    if($language=="ENGLISH")
    $OBJECT_FORM->addTBarItems("
        text: 'Remove'
        ,id: 'SINGLE_REMOVE_ID'
        ,formBind:true
        ,iconCls:'icon-delete'
        ,scope:this
        ,tooltip:'Remove'
        ,hidden: true
        ,handler:this.onSetObjectRemove
    ");
        
    $OBJECT_FORM->addTBarItems("
        text: 'Save'
        ,id: 'SINGLE_SAVE_ID'
        ,formBind:true
        ,iconCls:'icon-disk'
        ,scope:this
        ,tooltip:'Save'
        ,hidden: true
        ,handler:this.onSubmit
    ");
    
    if($language == "ENGLISH")
    $OBJECT_FORM->setRemoveParams("
        cmd: 'jsonDeleteLocalization'
        ,CONST: chooseConst
        ,language: '".$language."'
    ");
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'jsonActionLocalization'
        ,language: '".$language."'
    ");
    
    $OBJECT_FORM->setonEmbeddedEvents("
        Ext.getCmp('center').getLayout().setActiveItem(0);
        if (Ext.getCmp('".$OBJECT_GRID->getObjectId()."')) Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
    ");
    
    $OBJECT_FORM->setOnEmbeddedRemoveEvents("
        Ext.getCmp('center').getLayout().setActiveItem(0);
        if (Ext.getCmp('".$OBJECT_GRID->getObjectId()."')) Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
    ");
    
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 100;
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->renderJS();
    ?>
          
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: false
                ,split: true
            }
            ,items: [{
               	region:'west'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width: percentWidth(50)
                ,minSize: percentWidth(50)
                ,maxSize: percentWidth(50)
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype()?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,contentEl: 'iniContent'
                },{
                    layout: 'fit'
                    ,border: false 
                    ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype()?>'}]
                }]
            }]
        }]
    });
    
    var myGrid = Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>');
    if (myGrid) myGrid.on('rowclick', function(grid, rowIndex, e){
        Ext.getCmp('center').getLayout().setActiveItem(1);
        var rec = grid.store.getAt(rowIndex);
        chooseConst = rec.data.CONST;
        if (Ext.getCmp('SINGLE_SAVE_ID')) Ext.getCmp('SINGLE_SAVE_ID').show();
        if (Ext.getCmp('SINGLE_REMOVE_ID')) Ext.getCmp('SINGLE_REMOVE_ID').show();
        Ext.getCmp('MY_FORM').show();
        Ext.getCmp('CONST').setValue(rec.data.CONST);
        Ext.getCmp('ENGLISH_ID').setValue(rec.data.ENGLISH);
        Ext.getCmp('CHOOSE_LANGUAGE_ID').setValue(rec.data.CHOOSE_LANGUAGE);
    });
});
</script>
<?
print $OBJECT_ADMIN_PAGE->showCamemisFooter();
?>