<?
///////////////////////////////////////////////////////////
// @Sor Veasna
// Date: 24.07.2014
///////////////////////////////////////////////////////////

require_once 'clients/CamemisChart.php';
require_once 'clients/CamemisPage.php';
require_once 'models/filter/FilterData.php';
require_once 'models/filter/FilterDataSet.php';
require_once setUserLoacalization();
$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";
$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
$gradeId = "";
$campusId = "";
$schoolyearId = "";
$classId = "";

if (strpos($objectId, "CAMPUS_") !== false) {
    $Ids = explode("_",substr($objectId, 7));
    $campusId = isset($Ids[0])?$Ids[0]:"";
    $schoolyearId = isset($Ids[1])?$Ids[1]:"";
    $objectType = "CAMPUS";
} elseif (strpos($objectId, "GRADE_") !== false) {
    $objectType = "GRADE";
    $Ids = explode("_",substr($objectId, 6));
    $gradeId = isset($Ids[0])?$Ids[0]:"";
    $campusId = isset($Ids[1])?$Ids[1]:"";
    $schoolyearId = isset($Ids[2])?$Ids[2]:"";
} else{
    $objectType = "CLASS";
    $classId = $objectId;
}
$setParams="";

$objectDataSet = new FilterDataSet();
if($campusId){
    $objectDataSet->campusId = $campusId;
    $setParams .= "&campusId=".$campusId.""; 
}
if($gradeId){
    $objectDataSet->gradeId = $gradeId;
    $setParams .= "&gradeId=".$gradeId.""; 
}
if($schoolyearId){
    $objectDataSet->schoolyearId = $schoolyearId;
    $setParams .= "&schoolyearId=".$schoolyearId.""; 
}
if($classId){
    $objectDataSet->classId = $classId;
    $setParams .= "&classId=".$classId.""; 
}
if($objectType)
$objectDataSet->objectType = $objectType;

if($this->personType){
$objectDataSet->personType=$this->personType;    
}

$objectDataSet->type='DAILY';
$dataSetAbsenceDaily = $objectDataSet->getDataSetAbsenceType();

$chartAbsenceDaily = new CamemisChart("DISCRETE_BAR_CHART", 'chartAbsenceDailly', $dataSetAbsenceDaily);
$chartAbsenceDaily->chartSVG = "displayAbsenceDailly";
$chartAbsenceDaily->showLegend='true';
$chartAbsenceDaily->tooltips = 'true';
$chartAbsenceDaily->showValues ='true';
$chartAbsenceDaily->height = 280;

$objectDataSet->type='BLOCK';
$dataSetAbsenceBlock = $objectDataSet->getDataSetAbsenceType(); 

$chartAbsenceBlock = new CamemisChart("DISCRETE_BAR_CHART", 'chartAbsenceBlock', $dataSetAbsenceBlock);
$chartAbsenceBlock->chartSVG = "displayAbsenceBlock";
$chartAbsenceBlock->showLegend='true';
$chartAbsenceBlock->tooltips = 'true';
$chartAbsenceBlock->showValues ='true';
$chartAbsenceBlock->height = 280;

?>

<link href="http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer" rel="stylesheet" type="text/css">
<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">
<link href="/public/bootstrap/css/bootstrap.css" rel="stylesheet">
<link href="/public/bootstrap/css/custom.css" rel="stylesheet">
<script src="/public/nvd3/nvd3-camemis.php"></script>
    <div id="initStatistic" class="container-fluid" style="background-color:#f9f9f9;">
    
         <div class="row">
            <div class="col-md-12">
                <div class="panel-heading"><h5><b>Daily Attendance</b></h5></div>
                
                <div class="panel-body">
                    <button type="button" id="btnStudentEDMajor" class="btn btn-info"><span class="glyphicon glyphicon-search"></span>View Details</button>
                    <?= $chartAbsenceDaily->setChartDisplay(); ?>
                    <script><?= $chartAbsenceDaily->setChartScript(); ?></script> 
                </div>     
            </div>  
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <div class="panel-heading"><h5><b>Block Attendance</b></h5></div>
                
                <div class="panel-body">
                    <button type="button" id="btnStudentEDMajor" class="btn btn-info"><span class="glyphicon glyphicon-search"></span>View Details</button>
                    <?= $chartAbsenceBlock->setChartDisplay(); ?>
                    <script><?= $chartAbsenceBlock->setChartScript(); ?></script> 
                </div>     
            </div>  
        </div>
        
    </div>
    <script>
        Ext.onReady(function() {
            
            viewport = new Ext.Viewport({
                layout: 'fit'
                ,border: false
                ,items:[{
                    layout: 'card'
                    ,id:'content'
                    ,activeItem: 0
                    ,border: false
                    ,items:[{
                        border: false
                        ,bodyStyle: 'background:#dee7f6;'
                        ,autoScroll:true
                        ,contentEl: 'initStatistic'
                    }]
                }]
            });
            
           /*Ext.get('btnStudentEDMajor').on('click', function(){
               window.parent.openWinMax('', '/student/search/?camIds=<?=$this->urlEncryp->encryptedGet($setParams);?>');
           });*/
          
           
        });
    </script>
</body>
</html>
