<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";

$gradeId = "";
$campusId = "";
$schoolyearId = "";
$classId = "";

if (strpos($objectId, "CAMPUS_") !== false) {
    $Ids = explode("_",substr($objectId, 7));
    $campusId = isset($Ids[0])?$Ids[0]:"";
    $schoolyearId = isset($Ids[1])?$Ids[1]:"";
    $objectType = "CAMPUS";
} elseif (strpos($objectId, "GRADE_") !== false) {
    $objectType = "GRADE";
    $Ids = explode("_",substr($objectId, 6));
    $gradeId = isset($Ids[0])?$Ids[0]:"";
    $campusId = isset($Ids[1])?$Ids[1]:"";
    $schoolyearId = isset($Ids[2])?$Ids[2]:"";
} else{
    $classId = $objectId;
}

$OBJECT_GRID = new CamemisGrid("STUDENT_ATTENDANCE", "FILTER_".$objectType."");
$OBJECT_GRID->setLoadUrl('/attendance/jsonload');
$OBJECT_GRID->setSaveUrl('/attendance/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$columndata = Utiles::getGridColumnData("STUDENT_ATTENDANCE_FILTER_".$objectType."_ID");

?>
<style>
    .filter-row-grid .x-grid3-header {
    background: #f9f9f9 url(/public/images/filter-row-hrow.gif) repeat-x left top;
}

.filter-row-grid .filter-row-header {
    height: 26px;
}

tr.filter-row-header .filter-row-icon input {
    background-image: url(/public/images/filter-row-icon.png);
    background-repeat: no-repeat;
    padding-left: 16px;
}
</style>
<script>
Ext.onReady(function() {
    <?
    /**
     * Extjs: s.gif
     */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addCellRenderer("
        function renderTextBold(v, p, record, rowIndex){
            var str = '<span style=\"font-weight:bold;color:#061f83;white-space:normal;\">' + v + '</span>';
            return str;
        }
    ");
    
    $OBJECT_GRID->addCellRenderer("
        function renderText(v, p, record, rowIndex){
            var str = '<span style=\"font-weight:normal;color:#555;white-space:normal;\">' + v + '</span>';
            return str;
        }
    ");

    $OBJECT_GRID->addReadField("name: 'STUDENT', type: 'string'");
    $OBJECT_GRID->addReadField("name: 'CODE'");
    $OBJECT_GRID->addReadField("name: 'STUDENT_ID'");
    $OBJECT_GRID->addReadField("name: 'ABSENT_TYPE'");
    $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
    $OBJECT_GRID->addReadField("name: 'LASTNAME'");
    $OBJECT_GRID->addReadField("name: 'GENDER_NAME'");
    $OBJECT_GRID->addReadField("name: 'START_DATE'");
    $OBJECT_GRID->addReadField("name: 'END_DATE'");
    $OBJECT_GRID->addReadField("name: 'COUNT_DATE'");
    $OBJECT_GRID->addReadField("name: 'TRAINING_TERM'");
    $OBJECT_GRID->addReadField("name: 'CLASS_NAME'");
    $OBJECT_GRID->addReadField("name: 'SCHOOLYEAR_NAME'");
    $OBJECT_GRID->addReadField("name: 'STATUS'");
    $OBJECT_GRID->addReadField("name: 'STATUS_KEY'");
    $OBJECT_GRID->addReadField("name: 'TRAINING_NAME'");
    $OBJECT_GRID->addReadField("name: 'TRAINING_LEVEL'");
    $OBJECT_GRID->addReadField("name: 'DESCRIPTION'");
    $OBJECT_GRID->addReadField("name: 'SUBJECT_NAME'");
    ////////////////////////////////////
    $OBJECT_GRID->addColumn("header: '<b>".FULL_NAME."</b>', width: 160, hidden:".checkColHidden(1, $columndata).", renderer: renderTextBold, sortable: true, dataIndex: 'STUDENT', filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".TYPE."</b>', width: 130, hidden:".checkColHidden(2, $columndata).", renderer: renderText, sortable: true, dataIndex: 'ABSENT_TYPE', filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".FROM_DATE."</b>', align:'center', width: 120, hidden:".checkColHidden(3, $columndata).", renderer: renderText, sortable: true, dataIndex: 'START_DATE', filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".TO_DATE."</b>', align:'center', width: 120, hidden:".checkColHidden(4, $columndata).", renderer: renderText, sortable: true, dataIndex: 'END_DATE', filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".DAYS."</b>' , align:'center', hidden:".checkColHidden(5, $columndata).", width: 60, renderer: renderText, sortable: true, dataIndex: 'COUNT_DATE', filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".SUBJECT."</b>', width: 150, hidden:".checkColHidden(6, $columndata).", sortable: true, dataIndex: 'SUBJECT_NAME', filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".DESCRIPTION."</b>', width: 150, hidden:".checkColHidden(7, $columndata).", sortable: true, dataIndex: 'DESCRIPTION', filter:{}");
    $OBJECT_GRID->addColumn("header: '<b>".CURRENT_SCHOOL_YEAR."</b>', width: 160, hidden:".checkColHidden(8, $columndata).", renderer: renderText, sortable: true, dataIndex: 'SCHOOLYEAR_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".CURRENT_CLASS."</b>', width: 150, hidden:".checkColHidden(9, $columndata).", renderer: renderText, sortable: true, dataIndex: 'CLASS_NAME', filter:{}");


    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonSearchStudentAttendance'
        ,campusId: '".$campusId."'
        ,schoolyearId: '".$schoolyearId."'
        ,gradeId: '".$gradeId."'
        ,classId: '".$classId."'
    ";
    ////////////////////////////////////////////////////////////////////////////
    if(UserAuth::getACLValue("STUDENT_SEARCH_EXECUTE_RIGHT")){
        $OBJECT_GRID->addTBarItems("
            tbar.add([{
                text: '" . EXPORT_TO_EXCEL . "'
                ,disabled:true
                ,id: 'EXPORT_TO_EXCEL'
                ,iconCls:'icon-page_excel'
                ,handler: function(){
                    Ext.MessageBox.show({
                        msg: '".SAVING_YOUR_DATA_PLEASE_WAIT."',
                        progressText: 'Saving...',
                        width:300,
                        wait:true,
                        waitConfig: {interval:200},
                        icon:'ext-mb-download'
                    });
                    Ext.Ajax.request({
                        url: '/export/jsonexcel/'
                        ,method: 'POST'
                        ,timeout: 600000
                        ,params:{cmd: 'studentSearch'
                                ,objectId:'".$OBJECT_GRID->getObjectId()."'
                                }
                        ,success: function(response, options) {
                            Ext.MessageBox.hide();
                            window.location='/export/openstudentlist/'
                        }
                    });
                }
            }]);
        ");
    }
    
    
    $OBJECT_GRID->addTBarItems("tbar.add('->');");
    $OBJECT_GRID->isQuickySearch = true;
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    //$OBJECT_GRID->isGroupingView = true;
    $OBJECT_GRID->isFilterRow = true;
    //$OBJECT_GRID->groupField = "STUDENT";
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->setUserColumn = true;
    $OBJECT_GRID->loadMask = true;
    $OBJECT_GRID->renderJS();
    
    
    $params = "";
    $params .= "objectType=".$objectType."";
    $params .= "&campusId=".$campusId."";
    $params .= "&gradeId=".$gradeId."";
    $params .= "&schoolyearId=".$schoolyearId."";
    if($gradeId)
    $params .= "&academicId=".$gradeId."";
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{
               	region:'north'
                ,id:'NORTH_ID'
                ,margins: '3 3 0 3'
                ,cmargins: '3 3 3 3'
                ,autoScroll: true
                ,height:300
                ,minSize:300
                ,maxSize:300
                ,layout: 'fit'
                ,items: [new Ext.ux.IFrameComponent({ id: 'TRADITIONAL_EDUCATION_SYSTEM', url:'/chart/studentattendance/?camIds=<?=$this->urlEncryp->encryptedGet($params)?>'})]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '0 3 3 3'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType()?>'}]
            }]
        }]
    });
    Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>