<?
///////////////////////////////////////////////////////////
// @Sor Veasna
// Date: 17.05.2014
///////////////////////////////////////////////////////////

require_once 'clients/CamemisChart.php';
require_once 'clients/CamemisPage.php';
require_once 'models/statistic/StudentStatisticsDBAccess.php';
require_once 'models/filter/FilterData.php';
require_once 'models/filter/FilterStudentDataSet.php';
require_once setUserLoacalization();
$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";
$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
$gradeId = "";
$campusId = "";
$schoolyearId = "";
$classId = "";

if (strpos($objectId, "CAMPUS_") !== false) {
    $Ids = explode("_",substr($objectId, 7));
    $campusId = isset($Ids[0])?$Ids[0]:"";
    $schoolyearId = isset($Ids[1])?$Ids[1]:"";
    $objectType = "CAMPUS";
} elseif (strpos($objectId, "GRADE_") !== false) {
    $objectType = "GRADE";
    $Ids = explode("_",substr($objectId, 6));
    $gradeId = isset($Ids[0])?$Ids[0]:"";
    $campusId = isset($Ids[1])?$Ids[1]:"";
    $schoolyearId = isset($Ids[2])?$Ids[2]:"";
} else{
    $objectType = "CLASS";
    $classId = $objectId;
}
$setParams="";

$objectDataSet = new FilterStudentDataSet();
if($campusId){
    $objectDataSet->campusId = $campusId;
    $setParams .= "&campusId=".$campusId.""; 
}
if($gradeId){
    $objectDataSet->gradeId = $gradeId;
    $setParams .= "&gradeId=".$gradeId.""; 
}
if($schoolyearId){
    $objectDataSet->schoolyearId = $schoolyearId;
    $setParams .= "&schoolyearId=".$schoolyearId.""; 
}
if($classId){
    $objectDataSet->classId = $classId;
    $setParams .= "&classId=".$classId.""; 
}
if($objectType)
$objectDataSet->objectType = $objectType;

$dataSetMaleFemale=$objectDataSet->getDataSetStudentMaleFemale();
$chartMaleFemale = new CamemisChart("DONUT_CHART", 'chartMaleFemale', $dataSetMaleFemale);
$chartMaleFemale->chartSVG = "displayMaleFemale";
$chartMaleFemale->showLegend='true';
$chartMaleFemale->width = 280;
$chartMaleFemale->height = 280;

$datasetStatusAcount = $objectDataSet->getDataSetStudentActiveAndDeactive();
$chartStatusAcount = new CamemisChart("DONUT_CHART", 'chartStatusAcount', $datasetStatusAcount);
$chartStatusAcount->chartSVG = "displayStatusAcount";
$chartStatusAcount->showLegend='true';
$chartStatusAcount->width = 300;
$chartStatusAcount->height = 300;

$datasetAge=$objectDataSet->getDataSetStudentAge();
$chartAge = new CamemisChart("DISCRETE_BAR_CHART", 'chartAge', $datasetAge);
$chartAge->chartSVG = "displayAge";
$chartAge->showLegend='true';
$chartAge->tooltips = 'true';
$chartAge->showValues ='true';
$chartAge->height = 280;

$dataSetNationality = $objectDataSet->getDataSetNationality(); 
$chartNationality = new CamemisChart("DISCRETE_BAR_CHART", 'chartNationality', $dataSetNationality);
$chartNationality->chartSVG = "displayNationality";
$chartNationality->showLegend='true';
$chartNationality->tooltips = 'true';
$chartNationality->showValues ='true';
$chartNationality->height = 280;

$datasetReligion=$objectDataSet->getDataSetReligion();
$chartReligion = new CamemisChart("DONUT_CHART", 'chartReligion', $datasetReligion);
$chartReligion->showLegend = 'false';
$chartReligion->chartSVG = "displayReligion";
$chartReligion->showLegend='true';
$chartReligion->width = 300;
$chartReligion->height = 350;

$datasetSMS = $objectDataSet->getDataSetSMS();
$chartSMS = new CamemisChart("PIC_CHART", 'chartSMS', $datasetSMS);
$chartSMS->chartSVG = "displaySMS";
$chartSMS->showLegend='true';
$chartSMS->width = 300;
$chartSMS->height = 300;

$datasetCity=$objectDataSet->getDataSetCountryProvince(); 
$chartCity = new CamemisChart("DISCRETE_BAR_CHART", 'chartCity', $datasetCity);
$chartCity->chartSVG = "displayCity";
$chartCity->showControls=true;
$chartCity->showXAxis="false";
$chartCity->tooltips=true;
$chartCity->height = 280;

$datasetEthnic = $objectDataSet->getDataSetEthnicity();
$chartEthnic = new CamemisChart("DISCRETE_BAR_CHART", 'chartEthnic', $datasetEthnic);
$chartEthnic->showControls = 'true';
$chartEthnic->tooltips='true';
$chartEthnic->chartSVG = "displayEthnic";
$chartEthnic->showValues="true";
$chartEthnic->height = 350;
?>

<link href="http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer" rel="stylesheet" type="text/css">
<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">
<link href="/public/bootstrap/css/bootstrap.css" rel="stylesheet">
<link href="/public/bootstrap/css/custom.css" rel="stylesheet">
<script src="/public/nvd3/nvd3-camemis.php"></script>
    <div id="initStatistic" class="container-fluid" style="background-color:#f9f9f9;">
    
        <div class="row" style="background-color: #C2C2C2;">
            <div class="col-md-4">
                <div class="panel-heading"><h4><?=GENDER;?></h4></div>
                <div class="panel-body">
                    <button type="button" id="btnStudentGender"  class="btn btn-info">View Details</button>
                    <?= $chartMaleFemale->setChartDisplay(); ?>
                    <script><?= $chartMaleFemale->setChartScript(); ?></script>       
                </div>
                </div>
            <div class="col-md-8">
                 
                 <div class="panel-heading"><h4><?=AGE;?></h4></div>
                <div class="panel-body">
                    <button type="button" id="btnStudentAge" class="btn btn-info">View Details</button>
                    <?= $chartAge->setChartDisplay(); ?>
                    <script><?= $chartAge->setChartScript(); ?></script>    
                </div>    
           
            </div>
        </div>
        
        <div class="row" style="background-color: #DDD;">
            <div class="col-md-6">
                <div class="panel-heading"><h4>SMS</h4></div>          
                <div class="panel-body">
                    <button type="button" id="btnStudentSMS" class="btn btn-info">View Details</button>
                    <?= $chartSMS->setChartDisplay(); ?>
                    <script><?= $chartSMS->setChartScript(); ?></script> 
                </div>
            </div>
            
            <div class="col-md-6">
                
                <div class="panel-heading"><h4>Status Acount</h4></div>
                <div class="panel-body">
                    <button type="button" id="btnStudentAcountStatus" class="btn btn-info">View Details</button>
                    <?= $chartStatusAcount->setChartDisplay(); ?>
                    <script><?= $chartStatusAcount->setChartScript(); ?></script> 
                </div>
            
            </div>
        </div>   
        <div class="row" style="background-color: #EEE;">
            <div class="col-md-4">
                <div class="panel-heading"><h4><?=RELIGION;?></h4></div>
                <div class="panel-body">
                    <button type="button" id="btnStudentReligion" class="btn btn-info">View Details</button>
                    <?= $chartReligion->setChartDisplay(); ?>
                    <script><?= $chartReligion->setChartScript(); ?></script>    
                </div>     
               
            </div>    
            <div class="col-md-8">
                
                <div class="panel-heading"><h4><?=ETHNICITY;?></h4></div>
                <div class="panel-body">
                    <button type="button" id="btnStudentEthnicity" class="btn btn-info">View Details</button>
                    <?= $chartEthnic->setChartDisplay(); ?>
                    <script><?= $chartEthnic->setChartScript(); ?></script>    
                </div>  
            </div>
            
        </div>
        
         <div class="row" style="background-color: #E1E1E1;">
            <div class="col-md-12">
                <div class="panel-heading"><h4><?=NATIONALITY?></h4></div>
                
                <div class="panel-body">
                    <button type="button" id="btnStudentNationality" class="btn btn-info">View Details</button>
                    <?= $chartNationality->setChartDisplay(); ?>
                    <script><?= $chartNationality->setChartScript(); ?></script> 
                </div>     
            </div>  
        </div>
        
        <div class="row" style="background-color: #ECECEC;">
            <div class="col-md-12">
                <div class="panel-heading"><h4><?=CITY_PROVINCE?></h4></div>
                <div class="panel-body">
                    <button type="button" id="btnStudentEthnicity" class="btn btn-info">View Details</button>
                    <?= $chartCity->setChartDisplay(); ?>
                    <script><?= $chartCity->setChartScript(); ?></script> 
                </div> 
            </div>
        </div>
            
    </div>
    <script>
        Ext.onReady(function() {
            
            /*viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                title: ''
                ,id:'westcenter'
                ,collapsible: false
                ,region:'center'
                ,layout: 'fit'
                ,margins: '0 3 3 3'
                ,border:false
                ,bodyStyle: 'background:#dee7f6;'
                ,items: [{
                    border: false
                    ,bodyStyle: 'background:#dee7f6;'
                    ,autoScroll:true
                    ,contentEl: 'initStatistic'
                }]
            }]
        });*/
            
            Ext.get('btnStudentGender').on('click', function(){
               window.parent.openWinMax('', '/student/search/?camIds=<?=$this->urlEncryp->encryptedGet($setParams);?>');
            });
            
           Ext.get('btnStudentAge').on('click', function(){
               alert('fdsfdsf');
           });
           
        });
    </script>
</body>
</html>
