<?
///////////////////////////////////////////////////////////
// @Sor Veasna
// Date: 24.07.2014
///////////////////////////////////////////////////////////

require_once 'clients/CamemisChart.php';
require_once 'clients/CamemisPage.php';
require_once 'models/filter/FilterData.php';
require_once 'models/filter/FilterDataSet.php';
require_once setUserLoacalization();
$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";
$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
$gradeId = "";
$campusId = "";
$schoolyearId = "";
$classId = "";

if (strpos($objectId, "CAMPUS_") !== false) {
    $Ids = explode("_",substr($objectId, 7));
    $campusId = isset($Ids[0])?$Ids[0]:"";
    $schoolyearId = isset($Ids[1])?$Ids[1]:"";
    $objectType = "CAMPUS";
} elseif (strpos($objectId, "GRADE_") !== false) {
    $objectType = "GRADE";
    $Ids = explode("_",substr($objectId, 6));
    $gradeId = isset($Ids[0])?$Ids[0]:"";
    $campusId = isset($Ids[1])?$Ids[1]:"";
    $schoolyearId = isset($Ids[2])?$Ids[2]:"";
} else{
    $objectType = "CLASS";
    $classId = $objectId;
}
$setParams="";

$objectDataSet = new FilterDataSet();
if($campusId){
    $objectDataSet->campusId = $campusId;
    $setParams .= "&campusId=".$campusId.""; 
}
if($gradeId){
    $objectDataSet->gradeId = $gradeId;
    $setParams .= "&gradeId=".$gradeId.""; 
}
if($schoolyearId){
    $objectDataSet->schoolyearId = $schoolyearId;
    $setParams .= "&schoolyearId=".$schoolyearId.""; 
}
if($classId){
    $objectDataSet->classId = $classId;
    $setParams .= "&classId=".$classId.""; 
}
if($objectType)
$objectDataSet->objectType = $objectType;

$dataSetNationality = $objectDataSet->getDataSetStudentEDMajor(); 

//print($dataSetNationality);exit;
$chartStudentEDMajor = new CamemisChart("DISCRETE_BAR_CHART", 'chartStudentEDMajor', $dataSetNationality);
$chartStudentEDMajor->chartSVG = "displayMajor";
$chartStudentEDMajor->showLegend='true';
$chartStudentEDMajor->tooltips = 'true';
$chartStudentEDMajor->showValues ='true';
$chartStudentEDMajor->height = 280;

$datasetCity=$objectDataSet->getDataSetStudentEDDegree(); 
$chartCity = new CamemisChart("DISCRETE_BAR_CHART", 'chartCity', $datasetCity);
$chartCity->chartSVG = "displayCity";
$chartCity->showControls=true;
$chartCity->showXAxis="false";
$chartCity->tooltips=true;
$chartCity->height = 280;
?>

<link href="http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer" rel="stylesheet" type="text/css">
<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">
<link href="/public/bootstrap/css/bootstrap.css" rel="stylesheet">
<link href="/public/bootstrap/css/custom.css" rel="stylesheet">
<script src="/public/nvd3/nvd3-camemis.php"></script>
    <div id="initStatistic" class="container-fluid" style="background-color:#f9f9f9;">
    
         <div class="row">
            <div class="col-md-12">
                <div class="panel-heading"><h5><b><?=MAJOR?></b></h5></div>
                
                <div class="panel-body">
                    <button type="button" id="btnStudentEDMajor" class="btn btn-info"><span class="glyphicon glyphicon-search"></span>View Details</button>
                    <?= $chartStudentEDMajor->setChartDisplay(); ?>
                    <script><?= $chartStudentEDMajor->setChartScript(); ?></script> 
                </div>     
            </div>  
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <div class="panel-heading"><h5><b><?=QUALIFICATION_DEGREE?></b></h5></div>
                <div class="panel-body">
                    <button type="button" id="btnStudentCityProvince" class="btn btn-info"><span class="glyphicon glyphicon-search"></span>View Details</button>
                    <?= $chartCity->setChartDisplay(); ?>
                    <script><?= $chartCity->setChartScript(); ?></script> 
                </div> 
            </div>
        </div>
            
    </div>
    <script>
        Ext.onReady(function() {
            
            /*viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                title: ''
                ,id:'westcenter'
                ,collapsible: false
                ,region:'center'
                ,layout: 'fit'
                ,margins: '0 3 3 3'
                ,border:false
                ,bodyStyle: 'background:#dee7f6;'
                ,items: [{
                    border: false
                    ,bodyStyle: 'background:#dee7f6;'
                    ,autoScroll:true
                    ,contentEl: 'initStatistic'
                }]
            }]
        });*/
        
           Ext.get('btnStudentEDMajor').on('click', function(){
               window.parent.openWinMax('', '/student/search/?camIds=<?=$this->urlEncryp->encryptedGet($setParams);?>');
           });
           Ext.get('btnStudentCityProvince').on('click', function(){
               window.parent.openWinMax('', '/student/search/?camIds=<?=$this->urlEncryp->encryptedGet($setParams);?>');
           });
           
        });
    </script>
</body>
</html>
