<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 01.11.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $MAIN_CONTENT = "{
            title: '".MAIN_CONTENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'MAIN_CONTENT', url: '/room/roomcreate/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $MAIN_CONTENT;
        
        $TEACHING_SESSION = "{
            title: '".TEACHING_SESSION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'TEACHING_SESSION', url: '/room/listroomsession?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $TEACHING_SESSION;
        
        //
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'bottom'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>