<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("ROOM");
$OBJECT_FORM->setLoadUrl('/room/jsonload/');
$OBJECT_FORM->setSaveUrl('/room/jsonsave/');

$HAS_CHILD = RoomDBAccess::checkChild($this->objectId);

if($this->facette){
    $refreshId = $this->facette->PARENT;
}else{
    $refreshId = $this->parentId;
}

function setItems($fieldObject){
    $data = Array();
    switch($fieldObject->CHOOSE_TYPE){
        case 1:
            $entries = RoomDescriptionDBAccess::sqlDescription($fieldObject->ID, 1);
            if($entries){
                foreach($entries as $value){
                    $data[] = "{boxLabel: '" . setShowText($value->NAME) . "', name:'CHECKBOX_" . $value->ID . "', inputValue: '" . $value->ID . "'}";
                }
            }
            break;
        case 2:
            $entries = RoomDescriptionDBAccess::sqlDescription($fieldObject->ID, 2);
            if($entries){
                foreach($entries as $value){
                    $data[] = "{boxLabel: '" . setShowText($value->NAME) . "', name:'RADIOBOX_" . $fieldObject->ID . "', inputValue: '" . $value->ID . "'}";
                }
            }
        break;
    }
    return implode(",",$data);
}

$FIELD_PANEL_ITEMS = Array();
$entries = RoomDescriptionDBAccess::sqlDescription(false,false);
if($entries){
    foreach($entries as $value){

        $fieldObject = RoomDescriptionDBAccess::findObjectFromId($value->ID);
        if($fieldObject){

            if(RoomDescriptionDBAccess::checkChild($value->ID)){
                $ITEMS = "";
                $ITEMS .= "{";
                $ITEMS .= "xtype:'fieldset'";
                $ITEMS .= ",collapsible:true,collapsed:false";
                $ITEMS .= ",collapsed: false";
                $ITEMS .= ",title: '".setShowText($fieldObject->NAME)."'";
                $ITEMS .= ",bodyStyle: 'padding:10px;background: ".CamemisPage::userFormBgColor().";'";
                $ITEMS .= ",style: 'padding-bottom: 5px'";
                $ITEMS .= ",width: 550";

                switch($fieldObject->CHOOSE_TYPE){
                    case 1:
                        $ITEMS .= ",items:[{";
                            $ITEMS .= "xtype: 'checkboxgroup'";
                            $ITEMS .= ",fieldLabel: ''";
                            $ITEMS .= ",hideLabel: true";
                            $ITEMS .= ",border: false";
                            $ITEMS .= ",autoHeight:true";
                            $ITEMS .= ",columns:2";
                            $ITEMS .= ",itemCls: 'x-check-group-alt'";
                            $ITEMS .= ",items:[".setItems($fieldObject)."]";
                        $ITEMS .= "}]";
                        break;
                    case 2:
                        $ITEMS .= ",items:[{";
                            $ITEMS .= "xtype: 'radiogroup'";
                            $ITEMS .= ",fieldLabel: ''";
                            $ITEMS .= ",hideLabel: true";
                            $ITEMS .= ",border: false";
                            $ITEMS .= ",autoHeight:true";
                            $ITEMS .= ",columns:2";
                            $ITEMS .= ",itemCls: 'x-check-group-alt'";
                            $ITEMS .= ",items:[".setItems($fieldObject)."]";
                        $ITEMS .= "}]";
                        break;
                }
                $ITEMS .= "}";
                $FIELD_PANEL_ITEMS[] = $ITEMS;
            }
        }
    }
}

$DISPLAY_FIELDS = implode(",",$FIELD_PANEL_ITEMS);

//@PENG 23.01.2014
$facility = '';
if($this->objectId !='new' ){
    $FACILITY_PANEL_ITEMS = Array();
    $facility = RoomDBAccess::findFacilityByRoomId($this->objectId, $this->roomName);

    if($facility){
        foreach($facility as $value){
            if($value->PERMANENT_CHECKOUT == 0){
                if($value->PERMANENT_CHECKOUT == 'CHECK-OUT'){
                    $COUNT_FACILITY = RoomDBAccess::countFacilityByType($value->FACILITY_TYPE);

                    $panel = "{
                        ".CamemisField::Displayfield($value->NAME,"(".$value->SHORT.") ".$value->NAME,$COUNT_FACILITY)."
                    }";

                    $FACILITY_PANEL_ITEMS[] = $panel;    
                }    
            }else{
                $COUNT_FACILITY = RoomDBAccess::countFacilityByType($value->FACILITY_TYPE);
            
                $panel = "{
                    ".CamemisField::Displayfield($value->NAME,"(".$value->SHORT.") ".$value->NAME,$COUNT_FACILITY)."
                }";
                
                $FACILITY_PANEL_ITEMS[] = $panel;   
            }   
        }    
    }

    $DISPLAY_FACILITIES = "[".implode(',',$FACILITY_PANEL_ITEMS)."]";    
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        if($HAS_CHILD){
            $ITEMS = "
            [
                {".CamemisField::Textfield("SHORT_ID", "SHORT", SHORT,true)."}
                ,{".CamemisField::Textfield("NAME_ID", "NAME", NAME,true)."}
            ]";
        }else{
            $ITEMS = "
            [
                {".CamemisField::Textfield("SHORT_ID", "SHORT", SHORT,true)."}
                ,{".CamemisField::Textfield("NAME_ID", "NAME", NAME, true)."}
                ,{".CamemisField::Textfield("BUILDING_ID", "BUILDING", BUILDING)."}
                ,{".CamemisField::Textfield("FLOOR_ID", "FLOOR", FLOOR)."}
                ,{".CamemisField::Numberfield("MAX_COUNT", "MAX_COUNT", PERSONS, false, false, false) . "}
                ,{".CamemisField::Numberfield("ROOM_SIZE", "ROOM_SIZE", ROOM_SIZE, false, false, false) . "}
            ]
            ";
        }
        
        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: ".$ITEMS."
            }]
        }
        ";
        
        if($this->objectId != 'new'){
            $FACILITY_INFORMATION= "
            {
                title: '".FACILITY_INFORMATION."'
                ,autoHeight: true
                ,style: 'padding-bottom: 5px'
                ,bodyStyle: 'padding:10px'
                ,width: 550
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,bodyStyle: 'padding:10px;background: ".CamemisPage::userFormBgColor().";'
                    ,autoHeight:true
                    ,items:[".$DISPLAY_FACILITIES."]
                }]
            }
            ";
        }

        $DESCRIPTION = "
        {
            title: '".DESCRIPTION."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,height: 100
            ,items:[{
                layout: 'fit'
                ,border: false
                ,bodyStyle: 'padding:5px'
                ,items: [{".CamemisField::Textarea("DESCRIPTION", false,100)."}]
            }]
        }
        ";
        
        if($this->objectId == "new"){
            $items = "
                border: false
                ,id: 'FORM_ITEMS'
                ,bodyStyle: 'padding:0px'
                ,items: [
                    ".$DETAIL_INFORMATION."
                    ,".$DESCRIPTION."
                ]
            ";
        }else{
            if($HAS_CHILD){
                $items = "
                    border: false
                    ,id: 'FORM_ITEMS'
                    ,bodyStyle: 'padding:0px'
                    ,items: [
                        ".$DETAIL_INFORMATION."
                    ]
                ";
            }else{
                
                $FORM_ITEMS = "[";
                $FORM_ITEMS .= "".$DETAIL_INFORMATION;
                if($facility) $FORM_ITEMS .= ",".$FACILITY_INFORMATION;
                if ($DISPLAY_FIELDS) $FORM_ITEMS .= ",".$DISPLAY_FIELDS;
                $FORM_ITEMS .= ",".$DESCRIPTION;
                $FORM_ITEMS .= "]";
                
                $items = "
                    border: false
                    ,id: 'FORM_ITEMS'
                    ,bodyStyle: 'padding:0px'
                    ,items:".$FORM_ITEMS."
                ";
            }
        }
        
        $OBJECT_FORM->addObjectItems($items);

        if(!isset($_GET['schedule'])){
            
            $OBJECT_FORM->addTBarItems("
                text: '".CANCEL."'
                ,id: 'CANCEL_ID'
                ,formBind:true
                ,iconCls:'icon-cancel'
                ,scope:this
                ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
            ");
            
            if($this->objectId !="new"){
                if(UserAuth::getACLValue("SCHOOL_SETTING_REMOVE_RIGHT"))
                $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormEasyRemoveObject());    
            }
            
            if(UserAuth::getACLValue("SCHOOL_SETTING_EDIT_RIGHT"))
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
            
        }

        $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '".$this->objectId."'");
        $OBJECT_FORM->setSaveParams("
            cmd: 'actionSaveRoom'
            ,objectId: '".$this->objectId."'
            ,parentId:'".$this->parentId."'
        ");
        $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '".$this->objectId."'");

        $OBJECT_FORM->setRemoveParams("
            cmd: 'removeObject'
            ,objectId: '".$this->objectId."'
        ");

        ///////////////////////////////////////////////////
        if($this->facette){
            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                if(window.parent.Ext.getCmp('ROOM_LIST_ID'))
                window.parent.Ext.getCmp('ROOM_LIST_ID').store.reload();
                ".camemisPage::setRequestURI()."
            ");
            
            $OBJECT_FORM->setOnEmbeddedReleaseEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                if(window.parent.Ext.getCmp('ROOM_LIST_ID'))
                window.parent.Ext.getCmp('ROOM_LIST_ID').store.reload();
                ".camemisPage::setRequestURI()."
            ");
            
            $OBJECT_FORM->setOnEmbeddedRemoveEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                if(window.parent.Ext.getCmp('ROOM_LIST_ID'))
                window.parent.Ext.getCmp('ROOM_LIST_ID').store.reload();
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            ");
            
        }else{
            
            $parentObject = RoomDBAccess::findRoomFromId($this->parentId);
            
            $newRefreshId = $parentObject?$parentObject->PARENT:0;
            
            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                if(window.parent.Ext.getCmp('ROOM_LIST_ID'))
                window.parent.Ext.getCmp('ROOM_LIST_ID').store.reload();
                var result = Ext.util.JSON.decode(action.response.responseText);
                window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
            "); 
        }
        
        ///////////////////////////////////////////////////
        
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'panel'
                ,id: 'panel'
                ,border: false
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                }]
            }]
        });
    });
</script>
<style type="text/css">
.x-check-group-alt {
    background: #D1DDEF;
}
</style>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>