<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("TRANSLATION");
$OBJECT_FORM->setLoadUrl('/translation/jsonload/');
$OBJECT_FORM->setSaveUrl('/translation/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

    <?
    /**
     * Extjs: s.gif
     */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    $CONST = "
    {
        title: 'Use in CAMEMIS'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width:550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF; padding:5px'
            ,items: [
                {".CamemisField::Textarea("CONST", false, 20, true)."}
            ]
        }]
    }
    ";

    function showTranslation($SYSTEM_LANGUAGE) {

        $extjs = "";
        $extjs .= "
        {
            title: 'English'
            ,id: 'ENGLISH'
            ,hidden: true
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width:550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,disabled: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF; padding:5px'
                ,items: [
                    {".CamemisField::Textarea("ENGLISH", false, 60)."}
                ]
            }]
        }
        ";

        $extjs .= "
        ,{
        title: '".$SYSTEM_LANGUAGE."'
        ,id: '".$SYSTEM_LANGUAGE."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width:550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,disabled: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF; padding:5px'
            ,items: [
                {".CamemisField::Textarea($SYSTEM_LANGUAGE, false, 100)."}
            ]
        }]
        }
        ";

        return $extjs;
    }

    $items = "
    border: false
    ,id: 'FORM_ITEMS'
    ,bodyStyle: 'padding:0px'
    ,items: [
    ".$CONST.",
    ".showTranslation(Zend_Registry::get('SYSTEM_LANGUAGE'))."
    ]
    ";
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);}
    ");

    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSimpleSave());

    $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '".$this->objectId."'");
    $OBJECT_FORM->setSaveParams("
        cmd: 'updateObject'
        ,objectId: '".$this->objectId."'
    ");

    $OBJECT_FORM->setonEmbeddedEvents("
        window.parent.Ext.getCmp('TRANSLATION_LIST_ID').store.reload();
        window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);
    ");

    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>