<?
require_once 'clients/app_admin/AdminPage.php';
require_once 'clients/app_admin/AdminPage.php';
require_once 'clients/app_admin/AdminForm.php';
require_once 'clients/app_admin/AdminGrid.php';
require_once 'clients/app_admin/AdminPage.php';
require_once 'models/app_admin/MyConfig.php';

$AdminPage = AdminPage::getInstance();
$AdminPage->setLoadingMask = true;
print $AdminPage->showCamemisHeader();

$HIDDEN_PROVIDER_MANAGER = MyConfig::getACLValue("PROVIDER")?"false":"true";

?>
<div id="initCenter" class="x-hidden" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="header">Please make your selection...</h1>
</div>
<script>
Ext.onReady(function() {
    
    Ext.QuickTips.init();
    
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{
                region:'west'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width: 200
                ,minSize: 200
                ,maxSize: 200
                ,layout: 'fit'
                ,items:[{
                    layout: {
                        type:'vbox',
                        padding:'10',
                        align:'stretch'
                    }
                    ,border: false
                    ,defaults:{margins:'0 0 5 0'}
                    ,items:[{
                        xtype:'button'
                        ,height: 40
                        ,text: '<b>New DB-Column</b>'
                        ,handler: function(){
                            
                        }
                    },{
                        xtype:'button'
                        ,height: 40
                        ,text: '<b>Change DB-Column</b>'
                        ,handler: function(){
                            
                        }
                    },{
                        xtype:'button'
                        ,height: 40
                        ,text: '<b>Remove DB-Column</b>'
                        ,handler: function(){
                            
                        }
                    },{
                        xtype:'button'
                        ,height: 40
                        ,text: '<b>Translation</b>'
                        ,handler: function(){
                            
                        } 
                    }]
                }]
            },{
                collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,contentEl: 'initCenter'
                }]
            }]
        }]
    });
});
</script>
<?
print $AdminPage->showCamemisFooter();
?>