<?
require_once 'clients/app_admin/AdminBar.php';
require_once 'clients/app_admin/AdminPage.php';
require_once 'clients/app_admin/AdminForm.php';
require_once 'clients/app_admin/AdminTree.php';
require_once 'clients/app_admin/AdminGrid.php';
require_once 'clients/app_admin/AdminPage.php';

$OBJECT_ADMIN_PAGE = AdminPage::getInstance();
$OBJECT_ADMIN_PAGE->setLoadingMask = true;
print $OBJECT_ADMIN_PAGE->showCamemisHeader();

$LOCAL_TREE = new AdminTree("MAIN", "LIST_LOCAL");
$CUSTOMER_TREE = new AdminTree("CUSTOMER", "LIST_OF_CUSTOMERS");
?>
<div id="initCenter" class="x-hidden" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="header">Please make your selection...</h1>
</div>
<script>
var local;
Ext.onReady(function() {

    Ext.QuickTips.init();
    
    <?
    $LOCAL_TREE->setURL('/main/jsontree/');
    $LOCAL_TREE->isAsyncTreeNode = false;
    $LOCAL_TREE->isTreeExpand = true;
    $LOCAL_TREE->addTBarItems(AdminBar::tbarTreeRefresh(false));
    $LOCAL_TREE->setBaseParams("
    	cmd: 'jsonTreeAllLocals'
    ");
    $LOCAL_TREE->renderJS();
    
    $CUSTOMER_TREE->setURL('/customer/jsontree/');
    $CUSTOMER_TREE->isAsyncTreeNode = false;
    $CUSTOMER_TREE->addTBarItems(AdminBar::tbarTreeRefresh(false));
    $CUSTOMER_TREE->setBaseParams("
    	cmd: 'jsonTreeAllCustomers'
        ,local: local
    ");
    $CUSTOMER_TREE->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{
               	region:'west'
                ,id: 'west'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width: percentWidth(28)
                ,minSize: percentWidth(28)
                ,maxSize: percentWidth(28)
                ,layout: 'fit'
                ,items:[{xtype: '<?=$LOCAL_TREE->getObjectXtype();?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,contentEl: 'initCenter'
                }]
            }]
        }]
    });
    var myTreeLocal = <?=$LOCAL_TREE->ExtgetCmp();?>;
    myTreeLocal.on('click', function(node, e){
        if(node.isLeaf()){
            Ext.getCmp('west').collapse();
            var customerId = node.id;
            var schoolURL = node.text;
            var url = '/customer/showcustomer/?GuId=' + customerId + '&schoolURL=' + schoolURL;
            clickOpenPage('center','',url);
        }
    });
});
</script>
<?
print $OBJECT_ADMIN_PAGE->showCamemisFooter();
?>