<?
require_once 'clients/app_admin/AdminPage.php';
require_once 'clients/app_admin/AdminForm.php';
require_once 'clients/app_admin/AdminGrid.php';
require_once 'clients/app_admin/AdminField.php';
require_once 'clients/app_admin/AdminBar.php';
require_once 'clients/app_admin/AdminPage.php';
require_once 'models/app_admin/AdminCustomerDBAccess.php';

$CAMEMIS_PAGE = AdminPage::getInstance();
$DB_CUSTOMER = new AdminCustomerDBAccess();

print $CAMEMIS_PAGE->showCamemisHeader();

function getVisitorsCound($month, $year){
    
    $SQL = "SELECT COUNT(*) AS C FROM t_logininfo t_logininfo";
    $SQL .= " WHERE MONTH(DATE) = ".$month." AND YEAR(DATE)='".$year."'";
    $SQL .= " LIMIT 0,1";
    $result = Zend_Registry::get('SCHOOL_DB_ACCESS')->fetchRow($SQL);
    return $result?$result->C:0;
}

function getWeekVisitorsCound(){
    $SQL = "SELECT COUNT(*) AS C";
    $SQL .= " FROM t_logininfo";
    $SQL .= " WHERE";
    $SQL .= " YEARweek(DATE) = YEARweek(CURRENT_DATE)";
    //echo $SQL;
    $result = Zend_Registry::get('SCHOOL_DB_ACCESS')->fetchRow($SQL);
    return $result?$result->C:0;
}

function getLastWeekVisitorsCound(){
    $SQL = "SELECT COUNT(*) AS C";
    $SQL .= " FROM t_logininfo";
    $SQL .= " WHERE";
    $SQL .= " YEARweek(DATE) = YEARweek(CURRENT_DATE - INTERVAL 7 DAY)";
    //echo $SQL;
    $result = Zend_Registry::get('SCHOOL_DB_ACCESS')->fetchRow($SQL);
    return $result?$result->C:0;
}

function getLastMonthVisitorsCound(){
    $SQL = "SELECT COUNT(*) AS C";
    $SQL .= " FROM t_logininfo";
    $SQL .= " WHERE";
    $SQL .= " SUBSTRING(DATE from 1 FOR 7) = SUBSTRING(CURRENT_DATE - INTERVAL 1 MONTH from 1 FOR 7) ";
    //echo $SQL;
    $result = Zend_Registry::get('SCHOOL_DB_ACCESS')->fetchRow($SQL);
    return $result?$result->C:0;
}
?>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);
    
    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Week or Month');
        data.addColumn('number', 'Visitors');
        data.addRows([
          ['Last Month', <?=getLastMonthVisitorsCound();?>],
          ['Last Week', <?=getWeekVisitorsCound();?>]
        ]);

        var options = {
          width: 500, height: 400,
          title: 'CAMEMIS Visitors',
          hAxis: {title: 'Week or Month', titleTextStyle: {color: 'red'}}
        };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>
<div id="chart_div"></div>
<?
$a = Zend_Registry::getInstance();
print $CAMEMIS_PAGE->showCamemisFooter();
?>