<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'models/app_university/AcademicDateDBAccess.php';
require_once 'models/app_university/academic/AcademicDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$DB_SCHOOLYEAR = AcademicDateDBAccess::getInstance();

$OBJECT_FORM = new CamemisForm("ACADEMIC");
$OBJECT_FORM->setLoadUrl('/academic/jsonload/');
$OBJECT_FORM->setSaveUrl('/academic/jsonsave/');

$INSTRUCTOR_GRID = new CamemisGrid("INSTRUCTOR", "LIST");
$INSTRUCTOR_GRID->setLoadUrl('/academic/jsonload/');
$INSTRUCTOR_GRID->setSaveUrl('/academic/jsonsave/');

if(!$this->facette) {header("Location: /main/permission/");exit;}

$schoolyearId = $this->facette->SCHOOL_YEAR;
$CURRENT_SCHOOLYEAR = $DB_SCHOOLYEAR->isCurrentSchoolyear($schoolyearId);

print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<script>
    <?
    camemisPage::ExtformVTypes();
    ?>
    Ext.onReady(function() {
        
        function cssText(value, metadata, record){
            return '<div style="font-weight:normal; color:#333; padding: 5px;">' + value + '</div>';
        }
        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '" . $this->facette->GUID . "'");
        $OBJECT_FORM->setSaveParams("
            cmd: 'updateObject'
            ,objecttype: 'CLASS'
            ,objectId: '" . $this->facette->GUID . "'
        ");
        $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '" . $this->facette->GUID . "'");
        
        $DETAIL_INFORMATION_ITEMS = "[";
        
        $DETAIL_INFORMATION_ITEMS .= "{" . CamemisField::Textfield("CODE", "CODE", CODE_ID, false, true) . "}";
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Textfield("NAME", "NAME", NAME) . "}";
        if($this->facette->EDUCATION_SYSTEM){
            $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Textfield("NUMBER_CREDIT", "NUMBER_CREDIT", CREDITS, false, false) . "}";
        }
        $DETAIL_INFORMATION_ITEMS .= ",{" . CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false) . "}";
        
        $DETAIL_INFORMATION_ITEMS .= "]";
        $DETAIL_INFORMATION = "
        {
            title: '" . DETAIL_INFORMATION . "'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width:550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: ".$DETAIL_INFORMATION_ITEMS."
            }]
        }";
        
        $WORKING_DAYS = "
        {
            title: '".WORKING_DAYS."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,autoHeight: true
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: [
                    {".CamemisField::Checkbox("ID1","MO", MONDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID2","TU", TUESDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID3","WE", WEDNESDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID4","TH", THURSDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID5","FR", FRIDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID6","SA", SATURDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID7","SU", SUNDAY, 1, false)."}
                ]
            }]
        }";
        
        $DISABLED = 'false';
        if($this->facette){
            if($this->facette->STATUS){
                $DISABLED = 'true';
            }
        }
        $EXTRA_SEMESTER_DATE = "
        {
            title: '".EXTRA_SEMESTER_DATE."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,autoHeight: true
            ,tbar:['->',{
                text:'".FIRST_SEMESTER."'
                ,iconCls: 'icon-date'
                ,disabled:".$DISABLED."
                ,handler: function(){
                    showWinExtraSemesterDate(1);
                }
            },'-',{
                text:'".SECOND_SEMESTER."'
                ,iconCls: 'icon-date'
                ,disabled:".$DISABLED."
                ,handler: function(){
                    showWinExtraSemesterDate(2);
                }
            }]
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {".CamemisField::Displayfield("DISPLAY_FIRST_SEMESTER", FIRST_SEMESTER)."}
                    ,{".CamemisField::Displayfield("DISPLAY_SECOND_SEMESTER", SECOND_SEMESTER)."}
                ]
            }]
        }";
        
        $DESCRIPTION = "
        {
            title: '".DESCRIPTION."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: true
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:5px'
                ,items: [[{".CamemisField::Textarea("REMARK", false,200)."}]]
            }]
        }";
        
        ////////////////////////////////////////////////////////////////////////
        $INSTRUCTOR_GRID->addReadField("name: 'ID'");
        $INSTRUCTOR_GRID->addReadField("name: 'CHECKED'");
        $INSTRUCTOR_GRID->addReadField("name: 'CODE'");
        $INSTRUCTOR_GRID->addReadField("name: 'LASTNAME'");
        $INSTRUCTOR_GRID->addReadField("name: 'FIRSTNAME'");
        
        $INSTRUCTOR_GRID->addColumn("
            xtype: 'checkboxcolumn'
            ,align:'center'
            ,header: '<b>" . APPLY . "</b>'
            ,dataIndex: 'CHECKED'
            ,width: 80
            ,on: 1
            ,off: 0
            ,renderer: cssText
        ");
        
        $INSTRUCTOR_GRID->addColumn("
            header: '<b>" . CODE_ID . "</b>'
            , align:'left'
            , sortable: false
            , dataIndex: 'CODE'
            , width: 80
            ,renderer: cssText
        ");
        
        if(!SchoolDBAccess::displayPersonNameInGrid()){
            $INSTRUCTOR_GRID->addColumn("
                header: '<b>" . LASTNAME . "</b>'
                , align:'left'
                , sortable: false
                , dataIndex: 'LASTNAME'
                , width: 120
                ,renderer: cssText
            ");
            
            $INSTRUCTOR_GRID->addColumn("
                header: '<b>" . FIRSTNAME . "</b>'
                , align:'left'
                , sortable: false
                , dataIndex: 'FIRSTNAME'
                , width: 120
                ,renderer: cssText
            ");
        }else{
            $INSTRUCTOR_GRID->addColumn("
                header: '<b>" . FIRSTNAME . "</b>'
                , align:'left'
                , sortable: false
                , dataIndex: 'FIRSTNAME'
                , width: 120
                ,renderer: cssText
            ");
            
            $INSTRUCTOR_GRID->addColumn("
                header: '<b>" . LASTNAME . "</b>'
                , align:'left'
                , sortable: false
                , dataIndex: 'LASTNAME'
                , width: 120
                ,renderer: cssText
            ");
        }
                
        $INSTRUCTOR_GRID->baseParams = "
            start:0
            ,limit:100
            ,objectId: '" . $this->facette->GUID . "'
            ,cmd: 'jsonInstructorsByClass'
        ";
        $INSTRUCTOR_GRID->setSaveParams("
            cmd: 'actionClassInstructor'
            ,objectId: '" . $this->facette->GUID . "'
        ");
        $INSTRUCTOR_GRID->setEditEmbeddedEvents("
             XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        ");
        $INSTRUCTOR_GRID->isGridEditing = true;
        $INSTRUCTOR_GRID->loadMask = false;
        $INSTRUCTOR_GRID->isPagingToolbar = true;
        $INSTRUCTOR_GRID->isQuickySearch = true;
        $INSTRUCTOR_GRID->isObjectDefaultOnLoad = true;
        $INSTRUCTOR_GRID->forceFit = "false";
        $INSTRUCTOR_GRID->renderJS();
        ////////////////////////////////////////////////////////////////////////
        
        $INSTRUCTOR_GRID = "
        {
            title: '".INSTRUCTOR_IN."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,height: 350
            ,layout: 'fit'
            ,items:[{xtype: '".$INSTRUCTOR_GRID->getObjectXtype()."'}]
        }";
        
        $WORKING_DAYS = "
        {
            title: '".WORKING_DAYS."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,autoHeight: true
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: [
                    {".CamemisField::Displayfield("SHOW_MO", MONDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_TU", TUESDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_WE", WEDNESDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_TH", THURSDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_FR", FRIDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_SA", SATURDAY)."}
                    ,{".CamemisField::Displayfield("SHOW_SU", SUNDAY)."}
                ]
            }]
        }";
        
        ////////////////////////////////////////////////////////////////////////
        $CREATED = "
        {
            title: '".CREATED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("CREATED_DATE",CREATED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("CREATED_BY",CREATED_BY,false)."
                }]
            }]
        }";
        
        $MODIFIED = "
        {
            title: '".MODIFIED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("MODIFY_DATE",MODIFY_DATE,false)."
                },{
                    ".CamemisField::Displayfield("MODIFY_BY",MODIFY_BY,false)."
                }]
            }]
        }";
        
        $DISABLED = "
        {
            title: '".DISABLED."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,bodyStyle: 'padding:5px'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,frame:true
                ,bodyStyle: 'padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("DISABLED_DATE",DISABLED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("DISABLED_BY",DISABLED_BY,false)."
                }]
            }]
        }";
        ////////////////////////////////////////////////////////////////////////
        
        $DISPLAY_ITEMS = "[";
        
        $DISPLAY_ITEMS .= "".$DETAIL_INFORMATION;
        
        if($this->facette){
            if($this->facette->EXTRA_SEMESTER_DATE){
                $DISPLAY_ITEMS .= ",".$EXTRA_SEMESTER_DATE;
            }
        }
        
        $DISPLAY_ITEMS .= ",".$WORKING_DAYS;
        $DISPLAY_ITEMS .= ",".$DESCRIPTION;
        $DISPLAY_ITEMS .= ",".$INSTRUCTOR_GRID;
        $DISPLAY_ITEMS .= ",".$CREATED;
        $DISPLAY_ITEMS .= ",".$MODIFIED;
        $DISPLAY_ITEMS .= ",".$DISABLED;
        $DISPLAY_ITEMS .= "]";
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:10px'
            ,items: ".$DISPLAY_ITEMS."
        ";
        
        $OBJECT_FORM->addObjectItems($items);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('ACADEMIC_ID').expand();
            }
        ");
        
        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
        
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 150;
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            myNode = myTree.getNodeById('".$this->facette->PARENT."');
            myNode.reload();
            myNode.expand(true, false); 
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");

        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            myTree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            myNode = myTree.getNodeById('".$this->facette->PARENT."');
            myNode.reload();
            myNode.expand(true, false); 
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");

        $OBJECT_FORM->bodyStyle = "padding:0px";
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,id: 'content'
                ,title: ''
                ,layout: 'card'
                ,activeItem: 0
                ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
            }]
        });
    });
</script>
<?
print$CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>