<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$LIST_OF_STUDENTS = new CamemisGrid("LIST_OF_STUDENTS", "LIST_OF_STUDENTS");
$LIST_OF_STUDENTS->setLoadUrl("/student/jsonload/");
$LIST_OF_STUDENTS->setSaveUrl("/student/jsonsave/");

$ASSIGNED_STUDENTS = new CamemisGrid("STUDENT", "LIST_GRADE_YEAR");
$ASSIGNED_STUDENTS->setLoadUrl("/student/jsonload/");
$ASSIGNED_STUDENTS->setSaveUrl("/student/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$TERM_NUMBER = AcademicDBAccess::findAcademicTerm($this->facette->SCHOOL_YEAR);
$columndata = Utiles::getGridColumnData("STUDENT_LIST_GRADE_YEAR_ID");

?>

<script>
    
    var studentId,academicTerm;
    Ext.onReady(function() {
        
        function cssStatus(v, p, record){
            return String.format('<div style=\"font-weight:bold;padding:4px;background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['BG_COLOR']
            ,record.data['BG_COLOR_FONT']
            );
        }
        
        function cssText(value, metadata, record){
            var name = record.data.STUDENT;
            metadata.attr = 'ext:qtip="' + name + '"';
            return '<span style="color:#333; padding: 5px; height: 15px;">' + value + '</span>';
        }
           
        function qtipFullname(value, metadata, record){
            
            var isTransfer = record.data.TRANSFER;
            if (isTransfer === 1){
                var statusName = '<?=STUDENT_TRANSFER;?>';
                metadata.attr = 'ext:qtip="' + statusName + '"';
            }
            return '' + value + '';
        }

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $LIST_OF_STUDENTS->addReadField("name: 'CODE'");
        $LIST_OF_STUDENTS->addReadField("name: 'STUDENT_SCHOOL_ID'");
        $LIST_OF_STUDENTS->addReadField("name: 'LASTNAME'");
        $LIST_OF_STUDENTS->addReadField("name: 'FIRSTNAME'");
        $LIST_OF_STUDENTS->addReadField("name: 'GENDER'");
        $LIST_OF_STUDENTS->addReadField("name: 'DATE_BIRTH'");
        $LIST_OF_STUDENTS->addReadField("name: 'BG_COLOR'");
        $LIST_OF_STUDENTS->addReadField("name: 'BG_COLOR_FONT'");
        $LIST_OF_STUDENTS->addReadField("name: 'STATUS_KEY'");
        
        switch(Zend_Registry::get('SYSTEM_LANGUAGE')){
            case "VIETNAMESE": $width = 100;break;
            default: $width = 85;break;
        }
        
        $LIST_OF_STUDENTS->addColumn("header: '<b>".STATUS."</b>', align:'center', width: ".$width.", renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY'");
        $LIST_OF_STUDENTS->addColumn("header: '<b>".STUDENT_SCHOOL_ID."</b>', align:'left', renderer:cssText, sortable: true, width: 100, dataIndex: 'STUDENT_SCHOOL_ID'");
        
        $LIST_OF_STUDENTS->addColumn("header: '<b>".CODE_ID."</b>', align:'left', renderer:cssText, sortable: true, width: 80, dataIndex: 'CODE'");
        
        if(!SchoolDBAccess::displayPersonNameInGrid()){
            $LIST_OF_STUDENTS->addColumn("header: '<b>".LASTNAME."</b>', width: 100, renderer:cssText, sortable: true, dataIndex: 'LASTNAME'");
            $LIST_OF_STUDENTS->addColumn("header: '<b>".FIRSTNAME."</b>', width: 100, renderer:cssText, sortable: true, dataIndex: 'FIRSTNAME'");
        }else{
            $LIST_OF_STUDENTS->addColumn("header: '<b>".FIRSTNAME."</b>', width: 100, renderer:cssText, sortable: true, dataIndex: 'FIRSTNAME'");
            $LIST_OF_STUDENTS->addColumn("header: '<b>".LASTNAME."</b>', width: 100, renderer:cssText, sortable: true, dataIndex: 'LASTNAME'");
        }
        $LIST_OF_STUDENTS->addColumn("header: '<b>".GENDER."</b>', width: 100, renderer: cssText, sortable: true, dataIndex: 'GENDER'");
        $LIST_OF_STUDENTS->addColumn("header: '<b>".DATE_BIRTH."</b>', width: 120, renderer: cssText, sortable: true, dataIndex: 'DATE_BIRTH'");
        
        $LIST_OF_STUDENTS->isQuickySearch = true;
        $LIST_OF_STUDENTS->isCheckboxSelect = true;
        
        $LIST_OF_STUDENTS->addTBarItems("tbar.add('-');");
        if(UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT")){
            $LIST_OF_STUDENTS->addTBarItems("
                tbar.add([{
                    id: 'LIST_ADD_ENROLLMENT_RECORD_ID'
                    ,text: '<b>".APPLY_INTO_LIST_OF_STUDENTS."</b>'
                    ,iconCls:'icon-disk'
                    ,scope:this
                    ,handler: this.onSelection
                }]);
            ");
        }

        $LIST_OF_STUDENTS->baseParams = "
            start:0
            ,limit:100
            ,academicId: '".$this->facette->GUID."'
            ,cmd: 'jsonUnassignedStudents'
        ";

        $LIST_OF_STUDENTS->setSelectionParams("
            cmd: 'jsonAddEnrollStudentSchoolyear'
            ,academicId: '".$this->facette->GUID."'
        ");

        $LIST_OF_STUDENTS->setSelectionEmbeddedEvents("
            Ext.getCmp('".$ASSIGNED_STUDENTS->getObjectId()."').store.reload();
        ");

        $LIST_OF_STUDENTS->forceFit = "false";
        $LIST_OF_STUDENTS->renderJS();

        ////////////////////////////////////////////////////////////////////////////
        $ASSIGNED_STUDENTS->addReadField("name: 'ID'");
        $ASSIGNED_STUDENTS->addReadField("name: 'CODE'");
        $ASSIGNED_STUDENTS->addReadField("name: 'STUDENT_SCHOOL_ID'");
        $ASSIGNED_STUDENTS->addReadField("name: 'FULL_NAME'");
        $ASSIGNED_STUDENTS->addReadField("name: 'FIRSTNAME'");
        $ASSIGNED_STUDENTS->addReadField("name: 'LASTNAME'");
        $ASSIGNED_STUDENTS->addReadField("name: 'GENDER'");
        $ASSIGNED_STUDENTS->addReadField("name: 'DATE_BIRTH'");
        $ASSIGNED_STUDENTS->addReadField("name: 'CURRENT_SCHOOLYEAR'");
        $ASSIGNED_STUDENTS->addReadField("name: 'CURRENT_ACADEMIC'");
        $ASSIGNED_STUDENTS->addReadField("name: 'STUDENT_SCHOOL_ID'");
        $ASSIGNED_STUDENTS->addReadField("name: 'FIRSTNAME_LATIN'");
        $ASSIGNED_STUDENTS->addReadField("name: 'LASTNAME_LATIN'");
        $ASSIGNED_STUDENTS->addReadField("name: 'FULLNAME_MOTHER'");
        $ASSIGNED_STUDENTS->addReadField("name: 'FULLNAME_FATHER'");
        $ASSIGNED_STUDENTS->addReadField("name: 'CREATED_DATE'");
        $ASSIGNED_STUDENTS->addReadField("name: 'BG_COLOR'");
        $ASSIGNED_STUDENTS->addReadField("name: 'BG_COLOR_FONT'");
        $ASSIGNED_STUDENTS->addReadField("name: 'STATUS_KEY'");
        $ASSIGNED_STUDENTS->addReadField("name: 'STATUS'");
        $ASSIGNED_STUDENTS->addReadField("name: 'ENROLLMENT_TYPE'");
        
        switch(Zend_Registry::get('SYSTEM_LANGUAGE')){
            case "VIETNAMESE": $width = 100;break;
            default: $width = 85;break;
        }

        $ASSIGNED_STUDENTS->addColumn("header: '<b>".STATUS."</b>', align:'center', width: ".$width.", hidden:".checkColHidden(1, $columndata).", renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY'");
        $ASSIGNED_STUDENTS->addColumn("header: '<b>".CODE_ID."</b>', align:'center', width: 80, hidden:".checkColHidden(2, $columndata).", renderer: cssText, sortable: true, dataIndex: 'CODE'");
        $ASSIGNED_STUDENTS->addColumn("header: '<b>".STUDENT_SCHOOL_ID."</b>', align:'center', hidden:".checkColHidden(3, $columndata).", width: 80, renderer: cssText, sortable: true, dataIndex: 'STUDENT_SCHOOL_ID'");

        if(!SchoolDBAccess::displayPersonNameInGrid()){
            $ASSIGNED_STUDENTS->addColumn("
                header: '<b>".LASTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'LASTNAME'
                , editor: new Ext.form.TextField({
                    allowBlank: false
                    ,name: 'LASTNAME'
                })
            ");

            $ASSIGNED_STUDENTS->addColumn("
                header: '<b>".FIRSTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'FIRSTNAME'
                , editor: new Ext.form.TextField({
                    allowBlank: false
                    ,name: 'FIRSTNAME'
                })
            ");

        }else{

            $ASSIGNED_STUDENTS->addColumn("
                header: '<b>".FIRSTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'FIRSTNAME'
                , editor: new Ext.form.TextField({
                    allowBlank: false
                    ,name: 'FIRSTNAME'
                })
            ");

            $ASSIGNED_STUDENTS->addColumn("
                header: '<b>".LASTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'LASTNAME'
                , editor: new Ext.form.TextField({
                    allowBlank: false
                    ,name: 'LASTNAME'
                })
            ");
        }

        $ASSIGNED_STUDENTS->addColumn("header: '<b>".GENDER."</b>', align:'center',  width: 100, hidden:".checkColHidden(8, $columndata).", renderer: cssText, sortable: true, dataIndex: 'GENDER'");
        $ASSIGNED_STUDENTS->addColumn("header: '<b>".CURRENT_CLASS."</b>', width: 150, hidden:".checkColHidden(9, $columndata).", renderer: cssText, align: 'center', sortable: true, dataIndex: 'CURRENT_ACADEMIC'");
        $ASSIGNED_STUDENTS->addColumn("header: '<b>".CURRENT_SCHOOL_YEAR."</b>', align:'center', width: 120, hidden:".checkColHidden(10, $columndata).", renderer: cssText, sortable: true, dataIndex: 'CURRENT_SCHOOLYEAR'");
        $ASSIGNED_STUDENTS->addColumn("header: '<b>".CREATED_DATE."</b>', width: 150, hidden:".checkColHidden(11, $columndata).", renderer: cssText, sortable: true, dataIndex: 'CREATED_DATE'");
        
        $ASSIGNED_STUDENTS->isQuickySearch = true;
        $ASSIGNED_STUDENTS->isCheckboxSelect = false;
        $ASSIGNED_STUDENTS->isGridEditing = $this->isCurrentYear?true:false;
        
        $ASSIGNED_STUDENTS->addTBarItems(CamemisBar::tbarGridRemove("this.onRemove"));
        
        if(UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT")){
            $ASSIGNED_STUDENTS->addTBarItems("
                tbar.add('-',[{
                    id: 'ADD_STUDENTS'
                    ,iconCls:'icon-application_form_add'
                    ,text: '".ADD_STUDENTS." '
                    ,handler: function(){
                        openWinXType('WinXType','".ADD_STUDENTS."', '".$LIST_OF_STUDENTS->getObjectXType()."',percentWidth(80), percentHeight(85));
                    }
                }]);
            ");
        }
        
        if(UserAuth::getACLValue("STUDENT_SEARCH_EXECUTE_RIGHT")){
            $ASSIGNED_STUDENTS->addTBarItems("
                tbar.add(['->',{
                    text: '" . EXPORT_TO_EXCEL . "'
                    ,id: 'EXPORT_TO_EXCEL'
                    ,iconCls:'icon-page_excel'
                    ,handler: function(){
                        Ext.MessageBox.show({
                            msg: '".SAVING_YOUR_DATA_PLEASE_WAIT."',
                            progressText: 'Saving...',
                            width:300,
                            wait:true,
                            waitConfig: {interval:200},
                            icon:'ext-mb-download'
                        });
                        Ext.Ajax.request({
                            url: '/export/jsonexcel/'
                            ,method: 'POST'
                            ,params:{
                                cmd: 'studentSearch'
                                ,objectId:'STUDENT_LIST_GRADE_YEAR_ID'
                                ,gradeId: '".$this->facette->GRADE_ID."'
                                ,schoolyearId: '".$this->facette->SCHOOL_YEAR."'
                            }
                            ,success: function(response, options) {
                                Ext.MessageBox.hide();
                                window.location='/export/openstudentlist/'
                            }
                        });
                    }
                }]);
            ");
        }
        
        $ASSIGNED_STUDENTS->baseParams = "
            start:0
            ,limit:100
            ,gradeId: '".$this->facette->GRADE_ID."'
            ,schoolyearId: '".$this->facette->SCHOOL_YEAR."'
            ,cmd: 'searchStudent'
        ";

        $ASSIGNED_STUDENTS->setRemoveParams("
            cmd: 'jsonRemoveEnrolledStudentSchoolyear'
            ,type:'traditional'
            ,academicId: '".$this->facette->GUID."'
        ");
        
        ////////////////// Begin....
        $ASSIGNED_STUDENTS->setAftereditLoadParams("
            cmd: 'loadActionStudentSchoolYear'
        ");
        
        $ASSIGNED_STUDENTS->setRemoveEmbeddedEvents("
            Ext.getCmp('".$ASSIGNED_STUDENTS->getObjectId()."').store.reload();
        ");
        ////////////////// End...
        
        switch(UserAuth::getUserType()){
            case "ADMIN":
            case "SUPERADMIN":
                $ASSIGNED_STUDENTS->setSaveParams("
                    cmd: 'actionStudentGradeClassSchoolyear'
                    ,academicId: '".$this->facette->GUID."'
                    ,academicTerm:academicTerm
                ");
                $ASSIGNED_STUDENTS->setAftereditCallback("
                    XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                ");
                $ASSIGNED_STUDENTS->isGridEditing = true;
            break;
        }
        
        $ASSIGNED_STUDENTS->forceFit = "false";
        $ASSIGNED_STUDENTS->removeNAME = "STUDENT";
        $ASSIGNED_STUDENTS->setUserColumn = true;
        $ASSIGNED_STUDENTS->renderJS();
        
        $TAB_ITEMS = "";
        $TAB_ITEMS .= "{
            title: ''
            ,layout: 'fit'
            ,border:false
            ,items:[{
                border: false
                ,layout: 'card'
                ,id: 'center'
                ,activeItem: 0
                ,items:[{
                    border: false
                    ,layout: 'fit'
                    ,items: [{xtype: '".$ASSIGNED_STUDENTS->getObjectXType()."'}]
                }]
            }]
        }"; 
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,layout: 'fit'
                ,items:[<?=$TAB_ITEMS?>]
            }]
        });
        
        <?php
        
        $SHOW_DETAIL ="{";
        $SHOW_DETAIL .="text: '".SHOW_DETAIL." &raquo; ' + record.data.FULL_NAME";
        $SHOW_DETAIL .=",iconCls: 'icon-user'";
        $SHOW_DETAIL .=",handler: function(){";
        $SHOW_DETAIL .="contextMenu.hide();clickOpenPage('center','','/student/studentmonitor/?&target=".camemisId()."&objectId=' + record.data.ID);";
        $SHOW_DETAIL .="}";
        $SHOW_DETAIL .="}";
        $CONTEXTMENU_ITEMS[] = $SHOW_DETAIL;
        
        $CHOOSE_CONTEXTMENU_ITEMS = implode(",", $CONTEXTMENU_ITEMS);
        
        if($CONTEXTMENU_ITEMS){
            $js = "";
            $js .="var grid = Ext.getCmp('".$ASSIGNED_STUDENTS->getObjectId()."');";
            $js .="if (grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {";
                $js .="if (Ext.getCmp('REMOVE_ID')) Ext.getCmp('REMOVE_ID').enable();";
                $js .="var record = grid.store.getAt(rowIndex);";
                $js .= "if(columnIndex==1 || columnIndex==2){ ";
                    $js .="var contextMenu = new Ext.menu.Menu({";
                        $js .="items: [".$CHOOSE_CONTEXTMENU_ITEMS."]";
                    $js .="});";
                    $js .="contextMenu.showAt(event.xy);";
                    $js .="event.stopEvent();";
                $js .="}";
            $js .="});";
            echo $js;
        }
        ?>
        
        Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
        
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>