<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 01.01.2010
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTree("SUBJECT", "LIST");
$OBJECT_TREE->setURL('/subject/jsontree/');
$OBJECT_TREE->setSaveUrl('/subject/jsonsave/');

$OBJECT_GRID = new CamemisGrid("SUBJECT", "SUBJECT_TEACHER_CLASS");
$OBJECT_GRID->setLoadUrl('/subject/jsonload/');
$OBJECT_GRID->setSaveUrl('/subject/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    <?
    if($this->facette->EDUCATION_SYSTEM){
        echo "var subjectId='".$this->facette->SUBJECT_ID."';";    
    }else{
        echo "var subjectId;";
    }
    ?>
    
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        
        $OBJECT_TREE->setBaseParams("
            cmd: 'treeSubjectsByGrade'
            ,academicId: '".$this->facette->GUID."'
        ");
        
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->setWindowLocation($this->URL_WINDOW_LOCATION);
        $OBJECT_TREE->isOnClickContextMenu = false;
        $OBJECT_TREE->isTreeExpand = true;
        $OBJECT_TREE->renderJS();

        $OBJECT_GRID->addCellRenderer("
            
            function renderText(value, p, record, rowIndex){
                return String.format(
                    '<div style=\"padding: 5px;white-space:normal;\">{0}</div>',
                    value
                );
            }
        ");
        
        $OBJECT_GRID->addReadField("name: 'FIRST_SEMESTER'");
        $OBJECT_GRID->addReadField("name: 'SECOND_SEMESTER'");
        $OBJECT_GRID->addReadField("name: 'CODE'");
        $OBJECT_GRID->addReadField("name: 'LASTNAME'");
        $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
        
        $OBJECT_GRID->addColumn("header: '<B>".CODE_ID."</B>', align:'left', renderer: renderText, width: 80, sortable: false, dataIndex: 'CODE'");
        $OBJECT_GRID->addColumn("header: '<B>".LASTNAME."</B>', align:'left', renderer: renderText, width: 120, sortable: false, dataIndex: 'LASTNAME'");
        $OBJECT_GRID->addColumn("header: '<B>".FIRSTNAME."</B>', align:'left', renderer: renderText, width: 120, sortable: false, dataIndex: 'FIRSTNAME'");
        
        $OBJECT_GRID->addColumn("
            xtype: 'checkboxcolumn'
            ,header: '<B>".FIRST_SEMESTER."</B>'
            ,renderer: renderText
            ,align:'center'
            ,dataIndex: 'FIRST_SEMESTER'
            ,width: 100
            ,on: 1
            ,off: 0
        ");
        
        $OBJECT_GRID->addColumn("
            xtype: 'checkboxcolumn'
            ,header: '<B>".SECOND_SEMESTER."</B>'
            ,renderer: renderText
            ,align:'center'
            ,dataIndex: 'SECOND_SEMESTER'
            ,width: 100
            ,on: 1
            ,off: 0
        ");
        
        $OBJECT_GRID->setSaveParams("
            cmd: 'actionSubjectTeacherClass'
            ,subjectId: subjectId
            ,academicId: '".$this->facette->GUID."'
        ");
        
        $OBJECT_GRID->baseParams = "
            cmd: 'jsonLoadTeachersBySubject'
            ,subjectId: subjectId
            ,academicId: '".$this->facette->GUID."'
        ";
        
        $OBJECT_GRID->setEditEmbeddedEvents("
            Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
        ");
        
        $OBJECT_GRID->forceFit = "false";
        $OBJECT_GRID->isObjectDefaultOnLoad = true;
        $OBJECT_GRID->isCheckboxSelect = false;
        $OBJECT_GRID->isGridEditing = true;
        $OBJECT_GRID->loadMask = false;
        $OBJECT_GRID->renderJS();
        
        if($this->facette->EDUCATION_SYSTEM){
            $VIEWPORT_ITEMS = "
            {
                layout:'fit'
                ,border: false
                ,items: [{xtype: '".$OBJECT_GRID->getObjectXType()."'}]
            }"; 
        }else{
        
            $VIEWPORT_ITEMS = "
            {
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                },
                items: [{
                    title: '".SUBJECT."'
                    ,region:'west'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width: 250
                    ,minSize: 250
                    ,maxSize: 250
                    ,layout: 'fit'
                    ,items: [{xtype: '".$OBJECT_TREE->getObjectXType()."'}]
                },{
                    collapsible: false
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,items: [{
                        border: false
                        ,layout: 'anchor'
                        ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                        ,items: [{
                            title: ''
                            ,height:60
                            ,width:500
                            ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                            ,html:'<h1 class=\"header\">".PLEASE_MAKE_YOUR_SELECTIONS."</h1>'
                        }]
                    },{
                        id: 'CONTENT'
                        ,border: false
                        ,layout: 'fit'
                        ,items: [{xtype: '".$OBJECT_GRID->getObjectXType()."'}]
                    }]
                }]
            }";
        }
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[<?=$VIEWPORT_ITEMS;?>]
        });

        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;

        if(myTree) myTree.on('click', function(node, e){
            
            Ext.getCmp('CONTENT').setTitle(node.attributes.onlyText);
            subjectId = node.id;
            Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>').store.baseParams = {
                start:0
                ,limit:100
                ,cmd: 'jsonLoadTeachersBySubject'
                ,subjectId: node.id
                ,academicId: '<?=$this->facette->GUID?>'
            };
            Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>').store.load();
            Ext.getCmp('center').getLayout().setActiveItem(1);
            Ext.getCmp('center').ownerCt.doLayout();
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>