<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 22.10.2010
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisSchoolTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_university/staff/StaffDBAccess.php';
require_once 'models/app_university/subject/SubjectDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$schoolyearId = isset($_GET["schoolyearId"])?addText($_GET["schoolyearId"]):"";
$oldTeacherId = isset($_GET["oldTeacherId"])? addText($_GET["oldTeacherId"]):"";
$academicId = isset($_GET["academicId"])? (int) $_GET["academicId"]:"";
$subjectId = isset($_GET["subjectId"])? (int)$_GET["subjectId"]:"";

$teacherObject = StaffDBAccess::findStaffFromId($oldTeacherId);
$subjectObject = SubjectDBAccess::findSubjectFromId($subjectId);

$OBJECT_FORM = new CamemisForm("STAFF");
$OBJECT_FORM->setLoadUrl('/staff/jsonload/');
$OBJECT_FORM->setSaveUrl('/staff/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>

    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $NEW_TEACHER_OBJECT = new CamemisDynCombo("STAFF","COMBO_TEACHER");
        $NEW_TEACHER_OBJECT->setLoadUrl('/staff/jsonload/');
        $NEW_TEACHER_OBJECT->objectTitle = FUTURE_TEACHER;
        $NEW_TEACHER_OBJECT->allowBlank = "false";
        $NEW_TEACHER_OBJECT->varName = "newTeacherId";
        $NEW_TEACHER_OBJECT->renderJS();

        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonActionTeacherChange'
            ,schoolyearId: '".$schoolyearId."'
            ,academicId: '".$academicId."'
            ,subjectId: '".$subjectId."'
            ,oldTeacherId: '".$oldTeacherId."'
        ");

        $OBJECT_FORM->setonEmbeddedEvents("
            window.parent.Ext.getCmp('STAFF_LIST_OF_STAFFS_ID').store.load();
            window.parent.Ext.getCmp('OPEN_WIN_IFRAME_ID').close();
        ");

        $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,width: percentWidth(85)
        ,bodyStyle: 'padding:0px'
        ,layout: 'form'
        ,items: [
            {".CamemisField::Displayfield("SUBJECT", SUBJECT, $subjectObject->NAME)."}
            ,{".CamemisField::Displayfield("OLD_TEACHER", TEACHER_CHANGE, $teacherObject->LASTNAME." ".$teacherObject->FIRSTNAME)."}
            ,{xtype: '".$NEW_TEACHER_OBJECT->getObjectXType()."'}
            ,{".CamemisField::comboTwoTerms()."}
        ]
        ";
        $OBJECT_FORM->addObjectItems($items);
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
        });
        
        Ext.getCmp('COMBO_TEACHER_ID').store.baseParams = {
            start:0
            ,limit:100
            ,cmd: 'searchStaff'
            ,subjectId: '<?=$subjectId;?>'
            ,isTutor: 1
        };
        
        Ext.getCmp('COMBO_TEACHER_ID').store.load();
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>