<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader(); 

$setParams = "";
if($this->academicId) $setParams .= "&academicId=".$this->academicId."";
if($this->trainingId) $setParams .= "&trainingId=".$this->trainingId."";
if($this->classId) $setParams .= "&classId=".$this->classId."";
if($this->target) $setParams .= "&target=".$this->target."";
//@veasna
if($this->teacherId) $setParams .= "&teacherId=".$this->teacherId."";
?>
<style>
    .x-vr-tab-panel-bwrap {
        background: none repeat scroll 0 0 <?=CamemisPage::userBgColor();?>;
        border-left: 1px solid #99BBE8;
        float: right;
        padding: 3px;
    }
</style>
<script>

    Ext.onReady(function() {

        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $DAY_SCHEDULE = "{
            title: '".DAY_SCHEDULE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'DAY_SCHEDULE', url: '/schedule/dayeventlist/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
        }";
        $PENEL_ITEMS[] = $DAY_SCHEDULE;
        
        if($this->academicId){
            $WEEK_SCHEDULE = "{
                title: '".WEEK_SCHEDULE."'
                ,layout: 'fit'
                ,items:[new Ext.ux.IFrameComponent({ id: 'WEEK_SCHEDULE', url: '/schedule/classeventsetting/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
            }";
        }elseif($this->trainingId){
            $WEEK_SCHEDULE = "{
                title: '".WEEK_SCHEDULE."'
                ,layout: 'fit'
                ,items:[new Ext.ux.IFrameComponent({ id: 'WEEK_SCHEDULE', url: '/schedule/trainingscheduleweek/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
            }";
        }
        $PENEL_ITEMS[] = $WEEK_SCHEDULE;
        
        
        $EXTRA_TEACHING_SESSION = "{
            title: '".EXTRA_TEACHING_SESSION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'EXTRA_TEACHING_SESSION', url: '/schedule/listextrateachingsession/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
        }";
        $PENEL_ITEMS[] = $EXTRA_TEACHING_SESSION;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>