<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$academicId = isset($_GET["academicId"])? (int) $_GET["academicId"]:"";
$trainingId = isset($_GET["trainingId"])? (int) $_GET["trainingId"]:"";

if($academicId){
    $URL_WEEK_SCHEDULE = $this->URL_WEEK_SCHEDULE;
}elseif($trainingId){
    $URL_WEEK_SCHEDULE = "/schedule/trainingscheduleweek/?trainingId=".$trainingId.""; 
}

?>
<script>

    Ext.onReady(function() {

        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,border:false
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,items:[{
                    xtype: 'tabpanel'
                    ,plain:true
                    ,activeTab: 0
                    ,items:[{
                        title: '<?=DAY_SCHEDULE?>'
                        ,layout: 'fit'
                        ,border: false
                        ,items:[new Ext.ux.IFrameComponent({ id: 'DAY_SCHEDULE', url: '<?=$this->URL_DAY_SCHEDULE?>'})]
                    },{
                        title: '<?=EXTRA_TEACHING_SESSION?>'
                        ,layout: 'fit'
                        ,border: false
                        ,items:[new Ext.ux.IFrameComponent({ id: 'EXTRA_TEACHING_SESSION', url: '<?=$this->URL_EXTRA_TEACHING_SESSION_LIST?>'})]
                    },{
                        title: '<?=WEEK_SCHEDULE?>'
                        ,layout: 'fit'
                        ,border: false
                        ,items:[new Ext.ux.IFrameComponent({ id: 'WEEK_SCHEDULE', url: '<?=$URL_WEEK_SCHEDULE?>'})]
                    }]
                }]
            }]  
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>