<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$scheduleObject = ScheduleDBAccess::findScheduleFromGuId($this->scheduleId);

if(!$scheduleObject) {header("Location: /main/permission/");}

$SQL = Zend_Registry::get('DB_ACCESS')->select();
$SQL->distinct();
$SQL->from(array('A' => 't_subject'), array('NAME AS SUBJECT_NAME','ID AS SUBJECT_ID'));
$SQL->joinLeft(array('B' => 't_schedule'), 'A.ID=B.SUBJECT_ID', array('GUID AS SCHEDULE_GUID'));
$SQL->where("B.ACADEMIC_ID = '" . $scheduleObject->ACADEMIC_ID . "'");
$SQL->where("B.START_TIME = '" . $scheduleObject->START_TIME . "'");
$SQL->where("B.END_TIME = '" . $scheduleObject->END_TIME . "'");
$SQL->where("B.TERM = '" . $scheduleObject->TERM . "'");
$SQL->where("B.SHORTDAY = '" . $scheduleObject->SHORTDAY . "'");
$SQL->order("A.NAME DESC");
$result = Zend_Registry::get('DB_ACCESS')->fetchAll($SQL);

$firstObject = isset($result[0])?$result[0]:null;

$selectedId = $firstObject?$firstObject->SCHEDULE_GUID:0;

$STORE_ITEMS = "[";
if($result){
    $i=0;
    foreach($result as $value){
        $STORE_ITEMS .= $i?",":"";   
        $STORE_ITEMS .= "['".$value->SCHEDULE_GUID."','".$value->SUBJECT_NAME."']";        
        ++$i;
    }
}
$STORE_ITEMS .= "]";

$COMBO_ITEMS = "[{".CamemisField::Combo('COMO_SUBJECT','COMO_SUBJECT',$STORE_ITEMS, false,$selectedId,300,false)."}]";

$setParams = "";
$setParams .= "academicId=".$scheduleObject->ACADEMIC_ID."";
$setParams .= "&term=".$scheduleObject->TERM."";
$setParams .= "&isCancel=1";

?>
<script>
var schdeuleId = '<?=$selectedId;?>';
Ext.onReady(function() {

    <?
    /**
     * Extjs: s.gif
     */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'fit'
            ,border: false
            ,tbar:[{
                text:'<?=CANCEL?>'
                ,iconCls:'icon-cancel'
                ,handler: function(){
                    window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);
                }
            },'->','-',{
                xtype: 'buttongroup'
                ,items:<?=$COMBO_ITEMS?>
            }]
            ,items:[{
                border:false
                ,id:'content'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [new Ext.ux.IFrameComponent({ id: 'SCHEDULE', url:'/schedule/showclassevent/?camIds=<?=$this->urlEncryp->encryptedGet($setParams);?>&scheduleId=' + schdeuleId})]
            }]
        }]
    });
    
    var combo = Ext.getCmp('COMO_SUBJECT_ID');
        combo.on('select', function() {
        clickOpenPage('content','','/schedule/showclassevent/?camIds=<?=$this->urlEncryp->encryptedGet($setParams);?>&scheduleId=' + combo.getValue());
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>