<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("SCHEDULE", "LIST");
$OBJECT_TREE->setURL('/schedule/jsontree/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
	
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    $CAMEMIS_PAGE_OBJECT->setAddTab();
    
    $OBJECT_TREE->objectTitle = CLASSES;
    $OBJECT_TREE->isAsyncTreeNode = false;
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));
    $OBJECT_TREE->setBaseParams("
    	cmd: 'allClasses'
        ,gradeschoolyearId: '".$this->gradeschoolyearId."'
    ");
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            },
            items: [{
                title: ''
                ,collapsible: true
                ,region:'west'
                ,id: 'west'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width: 270
                ,minSize: 270
                ,maxSize: 270
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
            },{
                title: ''
                ,id: 'center'
                ,collapsible: false
                ,region:'center'
                ,margins: '3 3 3 0'
                ,id: 'center'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    border: false
                    ,layout: 'anchor'
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items: [{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                    }]
                }]
            }]
        }]
    });
    
    var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('click', function(node, e){
    	
        if(node.isLeaf()){
            if (node.attributes.type == 1){
                var targetURL = '<?=$this->URL_EVENT_SETTING?>&academicId=' + node.attributes.academicId;
                clickOpenPage('center', node.attributes.title, targetURL);
            }
            if (node.attributes.type == 2){
                var targetURL = '<?=$this->URL_DAY_EVENT_LIST?>&academicId=' + node.attributes.academicId;
                clickOpenPage('center', node.attributes.title, targetURL);
            }
        }
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>