<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

    Ext.onReady(function() {

        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $VIEW_ITEMS = "
        [{
            title: '".DAY_SCHEDULE."'
            /*,iconCls: 'icon-tabs'*/
            ,border: false
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'DAY_SCHEDULE', url: '/schedule/trainingscheduleday/?objectId=".$objectId."'})]
        },{
            title: '".WEEK_SCHEDULE."'
            /*,iconCls: 'icon-tabs'*/
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'WEEK_SCHEDULE', url: '/schedule/trainingscheduleweek/?objectId=".$objectId."'})]
        }]
        ";
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'panel'
                ,layout: 'fit'
                ,border: false
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,enableTabScroll:true
                    ,plain: true
                    ,activeTab: 0
                    ,items: <?=$VIEW_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>