<?
require_once 'clients/app_admin/AdminPage.php';
require_once 'clients/app_admin/AdminForm.php';
require_once 'clients/app_admin/AdminGrid.php';
require_once 'clients/app_admin/AdminField.php';
require_once 'clients/app_admin/AdminBar.php';
require_once 'clients/app_admin/AdminTree.php';
require_once 'clients/app_admin/AdminPage.php';

$CAMEMIS_PAGE = AdminPage::getInstance();
$OBJECT_FORM = new AdminForm("CUSTOMER");
$OBJECT_FORM->setURL("/app/");

$parentId = isset($_GET['parentId'])?$_GET['parentId']:0;

print $CAMEMIS_PAGE->showCamemisHeader();

?>
<script>
    var parentId =<?=$parentId;?>;
    Ext.onReady(function() {
        
        Ext.form.Field.prototype.msgTarget = 'side';
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE->setExtDefaultGif();
        
        $DETAIL_INFORMATION = "
        {
            title: 'Detail information'
            ,autoHeight: true
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#EEE;padding:10px; font-weight: bold;'
                ,items: [
                    {".AdminField::Displayfield("PARENT_NAME", "<b>Name of Parent</b>", false)."}    
                    ,{".AdminField::Textfield("CONST_RIGHT", "CONST_RIGHT", 'Const Right')."}
                    ,{".AdminField::Textfield("USER_RIGHT", "USER_RIGHT", 'User Right')."}    
                    ,{".AdminField::Displayfield("DEFAULT_ROLE", "Default role", false)."}    
                    ,{".AdminField::ComboObjectType('Object Type')."}
                    ,{".AdminField::Textfield("ICON", "ICON", 'Icon')."}
                    ,{".AdminField::Numberfield("CHECKED", "CHECKED", "Checked (0 or 1)", false, false, false)."}    
                    ,{".AdminField::Numberfield("SORTKEY", "SORTKEY", "Sortkey", false, false, false)."}
                ]
            }]
        }
        ";
        
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: [".$DETAIL_INFORMATION."]
        ";
        $OBJECT_FORM->addObjectItems($items);

        $OBJECT_FORM->addTBarItems("
            text: 'Cancel'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('SHOW_ITEM').disable();
                window.parent.Ext.getCmp('west').expand();
            }
        ");
         
        if($this->objectId!="new")
        if(!AdminAppDBAccess::checkChild($this->objectId)){
            $OBJECT_FORM->addTBarItems(AdminBar::tbarSingleRemove());
        }
        $OBJECT_FORM->addTBarItems(AdminBar::tbarSingleSave());
        
        $OBJECT_FORM->setLoadParams("cmd: 'jsonLoadAppRight',objectId: '".$this->objectId."'");
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonSaveAppRight'
            ,objectId: '".$this->objectId."'
            ,parentId: '".$parentId."'
        ");
        
        $OBJECT_FORM->setRemoveParams("
            cmd: 'jsonDeleteAppRight'
            ,objectId: '".$this->objectId."'
        ");
        
        $OBJECT_FORM->setonEmbeddedEvents("
            
            if(parentId){
                myNode = window.parent.Ext.getCmp('TREE.RIGHT_LIST_ID').getNodeById(parentId);
                if(myNode){
                    myNode.reload();
                    myNode.expand(true, false);
                    window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                }
                
            }else{
                var result = Ext.util.JSON.decode(action.response.responseText);
                window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
                window.parent.Ext.getCmp('TREE.RIGHT_LIST_ID').root.reload();
                window.parent.Ext.getCmp('TREE.RIGHT_LIST_ID').getRootNode().expand(true, false);
            }

        ");
        
        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            
            if(parentId){
                myNode = window.parent.Ext.getCmp('TREE.RIGHT_LIST_ID').getNodeById(parentId);
                if(myNode){
                    myNode.reload();
                    myNode.expand(true, false); 
                    window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                }
                
            }else{
                window.parent.Ext.getCmp('TREE.RIGHT_LIST_ID').root.reload();
                window.parent.Ext.getCmp('TREE.RIGHT_LIST_ID').getRootNode().expand(true, false);
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            }
        ");
        
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->isObjectDefaultOnLoad = true;
        $OBJECT_FORM->renderJS();
        ?>
                
        viewport = new Ext.Viewport({
            layout:'fit'
            ,border: false
            ,items: [{
                layout:'fit'
                ,border: false
                ,items:[{xtype: '<?= $OBJECT_FORM->getObjectXtype(); ?>'}]
            }]
        });
    });
</script>
<?
$a = Zend_Registry::getInstance();
print $CAMEMIS_PAGE->showCamemisFooter();
?>