<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'clients/CamemisViewport.php';
require_once 'models/UserAuth.php';
require_once 'models/app_school/LocationDBAccess.php';
require_once 'models/app_school/student/StudentDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$OBJECT_GRID = new CamemisGrid("DELETE_PAYMENTS", "LIST");
$OBJECT_GRID->setLoadUrl("/finance/jsonload/");
$OBJECT_GRID->setSaveUrl("/finance/jsonsave/");
$columndata = Utiles::getGridColumnData("DELETE_PAYMENTS_LIST_ID");

?>
<script>
Ext.onReady(function() {

    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#333; padding: 5px;">' + value + '</div>';
    }
    
    function cssTextPaid(value, metadata, record){
        var name = record.data.STUDENT;
        //metadata.attr = 'ext:qtip="' + name + '"';
        return '<div style="font-weight:bold; color:#061f83; padding: 5px; background:#FFF;">' + value + '</div>';
    }
    
    function cssTextOwed(value, metadata, record){
        var name = record.data.STUDENT;
        //metadata.attr = 'ext:qtip="' + name + '"';
        return '<div style="font-weight:bold; color:#e24f43; padding: 5px; background:#FFF;">' + value + '</div>';
    }
    
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addReadField("name: 'ASSIGNED'");
    $OBJECT_GRID->addReadField("name: 'FEE_NAME'");
    $OBJECT_GRID->addReadField("name: 'TRANSACTION_NUMBER'");
    $OBJECT_GRID->addReadField("name: 'AMOUNT'");
    $OBJECT_GRID->addReadField("name: 'STATUS'");
    $OBJECT_GRID->addReadField("name: 'INCOME_AMOUNT'");
    $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");
    $OBJECT_GRID->addColumn("
        xtype: 'checkboxcolumn'
        ,header: '<b>".REMOVE."</b>'
        ,align:'center'
        ,dataIndex: 'ASSIGNED'
        ,width:80
        ,on: 1
        ,off: 0
    ");
    
    $OBJECT_GRID->addColumn("header: '<b>".FEE_NAME."</b>', align:'left', renderer: cssText, width: 250, hidden:".checkColHidden(1, $columndata).", sortable: true, dataIndex: 'FEE_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".TRANSACTION_NUMBER."</b>', align:'right', renderer: cssTextPaid, width: 120, hidden:".checkColHidden(2, $columndata).", sortable: true, dataIndex: 'TRANSACTION_NUMBER'");
    //$OBJECT_GRID->addColumn("header: '<b>".AMOUNT."</b>', align:'right', renderer: cssTextOwed, width: 120, sortable: true, dataIndex: 'AMOUNT'");
    //$OBJECT_GRID->addColumn("header: '<b>".TOTAL."</b>', align:'right', renderer: cssTextOwed, width: 120, sortable: true, dataIndex: 'INCOME_AMOUNT'");
    $OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', renderer: cssTextOwed, width: 400, hidden:".checkColHidden(3, $columndata).", sortable: true, dataIndex: 'STATUS'");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_DATE."</b>', align:'right', renderer: cssText, width: 150, hidden:".checkColHidden(4, $columndata).", sortable: true, dataIndex: 'CREATED_DATE'");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonListStudentPayments'
        ,objectId:'".$this->objectId."'
        ,feeId:'".$this->fee."'
    ";
    
    $OBJECT_GRID->setSaveParams("
        cmd: 'removeStudentPayment'
        ,objectId:'".$this->objectId."'
        ,feeId:'".$this->fee."'
        ,type: '".$this->type."'
    ");
    
    $OBJECT_GRID->setAftereditCallback("
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
        Ext.getCmp('DELETE_PAYMENTS_LIST_ID').store.reload();
        window.parent.Ext.getCmp('FINANCE_LIST_ID').store.reload();
    ");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            }
        }]);
    ");
    
    $OBJECT_GRID->isPagingToolbar = true;
    $OBJECT_GRID->isGridEditing = true;
    $OBJECT_GRID->loadMask = false;
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'fit'
            ,border: false
            ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}]
        }]
    });
    Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>