<?
///////////////////////////////////////////////////////////
// @Sor Veasna
// Date: 23.05.2013
// 
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("FINANCE", "LIST");
$OBJECT_GRID->setLoadUrl("/finance/jsonload/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

Ext.onReady(function() {
    
    function cssTextBold(value, metadata, record){
        return '<div style="font-weight:normal; color:#3B5998; padding: 5px;">' + value + '</div>';
    }
    
    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#333; padding:3px;">' + value + '</div>';
    }
    
    function cssNumber(value, metadata, record){
        return '<div style="font-weight:bold; color:#3B5998; padding: 5px;">' + value + '</div>';
    }
        
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
     
    $OBJECT_GRID->addReadField("name: 'STUDENT_NAME'");
    $OBJECT_GRID->addReadField("name: 'CODE_ID'");
    $OBJECT_GRID->addReadField("name: 'LASTNAME'");
    $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
    $OBJECT_GRID->addReadField("name: 'STUDENT_CODE'");
    $OBJECT_GRID->addReadField("name: 'GENDER'");
    $OBJECT_GRID->addReadField("name: 'PHONE'");
    $OBJECT_GRID->addReadField("name: 'PAID_STATUS'");
    $OBJECT_GRID->addReadField("name: 'STUDENT_FEE_ID'");
    $OBJECT_GRID->addReadField("name: 'END_DATE'");
    $OBJECT_GRID->addReadField("name: 'FIRST_DUE_DATE_A'");
    
    $OBJECT_GRID->addColumn("header: '<b>".CODE."</b>', align:'right', renderer: cssNumber, width:80, sortable: true, dataIndex: 'STUDENT_CODE'");
    if(!SchoolDBAccess::displayPersonNameInGrid()){
        $OBJECT_GRID->addColumn("header: '<b>".LASTNAME."</b>', align:'left', renderer: cssText, width: 120, sortable: true, dataIndex: 'LASTNAME'");
        $OBJECT_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', align:'left', renderer: cssText, width: 120, sortable: true, dataIndex: 'FIRSTNAME'");
    }else{
        $OBJECT_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', align:'left', renderer: cssText, width: 120, sortable: true, dataIndex: 'FIRSTNAME'");
        $OBJECT_GRID->addColumn("header: '<b>".LASTNAME."</b>', align:'left', renderer: cssText, width: 120, sortable: true, dataIndex: 'LASTNAME'");
    }
    $OBJECT_GRID->addColumn("header: '<b>".PAYMENT_REMINDER."</b>', align:'left', renderer: cssTextBold, width: 120, sortable: true, dataIndex: 'FIRST_DUE_DATE_A'");
    $OBJECT_GRID->addColumn("header: '<b>".PAYMENT_STATUS."</b>', align:'left', renderer: cssTextBold, width: 120, sortable: true, dataIndex: 'PAID_STATUS'");
    
        
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'COMMUNICATION_ID'
            ,text: '".COMMUNICATION."'
            ,iconCls:'icon-email_add'
            ,scope:this
            ,disabled: false
            ,handler: function(){
                var selids = '';
                var seltexts = '';
                var sels = Ext.getCmp('FINANCE_LIST_ID').getSelectionModel().getSelections();
                for( var i = 0; i < sels.length; i++ ) {
                    if (i >0) selids += ',';
                    selids += sels[i].get('CODE_ID');
                    if (i >0) seltexts += ',';
                    seltexts += i+1 + ') ' + sels[i].get('LASTNAME') +' '+ sels[i].get('FIRSTNAME');
                }
                var url='".$this->URL_STUDENT_SEND_REMINDER."&objectId='+selids+'&objectName='+seltexts+'&fee=".$this->objectId."';
                clickOpenPage('center','Reminder Student',url);
                
        }
        }]);
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonLoadStudentFeeTraining'
        ,feeID: '".$this->objectId."'
    ";
    
    $OBJECT_GRID->isQuickySearch=true; 
    $OBJECT_GRID->isCheckboxSelect=true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,xtype: 'panel'
            ,layout: 'card'
            ,id: 'center'
            ,activeItem: 0
            ,items:[{
                border: false
                ,title: ''
                ,layout: 'fit'
                ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
            }]
        }]
    });
    
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>