<?
///////////////////////////////////////////////////////////
// @Sor Veasna
// Date: 30-05-2013
// 
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("COMMUNICATION");
$OBJECT_FORM->setLoadUrl('/communication/jsonload/');
$OBJECT_FORM->setSaveUrl('/communication/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
         
        $SUBJECT_EMAIL = "
        {
            title: '".SUBJECT_EMAIL."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,bodyStyle: 'padding:5px'
                ,items: [{".CamemisField::Textarea("SUBJECT", false,50, false, true)."}]
            },{
                layout: 'form'
                ,border: false
                ,bodyStyle: 'padding:5px'
                ,items: [
                    {".CamemisField::Hidden("STR_RECIPIENT",false)."}
                ]
            }]
        }
        ";
        
        $RECIPIENT = "
        {
            title: '".RECIPIENT."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,bodyStyle: 'padding:5px'
                ,items: [{".CamemisField::Textarea("STR_RECIPIENT_NAME", false,150, true, true)."}]
            }]
        }";
        
        $CONTENT = "
        {
            title: '".CONTENT."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,bodyStyle: 'padding:5px'
                ,items:[{".CamemisField::HTML("CONTENT",false,false)."}]
            }]
        }
        ";
        
        $ITEMS = "[";
            $ITEMS .= $SUBJECT_EMAIL;
            $ITEMS .= ",".$RECIPIENT; 
             $ITEMS .= ",".$CONTENT;             
        $ITEMS .= "]";
        
        $FORM_ITEMS = "
        border: false
        ,id: 'FORM_ITEMS'
        ,width: 550
        ,bodyStyle: 'padding:0px'
        ,items: ".$ITEMS."
        ";
        
        $OBJECT_FORM->addObjectItems($FORM_ITEMS);

        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            }
        ");

        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetSend());
        
        $OBJECT_FORM->setSendParams("
            cmd: 'jsonSaveAlertFeeCommunication'
            ,fee: '".$this->feeId."'
            ,communication_type: 'TEACHER_TO_STUDENTS'
            ,recipient_type: 'STUDENT'
            ,sender_type: 'STAFF'
            ,action: 'SEND'
        "); 

        $OBJECT_FORM->setOnEmbeddedSendEvents("
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            window.parent.Ext.getCmp('FINANCE_LIST_ID').store.reload();
        ");

        $OBJECT_FORM->isObjectDefaultOnLoad=false;
        $OBJECT_FORM->isObjectSend = true;
        $OBJECT_FORM->labelAlign = "top";
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,id: 'content'
                ,title: ''
                ,layout: 'card'
                ,activeItem: 0
                ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
            }]
        });
    
    Ext.getCmp('STR_RECIPIENT_NAME_ID').setValue('<?=$this->objectName;?>'); 
    Ext.getCmp('STR_RECIPIENT').setValue('<?=$this->str_recipient_id;?>');  
    });
</script>
<?                                                                    
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>