<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 22.12.2012
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("DEPARTMENT", "LIST");
$OBJECT_TREE->setURL("/department/jsontree/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
	
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));
    $OBJECT_TREE->setBaseParams("
    	cmd: 'jsonTreeAllDepartments'
    ");
    
    $OBJECT_TREE->addTBarItems("
        id: 'FACULTY_OR_DEPARTMENT'
        ,tooltip:'".FACULTY_OR_DEPARTMENT."'
        ,scope:this
        ,iconCls:'icon-application_form_add'
        ,handler: function(){
            clickOpenPage('center','".FACULTY_OR_DEPARTMENT."', '".$this->URL_SHOWITEM."&objectId=new&parent=0');    
        }
    ");
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{
               	region:'west'
                ,title:'<?=FACULTY_OR_DEPARTMENT;?>'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width:280
                ,minSize:280
                ,maxSize:280
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    border: false
                    ,layout: 'anchor'
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items: [{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                    }]
                }]
            }]
        }]
    });
    
    var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('click', function(node, e){
        var contextMenu = new Ext.menu.Menu({
            items: [{
                text: '<?=SHOW_DETAIL;?>'
                ,iconCls:'icon-application_form_magnify'
                ,handler:function(){
                    clickOpenPage('center','<?=SHOW_DETAIL?> &raquo; ' + node.text, '<?=$this->URL_SHOWITEM;?>objectId=' + node.id);
                }
            },{
                text: '<?=ADD_A_NEW_ITEM;?>'
                ,iconCls:'icon-application_form_add'
                ,handler: function(){
                    clickOpenPage('center','<?=ADD_A_NEW_ITEM?>', '<?=$this->URL_SHOWITEM?>objectId=new&parentId=' + node.id);
                }
            }]
        });
        e.stopEvent();
        contextMenu.showAt(e.xy);
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>