<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("DATASET");
$OBJECT_FORM->setSaveUrl("/dataset/jsonsave/");
$OBJECT_FORM->setLoadUrl("/dataset/jsonload/");

$parentId = isset($_GET["parentId"])?addText($_GET["parentId"]):"";
$lastNode = isset($_GET["lastNode"]) ? addText($_GET["lastNode"]):"";

$parentObject = TaxDBAccess::findObjectFromId($parentId);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
	Ext.form.Field.prototype.msgTarget = 'side';
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $FORM_ITEMS = "[
        {".CamemisField::Textfield("NAME_ID", "NAME", ACCOUNT_NAME, true)."}
        ,{".CamemisField::Textfield("NUMBER", "NUMBER", ACCOUNT_NUMBER, false)."}
        ,{".CamemisField::Numberfield("PERCENT", "PERCENT", AMOUNT." (%)", false, false, false, false)."}
        ,{".CamemisField::ComboFormularTax(FORMULAR,false)."}
        ,{".CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false, false)."}
    ]"; 

    $DETAIL_INFORMATION = "
    {
        title: '".DETAIL_INFORMATION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: ".$FORM_ITEMS."
        }]
    }
    ";
    
    $DESCRIPTION = "
    {
        title: '".DESCRIPTION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,height: 100
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'padding:5px'
            ,items: [{".CamemisField::Textarea("DESCRIPTION", false,100)."}]
        }]
    }
    ";

    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: [
            ".$DETAIL_INFORMATION."
            ,".$DESCRIPTION."
        ]
    ";
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        }
    ");
    if( UserAuth::getACLValue("FINANCIAL_MANAGEMENT_EDIT_RIGHT"))
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());

    $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '".$this->objectId."',type:'tax'");
    
    if($this->objectId == "new"){
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'updateObject'
            ,type:'tax'
            ,objectId: '".$this->objectId."'
            ,parentId: '".$parentId."'
        ");
        
        if($lastNode){
            if($parentObject){
                if($parentObject->PARENT){
                    $OBJECT_FORM->setonEmbeddedEvents("
                        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                        myTree = window.parent.Ext.getCmp('TREE.DATASET_LIST_ID');
                        myNode = myTree.getNodeById('".$parentObject->PARENT."');
                        myNode.reload();
                        myNode.expand(true, false);
                    ");
                }else{
                    $OBJECT_FORM->setonEmbeddedEvents("
                        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                        window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.reload();
                        window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.expand(true, false);
                    "); 
                }
            }
        }else{
            if($parentId){
                $OBJECT_FORM->setonEmbeddedEvents("
                    window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                    XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                    myTree = window.parent.Ext.getCmp('TREE.DATASET_LIST_ID');
                    myNode = myTree.getNodeById('".$parentId."');
                    myNode.reload();
                    myNode.expand(true, false);
                ");
            }else{
                $OBJECT_FORM->setonEmbeddedEvents("
                    window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                    window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.reload();
                    window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.expand(true, false);
                "); 
            }
        }
        
    }else{
        if(!$this->check){
            if( UserAuth::getACLValue("FINANCIAL_MANAGEMENT_REMOVE_RIGHT"))
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormEasyRemoveObject());
        }
        $OBJECT_FORM->setSaveParams("
            cmd: 'updateObject'
            ,type:'tax'
            ,objectId: '".$this->objectId."'
        ");
        
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('TREE.DATASET_LIST_ID');
            myNode = myTree.getNodeById('".$this->facette->PARENT."');
            myNode.reload();
            myNode.expand(true, false);
        ");
        
        $OBJECT_FORM->setRemoveParams("
            cmd: 'removeObject'
            ,type:'tax'
            ,objectId: '".$this->objectId."'
        ");

        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            window.parent.Ext.getCmp('TREE.DATASET_LIST_ID').root.reload();
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");
    }
    	
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>