<html>
    <head>
        <title><?= Zend_Registry::get('TITLE');?></title>
        <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/css/main.css" />
        <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/css/login.css" />
        <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/resources/css/ext-all.css" />
        <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/plugin/Cookies.js"></script>
        <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/adapter/ext/ext-base.js"></script>
        <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/ext-all.js"></script>
        <script type="text/javascript">
            
            Ext.SSL_SECURE_URL="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/resources/images/default/s.gif";
            Ext.BLANK_IMAGE_URL="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/resources/images/default/s.gif";
            
            Login = function(){
                var win,
                form,
                submitUrl = 'remote/';
                function onSubmit(){
                    this.showMask();
                    form.submit({
                        reset: true
                    });
                }
                return{
                    Init:function(){
                        Ext.QuickTips.init();

                        var logoPanel = new Ext.Panel({
                            baseCls: 'x-plain'
                            ,id: 'login-logo-default'
                            ,bodyStyle: 'padding:10px'
                            ,qtip:'Vikensoft Admin-Tool'
                            ,region: 'center'
                        });

                        var formPanel = new Ext.form.FormPanel({
                            baseCls: 'x-plain',
                            baseParams: {
                                module: 'login'
                            },
                            defaults: {
                                width: 200
                                ,border: false
                            },
                            defaultType: 'textfield',
                            frame: false,
                            height: 120,
                            id: 'login-form',
                            items: [{
                                fieldLabel: '<b>Login-Name</b>'
                                ,name: 'login'
                                ,anchor: '95%'
                                ,value: ''
                            },{
                                fieldLabel: '<b>Password</b>'
                                ,inputType: 'password'
                                ,name: 'password'
                                ,anchor: '95%'
                                ,value: ''
                            }],
                            labelWidth:115,
                            listeners: {
                                'actioncomplete': {
                                    fn: this.onActionComplete,
                                    scope: this
                                    },
                                        'actionfailed': {
                                            fn: this.onActionFailed,
                                            scope: this
                                        }
                                    },
                                    region: 'south',
                                    url: submitUrl
                                });
                                win = new Ext.Window({
                                    buttons: [{
                                        handler: onSubmit,
                                        scope: Login,
                                        text: 'Login'
                                    }],
                                    buttonAlign: 'right',
                                    closable: false,
                                    draggable: false,
                                    height: 240,
                                    id: 'login-win',
                                    keys: {
                                        key: [13], // enter key
                                        fn: onSubmit,
                                        scope:this
                                    },
                                    layout: 'border',
                                    minHeight: 210,
                                    minWidth: 430,
                                    plain: false,
                                    resizable: false,
                                    items: [
                                        logoPanel,
                                        formPanel
                                    ],
                                    title: 'Vikensoft - Admin-Tool Login',
                                    width: 430
                                });
                                form = formPanel.getForm();
                                formPanel.on('render', function(){
                                    var f = form.findField('user');
                                    if(f){
                                        f.focus();
                                    }
                                }, this, {delay: 200});
                                win.show();
                                },
                                hideMask : function(){
                                    this.pMask.hide();
                                    win.buttons[0].enable();
                                },
                                onActionComplete : function(f, a){
                                    this.hideMask();
                                    if(a && a.result){
                                        win.destroy(true);
                                        var path = window.location.pathname,
                                        path = path.substring(0, path.lastIndexOf('/') + 1);
                                        set_cookie('tokenId', a.result.sessionId, '', path, '', '' );
                                        set_cookie('languageId', a.result.languageId, '', path, '', '' );

                                        switch(a.result.sessionId){
                                            case 'failed':
                                                Ext.MessageBox.show({
                                                    title: 'Your authentication has failed.',
                                                    msg: 'Please verify your Loging-Name and Password are correct.',
                                                    width:300,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.WARNING,
                                                    fn: function(btn){
                                                        if (btn == 'ok'){
                                                            window.location = path;
                                                        }
                                                    }
                                                });
                                                break;
                                            case 'online':
                                                Ext.MessageBox.show({
                                                    title: 'User is online...',
                                                    msg: 'User is online...<br><br>This user is already logged in the system.',
                                                    width:300,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.WARNING,
                                                    fn: function(btn){
                                                        if (btn == 'ok'){
                                                            window.location = path;
                                                        }
                                                    }
                                                });
                                            break;
                                            default:
                                                window.location = path+"main/?welcome";
                                                break;
                                        }
                                    }
                                },
                                onActionFailed : function(){
                                    this.hideMask();
                                },
                                showMask : function(msg){
                                    if(!this.pMask){
                                        this.pMask = new Ext.LoadMask(win.body, {
                                        msg: 'CAMEMIS please wait...'
                                    });
                                }
                                if(msg){
                                    this.pMask.msg = msg;
                                }
                                this.pMask.show();
                                win.buttons[0].disable();
                            }
                        };
                    }();
                    Ext.onReady(Login.Init, Login, true);
        </script>

    </head>
    <body bgcolor="#FFFFFF">
   
    </body>
</html>