<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 22.10.2010
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisSchoolTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_university/AcademicDateDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("STUDENT");
$OBJECT_FORM->setLoadUrl('/student/jsonload/');
$OBJECT_FORM->setSaveUrl('/student/jsonsave/');

$olacademicId = isset($_GET["academicId"])? (int) $_GET["academicId"]:"";
$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";

$facette = AcademicDBAccess::findGradeFromId($olacademicId);

if(!$facette) {header("Location: /main/permission/");exit;}

$gradeId = $facette->GRADE_ID;
$schoolyearId = $facette->SCHOOL_YEAR;

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

    var schoolyearId = "<?=$schoolyearId?>";
    var olacademicId = "<?=$olacademicId?>";
    var gradeId = "<?=$gradeId?>";
    var objectId = "<?=$objectId?>";

    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $academicObject = new CamemisDynCombo("ACADEMIC","COMBO_CLASS");
        $academicObject->setLoadUrl('/academic/jsonload/');
        $academicObject->objectTitle = NEW_CLASS;
        $academicObject->allowBlank = "false";
        $academicObject->varName = "newacademicId";
        $academicObject->renderJS();

        $DETAIL_INFORMATION = "
        {
            title: '".CLASS_TRANSFER."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 400
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {xtype: '".$academicObject->getObjectXType()."'}
                ]
            }]
        }
        ";
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonActionStudentClassTransfer'
            ,objectId: objectId
            ,schoolyearId: schoolyearId
            ,olacademicId: olacademicId
        ");

        $OBJECT_FORM->setonEmbeddedEvents("
            window.parent.Ext.getCmp('STUDENT_ENROLLED_STUDENTS_ID').store.reload();
            window.parent.Ext.getCmp('OPEN_WIN_IFRAME_ID').close();
        ");

        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,width: 400
            ,bodyStyle: 'padding:0px'
            ,items: [
                " . $DETAIL_INFORMATION . "
            ]
        ";
        $OBJECT_FORM->addObjectItems($items);
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        ");
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->renderJS();
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                layout:'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        });
        
        Ext.getCmp('COMBO_CLASS_ID').store.baseParams = {
            start:0
            ,limit:100
            ,cmd: 'jsonSearchGrade'
            ,schoolyearId: schoolyearId
            ,gradeId: gradeId
            ,searchType: 'CLASS'
        };
        
        Ext.getCmp('COMBO_CLASS_ID').store.load();
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>