<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("STUDENT");
$OBJECT_FORM->setLoadUrl('/student/jsonload/');
$OBJECT_FORM->setSaveUrl('/student/jsonsave/');

$refresh = isset($_GET["refresh"]) ? addText($_GET["refresh"]):"";
$facette = StudentDBAccess::findStudentFromId($this->objectId);

if(!$facette) {header("Location: /main/permission/");exit;}

$LOGINNAME = $facette->LOGINNAME?$facette->LOGINNAME:"---";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<script>

Ext.onReady(function() {
    Ext.apply(Ext.form.VTypes, {
        password : function(val, field) {
            if (field.initialPassField) {
                var pwd = Ext.getCmp(field.initialPassField);
                return (val == pwd.getValue());
            }
            return true;
        },
        passwordText :'<?=PASSWORDS_ARE_DIFFERENT;?>'
    });
    Ext.form.Field.prototype.msgTarget = 'side';
    <?
    /**
     * Extjs: s.gif
     */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    $CHANGE_PASSWORD_ITEM = "{".CamemisField::Displayfield("OLD_LOGINNAME",LOGINNAME,$LOGINNAME)."}";
    $CHANGE_PASSWORD_ITEM .= ",{fieldLabel: '".NEW_LOGINNAME."',width: 250,xtype: 'textfield',name: 'LOGINNAME',id: 'LOGINNAME',allowBlank: true}";
    $CHANGE_PASSWORD_ITEM .= ",{fieldLabel: '".PASSWORD."',width: 250,xtype: 'textfield',name: 'PASSWORD',id: 'PASSWORD',inputType: 'password',allowBlank: true}";
    $CHANGE_PASSWORD_ITEM .= ",{fieldLabel: '".PASSWORD_REPEAT."',width: 250,xtype: 'textfield',name: 'PASSWORD_REPEAT',vtype: 'password',initialPassField: 'PASSWORD',inputType: 'password',allowBlank: true}";
    
    if(UserAuth::getACLValue("SYSTEM_USER_EDIT_RIGHT")){
        if(!UserAuth::myObject($this->objectId)){
            $CHANGE_PASSWORD_ITEM .= ",{".CamemisField::Checkbox("UMCPANL","UMCPANL", USER_MUST_CHANGE_PASSWORD_AT_NEXT_LOGIN, 1, false)."}";
            $CHANGE_PASSWORD_ITEM .= ",{".CamemisField::Checkbox("UCNCP","UCNCP", USER_CAN_NOT_CHANGE_PASSWORD, 1, false)."}";
        }
    }
    
    $CHANGE_PASSWORD = "
        title: ''
        ,border: false
        ,items:[{
            layout: 'form'
            ,border: false
            ,bodyStyle: 'padding:10px;'
            ,style: 'padding-bottom:10px'
            ,items: [".$CHANGE_PASSWORD_ITEM."]
        }]
    ";
        
    $ITEMS = "[";
    $ITEMS .= "{".$CHANGE_PASSWORD."}";
    $ITEMS .= "]";
    $formItems = "
        border: false
        ,layout: 'form'
        ,bodyStyle: 'padding:10px'
        ,items: ".$ITEMS."
    ";
    switch(UserAuth::getUserType()){
        case"STUDENT":
        if(UserAuth::getACLValue("PERSONAL_INFORMATION_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        break;
    }
    
    if(UserAuth::isSuperAdmin()){
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    }else{
        if(!$facette->UCNCP){
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        }
    }
    $OBJECT_FORM->addObjectItems($formItems);

    $OBJECT_FORM->setSaveParams("
        cmd: 'updateObject'
        ,objectId: '".$this->objectId."'
    ");

    switch($refresh){
        case "main":
            $GoTo = "/main/";
            break;
        default:
            $GoTo = "/student/student/?objectId=".$this->objectId."";
            break;
    }
    
    $OBJECT_FORM->setonEmbeddedEvents("   
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
        window.parent.window.location='".$GoTo."';
    ");
    $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '".$this->objectId."'");
    $OBJECT_FORM->bodyStyle = "padding:0px";
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 150;
    $OBJECT_FORM->isObjectDefaultOnLoad = true;
    $OBJECT_FORM->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,id: 'content'
            ,title: ''
            ,layout: 'card'
            ,activeItem: 0
            ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>