<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
  
$classObject = AcademicDBAccess::findGradeFromId($this->classId);

if(!$classObject) {header("Location: /main/permission/");exit;}
    
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();  
        
        $PANEL_ITEMS = array(); 

        $ATTENDANCE_INFORMATION = "{
            title: '".ATTENDANCE_INFORMATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ATTENDANCE_INFORMATION', url: '/attendance/studentclassmain/?target=general&classId=".$classObject->ID."&teacherId=".$this->objectId."'})]
        }";
        $PANEL_ITEMS[] = "" . $ATTENDANCE_INFORMATION . "";
        
        $SCHEDULE = "{
            title: '".SCHEDULE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SCHEDULE', url: '/schedule/byclass/?academicId=".$classObject->ID."'})]
        }";
        $PANEL_ITEMS[] = "" . $SCHEDULE . "";
        
        $EVENT = "{
            title: '".EVENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'EVENT', url: '/schoolevent/classevents/?target=general&classId=".$this->classId."'})]
        }";
        $PANEL_ITEMS[] = "" . $EVENT . "";
        
        $HOMEWORK = "{
            title: '".HOMEWORK."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'HOMEWORK', url: '/homework/homeworkmain/?classId=".$classObject->ID."&gradeId=".$classObject->GRADE_ID."&schoolyearId=".$classObject->SCHOOL_YEAR."&teacherId=".$this->objectId."'})]
        }";
        
        $PANEL_ITEMS[] = "" . $HOMEWORK . "";
        
        $SUBJECT= "{
            title: '".SUBJECT_LIST."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ALL_SUBJECTS', url: '/subject/byclass/?target=general&classId=".$classObject->ID."&gradeId=".$classObject->GRADE_ID."&schoolyearId=".$classObject->SCHOOL_YEAR."&teacherId=".$this->objectId."'})]
        }";
        
        $PANEL_ITEMS[] = "" . $SUBJECT . "";
        
        $TEACHING_REPORT= "{
            title: '".TEACHING_REPORT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'TEACHING_REPORT', url: '/subjectreport/subjectreportmain/?classId=".$this->classId."&teacherId=".$this->objectId."'})]
        }";
        $PANEL_ITEMS[] = "" . $TEACHING_REPORT . "";
        
        $ASSESSMENT = "{
            title: '".ASSESSMENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ASSESSMENT', url: '/academic/scoremonitor/?classId=".$this->classId."&teacherId=".$this->objectId."'})]
        }";
        $PANEL_ITEMS[] = "" . $ASSESSMENT . "";
        
        $DISCIPLINE_INFORMATION = "{
            title: '".DISCIPLINE_INFORMATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'DISCIPLINE_INFORMATION', url: '/discipline/byclass/?target=general&classId=".$classObject->ID."'})]
        }";
        $PANEL_ITEMS[] = "" . $DISCIPLINE_INFORMATION . "";
        
        $LIST_OF_STUDENTS = "{
            title: '".LIST_OF_STUDENTS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'LIST_OF_STUDENTS', url: '/academic/studentlist?objectId=".$classObject->ID."'})]
        }";
        $PANEL_ITEMS[] = "" . $LIST_OF_STUDENTS . "";
        
        $LIST_OF_TEACHERS = "{
            title: '".LIST_OF_TEACHERS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'LIST_OF_TEACHERS', url: '/academic/teachersbyclass/?objectId=".$classObject->ID."'})]
        }";
        $PANEL_ITEMS[] = "" . $LIST_OF_TEACHERS . "";
        
        $EXTRA_CLASS = "{
            title: '".EXTRA_CLASS."'
            ,layout: 'fit'
           ,items:[new Ext.ux.IFrameComponent({ id: 'EXTRA_CLASS', url: '/extraclass/showitem/?teacherId=".$this->objectId."'})]
        }";
        $PANEL_ITEMS[] = "" . $EXTRA_CLASS . "";
        
        $CHOOSE_ITEMS = "[".implode(',',$PANEL_ITEMS)."]";  
         
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false 
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false 
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true   
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>