<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////        
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
  
$classObject = AcademicDBAccess::findGradeFromId($this->classId);

if(!$classObject) {header("Location: /main/permission/");exit;}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

//@THORN Visal
$subjectObject = AcademicDBAccess::findGradeFromId($this->classId);
$getGradeSubject = GradeSubjectDBAccess::getGradeSubject(
    false
    , $subjectObject->CAMPUS_ID
    ,$subjectObject->SUBJECT_ID
    ,$subjectObject->SCHOOL_YEAR
);

$OBJECT_TREE = new CamemisTree("STAFFS", "LIST");
$OBJECT_TREE->setURL('/staff/jsontree/');
?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();  
        
        $TREE_ITEMS = Array();
        
        if($this->classId){
            $setParamsMaincontent .= "classId=".$this->classId;
        }
        if($this->objectId){
            $setParamsMaincontent .= "&objectId=".$this->objectId;
        }
        $MAIN_CONTENT = "{";
            $MAIN_CONTENT .= "text:'".MAIN_CONTENT."'";
            $MAIN_CONTENT .= ",leaf:true";
            $MAIN_CONTENT .= ",url:'/staff/creditsystemsubjectdetail/?camIds=".$this->urlEncryp->encryptedGet($setParamsMaincontent)."'";
            $MAIN_CONTENT .= ",cls:'nodeTextBold'";
            $MAIN_CONTENT .= ",iconCls: 'icon-component'";
        $MAIN_CONTENT .= "}";
        $TREE_ITEMS[] = $MAIN_CONTENT;
        
        $setParamsAttendance = "";
        if(Zend_Registry::get('USER')->ID)
        $setParamsAttendance .= "objectId=".Zend_Registry::get('USER')->ID;
        if($classObject->ID)
        $setParamsAttendance .="&classId=".$classObject->ID;
        if($this->subjectId)/////@THORN Visal
        $setParamsAttendance .="&subjectId=".$this->subjectId;  
        $ATTENDANCE_INFORMATION = "{";
            $ATTENDANCE_INFORMATION .= "text:'".ATTENDANCE_INFORMATION."'";
            $ATTENDANCE_INFORMATION .= ",leaf:true";
            $ATTENDANCE_INFORMATION .= ",url:'/staff/creditsystemstudentattendancesetting/?".$setParamsAttendance."'";
            $ATTENDANCE_INFORMATION .= ",cls:'nodeTextBold'";
            $ATTENDANCE_INFORMATION .= ",iconCls: 'icon-component_yellow'";
        $ATTENDANCE_INFORMATION .= "}";
        $TREE_ITEMS[] = $ATTENDANCE_INFORMATION;
        
        $setParamsSchedule = "";
        if($classObject->ID)
        $setParamsSchedule .= "academicId=".$classObject->ID;
        if($this->objectId)
        $setParamsSchedule .="&teacherId=".$this->objectId;
        $SCHEDULE = "{";
            $SCHEDULE .= "text:'".SCHEDULE."'";
            $SCHEDULE .= ",leaf:true";
            $SCHEDULE .= ",url:'/schedule/byclass/?camIds=".$this->urlEncryp->encryptedGet($setParamsSchedule)."'";
            $SCHEDULE .= ",cls:'nodeTextBold'";
            $SCHEDULE .= ",iconCls: 'icon-component'";
        $SCHEDULE .= "}";
        $TREE_ITEMS[] = $SCHEDULE;
        
        /////@THORN Visal
        $setParamsEvent = "";
        $setParamsEvent .= "target=general";
        if($classObject->ID)
        $setParamsEvent .= "&classId=".$classObject->ID;
        if($this->subjectId)
        $setParamsEvent .= "&subjectId=".$this->subjectId;
        if(Zend_Registry::get('USER')->ID)
        $setParamsEvent .="&objectId=".Zend_Registry::get('USER')->ID;
        $EVENT = "{";
            $EVENT .= "text:'".EVENT."'";
            $EVENT .= ",leaf:true";
            $EVENT .= ",url:'/staff/creditsystemeventsetting/?camIds=".$this->urlEncryp->encryptedGet($setParamsEvent)."'";
            $EVENT .= ",cls:'nodeTextBold'";
            $EVENT .= ",iconCls: 'icon-component_yellow'";
        $EVENT .= "}";
        $TREE_ITEMS[] = $EVENT;
        
        $setParamsHomework = "";
        if($classObject->ID)
        $setParamsHomework .= "classId=".$classObject->ID;
        if($classObject->GRADE_ID)
        $setParamsHomework .="&gradeId=".$classObject->GRADE_ID;
        if($classObject->SCHOOL_YEAR)
        $setParamsHomework .="&schoolyearId=".$classObject->SCHOOL_YEAR;
        if($this->objectId)
        $setParamsHomework .="&objectId=".$this->objectId;
        $HOMEWORK = "{";
            $HOMEWORK .= "text:'".HOMEWORK."'";
            $HOMEWORK .= ",leaf:true";
            $HOMEWORK .= ",url:'/staff/creditsystemhomeworksetting/?camIds=".$this->urlEncryp->encryptedGet($setParamsHomework)."'";
            $HOMEWORK .= ",cls:'nodeTextBold'";
            $HOMEWORK .= ",iconCls: 'icon-component'";
        $HOMEWORK .= "}";
        $TREE_ITEMS[] = $HOMEWORK;
        
        $SUBJECT_LIST = "{";
            $SUBJECT_LIST .= "text:'".SUBJECT_LIST."'";
            $SUBJECT_LIST .= ",leaf:true";
            $SUBJECT_LIST .= ",url:'/subject/byclass/?target=general&classId=".$classObject->ID."&gradeId=".$classObject->GRADE_ID."&schoolyearId=".$classObject->SCHOOL_YEAR."&teacherId=".$this->objectId."'";
            $SUBJECT_LIST .= ",cls:'nodeTextBold'";
            $SUBJECT_LIST .= ",iconCls: 'icon-component_yellow'";
        $SUBJECT_LIST .= "}";
        $TREE_ITEMS[] = $SUBJECT_LIST;
        
        $setParamsTeachingReport = "";
        if($classObject->ID) 
        $setParamsTeachingReport = "classId=".$classObject->ID;
        if($this->objectId)
        $setParamsTeachingReport .= "&objectId=".$this->objectId;//@THORN Visal
        $TEACHING_REPORT = "{";
            $TEACHING_REPORT .= "text:'".TEACHING_REPORT."'";
            $TEACHING_REPORT .= ",leaf:true";
            $TEACHING_REPORT .= ",url:'/staff/creditsystemsubjectteachingreportsetting/?camIds=".$this->urlEncryp->encryptedGet($setParamsTeachingReport)."'";
            $TEACHING_REPORT .= ",cls:'nodeTextBold'";
            $TEACHING_REPORT .= ",iconCls: 'icon-component'";
        $TEACHING_REPORT .= "}";
        $TREE_ITEMS[] = $TEACHING_REPORT;
        
        //@THORN Visal
        $setParamsAssessment = "";
        $setParamsAssessment .= "target=general";
        if($classObject->ID)
        $setParamsAssessment .= "&classId=".$classObject->ID;
        if($this->subjectId)
        $setParamsAssessment .= "&subjectId=".$this->subjectId;
        if(Zend_Registry::get('USER')->ID)
        $setParamsAssessment .="&objectId=".Zend_Registry::get('USER')->ID;
        $ASSESSMENT = "{";
            $ASSESSMENT .= "text:'".ASSESSMENT."'";
            $ASSESSMENT .= ",leaf:true";
            $ASSESSMENT .= ",url:'/staff/creditsystemassessmentsetting/?camIds=".$this->urlEncryp->encryptedGet($setParamsAssessment)."'";
            $ASSESSMENT .= ",cls:'nodeTextBold'";
            $ASSESSMENT .= ",iconCls: 'icon-component_yellow'";
        $ASSESSMENT .= "}";
        $TREE_ITEMS[] = $ASSESSMENT;
        
        $DISCIPLINE_INFORMATION = "{";
            $DISCIPLINE_INFORMATION .= "text:'".DISCIPLINE_INFORMATION."'";
            $DISCIPLINE_INFORMATION .= ",leaf:true";
            $DISCIPLINE_INFORMATION .= ",url:'/discipline/byclass/?target=general&classId=".$classObject->ID."'";
            $DISCIPLINE_INFORMATION .= ",cls:'nodeTextBold'";
            $DISCIPLINE_INFORMATION .= ",iconCls: 'icon-component'";
        $DISCIPLINE_INFORMATION .= "}";
        $TREE_ITEMS[] = $DISCIPLINE_INFORMATION;
        
        $LIST_OF_STUDENTS = "{";
            $LIST_OF_STUDENTS .= "text:'".LIST_OF_STUDENTS."'";
            $LIST_OF_STUDENTS .= ",leaf:true";
            $LIST_OF_STUDENTS .= ",url:'/staff/creditsystemstudentsetting?classId=".$classObject->ID."'";
            $LIST_OF_STUDENTS .= ",cls:'nodeTextBold'";
            $LIST_OF_STUDENTS .= ",iconCls: 'icon-component_yellow'";
        $LIST_OF_STUDENTS .= "}";
        $TREE_ITEMS[] = $LIST_OF_STUDENTS;
        
        $CHOOSE_ITEMS = "[".implode(',',$TREE_ITEMS)."]";
        
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isAsyncTreeNode = true;
        $OBJECT_TREE->setAsyncTreeNode($CHOOSE_ITEMS);
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible:true
                    ,split: true
                }
                ,items: [{
                    title: ''
                    ,id:'WEST_ID'
                    ,region:'west'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width:200
                    ,minSize:200
                    ,maxSize:200
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                },{
                    title: ''
                    ,border:true
                    ,collapsible: false
                    ,region:'center'
                    ,id: 'center'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,margins: '3 3 3 0'
                    ,items: [new Ext.ux.IFrameComponent({ id: 'MAIN_CONTENT', url:'/staff/creditsystemsubjectdetail/?camIds=<?=$this->urlEncryp->encryptedGet($setParamsMaincontent)?>'})]
                }]
            }]
        });
        
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node, event){
            clickOpenPage('center','',node.attributes.url);
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>