<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("INCOME");
$CATEGORY_TREE = new CamemisTree("DATASET","LIST");
$CATEGORY_TREE->setURL("/dataset/jsontree/");
$CATEGORY_TREE->setSaveUrl("/dataset/jsonsave/");

$OBJECT_FORM ->setSaveUrl("/finance/jsonsave/");
$OBJECT_FORM ->setLoadUrl("/finance/jsonload/");

$studentId = $this->facette?$this->facette->STUDENT:"";
$studentObject = StudentDBAccess::findStudentFromId($studentId);

$collapsed = $this->facette?"false":"false";

$entriesParentCheckbox = FinanceDescriptionDBAccess::sqlDescription(false, 1, 1);
$CHECKBOX_JS = "";
$CHECKBOX_DATA = array();
$CHECKBOX_ITEMS = array();
if($entriesParentCheckbox){
    foreach($entriesParentCheckbox as $value){
        if(FinanceDescriptionDBAccess::checkChild($value->ID)){
            $entries = FinanceDescriptionDBAccess::sqlDescription($value->ID, 1, 1);
            $CHECKBOX_JS .= "var CHECKBOX_$value->ID = new Ext.form.CheckboxGroup({";
               $CHECKBOX_JS .= "fieldLabel: '".$value->NAME."'";
               $CHECKBOX_JS .= ",columns: 2";
               $CHECKBOX_JS .= ",items:[";
                   $CHECKBOX_DATA = array();
                   foreach($entries as $v){
                       $CHECKBOX_DATA[] = "{boxLabel: '".$v->NAME."', name: 'CHECKBOX_".$v->ID."'}";
                   }
                   $CHECKBOX_JS .= implode(',',$CHECKBOX_DATA);
               $CHECKBOX_JS .= "]";
           $CHECKBOX_JS .= "});";

           $CHECKBOX_ITEMS[] = "CHECKBOX_".$value->ID."";   
        }
    }
}

$entriesParentRadiobox = FinanceDescriptionDBAccess::sqlDescription(false, 2, 1);
$RADIOBOX_JS = "";
$RADIOBOX_DATA = array();
$RADIOBOX_ITEMS = array();
if($entriesParentRadiobox){
    foreach($entriesParentRadiobox as $value){
        if(FinanceDescriptionDBAccess::checkChild($value->ID)){
            $entries = FinanceDescriptionDBAccess::sqlDescription($value->ID, 2, 1);
            $RADIOBOX_JS .= "var RADIOBOX_$value->ID = new Ext.form.RadioGroup({";
                $RADIOBOX_JS .= "fieldLabel: '".$value->NAME."'";
                $RADIOBOX_JS .= ",columns: 2";
                $RADIOBOX_JS .= ",items:[";
                    $RADIOBOX_DATA = array();
                    foreach($entries as $v){
                        $RADIOBOX_DATA[] = "{boxLabel: '".$v->NAME."', name: 'RADIOBOX_".$value->ID."', inputValue: '".$v->ID."'}";
                    }
                    $RADIOBOX_JS .= implode(',',$RADIOBOX_DATA);
                $RADIOBOX_JS .= "]";
            $RADIOBOX_JS .= "});";

            $RADIOBOX_ITEMS[] = "RADIOBOX_".$value->ID."";
        }
    }
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
	
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    echo $RADIOBOX_JS;
    echo $CHECKBOX_JS;
    
    $CATEGORY_TREE->isAsyncTreeNode = false;
    $CATEGORY_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
    $CATEGORY_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $CATEGORY_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());

    $CATEGORY_TREE->setBaseParams("
        cmd: 'jsonTreeAllIncomeCategories'
    ");

    $CATEGORY_TREE->backgroundColor = "#F9F9F9";
    $CATEGORY_TREE->isTreeExpand = true;
    $CATEGORY_TREE->renderJS();
    
    $triggerOnClickCategory = "
        openWinXType('INCOME_CATEGORY','".INCOME_CATEGORY."', '".$CATEGORY_TREE->getObjectXType()."', 500, percentHeight(85));
        var myTree = Ext.getCmp('".$CATEGORY_TREE->getObjectId()."');
        myTree.on('click', function(node, e){
        Ext.getCmp('CHOOSE_INCOME_CATEGORY_NAME_ID').setValue(node.attributes.text);
        Ext.getCmp('CHOOSE_INCOME_CATEGORY').setValue(node.attributes.id);
        Ext.getCmp('INCOME_CATEGORY').close();
    });
    ";
    
    ////////////////////////////////////////////////////////////////////////////
    
    if($this->facette){
        if(!$studentObject){
            $FORM_ITEMS = "[
                {".CamemisField::Displayfield("TRANSACTION_NUMBER", TRANSACTION_NUMBER, false, false)."}
                ,{".CamemisField::Textfield("TRANSACTION_NAME", "NAME", TRANSACTION_NAME, true)."}
                ,{".CamemisField::Textfield("PAYMENT_AMOUNT", "PAYMENT_AMOUNT", AMOUNT." (".Zend_Registry::get('SCHOOL')->CURRENCY.")", true, false, false, false, false)."}
                ,{".CamemisField::Trigger("CHOOSE_INCOME_CATEGORY_NAME",INCOME_CATEGORY,$triggerOnClickCategory,true, false, false)."}
            ]"; 
        }else{
           $taxforma=($this->tax=='1')?$taxforma='+':'-';
            $FORM_ITEMS = "[
                {".CamemisField::Displayfield("TRANSACTION_NUMBER", TRANSACTION_NUMBER, false, false)."}
                ,{".CamemisField::Displayfield("STUDENT", STUDENT, false, false)."}
                ,{".CamemisField::Displayfield("FEES", FEES." (".Zend_Registry::get('SCHOOL')->CURRENCY.")", false, false)."}
                ,{".CamemisField::Displayfield("CHOOSE_INCOME_CATEGORY_NAME", INCOME_CATEGORY, false, false)."}
                ,{".CamemisField::Displayfield("DISCOUNT", DISCOUNT." ".$this->facette->DISCOUNT_PERCENT."% (".Zend_Registry::get('SCHOOL')->CURRENCY.")", false, false)."} 
                ,{".CamemisField::Displayfield("TAX", TAX." ".$taxforma." ".$this->tax->PERCENT."% (".Zend_Registry::get('SCHOOL')->CURRENCY.")", false, false)."}
            ";
            if($this->facette->SCHOLARSHIP_PERCENT){
                $FORM_ITEMS .= "
                    ,{".CamemisField::Displayfield("SCHOLARSHIP", SCHOLARSHIP." ".$this->facette->SCHOLARSHIP_PERCENT."% (".Zend_Registry::get('SCHOOL')->CURRENCY.")", false, false)."}
                ";
            }
            $FORM_ITEMS .= "   
                ,{".CamemisField::Displayfield("TOTAL_AMOUNT", TOTAL_AMOUNT." (".Zend_Registry::get('SCHOOL')->CURRENCY.")", false, false)."}
            ]"; 
        }
    }else{
        $FORM_ITEMS = "[
            {".CamemisField::Displayfield("TRANSACTION_NUMBER", TRANSACTION_NUMBER, false, false)."}
            ,{".CamemisField::Textfield("TRANSACTION_NAME", "NAME", TRANSACTION_NAME, true)."}
            ,{".CamemisField::Textfield("PAYMENT_AMOUNT", "PAYMENT_AMOUNT", AMOUNT." (".Zend_Registry::get('SCHOOL')->CURRENCY.")", true, false, false, false, false)."}
            ,{".CamemisField::Trigger("CHOOSE_INCOME_CATEGORY_NAME",INCOME_CATEGORY,$triggerOnClickCategory,true, false, false)."}
        ]"; 
    }
    
    $DETAIL_INFORMATION = "
    {
        title: '".DETAIL_INFORMATION."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
            ,items: ".$FORM_ITEMS."
        }]
    }
    ";
    
    $DESCRIPTION = "
    {
        title: '".DESCRIPTION."'
        ,collapsible: true
        ,collapsed: ".$collapsed."
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
            ,items: [{".CamemisField::Textarea("DESCRIPTION", false,150)."}]
        }]
    }
    ";

    $DETAIL_CHECKBOX = "
    {
        title: '".CHECK_BOX."'
        ,collapsible: true
        ,collapsed: ".$collapsed."
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
            ,items: [".implode(',',$CHECKBOX_ITEMS)."]
        }]
    }
    ";
        
    $DETAIL_RADIOBOX = "
    {
        title: '".RADIO_BOX."'
        ,collapsible: true
        ,collapsed: ".$collapsed."
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
            ,items: [".implode(',',$RADIOBOX_ITEMS)."]
        }]
    }
    ";
        
    if($CHECKBOX_ITEMS && $RADIOBOX_ITEMS){
        $SET_ITEMS = "
        [
            ".$DETAIL_RADIOBOX."
            ,".$DETAIL_CHECKBOX."
        ]
        ";
    }elseif(!$CHECKBOX_ITEMS && $RADIOBOX_ITEMS){
        $SET_ITEMS = "
        [
            ".$DETAIL_RADIOBOX."
        ]
        ";
    }elseif($CHECKBOX_ITEMS && !$RADIOBOX_ITEMS){
        $SET_ITEMS = "
        [
            ".$DETAIL_CHECKBOX."
        ]
        ";
    }else{
        $SET_ITEMS = "
        [
        ]
        ";
    }
       
    $FORM_ITEMS = "[";
    
    $FORM_ITEMS .= $DETAIL_INFORMATION;
    $FORM_ITEMS .= ",".$SET_ITEMS;
    if($this->objectId!="new"){
        $ATTACHMENTS = "
        {
            title: '".ATTACHMENTS."'
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,height:650
            ,layout:'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ATTACHMENTS', url: '/dataset/attachment/?objectId=".$this->objectId."&template=INCOME'})]
        }
        ";
        
        $FORM_ITEMS .= ",".$ATTACHMENTS;
    }
    $FORM_ITEMS .= ",".$DESCRIPTION;
    $FORM_ITEMS .= "]";
    
    $OBJECT_FORM->addObjectItems(CamemisField::Hidden("CHOOSE_INCOME_CATEGORY",false)); 
    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: ".$FORM_ITEMS."
    ";
    
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        }
    ");
	
    if($this->facette){
        
        if(!$studentObject){
            //if (UserAuth::getACLValue("FINANCIAL_MANAGEMENT_REMOVE_RIGHT"))
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormEasyRemoveObject());

            //if (UserAuth::getACLValue("FINANCIAL_MANAGEMENT_EXECUTE_RIGHT"))
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave()); 
        }
    }else{
        //if (UserAuth::getACLValue("FINANCIAL_MANAGEMENT_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    }
    
    $OBJECT_FORM->setLoadParams("cmd: 'loadIncome',objectId: '".$this->objectId."'");
    $OBJECT_FORM->setSaveParams("
        cmd: 'saveIncome'
        ,objectId: '".$this->objectId."'
    ");
    
    $OBJECT_FORM->setonEmbeddedEvents("
        if (window.parent.Ext.getCmp('FINANCE_LIST_ID')) window.parent.Ext.getCmp('FINANCE_LIST_ID').store.reload();
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        var result = Ext.util.JSON.decode(action.response.responseText);
        var objectId = result.objectId;
        window.location='".$_SERVER["REQUEST_URI"]."&objectId='+objectId;
    ");

    $OBJECT_FORM->setRemoveParams("
        cmd: 'removeIncome'
        ,objectId: '".$this->objectId."'
    ");
	
    $OBJECT_FORM->setOnEmbeddedRemoveEvents("
        if (window.parent.Ext.getCmp('FINANCE_LIST_ID')) window.parent.Ext.getCmp('FINANCE_LIST_ID').store.reload();
        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
    ");
	
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>