<?
///////////////////////////////////////////////////////////
// @sor veasna  
// Date: 02/12/2013
// 
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisSchoolTree.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisSchoolTree("ACADEMIC");
$OBJECT_TREE->setURL("/academic/jsontree/");
$OBJECT_TREE->setSaveUrl("/academic/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_SCHOOLYEAR = new CamemisDynCombo("ACADEMICDATE","COMBO");
        $OBJECT_SCHOOLYEAR->setLoadUrl('/academicdate/jsonload/');
        $OBJECT_SCHOOLYEAR->objectTitle = false;
        $OBJECT_SCHOOLYEAR->allowBlank = "true";
        $OBJECT_SCHOOLYEAR->width = 150;
        $OBJECT_SCHOOLYEAR->varName = "SCHOOLYEAR";
        $OBJECT_SCHOOLYEAR->setLoadParams("cmd: 'allSchoolyearCombo'");
        $OBJECT_SCHOOLYEAR->renderJS();

        $OBJECT_TREE->isAsyncTreeNode = false;

        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        $OBJECT_TREE->addTBarItems("
            xtype: 'buttongroup'
            ,items:[{
                width: 80
                ,xtype: '".$OBJECT_SCHOOLYEAR->getObjectXType()."'
            }]
        ");
        
        $OBJECT_TREE->setBaseParams("
            
            cmd: 'getTreeCreditEducationSystem'
            ,educationSystem:1
        ");
        
        $OBJECT_TREE->isOnClickContextMenu = false;
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isTreeExpand = true;
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout: 'card'
                ,border: false
                ,activeItem: 0
                ,id: 'CONTENT'
                ,items:[{
                    layout:'border'
                    ,border: false
                    ,defaults: {
                        collapsible: true
                        ,split: true
                    }
                    ,items: [{
                        id: 'ACADEMIC_ID'
                        ,region:'west'
                        ,title: '&nbsp;'
                        ,autoScroll: true
                        ,margins: '3 0 3 3'
                        ,cmargins: '3 3 3 3'
                        ,width:350
                        ,minSize:350
                        ,maxSize:350
                        ,layout: 'fit'
                        ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                    },{
                        collapsible: false
                        ,id: 'center'
                        ,region:'center'
                        ,margins: '3 3 3 0'
                        ,layout: 'card'
                        ,activeItem: 0
                        ,bodyStyle: 'padding:1px'
                        ,items: [{
                            border: false
                            ,layout: 'anchor'
                            ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                            ,items: [{
                                title: ''
                                ,height:60
                                ,width:500
                                ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                                ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                            }]
                        }]
                    }]
                }]
            }]
        });
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        var myCombo = Ext.getCmp('COMBO_ID');
        if (myCombo)
        myCombo.on('select', function() {
            myTree.loader.baseParams.SCHOOLYEAR = Ext.getCmp('COMBO_ID').getValue();
            myTree.root.reload();
            myTree.getRootNode().expand(true, false);
            Ext.getCmp('center').getLayout().setActiveItem(0);
        });
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        
        myTree.on('click', function(node){
            if(node.isLeaf()){
                clickOpenPage('center',node.text, '/attendance/studentclassdaily/?target=general&classId=' + node.id+'&staffId=<?=Zend_Registry::get('USER')->ID?>');
                //clickOpenPage('center',node.text, '/attendance/studentclassmain/?target=general&classId=' + node.id);
                Ext.getCmp('ACADEMIC_ID').collapse();
            }
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>