<?
///////////////////////////////////////////////////////////
// @Sor Veasna
// Date: 04.12.2013
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$ASSIGNED_STUDENTS_GRID = new CamemisGrid("ASSIGNED_STUDENTS", "ENROLLED_STUDENTS");
$ASSIGNED_STUDENTS_GRID->setLoadUrl("/student/jsonload/");
$ASSIGNED_STUDENTS_GRID->setSaveUrl("/student/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<script>
    Ext.onReady(function() {
        
        function cssStatus(v, p, record){
            return String.format('<div style=\"font-weight:bold;padding:4px;background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['BG_COLOR']
            ,record.data['BG_COLOR_FONT']
            );
        }
        
        function cssText(value, metadata, record){
            return '<div style="font-weight:normal; color:#000; padding: 5px; height: 15px;;">' + value + '</div>';
        }

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $STAFF_ATTENDANCE_READ_RIGHT = UserAuth::getACLValue("STAFF_ATTENDANCE_READ_RIGHT")?"false":"true";
        
        ////
        $OBJECT_SCHOOLYEAR = new CamemisDynCombo("ACADEMICDATE","COMBO");
        $OBJECT_SCHOOLYEAR->setLoadUrl('/academicdate/jsonload/');
        $OBJECT_SCHOOLYEAR->objectTitle = false;
        $OBJECT_SCHOOLYEAR->allowBlank = "true";
        $OBJECT_SCHOOLYEAR->width = 150;
        $OBJECT_SCHOOLYEAR->varName = "SCHOOLYEAR";
        $OBJECT_SCHOOLYEAR->setLoadParams("cmd: 'allSchoolyearCombo'");
        $OBJECT_SCHOOLYEAR->renderJS();
        
        /////
        
        
        $ASSIGNED_STUDENTS_GRID->addReadField("name: 'ID'");
        $ASSIGNED_STUDENTS_GRID->addReadField("name: 'CODE_ID'");
        $ASSIGNED_STUDENTS_GRID->addReadField("name: 'STUDENT'");
        $ASSIGNED_STUDENTS_GRID->addReadField("name: 'FIRSTNAME'");
        $ASSIGNED_STUDENTS_GRID->addReadField("name: 'LASTNAME'");
        $ASSIGNED_STUDENTS_GRID->addReadField("name: 'GENDER'");
        $ASSIGNED_STUDENTS_GRID->addReadField("name: 'DATE_BIRTH'");
        
        $ASSIGNED_STUDENTS_GRID->addReadField("name: 'BG_COLOR'");
        $ASSIGNED_STUDENTS_GRID->addReadField("name: 'BG_COLOR_FONT'");
        $ASSIGNED_STUDENTS_GRID->addReadField("name: 'STATUS_KEY'");
        
        switch(Zend_Registry::get('SYSTEM_LANGUAGE')){
            case "VIETNAMESE": $width = 100;break;
            default: $width = 85;break;
        }

        $ASSIGNED_STUDENTS_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: ".$width.", renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY'");
        $ASSIGNED_STUDENTS_GRID->addColumn("header: '<b>".CODE_ID."</b>', align:'center', width: 80, renderer: cssText, sortable: true, dataIndex: 'CODE_ID'");
        $ASSIGNED_STUDENTS_GRID->addColumn("header: '<b>".LASTNAME."</b>', width: 120, renderer: cssText, sortable: true, dataIndex: 'LASTNAME'");
        $ASSIGNED_STUDENTS_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', width: 120, renderer: cssText, sortable: true, dataIndex: 'FIRSTNAME'");
       
        
        $ASSIGNED_STUDENTS_GRID->baseParams = "
            start:0
            ,limit:100
            ,schoolyearId: '".$this->schoolyearId."'
            ,cmd: 'jsonEnrolledCreditStudentInSchoolyear'
        ";
       
        $ASSIGNED_STUDENTS_GRID->addTBarItems("
            tbar.add('->');
        ");
        
        $ASSIGNED_STUDENTS_GRID->addTBarItems("
            tbar.add('-',[{
                 xtype: 'buttongroup'
                ,items:[{
                    width: 80
                    ,xtype: '".$OBJECT_SCHOOLYEAR->getObjectXType()."'
                }]
            }]);
        ");
        
        $ASSIGNED_STUDENTS_GRID->removeNAME = "STUDENT";
        $ASSIGNED_STUDENTS_GRID->loadMask = true;
        $ASSIGNED_STUDENTS_GRID->isPagingToolbar = true;
        $ASSIGNED_STUDENTS_GRID->isQuickySearch = true;
        $ASSIGNED_STUDENTS_GRID->isObjectDefaultOnLoad = true;
        $ASSIGNED_STUDENTS_GRID->forceFit = "false";
        $ASSIGNED_STUDENTS_GRID->renderJS();
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    id:'west'
                    ,region:'west'
                    ,title: ''
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width: 450
                    ,minSize: 450
                    ,maxSize: 450
                    ,layout: 'card'
                    ,activeItem: 0
                    ,items:[{xtype: '<?=$ASSIGNED_STUDENTS_GRID->getObjectXtype();?>'}]
                },{
                    collapsible: false
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,items: [{
                        border: false
                        ,layout: 'anchor'
                        ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                        ,items: [{
                            title: ''
                            ,height:60
                            ,width:500
                            ,bodyStyle: 'background:#F9F9F9; padding:15px; border:1px dotted #999;text-align:center;'
                            ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                        }]
                    }]
                }]
            }]
        });
        
        var myCombo = Ext.getCmp('<?=$OBJECT_SCHOOLYEAR->getObjectId();?>');
        var schoolyearId = '<?=$this->schoolyearId?>';
        if (myCombo)
        myCombo.on('select', function() {
            schoolyearId = myCombo.getValue();
            Ext.getCmp('<?=$ASSIGNED_STUDENTS_GRID->getObjectId()?>').store.baseParams = {
                start:0
                ,limit:100
                ,schoolyearId: schoolyearId
                ,cmd: 'jsonEnrolledCreditStudentInSchoolyear'
            };
            Ext.getCmp('<?=$ASSIGNED_STUDENTS_GRID->getObjectId()?>').store.load();
        });
        <?  
        
        ////////////////////////////////////////////////////////////
        //Block Absence Grid Click
        ///////////////////////////////////////////////////////////
        $LIST_ATTENDANCE ="{";
        $LIST_ATTENDANCE .="text: '".SHOW_DETAIL." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME";
        $LIST_ATTENDANCE .=",iconCls: 'icon-user'";
        $LIST_ATTENDANCE .=",handler: function(){";
        $LIST_ATTENDANCE .="clickOpenPage('center','','/attendance/personcreditblock/?studentId=' + record.data.ID + '&schoolyearId='+schoolyearId);";
        $LIST_ATTENDANCE .="}";
        $LIST_ATTENDANCE .="}";
        
        $CONTEXTMENU_ITEMS[] = $LIST_ATTENDANCE;
        
        $ADD_ATTENDANCE ="{";
        $ADD_ATTENDANCE .="text: '".ADD_ATTENDANCE." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME";
        $ADD_ATTENDANCE .=",iconCls: 'icon-add'";
        $ADD_ATTENDANCE .=",handler: function(){";
        $ADD_ATTENDANCE .="clickOpenPage('center','','/attendance/addattendancecreditstudent/?objectId=new&studentId=' + record.data.ID + '&schoolyearId='+schoolyearId);";
        $ADD_ATTENDANCE .="}";
        $ADD_ATTENDANCE .="}";
        
        $CONTEXTMENU_ITEMS[] = $ADD_ATTENDANCE;
        
        $CHOOSE_CONTEXTMENU_ITEMS = implode(",", $CONTEXTMENU_ITEMS);
        if($CONTEXTMENU_ITEMS){
        $js = "";
        $js .="var grid = Ext.getCmp('".$ASSIGNED_STUDENTS_GRID->getObjectId()."');";
        $js .="if (grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {";
            $js .="var record = grid.store.getAt(rowIndex);";
            $js .="var contextMenu = new Ext.menu.Menu({";
            $js .="items: [".$CHOOSE_CONTEXTMENU_ITEMS."]";
            $js .="});";
            $js .="event.stopEvent();";
            $js .="contextMenu.showAt(event.xy);"; 
        $js .="});";
        echo $js;
        }
        ?>
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>