<?
///////////////////////////////////////////////////////////
// @sor veasna
// Date: 26/12/2013
// 
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_GRID = new CamemisGrid("CREDIT_INFORMATION", "LIST");
$OBJECT_GRID->setLoadUrl("/academic/jsonload/");
$OBJECT_GRID->setSaveUrl("/academic/jsonsave/");

$studentschoolId = isset($_GET["studentschoolId"])?addText($_GET["studentschoolId"]):"";
$code = isset($_GET["student_code_id"])?addText($_GET["student_code_id"]):"";
$firstname = isset($_GET["firstname"])?addText($_GET["firstname"]):"";
$lastname = isset($_GET["lastname"])?addText($_GET["lastname"]):"";
$gender = isset($_GET["gender"])?addText($_GET["gender"]):"";

$schoolyearId = isset($_GET["schoolyearId"])?addText($_GET["schoolyearId"]):"";
$subjectId = isset($_GET["subjectId"])? (int)$_GET["subjectId"]:"";
$creditStatus = isset($_GET["creditStatus"])?addText($_GET["creditStatus"]):"";
$creditNumber = isset($_GET["creditNumber"])?addText($_GET["creditNumber"]):"";

$baseParams = "";
$baseParams .= "start:0";
$baseParams .= ",limit:100";
$baseParams .= ",cmd: 'jsonListCreditStudentInformation'";
$baseParams .= ",lastname:'".$lastname . "'"; 
$baseParams .= ",firstname:'".$firstname . "'"; 
$baseParams .= ",gender:'".$gender . "'"; 
$baseParams .= ",studentschoolId:'".$studentschoolId . "'"; 
$baseParams .= ",code:'".$code . "'";
$baseParams .= ",schoolyearId:'".$schoolyearId . "'"; 
$baseParams .= ",subjectId:'".$subjectId . "'";
$baseParams .= ",creditStatus:'".$creditStatus . "'";
$baseParams .= ",creditNumber:'".$creditNumber . "'";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$viewport = "";
$viewport .= "viewport = new Ext.Viewport({";
    $viewport .= "layout: 'fit'";
    $viewport .= ",border: false";
    $viewport .= ",items:[{";
        $viewport .= "border: false";
        $viewport .= ",xtype: 'panel' ";
        $viewport .= ",layout: 'card'";
        $viewport .= ",id: 'center'";
        $viewport .= ",activeItem: 0 ";
        $viewport .= ",items:[{ ";
            $viewport .= "border: false ";
            $viewport .= ",layout: 'fit' ";
            $viewport .= ",items: [{xtype: '".$OBJECT_GRID->getObjectXType()."'}]";
        $viewport .= "}]";
    $viewport .= "}] ";
$viewport .= "});";


 $SHOW_DETAIL ="{";
    $SHOW_DETAIL .="text: '".SHOW_DETAIL."'";
    $SHOW_DETAIL .=",iconCls: 'icon-application_form_magnify'";
    $SHOW_DETAIL .=",handler: function(){";
    $SHOW_DETAIL .="clickOpenPage('CONTENT','','/facility/subshowmanageitem/?&objectId=' + record.data.ID);";
    $SHOW_DETAIL .="}";
    $SHOW_DETAIL .="}";

$js = "";
$js .= "Ext.getCmp('CREDIT_INFORMATION_LIST_ID').on('cellclick', function(grid, rowIndex, columnIndex, event) {
        var record = grid.store.getAt(rowIndex);
        var contextMenu = new Ext.menu.Menu({
            items: [{
                text: 'SHOW STATUS' 
                ,iconCls: 'icon-application_form_magnify' 
                ,handler: function(){
                    clickOpenPage('center','','/academic/showcreditinformation/?studentSubjectId=' + record.data.ID);
                }
            },{
                text: 'SHOW ASSESSMENT' 
                ,iconCls: 'icon-application_form_magnify' 
                ,handler: function(){

                }
            }]
        });
        event.stopEvent();
        contextMenu.showAt(event.xy);
        
    });
";

?>
<script>
Ext.onReady(function() { 
    function cssTextBlue(value, metadata, record){
        return '<div style="font-weight:normal; color:#0000FF; padding: 5px;">' + value + '</div>';
    }
	function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#000; padding: 5px;">' + value + '</div>';
    }
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    /////
    $comboEditor = "
        new Ext.form.ComboBox({
            triggerAction:'all'
            ,mode:'local'
            ,store: new Ext.data.JsonStore({
                autoDestroy: true
                ,fields: ['chooseValue', 'chooseDisplay']
                ,data:[{chooseValue: 0, chooseDisplay: 'Incompleted'},{chooseValue: 1, chooseDisplay: 'Completed'}]
            })
            ,valueField: 'chooseValue'
            ,displayField: 'chooseDisplay'
            ,editable: false
            ,listeners: {
                select: function(combo, record, index) {
                    replaceValue = combo.getValue();
                    var newDisplay = record.get('chooseDisplay');
                    combo.setValue(newDisplay);
                }
            }
        })
    ";
    
    ///// 
    
    $OBJECT_GRID->addReadField("name: 'ID'");
    $OBJECT_GRID->addReadField("name: 'STUDENT_TOTAL_CREDIT'");
    $OBJECT_GRID->addReadField("name: 'SUBJECT'");
    $OBJECT_GRID->addReadField("name: 'CREDIT_NUMBER'");
    $OBJECT_GRID->addReadField("name: 'SESSION'");
    $OBJECT_GRID->addReadField("name: 'SCHOOLYEAR'");
    $OBJECT_GRID->addReadField("name: 'STATUS'");
    $OBJECT_GRID->addReadField("name: 'DESCRIPTION'");
    $OBJECT_GRID->addReadField("name: 'COLOR'");
    $OBJECT_GRID->addReadField("name: 'CREDIT_STATUS_BY'");
    $OBJECT_GRID->addReadField("name: 'CREDIT_STATUS_DATED'");
    
    $OBJECT_GRID->addColumn("header: '<b>Name</b>', align:'center', width: 250, renderer:cssTextBlue, sortable: true, dataIndex: 'STUDENT_TOTAL_CREDIT'");
    $OBJECT_GRID->addColumn("header: '<b>".SUBJECT."</b>', align:'center', width: 120, renderer: cssText, sortable: true, dataIndex: 'SUBJECT'");
    $OBJECT_GRID->addColumn("header: '<b>Credit Number</b>', align:'center', width: 120, renderer: cssText, sortable: true, dataIndex: 'CREDIT_NUMBER'");
    $OBJECT_GRID->addColumn("header: '<b>Session</b>', width: 120, renderer: cssText, align: 'center', sortable: true, dataIndex: 'SESSION'");
    $OBJECT_GRID->addColumn("header: '<b>".SCHOOL_YEAR."</b>', align:'center',  width: 120, renderer: cssText, sortable: true, dataIndex: 'SCHOOLYEAR'");
    $OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: 120, renderer: cssText, sortable: true, dataIndex: 'STATUS'");
    /*$OBJECT_GRID->addColumn("
                header: '<b>".STATUS."</b>'
                , width: 120
                , align: 'center'
                , sortable: true
                , dataIndex: 'STATUS'
                , renderer:cssText  
                , editor: ".$comboEditor."
            ");
            
    $OBJECT_GRID->addColumn("
                header: '<b>".DESCRIPTION."</b>'
                , width: 250
                , renderer: cssText
                , align: 'center'
                , sortable: true
                , dataIndex: 'DESCRIPTION'
                ,editor: {
                    xtype: 'textarea'
                }
            "); */
    $OBJECT_GRID->addColumn("header: '<b>".DESCRIPTION."</b>', width: 250, renderer: cssText, align: 'center', sortable: true, dataIndex: 'DESCRIPTION'");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_BY."</b>', width: 250, renderer: cssText, align: 'center', sortable: true, dataIndex: 'CREDIT_STATUS_BY'");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_DATE."</b>', width: 250, renderer: cssText, align: 'center', sortable: true, dataIndex: 'CREDIT_STATUS_DATED'");
    
    $OBJECT_GRID->baseParams = $baseParams;   
    
    /*$OBJECT_GRID->setSaveParams("
        cmd: 'changeCrditeStudentInformation'
    ");
    
    $OBJECT_GRID->setAftereditCallback("
        if(jsonData.error == ''){
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        }else{
            XMsg('".STATUS."',jsonData.error); 
        }
    "); */

    $OBJECT_GRID->isGroupingView = true;
    $OBJECT_GRID->groupField = 'STUDENT_TOTAL_CREDIT';
    $OBJECT_GRID->isQuickySearch = true;
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    //$OBJECT_GRID->isGridEditing = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    ?>
    <?=$viewport;?>
    <?=$js;?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>