<?
///////////////////////////////////////////////////////////
// @Veasna
// Date: 02.01.2014   
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance(); 
$OBJECT_FORM = new CamemisForm("CREDIT_INFROMATION","LIST");
$OBJECT_FORM->setLoadUrl('/academic/jsonload/');
$OBJECT_FORM->setSaveUrl('/academic/jsonsave/'); 

if(!$this->studentSubjectObject) {header("Location: /main/permission/");exit;}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();  
    
    $ATTACHMENTS = "
    {
        title: '".ATTACHMENTS."'
        ,collapsible: true
        ,collapsed: false
        ,width: 550
        ,height: 560
        ,style: 'padding-bottom: 5px'
        ,layout:'fit'
        ,items: [new Ext.ux.IFrameComponent({ id: 'ATTACHMENTS', url: '/dataset/attachment/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->studentSubjectId."&template=CREDIT_INFORMATION")."'})]
    }
    ";
    
    $CONTENT = "
    {
        title: '".DESCRIPTION."'
        ,collapsible: true
        ,collapsed: false
        ,width: 550
        ,style: 'padding-bottom: 5px'
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'padding:5px'
            ,items:[{".CamemisField::HTML("CONTENT",250,false)."}]
        }]
    }
    ";
    
    $store = "[";
    $store .= "['0', 'Ongoing']";
    $store .= ",['1', 'Incompleted']";
    $store .= ",['2', 'Completed']";
    $store .= "]";
    
    $CREDIT_STATUS = "{
        title: 'CREDIT STATUS'
        ,autoHeight: true
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,bodyStyle: 'background:#FFF; padding:10px'
            ,items: [{".CamemisField::Combo("CREDIT_STATUS","Credit Status",$store,false)."}]
        }]
    }"; 
        
    $ITEMS = "[";  
        $ITEMS .= $CREDIT_STATUS;  
        $ITEMS .= ",".$CONTENT;
        $ITEMS .= ",".$ATTACHMENTS; 
    $ITEMS .= "]";

    $formItems = "
        border: false
        ,layout: 'form'
        ,items:".$ITEMS 
    ;
    
    $OBJECT_FORM->addObjectItems($formItems);
    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);   
        }
    ");
 
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());                          
    $OBJECT_FORM->setLoadParams("
        cmd: 'jsonStudentCreditStatus'
        ,studentSubjectId: '".$this->studentSubjectId."'
    ");

    $OBJECT_FORM->setSaveParams("cmd: 'changeStudentSubjectCreditInfo',studentSubjectId: '".$this->studentSubjectId."'");
    
    $OBJECT_FORM->setonEmbeddedEvents(" 
        var result = Ext.util.JSON.decode(action.response.responseText);    
        if(result.error == ''){
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        }else{
            XMsg('".STATUS."',result.error); 
        }
        window.parent.Ext.getCmp('CREDIT_INFORMATION_LIST_ID').store.reload();
        window.location='".$_SERVER["REQUEST_URI"]."&studentSubjectId='+result.objectId;
    ");
    
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 150;
    $OBJECT_FORM->renderJS();

    $VIEWPORT = "
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,id: 'content'
                ,layout: 'fit'
                ,items:[{xtype: '".$OBJECT_FORM->getObjectXtype()."'}]
            }]
        }); 
    ";
    echo  $VIEWPORT;
    ?> 
        
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>