<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

if(!$this->facette) {header("Location: /main/permission/");exit;}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$OBJECT_GRID = new CamemisGrid("FINANCE", "PAYMENTS");
$OBJECT_GRID->setLoadUrl("/finance/jsonload/");
$columndata = Utiles::getGridColumnData("FINANCE_LIST_ID");

?>
<style>
    span.spanText {
        font-weight:bold;
        color:#333; 
        white-space:normal;
    }
</style>
<script>
var clickId;
Ext.onReady(function() {
	
    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#333; padding:3px;">' + value + '</div>';
    }
    
    function cssNumber(value, metadata, record){
        return '<div style="font-weight:bold; color:#3B5998; padding: 5px;">' + value + '</div>';
    }
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addReadField("name: 'FEE_NAME'");
    $OBJECT_GRID->addReadField("name: 'TRANSACTION_NUMBER'");
    $OBJECT_GRID->addReadField("name: 'AMOUNT'");
    $OBJECT_GRID->addReadField("name: 'ACADEMIC'");
    
    $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");
    $OBJECT_GRID->addReadField("name: 'CREATED_BY'");
    
    $OBJECT_GRID->addColumn("header: '<b>".NAME."</b>', align:'left', renderer: cssText, width: 150, hidden:".checkColHidden(1, $columndata).", sortable: true, dataIndex: 'FEE_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".NUMBER."</b>', align:'right', renderer: cssText, width: 150, hidden:".checkColHidden(2, $columndata).", sortable: true, dataIndex: 'TRANSACTION_NUMBER'");
    $OBJECT_GRID->addColumn("header: '<b>".AMOUNT."</b>', align:'right', renderer: cssNumber, width: 150, hidden:".checkColHidden(3, $columndata).", sortable: true, dataIndex: 'AMOUNT'");
    $OBJECT_GRID->addColumn("header: '<b>".ACADEMIC."</b>', align:'right', renderer: cssNumber, width: 150, hidden:".checkColHidden(4, $columndata).", sortable: true, dataIndex: 'ACADEMIC'");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_DATE."</b>', align:'right', renderer: cssText, width: 170, hidden:".checkColHidden(5, $columndata).", sortable: true, dataIndex: 'CREATED_DATE'");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_BY."</b>', align:'right', renderer: cssText, width: 150, hidden:".checkColHidden(6, $columndata).", sortable: true, dataIndex: 'CREATED_BY'");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'REFRESH_ID'
            ,text: '".REFRESH."'
            ,iconCls:'icon-reload'
            ,scope:this
            ,disabled: false
            ,handler: function(){
               Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
            }
        }]);
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,objectId:'".$this->objectId."'
        ,cmd: 'jsonListStudentPayments'
    ";
    $OBJECT_GRID->isGroupingView = true;
    $OBJECT_GRID->groupField = "FEE_NAME";
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,layout: 'card'
            ,activeItem: 0
            ,title:'<?=RECENT_PAYMENTS?>'
            ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
        }]
    });
    var myGrid = Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>');
    if (myGrid) myGrid.on('cellclick', function(grid, rowIndex, columnIndex, event) {
        var record = grid.store.getAt(rowIndex);
        var contextMenu = new Ext.menu.Menu({
            items: [{
                text: '<?=PRINTER;?> &raquo; ' + record.data.TRANSACTION_NUMBER
                ,iconCls:'icon-printer'
                ,handler:function(){
                    window.open("/finance/printpaid?objectId=" + record.data.ID, "_blank");
                }
            }]
        });
        event.stopEvent();
        contextMenu.showAt(event.xy);
    });
    Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>