<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'clients/CamemisViewport.php';
require_once 'models/UserAuth.php';
require_once 'models/app_school/LocationDBAccess.php';
require_once 'models/app_school/student/StudentDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$OBJECT_GRID = new CamemisGrid("SERVICES", "LIST");
$OBJECT_GRID->setLoadUrl("/finance/jsonload/");
$OBJECT_GRID->setSaveUrl("/finance/jsonsave/");
$columndata = Utiles::getGridColumnData("FINANCE_LIST_ID");

?>
<script>
Ext.onReady(function() {

    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#333; padding:3px;">' + value + '</div>';
    }
    
    function cssTextPaid(value, metadata, record){
        var name = record.data.STUDENT;
        //metadata.attr = 'ext:qtip="' + name + '"';
        return '<div style="font-weight:bold; color:#061f83; padding: 5px; background:#FFF;">' + value + '</div>';
    }
    
    function cssTextOwed(value, metadata, record){
        var name = record.data.STUDENT;
        //metadata.attr = 'ext:qtip="' + name + '"';
        return '<div style="font-weight:bold; color:#e24f43; padding: 5px; background:#FFF;">' + value + '</div>';
    }
    
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addReadField("name: 'ASSIGNED'");
    $OBJECT_GRID->addReadField("name: 'NAME'");
    $OBJECT_GRID->addReadField("name: 'AMOUNT_PAID'");
    $OBJECT_GRID->addReadField("name: 'AMOUNT_OWED'");
    $OBJECT_GRID->addReadField("name: 'PAID_STATUS'");
    $OBJECT_GRID->addColumn("
        xtype: 'checkboxcolumn'
        ,header: '&nbsp;'
        ,align:'center'
        ,dataIndex: 'ASSIGNED'
        ,width:80
        ,on: 1
        ,off: 0
    ");
    
    $OBJECT_GRID->addColumn("header: '<b>".NAME."</b>', align:'left', renderer: cssText, width: 250, hidden:".checkColHidden(1, $columndata).", sortable: true, dataIndex: 'NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".AMOUNT_PAID."</b>', align:'right', renderer: cssTextPaid, width: 120, hidden:".checkColHidden(2, $columndata).", sortable: true, dataIndex: 'AMOUNT_PAID'");
    $OBJECT_GRID->addColumn("header: '<b>".AMOUNT_OWED."</b>', align:'right', renderer: cssTextOwed, width: 120, hidden:".checkColHidden(3, $columndata).", sortable: true, dataIndex: 'AMOUNT_OWED'");
    $OBJECT_GRID->addColumn("header: '<b>".PAID_STATUS."</b>', align:'right', renderer: cssText, width: 150, hidden:".checkColHidden(4, $columndata).", sortable: true, dataIndex: 'PAID_STATUS'");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonListStudentFeeServices'
        ,objectId:'".$this->objectId."'
    ";
    
    $OBJECT_GRID->setSaveParams("
        cmd: 'actionStudentFeeServices'
        ,objectId:'".$this->objectId."'
    ");
    
    $OBJECT_GRID->setAftereditCallback("
        if(window.parent.Ext.getCmp('FINANCE_LIST_ID'))
        window.parent.Ext.getCmp('FINANCE_LIST_ID').store.reload();
        Ext.getCmp('SERVICES_LIST_ID').store.reload();
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
    ");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            }
        }]);
    ");
    
    $OBJECT_GRID->isPagingToolbar = true;
    $OBJECT_GRID->isGridEditing = true;
    $OBJECT_GRID->loadMask = false;
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'fit'
            ,border: false
            ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}]
        }]
    });
    Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>