<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisGrid.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("COMMUNICATION", "SEND");
$OBJECT_GRID->setLoadUrl('/communication/jsonload/');
$OBJECT_GRID->setSaveUrl('/communication/jsonsave/');
$columndata = Utiles::getGridColumnData("COMMUNICATION_SEND_ID");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

    Ext.onReady(function() {
        
        function cssContent(value, metadata, record){
            return '<div style="padding: 5px;">'
            +'<span style="font-weight:bold; white-space:normal; color:#061f83;">' 
            + value + '</span><br/><br/>'
            +'<span style="font-weight:bold; white-space:normal; color:#000;">'+record.data.SEND_RECIPIENT+' &nbsp;&nbsp;</span><br/><br/>'
            +'<span style="font-weight:normal; white-space:normal; color:#555;"> ' 
            + record.data.CONTENT + '</span></div>';
        }
        
        function cssNumber(value, metadata, record){
            return '<div style="font-weight:normal; color:#061f83; padding: 5px;">' + value + '</div>';
        }
        
        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_GRID->addReadField("name: 'SUBJECT'");
        $OBJECT_GRID->addReadField("name: 'SEND_DATE'");
        //@sea peng 09.05.2013
        $OBJECT_GRID->addReadField("name: 'SEND_TYPE'");
        //@end sea peng 09.05.2013
        $OBJECT_GRID->addReadField("name: 'CONTENT'");
        $OBJECT_GRID->addReadField("name: 'SEND_RECIPIENT'");
        //$OBJECT_GRID->addColumn("header: '".SEND_TO."', align:'left', width: 300, sortable: false, dataIndex: 'SEND_RECIPIENT'");
        $OBJECT_GRID->addColumn("header: '".SUBJECT_EMAIL."', renderer:cssContent, width: 500, hidden:".checkColHidden(1, $columndata).", sortable: false, dataIndex: 'SUBJECT'");
        $OBJECT_GRID->addColumn("header: '".DATE."', renderer:cssNumber, width: 150, hidden:".checkColHidden(2, $columndata).", sortable: false, dataIndex: 'SEND_DATE'");
        //@sea peng 09.05.2013
        $OBJECT_GRID->addColumn("header: '".TYPE."', renderer:cssNumber, width: 150,  hidden:".checkColHidden(3, $columndata).",sortable: false, dataIndex: 'SEND_TYPE'");
        //@end sea peng 09.05.2013
        $OBJECT_GRID->baseParams = "
            start:0
            ,limit:100
            ,cmd: 'jsonLoadAllCommunications'
            ,type: 'SEND'
            ,academicId: '".$this->academicId."'
        ";
        $OBJECT_GRID->setRemoveSelectionParams("
            cmd: 'jsonRemoveCommunication'
            ,type: 'SEND'
            ,academicId: '".$this->academicId."'
        ");
        
        $OBJECT_GRID->setRemoveEmbeddedEvents("
            ".$OBJECT_GRID->getObjectXtype().".store.reload();
            Ext.getCmp('center').getLayout().setActiveItem(0);
        ");
        
        $OBJECT_GRID->forceFit = "false";
        $OBJECT_GRID->isQuickySearch = true;
        //$OBJECT_GRID->isCheckboxSelect = true;
        $OBJECT_GRID->renderJS();
        
        $viewport = "";
        
        $viewport .= "viewport = new Ext.Viewport({";
            $viewport .= "layout: 'fit'";
            $viewport .= ",border: false";
            $viewport .= " ,items: [{";
                $viewport .= "xtype: 'panel'";
                $viewport .= ",id: 'center'";
                $viewport .= ",border: false";
                $viewport .= ",layout: 'card'";
                $viewport .= ",activeItem: 0";  
                $viewport .= ",items:[{xtype: '".$OBJECT_GRID->getObjectXtype()."'}]";
            $viewport .= " }]";
        $viewport .= "});";
        
        echo $viewport;
            
        $js = "";
        $js .= "var myGrid = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');";
        $js .= "myGrid.on('rowClick', function(grid, rowIndex,event){";
            $js .= "var record = grid.store.getAt(rowIndex);";
            $js .= "var contextMenu = new Ext.menu.Menu({";
                $js .= "items: [{";
                    $js .= "text: '".SHOW_DETAIL." &raquo; ' + record.data.SUBJECT";
                    $js .= ",iconCls:'icon-application_form_magnify'";
                    $js .= ",handler: function(){clickOpenPage('center',record.data.SUBJECT,'".$this->URL_MAIL_SEND."&objectId=' + record.data.ID);}";
                $js .= "},{";
                    $js .= "text: '".REMOVE." &raquo; ' + record.data.SUBJECT";
                    $js .= ",iconCls:'icon-delete'";
                    $js .= ",handler: function(){";
                        $js .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                        $js .= "myGrid.onRemoveSelection();";
                    $js .= "}";
                $js .= "}]";
            $js .= "});";
            $js .= "event.stopEvent();";
            $js .= "contextMenu.showAt(event.xy); ";
        $js .= "});";
        //$js .= "Ext.TaskMgr.start(runTask);";
        echo $js;
        ?>
        Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>