<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisGrid.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("COMMUNICATION", "DRAFTS");
$OBJECT_GRID->setLoadUrl('/communication/jsonload/');
$OBJECT_GRID->setSaveUrl('/communication/jsonsave/');
$columndata = Utiles::getGridColumnData("COMMUNICATION_DRAFTS_ID");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

    Ext.onReady(function() {
        
        function cssContent(value, metadata, record){
            return '<div style="padding: 5px;">'
            +'<span style="font-weight:bold; white-space:normal; color:#061f83;">' 
            + value + '</span><br/><br/>'
            +'<span style="font-weight:bold; white-space:normal; color:#000;">'+record.data.COMMUNICATION+' &nbsp;&nbsp;</span><br/><br/>'
            +'<span style="font-weight:normal; white-space:normal; color:#555;"> ' 
            + record.data.CONTENT + '</span></div>';
        }
        function cssNumber(value, metadata, record){
            return '<div style="font-weight:normal; color:#061f83; padding: 5px;">' + value + '</div>';
        }   
        <?
       switch(UserAuth::getUserType()) {
            case "SUPERADMIN":
            case "ADMIN":
                $HIDDEN_MAIL_TO_TEACHER = "true";
                $HIDDEN_MAIL_TO_STUDENTS = "false";
                $HIDDEN_MAIL_TO_STAFF = "false";
            break;
            case "TEACHER":
            case "INSTRUCTOR":
                $HIDDEN_MAIL_TO_TEACHER = "false";
                $HIDDEN_MAIL_TO_STUDENTS = "false";
                $HIDDEN_MAIL_TO_STAFF = "true";
                break;
            case "STUDENT":
                $HIDDEN_MAIL_TO_TEACHER = "false";
                $HIDDEN_MAIL_TO_STUDENTS = "false";
                $HIDDEN_MAIL_TO_STAFF = "true";
            break;
        }
        
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_GRID->addTBarItems("
            tbar.add([{
                id: 'COMPOSE_MAIL'
                ,text: '".COMPOSE_MAIL."'
                ,menu:[{
                    id: 'MAIL_TO_TEACHER_ID'
                    ,text: '".MAIL_TO_TEACHER."'
                    ,hidden: ".$HIDDEN_MAIL_TO_TEACHER."
                    ,iconCls:'icon-application_form_add'
                    ,scope:this
                    ,handler: function(){
                        //Ext.getCmp('DRAFTS').collapse();
                        clickOpenPage('center','".MAIL_TO_TEACHER."', '".$this->URL_MAIL_TO_TEACHER."&objectId=new');
                    }
                 },{
                    id: 'MAIL_TO_STAFF_ID'
                    ,text: '".MAIL_TO_STAFF."'
                    ,hidden: ".$HIDDEN_MAIL_TO_STAFF."
                    ,iconCls:'icon-application_form_add'
                    ,scope:this
                    ,handler: function(){
                        //Ext.getCmp('DRAFTS').collapse();
                        clickOpenPage('center','".MAIL_TO_STAFF."', '".$this->URL_MAIL_TO_STAFF."&objectId=new');
                    }
                 },{
                    id: 'MAIL_TO_STUDENTS_ID'
                    ,text: '".MAIL_TO_STUDENTS."'
                    ,hidden: ".$HIDDEN_MAIL_TO_STUDENTS."
                    ,iconCls:'icon-application_form_add'
                    ,scope:this
                    ,handler: function(){
                        //Ext.getCmp('DRAFTS').collapse();
                        clickOpenPage('center','".MAIL_TO_STUDENTS."', '".$this->URL_MAIL_TO_STUDENTS."&objectId=new');
                    }
                 }]
            }]);
        ");
        
        $OBJECT_GRID->setRemoveSelectionParams("
            cmd: 'jsonRemoveCommunication'
            ,type: 'DRAFTS'
            ,academicId: '".$this->academicId."'
        ");
        
        $OBJECT_GRID->setRemoveEmbeddedEvents("
            ".$OBJECT_GRID->getObjectXtype().".store.reload();
            Ext.getCmp('center').getLayout().setActiveItem(0);
        ");
        
        $OBJECT_GRID->addReadField("name: 'SUBJECT'");
        $OBJECT_GRID->addReadField("name: 'ASSIGNED'");
        $OBJECT_GRID->addReadField("name: 'CONTENT'");
        $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");
        $OBJECT_GRID->addReadField("name: 'COMMUNICATION_TYPE'");
        $OBJECT_GRID->addReadField("name: 'COMMUNICATION'");
        //$OBJECT_GRID->addColumn("header: '".COMMUNICATION."', align:'left', width: 150, sortable: false, dataIndex: 'COMMUNICATION'");
        $OBJECT_GRID->addColumn("header: '".SUBJECT_EMAIL."', renderer:cssContent, width: 500, hidden:".checkColHidden(1, $columndata).", sortable: false, dataIndex: 'SUBJECT'");
        $OBJECT_GRID->addColumn("header: '".CREATED_DATE."', renderer:cssNumber, width: 150, hidden:".checkColHidden(2, $columndata).", sortable: false, dataIndex: 'CREATED_DATE'");
        $OBJECT_GRID->baseParams = "
            start:0
            ,limit:100
            ,cmd: 'jsonLoadAllCommunications'
            ,type: 'DRAFTS'
            ,academicId: '".$this->academicId."'
        ";
        $OBJECT_GRID->forceFit = "false";
        $OBJECT_GRID->isQuickySearch = true;
        //$OBJECT_GRID->isCheckboxSelect = true;
        $OBJECT_GRID->renderJS();
        
        $viewport = "";
        
        $viewport .= "viewport = new Ext.Viewport({";
            $viewport .= "layout: 'fit'";
            $viewport .= ",border: false";
            $viewport .= " ,items: [{";
                $viewport .= "xtype: 'panel'";
                $viewport .= ",id: 'center'";
                $viewport .= ",border: false";
                $viewport .= ",layout: 'card'";
                $viewport .= ",activeItem: 0";  
                $viewport .= ",items:[{xtype: '".$OBJECT_GRID->getObjectXtype()."'}]";
            $viewport .= " }]";
        $viewport .= "});";
        
        echo $viewport;
        
        $js = "";
        $js .= "var myGrid = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');";
        $js .= "myGrid.on('rowClick', function(grid, rowIndex,event){";
            $js .= "var record = grid.store.getAt(rowIndex);";
            $js .= "if(record){";
                $js .= "var objectId = record.data.ID;";
                $js .= "var communication_type = record.data.COMMUNICATION_TYPE;";

                $js .= "if (communication_type === 'STUDENT_TO_TEACHER'){";
                    $js .= "clickUrl = '".$this->URL_MAIL_TO_TEACHER."objectId=' +objectId;";
                $js .= "}";
                $js .= "else if (communication_type === 'STAFF_TO_STAFF'){";
                    $js .= "clickUrl = '".$this->URL_MAIL_TO_STAFF."objectId=' + objectId";
                $js .= "}";
                $js .= "else if (communication_type === 'TEACHER_TO_STUDENTS'){";
                    $js .= "clickUrl = '".$this->URL_MAIL_TO_STUDENTS."objectId=' + objectId";
                $js .= "}";
                $js .= "else if (communication_type === 'REPLY_DRAFTS'){";
                    $js .= "clickUrl = '".$this->URL_MAIL_REPLY_DRAFTS."objectId=' + objectId";
                $js .= "}else{";
                    $js .= "clickUrl = '".$this->URL_MAIL_TO_TEACHER."objectId=' +objectId";
                $js .= "}";
            $js .= "}";
            $js .= "var contextMenu = new Ext.menu.Menu({";
                $js .= "items: [{";
                    $js .= "text: '".SHOW_DETAIL." &raquo; ' + record.data.SUBJECT";
                    $js .= ",iconCls:'icon-application_form_magnify'";
                    $js .= ",handler: function(){clickOpenPage('center',record.data.SUBJECT,clickUrl);}";
                $js .= "},{";
                    $js .= "text: '".REMOVE." &raquo; ' + record.data.SUBJECT";
                    $js .= ",iconCls:'icon-delete'";
                    $js .= ",handler: function(){";
                        $js .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                        $js .= "myGrid.onRemoveSelection();";
                    $js .= "}";
                $js .= "}]";
            $js .= "});";
            $js .= "event.stopEvent();";
            $js .= "contextMenu.showAt(event.xy); ";
        $js .= "});";
        //$js .= "Ext.TaskMgr.start(runTask);";
        echo $js;
        ?>
        Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));n
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>