<?
///////////////////////////////////////////////////////////
// @sea peng 22.04.2013
//////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";
$studentObject = StudentDBAccess::findStudentFromId($objectId);
$FULL_NAME=$studentObject->LASTNAME . ' '. $studentObject->FIRSTNAME;
$PAGE_NAME = isset($_GET["page_name"])? addText($_GET["page_name"]):"";

$OBJECT_FORM = new CamemisForm("COMMUNICATION");
$OBJECT_FORM->setLoadUrl('/communication/jsonload/');
$OBJECT_FORM->setSaveUrl('/communication/jsonsave/');

$OBJECT_GRID = new CamemisGrid("STUDENT", "LIST_OF_STUDENTS");
$OBJECT_GRID->setLoadUrl("/student/jsonload/");
$OBJECT_GRID->setSaveUrl("/student/jsonsave/");

$OBJECT_FORM_CHOSE = new CamemisForm("STUDENTTYPE");
$OBJECT_FORM_CHOSE->setLoadUrl('/dataset/jsonload/');
$OBJECT_TREE = new CamemisTree("COMMUNICATION", "LIST");
$OBJECT_TREE->setURL("/communication/jsontree/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    <?
    /**
     * Extjs: s.gif
     */
     
     //////////////////////////////////////////
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_TREE->setBaseParams("
        cmd: 'jsonTreeAllCommunicationSubject'
        ,objectType: 'COMMUNICATION_TYPE'
    ");
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->renderJS();  
     /////////////////////////////////////////
     
     $SEND_TYPE_STORE = "[
        ['EMAIL', '" . EMAIL . "']
        ,['SMS', 'SMS']
        ,['MESSAGE', '" . MESSAGE . "']
    ]";
    
    $SEND_TYPE = "
    {
        title: 'Send Type'
        ,autoHeight: true
        ,frame:false
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#F9F9F9;padding:10px'
            ,items: [{".CamemisField::Combo("SEND_TYPE",TYPE, $SEND_TYPE_STORE,false, false, false)."}]
        }]
    }";
    
    //@email
    $SUBJECT_EMAIL_ITEM = "
    {
        title: '".SUBJECT."'
        ,id:'SUBJECT_EMAIL_ITEM_ID'
        ,hidden:true
        ,autoHeight: true
        ,frame:false
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#F9F9F9;padding:5px'
            ,items:[{".CamemisField::Textarea("SUBJECT_EMAIL",'',50,false, false, false)."}]
        }]
        ,tbar:[{
            text: '".REMOVE."'
            ,iconCls:'icon-delete'
            ,handler: function(){
                Ext.getCmp('SUBJECT_EMAIL_ID').setValue('');
            }
        },{
            text: '".TEMPLATE."'
            ,iconCls:'icon-lightning'
            ,handler: function(){
                openWinXType('TEMPLATE','".TEMPLATE."', '".$OBJECT_TREE->getObjectXType()."', percentWidth(45), percentHeight(90));
                var academicTree = Ext.getCmp('".$OBJECT_TREE->getObjectId()."');
                academicTree.on('click', function(node, e){
                    if(node.isLeaf()){
                        Ext.getCmp('SUBJECT_EMAIL_ID').setValue(node.text);
                        Ext.getCmp('TEMPLATE').close(); 
                    }        
                });  
            }
        }]
    }";
    
    $CONTENT_EMAIL_ITEM = "
    {
        title: '".CONTENT."'
        ,id:'CONTENT_EMAIL_ITEM_ID'
        ,hidden:true
        ,autoHeight: true
        ,frame:false
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#F9F9F9;padding:5px'
            ,items:[{".CamemisField::Textarea("CONTENT_EMAIL",'',100,false,false,false)."}]
        },{
            layout: 'form'
            ,border: false
            ,bodyStyle: 'padding:5px'
            ,items: [{".CamemisField::Hidden("EMAIL",$studentObject->EMAIL)."}]
        }]
    }";
    //@end email
    
    //@sms
    $CONTENT_PHONE_ITEM = "
    {
        title: '".CONTENT."'
        ,id:'CONTENT_PHONE_ITEM_ID'
        ,hidden:true
        ,autoHeight: true
        ,frame:false
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#F9F9F9;padding:5px;'
            ,items:[{".CamemisField::Textarea("CONTENT_PHONE",'',100,false,false,false)."}]
        },{
            layout: 'form'
            ,border: false
            ,bodyStyle: 'padding:5px'
            ,items: [{".CamemisField::Hidden("MOBIL_PHONE",$studentObject->MOBIL_PHONE)."}]
        }]
        ,tbar:[{
            text: '".REMOVE."'
            ,iconCls:'icon-delete'
            ,handler: function(){
                Ext.getCmp('CONTENT_PHONE_ID').setValue('');
            }
        },{
            text: '".TEMPLATE."'
            ,iconCls:'icon-lightning'
            ,handler: function(){
                openWinXType('TEMPLATE','".TEMPLATE."', '".$OBJECT_TREE->getObjectXType()."', percentWidth(45), percentHeight(90));
                var academicTree = Ext.getCmp('".$OBJECT_TREE->getObjectId()."');
                academicTree.on('click', function(node, e){
                    if(node.isLeaf()){
                        Ext.getCmp('CONTENT_PHONE_ID').setValue(node.text);
                        Ext.getCmp('TEMPLATE').close(); 
                    }        
                }); 
            }
        }]
    }";
    //@end sms
    
    //@message
    $SUBJECT_MESSAGE_ITEM = "
    {
        title: '".SUBJECT."'
        ,id:'SUBJECT_MESSAGE_ITEM_ID'
        ,hidden:true
        ,autoHeight: true
        ,frame:false
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#F9F9F9;padding:5px'
            ,items:[{".CamemisField::Textarea("SUBJECT_MESSAGE",'',50,false, false, false)."}]
        }]
        ,tbar:[{
            text: '".REMOVE."'
            ,iconCls:'icon-delete'
            ,handler: function(){
                Ext.getCmp('SUBJECT_MESSAGE_ID').setValue('');
            }
        },{
            text: '".TEMPLATE."'
            ,iconCls:'icon-lightning'
            ,handler: function(){
                openWinXType('TEMPLATE','".TEMPLATE."', '".$OBJECT_TREE->getObjectXType()."', percentWidth(45), percentHeight(90));
                var academicTree = Ext.getCmp('".$OBJECT_TREE->getObjectId()."');
                academicTree.on('click', function(node, e){
                    if(node.isLeaf()){
                        Ext.getCmp('SUBJECT_MESSAGE_ID').setValue(node.text);
                        Ext.getCmp('TEMPLATE').close(); 
                    }        
                });  
            }
        }]
    }";
    
    $CONTENT_MESSAGE_ITEM = "
    {
        title: '".CONTENT."'
        ,id:'CONTENT_MESSAGE_ITEM_ID'
        ,hidden:true
        ,autoHeight: true
        ,frame:false
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#F9F9F9;padding:5px'
            ,items:[{".CamemisField::Textarea("CONTENT_MESSAGE",'',100,false,false,false)."}]
        }]
    }";
    //@end message
    
    $ITEMS = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: [
            " . $SEND_TYPE . "
            ," . $SUBJECT_EMAIL_ITEM . "
            ," . $CONTENT_EMAIL_ITEM . " 
            ," . $CONTENT_PHONE_ITEM . "
            ," . $SUBJECT_MESSAGE_ITEM . "
            ," . $CONTENT_MESSAGE_ITEM . "
        ]
    ";
    
    $OBJECT_FORM->addObjectItems($ITEMS);

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        }
    ");
    
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetSend());

    $OBJECT_FORM->setLoadParams("
        cmd: 'jsonLoadCommunication'
        ,objectId: '".$this->objectId."'
        ,academicId: '".$this->academicId."'
    ");

    $OBJECT_FORM->setSendParams("
        cmd: 'jsonActionSingleCommunication'
        ,objectId: '".$this->objectId."'
        ,academicId: '".$this->academicId."'
        ,STR_RECIPIENT: '".$studentObject->ID."'
        ,communication_type: 'TEACHER_TO_STUDENTS'
        ,interface_type: 1
        ,STR_RECIPIENT_NAME: '".$FULL_NAME."'
        ,recipient_type: 'STUDENT'
        ,sender_type: 'STAFF'
        ,action: 'SEND'
    ");
    
    switch ($PAGE_NAME){
        case "loadstudentlist":
            $OBJECT_FORM->setOnEmbeddedSendEvents("
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('STUDENT_ENROLLED_STUDENTS_ID').store.reload();
            ");
            break;
        default:
            $OBJECT_FORM->setOnEmbeddedSendEvents("
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('STUDENT_STUDENTSEARCH_ID').store.reload();
            ");
            break;
    }
    
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->isObjectSend = true;
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,layout: 'fit'
            ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
        }]
    });
    
    Ext.getCmp('SEND_TYPE_ID').on('select', function() {
        switch(Ext.getCmp('SEND_TYPE_ID').getValue()){
            case 'EMAIL':
                Ext.getCmp('SUBJECT_EMAIL_ITEM_ID').show();
                Ext.getCmp('CONTENT_EMAIL_ITEM_ID').show();
                Ext.getCmp('CONTENT_PHONE_ITEM_ID').hide();
                Ext.getCmp('SUBJECT_MESSAGE_ITEM_ID').hide();
                Ext.getCmp('CONTENT_MESSAGE_ITEM_ID').hide();
                <? 
                    if($studentObject->EMAIL == '' or $studentObject->EMAIL == '?'){
                       print("Ext.getCmp('SEND_ID').hide();");              
                    }else{
                        print("Ext.getCmp('SEND_ID').show();");
                    }
                ?>
            break;
            case 'SMS':
                Ext.getCmp('SUBJECT_EMAIL_ITEM_ID').hide();
                Ext.getCmp('CONTENT_EMAIL_ITEM_ID').hide();
                Ext.getCmp('CONTENT_PHONE_ITEM_ID').show();
                Ext.getCmp('SUBJECT_MESSAGE_ITEM_ID').hide();
                Ext.getCmp('CONTENT_MESSAGE_ITEM_ID').hide();
                <? 
                    if($studentObject->PHONE == '' or $studentObject->PHONE == '?'){
                       print("Ext.getCmp('SEND_ID').hide();");              
                    }else{
                        print("Ext.getCmp('SEND_ID').show();");
                    }
                ?>
                
            break;
            case 'MESSAGE':
                Ext.getCmp('SUBJECT_EMAIL_ITEM_ID').hide();
                Ext.getCmp('CONTENT_EMAIL_ITEM_ID').hide();
                Ext.getCmp('CONTENT_PHONE_ITEM_ID').hide();
                Ext.getCmp('SUBJECT_MESSAGE_ITEM_ID').show();
                Ext.getCmp('CONTENT_MESSAGE_ITEM_ID').show();
                Ext.getCmp('SEND_ID').show();
            break;
        }
    });   
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>