<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_school/staff/StaffDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("STAFF", "HISTORY");
$OBJECT_TREE->setURL('/staff/jsontree/');

$defaultClassObject = StaffDBAccess::getSubjectTeacherClass($this->objectId);

$classObject = AcademicDBAccess::findGradeFromId($defaultClassObject->ID);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    
    var clickTitle = '';
    var classId;
    var schoolyearId;
    var academicIds;
    var gradeId;
    var teacherId = '<?=$this->objectId;?>';
    
    Ext.onReady(function() {

        
        <?
        camemisPage::setNoLogoutMessage();
        
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        //History tree...
        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        
        $OBJECT_TREE->setBaseParams("
            cmd: 'academicHistoryTree'
            ,objectId: '".$this->objectId."'
        ");
        
        $OBJECT_TREE->backgroundColor = "#EEE";
        $OBJECT_TREE->isTreeExpand = true;
        $OBJECT_TREE->isOnClickContextMenu = false;
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    region:'west'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width:350
                    ,minSize:350
                    ,maxSize:350
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                },{
                    collapsible: false
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,border:false
                    ,items: [new Ext.ux.IFrameComponent({ id: 'MAIN_CONTENT', url: '/staff/showclassmain/?objectId=<?=$this->objectId;?>&classId=<?=$classObject->ID;?>'})]
                }]
            }]
        });
        var myTree = <?=$OBJECT_TREE->ExtgetCmp()?>;
        if (myTree) myTree.on('click', function(node, event){
            
            switch(node.attributes.treeType){
                case 'CLASS':
                    clickOpenPage('center','', '/staff/showclassmain/?objectId=<?=$this->objectId;?>&classId='+node.attributes.classId);
                    break;
                case 'SUBJECT':
                    clickOpenPage('center','', '/staff/showsubjectmain/?objectId=<?=$this->objectId;?>&classId='+node.attributes.classId+'&subjectId='+node.attributes.subjectId);
                break;
            } 
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>