<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        $WEEK = "{
            title: '".WEEK."'
            ,height:380
            ,layout: 'fit'
            ,border: false
            ,items: [new Ext.ux.IFrameComponent({ id: 'YEAR', url:'/chart/staffattendance/?camIds=".$this->urlEncryp->encryptedGet("objectType=WEEKLY")."'})]
        }";
        $PENEL_ITEMS[] = $WEEK;

        $MONTH = "{
            title: '".MONTH."'
            ,height:380
            ,layout: 'fit'
            ,border: false
            ,items: [new Ext.ux.IFrameComponent({ id: 'YEAR', url:'/chart/staffattendance/?camIds=".$this->urlEncryp->encryptedGet("objectType=MONTHLY")."'})]
        }";
        $PENEL_ITEMS[] = $MONTH;

        $YEAR = "{
            title: '".YEAR."'
            ,height:380
            ,layout: 'fit'
            ,border: false
            ,items: [new Ext.ux.IFrameComponent({ id: 'YEAR', url:'/chart/staffattendance/?camIds=".$this->urlEncryp->encryptedGet("objectType=YEARLY")."'})]
        }";
        $PENEL_ITEMS[] = $YEAR;

        $CHOOSE_PANEL = implode(',',$PENEL_ITEMS);
        ////////////////////////////////////////////////////////////////////////
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:[<?=$CHOOSE_PANEL?>]
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>