<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("COMMUNICATION");
$OBJECT_FORM->setLoadUrl('/communication/jsonload/');
$OBJECT_FORM->setSaveUrl('/communication/jsonsave/');

$SENDER_DATA = $this->senderData;
$OBJECT_DATA = $this->objectData;

if (UserAuth::getUserType() == "STUDENT"){
    $COMMUNICATION_TYPE = "STUDENT_TO_TEACHER";
}else{
    $COMMUNICATION_TYPE = $SENDER_DATA["COMMUNICATION_TYPE"];
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<style>
    .container{
        font-size: 1em;
        margin: 15px 15px 15px 15px;
    }
    .container ul{
        margin-left: 20px;
    }
    .container li{
        list-style: disc;
    }
    .container h2{
        margin-bottom: 3px;
    }
</style>
<div id="initContainer" class="x-hidden" >
    <?=isset($OBJECT_DATA["CONTENT"])?nl2br($OBJECT_DATA["CONTENT"]):"---";?>
</div>
<script>
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {".CamemisField::Textfield("SUBJECT", "SUBJECT", SUBJECT_EMAIL, true, false)."}
                    ,{".CamemisField::Displayfield("STR_RECIPIENT_NAME", RECIPIENT, false)."}
                ]
            }]
        }
        ";

        $CONTENT_INBOX = "
        {
            title: '".INBOX."'
            ,layout: 'fit'
            ,border: true
            ,width: 550
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,bodyStyle: 'padding:10px'
            ,items: [{
                layout: 'fit'
                ,border: false
                ,contentEl: 'initContainer'
            }]
        }
        ";

        $CONTENT_REPLY = "
        {
            title: '".REPLY."'
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,style: 'padding: 5px'
                ,items:[{".CamemisField::HTML("CONTENT_REPLY",false,false)."}]
            }]
        }
        ";
        
        $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,width: 550
        ,bodyStyle: 'padding:0px'
        ,items: [
            ".$DETAIL_INFORMATION."
            ,".$CONTENT_INBOX."
            ,".$CONTENT_REPLY."
        ]
        ";
        $OBJECT_FORM->addObjectItems($items);

        $OBJECT_FORM->addTBarItems("
            text: '".INBOX."'
            ,id: 'INBOX_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('INBOX_PANEL').getLayout().setActiveItem(0);}
        ");

        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetSend());
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
            
        $OBJECT_FORM->setLoadParams("
            cmd: 'jsonLoadAddReplyCommunication'
            ,objectId: '".$this->objectId."'
            ,academicId: '".$this->academicId."'
        ");
        
        $OBJECT_FORM->setSendParams("
            cmd: 'jsonSendCommunication'
            ,objectId: 'new'
            ,parentId: '".$this->objectId."'
            ,academicId: '".$this->academicId."'
            ,communication_type: '".$COMMUNICATION_TYPE."'
            ,recipient_type: '".$SENDER_DATA["RECIPIENT_TYPE"]."'
            ,sender_type: '".$SENDER_DATA["SENDER_TYPE"]."'
            ,STR_RECIPIENT_NAME: '".$SENDER_DATA["STR_RECIPIENT_NAME"]."'
            ,STR_RECIPIENT_ID: '".$SENDER_DATA["STR_RECIPIENT_ID"]."'
            ,action: 'REPLY_SEND'
        ");

        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonSaveCommunication'
            ,objectId: 'new'
            ,parentId: '".$this->objectId."'
            ,academicId: '".$this->academicId."'
            ,communication_type: '".$COMMUNICATION_TYPE."'
            ,recipient_type: '".$SENDER_DATA["RECIPIENT_TYPE"]."'
            ,sender_type: '".$SENDER_DATA["SENDER_TYPE"]."'
            ,sender_type: '".$SENDER_DATA["SENDER_TYPE"]."'
            ,STR_RECIPIENT_NAME: '".$SENDER_DATA["STR_RECIPIENT_NAME"]."'
            ,STR_RECIPIENT_ID: '".$SENDER_DATA["STR_RECIPIENT_ID"]."'
            ,action: 'REPLY_DRAFTS'
        ");
        
        $OBJECT_FORM->setRemoveParams("
            cmd: 'jsonRemoveCommunication'
            ,objectId: '".$this->objectId."'
        ");

        $OBJECT_FORM->setonEmbeddedEvents("
            window.parent.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->setOnEmbeddedSendEvents("
            window.parent.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            window.parent.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->isObjectSend = true;
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
               border: false
                ,layout: 'fit'
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                }]
            }]
        });
    });
</script>
<?
//print_r($SENDER_DATA);
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>