<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("COMMUNICATION");
$OBJECT_FORM->setLoadUrl('/communication/jsonload/');
$OBJECT_FORM->setSaveUrl('/communication/jsonsave/');

$senderData = $this->senderData;

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: percentWidth(85)
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {".CamemisField::Textfield("SUBJECT", "SUBJECT", SUBJECT_EMAIL, true, false)."}
                    ,{".CamemisField::Displayfield("STR_RECIPIENT_NAME", RECIPIENT, false)."}
                    ,{".CamemisField::Hidden("STR_RECIPIENT",false)."}
                ]
            }]
        }
        ";
        
        $CONTENT_REPLY = "
        {
            title: ''
            ,layout: 'fit'
            ,border: false
            ,width: percentWidth(85)
            ,height: 350
            ,items:[{".CamemisField::HTML("CONTENT",false,false)."}]
        }
        ";
        $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,width: percentWidth(85)
        ,bodyStyle: 'padding:0px'
        ,items: [
            ".$DETAIL_INFORMATION.",".$CONTENT_REPLY."
        ]
        ";
        $OBJECT_FORM->addObjectItems($items);

        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        ");

        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetSend());
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
            
        $OBJECT_FORM->setLoadParams("
            cmd: 'jsonLoadReplyCommunication'
            ,objectId: '".$this->objectId."'
            ,academicId: '".$this->academicId."'
        ");
        
        $OBJECT_FORM->setSendParams("
            cmd: 'jsonSendCommunication'
            ,objectId: '".$this->objectId."'
            ,academicId: '".$this->academicId."'
            ,communication_type: '".$senderData["COMMUNICATION_TYPE"]."'
            ,recipient_type: '".$senderData["RECIPIENT_TYPE"]."'
            ,sender_type: '".$senderData["SENDER_TYPE"]."'
            ,action: 'SEND'
        ");

        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonSaveCommunication'
            ,objectId: '".$this->objectId."'
            ,academicId: '".$this->academicId."'
            ,communication_type: 'REPLY_DRAFTS'
            ,recipient_type: '".$senderData["RECIPIENT_TYPE"]."'
            ,sender_type: '".$senderData["SENDER_TYPE"]."'
            ,action: 'REPLY_DRAFTS'
        ");

        $OBJECT_FORM->setRemoveParams("
            cmd: 'jsonRemoveCommunication'
            ,objectId: '".$this->objectId."'
        ");

        $OBJECT_FORM->setonEmbeddedEvents("
            window.parent.Ext.getCmp('COMMUNICATION_DRAFTS_ID').store.reload();
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->setOnEmbeddedSendEvents("
            window.parent.Ext.getCmp('COMMUNICATION_DRAFTS_ID').store.reload();
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            window.parent.Ext.getCmp('COMMUNICATION_DRAFTS_ID').store.reload();
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->isObjectSend = true;
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'panel'
                ,id: 'panel'
                ,border: false
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                }]
            }]
        });
    });
</script>
<?
//print_r($this->senderData);
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>