<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("COMMUNICATION");
$OBJECT_FORM->setLoadUrl('/communication/jsonload/');
$OBJECT_FORM->setSaveUrl('/communication/jsonsave/');

$OBJECT_DATA = $this->objectData;

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<style>
    .container{
        font-size: 1em;
        padding-left: 15px;
        margin: 15px 15px 15px 15px;
    }
    .container ul{
        margin-left: 20px;
    }
    .container li{
        list-style: disc;
    }
    .container h2{
        margin-bottom: 3px;
    }
</style>

<div id="initRecipient" class="x-hidden" >
    <?=isset($OBJECT_DATA["SEND_RECIPIENT"])?nl2br($OBJECT_DATA["SEND_RECIPIENT"]):"---";?>
</div>
<div id="initContainer" class="x-hidden" >
    <?=isset($OBJECT_DATA["CONTENT"])?nl2br($OBJECT_DATA["CONTENT"]):"---";?>
</div>
<script>
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {".CamemisField::Displayfield("SUBJECT", SUBJECT_EMAIL, false)."}
                    ,{".CamemisField::Displayfield("SENT_ON", SENT_ON, false)."}
                ]
            }]
        }
        ";

        $RECIPIENT = "
        {
            title: '".RECIPIENT."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,contentEl: 'initRecipient'
                }]
            }]
        }
        ";
        
        $CONTENT = "
        {
            title: '".TEXT."'
            ,layout: 'fit'
            ,border: true
            ,width: 550
            ,autoHeight: true
            ,items: [{
                layout: 'fit'
                ,border: false
                ,contentEl: 'initContainer'
            }]
        }
        ";
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,width: 550
            ,bodyStyle: 'padding:0px'
            ,items: [
                ".$DETAIL_INFORMATION.",".$RECIPIENT.",".$CONTENT."
            ]
        ";
        $OBJECT_FORM->addObjectItems($items);

        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        ");

        $OBJECT_FORM->setLoadParams("
            cmd: 'jsonLoadCommunication'
            ,objectId: '".$this->objectId."'
            ,academicId: '".$this->academicId."'
        ");

        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'panel'
                ,id: 'panel'
                ,border: false
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                }]
            }]
        });
    });
</script>
<?
//print_r($OBJECT_DATA);
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>