<?
///////////////////////////////////////////////////////////
// @Sor Veasna
// Date: 20.11.2013
// 
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisGrid.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$PREREQUISITE_COURSE_GRID = new CamemisGrid("STUDENTS_PREREQUISITE_COURSE", "LIST");
$PREREQUISITE_COURSE_GRID->setLoadUrl("/student/jsonload/");
$PREREQUISITE_COURSE_GRID->setSaveUrl("/student/jsonsave/");

if(!$this->facette) {header("Location: /main/permission/");}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

Ext.onReady(function() {
    function cssStatus(v, p, record){
        return String.format('<div style=\"font-weight:bold;padding:4px;background:{1};color:{2};\">{0}</div>'
        ,v
        ,record.data['BG_COLOR']
        ,record.data['BG_COLOR_FONT']
        );
    }
       
    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#000; padding: 5px; height: 15px;;">' + value + '</div>';
    }
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $PREREQUISITE_COURSE_GRID->addTBarItems("
        tbar.add('-',[{
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('ACADEMIC_ID').expand();
            }
        }]);
    ");  
    
    $PREREQUISITE_COURSE_GRID->addReadField("name: 'ID'");
    $PREREQUISITE_COURSE_GRID->addReadField("name: 'SUBJECT_NAME'");
    $PREREQUISITE_COURSE_GRID->addReadField("name: 'STUDENT_NAME'");
    $PREREQUISITE_COURSE_GRID->addReadField("name: 'STUDIED'");
    $PREREQUISITE_COURSE_GRID->addReadField("name: 'PASS'");
    $PREREQUISITE_COURSE_GRID->addReadField("name: 'ACADEMIC'");
    $PREREQUISITE_COURSE_GRID->addReadField("name: 'STATUS'");
    
    $PREREQUISITE_COURSE_GRID->addReadField("name: 'BG_COLOR'");
    $PREREQUISITE_COURSE_GRID->addReadField("name: 'BG_COLOR_FONT'");
    $PREREQUISITE_COURSE_GRID->addReadField("name: 'STATUS_KEY'");
   
   switch(Zend_Registry::get('SYSTEM_LANGUAGE')){
        case "VIETNAMESE": $width = 125;break;
        default: $width = 85;break;
    }
    
    $PREREQUISITE_COURSE_GRID->addColumn("header: '<b>".SUBJECT."</b>', width: 120, renderer: cssText, sortable: true, dataIndex: 'SUBJECT_NAME'");
    $PREREQUISITE_COURSE_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: ".$width.", renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY'");
    $PREREQUISITE_COURSE_GRID->addColumn("header: '<b>".STUDENT."</b>', width: 150, renderer: cssText, sortable: true, dataIndex: 'STUDENT_NAME'");
    //$PREREQUISITE_COURSE_GRID->addColumn("header: '<b>STUDIED</b>', width: 80, renderer: cssText, sortable: true, dataIndex: 'STUDIED'");
    //$PREREQUISITE_COURSE_GRID->addColumn("header: '<b>PASS</b>', align:'center',  width: 80, renderer: cssText, sortable: true, dataIndex: 'PASS'");
    $PREREQUISITE_COURSE_GRID->addColumn("header: '<b>".ACADEMIC."</b>', width: 150, renderer: cssText, sortable: true, dataIndex: 'ACADEMIC'");
    $PREREQUISITE_COURSE_GRID->addColumn("header: '<b>".STATUS."</b>', width: 150, renderer: cssText, sortable: true, dataIndex: 'STATUS'");
           
    $PREREQUISITE_COURSE_GRID->baseParams = "
        start:0
        ,limit:100
        ,academicId: '".$this->objectId."'
        ,schoolyear: '".$this->facette->SCHOOL_YEAR."'
        ,requisiteId: '".$this->facette->SUBJECT_ID."'
        ,cmd: 'jsonListStudentPreRequisiteCourse'
    ";
   
    $PREREQUISITE_COURSE_GRID->isGroupingView = true;
    $PREREQUISITE_COURSE_GRID->groupField='SUBJECT_NAME';
    $PREREQUISITE_COURSE_GRID->isObjectDefaultOnLoad = true;
    $PREREQUISITE_COURSE_GRID->forceFit = "false";
    $PREREQUISITE_COURSE_GRID->renderJS();
    ///////////////////////////////////////////////////////
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'fit'
            ,border: false
            ,items:[{xtype: '<?=$PREREQUISITE_COURSE_GRID->getObjectXtype();?>'}]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>