<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$setParams = "";
$setParams .= "&objectId=".$this->studentId."";
$setParams .= "&academicId=".$this->academicId."";
$setParams .= "&schoolyearId=".$this->schoolyearId."";

$setParamsFirstSemester = $setParams."&term=FIRST_SEMESTER";
$setParamsSecondSemester = $setParams."&term=SECOND_SEMESTER";

$setParamsFirstTerm = $setParams."&term=FIRST_TERM";
$setParamsSecondTerm = $setParams."&term=SECOND_TERM";
$setParamsThirdTerm = $setParams."&term=THIRD_TERM";

$setParamsFirstQuarter = $setParams."&term=FIRST_QUARTER";
$setParamsSecondQuarter = $setParams."&term=SECOND_QUARTER";
$setParamsThirdQuarter = $setParams."&term=THIRD_QUARTER";
$setParamsFourthQuarter = $setParams."&term=FOURTH_QUARTER";

?>

<script>
	Ext.onReady(function() {

		<?
		$CAMEMIS_PAGE_OBJECT->setCostumerCSS();
		$CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

		$FIRST_SEMESTER = "{
			title: '".FIRST_SEMESTER."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'FIRST_SEMESTER', url: '/student/weekcreditevent/?camIds=".$this->urlEncryp->encryptedGet($setParamsFirstSemester)."'})]
		}";

		$SECOND_SEMESTER = "{
			title: '".SECOND_SEMESTER."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'SECOND_SEMESTER', url: '/student/weekcreditevent/?camIds=".$this->urlEncryp->encryptedGet($setParamsSecondSemester)."'})]
		}";

		$FIRST_TERM = "{
			title: '".FIRST_TERM."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'FIRST_TERM', url: '/student/weekcreditevent/?camIds=".$this->urlEncryp->encryptedGet($setParamsFirstTerm)."'})]
		}";

		$SECOND_TERM = "{
			title: '".SECOND_TERM."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'SECOND_TERM', url: '/student/weekcreditevent/?camIds=".$this->urlEncryp->encryptedGet($setParamsSecondTerm)."'})]
		}";

		$THIRD_TERM = "{
			title: '".THIRD_TERM."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'THIRD_TERM', url: '/student/weekcreditevent/?camIds=".$this->urlEncryp->encryptedGet($setParamsThirdTerm)."'})]
		}";

		$FIRST_QUARTER = "{
			title: '".FIRST_QUARTER."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'FIRST_QUARTER', url: '/student/weekcreditevent/?camIds=".$this->urlEncryp->encryptedGet($setParamsFirstQuarter)."'})]
		}";

		$SECOND_QUARTER = "{
			title: '".SECOND_QUARTER."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'SECOND_QUARTER', url: '/student/weekcreditevent/?camIds=".$this->urlEncryp->encryptedGet($setParamsSecondQuarter)."'})]
		}";

		$THIRD_QUARTER = "{
			title: '".THIRD_QUARTER."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'THIRD_QUARTER', url: '/student/weekcreditevent/?camIds=".$this->urlEncryp->encryptedGet($setParamsThirdQuarter)."'})]
		}";

		$FOURTH_QUARTER = "{
			title: '".FOURTH_QUARTER."'
			,layout: 'fit'
			,items:[new Ext.ux.IFrameComponent({ id: 'FOURTH_QUARTER', url: '/student/weekcreditevent/?camIds=".$this->urlEncryp->encryptedGet($setParamsFourthQuarter)."'})]
		}";

		$ACADEMIC_SETTING_ITEMS = "[";
        switch (AcademicDBAccess::findAcademicTerm($this->academicId)) {
			case 1:
				$ACADEMIC_SETTING_ITEMS .= $FIRST_TERM;
				$ACADEMIC_SETTING_ITEMS .= ",".$SECOND_TERM;
				$ACADEMIC_SETTING_ITEMS .= ",".$THIRD_TERM;
				break;
			case 2:
				$ACADEMIC_SETTING_ITEMS .= $FIRST_QUARTER;
				$ACADEMIC_SETTING_ITEMS .= ",".$SECOND_QUARTER;
				$ACADEMIC_SETTING_ITEMS .= ",".$THIRD_QUARTER;
				$ACADEMIC_SETTING_ITEMS .= ",".$FOURTH_QUARTER; 
				break;
			default:
				$ACADEMIC_SETTING_ITEMS .= $FIRST_SEMESTER;
				$ACADEMIC_SETTING_ITEMS .= ",".$SECOND_SEMESTER;
				break;
			}
		$ACADEMIC_SETTING_ITEMS .= "]";

		?>
		viewport = new Ext.Viewport({
			layout: 'fit'
			,border: false
			,items:[{
				layout:'fit'
				,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
				,border:false
				,items:[{
					xtype: 'tabpanel'
					,plain:true
					,activeTab: 0
					,tabPosition: 'top'
					,items: <?=$ACADEMIC_SETTING_ITEMS;?>
				}]
			}]
		});
	});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>