<?
///////////////////////////////////////////////////////////
// @sor veasna
// Date: 29/11/2013
// 
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_school/AcademicDateDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("SCHEDULE", "LIST");
$OBJECT_GRID->setLoadUrl("/schedule/jsonload/");
$OBJECT_GRID->setSaveUrl("/schedule/jsonsave/");

$DB_SCHOOLYEAR = AcademicDateDBAccess::getInstance();
 
$schoolyearObject = $DB_SCHOOLYEAR->findAcademicDateFromId($this->schoolyearId);

$YEAR_DATE = $schoolyearObject?getShowDate($schoolyearObject->START):"";
$YEAR_DATE .= " - ";
$YEAR_DATE .= $schoolyearObject?getShowDate($schoolyearObject->END):"";

$FIRST_SEMESTER_DATE = $schoolyearObject?getShowDate($schoolyearObject->SEMESTER1_START):"";
$FIRST_SEMESTER_DATE .= " - ";
$FIRST_SEMESTER_DATE .= $schoolyearObject?getShowDate($schoolyearObject->SEMESTER1_END):"";

$SECOND_SEMESTER_DATE = $schoolyearObject?getShowDate($schoolyearObject->SEMESTER2_START):"";
$SECOND_SEMESTER_DATE .= " - ";
$SECOND_SEMESTER_DATE .= $schoolyearObject?getShowDate($schoolyearObject->SEMESTER2_END):"";
        
      
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    
    function styleTime(v, p, record, rowIndex){
        return String.format('<div style=\"font-weight:bold; padding: 20px; height: 35px;background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['COLOR']
            ,record.data['COLOR_FONT']
        );
    }
    
    function showText(v, p, record, rowIndex){
        return String.format('<div style=\"white-space:normal;font-weight:bold; padding: 20px; height: 35px; background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['COLOR']
            ,record.data['COLOR_FONT']
        );
    }
    
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    $OBJECT_GRID->addReadField("name: 'ID'");
    $OBJECT_GRID->addReadField("name: 'TIME'");
    $OBJECT_GRID->addReadField("name: 'SCHEDULE_TYPE'");
    $OBJECT_GRID->addReadField("name: 'EVENT'");
    $OBJECT_GRID->addReadField("name: 'TEACHER'");
    $OBJECT_GRID->addReadField("name: 'ROOM'");
    $OBJECT_GRID->addReadField("name: 'COLOR'");
    $OBJECT_GRID->addReadField("name: 'COLOR_FONT'");
    $OBJECT_GRID->addReadField("name: 'CODE'");
    $OBJECT_GRID->addReadField("name: 'STATUS'");
    $OBJECT_GRID->addReadField("name: 'TEACHING_STATUS'");
    $OBJECT_GRID->addReadField("name: 'SHOW_SUBSTITUTE'");
    $OBJECT_GRID->addReadField("name: 'SHOW_DAYOFFSCHOOL'");
    
    
    $OBJECT_GRID->addColumn("
        header: '<b>" . TIME . "</b>'
        , align:'center'
        ,renderer: styleTime
        , sortable: false
        , dataIndex: 'TIME'
        , width: 150
    ");
        
    $OBJECT_GRID->addColumn("
        header: '<b>" . EVENT . "</b>'
        ,renderer: showText
        , align:'center'
        , sortable: false
        , dataIndex: 'EVENT'
        , width: 180
    ");
        
    $OBJECT_GRID->addColumn("
        header: '<b>" . TEACHER . "</b>'
        , renderer: showText
        , align:'center'
        , sortable: false
        , dataIndex: 'TEACHER'
        , width: 200
    ");
        
    $OBJECT_GRID->addColumn("
        header: '<b>" . ROOM . "</b>'
        , renderer: showText
        , align:'center'
        , sortable: false
        , dataIndex: 'ROOM'
        , width: 200
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,studentId: '".$this->studentId."'
        ,schoolyearId: '".$this->schoolyearId."'
        ,cmd: 'jsonListCreditStudentExtraTeachingSession'
    ";
    
    
    $OBJECT_GRID->addTBarItems("
       tbar.add(['->','<b>".SCHOOL_YEAR."</b> (".$YEAR_DATE.")','-','<b>".FIRST_SEMESTER."</b> (".$FIRST_SEMESTER_DATE.")','-','<b>".SECOND_SEMESTER."</b> (".$SECOND_SEMESTER_DATE.")']);
    ");
    
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            text: '" . EXPORT_TO_EXCEL . "'
            ,id: 'EXPORT_TO_EXCEL'
            ,iconCls:'icon-page_excel'
            ,handler: function(){ 
                
            }
        }]);        
    ");
   
    $OBJECT_GRID->isPagingToolbar = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
	
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border:false
            ,layout: 'card'
            ,id: 'center'
            ,activeItem: 0
            ,title: ''
            ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
        }]
    });
    
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>