<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$setParams = "";
$setParams .= "&objectId=".$this->studentId."";
$setParams .= "&academicId=".$this->academicId."";
$setParams .= "&schoolyearId=".$this->schoolyearId."";

?>
<script>

	Ext.onReady(function() {

		<?
		$CAMEMIS_PAGE_OBJECT->setCostumerCSS();
		$CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
		?>
		viewport = new Ext.Viewport({
			layout: 'fit'
			,border: false
			,items:[{
				layout:'fit'
				,border:false
				,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
				,items:[{
					xtype: 'tabpanel'
					,plain:true
					,activeTab: 0
					,items:[{
						title: '<?=DAY_SCHEDULE?>'
						,layout: 'fit'
						,border: false
						,items:[new Ext.ux.IFrameComponent({ id: 'DAY_SCHEDULE', url: '/student/daycrediteventlist/?camIds=<?=$this->urlEncryp->encryptedGet($setParams);?>'})]
					},{
						title: '<?=EXTRA_TEACHING_SESSION?>'
						,layout: 'fit'
						,border: false
						,items:[new Ext.ux.IFrameComponent({ id: 'EXTRA_TEACHING_SESSION', url: '/student/listcreditstudentextrasession/?camIds=<?=$this->urlEncryp->encryptedGet($setParams);?>'})]
					},{
						title: '<?=WEEK_SCHEDULE?>'
						,layout: 'fit'
						,border: false
						,items:[new Ext.ux.IFrameComponent({ id: 'WEEK_SCHEDULE', url: '/student/creditstudenteventsetting/?camIds=<?=$this->urlEncryp->encryptedGet($setParams);?>'})]
					}]
				}]
			}]
		});
	});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>