<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$ASSIGNED_STUDENTS = new CamemisGrid("STUDENT", "LIST_CLASS");
$ASSIGNED_STUDENTS->setLoadUrl("/student/jsonload/");
$ASSIGNED_STUDENTS->setSaveUrl("/student/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

if(!$this->facette) {header("Location: /main/permission/");exit;}

?>

<script>
    Ext.onReady(function() {
        
        function cssStatus(v, p, record){
            return String.format('<div style=\"font-weight:bold;padding:4px;background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['BG_COLOR']
            ,record.data['BG_COLOR_FONT']
            );
        }
        function cssText(value, metadata, record){
            return '<div style="font-weight:normal; color:#000; padding: 5px; height: 15px;;">' + value + '</div>';
        }
        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $ASSIGNED_STUDENTS->addReadField("name: 'FULL_NAME'");
        $ASSIGNED_STUDENTS->addReadField("name: 'FIRSTNAME'");
        $ASSIGNED_STUDENTS->addReadField("name: 'LASTNAME'");
        $ASSIGNED_STUDENTS->addReadField("name: 'GENDER'");
        $ASSIGNED_STUDENTS->addReadField("name: 'DATE_BIRTH'");
        
        if(!SchoolDBAccess::displayPersonNameInGrid()){
            $ASSIGNED_STUDENTS->addColumn("
                header: '<b>".LASTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'LASTNAME'
            ");

            $ASSIGNED_STUDENTS->addColumn("
                header: '<b>".FIRSTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'FIRSTNAME'
            ");

        }else{

            $ASSIGNED_STUDENTS->addColumn("
                header: '<b>".FIRSTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'FIRSTNAME'
            ");

            $ASSIGNED_STUDENTS->addColumn("
                header: '<b>".LASTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'LASTNAME'
            ");
        }

        $ASSIGNED_STUDENTS->addColumn("
            header: '<b>".GENDER."</b>'
            ,dataIndex: 'GENDER'
            ,width: 120
            ,align: 'left'
        ");

        $ASSIGNED_STUDENTS->addColumn("
            header: '<b>".DATE_BIRTH."</b>'
            , width: 110
            , sortable: true
            , dataIndex: 'DATE_BIRTH'
        ");
        
        $ASSIGNED_STUDENTS->baseParams = "
            start:0
            ,limit:100
            ,classId: '".$this->facette->ID."'
            ,cmd: 'jsonEnrolledStudentsToClass'
        ";
        
        /////////////////////////////////////////
        $ASSIGNED_STUDENTS->addTBarItems("
            tbar.add('->');
        ");
        
        $ASSIGNED_STUDENTS->objectBorder = "false";
        $ASSIGNED_STUDENTS->isQuickySearch = true;
        $ASSIGNED_STUDENTS->forceFit = "false";
        $ASSIGNED_STUDENTS->renderJS();
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: false
                    ,split: true
                }
                ,items: [{
                    title: '<?=SELECTED_SUBJECT;?>'
                    ,region:'east'
                    ,id: 'EAST_ID'
                    ,margins: '3 3 3 0'
                    ,cmargins: '3 3 3 3'
                    ,width: 400
                    ,minSize: 400
                    ,maxSize: 400
                },{
                    title: ''
                    ,border:true
                    ,collapsible: false
                    ,region:'center'
                    ,id: 'center'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,margins: '3 0 3 3'
                    ,items: [{xtype: '<?=$ASSIGNED_STUDENTS->getObjectXType();?>'}]
                }]
            }]
        }); 
   });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>