<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_GRID = new CamemisGrid("STUDENT", "LIST_CLASS");
$OBJECT_GRID->setLoadUrl("/student/jsonload/");
$OBJECT_GRID->setSaveUrl("/student/jsonsave/");

$OBJECT_FORM = new CamemisForm("STUDENT");
$OBJECT_FORM->setLoadUrl('/student/jsonload/');
$OBJECT_FORM->setSaveUrl('/student/jsonsave/');

$listSubjects = GradeSubjectDBAccess::getListSubjectsFromAcademic($this->objectId, false);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

if(!$this->facette) {header("Location: /main/permission/");exit;}

?>

<script>
    var objectId;
    Ext.onReady(function() {
        
        function cssText(value, metadata, record){
            return '<div style="font-weight:normal; color:#000; padding: 5px; height: 15px;;">' + value + '</div>';
        }
        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_GRID->addReadField("name: 'FULL_NAME'");
        $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
        $OBJECT_GRID->addReadField("name: 'LASTNAME'");
        $OBJECT_GRID->addReadField("name: 'GENDER'");
        $OBJECT_GRID->addReadField("name: 'DATE_BIRTH'");
        
        if(!SchoolDBAccess::displayPersonNameInGrid()){
            $OBJECT_GRID->addColumn("
                header: '<b>".LASTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'LASTNAME'
            ");

            $OBJECT_GRID->addColumn("
                header: '<b>".FIRSTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'FIRSTNAME'
            ");

        }else{

            $OBJECT_GRID->addColumn("
                header: '<b>".FIRSTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'FIRSTNAME'
            ");

            $OBJECT_GRID->addColumn("
                header: '<b>".LASTNAME."</b>'
                , width: 110
                , sortable: true
                , dataIndex: 'LASTNAME'
            ");
        }

        $OBJECT_GRID->addColumn("
            header: '<b>".GENDER."</b>'
            ,dataIndex: 'GENDER'
            ,width:80
            ,align: 'left'
        ");
        
        $OBJECT_GRID->addColumn("
            header: '<b>".DATE_BIRTH."</b>'
            ,dataIndex: 'DATE_BIRTH'
            ,width:110
            ,align: 'left'
        ");
        
        $OBJECT_GRID->baseParams = "
            start:0
            ,limit:100
            ,classId: '".$this->facette->ID."'
            ,cmd: 'jsonEnrolledStudentsToClass'
        ";
        
        /////////////////////////////////////////
        $OBJECT_GRID->addTBarItems("
            tbar.add('->');
        ");
        
        $OBJECT_GRID->objectBorder = "false";
        $OBJECT_GRID->isQuickySearch = true;
        $OBJECT_GRID->forceFit = "false";
        $OBJECT_GRID->renderJS();
        
        ////////////////////////////////////////////////////////////////////////
        $PERSON_INFORMATION = "
        {
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle:'padding:15px;background:#FFF;'
            ,items: [
                {".CamemisField::Displayfield("PERSON_INFORMATION",STUDENT,false)."}
            ]
        }";
        $DETAIL_INFORMATION_ITEMS = "[";
        if($listSubjects){
            $i = 0;
            foreach($listSubjects as $value){
                $SUBJECT_ID = $value->SUBJECT_ID;
                $SUBJECT_NAME = "(".addslashes($value->SUBJECT_SHORT).") ".addslashes($value->SUBJECT_NAME);
                $DETAIL_INFORMATION_ITEMS .= $i?",":"";
                $DETAIL_INFORMATION_ITEMS .= "{".CamemisField::Checkbox("SUB_".$SUBJECT_ID."","SUB_".$value->SUBJECT_ID."",$SUBJECT_NAME, $SUBJECT_ID, false, false)."}";
                $i++;
            }
        }
        
        $DETAIL_INFORMATION_ITEMS .= "]";
        $DETAIL_INFORMATION = "
        {
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle:'padding:15px;background:#d1ddef;'
            ,items: ".$DETAIL_INFORMATION_ITEMS."
        }";
        $FORM_ITEMS = "";
        $FORM_ITEMS .= $PERSON_INFORMATION;
        $FORM_ITEMS .= ",".$DETAIL_INFORMATION;
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:10px'
            ,items: [" . $FORM_ITEMS . "]
        ";
        $OBJECT_FORM->addObjectItems($items);
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 80;
        $OBJECT_FORM->addTBarItems("
            text: '".APPLY."'
            ,id: 'APPLY'
            ,disabled:true
            ,formBind:true
            ,iconCls:'icon-lightning_add'
            ,scope:this
            ,handler: function(){
                myForm = Ext.getCmp('".$OBJECT_FORM->getObjectId()."').getForm();
                Ext.Ajax.request({
                    url: '/student/jsonsave/'
                    ,method: 'POST'
                    ,params:{cmd: 'jsonSaveStudentEnrollBySubject',objectId:objectId,academicId:'".$this->objectId."'}
                    ,form: myForm.getEl().dom
                    ,success: function(response, options) {
                        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                    }
                });
            }
        ");
        
        $OBJECT_FORM->bodyStyle = "padding:0px";
        $OBJECT_FORM->renderJS();
        
        $js = "";
        $js .= "viewport = new Ext.Viewport({";
            $js .= "layout: 'fit'";
            $js .= ",border: false";
            $js .= ",items:[{";
                $js .= "layout:'border'";
                $js .= ",border: false";
                $js .= ",defaults: {";
                    $js .= "collapsible: false";
                    $js .= ",split: true";
                $js .= "}";
                $js .= ",items: [{";
                    $js .= "title: ''";
                    $js .= ",layout: 'fit'";
                    $js .= ",region:'east'";
                    $js .= ",id: 'EAST_ID'";
                    $js .= ",margins: '3 3 3 0'";
                    $js .= ",cmargins: '3 3 3 3'";
                    $js .= ",width: percentWidth(55)";
                    $js .= ",minSize: percentWidth(55)";
                    $js .= ",maxSize: percentWidth(55)";
                    $js .= ",items: [{xtype: '".$OBJECT_GRID->getObjectXType()."'}]";
                $js .= "},{";
                    $js .= "title: '".SELECTED_SUBJECT."'";
                    $js .= ",border:true";
                    $js .= ",collapsible: false";
                    $js .= ",region:'center'";
                    $js .= ",id: 'center'";
                    $js .= ",layout: 'card'";
                    $js .= ",activeItem: 0";
                    $js .= ",margins: '3 0 3 3'";
                    $js .= ",items: [{xtype: '".$OBJECT_FORM->getObjectXType()."'}]";
                $js .= "}]";
            $js .= "}]";
        $js .= "}); ";
        $js .= "var grid = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');";
        $js .= "if (grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {";
            $js .= "var record = grid.store.getAt(rowIndex);";
            $js .= "objectId = record.data.ID;";
            
            $js .= "Ext.getCmp('".$OBJECT_FORM->getObjectId()."').load({";
                $js .= "url:'/student/jsonload/'";
                $js .= ",loadMask: new Ext.LoadMask(Ext.getBody(), {msg:'<b>CAMEMIS " . LOADING . "</b>', msgCls:'x-mask-loading-camemis'})";
                $js .= ",params:{cmd:'jsonLoadStudentEnrollBySubject',academicId:'".$this->facette->ID."',objectId:objectId}";
            $js .= "});";
            
            $js .= "Ext.getCmp('APPLY').enable();";
            $js .= "Ext.getCmp('PERSON_INFORMATION_ID').setValue(record.data.FULL_NAME);";
        $js .= "});";
        
        echo $js;
        ?>
   });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>