<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

if(!$this->facette) {header("Location: /main/permission/");exit;}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$OBJECT_GRID = new CamemisGrid("FINANCE", "INVOICES");
$OBJECT_GRID->setLoadUrl("/finance/jsonload/");

?>
<script>
var clickId;
Ext.onReady(function() {
    
    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#333; padding:3px;">' + value + '</div>';
    }
    
    function cssNumber(value, metadata, record){
        return '<div style="font-weight:bold; color:#3B5998; padding: 5px;">' + value + '</div>';
    }
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addReadField("name: 'INVOICE_NUMBER'");
    $OBJECT_GRID->addReadField("name: 'AMOUNT'");
    $OBJECT_GRID->addReadField("name: 'AMOUNT_OWED'");
    $OBJECT_GRID->addReadField("name: 'CLICK_ADD'");
    
    $OBJECT_GRID->addColumn("header: '<b>".NAME."</b>', align:'left', renderer: cssText, width: 200, sortable: true, dataIndex: 'INVOICE_NUMBER'");
    $OBJECT_GRID->addColumn("header: '<b>".AMOUNT."</b>', align:'right', renderer: cssNumber, width: 150, sortable: true, dataIndex: 'AMOUNT'");
    $OBJECT_GRID->addColumn("header: '<b>".AMOUNT_OWED."</b>', align:'right', renderer: cssNumber, width: 150, sortable: true, dataIndex: 'AMOUNT_OWED'");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'REFRESH_ID'
            ,text: '".REFRESH."'
            ,iconCls:'icon-reload'
            ,scope:this
            ,disabled: false
            ,handler: function(){
               Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
            }
        }]);
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,objectId:'".$this->objectId."'
        ,cmd: 'jsonListStudentInvoicesGeneral'
        ,services:1
    ";
    
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,id:'content'
            ,layout: 'card'
            ,activeItem: 0
            ,title:'<?=STUDENT_SERVICES?>'
            ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
        }]
    });
    
    var myGrid = Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>');
    
    <?
    //if(UserAuth::getACLValue("FINANCIAL_MANAGEMENT_EDIT_RIGHT")){
    ?>
    if (myGrid) myGrid.on('cellclick', function(grid, rowIndex, columnIndex, event) {
        var record = grid.store.getAt(rowIndex);
        var contextMenu = new Ext.menu.Menu({
            items: [{
                text: '<?=PAYMENT;?> &raquo; ' + record.data.INVOICE_NUMBER
                ,iconCls:'icon-application_form_add'
                ,handler:function(){
                    if (record.data.CLICK_ADD) clickOpenPage('content','','/finance/studentpaymentservice/?fee='+record.data.ID + '&objectId=<?=$this->objectId?>');
                }
            },{
                text: '<?=PAYMENT_REMINDER;?> &raquo; ' + record.data.INVOICE_NUMBER
                ,iconCls:'icon-email'
                ,handler:function(){
                    openWinIFrame('Mail &raquo; ' + record.data.INVOICE_NUMBER, '/dataset/sendemail/?objectId=<?=$this->objectId;?>&fee=' + record.data.ID,550,percentHeight(85));
                }
            }]
        });
        event.stopEvent();
        contextMenu.showAt(event.xy);
    });
    <?        
    //}
    ?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>