<?
///////////////////////////////////////////////////////////////////////////////////
//@THORN Visal
//Date:16.12.2013
//////////////////////////////////////////////////////////////////////////////////

require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";

$OBJECT_FORM = new CamemisForm("STAFF_CONTRACT");
$OBJECT_FORM->setLoadUrl('/staffcontract/jsonload/');

$OBJECT_GRID = new CamemisGrid("STAFF_CONTRACT", "LIST");
$OBJECT_GRID->setLoadUrl("/staffcontract/jsonload/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

    var startDate;
    var endDate;
    var code = '';
    var firstname= '';
    var lastname= '';
    var expiredDate= '';
    var searchType = '';
    var contractType = '';
    
    Ext.apply(Ext.form.VTypes, {
        daterange : function(val, field) {
            var date = field.parseDate(val);

            if(!date){
                return false;
            }
            if (field.startDateField && (!this.dateRangeMax || (date.getTime() !== this.dateRangeMax.getTime()))) {
                var start = Ext.getCmp(field.startDateField);
                start.setMaxValue(date);
                start.validate();
                this.dateRangeMax = date;
            }
            else if (field.endDateField && (!this.dateRangeMin || (date.getTime() !== this.dateRangeMin.getTime()))) {
                var end = Ext.getCmp(field.endDateField);
                end.setMinValue(date);
                end.validate();
                this.dateRangeMin = date;
            }
            return true;
        }
    });
    
    Ext.onReady(function(){
        function renderText(value,record){
            return '<div style=\"font-weight:normal; color:#000000; padding: 5px; height:15px;background:#FFFFFF;\">' + value + '</div>';
        }
        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_FORM->addTBarItems("
            text: '".RESET."'
            ,iconCls:'icon-arrow_undo'
            ,scope:this
            ,handler: function(){".CamemisPage::setRequestURI()."}
        ");

        $OBJECT_FORM->addTBarItems("
            text: '".SEARCH."'
            ,formBind:true
            ,iconCls:'icon-magnifier'
            ,scope:this
            ,handler:function(){
                Ext.getCmp('TABPANEL_ID').getLayout().setActiveItem(1);
                Ext.getCmp('center').getLayout().setActiveItem(1);
                var _startDate = this.getForm().findField('START_DATE').getValue(); 
                if(_startDate){
                    
                    startDate = _startDate.getFullYear() + '-' + (parseInt(_startDate.getMonth()) + 1) + '-' + _startDate.getDate();
                }else{
                    startDate = '';
                }
                
                var _endDate = this.getForm().findField('END_DATE').getValue(); 
                if(_endDate){
                    endDate = _endDate.getFullYear() + '-' + (parseInt(_endDate.getMonth()) + 1) + '-' + _endDate.getDate();
                }else{
                    endDate = ''; 
                }
                
                lastname = this.getForm().findField('LASTNAME').getValue();
                firstname = this.getForm().findField('FIRSTNAME').getValue();
                code = this.getForm().findField('CODE').getValue();
                name = this.getForm().findField('NAME').getValue();
                expiredDate = this.getForm().findField('END_DATE').getValue();
                searchType = this.getForm().findField('SEARCH_TYPE').getValue();
                contractType = this.getForm().findField('CONTRACT_TYPE').getValue();
                
                
                Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.baseParams = {
                    start:0
                    ,limit:100
                    ,cmd: 'jsonSearchStaffContract'
                    ,code: code
                    ,firstname: firstname
                    ,lastname: lastname
                    ,endDate: endDate
                    ,startDate: startDate
                    ,name: name
                    ,expiredDate: expiredDate
                    ,searchType: searchType
                    ,contractType: contractType
                };
                Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.load();
            }
        ");
        
        $OBJECT_FORM->addTBarItems("
            text: '".ADD_A_NEW_ITEM."'
            ,tooltip:'".ADD_A_NEW_ITEM."'
            ,iconCls:'icon-application_form_add'
            ,scope:this
            ,handler: function(){
                clickOpenPage('center','".ADD_A_NEW_ITEM."', '/staffcontract/staffshowitem?objectId=new');
            }
        ");
        
        $SEARCH_TYPE_STORE = "[
            ['CLEAR', '[---]']
            ,['CREATED_DATE', '" . CREATED_DATE . "']
            ,['START_DATE', '" . START_DATE . "']
            ,['EXPIRED_DATE', '" . EXPIRED_DATE . "']
        ]";
        
        $OBJECT_FORM->addObjectItems("
            xtype:'fieldset'
            ,checkboxToggle:true
            ,title: '".DATE."'
            ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
            ,width: 330
            ,items:[{
                name: 'START_DATE'
                ,hidden: false
                ,width: 150
                ,fieldLabel: '" . START_DATE . "'
                ,xtype: 'datefield'
                ,id: 'START_DATE'
                ,vtype: 'daterange'
                ,endDateField: 'END_DATE'
                ,format: '" . setExtDatafieldFormat() . "'
                ,allowBlank: true
            },{
                name: 'END_DATE'
                ,hidden: false
                ,width: 150
                ,fieldLabel: '" . END_DATE . "'
                ,xtype: 'datefield'
                ,id: 'END_DATE'
                ,vtype: 'daterange'
                ,format: '" . setExtDatafieldFormat() . "'
                ,startDateField: 'START_DATE'
                ,allowBlank: true
            },{".CamemisField::Combo("SEARCH_TYPE", TYPE, $SEARCH_TYPE_STORE, false, false, 150, false, false)."}]
        ");
        
        $OBJECT_FORM->addObjectItems("
            xtype:'fieldset'
            ,checkboxToggle:true
            ,title: '".STAFF_INFORMATION."'
            ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
            ,width: 330
            ,items:[
                {".CamemisField::Textfield("CODE", "CODE", CODE, false, false, false, 150)."}
                ,{".CamemisField::Textfield("LASTNAME", "LASTNAME", LASTNAME, false, false, false, 150)."}
                ,{".CamemisField::Textfield("FIRSTNAME", "FIRSTNAME", FIRSTNAME, false, false, false, 150)."}
            ]
        ");
        $OBJECT_FORM->addObjectItems("
            xtype:'fieldset'
            ,checkboxToggle:true
            ,title: '".CONTACT_INFORMATION."'
            ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
            ,width: 330
            ,items:[
                {".CamemisField::Textfield("NAME", "NAME", NAME, false, false, false, 150)."}
                ,{".CamemisField::comboCamemisTypes("CONTRACT_TYPE", CONTRACT_TYPE, false,150, true)."}
            ]
        ");
        
        $OBJECT_FORM->setBodyStyle("padding:5px;background:".CamemisPage::userFormBgColor().";");
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->isKeys = true;
        $OBJECT_FORM->renderJS();
        /////////////////////////////////////////////
        
        if($objectId){
            
            $OBJECT_GRID->addReadField("name: 'ID'");
            $OBJECT_GRID->addReadField("name: 'SUBJECT_NAME'");
            $OBJECT_GRID->addReadField("name: 'CONTRACT_TYPE'");
            $OBJECT_GRID->addReadField("name: 'DESCRIPTION'");
            $OBJECT_GRID->addReadField("name: 'START_DATE'");
            $OBJECT_GRID->addReadField("name: 'EXPIRED_DATE'");
            $OBJECT_GRID->addReadField("name: 'CREATED_BY'");
            $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");
            
            $OBJECT_GRID->addColumn("header: '<b>" . SUBJECT . "</b>', align:'left', width: 120, dataIndex: 'SUBJECT_NAME'");
            $OBJECT_GRID->addColumn("header: '<b>" . CONTRACT_TYPE . "</b>', align:'left', width: 120, dataIndex: 'CONTRACT_TYPE'");
            $OBJECT_GRID->addColumn("header: '<b>" . DESCRIPTION . "</b>', align:'left', width: 120, dataIndex: 'DESCRIPTION'");
            $OBJECT_GRID->addColumn("header: '<b>" . START_DATE . "</b>', align:'left', width: 100, dataIndex: 'START_DATE'");
            $OBJECT_GRID->addColumn("header: '<b>" . EXPIRED_DATE . "</b>', align:'left', width: 100, dataIndex: 'EXPIRED_DATE'");
            $OBJECT_GRID->addColumn("header: '<b>" . CREATED_BY . "</b>', align:'left', width: 100, dataIndex: 'CREATED_BY'");
            $OBJECT_GRID->addColumn("header: '<b>" . CREATED_DATE . "</b>', align:'left', width: 100, dataIndex: 'CREATED_DATE'");
            
            $OBJECT_GRID->baseParams = "
                start:0
                ,limit:100
                ,cmd: 'jsonShowAllStaffContracts'
                ,objectId : '".$objectId."'
            ";
                
            $OBJECT_GRID->isObjectDefaultOnLoad = true;
            $OBJECT_GRID->loadMask = true;
            $OBJECT_GRID->forceFit = "true";
            $OBJECT_GRID->renderJS();
            
            $js = "viewport = new Ext.Viewport({";
                 $js .= "layout: 'fit'";
                 $js .= ",border: false";
                 $js .= ",items: [{" ;
                    $js .= "xtype: 'panel'";
                    $js .= ",id: 'center'";    
                    $js .= ",border: false";    
                    $js .= ",layout: 'card'";    
                    $js .= ",activeItem: 0";    
                    $js .= ",items: [{";    
                        $js .= "layout: 'fit'";        
                        $js .= ",border: false";        
                        $js .= ",items: [{xtype: '".$OBJECT_GRID->getObjectXType()."'}]";        
                    $js .= "}]";
                 $js .= "}]"; 
            $js .= "});";
            
        }else{
            
            $OBJECT_GRID->addReadField("name: 'ID'");
            $OBJECT_GRID->addReadField("name: 'SUBJECT_NAME'");
            $OBJECT_GRID->addReadField("name: 'STAFF_NAME'");
            $OBJECT_GRID->addReadField("name: 'CONTRACT_TYPE'");
            $OBJECT_GRID->addReadField("name: 'DESCRIPTION'");
            $OBJECT_GRID->addReadField("name: 'START_DATE'");
            $OBJECT_GRID->addReadField("name: 'EXPIRED_DATE'");
            $OBJECT_GRID->addReadField("name: 'CREATED_BY'");
            $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");
            
            $OBJECT_GRID->addColumn("header: '<b>" . SUBJECT . "</b>', align:'left', width: 120, dataIndex: 'SUBJECT_NAME'");
            $OBJECT_GRID->addColumn("header: '<b>" . STAFF . "</b>', align:'left', width: 120, dataIndex: 'STAFF_NAME'");
            $OBJECT_GRID->addColumn("header: '<b>" . CONTRACT_TYPE . "</b>', align:'left', width: 120, dataIndex: 'CONTRACT_TYPE'");
            $OBJECT_GRID->addColumn("header: '<b>" . DESCRIPTION . "</b>', align:'left', width: 120, dataIndex: 'DESCRIPTION'");
            $OBJECT_GRID->addColumn("header: '<b>" . START_DATE . "</b>', align:'left', width: 100, dataIndex: 'START_DATE'");
            $OBJECT_GRID->addColumn("header: '<b>" . EXPIRED_DATE . "</b>', align:'left', width: 100, dataIndex: 'EXPIRED_DATE'");
            $OBJECT_GRID->addColumn("header: '<b>" . CREATED_BY . "</b>', align:'left', width: 100, dataIndex: 'CREATED_BY'");
            $OBJECT_GRID->addColumn("header: '<b>" . CREATED_DATE . "</b>', align:'left', width: 100, dataIndex: 'CREATED_DATE'");
        
            $OBJECT_GRID->baseParams = "
                start:0
                ,limit:100
                ,cmd: 'jsonShowAllStaffContracts'
                ,objectId : ''
            ";
            
            $OBJECT_GRID->isObjectDefaultOnLoad = true;
            $OBJECT_GRID->isGroupingView = true;
            $OBJECT_GRID->groupField = "STAFF_NAME";
            $OBJECT_GRID->loadMask = true;
            $OBJECT_GRID->forceFit = "false";
            $OBJECT_GRID->renderJS();
        
            $js = "viewport = new Ext.Viewport({";
                $js .= "layout: 'fit'";
                $js .= ",border: false";
                $js .= ",items:[{";
                    $js .= "layout:'border'";
                    $js .= ",border: false";
                    $js .= ",defaults: {";
                        $js .= "collapsible: true";
                        $js .= ",split: true";
                    $js .= "}";
                    $js .= ",items: [{";
                        $js .= "title: ''";
                        $js .= ",id:'WEST_ID'";
                        $js .= ",region:'west'";
                        $js .= ",margins: '3 0 3 3'";
                        $js .= ",cmargins: '3 3 3 3'";
                        $js .= ",width: 350";
                        $js .= ",minSize: 350";
                        $js .= ",maxSize: 350";
                        $js .= ",layout: 'fit'";
                        $js .= ",items: [{xtype: '".$OBJECT_FORM->getObjectXType()."'}]";
                    $js .= "},{";
                        $js .= "title: ''";
                        $js .= ",collapsible: false";
                        $js .= ",id: 'center'";
                        $js .= ",region:'center'";
                        $js .= ",layout: 'card'";
                        $js .= ",activeItem: 0";
                        $js .= ",margins: '3 3 3 0'";
                        $js .= ",items:[{";
                            $js .= "layout:'fit'";
                            $js .= ",bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px'";
                            $js .= ",border: false";
                            $js .= ",items:[{";
                                $js .= "xtype: 'tabpanel'";
                                $js .= ",id:'TABPANEL_ID'";
                                $js .= ",tabPosition: 'top'";
                                $js .= ",plain:true";
                                $js .= ",activeTab: 0";
                                $js .= ",enableTabScroll:true";
                                $js .= ",items:[{";
                                    $js .= "title:'".CHART."'";
                                    $js .= ",layout:'fit'";
                                    $js .= ",items: [new Ext.ux.IFrameComponent({ id: 'STAFF_CONTRACT_CHARTS', url:'/staffcontract/chartreport/?key=<?=camemisId();?>'})]";
                                $js .= "},{";
                                    $js .= "title:'".SEARCH_RESULT."'";
                                    $js .= ",layout:'fit'";
                                    $js .= ",items: [{xtype: '".$OBJECT_GRID->getObjectXType()."'}]";
                                $js .= "}]";
                            $js .= "}]";
                        $js .= "}]";
                    $js .= "}]";
                $js .= "}]";
            $js .= "});";
        }
        
        print $js;
        
       ?>
        
        var grid = Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>');
        if(grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {
            var record = grid.store.getAt(rowIndex);
            clickOpenPage('center','', '/staffcontract/staffshowitem?objectId='+record.data.ID);   
        }) 
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>