<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$target = isset($_GET['target'])?addText($_GET['target']):""; ///@THORN Visal
$academicId = isset($_GET['academicId']) ? addText($_GET["academicId"]):"";
$trainingId = isset($_GET['trainingId'])?addText($_GET['trainingId']):"";
$subjectId = isset($_GET['subjectId'])?addText($_GET['subjectId']):"";///@THORN Visal

if($academicId){
    $params = "academicId=".$academicId."&staffId=".Zend_Registry::get('USER')->ID."";
}elseif($trainingId){
    $params = "trainingId=".$trainingId."&staffId=".Zend_Registry::get('USER')->ID."";
}else{
   $params = "academicId=".$academicId."";///@THORN Visal 
}

if($subjectId){
    $params = "academicId=".$academicId."&subjectId=".$subjectId."&target=".$target."";///@THORN Visal
}

$PENEL_ITEMS = Array();

$DAILY_ATTENDANCE = "{
    title: '".DAILY_ATTENDANCE."'
    ,layout: 'fit'
    ,items:[new Ext.ux.IFrameComponent({ id: 'DAILY_ATTENDANCE', url: '/attendance/studentclassdaily/?camIds=".$this->urlEncryp->encryptedGet($params)."'})]
}";
$PENEL_ITEMS[] = $DAILY_ATTENDANCE;

$BLOCK_ATTENDANCE = "{
    title: '".BLOCK_ATTENDANCE."'
    ,layout: 'fit'
    ,items:[new Ext.ux.IFrameComponent({ id: 'BLOCK_ATTENDANCE', url: '/attendance/studentclassblock/?camIds=".$this->urlEncryp->encryptedGet($params)."'})]
}";
$PENEL_ITEMS[] = $BLOCK_ATTENDANCE;

///@THORN Visal
$REPORTS = "{
    title: '".REPORTS."'
    ,layout: 'fit'
    ,items:[new Ext.ux.IFrameComponent({ id: 'REPORTS', url: '/attendance/studentclassreport/?camIds=".$this->urlEncryp->encryptedGet($params)."'})]
}";
$PENEL_ITEMS[] = $REPORTS;
///////

$CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
?>
<script>
    Ext.onReady(function() {
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px;'
                ,border:false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,items:<?=$CHOOSE_ITEMS;?>
                }]     
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>