<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_school/AcademicDateDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("SCHEDULE", "LIST");
$OBJECT_GRID->setLoadUrl("/schedule/jsonload/");
$OBJECT_GRID->setSaveUrl("/schedule/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
var choosedate = '<?=date('Y-m-d')?>';
Ext.onReady(function() {
    
    function styleTime(v, p, record, rowIndex){
    
        return String.format('<div style=\"font-weight:bold; padding: 20px; height: 35px;background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['COLOR']
            ,record.data['COLOR_FONT']
        );
    }
    
    function showText(v, metadata, record){
        
        var name = record.data.DESCRIPTION;
        return String.format('<div style=\"white-space:normal;font-weight:bold; padding: 20px; height: 35px; background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['COLOR']
            ,record.data['COLOR_FONT']
        );
    }
    
    function showTextStatus(v, p, record, rowIndex){
        return String.format('<div style=\"white-space:normal;font-weight:bold; padding: 20px; height: 35px;\">{0}</div>'
            ,v
        );
    }
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    $OBJECT_GRID->addReadField("name: 'ID'");
    $OBJECT_GRID->addReadField("name: 'TIME'");
    $OBJECT_GRID->addReadField("name: 'SCHEDULE_TYPE'");
    $OBJECT_GRID->addReadField("name: 'EVENT'");
    $OBJECT_GRID->addReadField("name: 'TEACHER'");
    $OBJECT_GRID->addReadField("name: 'ROOM'");
    $OBJECT_GRID->addReadField("name: 'COLOR'");
    $OBJECT_GRID->addReadField("name: 'COLOR_FONT'");
    $OBJECT_GRID->addReadField("name: 'CODE'");
    $OBJECT_GRID->addReadField("name: 'STATUS'");
    $OBJECT_GRID->addReadField("name: 'TEACHING_STATUS'");
    $OBJECT_GRID->addReadField("name: 'DESCRIPTION'");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add('-','<b>".DATE."</b>&nbsp;',[{
            xtype:'datefield'
            ,width:150
            ,id:'CHOOSE_DATE'
            ,name: 'CHOOSE_DATE'
            ,format: '".setExtDatafieldFormat()."'
            ,value:choosedate
        }]);
    ");
    
    $OBJECT_GRID->addColumn("
        header: '<b>" . TIME . "</b>'
        , align:'center'
        ,renderer: styleTime
        , sortable: false
        , dataIndex: 'TIME'
        , width: 150
    ");
        
    $OBJECT_GRID->addColumn("
        header: '<b>" . EVENT . "</b>'
        ,renderer: showText
        , align:'center'
        , sortable: false
        , dataIndex: 'EVENT'
        , width: 180
    ");
        
    $OBJECT_GRID->addColumn("
        header: '<b>" . TEACHER . "</b>'
        , renderer: showText
        , align:'center'
        , sortable: false
        , dataIndex: 'TEACHER'
        , width: 200
    ");
        
    $OBJECT_GRID->addColumn("
        header: '<b>" . ROOM . "</b>'
        , renderer: showText
        , align:'center'
        , sortable: false
        , dataIndex: 'ROOM'
        , width: 200
    ");
    
    $OBJECT_GRID->addColumn("
        header: '<b>" . STATUS . "</b>'
        , renderer: showTextStatus
        , align:'center'
        , sortable: false
        , dataIndex: 'TEACHING_STATUS'
        , width: 200
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,schoolyearId: '".$this->schoolyearId."'
        ,studentId: '".$this->studentId."'
        ,eventDay: choosedate
        ,cmd: 'dayCreditStudentEventList' 
    ";
    
    $OBJECT_GRID->addTBarItems("
        tbar.add('->');
    ");
    
    $OBJECT_GRID->isPagingToolbar = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    
    $viewport = "";
    $viewport .= "viewport = new Ext.Viewport({";
        $viewport .= "layout: 'fit'";
        $viewport .= ",border: false";
        $viewport .= ",items:[{";
            $viewport .= "border:false";
            $viewport .= ",layout: 'card'";
            $viewport .= ",id: 'center'";
            $viewport .= ",activeItem: 0";
            $viewport .= ",title: ''";
            $viewport .= ",items: [{xtype: '".$OBJECT_GRID->getObjectXType()."'}]";
        $viewport .= "}]";
    $viewport .= "});";
    
    echo $viewport;
   
    $js = "Ext.getCmp('CHOOSE_DATE').on('select', function(date_picker, date) {";
        $js .= "choosedate = date.getFullYear() + '-' + (parseInt(date.getMonth()) + 1) + '-' + date.getDate();";
        $js .= "Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.baseParams = {";
            $js .= "start:0";
            $js .= ",limit:100";
            $js .= ",schoolyearId: '".$this->schoolyearId."'";
            $js .= ",studentId: '".$this->studentId."'";
            $js .= ",eventDay: choosedate";
            $js .= ",cmd: 'dayCreditStudentEventList'";
        $js .= "};";
        $js .= "if (Ext.getCmp('".$OBJECT_GRID->getObjectId()."')) Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.load();";
    $js .= "});";
    echo $js;
    ?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>