<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisSchoolTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("DISCIPLINE");
$OBJECT_FORM->setLoadUrl('/enrollment/jsonload/');
$OBJECT_FORM->setSaveUrl('/enrollment/jsonsave/');
$OBJECT_GRID=new CamemisGrid("STUDENT","LIST");
$OBJECT_GRID->setLoadUrl('/enrollment/jsonload/');
$OBJECT_GRID->setSaveUrl('/enrollment/jsonload/');


print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
 
Ext.onReady(function() {
	 function cssStatus(v, p, record){
            return String.format('<div style=\"font-weight:bold;padding:4px;background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['BG_COLOR']
            ,record.data['BG_COLOR_FONT']
            );
        }
        
    function cssText(value, metadata, record){
        var name = record.data.STUDENT_NAME;
        metadata.attr = 'ext:qtip="' + name + '"';
        return '<span style="color:#333; padding:5px; height: 25px;">' + value + '</span>';
    }
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $js = "";
    $js .= "xtype: 'combo'";
    $js .= ",id: 'CHOOSE_OPTION'";
    $js .= ",fieldLabel: '" . TYPE . "'";
    $js .= ",mode: 'local'";
    $js .= ",triggerAction: 'all'";
    $js .= ",emptyText: '" . PLEASE_CHOOSE . "'";
    $js .= ",store: [['','[---]'],['TRANSFER','TRANSFER'],['UPGRADE','UPGRADE'],['DOWNGRADE','DOWNGRADE']]";
    $js .= ",editable:false";
    $js .= ",name: 'CHOOSE_OPTION'";
    $js .= ",width:150";

    $OBJECT_GRID->addReadField("name: 'CODE'");                  
    $OBJECT_GRID->addReadField("name: 'LASTNAME'");
    $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
    $OBJECT_GRID->addReadField("name: 'STUDENT_NAME'");
    $OBJECT_GRID->addReadField("name: 'STUDENT_NAME'");
    $OBJECT_GRID->addReadField("name: 'GENDER'");
    $OBJECT_GRID->addReadField("name: 'FROM_CLASS_NAME'");    
    $OBJECT_GRID->addReadField("name: 'FROM_GRADE'");
    $OBJECT_GRID->addReadField("name: 'CURRENT_CLASS_NAME'");    
    $OBJECT_GRID->addReadField("name: 'CURRENT_GRADE'");
    $OBJECT_GRID->addReadField("name: 'TYPE'");
    $OBJECT_GRID->addReadField("name: 'BG_COLOR'");
    $OBJECT_GRID->addReadField("name: 'BG_COLOR_FONT'");
    $OBJECT_GRID->addReadField("name: 'STATUS_KEY'"); 
    $OBJECT_GRID->addReadField("name: 'CREATE_DATE'");   
    
    //$OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: 120, renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY'");
    $OBJECT_GRID->addColumn("header: '<b>".CODE_ID."</b>', align:'left', renderer: cssText, width: 80, sortable: true, dataIndex: 'CODE'");
    $OBJECT_GRID->addColumn("header: '<b>".NAME."</b>', align:'left', renderer: cssText, width: 120, sortable: true, dataIndex: 'STUDENT_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".GENDER."</b>', align:'left', renderer: cssText, width: 80, sortable: true, dataIndex: 'GENDER'");
    $OBJECT_GRID->addColumn("header: '<b>".PREVIOUS_GRADE."</b>', align:'left', renderer: cssText, width: 120, sortable: true, dataIndex: 'FROM_GRADE'");
    $OBJECT_GRID->addColumn("header: '<b>".PREVIOUS_CLASS."</b>', align:'left', renderer: cssText, width: 110, sortable: true, dataIndex: 'FROM_CLASS_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".CURRENT_GRADE."</b>', align:'left', renderer: cssText, width: 110, sortable: true, dataIndex: 'CURRENT_GRADE'");
    $OBJECT_GRID->addColumn("header: '<b>".CURRENT_CLASS."</b>', align:'left', renderer: cssText, width: 120, sortable: true, dataIndex: 'CURRENT_CLASS_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".TYPE."</b>', align:'left', renderer: cssText, width: 110, sortable: true, dataIndex: 'TYPE'");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_DATE."</b>', align:'left', renderer: cssText, width: 110, sortable: true, dataIndex: 'CREATE_DATE'");
    
    
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonAllStudentsHistory'
    ";
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'REFRESH_ID'
            ,text: '".REFRESH."'
            ,iconCls:'icon-reload'
            ,scope:this
            ,disabled: false
            ,handler: function(){
               Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
            }
        }]);
    ");
    
    $OBJECT_GRID->isObjectDefaultOnLoad=false; 
    $OBJECT_GRID->isQuickySearch=true; 
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
	
    $OBJECT_FORM->addObjectItems("
        xtype:'fieldset'
        ,checkboxToggle:true
        ,title: '".DATE."'
        ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
        ,width: 310
        ,items:[
            {".CamemisField::Datefield("START_DATE",START_DATE,false,false,150)."}
            ,{".CamemisField::Datefield("END_DATE",END_DATE,false,false,150)."}
        ]
    ");
	

    $OBJECT_FORM->addObjectItems("
        xtype:'fieldset'
        ,checkboxToggle:true
        ,title: '".PERSONAL_INFORMATION."'
        ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
        ,width: 310
        ,items:[
            {".CamemisField::Textfield("STUDENT_SCHOOL_ID", "STUDENT_SCHOOL_ID", STUDENT_SCHOOL_ID, false, false, false, 150)."}
            ,{".CamemisField::Textfield("CODE_ID", "CODE", CODE_ID, false, false, false, 150)."}
            ,{".CamemisField::Textfield("LASTNAME_ID", "LASTNAME", LASTNAME, false, false, false, 150)."}
            ,{".CamemisField::Textfield("FIRSTNAME_ID", "FIRSTNAME", FIRSTNAME, false, false, false, 150)."}
            ,{".CamemisField::ComboGender(GENDER, false, false, 150)."}
            ,{".$js."}
            
        ]
    ");
  
    $OBJECT_FORM->addTBarItems("
        text: '".RESET."'
        ,iconCls:'icon-arrow_undo'
        ,scope:this
        ,handler: function(){".CamemisPage::setRequestURI()."}
    ");

    
    $OBJECT_FORM->addTBarItems("
        text: '".FIND."'
        ,formBind:true
        ,iconCls:'icon-magnifier'
        ,scope:this
        ,handler: function(){
            var loadMask = new Ext.LoadMask(Ext.getBody(), {msg:'<b>CAMEMIS " . LOADING . "</b>', msgCls:'x-mask-loading-camemis'});
            loadMask.show(); 
            Ext.Ajax.request({
                url: '/enrollment/jsonload'
                ,method: 'POST'
                ,params:{cmd: 'jsonAllStudentsHistory',start:0,limit:100}
                ,form: ".$OBJECT_FORM->ExtgetCmp().".getForm().getEl().dom
                ,success: function(response, options) {
                    jsonData = Ext.util.JSON.decode(response.responseText);
                    Ext.getCmp('".$OBJECT_GRID->getObjectId()."').getStore().loadData(jsonData);
                    loadMask.hide();
                }
            });   
        }
    ");
     
    $OBJECT_FORM->setBodyStyle("padding:10px;background:".CamemisPage::userFormBgColor().";");
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->isKeys = true;
    $OBJECT_FORM->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{
                title: ''
                ,region:'west'
                ,id: 'WEST_ID'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width: 350
                ,minSize: 350
                ,maxSize: 350
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            },{
                title: ''
                ,collapsible: false
                ,id: 'center'
                ,region:'center'
                ,layout: 'card'
                ,activeItem: 0
                ,margins: '3 3 3 0'
                ,items:[{
                    border: false
                    ,layout: 'fit'
                    ,bodyStyle: 'background:#FFFFFF;'
                    ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
                }]
            }]
        }]
    });
	
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>