<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTree("TRANSFER","LIST");

$OBJECT_TREE->setURL("/academic/jsontree/");
$OBJECT_TREE->setSaveUrl("/academic/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_SCHOOLYEAR = new CamemisDynCombo("ACADEMICDATE","COMBO");
        $OBJECT_SCHOOLYEAR->setLoadUrl('/academicdate/jsonload/');
        $OBJECT_SCHOOLYEAR->objectTitle = false;
        $OBJECT_SCHOOLYEAR->allowBlank = "true";
        $OBJECT_SCHOOLYEAR->width = 150;
        $OBJECT_SCHOOLYEAR->varName = "SCHOOLYEAR";
        $OBJECT_SCHOOLYEAR->setLoadParams("cmd: 'selectBoxSchoolyearNowFuture'");
        $OBJECT_SCHOOLYEAR->renderJS();
        
        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems("
            id: 'REFRESH'
            ,scope:this
            ,text:'".REFRESH."'
            ,iconCls:'icon-arrow_refresh'
            ,handler: function(){
                ".CamemisPage::setRequestURI(false)."
            }
        ");
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        $OBJECT_TREE->addTBarItems("
            xtype: 'buttongroup'
            ,items:[{
                width: 80
                ,xtype: '".$OBJECT_SCHOOLYEAR->getObjectXType()."'
            }]
        ");
        
        $OBJECT_TREE->isTreeExpand = false;
        $OBJECT_TREE->setBaseParams("
            cmd: 'getTreeTraditionalEducationSystem'

        ");
        
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout: 'fit'
                ,border: false
                ,id: 'CONTENT'
                ,items:[{
                    layout:'border'
                    ,border: false
                    ,defaults: {
                        collapsible: true
                        ,split: true
                    }
                    ,items: [{
                        title:''
                        ,layout:'fit'
                        ,region:'west'
                        ,id: 'WEST_ID'
                        ,margins: '3 0 3 3'
                        ,cmargins: '3 3 3 3'
                        ,width:350
                        ,minSize:350
                        ,maxSize:350
                        ,bodyStyle: 'background-color:#E0E7F7'
                        ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                    },{
                        title: ''
                        ,collapsible: false
                        ,id: 'center'
                        ,region:'center'
                        ,layout: 'card'
                        ,activeItem: 0
                        ,margins: '3 3 3 0'
                        ,items: [{
                            border: false
                            ,layout: 'anchor'
                            ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                            ,items: [{
                                title: ''
                                ,height:60
                                ,width:500
                                ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                                ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                            }]
                        }]
                    }] 
                }]
            }]
        });
        
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        var myCombo = Ext.getCmp('COMBO_ID');
        if (myCombo)
        myCombo.on('select', function() {
            myTree.loader.baseParams.SCHOOLYEAR = Ext.getCmp('COMBO_ID').getValue();
            myTree.root.reload();
            myTree.getRootNode().expand(true, false);
            Ext.getCmp('center').getLayout().setActiveItem(0);
        });
        
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node, e){
          
            if(node.attributes.objecttype=='CLASS') {
               
               clickOpenPage('center','<?=CLASS_NAME;?>&raquo;'+node.text,'/enrollment/enrollmentbyyear/?objectId=' + node.id + '&gradeId='+ node.attributes.gradeId + '&schoolyearId=' + node.attributes.schoolyearId);
               
            } 
            
            
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>