<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("SUBJECT");
$OBJECT_FORM->setLoadUrl('/subject/jsonload/');
$OBJECT_FORM->setSaveUrl('/subject/jsonsave/');

$educationType = isset($_GET["educationType"])?$_GET["educationType"]:"";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<script>
Ext.onReady(function() {
	
    <?
    /**
    * Extjs: s.gif
    */
    
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    $items = "
        border: false
        ,width: 550
        ,autoScroll: true
        ,items: [{
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,collapsed: false
            ,collapsible: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: [
                    {".CamemisField::Textfield("SHORT_ID", "SHORT", SHORT, true)."}
                    ,{".CamemisField::Textfield("NAME_ID", "NAME", NAME, true)."}
                    ,{".CamemisField::Numberfield("NUMBER_CREDIT", "NUMBER_CREDIT", NUMBER_CREDIT, false, false, false) . "}
                    ,{".CamemisField::ComboSubjectType(TYPE, false, false, false)."}
                    ,{".CamemisField::Colorfield("COLOR", COLOR, false)."}
                    ,{".CamemisField::Textarea("DESCRIPTION", DESCRIPTION, 80)."}
                ]
            }]
        }]
    ";
    
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
    ");
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'createOnlyItem'
        ,educationType: '".$educationType."'
        ,objectId: '".$this->objectId."'
    ");
    
    $OBJECT_FORM->setonEmbeddedEvents("
        
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
        if(window.parent.Ext.getCmp('TREE.SUBJECT_LIST_ID'))
        window.parent.Ext.getCmp('TREE.SUBJECT_LIST_ID').root.reload();
        window.parent.Ext.getCmp('TREE.SUBJECT_LIST_ID').getRootNode().expand(true, false);
        var result = Ext.util.JSON.decode(action.response.responseText);
        window.location='/subject/showitem/?objectId='+result.objectId;

    ");
    
    if (UserAuth::getACLValue("ACADEMIC_SETTING_EDIT_RIGHT"))
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>