<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTree("SUBJECT", "LIST");
$OBJECT_TREE->setURL('/subject/jsontree/');
$OBJECT_TREE->setSaveUrl('/subject/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
$EDIT_RIGHT=UserAuth::getACLValue("ACADEMIC_SETTING_EDIT_RIGHT")?"false":"true";
$READ_RIGHT=UserAuth::getACLValue("ACADEMIC_SETTING_READ_RIGHT")?"false":"true";
?>
<script>
var subjectId = null;
Ext.onReady(function() {
	
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    
    $OBJECT_TREE->addTBarItems("
        scope:this
        ,text:'".REFRESH."'
        ,iconCls:'icon-arrow_refresh'
        ,handler: function(){
            ".CamemisPage::setRequestURI(false)."
        }
    ");
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    $OBJECT_TREE->addTBarItems("
        xtype: 'buttongroup'
        ,keys:{
            key:[13]
            ,fn: function(){
                ".$OBJECT_TREE->ExtgetCmp().".loader.baseParams.query = document.getElementById('query').value;
                ".$OBJECT_TREE->ExtgetCmp().".root.reload();
                ".$OBJECT_TREE->ExtgetCmp().".getRootNode().expand(true, false);
            }
            ,scope:this
        }
        ,items:[{
            xtype:'textfield'
            ,id:'query'
            ,emptyText: '".ENTER_NAME_OR_CODEID."'
            ,width:120
        },{
            iconCls:'icon-find'
            ,tooltip:'".SEARCH."'
            ,handler: function(){
                ".$OBJECT_TREE->ExtgetCmp().".loader.baseParams.query = document.getElementById('query').value;
                ".$OBJECT_TREE->ExtgetCmp().".root.reload();
                ".$OBJECT_TREE->ExtgetCmp().".getRootNode().expand(true, false);
            }
        }]
    ");
    
     $OBJECT_TREE->addTBarItems("
            text:''
            ,tooltip:'".CAMEMIS_HELP."'
            ,iconCls: 'icon-help'
            ,handler:function(){
                ".CamemisPage::setEmbeddedHelp("6685-53EE")."
            }
        ");
    
    $OBJECT_TREE->setBaseParams("
    	cmd: 'treeAllSubjects'
    ");
    
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->isTreeExpand = false;
    $OBJECT_TREE->isOnClickContextMenu = false;
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{
               	region:'west'
                ,title: '<?=SUBJECT?>'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width:350
                ,minSize:350
                ,maxSize:350
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    border: false
                    ,layout: 'anchor'
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items: [{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                    }]
                }]
            }]
        }]
    });
    
    myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('click', function(node, event){
        
        if(node.isLeaf()){
            addDisabled = true;
            showDisabled = false;
        }else{
            addDisabled = false;
            showDisabled = true;
        }
        var contextMenu = new Ext.menu.Menu({
            items: [{
                text: '<?=ADD_ENTRY?> &raquo; ' + node.text
                ,iconCls: 'icon-application_form_add'
                ,disabled:addDisabled
                ,hidden:<?=$EDIT_RIGHT;?>
                ,handler: function(){
                    clickOpenPage('center',node.text, '<?=$this->URL_ADD_ITEM?>objectId=new&parent=' + node.attributes.parentId);
                }
            },{
                text: '<?=SHOW_DETAIL?> &raquo; ' + node.text
                ,iconCls: 'icon-application_form_magnify'
                ,disabled:showDisabled
                ,hidden:<?=$READ_RIGHT?>
                ,handler: function(){
                    clickOpenPage('center','', '<?=$this->URL_SHOWITEM;?>objectId=' + node.attributes.subjectId);
                }
            }]
        });
        event.stopEvent();
        contextMenu.showAt(event.xy); 
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>