<?
///////////////////////////////////////////////////////////
// @THORN Visal
// Date: 16.12.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("STAFF_CONTRACT");
$OBJECT_FORM->setLoadUrl('/staffcontract/jsonload/');
$OBJECT_FORM->setSaveUrl('/staffcontract/jsonsave/');

$MEMBER_GRID = new CamemisGrid("MEMBERS", "LIST");
$MEMBER_GRID->setLoadUrl("/staffcontract/jsonload/");
$MEMBER_GRID->setSaveUrl("/staffcontract/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

    Ext.apply(Ext.form.VTypes, {
        daterange : function(val, field) {
            var date = field.parseDate(val);

            if(!date){
                return false;
            }
            if (field.startDateField && (!this.dateRangeMax || (date.getTime() !== this.dateRangeMax.getTime()))) {
                var start = Ext.getCmp(field.startDateField);
                start.setMaxValue(date);
                start.validate();
                this.dateRangeMax = date;
            }
            else if (field.endDateField && (!this.dateRangeMin || (date.getTime() !== this.dateRangeMin.getTime()))) {
                var end = Ext.getCmp(field.endDateField);
                end.setMinValue(date);
                end.validate();
                this.dateRangeMin = date;
            }
            return true;
        }
    });
    
    Ext.onReady(function() {
        function cssStatus(v, p, record){
            return String.format('<div style=\"font-weight:bold;padding:4px;background:{1};color:{2};\">{0}</div>'
                ,v
                ,record.data['BG_COLOR']
                ,record.data['BG_COLOR_FONT']
            );
        }
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $MEMBER_GRID->addReadField("name: 'ID'");
        $MEMBER_GRID->addReadField("name: 'CODE'");
        $MEMBER_GRID->addReadField("name: 'NAME'");
        $MEMBER_GRID->addReadField("name: 'ROLE'");
        $MEMBER_GRID->addReadField("name: 'BG_COLOR'");
        $MEMBER_GRID->addReadField("name: 'BG_COLOR_FONT'");
        $MEMBER_GRID->addReadField("name: 'STATUS_KEY'");
        
        $MEMBER_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: 85, renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY'");
        $MEMBER_GRID->addColumn("header: '<b>" . CODE . "</b>', align:'left', width: 150, dataIndex: 'CODE'");
        $MEMBER_GRID->addColumn("header: '<b>" . NAME . "</b>', align:'left', width: 100, dataIndex: 'NAME'");
        $MEMBER_GRID->addColumn("header: '<b>" . USER_ROLE . "</b>', align:'left', width: 100, dataIndex: 'ROLE'");
        
        
        $MEMBER_GRID->baseParams = "
            start:0
            ,limit:100
            ,cmd: 'jsonShowAllMembers'
        ";
        
        $MEMBER_GRID->loadMask = true;
        $MEMBER_GRID->isObjectDefaultOnLoad = true;
        $MEMBER_GRID->isQuickySearch = true;   
        $MEMBER_GRID->renderJS();
        
        ///////////////////////////////////////////////////////////
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        ");
        
        if($this->objectId != "new"){
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleRemove());
            
            $OBJECT_FORM->setOnEmbeddedRemoveEvents("
                XMsg('".STATUS."','".MSG_ACTION_REMOVED_ITEM."'); 
                window.parent.Ext.getCmp('STAFF_CONTRACT_LIST_ID').store.reload();
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0); 
            ");
            
            $OBJECT_FORM->setLoadParams("
                cmd: 'jsonLoadStaffContract'
                ,objectId: '".$this->objectId."'
            ");
            
            $OBJECT_FORM->setRemoveParams("
                cmd: 'jsonRemoveStaffContract'
                ,objectId: '".$this->objectId."'
            "); 
            
        }
        
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        
        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonSaveStaffContract'
            ,objectId: '".$this->objectId."'
        ");
        
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
            window.parent.Ext.getCmp('STAFF_CONTRACT_LIST_ID').store.reload();
            var result = Ext.util.JSON.decode(action.response.responseText);
            window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
         ");    
        
        $OBJECT_FORM->addObjectItems("
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,collapsible: true
            ,collapsed: false
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {".CamemisField::Textfield("NAME", "NAME", NAME, false, false, false, false)."}
                    ,{".CamemisField::comboCamemisTypes("CONTRACT_TYPE", CONTRACT_TYPE, false,false, true)."}
                    ,{
                        name: 'START_DATE'
                        ,hidden: false
                        ,width: 250
                        ,fieldLabel: '" . START_DATE . "'
                        ,xtype: 'datefield'
                        ,id: 'START_DATE'
                        ,vtype: 'daterange'
                        ,endDateField: 'EXPIRED_DATE'
                        ,format: '" . setExtDatafieldFormat() . "'
                        ,allowBlank: true
                    },{
                        name: 'EXPIRED_DATE'
                        ,hidden: false
                        ,width: 250
                        ,fieldLabel: '" . EXPIRED_DATE . "'
                        ,xtype: 'datefield'
                        ,id: 'EXPIRED_DATE'
                        ,vtype: 'daterange'
                        ,format: '" . setExtDatafieldFormat() . "'
                        ,startDateField: 'START_DATE'
                        ,allowBlank: true
                    }]
            }]   
        ");
        
        $OBJECT_FORM->addObjectItems("
            title: '".STAFF."'
            ,id: 'STAFF'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,tbar: ['->',{
                    text: '".STAFF."'
                    ,iconCls:'icon-add_users'
                    ,handler: function(){
                        var win = new Ext.Window({
                            title: '".STAFF."'
                            ,id: 'OPEN_WINDOW'
                            ,closable:true
                            ,width:percentWidth(70)
                            ,height: percentHeight(90)
                            ,plain:true
                            ,modal: true
                            ,layout:'border'
                            ,border: false
                            ,collapsible: false
                            ,split: true
                            ,items: [{
                                collapsible: false
                                ,id: 'center'
                                ,region:'center'
                                ,margins: '3 3 3 0'
                                ,layout: 'fit'
                                ,items: [{xtype: '".$MEMBER_GRID->getObjectXType()."'}]
                            }]
                           
                        });
                        win.show();
                        var grid = Ext.getCmp('".$MEMBER_GRID->getObjectId()."');
                        if(grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {
                            var record = grid.store.getAt(rowIndex);
                            Ext.getCmp('STAFF_NAME').setValue(record.data.NAME);
                            Ext.getCmp('CHOSE_STAFF').setValue(record.data.ID);
                            win.close();   
                        })
                    }
                }]
                ,layout: 'form'
                ,items:[
                    {".CamemisField::Textfield("STAFF_NAME", "STAFF_NAME", STAFF, false, true, false)."}
                    ,{".CamemisField::Hidden("CHOSE_STAFF")."}
                ]
            }]
        ");
        
        $apply = "var grid = Ext.getCmp('".$MEMBER_GRID->getObjectId()."');";
        $apply .= "if (grid.getSelectionModel().hasSelection()) {";
        $apply .= "var row = grid.getSelectionModel().getSelection()[0];";
        $apply .= "console.log(row.get('dni'))}";
        
        if($MEMBER_GRID->getObjectXType())
            //print $apply;
        
        $OBJECT_FORM->addObjectItems("
            title: '".DESCRIPTION."'
            ,collapsible: true
            ,collapsed: false
            ,width:550
            ,style: 'padding-bottom: 5px'
            ,items:[{
                layout: 'fit'
                ,border: false
                ,bodyStyle: 'padding:5px'
                ,items:[{".CamemisField::Textarea("DESCRIPTION",DESCRIPTION,200,false,false)."}]
            }]   
        ");
        
        $OBJECT_FORM->isObjectDefaultOnLoad = ($this->objectId=="new")?false:true; 
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->renderJS();
        
        ///////////////////////////////////////////////////////////////////////////////////

                       
        
        $VIEWPORT = "";
        if($this->objectId != "new"){
        switch(UserAuth::getUserType()){
            case "SUPERADMIN":
            $VIEWPORT .= "
                title: ''
                ,collapsible: false
                ,id: 'center'
                ,region:'center'
                ,layout: 'card'
                ,activeItem: 0
                ,margins: '3 3 3 0'
                ,border: false
                ,items:[{
                    layout:'fit'
                    ,bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px'
                    ,border: false
                    ,items:[{
                        xtype: 'tabpanel'
                        ,id:'TABPANEL_ID'
                        ,tabPosition: 'top'
                        ,plain:true
                        ,activeTab: 0
                        ,enableTabScroll:true
                        ,items:[{
                            title: '".MAIN_CONTENT."'
                            ,layout:'fit'
                            ,items: [{xtype: '".$OBJECT_FORM->getObjectXType()."'}]
                        },{
                            title:'".ATTACHMENTS."'
                            ,layout:'fit'
                            ,items: [new Ext.ux.IFrameComponent({ id: 'STUDENT_ADVISORY', url:'/dataset/attachment/?camIds=".$this->urlEncryp->encryptedGet("template=STAFF_CONTRACT&count=1&objectId=".$this->objectId."")."'})]
                        }]
                    }]
                }]
            ";
                break;
            default:
                $VIEWPORT .= "
                    xtype: 'panel'
                    ,id: 'panel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,border: false
                    ,layout: 'card'
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items: [{
                        layout: 'fit'
                        ,border: false
                        ,items: [new Ext.ux.IFrameComponent({ id: 'STAFF_CONTRACT', url:'/dataset/attachment/?camIds=".$this->urlEncryp->encryptedGet("template=STAFF_CONTRACT&count=1&objectId=".$this->objectId."")."'})]
                    }]
                ";
                break;   
        }
        }else{
            $VIEWPORT .= "
                xtype: 'panel'
                ,id: 'panel'
                ,border: false
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items: [{xtype: '".$OBJECT_FORM->getObjectXType()."'}]
                }]
            ";
        }
        
        ///////////////////////////////////////////////////////////////////////////////////
        $js = "viewport = new Ext.Viewport({";
            $js .= "layout: 'fit'";
            $js .= ",border: false";
            $js .= ",items: [{".$VIEWPORT."}]";
        $js .= "});";
        
        print $js;
        ?>
          
        
    });
    
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>