<?
///////////////////////////////////////////////////////////
// @veasna
// Date: 05.07.2013
// 
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'clients/CamemisViewport.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("STUDENT");
$OBJECT_FORM->setLoadUrl('/student/jsonload/');
$OBJECT_FORM->setSaveUrl('/student/jsonsave/');

$OBJECT_GRID = new CamemisGrid("FINANCE", "LIST");
$OBJECT_GRID->setLoadUrl("/finance/jsonload/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
Ext.onReady(function() {
	
    function cssTextBold(value, metadata, record){
        
        return '<div style="font-weight:normal; color:#333; padding: 5px;">' + value + '</div>';
    }

    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    $OBJECT_FORM->addObjectItems("
        xtype:'fieldset'
        ,checkboxToggle:true
        ,collapsed: false
        ,title: '".PERSONAL_INFORMATION."'
        ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;padding:10px'
        ,width: 250
        ,items:[
            {".CamemisField::Textfield("CODE", "CODE", SHORT." (PRE_FEE-)", false, false, false, 200)."}
            ,{".CamemisField::Textfield("NAME", "NAME", FEE_NAME, false, false, false, 200)."}		
        ]
    ");   
    
    $OBJECT_FORM->addTBarItems("
        text: '".RESET."'
        ,iconCls:'icon-arrow_undo'
        ,handler: function(){
            ".CamemisPage::setRequestURI(false)."
        }
    ");
    
    
    $OBJECT_FORM->addTBarItems("
        text: '".FIND."'
        ,formBind:true
        ,iconCls:'icon-magnifier'
        ,scope:this
        ,handler:function(){
        name = this.getForm().findField('NAME').getValue();
        Feecode = this.getForm().findField('CODE').getValue();

        Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.baseParams = {
            cmd: 'jsonSearchFeePrePayment'
            ,programId:'".$this->objectId."'
            ,code:Feecode
            ,FEE_NAME:name
            ,type:'training'
        };
        Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.load();
    }
    "); 

    $OBJECT_FORM->addTBarItems("
        text: '".ADD_NEW_ITEM."'
        ,iconCls:'icon-application_form_add'
        ,scope:this
        ,handler: function(){
            Ext.getCmp('WEST_ID').collapse();
            clickOpenPage('center','', '/finance/showprepaidtraining/?objectId=new&program=".$this->objectId."');
        }
    ");

    $OBJECT_FORM->labelAlign = "top";
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->isKeys = false;
    $OBJECT_FORM->renderJS();
    
    ///////////////////////////////////////////////////////
     $OBJECT_GRID->addReadField("name: 'ID'");
    $OBJECT_GRID->addReadField("name: 'FEE_NAME'");
    $OBJECT_GRID->addReadField("name: 'FEES'");
    $OBJECT_GRID->addReadField("name: 'TAX_CATEGORY'");
    $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");
    
    $OBJECT_GRID->addColumn("header: '<b>".FEE_NAME."</b>', align:'left', renderer: cssTextBold, width: 280, sortable: true, dataIndex: 'FEE_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".FEES."</b>', align:'right', renderer: cssTextBold, width: 140, sortable: true, dataIndex: 'FEES'");
    $OBJECT_GRID->addColumn("header: '<b>".TAX_CATEGORY."</b>', align:'right', renderer: cssTextBold, width: 100, sortable: true, dataIndex: 'TAX_CATEGORY'");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_DATE."</b>', align:'right', renderer: cssTextBold, width: 150, sortable: true, dataIndex: 'CREATED_DATE'");
   
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'REFRESH_ID'
            ,text: '".REFRESH."'
            ,iconCls:'icon-reload'
            ,scope:this
            ,disabled: false
            ,handler: function(){
               Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
            }
        }]);
    ");
    
    $OBJECT_GRID->baseParams = "
        cmd: 'jsonSearchFeePrePayment'
        ,programId:'".$this->objectId."'
        
    ";
    
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();  
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{
               	region:'west'
                ,title: '<?=PREPAY_FEE;?>'
                ,id:'WEST_ID'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width: 270
                ,minSize: 270
                ,maxSize: 270
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
                }]
            }]
        }]
    });
    
    var myGrid = Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>');
    if (myGrid) myGrid.on('cellclick', function(grid,rowIndex) {
        Ext.getCmp('WEST_ID').collapse();
        var record = grid.store.getAt(rowIndex);
        clickOpenPage('center',record.data.FEE_NAME,'/finance/showprepaidtraining/?objectId=' + record.data.ID+'&program=<?=$this->objectId;?>');
    });
   
}); 
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>