<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTree("SCHOOL", "LIST");
$OBJECT_TREE->setURL('/school/jsontree/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<style>
    .x-vr-tab-panel-bwrap {
        background: none repeat scroll 0 0 <?=CamemisPage::userBgColor();?>;
        border-left: 1px solid #99BBE8;
        float: right;
        padding: 3px;
    }
</style>
<script>

    Ext.onReady(function() {

        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $TREE_ITEMS = Array();
        
        $MAIN_CONTENT = "{
            text:'".MY_SCHOOL."'
            ,leaf:true
            ,url:'/school/showitem/?camIds=".$this->urlEncryp->encryptedGet("target=main_content")."'
            ,cls:'nodeTextBold'
            ,iconCls: 'icon-component'
        }";
        $TREE_ITEMS[] = $MAIN_CONTENT;
        $SETTINGS = "{
            text:'".SETTINGS."'
            ,leaf:true
            ,url:'/school/showitem/?camIds=".$this->urlEncryp->encryptedGet("target=settings")."'
            ,cls:'nodeTextBold'
            ,iconCls: 'icon-component_yellow'
        }";
        $TREE_ITEMS[] = $SETTINGS;
        $SECURITY_SETTINGS = "{
            text:'".SECURITY_SETTINGS."'
            ,leaf:true
            ,url:'/school/showitem/?camIds=".$this->urlEncryp->encryptedGet("target=security")."'
            ,cls:'nodeTextBold'
            ,iconCls: 'icon-component_red'
        }";
        $TREE_ITEMS[] = $SECURITY_SETTINGS;
        $BACK_UP = "{
            text:'".BACK_UP." - Recovery'
            ,leaf:true
            ,url:'/school/showitem/?camIds=".$this->urlEncryp->encryptedGet("target=back_up")."'
            ,cls:'nodeTextBold'
            ,iconCls: 'icon-component_red'
        }";
        $TREE_ITEMS[] = $BACK_UP;
        $PRIVACY = "{
            text:'".PRIVACY."'
            ,leaf:true
            ,url:'http://camemis.com.kh/privacy'
            ,cls:'nodeTextBold'
            ,iconCls: 'icon-component_yellow'
        }";
        $TREE_ITEMS[] = $PRIVACY;
        $TERM_OF_SERVICES = "{
            text:'".TERM_OF_SERVICES."'
            ,leaf:true
            ,url:'http://camemis.com.kh/terms-of-services?limitstart=0'
            ,cls:'nodeTextBold'
            ,iconCls: 'icon-component_yellow'
        }";
        $TREE_ITEMS[] = $TERM_OF_SERVICES;
        
        $CHOOSE_ITEMS = "[".implode(',',$TREE_ITEMS)."]";
        
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        $OBJECT_TREE->addTBarItems("
            text:''
            ,tooltip:'".CAMEMIS_HELP."'
            ,iconCls: 'icon-help'
            ,handler:function(){
                ".CamemisPage::setEmbeddedHelp("E718-8B04")."
            }
        ");
        
        $OBJECT_TREE->isAsyncTreeNode = true;
        $OBJECT_TREE->setAsyncTreeNode($CHOOSE_ITEMS);
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible:true
                    ,split: true
                }
                ,items: [{
                    title: ''
                    ,id:'WEST_ID'
                    ,region:'west'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width:230
                    ,minSize:230
                    ,maxSize:230
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                },{
                    title: ''
                    ,border:false
                    ,collapsible: false
                    ,region:'center'
                    ,id: 'center'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,margins: '3 3 3 0'
                    ,items: [new Ext.ux.IFrameComponent({ id: 'MAIN_CONTENT', url:'/school/showitem/?camIds=<?=$this->urlEncryp->encryptedGet("target=main_content")?>'})]
                }]
            }]
        });
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node, event){
            clickOpenPage('center','',node.attributes.url);
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>