<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $SCHOOL = "{
            title: '".MAIN_CONTENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SCHOOL', url: '/school/showmain/?camIds=".$this->urlEncryp->encryptedGet("target=main_content")."'})]
        }";
        $PENEL_ITEMS[] = $SCHOOL;
        
        $SETTING = "{
            title: '".ROOM_SETTINGS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SETTING', url: '/room/roomdescription/?camIds=".$this->urlEncryp->encryptedGet("target=setting")."'})]
        }";
        $PENEL_ITEMS[] = $SETTING;
        
        $ROOM = "{
            title: '".ROOM."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ROOM', url: '/room/?camIds=".$this->urlEncryp->encryptedGet("target=room")."'})]
        }";
        $PENEL_ITEMS[] = $ROOM;
        
        $CITY_PROVINCE = "{
            title: '".CITY_PROVINCE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'TOWN_CITY', url: '/dataset/alllocation/?camIds=".$this->urlEncryp->encryptedGet("target=town_city")."'})]
        }";
        $PENEL_ITEMS[] = $CITY_PROVINCE;
        
        $BRANCH_OFFICE = "{
            title: '".MULTIPLE_LOCATIONS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'MULTIPLE_LOCATIONS', url: '/dataset/allbranchoffices/?camIds=".$this->urlEncryp->encryptedGet("target=locations")."'})]
        }";
        $PENEL_ITEMS[] = $BRANCH_OFFICE;
        
        $TRANSLATION = "{
            title: '".TRANSLATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'TRANSLATION', url: '/translation/?camIds=".$this->urlEncryp->encryptedGet("target=translation")."'})]
        }";
        $PENEL_ITEMS[] = $TRANSLATION;

        $LOG = "{
            title: '"."Track"."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'LOG', url: '/log/?camIds=".$this->urlEncryp->encryptedGet("target=translation")."'})]
        }";
        $PENEL_ITEMS[] = $LOG;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>