<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $GENERAL_EDUCATION = "{
            title: '".GENERAL_EDUCATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'GENERAL_EDUCATION', url: '/student/importxls/?key=".camemisId()."&target=general'})]
        }";
        if (UserAuth::displayRoleGeneralEducation())
        $PENEL_ITEMS[] = $GENERAL_EDUCATION;
        
        $TRAINING_PROGRAMS = "{
            title: '".TRAINING_PROGRAMS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'GENERAL_EDUCATION', url: '/student/importxls/?key=".camemisId()."&target=training'})]
        }";
        if (UserAuth::displayRoleTrainingEducation())
        $PENEL_ITEMS[] = $TRAINING_PROGRAMS;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>