<?
///////////////////////////////////////////////////////////
// @sor Veasna
// Date: 12.07.2014
/////////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisTrainingTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTrainingTree("TRAINING_TRANSFER","LIST");
$OBJECT_TREE->setURL("/training/jsontree/");
$OBJECT_TREE->setSaveUrl("/training/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    var choosedate = '<?=date('Y-m-d');?>';
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        
        
        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems("
            id: 'REFRESH'
            ,scope:this
            ,text:'".REFRESH."'
            ,iconCls:'icon-arrow_refresh'
            ,handler: function(){
                ".CamemisPage::setRequestURI(false)."
            }
        ");
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        $OBJECT_TREE->addTBarItems("
            xtype: 'buttongroup'
            ,items:[{
                xtype:'datefield'
                ,format: '" . setExtDatafieldFormat() . "'
                ,width:120
                ,name:'choosedate'
                ,value:'".getShowDate(date('d-m-Y'))."'
                ,listeners: {
                    'select' : function(dp, date) {
                        myTree = ".$OBJECT_TREE->ExtgetCmp().";
                        myTree.loader.baseParams.choosedate = date.format('Y-m-j');
                        myTree.root.reload();
                    }
                }
            }]
        ");
        
        $OBJECT_TREE->isTreeExpand = false;
        $OBJECT_TREE->setBaseParams("
            cmd: 'jsonTreeAllTrainings'
            ,choosedate:choosedate

        ");
        
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout: 'fit'
                ,border: false
                ,id: 'CONTENT'
                ,items:[{
                    layout:'border'
                    ,border: false
                    ,defaults: {
                        collapsible: true
                        ,split: true
                    }
                    ,items: [{
                        title:''
                        ,layout:'fit'
                        ,region:'west'
                        ,id: 'WEST_ID'
                        ,margins: '3 0 3 3'
                        ,cmargins: '3 3 3 3'
                        ,width:350
                        ,minSize:350
                        ,maxSize:350
                        ,bodyStyle: 'background-color:#E0E7F7'
                        ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                    },{
                        title: ''
                        ,collapsible: false
                        ,id: 'center'
                        ,region:'center'
                        ,layout: 'card'
                        ,activeItem: 0
                        ,margins: '3 3 3 0'
                        ,items: [{
                            border: false
                            ,layout: 'anchor'
                            ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                            ,items: [{
                                title: ''
                                ,height:60
                                ,width:500
                                ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                                ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                            }]
                        }]
                    }] 
                }]
            }]
        });
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node, e){
            if(node.attributes.objecttype=='CLASS') {
               clickOpenPage('center','<?=CLASS_NAME;?>&raquo;'+node.text,'/enrollment/transfertraining/?objectId=' + node.id);
            } 
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>