<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 25.11.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_school/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$entries = GuardianDBAccess::sqlStudentGuardian($this->objectId);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        if($entries){
            foreach($entries as $value){
                if(!SchoolDBAccess::displayPersonNameInGrid()){
                    $studentName = setShowText($value->LASTNAME) . " " . setShowText($value->FIRSTNAME);
                }else{
                    $studentName = setShowText($value->FIRSTNAME) . " " . setShowText($value->LASTNAME);
                }
                $panel = "{
                    title: '".$studentName."'
                    ,layout: 'fit'
                    ,items: [new Ext.ux.IFrameComponent({ id: 'IFRAME_".$value->ID."', url:'/main/showstudentmain/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$value->ID."")."'})]
                }";
                $PENEL_ITEMS[] = $panel;    
            }    
        }
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?> 
                }]
            }]
        }); 
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>