<?
///////////////////////////////////////////////////////////
// @veasna
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();
require_once 'models/app_university/academic/AcademicDBAccess.php';

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("COLUMN");
$OBJECT_FORM->setLoadUrl('/dataset/jsonload/');

/*
$facette=ExaminationDBAccess::findAcademicById($this->academicId);
$params["type"]=6;
$params["schoolyearId"]=$facette->SCHOOL_YEAR;
$params["gradeId"]=$facette->GRADE_ID;
$subjectExam=ExaminationDBAccess::getSQLExamination($params);
$item="";
if($subjectExam){
    foreach($subjectExam as $values){
        $item={boxLabel: '".DETAIL_INFORMATION."', name: 'NAME'}        
    }    
}
*/
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
$bnt=$this->bnt;
$params='';
switch ($bnt){
   
     case '1':
        $objectId=isset($_GET['objectId'])?$_GET['objectId']:'';
        $academic=isset($_GET['academicId'])?$_GET['academicId']:'';
        $params='&objectId='.$objectId;
        $params.='&academicId='.$academic;
        $params.='&type='.$this->type;
        $params.='&bnt='.$bnt;
        break;
    case '5':
        
        $params='&objectType='.$this->objectType;
        $params.='&enrollExamType='.$this->enrollExamType;
        $params.='&campus='.$this->campus;
        $params.='&gender='.$this->gender;
        $params.='&examResult='.$this->examResult;
        $params.='&type='.$this->type;
        $params.='&bnt='.$bnt;
        break;
}

?>
<script>
Ext.onReady(function() {
    
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $PERSONAL_INFORMATION = "{
        xtype: 'checkboxgroup'
        ,fieldLabel: '<b>".PERSONAL_INFORMATION."</b>'
        ,columns: 2
        ,items: [
            {boxLabel: '".CANDIDATE_CODE."', name: 'CANDIDATE_CODE'}
            ,{boxLabel: '".FULL_NAME."', name: 'FULL_NAME'}
            ,{boxLabel: '".FIRSTNAME."', name: 'FIRSTNAME'}
            ,{boxLabel: '".LASTNAME."', name: 'LASTNAME'}
            ,{boxLabel: '".LASTNAME_LATIN."', name: 'LASTNAME_LATIN'}
            ,{boxLabel: '".FIRSTNAME_LATIN."', name: 'FIRSTNAME_LATIN'}
            ,{boxLabel: '".GENDER."', name: 'GENDER'}
            ,{boxLabel: '".DATE_BIRTH."', name: 'DATE_BIRTH'}
            ,{boxLabel: '".PHONE."', name: 'PHONE'}
            ,{boxLabel: '".EMAIL."', name: 'EMAIL'}
            ,{boxLabel: '".SIGNATURE_STUDENT_SUBMISSION."',name:'SIGNATURE_STUDENT_SUBMISSION'}
        ]
    }";
    
   $ROOM_INFORMATION="{
        xtype: 'checkboxgroup'
        ,fieldLabel: '<b>".ROOM."</b>'
        ,columns: 2
        ,items: [
            {boxLabel: '".ROOM."', name: 'ROOM'}
        ]
    }"; 
    
    $SUBJECT_INFORMATION = "{
        xtype: 'checkboxgroup'
        ,fieldLabel: '<b>".EXAM_SUBJECT."</b>'
        ,columns: 2
        ,items: [
            {boxLabel: '".SUBJECT."', name: 'EXAM_SUBJECT'}
            ,{boxLabel: '".AVERAGE."', name: 'EXAM_AVERAGE'}
            ,{boxLabel: '".EXAM_RESULT."', name: 'EXAM_RESULT'}
        ]
    }";
       
    
    $HEADER_INFORMATION = "{
        xtype: 'checkboxgroup'
        ,fieldLabel: '<b>".SCHOOL_LETTER_HEADER."</b>'
        ,columns: 2
        ,items: [
            {boxLabel: '".DETAIL_INFORMATION."', name: 'HEAD_NAME'}

        ]
    }";
    
    $FOOTER_INFORMATION = "{
        xtype: 'checkboxgroup'
        ,fieldLabel: '<b>".SCHOOL_LETTER_FOOTER."</b>'
        ,columns: 2
        ,items: [
            {boxLabel: '".CREATED_DATE."', name: 'SIGNATURE'}
        ]
    }";
    
      
    $DETAIL_INFORMATION_ITEMS = "[";
        $DETAIL_INFORMATION_ITEMS .= $PERSONAL_INFORMATION;
        $DETAIL_INFORMATION_ITEMS .= ",".$SUBJECT_INFORMATION;
        $DETAIL_INFORMATION_ITEMS .= ",".$ROOM_INFORMATION;    
        $DETAIL_INFORMATION_ITEMS .= ",".$HEADER_INFORMATION;
        $DETAIL_INFORMATION_ITEMS .= ",".$FOOTER_INFORMATION;
    $DETAIL_INFORMATION_ITEMS .= "]";
    
    $DETAIL_INFORMATION = "
    {
        title: ''
        ,border:false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 500
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:5px'
            ,items: ".$DETAIL_INFORMATION_ITEMS."
        }]
    }
    ";
    
    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: [
            ".$DETAIL_INFORMATION."
        ]
    ";
    $OBJECT_FORM->addObjectItems($items);
    

   $OBJECT_FORM->addTBarItems("
        text:'".EXPORT_TO_EXCEL."'
        ,iconCls:'icon-lightning'
        ,handler:function(){
            myForm = Ext.getCmp('".$OBJECT_FORM->getObjectId()."');
            form = myForm.getForm();
                      
            CANDIDATE_CODE = form.findField('CANDIDATE_CODE').getValue()?1:0;
            FULL_NAME = form.findField('FULL_NAME').getValue()?1:0;
            FIRSTNAME = form.findField('FIRSTNAME').getValue()?1:0;
            LASTNAME = form.findField('LASTNAME').getValue()?1:0;
            LASTNAME_LATIN = form.findField('LASTNAME_LATIN').getValue()?1:0;
            FIRSTNAME_LATIN = form.findField('FIRSTNAME_LATIN').getValue()?1:0;
            GENDER = form.findField('GENDER').getValue()?1:0;
            DATE_BIRTH = form.findField('DATE_BIRTH').getValue()?1:0;
            PHONE = form.findField('PHONE').getValue()?1:0;
            EMAIL = form.findField('EMAIL').getValue()?1:0;
            SIGNATURE_STUDENT_SUBMISSION = form.findField('SIGNATURE_STUDENT_SUBMISSION').getValue()?1:0;
            
            ROOM = form.findField('ROOM').getValue()?1:0;
            
            SUBJECT = form.findField('EXAM_SUBJECT').getValue()?1:0;
            AVERAGE = form.findField('EXAM_AVERAGE').getValue()?1:0;
            EXAM_RESULT = form.findField('EXAM_RESULT').getValue()?1:0;
            
            HEAD_NAME = form.findField('HEAD_NAME').getValue()?1:0;
            SIGNATURE = form.findField('SIGNATURE').getValue()?1:0;
            
            var params = '';
            params = params + 'CANDIDATE_CODE=' + CANDIDATE_CODE +
            params + '&FULL_NAME=' + FULL_NAME +
            params + '&FIRSTNAME=' + FIRSTNAME +
            params + '&LASTNAME=' + LASTNAME +
            params + '&LASTNAME_LATIN=' + LASTNAME_LATIN +
            params + '&FIRSTNAME_LATIN=' + FIRSTNAME_LATIN +
            params + '&GENDER=' + GENDER +
            params + '&DATE_BIRTH=' + DATE_BIRTH +
            params + '&PHONE=' + PHONE +           
            params + '&EMAIL=' + EMAIL +
            params + '&SIGNATURE_STUDENT_SUBMISSION=' + SIGNATURE_STUDENT_SUBMISSION +
            params + '&ROOM=' + ROOM +    
            params + '&SUBJECT=' + SUBJECT +
            params + '&AVERAGE=' + AVERAGE +
            params + '&EXAM_RESULT=' + EXAM_RESULT +
            params + '&HEAD_NAME=' + HEAD_NAME +
            params + '&SIGNATURE=' + SIGNATURE;
            
            window.location='/export/exam?' + params+'".$params."';
        }
    "); 
      
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 150;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>