<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 25.09.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("ACADEMIC_INFORMATION");
$OBJECT_FORM->setSaveUrl("/academicsetting/jsonsave/");
$OBJECT_FORM->setLoadUrl("/academicsetting/jsonload/");

$STUDENT_TREE = new CamemisTree("ACADEMIC_INFORMATION","STUDENT_LIST");
$STUDENT_TREE->setURL('/academicsetting/jsontree/');

if($this->objectId == "new"){
    $parentId = isset($_GET['parentId'])? addText($_GET['parentId']):'';
}else{
    $facette = AcademicAdditionalDBAccess::findAcademicAdditionalFromId($this->objectId);
    $parentId = $facette?$facette->PARENT:'';    
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
Ext.onReady(function() {
	
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    if(!$parentId){
        $store = "[
            [1, 'Checkbox']
            ,[2, 'Radiobox']
            ,[3, 'Inputfield']
            ,[4, 'Textarea']
        ]";
        
        $FORM_ITEMS = "[{
            ".CamemisField::Textfield("NAME_ID", "NAME", NAME)."
        },{
            ".CamemisField::Combo('CHOOSE_TYPE', TYPE, $store, false, false, false, false, true)."
        }]";
    }else{
       $FORM_ITEMS = "[
            {".CamemisField::Textfield("NAME_ID", "NAME", NAME)."}
        ]"; 
    }

    $DETAIL_INFORMATION = "
    {
        title: '".ADDITIONAL_INFORMATION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: ".$FORM_ITEMS."
        }]
    }
    ";
    
    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:0px'
        ,items: [
            ".$DETAIL_INFORMATION."
        ]
    ";
    $OBJECT_FORM->addObjectItems($items);
    
   
    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
    ");
    
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    
    $OBJECT_FORM->setLoadParams("
        cmd: 'jsonLoadAdditionalInformation'
        ,objectId: '".$this->objectId."'
    ");
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'jsonSaveAcademicAdditional'
        ,objectId: '".$this->objectId."'
        ,parentId: '".$parentId."'
    ");

     if($this->objectId == "new"){
            
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('TREE.ACADEMIC_INFORMATION_LIST_ID');
            myNode = myTree.getNodeById('".$parentId."');
            if(myNode.parentNode==null){
                myTree.root.reload();
            }else{
                var parentId = myNode.parentNode.id
                myPerentNode = myTree.getNodeById(parentId);
                if(myNode.isLeaf()){
                    if(myPerentNode){
                        myPerentNode.reload();
                        myPerentNode.expand(true, false);
                    }else{
                        myTree.root.reload();
                    }
                }else{
                    if (myNode.hasChildNodes()) {
                        myNode.reload();
                        myNode.expand(true, false);
                    }
                }
            }
            var result = Ext.util.JSON.decode(action.response.responseText);
            window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
        ");
    }else{
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleRemove());
        $OBJECT_FORM->setRemoveParams("
            cmd: 'jsonRemoveAcademicAdditional'
            ,objectId: '".$this->objectId."'
        ");
        
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
            myTree = window.parent.Ext.getCmp('TREE.ACADEMIC_INFORMATION_LIST_ID');
            myNode = myTree.getNodeById('".$parentId."');
            if(myNode.parentNode==null){
                myTree.root.reload();
            }else{
                var parentId = myNode.parentNode.id
                myPerentNode = myTree.getNodeById(parentId);
                if(myNode.isLeaf()){
                    if(myPerentNode){
                        myPerentNode.reload();
                        myPerentNode.expand(true, false);
                    }else{
                        myTree.root.reload();
                    }
                }else{
                    if (myNode.hasChildNodes()) {
                        myNode.reload();
                        myNode.expand(true, false);
                    }
                }
            }
            ".camemisPage::setRequestURI()."
        ");
        
        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            XMsg('".STATUS."','".RECORD_WAS_REMOVED."'); 
            myTree = window.parent.Ext.getCmp('TREE.ACADEMIC_INFORMATION_LIST_ID');
            myNode = myTree.getNodeById('".$parentId."');
            if(myNode.parentNode==null){
                myTree.root.reload();
            }else{
                var parentId = myNode.parentNode.id
                myPerentNode = myTree.getNodeById(parentId);
                if(myNode.isLeaf()){
                    if(myPerentNode){
                        myPerentNode.reload();
                        myPerentNode.expand(true, false);
                    }else{
                        myTree.root.reload();
                    }
                }else{
                    if (myNode.hasChildNodes()) {
                        myNode.reload();
                        myNode.expand(true, false);
                    }
                }
            }
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        "); 
    }

    if($this->objectId != "new"){
        $OBJECT_FORM->isObjectDefaultOnLoad = true;
    }
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();

    $js = "";
    $js .= "viewport = new Ext.Viewport({";
        $js .= "layout: 'fit'";
        $js .= ",border: false";
        $js .= ",items: [{";
            $js .= "xtype: 'panel'";
            $js .= ",id: 'panel'";
            $js .= ",border: false";
            $js .= ",layout: 'card'";
            $js .= ",activeItem: 0";
            $js .= ",items: [{";
                $js .= "layout: 'fit'";
                $js .= ",border: false";
                $js .= ",items: [{xtype: '".$OBJECT_FORM->getObjectXType()."'}]";
            $js .= "}]";    
        $js .= "}]";
    $js .= "});";
    print $js;
    
    if($this->objectId != "new"){
         $js = "";
         $js .= "var myTree = ".$STUDENT_TREE->ExtgetCmp().";";
         $js .= "if (myTree) myTree.on('checkchange', function(node, checked){";
            
            ///////////////////////////////////////////////////////////////////////////
            $js .= "myTree = window.parent.Ext.getCmp('TREE.ACADEMIC_INFORMATION_LIST_ID');";
            $js .= "myNode = myTree.getNodeById('".$parentId."');";
            $js .= "if(myNode.parentNode==null){";
                $js .= "myTree.root.reload();";
            $js .= "}else{";
                $js .= "var parentId = myNode.parentNode.id";
                $js .= "myPerentNode = myTree.getNodeById(parentId);";
                $js .= "if(myNode.isLeaf()){";
                    $js .= "if(myPerentNode){";
                        $js .= "myPerentNode.reload();";
                        $js .= "myPerentNode.expand(true, false);";
                    $js .= "}else{";
                        $js .= "myTree.root.reload();";
                    $js .= "}";
                $js .= "}else{";
                    $js .= "if (myNode.hasChildNodes()) {";
                        $js .= "myNode.reload();";
                        $js .= "myNode.expand(true, false);";
                    $js .= "}";
                $js .= "}";
            $js .= "}";
            ///////////////////////////////////////////////////////////////////////////
                      
            $js .= "Ext.Ajax.request({";
                $js .= "url:'/academicsetting/jsonsave/'";
                $js .= ",method:'POST'";
                $js .= ",params:{";
                    $js .= "cmd:'jsonAcademicToAdditionalInformation'";
                    $js .= ",checked: checked";
                    $js .= ",academic: node.id";
                    $js .= ",objectId: '".$this->objectId."'";
                $js .= "}";
                $js .= ",success: function(response, options) {";
                    $js .= "result = Ext.util.JSON.decode(response.responseText);";
                    $js .= "XMsg('".STATUS."',result.msg);";
                $js .= "}";
            $js .= "});";
        $js .= "});";
        
        print $js;    
    }
    ?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>