<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("ACADEMICDATE");
$OBJECT_FORM->setLoadUrl('/academicdate/jsonload/');
$OBJECT_FORM->setSaveUrl('/academicdate/jsonsave/');


print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
	
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    $DETAIL_INFORMATION = "
    {
        title: '".DETAIL_INFORMATION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF;padding:10px'
            ,items: [
                {".CamemisField::Textfield("NAME", "NAME", NAME, true)."}
                ,{".CamemisField::ComboSchoolTerm(false)."}
                ,{".CamemisField::Numberfield("SORT", "SORT", SORTKEY, false)."}
            ]
        }]
    }
    ";
    
    $formItems = "[";
    $formItems .= $DETAIL_INFORMATION;
    $formItems .= "]";
    
    $OBJECT_FORM->addObjectItems("
    	xtype: 'panel'
    	,border: false
        ,bodyStyle: 'padding:0px'
    	,layout: 'form'
    	,items: ".$formItems."
    ");
    
    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        }
    ");
    
    if (UserAuth::getACLValue("ACADEMIC_SETTING_EDIT_RIGHT"))
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());

    $OBJECT_FORM->setSaveParams("
        cmd: 'createOnlyItem'
    ");
	
    $OBJECT_FORM->setonEmbeddedEvents("
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        window.parent.Ext.getCmp('TREE.ACADEMICDATE_LIST_ID').root.reload();
        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
    ");

    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>