<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("ACADEMICDATE", "LIST");
$OBJECT_TREE->setURL('/academicdate/jsontree/');
$OBJECT_TREE->setSaveUrl('/academicdate/jsonsave/');

print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    var parentId=0;
    Ext.onReady(function() {

        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $OBJECT_TREE->isAsyncTreeNode = false;

        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        if (UserAuth::getACLValue("ACADEMIC_SETTING_EDIT_RIGHT")){
            $OBJECT_TREE->addTBarItems("
                text:'".ADD_A_NEW_ITEM."'
                ,tooltip:'".ADD_A_NEW_ITEM."'
                ,iconCls: 'icon-add'
                ,handler:function(){
                    clickOpenPage('center','".ADD_A_NEW_ITEM."', '/academicdate/additem/');
                }
            ");
        }
        
        $OBJECT_TREE->addTBarItems("
            text:''
            ,tooltip:'".CAMEMIS_HELP."'
            ,iconCls: 'icon-help'
            ,handler:function(){
                ".CamemisPage::setEmbeddedHelp("GENERAL_EDUCATION")."
            }
        ");
        
        $OBJECT_TREE->setBaseParams("
            cmd: 'jsonTreeAllAcademicDate'
        ");
        $OBJECT_TREE->setSaveParams("
            cmd: 'createOnlyItem'
        ");
        
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->setWindowLocation($this->URL_WINDOW_LOCATION);
        $OBJECT_TREE->isOnClickContextMenu = false;
        $OBJECT_TREE->isTreeExpand = false;
        $OBJECT_TREE->renderJS();

        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    region:'west'
                    ,title:'<?=SCHOOL_YEAR?>'
                    ,id: 'WEST_ID'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width:280
                    ,minSize:280
                    ,maxSize:280
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                },{
                    collapsible: false
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,items: [{
                        border: false
                        ,layout: 'anchor'
                        ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                        ,items: [{
                            title: ''
                            ,height:60
                            ,width:500
                            ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                            ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                        }]
                    }]
                }]
            }]
        });

        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node,event){
            var contextMenu = new Ext.menu.Menu({
                items: [{
                    text: '<?=SEMESTER;?> &raquo; ' + node.text
                    ,iconCls:'icon-date'
                    ,handler:function(){
                        clickOpenPage('center','', '<?=$this->URL_SHOWITEM;?>objectId=' + node.id);
                    }
                }]
            });
            event.stopEvent();
            contextMenu.showAt(event.xy);
        });
    });
</script>
<?
print$CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>