<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 15.01.2014
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'include/Common.inc.php'; 
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_university/GuardianDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$guardianId = Zend_Registry::get('USER')->ID;
$guardianObject = GuardianDBAccess::findObjectFromId($guardianId);
if(!$guardianObject) {header("Location: /main/permission/");exit;}

$OBJECT_TREE = new CamemisTree("GUARDIAN", "LIST");
$OBJECT_TREE->setURL("/guardian/jsontree/");
$OBJECT_TREE->setSaveUrl("/guardian/jsonsave/");

$imageGender = "/public/images/navigation/male.png";
$imageGenderHover = "/public/images/navigation/male-hover.png";
                
if(isset(Zend_Registry::get('USER')->GENDER)){
    switch(Zend_Registry::get('USER')->GENDER){
        case 1:
            $imageGender = "/public/images/navigation/male.png";
            $imageGenderHover = "/public/images/navigation/male-hover.png";
            break;
        case 2:
            $imageGender = "/public/images/navigation/female.png";
            $imageGenderHover = "/public/images/navigation/female-hover.png";
            break;
    }
}

$schoolName = (Zend_Registry::get('SCHOOL')->NAME)?Zend_Registry::get('SCHOOL')->NAME:"";
$personalimg = $imageGender;
$personalimgHover = $imageGenderHover;

?>
<script>
    
    Ext.onReady(function() {
        var button = Ext.get('show-btn');
        button.on('click', function(){
            addTab('PERSONAL_INFORMATION','<?=PERSONAL_INFORMATION;?>','/guardian/guardianshowitem/?objectId=<?=$guardianId?>');
        });
        var updateClock = function(){
            Ext.getCmp('clock').setText('<b><?=showCurrentDBDate();?> '+new Date().format('g:i:s A')+'</b>');
        }
        var clock = new Ext.Toolbar.TextItem({id:'clock',text: '<b><?=showCurrentDBDate();?> 00:00:00 AM</b>'});
        
        var task = {
            run: updateClock,//the method to run...
            interval: 1000 //every second
        }
        var runner = new Ext.util.TaskRunner();
        runner.start(task);
        
        Ext.state.Manager.setProvider(new Ext.state.CookieProvider());
        if (get_cookie('tokenId')) var tokenId = get_cookie('tokenId');
        <?
        $CAMEMIS_PAGE_OBJECT->setAddTab();
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        
        $CHOOSE_PANEL = array();
        
        $MY_CALENDAR = "{";
        $MY_CALENDAR .= "title: '".MY_CALENDAR."'";
        $MY_CALENDAR .= ",layout: 'fit',bodyStyle:'background:".CamemisPage::userBgColor().";padding:3px'";
        $MY_CALENDAR .= ",items: [new Ext.ux.IFrameComponent({ id: 'MY_CALENDAR', url:'/school/calendar/'})]";
        $MY_CALENDAR .= "}";
        $CHOOSE_PANEL[] = "" . $MY_CALENDAR . "";
        
        $BULLETIN_BOARD = "{";
        $BULLETIN_BOARD .= "title: '".BULLETIN_BOARD."'";
        $BULLETIN_BOARD .= ",layout: 'fit',bodyStyle:'background:".CamemisPage::userBgColor().";padding:3px'";
        $BULLETIN_BOARD .= ",items: [new Ext.ux.IFrameComponent({ id: 'BULLETIN_BOARD', url:'/bulletin/profilebulletin/?objectId=".$guardianId."'})]";
        $BULLETIN_BOARD .= "}";
        $CHOOSE_PANEL[] = "" . $BULLETIN_BOARD . "";
        
        $COMMUNICATION = "{";
        $COMMUNICATION .= "title: '".COMMUNICATION."'";
        $COMMUNICATION .= ",layout: 'fit',bodyStyle:'background:".CamemisPage::userBgColor().";padding:3px'";
        $COMMUNICATION .= ",items: [new Ext.ux.IFrameComponent({ id: 'COMMUNICATION', url:'/communication/'})]";
        $COMMUNICATION .= "}";
        $CHOOSE_PANEL[] = "" . $COMMUNICATION . "";
        
        $USER_TAB = "";
        $USER_TAB .= "var tabs =  new Ext.TabPanel({";
            $USER_TAB .= "autoTabs:true";
            $USER_TAB .= ",plain:true";
            $USER_TAB .= ",tabPosition: 'top'";
            $USER_TAB .= ",enableTabScroll:true";
            $USER_TAB .= ",activeTab:0,bodyStyle: 'background:".CamemisPage::userBgColor()."'";
            $USER_TAB .= ",items:[".implode(',',$CHOOSE_PANEL)."]";
        $USER_TAB .= "});";

        $USER_TAB_LOGIN = $USER_TAB;
        
        echo $USER_TAB_LOGIN;
        
        $eventJs = "";
        $eventJs .= "function showResult(btn){";
            $eventJs .= "if (btn == \"yes\"){";
                $eventJs .= "Ext.Ajax.request({";
                    $eventJs .= "url:'/school/jsonsave/'";
                    $eventJs .= ",method: 'POST'";
                    $eventJs .= ",params: {cmd:'jsonLogout'}";
                    $eventJs .= ",success: function(response, options) {";
                        $eventJs .= "window.location.href='".Zend_Registry::get('CAMEMIS_URL')."/'";
                    $eventJs .= "}";
                $eventJs .= "});";
            $eventJs .= "}";
        $eventJs .= "};";
        echo $eventJs;
        
        ////////////////////////////////////////////////////////////////////////
        //GENERAL EDUCATION TREE...
        ////////////////////////////////////////////////////////////////////////
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand("GENERAL_EDUCATION"));
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse("GENERAL_EDUCATION"));
        $OBJECT_TREE->isAsyncTreeNode = true;
        $OBJECT_TREE->setAsyncTreeNode(Utiles::getStudentGuardianHistyTreeItems($guardianId));
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    title: ''
                    ,id: 'app-header'
                    ,region: 'north'
                    ,height: 40
                    ,xtype: 'box'
                    ,html:'<p class="school-name"><?=$schoolName;?></p>'
                },{
                    title: ''
                    ,id:'MAIN_WEST_ID'
                    ,region:'west'
                    ,margins: '0 0 3 3'
                    ,cmargins: '0 3 3 3'
                    ,width: 220
                    ,minSize: 220
                    ,maxSize: 220
                    ,layout: 'fit'
                    ,items:[{
                        layout:'border'
                        ,border: false
                        ,defaults: {
                            collapsible: false
                            ,split: true
                        }
                        ,items: [{
                            title: ''
                            ,collapsible: false
                            ,region:'center'
                            ,id: 'westcenter'
                            ,layout: 'fit'
                            ,margins: '0 3 3 3'
                            ,border:false
                            ,bodyStyle: 'background:#dee7f6;'
                            ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype()?>'}]
                        },{
                            title:'<?=PERSONAL_INFORMATION;?>'
                            ,id:'SOUTH'
                            ,region:'south'
                            ,margins: '0 3 3 3'
                            ,cmargins: '0 3 3 3'
                            ,height:120
                            ,bodyStyle: 'padding:10px;'
                            ,items: [{
                                border: false
                                ,autoScroll: true
                                ,contentEl: 'initPersonal'
                            }]
                        }]
                    }]
                },{
                    title: ''
                    ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px;'
                    ,collapsible: false
                    ,region:'center'
                    ,id: 'center'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,margins: '3 3 3 0'
                    ,items: tabs
                    ,tbar:[<?=$this->TOOLBAR;?>]
                }]
            }]
        });
        <?
        if(UserAuth::getUserLoginActionStatus()){
            echo "openEasyWindow('".CHANGE_YOUR_PASSWORD."', '/staff/changepassword/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$guardianId."&refresh=main")."',500,300);";
        }
        ?>
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        if (myTree) myTree.on('click', function(node, e){
            if (node.attributes.isClick) addTab(node.id,node.attributes.title,node.attributes.url);
        });
    });
</script>
<div>
    <div id="initPersonal" class="x-hidden">
        <table>
            <tr>
                <td><b><a id="show-btn" href="#">(<?=$guardianObject->CODE;?>) <?=$guardianObject->FIRSTNAME;?> <?=$guardianObject->LASTNAME;?></b></a></td>
            </tr>
            <tr>
                <td><?=str_replace(',', '<br>', $guardianObject->PHONE);?></td>
            </tr>
            <tr>
                <td><?=str_replace(',', '<br>', $guardianObject->EMAIL);?></td>
            </tr>
        </table>
    </div>
</div>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>