<?
$ldapserver = 'localhost';
$ldapuser = 'cn=manager,dc=camemis,dc=com,dc=kh';
$ldappass = 'camfirst@)!@';
//Search student
//$ldaptree = "ou=student,dc=camemis,dc=com,dc=kh";
//Search teacher
$ldaptree = "dc=camemis,dc=com,dc=kh";

// connect 
$ldapconn = ldap_connect($ldapserver) or die("Could not connect to LDAP server.");

if ($ldapconn) {
    // binding to ldap server
    $ldapbind = ldap_bind($ldapconn, $ldapuser, $ldappass);

    if ($ldapbind) {
        //echo "Yes....good";
    } else {
        echo "".STATUS."" . ldap_error($ldapconn);
    }

    //or die("Hallo world....Error trying to bind: " . ldap_error($ldapconn));
    //
    // verify binding
    if ($ldapbind) {

        $result = ldap_search($ldapconn, $ldaptree, "(cn=*)") or die("Error in search query: " . ldap_error($ldapconn));
        $data = ldap_get_entries($ldapconn, $result);
        /*
          // SHOW ALL DATA
          echo '<h1>Dump all data</h1><pre>';
          print_r($data);
          echo '</pre>';
         */
        // iterate over array and print data for each entry
        echo '<h1>Show users in CAMEMIS</h1>';
        ?>
        <table border="1">
            <tr>
                <td>SN</td>
                <td>CN</td>
                <td>EAMIL</td>
                <td>GIVENAME</td>
                <td>UID</td>
                <td>UIDNUMBER</td>
                <td>HOMEDIRECTORY</td>
                <td>LOGINSHELL</td>
                <td>GROUP</td>
            </tr>
            <?
            for ($i = 0; $i < $data["count"]; $i++) {

                $sn = isset($data[$i]["sn"][0]) ? $data[$i]["sn"][0] : '---';
                $cn = isset($data[$i]["cn"][0]) ? $data[$i]["cn"][0] : '---';
                $eamil = isset($data[$i]["mail"][0]) ? $data[$i]["mail"][0] : '---';
                $givenname = isset($data[$i]["givenname"][0]) ? $data[$i]["givenname"][0] : '---';
                $uid = isset($data[$i]["uid"][0]) ? $data[$i]["uid"][0] : '---';
                $uidnumber = isset($data[$i]["uidnumber"][0]) ? $data[$i]["uidnumber"][0] : '---';
                $homedirectory = isset($data[$i]["homedirectory"][0]) ? $data[$i]["homedirectory"][0] : '---';
                $loginshell = isset($data[$i]["loginshell"][0]) ? $data[$i]["loginshell"][0] : '---';
                $usergroup = isset($data[$i]["dn"]) ? $data[$i]["dn"] : '---';
                ?>
                <tr>
                    <td><?= $sn ?></td>
                    <td><?= $cn ?></td>
                    <td><?= $eamil ?></td>
                    <td><?= $givenname ?></td>
                    <td><?= $uid ?></td>
                    <td><?= $uidnumber ?></td>
                    <td><?= $homedirectory ?></td>
                    <td><?= $loginshell ?></td>
                    <td><?= $usergroup ?></td>
                </tr>
                <?
            }
            ?>
        </table>
        <?
        // print number of entries found
        echo "<p>Number of entries found: " . ldap_count_entries($ldapconn, $result) . "</p>";
    } else {
        echo "LDAP bind failed...";
    }
}

// all done? clean up
ldap_close($ldapconn);
?>