<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////        
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
  
$classObject = AcademicDBAccess::findGradeFromId($this->classId);

if(!$classObject) {header("Location: /main/permission/");}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
//@THORN Visal
$subjectObject = AcademicDBAccess::findGradeFromId($this->classId);
$getGradeSubject = GradeSubjectDBAccess::getGradeSubject(false, $subjectObject->CAMPUS_ID,$subjectObject->SUBJECT_ID,$subjectObject->SCHOOL_YEAR);
?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();  
        
        $PANEL_ITEMS = array(); 
        //@THORN Visal
        $setParamsMaincontent = "";
        /*$setParamsMaincontent .= "target=".camemisId();
        if(Zend_Registry::get('USER')->ID)
        $setParamsMaincontent .= "&teacherId=".Zend_Registry::get('USER')->ID;
        if($classObject->ID)
        $setParamsMaincontent .="&classId=".$classObject->ID;
        if($subjectObject->SUBJECT_ID)
        $setParamsMaincontent .="&subjectId=".$subjectObject->SUBJECT_ID;
        if($getGradeSubject->ID)
        $setParamsMaincontent .="&gradesubjectId=".$getGradeSubject->ID;*/
        if($this->classId){
        $setParamsMaincontent .= "classId=".$this->classId;
        }
        if($this->objectId){
        $setParamsMaincontent .= "&objectId=".$this->objectId;
        }
        
        $MAIN_CONTENT = "{
            title: '".MAIN_CONTENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'MAIN_CONTENT', url: '/staff/creditsystemsubjectdetail/?camIds=".$this->urlEncryp->encryptedGet($setParamsMaincontent)."'})]
        }";
        $PANEL_ITEMS[] = "" . $MAIN_CONTENT . "";
        
        $setParamsAttendance = "";
        if(Zend_Registry::get('USER')->ID)
        $setParamsAttendance .= "objectId=".Zend_Registry::get('USER')->ID;
        if($classObject->ID)
        $setParamsAttendance .="&classId=".$classObject->ID;
        if($this->subjectId)/////@THORN Visal
        $setParamsAttendance .="&subjectId=".$this->subjectId;  
        
        $ATTENDANCE_INFORMATION = "{
            title: '".ATTENDANCE_INFORMATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ATTENDANCE_INFORMATION', url: '/staff/creditsystemstudentattendancesetting/?".$setParamsAttendance."'})]
        }";
        $PANEL_ITEMS[] = "" . $ATTENDANCE_INFORMATION . "";
        
        $setParamsSchedule = "";
        if($classObject->ID)
        $setParamsSchedule .= "academicId=".$classObject->ID;
        if($this->objectId)
        $setParamsSchedule .="&teacherId=".$this->objectId;
        
        $SCHEDULE = "{
            title: '".SCHEDULE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SCHEDULE', url: '/schedule/byclass/?camIds=".$this->urlEncryp->encryptedGet($setParamsSchedule)."'})]
        }";
        $PANEL_ITEMS[] = "" . $SCHEDULE . "";
        
        /////@THORN Visal
        $setParamsEvent = "";
        $setParamsEvent .= "target=general";
        if($classObject->ID)
        $setParamsEvent .= "&classId=".$classObject->ID;
        if($this->subjectId)
        $setParamsEvent .= "&subjectId=".$this->subjectId;
        if(Zend_Registry::get('USER')->ID)
        $setParamsEvent .="&objectId=".Zend_Registry::get('USER')->ID;
        $EVENT = "{
            title: '".EVENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'EVENT', url: '/staff/creditsystemeventsetting/?camIds=".$this->urlEncryp->encryptedGet($setParamsEvent)."'})]
        }";
        $PANEL_ITEMS[] = "" . $EVENT . "";
        /////////////////
        $setParamsHomework = "";
        if($classObject->ID)
        $setParamsHomework .= "classId=".$classObject->ID;
        if($classObject->GRADE_ID)
        $setParamsHomework .="&gradeId=".$classObject->GRADE_ID;
        if($classObject->SCHOOL_YEAR)
        $setParamsHomework .="&schoolyearId=".$classObject->SCHOOL_YEAR;
        if($this->objectId)
        $setParamsHomework .="&objectId=".$this->objectId;
        
        $HOMEWORK = "{
            title: '".HOMEWORK."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'HOMEWORK', url: '/staff/creditsystemhomeworksetting/?camIds=".$this->urlEncryp->encryptedGet($setParamsHomework)."'})]
        }"; 
        
        $PANEL_ITEMS[] = "" . $HOMEWORK . "";
        
        $SUBJECT= "{
            title: '".SUBJECT_LIST."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ALL_SUBJECTS', url: '/subject/byclass/?target=general&classId=".$classObject->ID."&gradeId=".$classObject->GRADE_ID."&schoolyearId=".$classObject->SCHOOL_YEAR."&teacherId=".$this->objectId."'})]
        }";
        
        $setParamsTeachingReport = "";
        if($classObject->ID) 
        $setParamsTeachingReport = "classId=".$classObject->ID;
        if($this->objectId)
        $setParamsTeachingReport .= "&objectId=".$this->objectId;//@THORN Visal
        $TEACHING_REPORT= "{
            title: '".TEACHING_REPORT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'TEACHING_REPORT', url: '/staff/creditsystemsubjectteachingreportsetting/?camIds=".$this->urlEncryp->encryptedGet($setParamsTeachingReport)."'})]
        }";
        $PANEL_ITEMS[] = "" . $TEACHING_REPORT . "";
        //@THORN Visal
        $setParamsAssessment = "";
        $setParamsAssessment .= "target=general";
        if($classObject->ID)
        $setParamsAssessment .= "&classId=".$classObject->ID;
        if($this->subjectId)
        $setParamsAssessment .= "&subjectId=".$this->subjectId;
        if(Zend_Registry::get('USER')->ID)
        $setParamsAssessment .="&objectId=".Zend_Registry::get('USER')->ID;
        $ASSESSMENT = "{
            title: '".ASSESSMENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ASSESSMENT', url: '/staff/creditsystemassessmentsetting/?camIds=".$this->urlEncryp->encryptedGet($setParamsAssessment)."'})]
        }";
        $PANEL_ITEMS[] = "" . $ASSESSMENT . "";
        
        $DISCIPLINE_INFORMATION = "{
            title: '".DISCIPLINE_INFORMATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'DISCIPLINE_INFORMATION', url: '/discipline/byclass/?target=general&classId=".$classObject->ID."'})]
        }";
        $PANEL_ITEMS[] = "" . $DISCIPLINE_INFORMATION . "";
        
        $LIST_OF_STUDENTS = "{
            title: '".LIST_OF_STUDENTS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'LIST_OF_STUDENTS', url: '/staff/creditsystemstudentsetting?classId=".$classObject->ID."'})]
        }";
        $PANEL_ITEMS[] = "" . $LIST_OF_STUDENTS . "";
        
        $CHOOSE_ITEMS = "[".implode(',',$PANEL_ITEMS)."]";  
         
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false 
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false  
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true   
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>