<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
  
$classObject = AcademicDBAccess::findGradeFromId($this->classId);

if(!$classObject) {header("Location: /main/permission/");exit;}
    
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$CREDIT_CLASS = ScheduleDBAccess::getCreditClassInAcademicSubject(array('academicId'=>$classObject->ID,'schoolyearId'=>$classObject->SCHOOL_YEAR,'teacherId'=>$this->objectId));

$DEFAULT_CREDIT_CLASS = ""; 
$DATA_STORE = "[";
if($CREDIT_CLASS){
    $i=0;
    foreach($CREDIT_CLASS as $object){
        
            $icon = "icon-application_form_magnify";
            $DATA_STORE .= $i?",":"";
            $DATA_STORE .= "['" . $object->ID . "', '" . $object->NAME . "', '".$icon."']";
        $i++;
    }
    $DEFAULT_CREDIT_CLASS_ID = $CREDIT_CLASS?$CREDIT_CLASS[0]->ID:0;
}
$DATA_STORE .= "]";

$setParams ="";
if($classObject->SUBJECT_ID)
$setParams .="subjectId=".$classObject->SUBJECT_ID;
if($this->objectId)
$setParams .="&teacherId=".$this->objectId;
if($DEFAULT_CREDIT_CLASS_ID)
$setParams .="&classId=".$DEFAULT_CREDIT_CLASS_ID;

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();  
        
        $SHOW_LAYOUT = "new Ext.ux.IFrameComponent({ id: 'EVENT', url: '/subjectreport/subjectreportlist/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})";
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false 
            ,items:[{
                layout:'card'
                ,id:'content'
                ,activeItem: 0
                ,border: false 
                ,tbar:['->','<?=GRADE_CLASS;?>',{
                    xtype: 'buttongroup'
                    ,items:[{
                        xtype:'combo'
                        ,width:250
                        ,id:'COMO_CREDIT_CLASS_ID'
                        ,fieldLabel:'IconCombo'
                        ,store: new Ext.data.SimpleStore({
                            fields: ['comboCode', 'comboName', 'comboIcon'],
                            data: <?=$DATA_STORE;?>
                        }),
                        plugins:new Ext.ux.plugins.IconCombo()
                        ,valueField: 'comboCode'
                        ,displayField: 'comboName'
                        ,iconClsField: 'comboIcon'
                        ,triggerAction: 'all'
                        ,mode: 'local'
                        ,value:'<?=$DEFAULT_CREDIT_CLASS_ID?>'
                    }]
                }] 
                ,items:<?=$SHOW_LAYOUT?>
            }]
        });
        var comboCreditClass = Ext.getCmp('COMO_CREDIT_CLASS_ID');
        comboCreditClass.on('select', function() {
            clickOpenPage('content','','/subjectreport/subjectreportlist/?camIds=<?=$this->urlEncryp->encryptedGet($setParams);?>&classId='+comboCreditClass.getValue());  
        });
        
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>