<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    ////////////////////////////////////////////////////////////////////////////
    //@Viewport
    ////////////////////////////////////////////////////////////////////////////
    <?
    $STUDENT_PENEL_ITEMS = Array();
    $TRADITIONAL_EDUCATION_SYSTEM = "{  
        columnWidth: 1
        ,baseCls:'x-plain'
        ,bodyStyle:'padding:5px 5px 5px 5px'
        ,items:[{
            title: '".TRADITIONAL_EDUCATION_SYSTEM."'
            ,layout: 'fit'
            ,collapsible: true
            ,collapsed: false
            ,height:350
            ,items: [new Ext.ux.IFrameComponent({ id: 'TRADITIONAL_EDUCATION_SYSTEM', url:'/chart/studentacademictraditional/?camIds=".$this->urlEncryp->encryptedGet("objectType=CAMPUS")."'})]
        }]
    }";

    if (Zend_Registry::get('SCHOOL')->TRADITIONAL_EDUCATION_SYSTEM)
    $STUDENT_PENEL_ITEMS[] = $TRADITIONAL_EDUCATION_SYSTEM;

    $CREDIT_EDUCATION_SYSTEM = "{ 
        columnWidth: 1
        ,baseCls:'x-plain'
        ,bodyStyle:'padding:5px 5px 5px 5px'
        ,items:[{
            title: '".CREDIT_EDUCATION_SYSTEM."'
            ,layout: 'fit'
            ,collapsible: true
            ,collapsed: false
            ,height:350
            ,items: [new Ext.ux.IFrameComponent({ id: 'CREDIT_EDUCATION_SYSTEM', url:'/chart/studentacademiccredit/?camIds=".$this->urlEncryp->encryptedGet("objectType=CAMPUS")."'})]
        }]
    }";

    if (Zend_Registry::get('SCHOOL')->CREDIT_EDUCATION_SYSTEM)
    $STUDENT_PENEL_ITEMS[] = $CREDIT_EDUCATION_SYSTEM;

    $TRAINING_PROGRAMS = "{  
        columnWidth: 1
        ,baseCls:'x-plain'
        ,bodyStyle:'padding:5px 5px 5px 5px'
        ,items:[{
            title: '".TRAINING_PROGRAMS."'
            ,layout: 'fit'
            ,collapsible: true
            ,collapsed: false
            ,height:350
            ,items: [new Ext.ux.IFrameComponent({ id: 'TRAINING_PROGRAMS', url:'/chart/studentacademictraining/?camIds=".$this->urlEncryp->encryptedGet("objectType=PROGRAM")."'})]
        }]
    }";

    if (Zend_Registry::get('SCHOOL')->TRAINING_PROGRAMS)
    $STUDENT_PENEL_ITEMS[] = $TRAINING_PROGRAMS;

    $CHOOSE_PANEL = implode(',',$STUDENT_PENEL_ITEMS);
    ////////////////////////////////////////////////////////////////////////////
    ?>
    Ext.onReady(function() {
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,layout: 'fit'
                ,tbar:[{
                    text:'<?=REFRESH?>'
                    ,iconCls:'icon-arrow_refresh'
                    ,handler: function(){
                        window.location="<?=CamemisPage::setRequestURI()?>";
                    }
                }]
                ,items:[{
                    layout:'column'
                    ,height:percentHeight(100)
                    ,autoScroll:true
                    ,border:false
                    ,defaults: {
                        layout: 'anchor'
                        ,defaults: {anchor: '100%'}
                    }
                    ,items: [<?=$CHOOSE_PANEL;?>]///////////////////be continune
                }]
            }]
        });
    });
</script>
    
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>
