<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("FINANCE", "LIST");

$READ_RIGHT = UserAuth::getACLValue("FINANCIAL_MANAGEMENT_READ_RIGHT")?"true":"false";

$target = isset($_GET["target"])?addText($_GET["target"]):"";

print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        ///
        $RECENT_PAYMENTS_TREE_ITEM=array();
        $GENERAL_EDUCATION = "{
            text:'".HIGHER_EDUCATION."'
            ,iconCls:'icon-folder_magnify'
            ,leaf:false
            ,cls:'nodeTextBold'
            ,isClick:false
            ,expanded:true
            ,children:[{
                text:'".FEES."'
                ,iconCls:'icon-plugin'
                ,leaf:true
                ,url:'".$this->URL_STUDENT_INVOICES_GENERAL."'
                ,cls:'nodeTextBlue'
                ,isClick:".$READ_RIGHT."
            },{
                text:'".STUDENT_SERVICES."'
                ,iconCls:'icon-plugin'
                ,leaf:true
                ,url:'".$this->URL_STUDENT_INVOICES_SERVICES_EDU."'
                ,cls:'nodeTextBlue'
                ,isClick:".$READ_RIGHT."
            }]
        }";
        
        
        $TRAINING_PROGRAMS = "{
            text:'".TRAINING_PROGRAMS."'
            ,iconCls:'icon-folder_magnify'
            ,leaf:false
            ,cls:'nodeTextBold'
            ,isClick:false
            ,expanded:true
            ,children:[{
                text:'".FEES."'
                ,iconCls:'icon-plugin'
                ,leaf:true
                ,url:'".$this->URL_STUDENT_INVOICES_TRAINING."'
                ,cls:'nodeTextBlue'
                ,isClick:".$READ_RIGHT."
            },{
                text:'".STUDENT_SERVICES."'
                ,iconCls:'icon-plugin'
                ,leaf:true
                ,url:'".$this->URL_STUDENT_INVOICES_SERVICES_TRAINING."'
                ,cls:'nodeTextBlue'
                ,isClick:".$READ_RIGHT."
            }]
        }";
        
        if(UserAuth::displayRoleGeneralEducation())
            $RECENT_PAYMENTS_TREE_ITEM[]=$GENERAL_EDUCATION;
        if(UserAuth::displayRoleTrainingEducation())
            $RECENT_PAYMENTS_TREE_ITEM[]=$TRAINING_PROGRAMS;
        $CHOOSE_RECENT_PAYMENTS_TREE_ITEM = implode(",", $RECENT_PAYMENTS_TREE_ITEM);
        ///
        $TREE_ITEM = "";
        $TREE_ITEM .= "[{";
        $TREE_ITEM .= "text:'".RECENT_PAYMENTS."'";
        $TREE_ITEM .= ",iconCls:'icon-folder_magnify'";
        $TREE_ITEM .= ",cls:'nodeTextBold'";
        $TREE_ITEM .= ",expanded:true";
        $TREE_ITEM .= ",isClick:true";
        $TREE_ITEM .= ",url:'".$this->URL_STUDENT_PAYMENTS."'";
        $TREE_ITEM .= ",children:[".$CHOOSE_RECENT_PAYMENTS_TREE_ITEM."]";
        $TREE_ITEM .= "}]";
        
        if($target)
        $OBJECT_TREE->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        ");
        
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        $OBJECT_TREE->isAsyncTreeNode = true;
        $OBJECT_TREE->setAsyncTreeNode($TREE_ITEM);
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    region:'west'
                    ,title:'<?=FINANCIAL_MANAGEMENT?>'
                    ,id: 'WEST_ID'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width: 250
                    ,minSize: 250
                    ,maxSize: 250
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                },{
                    collapsible: false
                    ,title:''
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,items: [new Ext.ux.IFrameComponent({ id: 'URL_FEE', url: '<?=$this->URL_STUDENT_PAYMENTS?>'})]
                }]
            }]
        });
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node, e){
            if(node.attributes.url) clickOpenPage('center','', node.attributes.url);
        });
    });
</script>
<?
print$CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>