<?

$HELP_ACCESS = new AdminHelpDBAccess();

$field = isset($_GET["field"])?addText($_GET["field"]):"";

$HELP_OBJECT = $HELP_ACCESS->findHelp($this->objectId);

$YOUTUBE_KEY_EN = isset($HELP_OBJECT)?$HELP_OBJECT->YOUTUBE_KEY_ENGLISH:"";

if(!$HELP_OBJECT) {header("Location: /main/permission/");exit;}

switch($field){
    case "CONTENT_ENGLISH":
        $content = setShowText($HELP_OBJECT->CONTENT_ENGLISH);
        break;
    case "CONTENT_KHMER":
        $content = $HELP_OBJECT->CONTENT_KHMER;
        break;
    case "CONTENT_VIETNAMESE":
        $content = $HELP_OBJECT->CONTENT_VIETNAMESE;
        break;
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>CAMEMIS</title>
<meta content="text/html; charset=utf-8" http-equiv="content-type" />
<script type="text/javascript" src="/public/ckeditor/ckeditor.js"></script>
<link href="/public/ckeditor/samples/sample.css" rel="stylesheet" type="text/css" />
</head>
<body style='background:#FFF;'>
    <script type="text/javascript">
        var editor;
        CKEDITOR.on( 'instanceReady', function( ev ) {
            editor = ev.editor;
            document.getElementById( 'readOnlyOn' ).style.display = '';
            editor.on( 'readOnly', function() {
                document.getElementById( 'readOnlyOn' ).style.display = this.readOnly ? 'none' : '';
                document.getElementById( 'readOnlyOff' ).style.display = this.readOnly ? '' : 'none';
            });
        });
        function toggleReadOnly( isReadOnly ) {
            editor.setReadOnly( isReadOnly );
        }
    </script>
    <?=html_entity_decode($content);?>
    <?
    $entries = AdminUploadDBAccess::getFilesFromObjectId($this->objectId, false, $field);
    if($entries){
        foreach($entries as $value){
            ?>
            <div style="margin-bottom:10px;"><img src="/public/users/admin/images/<?=$value->FILE_SHOW;?>" width="600" alt="<?=$value->FILE_NAME;?>"></div>
            <?
        }
    }
?>
</body>
</html>