<?
require_once 'clients/app_admin/AdminPage.php';
require_once 'clients/app_admin/AdminForm.php';
require_once 'clients/app_admin/AdminTree.php';
require_once 'clients/app_admin/AdminGrid.php';
require_once 'clients/app_admin/AdminField.php';
require_once 'clients/app_admin/AdminBar.php';
require_once 'clients/app_admin/AdminPage.php';
require_once 'models/app_admin/AdminHelpDBAccess.php';

$CAMEMIS_PAGE = AdminPage::getInstance();
print $CAMEMIS_PAGE->showCamemisHeader();
?>
<script>
    
    Ext.onReady(function() {
        
        <?
        $ENGLISH = "{
            title: 'English'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ENGLISH', url: '/help/showdetail/?objectId=".$this->objectId."&type=1'})]
        }";
        $PENEL_ITEMS[] = $ENGLISH;
        
        $KHMER = "{
            title: 'Khmer'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'KHMER', url: '/help/showdetail/?objectId=".$this->objectId."&type=2'})]
        }";
        $PENEL_ITEMS[] = $KHMER;
        
        $VIETNAMESE = "{
            title: 'Vietnamese'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'VIETNAMESE', url: '/help/showdetail/?objectId=".$this->objectId."&type=3'})]
        }";
        $PENEL_ITEMS[] = $VIETNAMESE;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE->showCamemisFooter();
?>