<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$CATEGORY_OBJECT_TREE = new CamemisTree("DATASET","LIST");
$CATEGORY_OBJECT_TREE ->setURL("/dataset/jsontree/");

$OBJECT_FORM = new CamemisForm("FINANCE");
$OBJECT_FORM->setLoadUrl('/finance/jsonload/');
$OBJECT_FORM->setSaveUrl('/finance/jsonsave/');

$OBJECT_GRID = new CamemisGrid("FINANCE", "SESSION");
$OBJECT_GRID->setLoadUrl("/schedule/jsonload/");   

$entriesParentCheckbox = FinanceDescriptionDBAccess::sqlDescription(false, 1, 2);

$CHECKBOX_JS = "";
$CHECKBOX_DATA = array();
$CHECKBOX_ITEMS = array();
if($entriesParentCheckbox){
    foreach($entriesParentCheckbox as $value){
        if(FinanceDescriptionDBAccess::checkChild($value->ID)){
            $entries = FinanceDescriptionDBAccess::sqlDescription($value->ID, 1, 2);
            $CHECKBOX_JS .= "var CHECKBOX_$value->ID = new Ext.form.CheckboxGroup({";
               $CHECKBOX_JS .= "fieldLabel: '".addslashes($value->NAME)."'";
               $CHECKBOX_JS .= ",columns: 2";
               $CHECKBOX_JS .= ",items:[";
                   $CHECKBOX_DATA = array();
                   foreach($entries as $v){
                       $CHECKBOX_DATA[] = "{boxLabel: '".addslashes($v->NAME)."', name: 'CHECKBOX_".$v->ID."'}";
                   }
                   $CHECKBOX_JS .= implode(',',$CHECKBOX_DATA);
               $CHECKBOX_JS .= "]";
           $CHECKBOX_JS .= "});";

           $CHECKBOX_ITEMS[] = "CHECKBOX_".$value->ID."";   
        }
    }
}

$entriesParentRadiobox = FinanceDescriptionDBAccess::sqlDescription(false, 2, 2);
$RADIOBOX_JS = "";
$RADIOBOX_DATA = array();
$RADIOBOX_ITEMS = array();
if($entriesParentRadiobox){
    foreach($entriesParentRadiobox as $value){
        if(FinanceDescriptionDBAccess::checkChild($value->ID)){
            $entries = FinanceDescriptionDBAccess::sqlDescription($value->ID, 2, 2);
            $RADIOBOX_JS .= "var RADIOBOX_$value->ID = new Ext.form.RadioGroup({";
                $RADIOBOX_JS .= "fieldLabel: '".addslashes($value->NAME)."'";
                $RADIOBOX_JS .= ",columns: 2";
                $RADIOBOX_JS .= ",items:[";
                    $RADIOBOX_DATA = array();
                    foreach($entries as $v){
                        $RADIOBOX_DATA[] = "{boxLabel: '".addslashes($v->NAME)."', name: 'RADIOBOX_".$value->ID."', inputValue: '".$v->ID."'}";
                    }
                    $RADIOBOX_JS .= implode(',',$RADIOBOX_DATA);
                $RADIOBOX_JS .= "]";
            $RADIOBOX_JS .= "});";

            $RADIOBOX_ITEMS[] = "RADIOBOX_".$value->ID."";
        }
    }
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    var startDate;
    var endDate;
    Ext.apply(Ext.form.VTypes, {
        daterange : function(val, field) {
            var date = field.parseDate(val);
            if(!date){
                return false;
            }
            if (field.startDateField) {
                var start = Ext.getCmp(field.startDateField);
                if (!start.maxValue || (date.getTime() != start.maxValue.getTime())) {
                    start.setMaxValue(date);
                    start.validate();
                }
            }
            else if (field.endDateField) {
                var end = Ext.getCmp(field.endDateField);
                if (!end.minValue || (date.getTime() != end.minValue.getTime())) {
                    end.setMinValue(date);
                    end.validate();
                }
            }
            return true;
        }
    });
    
    Ext.onReady(function() {

        Ext.form.Field.prototype.msgTarget = 'side';
        
        function showText(v, p, record, rowIndex){
            return String.format('<div style=\"white-space:normal;font-weight:bold; padding: 20px; height: 25px; background:{1};color:{2};\">{0}</div>'
                ,v
                ,record.data['COLOR']
                ,record.data['COLOR_FONT']
            );
        }
        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        echo $RADIOBOX_JS;
        echo $CHECKBOX_JS;
    
        $CATEGORY_OBJECT_TREE->isAsyncTreeNode = false;
        $CATEGORY_OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $CATEGORY_OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $CATEGORY_OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());

        $CATEGORY_OBJECT_TREE->setBaseParams("
            cmd: 'jsonTreeAllExpenseCategories'
        ");

        $CATEGORY_OBJECT_TREE->backgroundColor = "#F9F9F9";
        $CATEGORY_OBJECT_TREE->isTreeExpand = true;
        $CATEGORY_OBJECT_TREE->renderJS();
        $triggerOnClickCategory = "
            openWinXType('EXPENSE_CATEGORY','".EXPENSE_CATEGORY."', '".$CATEGORY_OBJECT_TREE->getObjectXType()."', 500, percentHeight(85));
            var myTree = Ext.getCmp('".$CATEGORY_OBJECT_TREE->getObjectId()."');
            myTree.on('click', function(node, e){
            Ext.getCmp('CHOOSE_EXPENSE_CATEGORY_NAME_ID').setValue(node.attributes.text);
            Ext.getCmp('CHOOSE_EXPENSE_CATEGORY').setValue(node.attributes.id);
            Ext.getCmp('EXPENSE_CATEGORY').close();
        });
        ";
          
        $FORM_ITEMS = "[
            {".CamemisField::Textfield("PAYMENT_AMOUNT", "PAYMENT_AMOUNT", AMOUNT." (".Zend_Registry::get('SCHOOL')->CURRENCY.")", true, false, false, false, false)."}
            ,{".CamemisField::Trigger("CHOOSE_EXPENSE_CATEGORY_NAME",EXPENSE_CATEGORY,$triggerOnClickCategory,true, false, false)."}
            ,{".CamemisField::Hidden("CHOOSE_EXPENSE_CATEGORY",false)."}
        ]"; 

        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
                ,items: ".$FORM_ITEMS."
            }]
        }
        ";
        
        $DATE_ITEMS = "[{
            name: 'START_DATE'
            ,hidden: false
            ,width: 250
            ,fieldLabel: '" . START_DATE . "'
            ,xtype: 'datefield'
            ,id: 'START_DATE'
            ,vtype: 'daterange'
            ,endDateField: 'END_DATE'
            ,format: '" . setExtDatafieldFormat() . "'
            ,allowBlank: false
            ,value:'".date('Y-m-01')."'
        },{
            name: 'END_DATE'
            ,hidden: false
            ,width: 250
            ,fieldLabel: '" . END_DATE . "'
            ,xtype: 'datefield'
            ,id: 'END_DATE'
            ,vtype: 'daterange'
            ,format: '" . setExtDatafieldFormat() . "'
            ,startDateField: 'START_DATE'
            ,allowBlank: false
            ,value:'".date('Y-m-t')."'
        }]"; 
        
        $TEACHING_SESSION = "
        {
            title: '".DATE."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
                ,items: ".$DATE_ITEMS."
            }]
        }
        ";
        
        $DESCRIPTION = "
        {
            title: '".DESCRIPTION."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,height: 100
            ,items:[{
                layout: 'fit'
                ,border: false
                ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
                ,items: [{".CamemisField::Textarea("DESCRIPTION", false,100)."}]
            }]
        }
        ";

        $DETAIL_CHECKBOX = "
        {
            title: 'Check Box'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
                ,items: [".implode(',',$CHECKBOX_ITEMS)."]
            }]
        }
        ";

        $DETAIL_RADIOBOX = "
        {
            title: 'Radio Box'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF; color:#000;padding:10px'
                ,items: [".implode(',',$RADIOBOX_ITEMS)."]
            }]
        }
        ";

        if($CHECKBOX_ITEMS && $RADIOBOX_ITEMS){
            $SET_ITEMS = "
            [
                ".$DETAIL_RADIOBOX."
                ,".$DETAIL_CHECKBOX."
            ]
            ";
        }elseif(!$CHECKBOX_ITEMS && $RADIOBOX_ITEMS){
            $SET_ITEMS = "
            [
                ".$DETAIL_RADIOBOX."
            ]
            ";
        }elseif($CHECKBOX_ITEMS && !$RADIOBOX_ITEMS){
            $SET_ITEMS = "
            [
                ".$DETAIL_CHECKBOX."
            ]
            ";
        }else{
            $SET_ITEMS = "
            [
            ]
            ";
        }
        
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: [
                ".$DETAIL_INFORMATION."
                ,".$TEACHING_SESSION."
                ,".$SET_ITEMS."
                ,".$DESCRIPTION."
            ]
        ";
        $OBJECT_FORM->addObjectItems($items);

        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            }
        ");
        if(UserAuth::getACLValue("CASH_MANAGEMENT_STAFF_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        if(UserAuth::getACLValue("CASH_MANAGEMENT_STAFF_REMOVE_RIGHT"))
        if ($this->paymentId !="new") $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleRemove());

        $OBJECT_FORM->setLoadParams("cmd: 'jsonLoadStaffPayment',paymentId: '".$this->paymentId."'");
        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonActionStaffPayment'
            ,paymentId: '".$this->paymentId."'
            ,objectId:'".$this->objectId."'
            ,paymentType:'PAYMENT_FOR_SALARY'
        ");

        $OBJECT_FORM->setonEmbeddedEvents("
            if (window.parent.Ext.getCmp('FINANCE_INVOICE_ID')) window.parent.Ext.getCmp('FINANCE_INVOICE_ID').store.reload();
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
            if(window.parent.Ext.getCmp('FINANCE_MANAGEMENT_LIST_ID'))
            window.parent.Ext.getCmp('FINANCE_MANAGEMENT_LIST_ID').store.reload();
            window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->setRemoveParams("
            cmd: 'removeStaffPayment'
            ,paymentId: '".$this->paymentId."'
        ");

        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            if (window.parent.Ext.getCmp('FINANCE_INVOICE_ID')) window.parent.Ext.getCmp('FINANCE_INVOICE_ID').store.reload();
            window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->isObjectDefaultOnLoad = true;
        $OBJECT_FORM->renderJS();

        $OBJECT_GRID->addCellRenderer("
            function cssText(v, p, record, rowIndex){
                var str = '<div style=\"padding:5px;\"><span class=spanText>' + v + '</span></div>';
                return str;
            }
        ");

        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }); 
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>