<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 06.06.2013
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("EXTRACLASS");
$OBJECT_FORM->setSaveUrl('/extraclass/jsonsave/');

$template = isset($_GET["template"]) ? addText($_GET["template"]):"";
$parentId = isset($_GET["parentId"])?addText($_GET["parentId"]):"0";

$OBJECT_TREE = new CamemisTree("SUBJECT", "LIST");
$OBJECT_TREE->setURL('/subject/jsontree/');
$OBJECT_TREE->setSaveUrl('/subject/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
<? camemisPage::ExtformVTypes(); ?>

Ext.onReady(function() {
    <?
    /**
     * Extjs: s.gif
     */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    
    $OBJECT_TREE->setBaseParams("
        cmd: 'treeAllSubjects'
    ");
    
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->isTreeExpand = false;
    $OBJECT_TREE->isOnClickContextMenu = false;
    $OBJECT_TREE->renderJS();
    
    $triggerOnClickSubject = "
        openWinXType('SUBJECT','".SUBJECT."', '".$OBJECT_TREE->getObjectXType()."', percentWidth(45), percentHeight(90));
        var academicTree = Ext.getCmp('".$OBJECT_TREE->getObjectId()."');
        academicTree.on('click', function(node, e){
            if(node.isLeaf()){
                Ext.getCmp('NAME_ID').setValue(node.text);
                Ext.getCmp('SUBJECT_ID').setValue(node.attributes.id);
                Ext.getCmp('SUBJECT').close(); 
            }        
        });
    ";
    
    $PROGRAMM_ITEMS = "
    [
        {".CamemisField::Textfield("NAME","NAME",NAME, true)."}
    ]
    ";
    
    $TERM_ITEMS = "
    [
        {".CamemisField::StartDatefieldRange("START_DATE", START_DATE, "END_DATE", true)."}
        ,{".CamemisField::EndDatefieldRange("END_DATE", END_DATE, "START_DATE", true)."}
    ]
    ";
    
    $LEVEL_ITEMS = "
    [
        {".CamemisField::Textfield("NAME","NAME",NAME)."}
        ,{".CamemisField::Numberfield("GRADE_LEVEL", "GRADE_LEVEL", LEVEL, true, false)."}
    ]
    ";
    
    $CLASS_ITEMS = "
    [
        {".CamemisField::Trigger2("NAME",NAME,$triggerOnClickSubject, false, 230)."}
    ]
    ";
    
    //Hidden Field subject id
    $OBJECT_FORM->addObjectItems(CamemisField::Hidden("SUBJECT_ID",false));
    
    $OBJECT_FORM->setLoadParams("
        cmd: 'jsonLoadObject'
        ,objectId: '".$this->objectId."'
    ");
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'jsonSaveObject'
        ,objectId: '".$this->objectId."'
        ,parent: '".$parentId."'
        ,objctType:'".$template."'
    ");
    
    switch($template){
        case "PROGRAM":
            $DETAIL_ITEMS = $PROGRAMM_ITEMS;
            break;
        case "LEVEL":
            $DETAIL_ITEMS = $LEVEL_ITEMS;
            break;
        case "TERM":
            $DETAIL_ITEMS = $TERM_ITEMS;
            break;
        case "CLASS":
            $DETAIL_ITEMS = $CLASS_ITEMS;
            break;
        default:
            $DETAIL_ITEMS = $PROGRAMM_ITEMS;
            break;
    }
    
    $DETAIL_INFORMATION = "
    {
        title: '".DETAIL_INFORMATION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: ".$DETAIL_ITEMS."
        }]
    }
    ";
    
    $ITEMS = $DETAIL_INFORMATION;
    
    $items = "
        border: false
        ,id: 'FORM_ITEMS'
        ,autoScroll: true
        ,bodyStyle: 'padding:0px'
        ,items: [".$ITEMS."]
    ";
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
    ");
    
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    
    $OBJECT_FORM->setonEmbeddedEvents("
       XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        myTree = window.parent.Ext.getCmp('EXTRACLASS_TREE_ID');
        myNode = myTree.getNodeById('".$parentId."');
        if(myNode.parentNode==null){
            myTree.root.reload();
        }else{
            myNode.reload();
            myNode.expand(true, false);
        }

        var result = Ext.util.JSON.decode(action.response.responseText);
        window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
    ");
    
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>
