<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 17.02.2012
// @Sothearung....
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$DEPARTMENT_TREE = new CamemisTree("DEPARTMENT", "LIST");
$DEPARTMENT_TREE->setURL("/department/jsontree/");

$ORGANIZATION_CHART_TREE = new CamemisTree("ORGANIZATION_CHART", "LIST");
$ORGANIZATION_CHART_TREE->setURL("/organization/jsontree/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

    Ext.onReady(function() {
        <?
        $DEPARTMENT_TREE->isAsyncTreeNode = false;
        $DEPARTMENT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));
        $DEPARTMENT_TREE->setBaseParams("
            cmd: 'jsonTreeAllDepartments'
            ,userId: '".$this->objectId."'
        ");
        $DEPARTMENT_TREE->backgroundColor = "#F9F9F9";
        $DEPARTMENT_TREE->renderJS();
    
        ///////////////////////////////////////////////////
        //
        $ORGANIZATION_CHART_TREE->backgroundColor = "#F9F9F9";
        $ORGANIZATION_CHART_TREE->isAsyncTreeNode = false;
        $ORGANIZATION_CHART_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));
        $ORGANIZATION_CHART_TREE->setBaseParams("
            cmd: 'jsonTreeAllOrganizations'
            ,userId: '".$this->objectId."'
        ");
        $ORGANIZATION_CHART_TREE->renderJS();
        ///////////////////////////////////////////////////
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                xtype: 'tabpanel'
                ,border:false
                ,tabPosition: 'top'
                ,activeTab: 0
                ,items:[{
                    title: '<?=FACULTY_OR_DEPARTMENT?>'
                    ,layout:'fit'
                    ,items:[{xtype: '<?=$DEPARTMENT_TREE->getObjectXtype();?>'}]
                },{
                    title: '<?=ORGANIZATION_CHART?>'
                    ,layout:'fit'
                    ,items:[{xtype: '<?=$ORGANIZATION_CHART_TREE->getObjectXtype();?>'}]
                }]
            }]
        });
        <?
        $js = "";
        $js .= "var departmentTree = Ext.getCmp('".$DEPARTMENT_TREE->getObjectId()."');";
        $js .= "departmentTree.on('checkchange', function(node, checked){";
            $js .= "Ext.Ajax.request({";
                $js .= "url:'/staff/jsonsave/'";
                $js .= ",method:'POST'";
                $js .= ",params:{";
                    $js .= "cmd:'actionStaffDepartment'";
                    $js .= ",checked:checked";
                    $js .= ",Id:node.id";
                    $js .= ",setId:'".$this->objectId."'";
                $js .= "}";
                $js .= ",success:function(response, options) {";
                    $js .= "result = Ext.util.JSON.decode(response.responseText);";
                    $js .= "XMsg('".STATUS."',result.msg);";
                $js .= "}";
            $js .= "});";
        $js .= "});";
        ///////////////////////////////////////////////////
        //Organization...
        ///////////////////////////////////////////////////
        $js .= "var organizationTree = Ext.getCmp('".$ORGANIZATION_CHART_TREE->getObjectId()."');";
        $js .= "organizationTree.on('checkchange', function(node, checked){";
            $js .= "Ext.Ajax.request({";
                $js .= "url:'/organization/jsonsave/'";
                $js .= ",method:'POST'";
                $js .= ",params:{";
                    $js .= "cmd:'actionUserOrganization'";
                    $js .= ",checked:checked";
                    $js .= ",Id:node.id";
                    $js .= ",setId:'".$this->objectId."'";
                $js .= "}";
                $js .= ",success:function(response, options) {";
                    $js .= "result = Ext.util.JSON.decode(response.responseText);";
                    $js .= "XMsg('".STATUS."',result.msg);";
                $js .= "}";
            $js .= "});";
        $js .= "});";
        echo $js;
        ?>  
    });
</script>

<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>