<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 20.20.2012
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'clients/CamemisViewport.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("STAFF", "LIST");
$OBJECT_TREE->setURL('/staff/jsontree/');

$target = isset($_GET["target"])?addText($_GET["target"]):"";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
var roleId;
Ext.onReady(function() {

    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $PERSON_ITEMS = "";
    $PERSON_ITEMS .= "[{";
        $PERSON_ITEMS .= "text: '".PERSONAL_INFORMATION."'";
        $PERSON_ITEMS .= ",iconCls: 'icon-folder_magnify'";
        $PERSON_ITEMS .= ",cls:'nodeTextBold'";
        $PERSON_ITEMS .= ",isClick:true";
        $PERSON_ITEMS .= ",url:'/staff/staff/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&template=DETAIL")."'";
        $PERSON_ITEMS .= ",expanded: true";
        $PERSON_ITEMS .= ",children: [";
        
        $PERSON_ITEMS .= "{";
            $PERSON_ITEMS .= "text:'".ADDITIONAL_INFORMATION."'";
            $PERSON_ITEMS .= ",iconCls: 'icon-component'";
            $PERSON_ITEMS .= ",leaf: true";
            $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
            $PERSON_ITEMS .= ",url:'/staff/description/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&isCancel=true")."'";
            $PERSON_ITEMS .= ",isClick:true";
        $PERSON_ITEMS .= "}";
        
        $PERSON_ITEMS .= ",{";
            $PERSON_ITEMS .= "text: '".WORK_EXPERIENCE."'";
            $PERSON_ITEMS .= ",cls:'nodeTextBold'";
            $PERSON_ITEMS .= ",iconCls: 'icon-folder_magnify'";
            $PERSON_ITEMS .= ",leaf: false";
            $PERSON_ITEMS .= ",expanded: true";
            $PERSON_ITEMS .= ",url:'/staff/personinfos/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&target=WORK_EXPERIENCE&isCancel=true")."'";
            $PERSON_ITEMS .= ",isClick:true";
            $PERSON_ITEMS .= ",children: [";
                $PERSON_ITEMS .= "{";
                    $PERSON_ITEMS .= "text: '".DETAIL_INFORMATION."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",url:'/dataset/ckeditor/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&field=WORK_EXPERIENCE&object=staff&isCancel=true")."'";
                    $PERSON_ITEMS .= ",isClick:true";
                $PERSON_ITEMS .= "}";
                $PERSON_ITEMS .= ",{";
                    $PERSON_ITEMS .= "text: '".ATTACHMENT."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",url:'/dataset/attachment/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&template=WORK_EXPERIENCE&isCancel=true")."'";
                    $PERSON_ITEMS .= ",isClick:true";
                $PERSON_ITEMS .= "}";
            $PERSON_ITEMS .= "]";
        $PERSON_ITEMS .= "}";
        
        $PERSON_ITEMS .= ",{";
            $PERSON_ITEMS .= "text: '".SKILL."'";
            $PERSON_ITEMS .= ",cls:'nodeTextBold'";
            $PERSON_ITEMS .= ",iconCls: 'icon-folder_magnify'";
            $PERSON_ITEMS .= ",leaf: false";
            $PERSON_ITEMS .= ",isClick:true";
            $PERSON_ITEMS .= ",url:'/staff/personinfos/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&target=PROFESSION&isCancel=true")."'";
            $PERSON_ITEMS .= ",expanded: true";
            $PERSON_ITEMS .= ",children: [";
                $PERSON_ITEMS .= "{";
                    $PERSON_ITEMS .= "text: '".DETAIL_INFORMATION."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",isClick:true";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",url:'/dataset/ckeditor/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&field=PROFESSION&object=staff&isCancel=true")."'";
                $PERSON_ITEMS .= "}";
                $PERSON_ITEMS .= ",{";
                    $PERSON_ITEMS .= "text: '".ATTACHMENT."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",url:'/dataset/attachment/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&template=PROFESSION&isCancel=true")."'";
                    $PERSON_ITEMS .= ",isClick:true";
                $PERSON_ITEMS .= "}";
            $PERSON_ITEMS .= "]";
        $PERSON_ITEMS .= "}";
        
        //RELATIVE_INFORMATION
        ////////////////////////////////////////////////////////////////////////////
        $PERSON_ITEMS .= ",{";
            $PERSON_ITEMS .= "text: '".RELATIVE_INFORMATION."'";
            $PERSON_ITEMS .= ",cls:'nodeTextBold'";
            $PERSON_ITEMS .= ",iconCls: 'icon-folder_magnify'";
            $PERSON_ITEMS .= ",leaf: false";
            $PERSON_ITEMS .= ",expanded: true";
            $PERSON_ITEMS .= ",url:'/staff/personinfos/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&target=EMERCP&isCancel=true")."'";
            $PERSON_ITEMS .= ",isClick:true";
            $PERSON_ITEMS .= ",children: [";
                $PERSON_ITEMS .= "{";
                    $PERSON_ITEMS .= "text: '".DETAIL_INFORMATION."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component_yellow'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",url:'/dataset/ckeditor/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&field=RELATIVE_INFO&object=staff&isCancel=true")."'";
                    $PERSON_ITEMS .= ",isClick:true";
                $PERSON_ITEMS .= "}";
                $PERSON_ITEMS .= ",{";
                    $PERSON_ITEMS .= "text: '".ATTACHMENT."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component_yellow'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",url:'/dataset/attachment/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&template=EMERCP&isCancel=true")."'";
                    $PERSON_ITEMS .= ",isClick:true";
                $PERSON_ITEMS .= "}";
            $PERSON_ITEMS .= "]";
        $PERSON_ITEMS .= "}";
        
        //EDUCATION BACKGROUND
        ////////////////////////////////////////////////////////////////////////////
        $PERSON_ITEMS .= ",{";
            $PERSON_ITEMS .= "text: '".EDUCATION_BACKGROUND."'";
            $PERSON_ITEMS .= ",cls:'nodeTextBold'";
            $PERSON_ITEMS .= ",iconCls: 'icon-folder_magnify'";
            $PERSON_ITEMS .= ",leaf: false";
            $PERSON_ITEMS .= ",expanded: true";
            $PERSON_ITEMS .= ",url:'/staff/personinfos/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&target=EDUBACK&isCancel=true")."'";
            $PERSON_ITEMS .= ",isClick:true";
            $PERSON_ITEMS .= ",children: [";
                $PERSON_ITEMS .= "{";
                    $PERSON_ITEMS .= "text: '".DETAIL_INFORMATION."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component_yellow'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",url:'/dataset/ckeditor/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&field=BACKGROUND_INFO&object=staff&isCancel=true")."'";
                    $PERSON_ITEMS .= ",isClick:true";
                $PERSON_ITEMS .= "}";
                $PERSON_ITEMS .= ",{";
                    $PERSON_ITEMS .= "text: '".ATTACHMENT."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component_yellow'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",url:'/dataset/attachment/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&template=EDUBACK&isCancel=true")."'";
                    $PERSON_ITEMS .= ",isClick:true";
                $PERSON_ITEMS .= "}";
            $PERSON_ITEMS .= "]";
        $PERSON_ITEMS .= "}";
        
        //PUBLICATION
        ////////////////////////////////////////////////////////////////////////////
        $PERSON_ITEMS .= ",{";
            $PERSON_ITEMS .= "text: '".PUBLICATION."'";
            $PERSON_ITEMS .= ",cls:'nodeTextBold'";
            $PERSON_ITEMS .= ",iconCls: 'icon-folder_magnify'";
            $PERSON_ITEMS .= ",leaf: false";
            $PERSON_ITEMS .= ",expanded: true";
            $PERSON_ITEMS .= ",url:'/staff/personinfos/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&target=PUBLICATION&isCancel=true")."'";
            $PERSON_ITEMS .= ",isClick:true";
            $PERSON_ITEMS .= ",children: [";
                $PERSON_ITEMS .= "{";
                    $PERSON_ITEMS .= "text: '".DETAIL_INFORMATION."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component_yellow'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",url:'/dataset/ckeditor/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&field=PUBLICATION&object=staff&isCancel=true")."'";
                    $PERSON_ITEMS .= ",isClick:true";
                $PERSON_ITEMS .= "}";
                $PERSON_ITEMS .= ",{";
                    $PERSON_ITEMS .= "text: '".ATTACHMENT."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component_yellow'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",url:'/dataset/attachment/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&template=PUBLICATION&isCancel=true")."'";
                    $PERSON_ITEMS .= ",isClick:true";
                $PERSON_ITEMS .= "}";
            $PERSON_ITEMS .= "]";
        $PERSON_ITEMS .= "}";
        
        $PERSON_ITEMS .= ",{";
            $PERSON_ITEMS .= "text: '".STAFF_CONTRACT."'";
            $PERSON_ITEMS .= ",cls:'nodeTextBold'";
            $PERSON_ITEMS .= ",iconCls: 'icon-folder_magnify'";
            $PERSON_ITEMS .= ",leaf: false";
            $PERSON_ITEMS .= ",expanded: true";
            $PERSON_ITEMS .= ",url:'/staffcontract/staffcontractmain/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId)."'";
            $PERSON_ITEMS .= ",isClick:true";
            $PERSON_ITEMS .= ",children: [";
                $PERSON_ITEMS .= "{";
                    $PERSON_ITEMS .= "text: '".DETAIL_INFORMATION."'";
                    $PERSON_ITEMS .= ",iconCls: 'icon-component'";
                    $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",url:'/dataset/ckeditor/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&field=CONTRACT_INFO&object=staff&isCancel=true")."'";
                    $PERSON_ITEMS .= ",isClick:true";
                $PERSON_ITEMS .= "}";
            $PERSON_ITEMS .= "]";
        $PERSON_ITEMS .= "}";
        
        $PERSON_ITEMS .= "]";
        switch(UserAuth::getUserType()){
            case "SUPERADMIN":
            case "ADMIN":
                $PERSON_ITEMS .= "},{";
                    $PERSON_ITEMS .= "text:'".SCHOOL_INFORMATION."'";
                    $PERSON_ITEMS .= ",iconCls:'icon-folder_magnify'";
                    $PERSON_ITEMS .= ",cls:'nodeTextBold'";
                    $PERSON_ITEMS .= ",expanded:true";
                    $PERSON_ITEMS .= ",isClick:false";
                    $PERSON_ITEMS .= ",children:[";

                    $PERSON_ITEMS .= "{";
                        $PERSON_ITEMS .= "text:'".ADMINISTRATION."'";
                        $PERSON_ITEMS .= ",iconCls:'icon-component_red'";
                        $PERSON_ITEMS .= ",leaf:true";
                        $PERSON_ITEMS .= ",url:'/staff/administration/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."")."'";
                        $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                        $PERSON_ITEMS .= ",isClick:true";
                    $PERSON_ITEMS .= "}";

                    $PERSON_ITEMS .= ",{";
                        $PERSON_ITEMS .= "text:'".TEACHING_SESSION."'";
                        $PERSON_ITEMS .= ",iconCls:'icon-component_red'";
                        $PERSON_ITEMS .= ",leaf: true";
                        $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                        $PERSON_ITEMS .= ",url:'/staff/staffsession/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."")."'";
                        $PERSON_ITEMS .= ",isClick:true";
                    $PERSON_ITEMS .= "}";

                    $PERSON_ITEMS .= ",{";
                        $PERSON_ITEMS .= "text:'".SUBJECT."'";
                        $PERSON_ITEMS .= ",iconCls: 'icon-component_red'";
                        $PERSON_ITEMS .= ",leaf: true";
                        $PERSON_ITEMS .= ",cls:'nodeTextBlue'";
                        $PERSON_ITEMS .= ",url:'/staff/teachersubject/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."")."'";
                        $PERSON_ITEMS .= ",isClick:true";
                    $PERSON_ITEMS .= "}";

                    $PERSON_ITEMS .= "]";
                $PERSON_ITEMS .= "}";

                $PERSON_ITEMS .= ",{";
                    $PERSON_ITEMS .= "text:'".STATUS."'";
                    $PERSON_ITEMS .= ",iconCls:'icon-component_red'";
                    $PERSON_ITEMS .= ",cls:'nodeTextBold'";
                    $PERSON_ITEMS .= ",leaf: true";
                    $PERSON_ITEMS .= ",url:'/staff/statusbystaff/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&target=general")."'";
                    $PERSON_ITEMS .= ",isClick:true";
        break;
    }
    $PERSON_ITEMS .= "}";
    $PERSON_ITEMS .="]";
    
    if($target)
    $OBJECT_TREE->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            Ext.Ajax.request({
                url:'/staff/jsonload/'
                ,method: 'POST'
                ,params: {cmd: 'jsonLoadLastStaffStatus',objectId:'".$this->objectId."'}
                ,success: function(response, options) {
                    var jsonData = Ext.util.JSON.decode(response.responseText);
                    if(window.parent.Ext.getCmp('STAFF_LIST_ID')){
                        var sm = window.parent.Ext.getCmp('STAFF_LIST_ID').getSelectionModel();
                        var record = sm.getSelected();
                        record.set('STATUS_KEY',jsonData.data.SHORT);
                        record.set('BG_COLOR',jsonData.data.COLOR);
                        record.set('BG_COLOR_FONT',jsonData.data.COLOR_FONT);
                        record.commit();
                    }
                    window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                }
                ,failure: function(response, options) {}
            });
        }
    ");
    
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    //@CHHE Vathana
    $OBJECT_TREE->addTBarItems("
        text: '" . EXPORT_TO_EXCEL . "'
        ,id: 'EXPORT_TO_EXCEL'
        ,iconCls:'icon-page_excel'
        ,handler: function(){
            Ext.MessageBox.show({
                msg: '".SAVING_YOUR_DATA_PLEASE_WAIT."',
                progressText: 'Saving...',
                width:300,
                wait:true,
                waitConfig: {interval:200},
                icon:'ext-mb-download'
            });
            Ext.Ajax.request({
                url: '/export/jsonexcel/'
                ,method: 'POST'
                ,params:{
                    cmd: 'staffpersonalinfo' 
                    ,objectId:'".$this->objectId."'
                }
                ,success: function(response, options) {
                    Ext.MessageBox.hide();
                    window.location='/export/openstaffpersonalinfolist/'
                }
            });
        }
    ");
    //End
    $OBJECT_TREE->isAsyncTreeNode = true;
    $OBJECT_TREE->setAsyncTreeNode($PERSON_ITEMS);
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{
               	region:'west'
                ,bodyStyle: 'background:#EEE'
                ,title:'<?=STAFF?>'
                ,id: 'WEST_ID'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width:260
                ,minSize:260
                ,maxSize:260
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [new Ext.ux.IFrameComponent({ id: 'OPEN_IFRAME', url: '/staff/staff/?camIds=<?=$this->urlEncryp->encryptedGet("objectId=$this->objectId&template=DETAIL");?>'})]
            }]
        }]
    });
    var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('click', function(node, e){
        if(node.attributes.isClick) clickOpenPage('center',node.text, node.attributes.url);
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>