<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////

require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("STAFF");
$OBJECT_FORM->setLoadUrl('/staff/jsonload/');
$OBJECT_FORM->setSaveUrl('/staff/jsonsave/');

$TRAINING_TREE = new CamemisTree("TRAINING","LIST");
$TRAINING_TREE->setURL('/training/jsontree/');
$TRAINING_TREE->setSaveUrl('/training/jsonsave/');

$objectId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";
$statusId = isset($_GET["statusId"])?$_GET["statusId"]:"";
$target = isset($_GET["target"])?addText($_GET["target"]):"";
$facette = $this->facette;

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<style>
    body{
        font:normal 12px Tahoma, Arial, sans-serif,Hanuman;
    }
    </style>
    
    <div id="content" class="x-hide-display">
        <div style="border:0px silver solid;margin:10px;padding:10px;">
                <span style="font-weight:bold;font-size:14px; color:#333;"><?=isset($facette)?showNewlineText($facette->SHORT):"---"?></span>
            </div>
            
            <div style="border:0px silver solid;margin:10px;padding:10px;">
            <span style="font-size:12px; color:#333;">
                <?=isset($facette)?$facette->DESCRIPTION:"---"?>
            </span>
            <br/>
        </div>
    </div>
<script>

     viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,tbar:[{
                    text: '<?=CANCEL?>'
                    ,id: 'CANCEL_ID'
                    ,formBind:true
                    ,iconCls:'icon-cancel'
                    ,scope:this
                    ,handler: function(){
                        window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                    }
                }]
                ,id: 'DESCRIPTION'
                ,xtype: 'panel'
                ,layout: 'card'
                ,enableTabScroll:true
                ,activeItem: 0
                ,items:[{
                    layout:'border'
                    ,border: false
                    ,defaults: {
                        collapsible: false
                        ,split: true
                    }
                    ,items: [{
                        collapsible: false
                        ,id: 'center'
                        ,region:'center'
                        ,margins: '3 0 3 3'
                        ,layout: 'fit'
                        ,bodyStyle: 'padding:10px'
                        ,autoScroll: true
                        ,contentEl:'content'
                    }]
                }]
            }]
        });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>