<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTree("ASSIGNMENT", "ASSIGNMENT");
$OBJECT_TREE->setURL("/assignment/jsontree/");
$OBJECT_TREE->setSaveUrl("/assignment/jsonsave/");

$target = isset($_GET["target"])?addText($_GET["target"]):"GENERAL";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
$EDIT_RIGHT=UserAuth::getACLValue("ACADEMIC_SETTING_EDIT_RIGHT")?"false":"true";

?>
<script>
    
var educationType;
Ext.onReady(function() {
	
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    
    $OBJECT_TREE->setSaveParams("
    	cmd: 'addObject'
        ,educationType: educationType
    ");
    
    $OBJECT_TREE->setBaseParams("
    	cmd: 'jsonTreeAllAssignmentTemp'
        ,target:'".$target."'
    ");
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->isTreeExpand = false;
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{
               	region:'west'
                ,title: '<?=ASSIGNMENT?>'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width:350
                ,minSize:350
                ,maxSize:350
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    border: false
                    ,layout: 'anchor'
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items: [{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                    }]
                }]
            }]
        }]
    });
    
    var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('click', function(node,event){

        if(node.attributes.add){
            addDisabled = false;
        }else{
            addDisabled = true;
        }
        
        if(node.attributes.show){
            showDisabled = false;
        }else{
            showDisabled = true;
        }
        
        var contextMenu = new Ext.menu.Menu({
            items: [{
                text: '<?=ADD_ENTRY?> &raquo; ' + node.text
                ,iconCls: 'icon-application_form_add'
                ,disabled:addDisabled
                ,handler: function(){
                    clickOpenPage('center',node.text, '<?=$this->URL_SHOW_ASSIGNMENT_TEMP?>objectId=new&educationType=' + node.attributes.parentId);
                }
            },{
                text: '<?=SHOW_DETAIL?> &raquo; ' + node.text
                ,iconCls: 'icon-application_form_magnify'
                ,hidden:showDisabled                
                ,handler: function(){
                    clickOpenPage('center','', '<?=$this->URL_SHOW_ASSIGNMENT_TEMP;?>objectId=' + node.id);
                }
            }]
        });
        event.stopEvent();
        contextMenu.showAt(event.xy); 
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>