<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $ENROLLMENT_EXAMINATION = "{
            title: '".ENROLLMENT_EXAMINATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ENROLLMENT_EXAMINATION', url: '/examination/listexaminations/?parentId=6'})]
        }";
        $PENEL_ITEMS[] = $ENROLLMENT_EXAMINATION;
        
        $SEMESTER_TEST = "{
            title: '".SEMESTER_TEST."'
            ,layout: 'fit'
            ,disabled:true
            ,items:[new Ext.ux.IFrameComponent({ id: 'SEMESTER_TEST', url: '/examination/listexaminations/?parentId=1'})]
        }";
        $PENEL_ITEMS[] = $SEMESTER_TEST;
        
        $LEARNING_QUALITY = "{
            title: '".LEARNING_QUALITY."'
            ,layout: 'fit'
            ,disabled:false
            ,items:[new Ext.ux.IFrameComponent({ id: 'LEARNING_QUALITY', url: '/examination/listexaminations/?parentId=4'})]
        }";
        $PENEL_ITEMS[] = $LEARNING_QUALITY;
        
        $OLYMPIA_TEST = "{
            title: '".OLYMPIA_TEST."'
            ,layout: 'fit'
            ,disabled:false
            ,items:[new Ext.ux.IFrameComponent({ id: 'OLYMPIA_TEST', url: '/examination/listexaminations/?parentId=3'})]
        }";
        $PENEL_ITEMS[] = $OLYMPIA_TEST;
        
        $STATE_EXAM = "{
            title: '".STATE_EXAM."'
            ,layout: 'fit'
            ,disabled:true
            ,items:[new Ext.ux.IFrameComponent({ id: 'STATE_EXAM', url: '/examination/listexaminations/?parentId=5'})]
        }";
        $PENEL_ITEMS[] = $STATE_EXAM;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>