<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $FINANCIAL_MANAGEMENT = "{
            title: '".FINANCIAL_MANAGEMENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'FINANCIAL_MANAGEMENT', url: '/finance/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $FINANCIAL_MANAGEMENT;
        
        $CASH_MANAGEMENT_STUDENT = "{
            title: '".CASH_MANAGEMENT_STUDENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'FINANCIAL_MANAGEMENT', url: '/finance/studentmain/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $CASH_MANAGEMENT_STUDENT;
        
        $CASH_MANAGEMENT_STAFF = "{
            title: '".CASH_MANAGEMENT_STAFF."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'CASH_MANAGEMENT_STAFF', url: '/finance/staffmain/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $CASH_MANAGEMENT_STAFF;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>