<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $SCHOOL_YEAR = "{
            title: '".SCHOOL_YEAR."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SCHOOL_YEAR', url: '/academicdate/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $SCHOOL_YEAR;
        
        $SUBJECT = "{
            title: '".SUBJECT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SUBJECT', url: '/subject/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $SUBJECT;
        
        $ASSIGNMENT = "{
            title: '".ASSIGNMENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ASSIGNMENT', url: '/academicsetting/allassignments/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $ASSIGNMENT;
        
        $GRADING_SCALES = "{
            title: '".GRADING_SCALES."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'GRADING_SCALES', url: '/academicsetting/gradingsystem/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $GRADING_SCALES;
        
        $ATTENDANCE_TYPE = "{
            title: '".ATTENDANCE_TYPE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ATTENDANCE_TYPE', url: '/dataset/allabsenttypes/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $ATTENDANCE_TYPE;
        
        $PERSON_STATUS = "{
            title: '".PERSON_STATUS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'PERSON_STATUS', url: '/dataset/allpersonstatus/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $PERSON_STATUS;
        
        $SCHOLARSHIP = "{
            title: '".SCHOLARSHIP."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SCHOLARSHIP', url: '/dataset/allscholarshiptype/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $SCHOLARSHIP;
        
        $ADDITIONAL_INFORMATION = "{
            title: '".ADDITIONAL_INFORMATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ACADEMIC_ADDITIONAL', url: '/academicsetting/additionalinformation/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $ADDITIONAL_INFORMATION;
        
        $CAMEMIS_TYPE = "{
            title: '".CAMEMIS_TYPE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ADVISORY_TYPE', url: '/dataset/camemistype/?key=".camemisId()."'})]
        }";
        $PENEL_ITEMS[] = $CAMEMIS_TYPE;
        //
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>