<?
///////////////////////////////////////////////////////////
//@Chung veng 
//Date: 16.12.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $ATTENDANCE_REPORTING = "{
            title: 'Discipline Report'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'DISCIPLINE_REPORTING', url: '/discipline/?key=".camemisId()."&target=general'})]
        }";
        $PENEL_ITEMS[] = $ATTENDANCE_REPORTING;
        
        $STUDENT_ATTENDANCE = "{
            title: 'Student Discipline'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'STUDENT_DISCIPLINE', url: '/discipline/studentdisciplines/?key=".camemisId()."&target=general'})]
        }";
        
        $PENEL_ITEMS[] = $STUDENT_ATTENDANCE;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>