<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $ATTENDANCE_REPORTING = "{
            title: '".ATTENDANCE_REPORTING."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ATTENDANCE_REPORTING', url: '/attendance/studentsearchmain/?key=".camemisId()."&target=training'})]
        }";
        $PENEL_ITEMS[] = $ATTENDANCE_REPORTING;
        
        $STUDENT_ATTENDANCE = "{
            title: '".STUDENT_ATTENDANCE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'STUDENT_ATTENDANCE', url: '/attendance/studentclassadmin/?key=".camemisId()."&target=training'})]
        }";
        
        $PENEL_ITEMS[] = $STUDENT_ATTENDANCE;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'bottom'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>