<?
///////////////////////////////////////////////////////////
// @Math Man Web Application Developer
// Date: 04.03.2014
///////////////////////////////////////////////////////////
require_once 'models/statistic/LetterStatisticsDBAccess.php';

$objectType = isset($_GET["objectType"]) ? addText($_GET["objectType"]) : "";
$objectId = isset($_GET["objectId"]) ? addText($_GET["objectId"]) : "";

$dataSet = "";
switch($objectType){
    case "WEEKLY":
        $dataSet = LetterStatisticsDBAccess::getDataSetLetterDashboard("WEEKLY");
    break;
    case "MONTHLY":
        $dataSet = LetterStatisticsDBAccess::getDataSetLetterDashboard("MONTHLY");
    break;
    case "YEARLY":
        $dataSet = LetterStatisticsDBAccess::getDataSetLetterDashboard("YEARLY");
    break;
}

?>
<!DOCTYPE html>
<meta charset="utf-8">

<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">

<style>
    body {
        overflow-y:scroll;
    }

    text {
        font: 11px tahoma,verdana,arial,sans-serif,Hanuman;
    }

    #chart1 {
        height:230px; 
        margin: 10px;
        min-width: 100px;
        min-height: 100px;
    }
</style>
<body>
<div id="chart1"><svg></svg></div>
<script src="/public/nvd3/nvd3-camemis.php"></script>
<script>
var chart;
nv.addGraph(function() {
    chart = nv.models.multiBarChart()
    .showLegend(false)
    .barColor(d3.scale.category20().range())
    .margin({bottom: 50})
    .transitionDuration(300)
    .delay(0)
    .rotateLabels(0)
    .groupSpacing(0.1);
    chart.multibar
    .hideable(true);
    chart.reduceXTicks(false).staggerLabels(true);
    chart.xAxis
    .showMaxMin(false)
    .tickFormat(function(d){ return d;});
    chart.yAxis
    .tickFormat(function(d){ return d;});
    d3.select('#chart1 svg')
    .datum(<?=$dataSet?>)
    .call(chart);
    nv.utils.windowResize(chart.update);
    chart.dispatch.on('stateChange', function(e) { nv.log('New State:', JSON.stringify(e)); });
    return chart;
});
</script>
