<?
require_once 'clients/CamemisChart.php';
require_once 'models/statistic/LetterStatisticsDBAccess.php';

$objectType = isset($_GET["objectType"]) ? addText($_GET["objectType"]) : "";
$objectId = isset($_GET["objectId"]) ? addText($_GET["objectId"]) : "";

$dataSet = "";
switch($objectType){
    case "WEEKLY":
        $dataSet = LetterStatisticsDBAccess::getDataSetLetterDashboard("WEEKLY");
    break;
    case "MONTHLY":
        $dataSet = LetterStatisticsDBAccess::getDataSetLetterDashboard("MONTHLY");
    break;
    case "YEARLY":
        $dataSet = LetterStatisticsDBAccess::getDataSetLetterDashboard("YEARLY");
    break;
}

$chart = new CamemisChart("MULTIBARCHART", 'chart1', $dataSet);
$chart->chartSVG = "display";
$chart->height = 230;
?>
<!DOCTYPE html>
<meta charset="utf-8">
<link href="http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer" rel="stylesheet" type="text/css">
<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">
<body>
    <script src="/public/nvd3/nvd3-camemis.php"></script>
    <div><?= $chart->setChartDisplay(); ?></div>
    <script><?= $chart->setChartScript(); ?></script>
</body>
</html>
