<?

require_once 'clients/CamemisChart.php';
require_once 'models/statistic/StaffStatisticsDBAccess.php';

$objectType = isset($_GET["objectType"])?addText($_GET["objectType"]):"";
$staffId = isset($_GET["staffId"])?addText($_GET["staffId"]):"";

$dataSet = StaffStatisticsDBAccess::getDataSetStaffAttendance("WEEKLY", $staffId);
switch($objectType){
    case "WEEKLY":
        $dataSet = StaffStatisticsDBAccess::getDataSetStaffAttendance("WEEKLY", $staffId);
        break;
    case "MONTHLY":
        $dataSet = StaffStatisticsDBAccess::getDataSetStaffAttendance("MONTHLY", $staffId);
        break;
    case "YEARLY":
        $dataSet = StaffStatisticsDBAccess::getDataSetStaffAttendance("YEARLY", $staffId);
        break;
}

$chart = new CamemisChart("MULTIBARCHART", 'chart1', $dataSet);
$chart->setChartSVG("display");
$chart->setShowLegend("false");
$chart->setHeight(230);
?>
<!DOCTYPE html>
<meta charset="utf-8">
<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">
<body>
    <script src="/public/nvd3/nvd3-camemis.php"></script>
    <div><?= $chart->setChartDisplay(); ?></div>
    <script><?= $chart->setChartScript(); ?></script>
</body>
</html>
