<?

require_once 'clients/CamemisChart.php';
require_once 'models/statistic/StudentStatisticsDBAccess.php';

$objectType = isset($_GET["objectType"])?addText($_GET["objectType"]):"";
$campusId = isset($_GET["campusId"])?addText($_GET["campusId"]):"";
$subjectId = isset($_GET["subjectId"])? (int)$_GET["subjectId"]:"";

switch($objectType){
    case "CAMPUS":
        $dataSet = StudentStatisticsDBAccess::getDataSetStudentCreditSystem("CAMPUS", false, false);
        break;
    case "SUBJECT":
        $dataSet = StudentStatisticsDBAccess::getDataSetStudentCreditSystem("GRADE", $campusId, false);
        break;
    case "GROUP":
        $dataSet = StudentStatisticsDBAccess::getDataSetStudentCreditSystem("CLASS", $campusId, $subjectId);
        break;
}
?>

$chart = new CamemisChart("MULTI_BAR_CHART", 'chart1', $dataSet);
$chart->chartSVG = "display";
$chart->height = 230;
<!DOCTYPE html>
<meta charset="utf-8">
<link href="http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer" rel="stylesheet" type="text/css">
<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">
<body>
    <script src="/public/nvd3/nvd3-camemis.php"></script>
    <div><?= $chart->setChartDisplay(); ?></div>
    <script><?= $chart->setChartScript(); ?></script>
</body>
</html>
