<?
require_once 'models/statistic/StudentStatisticsDBAccess.php';

$objectType = isset($_GET["objectType"])?addText($_GET["objectType"]):"";
$campusId = isset($_GET["campusId"])?addText($_GET["campusId"]):"";
$gradeId = isset($_GET["gradeId"])?addText($_GET["gradeId"]):"";
$schoolyearId = isset($_GET["schoolyearId"])?addText($_GET["schoolyearId"]):"";

if(!$schoolyearId){
    $showLegen = "false";
    switch($objectType){
        case "CAMPUS":
            $dataSet = StudentStatisticsDBAccess::getDataSetStudentTraditionalSystem("CAMPUS", false, false);
            break;
        case "GRADE":
            $dataSet = StudentStatisticsDBAccess::getDataSetStudentTraditionalSystem("GRADE", $campusId, false);
            break;
        case "CLASS":
            $dataSet = StudentStatisticsDBAccess::getDataSetStudentTraditionalSystem("CLASS", $campusId, $gradeId);
            break;
    }
}else{
    $showLegen = "true";
    switch($objectType){
        case "CAMPUS":
            $dataSet = StudentStatisticsDBAccess::getDataSetStudentTradiionalEnrollment("CAMPUS",$campusId, $gradeId, $schoolyearId);
            break;
        case "GRADE":
            $dataSet = StudentStatisticsDBAccess::getDataSetStudentTradiionalEnrollment("GRADE", $campusId, $gradeId, $schoolyearId);
            break;
    }
}

?>
<!DOCTYPE html>
<meta charset="utf-8">

<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">

<style>

body {
    overflow-y:scroll;
}

text {
    font: 11px tahoma,verdana,arial,sans-serif,Hanuman;
}

#chart1 {
    height:230px; 
    margin: 10px;
    min-width: 100px;
    min-height: 100px;
}

</style>
<body>

<div id="chart1"><svg></svg></div>
<script src="/public/nvd3/nvd3-camemis.php"></script>
<script>

var chart;
nv.addGraph(function() {
    chart = nv.models.multiBarChart()
    .showLegend(<?=$showLegen?>)
    .showXAxis(true)
    .barColor(d3.scale.category20().range())
    .margin({bottom: 50})
    .transitionDuration(300)
    .delay(0)
    .rotateLabels(0)
    .groupSpacing(0.1);
    chart.multibar
    .hideable(true);
    chart.reduceXTicks(false).staggerLabels(true);
    chart.xAxis
    .showMaxMin(false)
    .tickFormat(function(d){ return d;});
    chart.yAxis
    .tickFormat(function(d){ return d;});
    d3.select('#chart1 svg')
    .datum(<?=$dataSet?>)
    .call(chart);
    nv.utils.windowResize(chart.update);
    chart.dispatch.on('stateChange', function(e) { nv.log('New State:', JSON.stringify(e)); });
    return chart;
});
</script>
