<?
require_once 'clients/CamemisChart.php';
require_once 'models/statistic/StudentStatisticsDBAccess.php';

$objectType = isset($_GET["objectType"]) ? addText($_GET["objectType"]) : "";
$academicId = isset($_GET["academicId"]) ? (int) $_GET["academicId"] : "";
$campusId = isset($_GET["campusId"]) ? addText($_GET["campusId"]) : "";
$gradeId = isset($_GET["gradeId"]) ? addText($_GET["gradeId"]) : "";
$schoolyearId = isset($_GET["schoolyearId"]) ? addText($_GET["schoolyearId"]) : "";
$target = isset($_GET["target"]) ? addText($_GET["target"]) : "";
$studentId = isset($_GET["studentId"]) ? addText($_GET["studentId"]) : "";

$dataSet = StudentStatisticsDBAccess::getDataSetStudentAttendance("WEEKLY", $studentId, $academicId, $target);
switch ($objectType) {
    case "WEEKLY":
        $dataSet = StudentStatisticsDBAccess::getDataSetStudentAttendance("WEEKLY", $studentId, $academicId, $target);
        break;
    case "MONTHLY":
        $dataSet = StudentStatisticsDBAccess::getDataSetStudentAttendance("MONTHLY", $studentId, $academicId, $target);
        break;
    case "YEARLY":
        $dataSet = StudentStatisticsDBAccess::getDataSetStudentAttendance("YEARLY", $studentId, $academicId, $target);
    case "CAMPUS":
        $params = array('campusId' => $campusId, 'schoolyearId' => $schoolyearId);
        $dataSet = StudentStatisticsDBAccess::getDataAttendance($params);
        break;
    case "GRADE":
        $params = array('campusId' => $campusId, 'gradeId' => $gradeId, 'schoolyearId' => $schoolyearId);
        $dataSet = StudentStatisticsDBAccess::getDataAttendance($params);
        break;
}

$chart = new CamemisChart("MULTIBARCHART", 'chart1', $dataSet);
$chart->setChartSVG("display");
$chart->setShowLegend(false);
$chart->setHeight(230);
?>
<!DOCTYPE html>
<meta charset="utf-8">
<link href="http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer" rel="stylesheet" type="text/css">
<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">
<body>
    <script src="/public/nvd3/nvd3-camemis.php"></script>
    <div><?= $chart->setChartDisplay(); ?></div>
    <script><?= $chart->setChartScript(); ?></script>
</body>
</html>
