<?

require_once 'clients/CamemisChart.php';
require_once 'models/statistic/UserOnlineStatisticsDBAccess.php';

$dataset = UserOnlineStatisticsDBAccess::getDataSetUserOnline();

$chart = new CamemisChart("STACKEAREACHART", 'Online1', $dataset);
$chart->setChartDIV("chart1");
$chart->setHeight(300);

?>
<!DOCTYPE html>
<meta charset="utf-8">

<link href=http://fonts.googleapis.com/css?family=Hanuman:regular,bold&subset=khmer rel=stylesheet type=text/css>
<link href="/public/nvd3/src/nv.d3.css" rel="stylesheet" type="text/css">

<style>

body {
  overflow-y:scroll;
}

text {
  font: 11px sans-serif;
}

</style>
<body class='with-3d-shadow with-transitions'>

<script src="/public/nvd3/nvd3-camemis.php"></script>

<?

echo $chart->drawChart();

?>
