<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisGrid.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$setId = isset($_GET["setId"])?addText($_GET["setId"]):"";
$tmpArr = explode("-",$setId);
$academicId = $tmpArr[0];
$subjectId = $tmpArr[1]; 
$objectGradeSubject=SubjectDBAccess::getAcademicSubject($subjectId, $academicId);
$setParams = "target=ACADEMIC_SUBJECT&objectId=".$objectGradeSubject->GRADE_SUBJECT_ID."&academicId=".$academicId."";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $ONLINE_COURSE = "{
            title: '".ONLINE_COURSE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'GOALS', url: ''})]
        }";
        
        if (Zend_Registry::get('SCHOOL')->AVAILABLE_ELEARNING == 2) {
            $PENEL_ITEMS[] = $ONLINE_COURSE;
        }
        
        $OBJECTIVES = "{
            title: '".OBJECTIVES."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'OBJECTIVES', url: '/subject/subjectdisplay/?setId=".$setId."&field=OBJECTIVES&object=gradesubject'})]
        }";
        $PENEL_ITEMS[] = $OBJECTIVES;
        
        $EVALUATION = "{
            title: '".EVALUATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'EVALUATION', url: '/subject/subjectdisplay/?setId=".$setId."&field=EVALUATION&object=gradesubject'})]
        }";
        $PENEL_ITEMS[] = $EVALUATION;
        
        $MATERIALS = "{
            title: '".MATERIALS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'MATERIALS', url: '/subject/subjectdisplay/?setId=".$setId."&field=MATERIALS&object=gradesubject'})]
        }";
        $PENEL_ITEMS[] = $MATERIALS;
        
        $ATTACHMENTS = "{
            title: '".ATTACHMENTS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ATTACHMENTS', url: '/dataset/dataview/?camIds=".$this->urlEncryp->encryptedGet($setParams)."'})]
        }";
       
        $PENEL_ITEMS[] = $ATTACHMENTS;
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        
        $TBAR = "";
        switch(UserAuth::getUserType()){
            case 'STUDENT':
            case 'SUPERADMIN':
            case 'ADMIN':
            $TBAR = ",tbar:[{
                text: '".CANCEL."'
                ,id: 'CANCEL_ID'
                ,iconCls:'icon-cancel'
                ,scope:this
                ,handler: function(){window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);}
            }]";
            break;
        }
        
        echo "viewport = new Ext.Viewport({";
            echo "layout: 'fit'";
            echo ",border: false";
            echo ",items:[{";
                echo "layout:'fit'";
                echo ",bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px;'";
                echo ",border:false";
                echo "".$TBAR."";
                echo ",items:[{";
                    echo "xtype: 'tabpanel'";
                    echo ",plain:true";
                    echo ",activeTab: 0";
                    echo ",items:".$CHOOSE_ITEMS."";
                echo "}]";  
            echo "}]";
        echo "});";
        ?>
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>