<?
////////////////////////////////////////////////////////////////////////////////
// @chungveng
// Date: 16.12.2013
////////////////////////////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$personType = isset($_GET["personType"])? addText($_GET["personType"]):""; //@Man

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    //////////////////////////////////////////////////////////////////////
    //@Viewport
    /////////////////////////////////////////////////////////////////////
    Ext.onReady(function() {
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,layout: 'fit'
                ,tbar:[{
                    text:'<?=REFRESH?>'
                    ,iconCls:'icon-arrow_refresh'
                    ,handler: function(){
                        window.location="<?=CamemisPage::setRequestURI()?>";
                    }
                }]
                ,items:[{
                    layout:'column'
                    ,height:percentHeight(100)
                    ,autoScroll:true
                    ,border:false
                    ,defaults: {
                        layout: 'anchor'
                        ,defaults: {anchor: '100%'}
                    }
                    ,items: [{
                        columnWidth: 1
                        ,baseCls:'x-plain'
                        ,bodyStyle:'padding:5px 5px 5px 5px'
                        ,items:[{
                            title: '<?=WEEK?>'
                            ,layout: 'fit'
                            ,collapsible: true
                            ,collapsed: false
                            ,height:350
                            ,items: [new Ext.ux.IFrameComponent({ id: 'DISCIPINE_WEEKLY', url:'/chart/discipline/?camIds=<?=$this->urlEncryp->encryptedGet("objectType=WEEKLY&personType=$personType")?>'})]
                        }]
                    },{
                        columnWidth: 1
                        ,baseCls:'x-plain'
                        ,bodyStyle:'padding:0px 5px 5px 5px'
                        ,items:[{
                            title: '<?=MONTH?>'
                            ,layout: 'fit'
                            ,collapsible: true
                            ,collapsed: false
                            ,height:350
                            ,items: [new Ext.ux.IFrameComponent({ id: 'DISCIPLINE_MONTHLY', url:'/chart/discipline/?camIds=<?=$this->urlEncryp->encryptedGet("objectType=MONTHLY&personType=$personType")?>'})]
                        }]    
                    },{
                        columnWidth: 1
                        ,baseCls:'x-plain'
                        ,bodyStyle:'padding:0px 5px 5px 5px'
                        ,items:[{
                            title: '<?=YEAR?>'
                            ,layout: 'fit'
                            ,collapsible: true
                            ,collapsed: false
                            ,height:350
                            ,items: [new Ext.ux.IFrameComponent({ id: 'DISCIPLINE_YEARLY', url:'/chart/discipline/?camIds=<?=$this->urlEncryp->encryptedGet("objectType=YEARLY&personType=$personType")?>'})]
                        }]    
                    }]///////////////////be continune
                }]
            }]
        });
    });
</script>
    
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>
