<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM= new CamemisForm("DISCIPLINE");
$OBJECT_FORM->setSaveUrl("/discipline/jsonsave/");
$OBJECT_FORM->setLoadUrl("/discipline/jsonload/"); 

$personType = isset($_GET["personType"])?$_GET["personType"]:"";

switch (strtoupper($personType)) {
    case "STAFF":
        $TITLE = STAFF;
        $DISCIPLINE_REMOVE_RIGHT = "STAFF_DISCIPLINE_REMOVE_RIGHT";
        $DISCIPLINE_EDIT_RIGHT = "STAFF_DISCIPLINE_EDIT_RIGHT";
        
        $OBJECT_GRID = new CamemisGrid("STAFF", "LIST");
        $OBJECT_GRID->setLoadUrl("/staff/jsonload/");
        $OBJECT_GRID->setSaveUrl("/staff/jsonsave/");
        
    break;
    default:
        $TITLE = STUDENT;
        $DISCIPLINE_REMOVE_RIGHT = "STUDENT_DISCIPLINE_REMOVE_RIGHT";
        $DISCIPLINE_EDIT_RIGHT = "STUDENT_DISCIPLINE_EDIT_RIGHT";
        
        $OBJECT_GRID = new CamemisGrid("STUDENT", "LIST");
        $OBJECT_GRID->setLoadUrl("/student/jsonload/");
        $OBJECT_GRID->setSaveUrl("/student/jsonsave/");
    break;
}
//////////////////////

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    <?
    camemisPage::ExtformVTypes();
    ?>
    Ext.onReady(function() {
        
        Ext.form.Field.prototype.msgTarget = 'side';
        function cssText(value, metadata, record){
            return '<div style="font-weight:normal; color:#333; padding: 5px;">' + value + '</div>';
        }
        function cssStatus(v, p, record){
            return String.format('<div style=\"font-weight:bold;padding:4px;background:{1};color:{2};\">{0}</div>'
                ,v
                ,record.data['BG_COLOR']
                ,record.data['BG_COLOR_FONT']
            );
        }
        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $OBJECT_GRID->addReadField("name: 'ID'");
        $OBJECT_GRID->addReadField("name: 'CODE'");
        $OBJECT_GRID->addReadField("name: 'GENDER'");
        $OBJECT_GRID->addReadField("name: 'BG_COLOR'");
        $OBJECT_GRID->addReadField("name: 'BG_COLOR_FONT'");
        $OBJECT_GRID->addReadField("name: 'STATUS_KEY'");
        $OBJECT_GRID->addReadField("name: 'FULL_NAME'");
        $OBJECT_GRID->addReadField("name: 'STATUS'");
        $OBJECT_GRID->addReadField("name: 'CURRENT_ACADEMIC'");

        switch(Zend_Registry::get('SYSTEM_LANGUAGE')){
            case "VIETNAMESE": $width = 125;break;
            default: $width = 85;break;
        }

        $OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: ".$width.",renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY'");
        $OBJECT_GRID->addColumn("header: '<b>" .CODE. "</b>', align:'left', width: 150, dataIndex: 'CODE'");  
        $OBJECT_GRID->addColumn("header: '<b>".FULL_NAME."</b>', width: 150, renderer:cssText, sortable: true, dataIndex: 'FULL_NAME'");
        $OBJECT_GRID->addColumn("header: '<b>".GENDER."</b>', width: 100, renderer:cssText, sortable: true, dataIndex: 'GENDER'");
        $OBJECT_GRID->addColumn("header: '<b>".CURRENT_CLASS."</b>', width: 150,  renderer: cssText, align: 'center', sortable: true, dataIndex: 'CURRENT_ACADEMIC'");

        switch (strtoupper($personType)) {
            case "STAFF":
                $OBJECT_GRID->baseParams = "
                    start:0
                    ,limit:100
                    ,cmd: 'searchStaff'
                ";
                $OBJECT_GRID->isObjectDefaultOnLoad = true;
            break;
            default:
                $OBJECT_GRID->baseParams = "
                    start:0
                    ,limit:100
                    ,cmd: 'searchStudent'
                    ,classId: '".$this->academicId."'
                ";
                $OBJECT_GRID->isObjectDefaultOnLoad = false;
            break;
        }
        
        $OBJECT_GRID->loadMask = true;
        $OBJECT_GRID->isPagingToolbar = true;
        $OBJECT_GRID->isQuickySearch = true;
        $OBJECT_GRID->forceFit = "false";
        $OBJECT_GRID->renderJS();

        $DESCRIPTION_ITEMS = '';
        switch(UserAuth::getUserType()) {
            case "STUDENT":
                $DETAIL_INFORMATION_ITEMS = "
                {".CamemisField::Displayfield('INFRACTION_DATE', INFRACTION_DATE)."}
                ,{".CamemisField::comboCamemisTypes("DISCIPLINE_TYPE_STUDENT", INFRACTION_TYPE, true)."}
                ,{".CamemisField::ComboPunishmentType()."} 
                ";
                $DESCRIPTION_ITEMS = "
                {".CamemisField::Displayfield("COMMENT", DESCRIPTION)."}
                ";
            break;
            default:
                switch (strtoupper($personType)) {
                    case "STAFF":
                        $DETAIL_INFORMATION_ITEMS = "
                        {".CamemisField::Datefield('INFRACTION_DATE', INFRACTION_DATE, true)."}
                        ,{".CamemisField::comboCamemisTypes("DISCIPLINE_TYPE_STAFF", DISCIPLINE, false,false, true)."}
                        ";
                    break;
                    default:
                        $DETAIL_INFORMATION_ITEMS = "
                        {".CamemisField::Datefield('INFRACTION_DATE', INFRACTION_DATE, true)."}
                        ,{".CamemisField::comboCamemisTypes("DISCIPLINE_TYPE_STUDENT", INFRACTION_TYPE, false,false, true)."}
                        ,{".CamemisField::ComboPunishmentType()."} 
                        ";
                    break;
                }

                $DESCRIPTION_ITEMS = "
                    {".CamemisField::Textarea("COMMENT", DESCRIPTION, 150)."}
                ";
            break;
        }
        //////////////////////
        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [".$DETAIL_INFORMATION_ITEMS."]
            }]
        }
        ";

        $DESCRIPTION = "
        {
            title: '".DISCIPLINE." - ".NOTES."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,style: 'padding: 5px'
                ,items: [".$DESCRIPTION_ITEMS."]
            }]
        }
        ";
        
        $CREATED = "
        {
            title: '".CREATED."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#E0E7F7; padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("CREATED_DATE",CREATED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("CREATED_BY",CREATED_BY,false)."
                }]
            }]
        }
        ";
        
        $MODIFIED = "
        {
            title: '".MODIFIED."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#E0E7F7; padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("MODIFY_DATE",MODIFY_DATE,false)."
                },{
                    ".CamemisField::Displayfield("MODIFY_BY",MODIFY_BY,false)."
                }]
            }]
        }
        ";

        $ENABLED = "
        {
            title: '".ENABLED."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#E0E7F7; padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("ENABLED_DATE",ENABLED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("ENABLED_BY",ENABLED_BY,false)."
                }]
            }]
        }
        ";

        $DISABLED = "
        {
            title: '".DISABLED."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#E0E7F7; padding:10px'
                ,items:[{
                    ".CamemisField::Displayfield("DISABLED_DATE",DISABLED_DATE,false)."
                },{
                    ".CamemisField::Displayfield("DISABLED_BY",DISABLED_BY,false)."
                }]
            }]
        }
        ";
        $TITLE_INFO =" {
            title: '".$TITLE."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px;'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px;'
                ,tbar: ['->',{
                    text: '".$TITLE."'
                    ,iconCls:'icon-application_form_add'
                    ,handler: function(){
                        var win = new Ext.Window({
                            title: '".$TITLE."'
                            ,id: 'OPEN_WINDOW'
                            ,closable:true
                            ,width:percentWidth(70)
                            ,height: percentHeight(85)
                            ,plain:true
                            ,modal: true
                            ,layout:'border'
                            ,border: false
                            ,collapsible: false
                            ,split: true
                            ,items: [{
                                collapsible: false
                                ,id: 'center'
                                ,region:'center'
                                ,margins: '3 3 3 0'
                                ,layout: 'fit'
                                ,items: [{xtype: '".$OBJECT_GRID->getObjectXType()."'}]
                            }]
                        });
                        win.show();
                        var grid = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');
                        if(grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {
                            var record = grid.store.getAt(rowIndex);
                            Ext.getCmp('STUDENT').setValue(record.data.FULL_NAME);
                            Ext.getCmp('studentId').setValue(record.data.ID);
                            win.close();
                        })
                    }
                }]
                ,layout: 'form'
                ,items:[
                    {".CamemisField::Textfield("STUDENT", "STUDENT", $TITLE, false, true, false)."}
                    ,{".CamemisField::Hidden("studentId")."}
                ]
            }]
        }"; 

        $FORM_ITEMS = "[";
            switch(UserAuth::getUserType()) { //@Math Man
                case "STUDENT":
                    $FORM_ITEMS .= $DETAIL_INFORMATION; 
                    $FORM_ITEMS .= ",".$DESCRIPTION;
                break;
                default:
                    if ($this->objectId !="new") {
                        $FORM_ITEMS .= $DETAIL_INFORMATION; 
                        $FORM_ITEMS .= ",".$DESCRIPTION;
                        $FORM_ITEMS .= ",".$CREATED;
                        $FORM_ITEMS .= ",".$MODIFIED;
                        $FORM_ITEMS .= ",".$ENABLED;
                        $FORM_ITEMS .= ",".$DISABLED;
                    }else{
                        $FORM_ITEMS .= $DETAIL_INFORMATION;
                        $FORM_ITEMS .= ",".$TITLE_INFO;
                        $FORM_ITEMS .= ",".$DESCRIPTION;
                    }
                break;
        }
        $FORM_ITEMS .= "]";
        
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: $FORM_ITEMS
        ";
		
        $OBJECT_FORM->addObjectItems($items);

        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        ");
        
        switch(UserAuth::getUserType()) {
            case "SUPERADMIN":
            case "ADMIN":
            case "INSTRUCTOR":
            case "TEACHER":
                if(UserAuth::getACLValue($DISCIPLINE_REMOVE_RIGHT))
                $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormRemoveObject($this->remove_status));

                if ($this->objectId !="new") {
                    if(UserAuth::getACLValue($DISCIPLINE_EDIT_RIGHT))
                    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
                    if(UserAuth::getACLValue($DISCIPLINE_EDIT_RIGHT))
                    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave()); 
                }else{
                    if(UserAuth::getACLValue($DISCIPLINE_EDIT_RIGHT)) 
                    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
                }
            break;
        }

        $OBJECT_FORM->setReleaseParams("cmd: 'releaseDiscipline',objectId: '".$this->objectId."',personType: '".$personType."'");
        $OBJECT_FORM->setLoadParams("
            cmd: 'loadDiscipline'
            ,objectId: '".$this->objectId."'
            ,personType: '".$personType."'
        ");

        if ($this->objectId !="new") {
            $OBJECT_FORM->setSaveParams("
                cmd: 'actionDiscipline'
                ,objectId: '".$this->objectId."'
                ,personType: '".$personType."'
            "); 
        }else{
            $OBJECT_FORM->setSaveParams("
                cmd: 'actionDiscipline'
                ,objectId: '".$this->objectId."'
                ,target: '".$this->target."'
                ,personType: '".$personType."'
            ");
        }
        
        $OBJECT_FORM->setRemoveParams("
            cmd: 'removeDiscipline'
            ,objectId: '".$this->objectId."'
            ,personType: '".$personType."'
        ");
        
        $OBJECT_FORM->setonEmbeddedEvents("
            if (window.parent.Ext.getCmp('DISCIPLINE_GENERAL_ID')) window.parent.Ext.getCmp('DISCIPLINE_GENERAL_ID').store.reload();
            var result = Ext.util.JSON.decode(action.response.responseText);
            var objectId = result.objectId;
            window.location='".$_SERVER["REQUEST_URI"]."&objectId='+objectId;
        ");
        
        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            if (window.parent.Ext.getCmp('DISCIPLINE_GENERAL_ID')) window.parent.Ext.getCmp('DISCIPLINE_GENERAL_ID').store.reload();
            if (window.parent.Ext.getCmp('DISCIPLINE_GENERAL_ID'))
            window.parent.Ext.getCmp('DISCIPLINE_GENERAL_ID').store.reload();
            " . camemisPage::setRequestURI() . "
        ");

        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            if (window.parent.Ext.getCmp('DISCIPLINE_GENERAL_ID')) window.parent.Ext.getCmp('DISCIPLINE_GENERAL_ID').store.reload();
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->isObjectDefaultOnLoad = ($this->objectId=="new")?false:true;
        $OBJECT_FORM->isWindowlocation = false;
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 170;
        $OBJECT_FORM->renderJS();

        $LAYOUT_ITMEMS = "[{xtype: '".$OBJECT_FORM->getObjectXType()."'}]";

        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                border: false
                ,layout: 'fit'
                ,items: <?=$LAYOUT_ITMEMS;?>
            }]
        });
        Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
    });
</script>
<style type="text/css">
	#COMMENT_ID {height: auto !important;}
</style>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>