<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// @Sothearung....
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_university/student/StudentDBAccess.php';
require_once 'models/app_university/student/StudentAcademicDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$DB_STUDENT = StudentDBAccess::getInstance();

$OBJECT_FORM = new CamemisForm("STUDENT");
$OBJECT_FORM->setLoadUrl('/student/jsonload/');
$OBJECT_FORM->setSaveUrl('/student/jsonsave/');

$academicId = isset($_GET["academicId"])? (int) $_GET["academicId"]:"";
$schoolyearId = isset($_GET["schoolyearId"])?addText($_GET["schoolyearId"]):"";
$studentId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";

$STUDENT_CLASS = StudentAcademicDBAccess::getCurrentStudentAcademic(
        $studentId
        , $academicId
        , false
        , false
        );

$CHECK_STUDENT_CLASS_ACTIVITY = $DB_STUDENT->checkStudentActivityInSchoolyear(
        $studentId
        , $schoolyearId
        );

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<div id="initNO" class="x-hide-display" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="headerError"><?=CAN_NOT_BE_REMOVED;?></h1>
</div>
<div id="initYES" class="x-hide-display" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="headerError"><?=MSG_WANT_PERFORM_ACTION;?></h1>
</div>
<script>

    Ext.onReady(function() {
        Ext.QuickTips.init();

        <?
        /**
        * Extjs: s.gif
        */
        camemisPage::setNoLogoutMessage();
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        if($CHECK_STUDENT_CLASS_ACTIVITY){
            $ITEMS = "
            [{
                layout: 'fit'
                ,border: false
                ,contentEl: 'initNO'
            }]
            ";
        }else{
           $ITEMS = "
            [{
                layout: 'fit'
                ,border: false
                ,contentEl: 'initYES'
            }]
            "; 
        }
        
        $formItems = "
            border: false
            ,layout: 'form'
            ,bodyStyle: 'padding:10px'
            ,items:[{
                border: false
                ,layout:'card'
                ,activeItem: 0
                ,id: 'FORM_CONTENT'
                ,items: ".$ITEMS."
            }]
        ";
        
        $OBJECT_FORM->addObjectItems($formItems);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('CENTER_CONTENT').getLayout().setActiveItem(0);}
        ");
        
        if(!$CHECK_STUDENT_CLASS_ACTIVITY){
            
            $OBJECT_FORM->setonEmbeddedEvents("
                if (window.parent.Ext.getCmp('STUDENT_ENROLLED_STUDENTS_ID')) window.parent.Ext.getCmp('STUDENT_ENROLLED_STUDENTS_ID').store.reload();
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                window.parent.Ext.getCmp('CENTER_CONTENT').getLayout().setActiveItem(0);
            ");
            
            $OBJECT_FORM->setSaveParams("
                cmd: 'jsonRemoveEnrolledStudentFromClass'
                ,removeId: '".$STUDENT_CLASS->ID."'
            ");
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        }
        
        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->bodyStyle = "padding:0px";
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 150;
        $OBJECT_FORM->renderJS();
        ?>
                
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'panel'
                ,id: 'panel'
                ,border: false
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                }]
            }]
        });
    });
</script>
<?
$registry = Zend_Registry::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>