<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisSchoolTree.php';//@veasna
require_once 'clients/CamemisSchoolTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';

require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$GENERAL_EDU_TREE = new CamemisSchoolTree("ACADEMIC", "LIST");
$GENERAL_EDU_TREE->setURL('/academic/jsontree/');
$GENERAL_EDU_TREE->setSaveUrl('/academic/jsonsave/');

///@veasna
$OBJECT_TREE = new CamemisSchoolTree("CREDIT_ACADEMIC");
$OBJECT_TREE->setURL("/academic/jsontree/");
$OBJECT_TREE->setSaveUrl("/academic/jsonsave/");
/// 

$TRAINING_TREE = new CamemisTree("TRAINING","LIST");
$TRAINING_TREE->setURL('/training/jsontree/');
$TRAINING_TREE->setSaveUrl('/training/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();  

$STUDENT_REGISTRATION_EDIT_RIGHT = UserAuth::getACLValue("STUDENT_REGISTRATION_WIZARD_EDIT_RIGHT")?"false":"true";

?>
<div id="congratulations" class="x-hide-display">
    <h1 class="header"><?=CONGRATULATIONS?></h1>
    <br/><br/>
    <p class="header"><?=STEP?> 3/3 - <?=COMPLETE?></p>
    <p class="header">
        <?=MSG_CREATE_NOW_RECORDS;?>
        <br><br>
        <?=MSG_CLICK_SAVE_BUTTON;?>
    </p>
</div>
<script>

    var classId;
    var gradeId;
    var schoolyearId;
    var campusId;
    var academicType;
    var gradeSchoolYearId = '<?=isset($_GET["classId"])?addText($_GET["classId"]):0?>';
    Ext.onReady(function() {

        Ext.QuickTips.init();
        // turn on validation errors beside the field globally
        
        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_LOCATION_PARENT = new CamemisDynCombo("DATASET","PROVINCE");
        $OBJECT_LOCATION_PARENT->setLoadUrl('/dataset/jsonload/');
        $OBJECT_LOCATION_PARENT->objectTitle = CITY_PROVINCE;
        $OBJECT_LOCATION_PARENT->allowBlank = "true";
        $OBJECT_LOCATION_PARENT->width = 250;
        $OBJECT_LOCATION_PARENT->varName = "COUNTRY_PROVINCE";
        $OBJECT_LOCATION_PARENT->setLoadParams("cmd: 'jsonAllLocation',parentId:0");
        $OBJECT_LOCATION_PARENT->renderJS();

        $OBJECT_LOCATION_CHILD = new CamemisDynCombo("DATASET","TWON");
        $OBJECT_LOCATION_CHILD->setLoadUrl('/dataset/jsonload/');
        $OBJECT_LOCATION_CHILD->objectTitle = TOWN_CITY;
        $OBJECT_LOCATION_CHILD->allowBlank = "true";
        $OBJECT_LOCATION_CHILD->width = 250;
        $OBJECT_LOCATION_CHILD->varName = "TOWN_CITY";
        $OBJECT_LOCATION_CHILD->setLoadParams("cmd: 'jsonAllLocation',parentId:'1010101010'");
        $OBJECT_LOCATION_CHILD->renderJS();

        $TRAINING_TREE->isAsyncTreeNode = false;
        $TRAINING_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $TRAINING_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $TRAINING_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());

        $TRAINING_TREE->setBaseParams("
            cmd: 'jsonTreeAllTrainings'
        ");
        $TRAINING_TREE->backgroundColor = "#F9F9F9";
        $TRAINING_TREE->isTreeExpand = false;
        $TRAINING_TREE->renderJS();
        $triggerOnClickTraining = "
            openWinXType('XTYPE_TRAINING','".TRAINING_PROGRAMS."', '".$TRAINING_TREE->getObjectXType()."', 500, percentHeight(85));
            var trainingTree = Ext.getCmp('".$TRAINING_TREE->getObjectId()."');
            trainingTree.on('click', function(node, e){   
                if(node.attributes.objecttype == 'TERM' || node.attributes.objecttype == 'CLASS'){
                    Ext.getCmp('CHOOSE_TRAINING_NAME_ID').setValue(node.text);
                    Ext.getCmp('CHOOSE_TRAINING').setValue(node.id);
                    Ext.getCmp('XTYPE_TRAINING').close();
                }
            });
        ";
        
        $OBJECT_SCHOOLYEAR = new CamemisDynCombo("ACADEMICDATE","COMBO");
        $OBJECT_SCHOOLYEAR->setLoadUrl('/academicdate/jsonload/');
        $OBJECT_SCHOOLYEAR->objectTitle = false;
        $OBJECT_SCHOOLYEAR->allowBlank = "true";
        $OBJECT_SCHOOLYEAR->varName = "SCHOOLYEAR";
        $OBJECT_SCHOOLYEAR->setLoadParams("cmd: 'allSchoolyearCombo'");
        $OBJECT_SCHOOLYEAR->renderJS();
    
        $GENERAL_EDU_TREE->isAsyncTreeNode = false;
        $GENERAL_EDU_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $GENERAL_EDU_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $GENERAL_EDU_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        $GENERAL_EDU_TREE->addTBarItems("
            xtype: 'buttongroup'
            ,items:[{
                width: 120
                ,xtype: '".$OBJECT_SCHOOLYEAR->getObjectXType()."'
            }]
        ");

        $GENERAL_EDU_TREE->setBaseParams("
            cmd: 'getTreeTraditionalEducationSystem'
             ,gradeSchoolyearId: gradeSchoolYearId
        ");                                       
        $GENERAL_EDU_TREE->isOnClickContextMenu = false;
        $GENERAL_EDU_TREE->isTreeExpand = false;
        $GENERAL_EDU_TREE->renderJS();
        
        /////@veasna   credit system
        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        $OBJECT_TREE->addTBarItems("
                xtype: 'buttongroup'
                ,items:[{
                    width: 80
                    ,xtype: '".$OBJECT_SCHOOLYEAR->getObjectXType()."'
                }]
            ");
        $OBJECT_TREE->setBaseParams("
                cmd: 'getTreeCreditEducationSystem'
                ,educationSystem:1
            ");
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isCrediSystem = true;
        $OBJECT_TREE->isTreeExpand = true;
        $OBJECT_TREE->renderJS();
        $triggerCreditTreeOnClick = "
            openWinXType('SCHOOL_YEAR_OR_CLASS','".HIGHER_EDUCATION."', '".$OBJECT_TREE->getObjectXType()."', 500, percentHeight(85));
            var myTree = Ext.getCmp('".$OBJECT_TREE->getObjectId()."');

            Ext.getCmp('COMBO_ID').on('select', function() {
                myTree.loader.baseParams.SCHOOLYEAR = Ext.getCmp('COMBO_ID').getValue();
                myTree.root.reload();
                myTree.getRootNode().expand(true, false);
            });

            myTree.getRootNode().expand(true, false);

            if (myTree) myTree.on('click', function(node, e){   
                if(node.attributes.objecttype == 'CLASS' || node.attributes.objecttype == 'SUBJECT'){
                    Ext.getCmp('CHOOSE_CREDIT_NAME_ID').setValue(node.attributes.title);
                    Ext.getCmp('CHOOSE_GRADE').setValue(node.id);
                    Ext.getCmp('SCHOOL_YEAR_OR_CLASS').close();
                }
            });
        ";  
        ///

        $studentschoolIdHandler = "
            function(){
                var win = new Ext.Window({
                    modal: true
                    ,title: '".CHECK_STUDENT_SCHOOL_ID."'
                    ,width:330
                    ,autoHeight: true
	                ,closeAction:'hide'
	                ,plain: false
	                ,xtype: 'form'
	                ,labelAlign: 'top'
	                ,bodyStyle: 'padding:10px'
                        ,items:[{
                            xtype: 'textfield'
                            ,allowBlank: false
                            ,id: 'CHECK_FORM_ID'
                            ,name: 'studentSchoolId'
                            ,allowBlank: false
                            ,width: 250
	                }]
                    ,tbar:['->',{
                        text: '".APPLY."'
                        ,id: 'APPLY_ID'
                        ,iconCls:'icon-lightning_add'
                        ,handler: function(){
                            var checkFormId = document.getElementById('CHECK_FORM_ID').value;
                            Ext.Ajax.request({
                                url: '/student/jsonload/'
                                ,method: 'POST'
                                ,params: {
                                    cmd: 'jsonCheckStudentSchoolID'
                                    ,studentSchoolId: checkFormId
                                }
                                ,success: function(result) {
                                    jsonData = Ext.util.JSON.decode(result.responseText);
                                    if (jsonData.status){
                                        Ext.getCmp('CHOOSE_STUDENT_SCHOOID_ID_NAME').setValue(checkFormId);
                                        win.close();
                                    }else{
                                        ".camemisPage::alertPleaseSelect(WARNING, setICONV(SCHOOL_ID_EXISTS))."
                                    }
                                }
                            });
                        }
                    },{
                        text: '".CLOSE."'
                        ,iconCls:'icon-cancel'
                        ,handler: function(){
                            win.close();
                        }
                    }]
                });
                win.show();
            }
        ";

        $triggerOnClick = "
            openWinXType('SCHOOL_YEAR_OR_CLASS','".SCHOOL_YEAR_OR_CLASS."', '".$GENERAL_EDU_TREE->getObjectXType()."', 500, percentHeight(85));
            var academicTree = Ext.getCmp('".$GENERAL_EDU_TREE->getObjectId()."');
            
            Ext.getCmp('COMBO_ID').on('select', function() {
                academicTree.loader.baseParams.SCHOOLYEAR = Ext.getCmp('COMBO_ID').getValue();
                academicTree.root.reload();
                academicTree.getRootNode().expand(true, false); 
            }); 
             
            academicTree.getRootNode().expand(true, false);  
            academicTree.on('click', function(node, e){ 
               
                Ext.getCmp('CHOOSE_CAMPUS').setValue('');
                Ext.getCmp('CHOOSE_GRADE').setValue('');
                Ext.getCmp('CHOOSE_SCHOOLYEAR').setValue('');
                Ext.getCmp('CHOOSE_CLASS').setValue('');
                Ext.getCmp('CHOOSE_GRADE_NAME_ID').setValue('')
                        
                if(node.attributes.objecttype == 'SCHOOLYEAR' || node.attributes.objecttype == 'CLASS' ){
                
                    //////////////////////
                    //Choose Schoolyear
                    //////////////////////
                    if (node.attributes.objecttype == 'SCHOOLYEAR') {
                        Ext.getCmp('CHOOSE_CAMPUS').setValue(node.attributes.campusId);
                        Ext.getCmp('CHOOSE_GRADE').setValue(node.id);
                        Ext.getCmp('CHOOSE_SCHOOLYEAR').setValue(node.attributes.schoolyearId);
                        Ext.getCmp('CHOOSE_GRADE_NAME_ID').setValue(node.attributes.title);
                    }
                    ///////////////////////
                    //Choose Class
                    ///////////////////////
                    if (node.attributes.objecttype == 'CLASS') {
                        Ext.getCmp('CHOOSE_CAMPUS').setValue(node.attributes.campusId);
                        Ext.getCmp('CHOOSE_GRADE').setValue(node.id);
                        Ext.getCmp('CHOOSE_SCHOOLYEAR').setValue(node.attributes.schoolyearId);
                        classId=node.id;
                        Ext.getCmp('CHOOSE_CLASS').setValue(node.id);
                        Ext.getCmp('CHOOSE_GRADE_NAME_ID').setValue(node.attributes.title);
                    }
                    
                    Ext.getCmp('SCHOOL_YEAR_OR_CLASS').close();
                }
            });
        ";
        
        if(!SchoolDBAccess::displayPersonNameInGrid()){
           $personItems = "[
                {".CamemisField::Textfield("LASTNAME", "LASTNAME", LASTNAME, true)."}
                ,{".CamemisField::Textfield("FIRSTNAME", "FIRSTNAME", FIRSTNAME, true)."}
                ,{".CamemisField::ComboGender(GENDER)."}
                ,{".CamemisField::Datefield("DATE_BIRTH", DATE_BIRTH, true)."}
                ,{".CamemisField::Textarea("BIRTH_PLACE", BIRTH_PLACE, 80)."}
                ,{".CamemisField::comboReligion()."}
                ,{".CamemisField::comboEthnic()."}
                ,{".CamemisField::comboNationality()."}
            ]";
        }else{
            $personItems = "[
                {".CamemisField::Textfield("FIRSTNAME", "FIRSTNAME", FIRSTNAME, true)."}
                ,{".CamemisField::Textfield("LASTNAME", "LASTNAME", LASTNAME, true)."}
                ,{".CamemisField::ComboGender(GENDER)."}
                ,{".CamemisField::Datefield("DATE_BIRTH", DATE_BIRTH, true)."}
                ,{".CamemisField::Textarea("BIRTH_PLACE", BIRTH_PLACE, 80)."}
                ,{".CamemisField::comboReligion()."}
                ,{".CamemisField::comboEthnic()."}
                ,{".CamemisField::comboNationality()."}
            ]";
        }
        
        $contactItems = "[
            {".CamemisField::Textarea("ADDRESS", ADDRESS, 50)."},
            {xtype: '".$OBJECT_LOCATION_PARENT->getObjectXType()."'},
            {xtype: '".$OBJECT_LOCATION_CHILD->getObjectXType()."'},
            {".CamemisField::Textfield("PHONE", "PHONE", PHONE, false)."},
            {".CamemisField::Textfield("EMAIL", "EMAIL", EMAIL, false)."}
        ]";
        
        $card1Items = "[{
            title: '".PERSONAL_INFORMATION."'
            ,width: 520
            ,bodyStyle: 'padding:10px'
            ,layout: 'form'
            ,items: ".$personItems."
        },{
            title: '".CONTACT_INFORMATION."'
            ,bodyStyle: 'padding:10px'
            ,style:'padding:5px 0px 0px 0px'
            ,layout: 'form'
            ,width: 520
            ,items: ".$contactItems."
        }]";
        $SEARCH_ITEMS = array();
            
        $GENERAL_EDUCATION="{".CamemisField::Radio("GENERAL_EDUCATION", "ACADEMIC", GENERAL_EDUCATION, "GENERAL", false)."}";
        //@veasna
        $CREDIT_EDUCATION="{".CamemisField::Radio("CREDIT_EDUCATION_SYSTEM", "ACADEMIC", CREDIT_EDUCATION_SYSTEM, "CREDIT", false)."}";
        //
        $TRAINING_PROGRAMS= "{".CamemisField::Radio("TRAINING", "ACADEMIC", TRAINING_PROGRAMS, "TRAINING", false)."}";
        $CHOOSE_GRADE_NAME= "{".CamemisField::Trigger("CHOOSE_GRADE_NAME",GENERAL_EDUCATION,$triggerOnClick, false, true, false)."}";
        $CHOOSE_TRAINING_NAME= "{".CamemisField::Trigger("CHOOSE_TRAINING_NAME",TRAINING_PROGRAMS,$triggerOnClickTraining,false, true, false)."}";
        $CHOOSE_CREDIT_NAME= "{".CamemisField::Trigger("CHOOSE_CREDIT_NAME",CREDIT_EDUCATION_SYSTEM,$triggerCreditTreeOnClick,false, true, false)."}";//@veasna
        $CHOOSE_CAMPUS="{".CamemisField::Hidden("CHOOSE_CAMPUS",false)."}";
        $CHOOSE_GRADE="{".CamemisField::Hidden("CHOOSE_GRADE",false)."}";
        $CHOOSE_SCHOOLYEAR="{".CamemisField::Hidden("CHOOSE_SCHOOLYEAR",false)."}";
        $CHOOSE_CLASS="{".CamemisField::Hidden("CHOOSE_CLASS",false)."}";
        $CHOOSE_TRAINING="{".CamemisField::Hidden("CHOOSE_TRAINING",false)."}";
        $STUDENT_TRANSFER="{".CamemisField::ComboYesNO("TRANSFER", "TRANSFER", STUDENT_TRANSFER,false,false)."}";
        
        if (UserAuth::displayRoleGeneralEducation()){
           //@veasna
            if (UserAuth::displayTraditionalEducationSystem()) 
            $SEARCH_ITEMS[]=  $GENERAL_EDUCATION ;
            if (UserAuth::displayCreditEducationSystem()) 
            $SEARCH_ITEMS[]= $CREDIT_EDUCATION ;
            //
        }
        if (UserAuth::displayRoleTrainingEducation()){
           $SEARCH_ITEMS[]=  $TRAINING_PROGRAMS ;
        }
        $SEARCH_ITEMS[]=  $CHOOSE_GRADE_NAME ;
        $SEARCH_ITEMS[]=  $CHOOSE_TRAINING_NAME ;
        $SEARCH_ITEMS[]=  $CHOOSE_CREDIT_NAME ; //@veasna
        $SEARCH_ITEMS[]=  $CHOOSE_CAMPUS ;
        $SEARCH_ITEMS[]=  $CHOOSE_GRADE ;
        $SEARCH_ITEMS[]=  $CHOOSE_SCHOOLYEAR ;
        $SEARCH_ITEMS[]=  $CHOOSE_CLASS ;
        $SEARCH_ITEMS[]=  $CHOOSE_TRAINING ;
        $SEARCH_ITEMS[]=  $STUDENT_TRANSFER ; 
        
        $CHOOSE_SEARCH_ITEMS = implode(",", $SEARCH_ITEMS);
        
        $card2Items = "[{
            title: '".SCHOOL_INFORMATION."'
            ,bodyStyle: 'padding:10px'
            ,width: 550
            ,layout: 'form'
            ,tbar:['->',{
                text: '".CHECK_STUDENT_SCHOOL_ID."'
                ,iconCls:'icon-lightning'
                ,handler: ".$studentschoolIdHandler."
            }]
            ,items: [{
                name: 'STUDENT_SCHOOL_ID'
                ,width: 250
                ,fieldLabel: '".STUDENT_SCHOOL_ID."'
                ,xtype: 'textfield'
                ,allowBlank: true
                ,readOnly: true
                ,id: 'CHOOSE_STUDENT_SCHOOID_ID_NAME'
            },{
                xtype: 'hidden'
                ,id: 'CHOOSE_STUDENT_SCHOOL_ID'
            },".$CHOOSE_SEARCH_ITEMS."]
        }]";
        
        $STUDENT_REGISTRATION_READ_RIGHT = (UserAuth::getACLValue("STUDENT_REGISTRATION_WIZARD_READ_RIGHT"))?"false":"true";
        ?>
        
        var cardNav = function(incr){
            var l = Ext.getCmp('card-wizard-panel').getLayout();
            var i = l.activeItem.id.split('card-')[1];
            var next = parseInt(i) + incr;

            l.setActiveItem(next);

            Ext.getCmp('card-prev').setDisabled(next===0);
            Ext.getCmp('card-next').setDisabled(next===2);
            Ext.getCmp('card-next').setDisabled(next===3);
            
            var formCard1 = Ext.getCmp('card-1').getForm();
            var formCard2 = Ext.getCmp('card-2').getForm();

            if (formCard1.isValid() === false){
                l.setActiveItem(1);
            }
            if (formCard1.isValid() === true && formCard2.isValid() === false){
                l.setActiveItem(2);
            }
        };

        function actionSave(){

            var formCard1 = Ext.getCmp('card-1').getForm();
            var formCard2 = Ext.getCmp('card-2').getForm();
            
            var connection = new Ext.data.Connection();
            connection.request({
                url: '/student/jsonsave/'
                ,scope:this
                ,params:{
                    cmd: 'registrationRecord'
                    ,objectId: '<?=generateGuid();?>'
                    ,firstname: formCard1.findField('FIRSTNAME').getValue()
                    ,lastname: formCard1.findField('LASTNAME').getValue()
                    ,gender: formCard1.findField('GENDER').getValue()
                    ,religion: formCard1.findField('RELIGION').getValue()
                    ,ethnic: formCard1.findField('ETHNIC').getValue()
                    ,nationality: formCard1.findField('NATIONALITY').getValue()
                    ,datebirth: formCard1.findField('DATE_BIRTH').getValue().format('Y-m-d')
                    ,birth_place: formCard1.findField('BIRTH_PLACE').getValue()
                    ,address: formCard1.findField('ADDRESS').getValue()

                    ,town_city: formCard1.findField('TOWN_CITY').getValue()

                    ,country_province: formCard1.findField('COUNTRY_PROVINCE').getValue()
                    ,phone: formCard1.findField('PHONE').getValue()
                    ,email: formCard1.findField('EMAIL').getValue()

                    ,campusId: formCard2.findField('CHOOSE_CAMPUS').getValue() 
                    ,gradeId: formCard2.findField('CHOOSE_GRADE').getValue() 
                    ,schoolyearId: formCard2.findField('CHOOSE_SCHOOLYEAR').getValue() 
                    ,classId: formCard2.findField('CHOOSE_GRADE').getValue() 

                    ,trainingId: formCard2.findField('CHOOSE_TRAINING').getValue()
                    ,academicType: academicType
                    ,studentschoolId: formCard2.findField('STUDENT_SCHOOL_ID').getValue()
                    ,transfer: formCard2.findField('TRANSFER').getValue()
                    
                }
                ,method: 'POST'
                ,success: function (result) {
                    <?=camemisPage::setRequestURI();?>
                }
            });
        }
        
        viewport = new Ext.Viewport({
            border: false
            ,items: [{
                layout:'fit'
                ,border: false
                ,items:[{
                    xtype: 'panel'
                    ,border: false
                    ,layout:'card'
                    ,activeItem: 0
                    ,id:'card-wizard-panel'
                    ,title: ''
                    ,items:[{
                        xtype: 'form'
                        ,title: ''
                        ,border: false
                        ,id: 'card-0'
                        ,autoScroll: true
                        ,height: percentHeight(95)
                        ,items:[{
                            title: ''
                            ,border: false
                            ,bodyStyle: 'padding:10px'
                            ,html: '<h1 class="header"><?=MSG_WELCOME_STUDENT_REGISTRATION?><p class="header"><br>3 <?=STEPS?><br><br><?=MSG_NEXT_CONTINUE;?></p></h1>'
                        }]
                    },{
                        xtype: 'form'
                        ,labelWidth: 170
                        ,title: '1/3'
                        ,border: false
                        ,id: 'card-1'
                        ,autoScroll: true
                        ,height: percentHeight(95)
                        ,items:[{
                            title: ''
                            ,border: false
                            ,bodyStyle: 'padding:10px'
                            ,items: <?=$card1Items?>
                        }]
                    },{
                        xtype: 'form'
                        ,labelWidth: 170
                        ,title: '2/3'
                        ,border: false
                        ,id: 'card-2'
                        ,height: percentHeight(95)
                        ,autoScroll: true
                        ,items:[{
                            title: ''
                            ,border: false
                            ,bodyStyle: 'padding:10px'
                            ,items: <?=$card2Items?>
                        }]
                    },{
                        xtype: 'form'
                        ,labelWidth: 170
                        ,title: '3/3'
                        ,border: false
                        ,id: 'card-3'
                        ,height: percentHeight(95)
                        ,autoScroll: true
                        ,items:[{
                            title: ''
                            ,border: false
                            ,bodyStyle: 'padding:10px'
                            ,contentEl:'congratulations'
                            ,tbar:['->','-',{
                                text: '<?=SAVE;?>'
                                ,disabled: <?=$STUDENT_REGISTRATION_EDIT_RIGHT?>
                                ,id: 'SAVE_ID'
                                ,iconCls:'icon-disk'
                                ,handler: function () {
                                    actionSave();
                                }
                            }]
                        }]
                    }]
                    ,tbar: [
                    {
                        text: '<?=REFRESH;?>'
                        ,iconCls:'icon-reload'
                        ,handler: function(){
                            <?=camemisPage::setRequestURI();?>
                        }
                    },'->', {
                        id: 'card-prev'
                        ,text: '&laquo; <?=PREVIOUS;?>'
                        ,handler: cardNav.createDelegate(this, [-1])
                        ,disabled: true
                    },'-',{
                        id: 'card-next'
                        ,disabled: <?=$STUDENT_REGISTRATION_EDIT_RIGHT;?>
                        ,text: '<?=NEXT;?> &raquo;'
                        ,handler: cardNav.createDelegate(this, [1])
                    }]
                }]
            }]
        });
        if(Ext.get('GENERAL_EDUCATION')){
            Ext.get('GENERAL_EDUCATION').on('click', function(e){
                if(Ext.getCmp('GENERAL_EDUCATION').getValue() === true){
                    Ext.getCmp('CHOOSE_GRADE_NAME_ID').show();
                    Ext.getCmp('CHOOSE_TRAINING').setValue('');
                    Ext.getCmp('CHOOSE_TRAINING_NAME_ID').hide(); 
                    Ext.getCmp('CHOOSE_CREDIT_NAME_ID').hide(); 
                }
            });
        }
        if(Ext.get('CREDIT_EDUCATION_SYSTEM')){
            Ext.get('CREDIT_EDUCATION_SYSTEM').on('click', function(e){
                if(Ext.getCmp('CREDIT_EDUCATION_SYSTEM').getValue() === true){
                    Ext.getCmp('CHOOSE_CREDIT_NAME_ID').show();
                    Ext.getCmp('CHOOSE_TRAINING').setValue('');
                    Ext.getCmp('CHOOSE_TRAINING_NAME_ID').hide();
                    Ext.getCmp('CHOOSE_GRADE_NAME_ID').hide();
                }
            });
        }
        if(Ext.get('TRAINING')){
            Ext.get('TRAINING').on('click', function(e){
                if(Ext.getCmp('TRAINING').getValue() === true){
                    Ext.getCmp('CHOOSE_GRADE_NAME_ID').hide();
                    Ext.getCmp('CHOOSE_GRADE').setValue('');
                    Ext.getCmp('CHOOSE_TRAINING_NAME_ID').show();
                    Ext.getCmp('CHOOSE_CREDIT_NAME_ID').hide();
                }
            });
        }
        var comboParent = Ext.getCmp('PROVINCE_ID');
        var comboChild = Ext.getCmp('TWON_ID');
        
        if(comboParent){
            comboParent.on('select', function() {
                comboChild.setValue('');
                comboChild.store.baseParams = {
                    cmd: 'jsonAllLocation'
                    ,parentId: comboParent.getValue()
                };
                comboChild.store.reload();
            });
        }
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>