<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("SCHOOLEVENT", "LIST");
$OBJECT_GRID->setLoadUrl("/schoolevent/jsonload/");
$OBJECT_GRID->setSaveUrl("/schoolevent/jsonsave/");

switch(UserAuth::getUserType()) {
    case "INSTRUCTOR":
    case "TEACHER":
    case "STUDENT":
        $HIDDEN_SHOW_DETAIL = "true";
        $HIDDEN_ADD_ENTRY = "true";
    break;
    default:
        $HIDDEN_SHOW_DETAIL = "false";
        $HIDDEN_ADD_ENTRY = 'false';
        break;
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

Ext.onReady(function() {
    function cssText(v){
        return String.format('<div style=\"font-weight:normal; white-space:normal; color:#333; padding: 10px;\">{0}</div>'
            ,v
        );
    }
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addReadField("name: 'EVENT_NAME', type: 'string'");
    $OBJECT_GRID->addReadField("name: 'START_DATE'");
    $OBJECT_GRID->addReadField("name: 'END_DATE'");
    $OBJECT_GRID->addReadField("name: 'LOCATION'");
    $OBJECT_GRID->addReadField("name: 'REMARK'");
    $OBJECT_GRID->addReadField("name: 'STATUS'");
    $OBJECT_GRID->addReadField("name: 'STATUS_KEY'");
    
    if(UserAuth::isUserTypeAdmin()){
        $OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: 80, renderer:cssText, sortable: true, dataIndex: 'STATUS_KEY'");
    }
    
    $OBJECT_GRID->addColumn("header: '<b>".NAME."</b>', width: 200, sortable: false, renderer:cssText, dataIndex: 'EVENT_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".START_DATE."</b>', width: 110, sortable: false, renderer:cssText, dataIndex: 'START_DATE'");
    $OBJECT_GRID->addColumn("header: '<b>".END_DATE."</b>', width: 110, sortable: false, renderer:cssText, dataIndex: 'END_DATE'");
    $OBJECT_GRID->addColumn("header: '<b>".LOCATION."</b>', width: 300, renderer:cssText, dataIndex: 'END_DATE'");
    $OBJECT_GRID->addColumn("header: '<b>".DESCRIPTION."</b>', width: 300, renderer:cssText, dataIndex: 'REMARK'");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'REFRESH_ID'
            ,text: '".REFRESH."'
            ,iconCls:'icon-reload'
            ,scope:this
            ,disabled: false
            ,handler: function(){
               Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
            }
        }]);
    ");

    //if (UserAuth::getACLValue("SCHOOL_SETTING_EDIT_RIGHT"))
    $OBJECT_GRID->addTBarItems("
        tbar.add(['-',{
            id: 'CREATE_ITEM_ID'
            ,hidden: ".$HIDDEN_ADD_ENTRY."
            ,text: '".ADD_ENTRY."'
            ,iconCls:'icon-application_form_add'
            ,scope:this
            ,handler: this.onAddItem
        }]);
    ");
    
    $OBJECT_GRID->setSaveParams("
        cmd: 'addObject'
        ,eventType: 1
        ,schoolyearId: '".$this->schoolyearId."'
    ");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add(['-',{
            id: 'DETAIL_INFORMATION_ID'
            ,text: '".SHOW_DETAIL."'
            ,hidden: ".$HIDDEN_SHOW_DETAIL."
            ,iconCls:'icon-magnifier'
            ,scope:this
            ,handler: function(){
                var sm = this.getSelectionModel();
                var record = sm.getSelected();
                if(record){
                    var objectId = record.data.ID;
                    clickOpenPage('content',record.data.EVENT_NAME, '".$this->URL_SHOWITEM."&objectId=' + objectId);
                }else{
                    ".camemisPage::alertPleaseSelect()."
                }
            }
        }]);
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,eventType: 1
        ,schoolyearId: '".$this->schoolyearId."'
        ,cmd: 'allSchoolevents'
    ";
    
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,xtype: 'panel'
            ,layout: 'card'
            ,id: 'content'
            ,activeItem: 0
            ,items:[{
                border: false
                ,title: ''
                ,layout: 'fit'
                ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
            }]
        }]
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>