<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_GRID = new CamemisGrid("SCHOOLEVENT", "LIST");
$OBJECT_GRID->setLoadUrl("/schoolevent/jsonload/");
$OBJECT_GRID->setSaveUrl("/schoolevent/jsonsave/");

$OBJECT_TREE = new CamemisTree("SUBJECT", false);
$OBJECT_TREE->setURL('/subject/jsontree/');
$OBJECT_TREE->setSaveUrl('/subject/jsonsave/');

$OBJECT_FORM = new CamemisForm("SCHOOLEVENT");
$OBJECT_FORM->setLoadUrl('/schoolevent/jsonload/');
$OBJECT_FORM->setSaveUrl('/schoolevent/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<div id="initContentWest" class="x-hide-display" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>
</div>
<div id="initContentSouth" class="x-hide-display" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>
</div>
<script>

var subjectId;
var academicId;
var assignmentId;
var chooseText;

Ext.apply(Ext.form.VTypes, {
    daterange : function(val, field) {
        var date = field.parseDate(val);

        if(!date){
            return false;
        }
        if (field.startDateField && (!this.dateRangeMax || (date.getTime() != this.dateRangeMax.getTime()))) {
            var start = Ext.getCmp(field.startDateField);
            start.setMaxValue(date);
            start.validate();
            this.dateRangeMax = date;
        }
        else if (field.endDateField && (!this.dateRangeMin || (date.getTime() != this.dateRangeMin.getTime()))) {
            var end = Ext.getCmp(field.endDateField);
            end.setMinValue(date);
            end.validate();
            this.dateRangeMin = date;
        }
        return true;
    }
});

Ext.onReady(function() {
    
    <?
    /**
     * Extjs: s.gif
     */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    ///////////////////////////////////////////////////////
    // Subject-Assignment...
    ///////////////////////////////////////////////////////
    $OBJECT_TREE->isAsyncTreeNode = false;

    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    
    $OBJECT_TREE->isTreeExpand = false;
    $OBJECT_TREE->setBaseParams("
        cmd: 'treeGradeSubjectAssignments'
        ,gradeId: '".$this->gradeId."'
        ,schoolyearId: '".$this->schoolyearId."'
    ");
    
    $OBJECT_TREE->isOnClickContextMenu = false;
    $OBJECT_TREE->renderJS();
    
    $OBJECT_GRID->addReadField("name: 'CLASS_NAME', type: 'string'");
    $OBJECT_GRID->addReadField("name: 'DATE'");
    $OBJECT_GRID->addReadField("name: 'TIME'");
    $OBJECT_GRID->addReadField("name: 'REMARK'");

    $OBJECT_GRID->addColumn("header: '" . GRADE_CLASS . "', width: 120, menuDisabled : true, sortable: false, dataIndex: 'CLASS_NAME'");
    $OBJECT_GRID->addColumn("header: '" . DATE . "', width: 160, menuDisabled : true, sortable: false, dataIndex: 'DATE'");
    $OBJECT_GRID->addColumn("header: '" . TIME . "', width: 110, menuDisabled : true, sortable: false, dataIndex: 'TIME'");
    $OBJECT_GRID->addColumn("header: '" . NOTES . "', width: 250, menuDisabled : true, sortable: false, dataIndex: 'REMARK'");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonTestSchedule'
        ,schoolyearId: '$this->schoolyearId'
        ,gradeId: '$this->gradeId'
    ";
    
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->loadMask = false;
    $OBJECT_GRID->renderJS();
    
    $DATE_ITEM = "{
        title: '" . DATE . "'
        ,width: 550
        ,layout: 'form'
        ,bodyStyle: 'padding:10px'
        ,style: 'padding-bottom: 5px'
        ,items:[{
            xtype: 'compositefield'
            ,fieldLabel: '" . START_DATE . "'
            ,combineErrors: false
            ,items: [{
               width: percentWidth(20)
               ,name: 'START_DATE'
                ,xtype: 'datefield'
               ,id: 'START_DATE'
                ,vtype: 'daterange'
                ,endDateField: 'END_DATE'
                ,format: '" . setExtDatafieldFormat() . "'
                ,allowBlank: false
            },{
                name : 'START_HOUR'
                ,xtype: 'textfield'
                ,width: 80
               ,value: '00:00'
                ,allowBlank: false
           }]
        },{
            xtype: 'compositefield'
            ,fieldLabel: '" . END_DATE . "'
            ,combineErrors: false
            ,items: [{
                width: percentWidth(20)
                ,name: 'END_DATE'
                ,xtype: 'datefield'
                ,id: 'END_DATE'
                ,vtype: 'daterange'
                ,format: '" . setExtDatafieldFormat() . "'
                ,startDateField: 'START_DATE'
                ,allowBlank: false
            },{
                name : 'END_HOUR'
                ,xtype: 'textfield'
                ,width: 80
                ,value: '00:00'
                ,allowBlank: false
            }]
        }]
    }";
    
    $REMARK_ITEM = "{
        title: '" . NOTES . "'
        ,width: 550
        ,layout: 'fit'
        ,bodyStyle: 'padding:10px'
        ,items:[{
            ".CamemisField::Textarea("REMARK", false, 120)."
        }]
    }";
    
    $items = "
    border: false
    ,id: 'FORM_ITEMS'
    ,autoScroll: true
    ,bodyStyle: 'padding:0px'
    ,items: [
        " . $DATE_ITEM . "
        ," . $REMARK_ITEM . "
    ]
    ";
    
    $OBJECT_FORM->addObjectItems($items);

    $OBJECT_FORM->setLoadParams("
        cmd: 'jsonLaodTestSchedule'
        ,academicId: academicId
        ,subjectId: subjectId
        ,assignmentId: assignmentId
        ,gradeId: '".$this->gradeId."'
        ,schoolyearId: '".$this->schoolyearId."'
    ");
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'jsonActionTestSchedule'
        ,academicId: academicId
        ,subjectId: subjectId
        ,assignmentId: assignmentId
        ,gradeId: '".$this->gradeId."'
        ,schoolyearId: '".$this->schoolyearId."'
    ");
    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){Ext.getCmp('south').getLayout().setActiveItem(0);}
    ");
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    
    $OBJECT_FORM->setonEmbeddedEvents("
        Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
    ");
    
    $OBJECT_FORM->isObjectDefaultOnLoad = false;
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: false
                ,split: false
            }
            ,items: [{
               	region:'west'
                ,id: 'WEST_ID'
               	,title: '<?=TEST_SCHEDULE;?>'
                ,margins: '3 3 3 3'
                ,cmargins: '3 3 3 3'
                ,autoScroll: true
                ,width:350
                ,minSize:350
                ,maxSize:350
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
            },{
               	collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,bodyStyle: 'padding:0px'
                ,items:[{
                    layout: 'fit'
                    ,border: false
                    ,contentEl: 'initContentWest'
                },{
                    layout:'border'
                    ,border: false
                    ,defaults: {
                        collapsible: false
                        ,split: true
                    },
                    items: [{
                        title: ''
                        ,region: 'south'
                        ,id: 'south'
                        ,layout: 'card'
                        ,activeItem: 0
                        ,height: percentHeight(50)
                        ,minSize: percentHeight(50)
                        ,maxSize: percentHeight(50)
                        ,margins: '0 3 3 3'
                        ,items:[{
                            layout: 'fit'
                            ,border: false
                            ,contentEl: 'initContentSouth'
                        },{
                            layout: 'fit'
                            ,border: false
                            ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                        }]
                    },{
                        title: ''
                        ,id: 'east_center'
                        ,collapsible: false
                        ,region:'center'
                        ,margins: '3 3 0 3'
                        ,items:[{
                            title: chooseText
                            ,border: false
                            ,layout: 'fit'
                            ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}] 
                        }]
                        ,tbar:[{
                            text: '<?=CANCEL?>'
                            ,id: 'GRID_CANCEL_ID'
                            ,iconCls:'icon-cancel'
                            ,handler: function(){Ext.getCmp('center').getLayout().setActiveItem(0);}
                        }]
                    }]
                }]
            }]
        }]
    });
    var myTree = <? echo $OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('click', function(node, e){
        
        chooseText = node.text;
        subjectId = node.attributes.subjectId;
        assignmentId = node.attributes.mappingId;
        Ext.getCmp('center').getLayout().setActiveItem(1);
        Ext.getCmp('south').getLayout().setActiveItem(0);
        var myGrid = Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>');
        myGrid.store.baseParams = {
            start:0
            ,limit:100
            ,cmd: 'jsonTestSchedule'
            ,assignmentId: assignmentId
            ,subjectId: subjectId
            ,schoolyearId: '<?=$this->schoolyearId?>'
            ,gradeId: '<?=$this->gradeId?>'
        };
        
        myGrid.store.load();
        myGrid.on('cellclick', function(grid, rowIndex, e){
           
            var record = grid.store.getAt(rowIndex);
            academicId = record.data.ID;
            Ext.getCmp('south').getLayout().setActiveItem(1);
            Ext.getCmp('<?=$OBJECT_FORM->getObjectId()?>').load({
                url: '/schoolevent/jsonload/'
                ,params: {
                    cmd: 'jsonLoadTestSchedule'
                    ,schoolyearId: '<?=$this->schoolyearId?>'
                    ,academicId: academicId
                    ,assignmentId: assignmentId
                    ,subjectId: subjectId
                    ,gradeId: '<?=$this->gradeId?>'
                }
            });
        });
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>