<?
///////////////////////////////////////////////////////////
//@Chung veng Web Developer
//Date: 22.06.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("CLUB", "LIST");
$OBJECT_GRID->setLoadUrl("/club/jsonload/");
$OBJECT_GRID->setSaveUrl("/club/jsonsave/");
$columndata = Utiles::getGridColumnData("CLUB_LIST_ID");

switch(UserAuth::getUserType()) {
    case "INSTRUCTOR":
    case "TEACHER":
    case "STUDENT":
        $HIDDEN_SHOW_DETAIL = "true";
        $HIDDEN_ADD_ENTRY = "true";
    break;
    default:
        $HIDDEN_SHOW_DETAIL = "false";
        $HIDDEN_ADD_ENTRY = 'false';
        break;
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

Ext.onReady(function() {
    function cssText(v){
        return String.format('<div style=\"font-weight:normal; white-space:normal; color:#333; padding: 10px;\">{0}</div>'
            ,v
        );
    }
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
	
    $OBJECT_GRID->addCellRenderer("
        function renderText(v, p, record, rowIndex){
            var str = '<span class=spanText>' + v + '</span>';
            return str;
        }
    ");
    
    $OBJECT_GRID->addReadField("name: 'START_DATE'");
    $OBJECT_GRID->addReadField("name: 'END_DATE'");
    $OBJECT_GRID->addReadField("name: 'NAME'");
    $OBJECT_GRID->addReadField("name: 'STATUS'");
    $OBJECT_GRID->addReadField("name: 'STATUS_KEY'");
    $OBJECT_GRID->addReadField("name: 'REMARK'");
    
    if(UserAuth::isUserTypeAdmin()){
        $OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: 80, hidden:".checkColHidden(1, $columndata).", renderer:cssText, sortable: true, dataIndex: 'STATUS_KEY'");
    }
  
    $OBJECT_GRID->addColumn("header: '<b>".NAME."</b>', width: 200, hidden:".checkColHidden(2, $columndata).", sortable: false, renderer:cssText, dataIndex: 'NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".START_DATE."</b>', width: 110, hidden:".checkColHidden(3, $columndata).", sortable: false, renderer:cssText, dataIndex: 'START_DATE'");
    $OBJECT_GRID->addColumn("header: '<b>".END_DATE."</b>', width: 110, hidden:".checkColHidden(4, $columndata).", sortable: false, renderer:cssText, dataIndex: 'END_DATE'");
    $OBJECT_GRID->addColumn("header: '<b>".REMARK."</b>', width: 300, hidden:".checkColHidden(5, $columndata).", renderer:cssText, dataIndex: 'REMARK'");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'REFRESH_ID'
            ,text: '".REFRESH."'
            ,iconCls:'icon-reload'
            ,scope:this
            ,disabled: false
            ,handler: function(){
               Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
            }
        }]);
    ");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'CREATE_ITEM_ID'
            ,hidden: ".$HIDDEN_ADD_ENTRY."
            ,text: '".ADD_ENTRY."'
            ,iconCls:'icon-application_form_add'
            ,scope:this
            ,handler: this.onAddItem
        }]);
    ");
    
    $OBJECT_GRID->setSaveParams("
        cmd: 'addObject'
        ,objectId: '".$this->objectId."'
    ");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'DETAIL_INFORMATION_ID'
            ,text: '".SHOW_DETAIL."'
            ,hidden: ".$HIDDEN_SHOW_DETAIL."
            ,iconCls:'icon-magnifier'
            ,scope:this
            ,handler: function(){
                var sm = this.getSelectionModel();
                var record = sm.getSelected();
                if(record){
                    var objectId = record.data.ID;
                    clickOpenPage('content',record.data.NAME, '".$this->URL_CLUB_SHOWITEM."&objectId=' + objectId);
                }else{
                    ".camemisPage::alertPleaseSelect()."
                }
            }
        }]);
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,objectId: '".$this->objectId."'
        ,cmd: 'allClubevents'
    ";
    
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,xtype: 'panel'
            ,layout: 'card'
            ,id: 'content'
            ,activeItem: 0
            ,items:[{
                border: false
                ,title: ''
                ,layout: 'fit'
                ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
            }]
        }]
    });
    Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>