<?
///////////////////////////////////////////////////////////
//@Chung veng Web Developer
//Date: 22.06.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("CLUB");
$OBJECT_FORM->setLoadUrl("/club/jsonload/");
$OBJECT_FORM->setSaveUrl("/club/jsonsave/");

if(!$this->facette) {header("Location: /main/permission/");}
$STATUS = $this->facette->STATUS;

$removeStatus = true;
if ($STATUS ==1){
    $removeStatus = false;
}else{
    $removeStatus = true;
}   

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    <? camemisPage::ExtformVTypes(); ?>
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width:550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [
                    {".CamemisField::Textfield("NAME", "NAME", NAME)."}
                    ,{".CamemisField::StartDatefieldRange("START_DATE", START_DATE, "END_DATE", true)."}
                    ,{".CamemisField::EndDatefieldRange("END_DATE", END_DATE, "START_DATE", true)."}
                    
                ]
            }]
        }
        ";
        
        $REMARK = "
        {
            title: '".REMARK."'
            ,collapsible: true
            ,collapsed: false
            ,layout: 'fit'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,bodyStyle: 'padding:5px'
            ,width:550
            ,items: [{".CamemisField::Textarea("REMARK", REMARK, 100)."}]
        }
        ";
        
        switch(UserAuth::getUserType()){
            case "INSTRUCTOR":
            case "TEACHER":
                $FORM_ITEMS = "[
                    ".$DETAIL_INFORMATION."                  
                    ,".$REMARK."
                ]";
            break;
            default:
                $FORM_ITEMS = "[
                    ".$DETAIL_INFORMATION."
                    ,".$REMARK."                  
                ]";
            break;
        }
        
        $ITEMS = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: ".$FORM_ITEMS."
        ";
        
        $OBJECT_FORM->addObjectItems($ITEMS);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);
                //window.parent.Ext.getCmp('CLUB_LIST_ID').store.reload();
            }
        ");
 
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormRemoveObject($removeStatus));
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease());
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
        
        $OBJECT_FORM->setLoadParams("cmd:'loadObject',objectId: '".$this->objectId."'");

        $OBJECT_FORM->setSaveParams("
            cmd: 'jsonSaveEvent'
            ,objectId: '".$this->objectId."'
        ");
           
        $OBJECT_FORM->setReleaseParams("cmd: 'releaseObjectEvent',objectId: '".$this->objectId."'");

        $OBJECT_FORM->setonEmbeddedEvents("
            if(window.parent.Ext.getCmp('CLUB_LIST_ID'))
            window.parent.Ext.getCmp('CLUB_LIST_ID').store.reload();
            var result = Ext.util.JSON.decode(action.response.responseText);
            var objectId = result.objectId;
            window.location='".$_SERVER["REQUEST_URI"]."&objectId='+objectId;
        ");
        
        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            if(window.parent.Ext.getCmp('CLUB_LIST_ID'))
            window.parent.Ext.getCmp('CLUB_LIST_ID').store.reload();
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");
        $OBJECT_FORM->setRemoveParams("
            cmd: 'removeObject'
            ,objectId: '".$this->objectId."'
        ");   

        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            if(window.parent.Ext.getCmp('CLUB_LIST_ID'))
            window.parent.Ext.getCmp('CLUB_LIST_ID').store.reload();
            window.parent.Ext.getCmp('content').getLayout().setActiveItem(0);
           
        ");

        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 150;
        $OBJECT_FORM->renderJS();
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,id: 'content'
                ,layout: 'card'
                ,activeItem: 0
                ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>