<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<style>
    .x-vr-tab-panel-bwrap {
        background: none repeat scroll 0 0 <?=CamemisPage::userBgColor();?>;
        border-left: 1px solid #99BBE8;
        float: right;
        padding: 3px;
    }
</style>
<script>

    Ext.onReady(function() {

        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $MAIN_CONTENT = "{
            title: '".MY_SCHOOL."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'MY_SCHOOL', url: '/school/showitem/?camIds=".$this->urlEncryp->encryptedGet("target=main_content")."'})]
        }";
        $PENEL_ITEMS[] = $MAIN_CONTENT;
        
        $SETTINGS = "{
            title: '".SETTINGS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SETTINGS', url: '/school/showitem/?camIds=".$this->urlEncryp->encryptedGet("target=settings")."'})]
        }";
        
        $PENEL_ITEMS[] = $SETTINGS;
        
        $SECURITY_SETTINGS = "{
            title: '".SECURITY_SETTINGS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SECURITY_SETTINGS', url: '/school/showitem/?camIds=".$this->urlEncryp->encryptedGet("target=security")."'})]
        }";
        $PENEL_ITEMS[] = $SECURITY_SETTINGS;
        
        $BACK_UP = "{
            title: '".BACK_UP." - Recovery'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'BACK_UP', url: '/school/showitem/?camIds=".$this->urlEncryp->encryptedGet("target=back_up")."'})]
        }";
        $PENEL_ITEMS[] = $BACK_UP;
        
        $PRIVACY = "{
            title: '".PRIVACY."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'PRIVACY', url: 'http://camemis.com.kh/privacy'})]
        }";
        $PENEL_ITEMS[] = $PRIVACY;
        
        $TERM_OF_SERVICES = "{
            title: '".TERM_OF_SERVICES."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'TERM_OF_SERVICES', url: 'http://camemis.com.kh/terms-of-services?limitstart=0'})]
        }";
        $PENEL_ITEMS[] = $TERM_OF_SERVICES;
        
        $NOTIFICATION = "{
            title: '".NOTIFICATION."'
            ,layout: 'fit'
            ,disabled:true
            ,items:[new Ext.ux.IFrameComponent({ id: 'NOTIFICATION', url: ''})]
        }";
        $PENEL_ITEMS[] = $NOTIFICATION;
        
        $UPGRADE = "{
            title: 'CAMEMIS Upgrade'
            ,layout: 'fit'
            ,disabled:true
            ,items:[new Ext.ux.IFrameComponent({ id: 'UPGRADE', url: ''})]
        }";
        $PENEL_ITEMS[] = $UPGRADE;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'vrtabpanel'
                ,activeTab: 0
                ,tabMarginTop:100
                ,enableTabScroll:true       
                ,defaults: {autoScroll:true}
                ,items:<?=$CHOOSE_ITEMS?>
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>