<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("SCHOOL");
$OBJECT_FORM->setSaveUrl("/school/jsonsave/");
$OBJECT_FORM->setLoadUrl("/school/jsonload/");

$target = isset($_GET["target"])?strtoupper(addText($_GET["target"])):"";

if(!$target){
    header("Location: /main/permission/");
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<script>
Ext.onReady(function() {
    
    <?
    
    camemisPage::showBlob();
    camemisPage::deleteBlob();
    camemisPage::uploadBlob();
    
    /**
     * Extjs: s.gif
     */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    ///////////////////////////////////////////////////////
    // Form: Schoolsetting...
    ///////////////////////////////////////////////////////
    $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '".$this->objectId."'");
    $OBJECT_FORM->setSaveParams("
        cmd: 'updateObject'
        ,objectId: '".$this->objectId."'
    ");
    $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '".$this->objectId."'");
    
    $DETAIL_INFORMATION = "
    {
        title: '".NAME."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{".CamemisField::Textarea("NAME", false,30)."}]    
            }]
        }]
    }
    ";
    
    $SHORT = "
    {
        title: '".SHORT."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [{
                xtype: 'textfield'
                ,fieldLabel: '".NAME."'
                ,width:250
                ,name: 'SHORT'
                ,enableKeyEvents: true
                ,listeners: {
                    'keyup': {
                        fn: function(t){
                            var v = t.getValue();
                            if(v.length>11){
                                ".CamemisPage::alertMSG(STATUS,EXCEED_11_CHARACTERS, false)."
                                Ext.getCmp('SIMPLE_SAVE_ID').disable();
                            }else{
                                Ext.getCmp('SIMPLE_SAVE_ID').enable();
                            }
                        }
                    }
                }
            }]
        }]
    }
    ";

    $SCHOOL_LOGO_ITEMS = "{
        title: '" . SCHOOL_LOGO . "'
        ,height: 270
        ,collapsible: true
        ,collapsed: false
        ,layout: 'fit'
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items: [new Ext.ux.IFrameComponent({ id: 'SCHOOL_LOGO', url:'/dataset/image/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$this->objectId."&objectName=SCHOOL_LOGO")."'})]
    }";
    
    $CONTACT_INFORMATION = "
    {
        title: '".CONTACT_INFORMATION."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Textfield("PHONE_ID","PHONE",PHONE)."}
                ,{".CamemisField::Textfield("FAX_ID","FAX",FAX)."}
                ,{".CamemisField::Textfield("EMAIL_ID","EMAIL",EMAIL)."}
                ,{".CamemisField::Textfield("WEBSITE","WEBSITE",WEBSITE)."}
            ]
        }]
    }
    ";
    
    $EMBEDDED_URL = "
    {
        title: '".EMBEDDED_CAMEMIS_URL_FOR_EDUCATION_INSTITUTION."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,height: 100
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'background:#FFF; padding:3px'
            ,items: [{".CamemisField::Textarea("EMBEDDED_URL", false,80, true)."}]
        }]
    }
    ";
    
    $SCHOOL_TIMEZONE = "
    {
        title: '".SCHOOL_TIMEZONE."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,autoHeight: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::comboTimezone(false, false)."}
            ]
        }]
    }
    ";
    
    $ADDRESS = "
    {
        title: '".ADDRESS."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,height: 100
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'background:#FFF; padding:3px'
            ,items: [{".CamemisField::Textarea("ADDRESS", false,120)."}]
        }]
    }
    ";
    
    $EMERGENCY_CALL = "
    {
        title: '".EMERGENCY_CALL."'
        ,collapsible: true
        ,collapsed: true
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF; padding:3px'
            ,items: [
                {".CamemisField::HTML("EMERGENCY_CALL",350,false)."}
            ]
        }]
    }
    ";

    $DATA_PRIVACY = "
    {
        title: ''
        ,collapsible: true
        ,collapsed: true
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'fit'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'background:#FFF; padding:3px'
            ,items: [
                {".CamemisField::HTML("EMERGENCY_CALL",350,false)."}
            ]
        }]
    }
    ";
    
    $CAMEMIS_FORMAT = "
    {
        title: '".CAMEMIS_FORMAT."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout:'fit'
            ,bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px'
            ,border: false
            ,autoHeight: true
            ,items:[{
                xtype: 'tabpanel'
                ,tabPosition: 'top'
                ,plain:true
                ,activeTab: 0
                ,enableTabScroll:true
                ,items:[{
                    title:'".CAMEMIS_DATE_FORMAT."'
                    ,items:[{
                        layout: 'form'
                        ,border: false
                        ,height: 170
                        ,bodyStyle: 'padding:10px'
                        ,items:[
                            {".CamemisField::Radio("DATEFORMAT_1", "SYSTEM_DATE_FORMAT", "dd.mm.YYYY", "DD.MM.YYYY", true)."}
                            ,{".CamemisField::Radio("DATEFORMAT_2", "SYSTEM_DATE_FORMAT", "dd-mm-YYYY", "DD-MM-YYYY", false)."}
                            ,{".CamemisField::Radio("DATEFORMAT_3", "SYSTEM_DATE_FORMAT", "dd/mm/YYYY", "DD/MM/YYYY", false)."}
                            ,{".CamemisField::Radio("DATEFORMAT_4", "SYSTEM_DATE_FORMAT", "mm.dd.YYYY", "MM.DD.YYYY", true)."}
                            ,{".CamemisField::Radio("DATEFORMAT_5", "SYSTEM_DATE_FORMAT", "mm-dd-YYYY", "MM-DD-YYYY", false)."}
                            ,{".CamemisField::Radio("DATEFORMAT_6", "SYSTEM_DATE_FORMAT", "mm/dd/YYYY", "MM/DD/YYYY", false)."}
                        ]
                    }]
                },{
                    title:'".CAMEMIS_NUMBER_FORMAT."'
                    ,items:[{
                        layout: 'form'
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle: 'padding:10px'
                        ,items:[
                            {".CamemisField::Radio("DATE_FORMAT_1", "CAMEMIS_DATE_FORMAT", "123.00", "0", true)."}
                            ,{".CamemisField::Radio("DATE_FORMAT_2", "CAMEMIS_DATE_FORMAT", "123,00", "1", false)."}
                        ]
                    }]
                },{
                    title:'".CAMEMIS_NAME_FORMAT."'
                    ,items:[{
                        layout: 'form'
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle: 'padding:10px'
                        ,items:[
                            {".CamemisField::Combo('DISPLAY_POSITION_LASTNAME', PLEASE_CHOOSE,"[[0, '" . LASTNAME . ", " . FIRSTNAME . "'],[2, '" . FIRSTNAME . ", " . LASTNAME . "']]", false, false, false, false)."}
                        ]
                    }]
                },{
                    title:'".CAMEMIS_ROUND_FORMAT."'
                    ,items:[{
                        layout: 'form'
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle: 'padding:10px'
                        ,items:[
                            {".CamemisField::Numberfield("DECIMAL_PLACES", "DECIMAL_PLACES", PLEASE_CHOOSE, false, false, false)."}   
                        ]
                    }]
                },{
                    title:'".CAMEMIS_CURRENCY_FORMAT."'
                    ,items:[{
                        layout: 'form'
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle: 'padding:10px'
                        ,items:[
                            {".CamemisField::ComboCurrency()."}
                        ]
                    }]
                },{
                    title:'".SCHEDULE_DISPLAY."'
                    ,items:[{
                        layout: 'form'
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle: 'padding:10px'
                        ,items:[
                            {".CamemisField::Combo('SUBJECT_DISPLAY', SUBJECT_DISPLAY,"[[0, '" . SUBJECT . " - " . NAME . "'],[1, '" . SUBJECT . " - " . SHORT . "']]", false, false, false, false)."}
                            ,{".CamemisField::Combo('ROOM_DISPLAY', ROOM_DISPLAY,"[[0, '" . ROOM . " - " . NAME . "'],[1, '" . ROOM . " - " . SHORT . "']]", false, false, false, false)."}
                        ]
                    }]
                },{
                    title:'".SORT_DESCENDING."'
                    ,items:[{
                        layout: 'form'
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle: 'padding:10px'
                        ,items:[
                            {".CamemisField::Combo('SORT_DISPLAY', PLEASE_CHOOSE,"[[0, '" . STUDENT_SCHOOL_ID . "'],[1, '" . LASTNAME . "'],[2, '" . FIRSTNAME . "']]", false, false, false, false)."}
                        ]
                    }]
                }]
            }]
        }]
    }
    ";

    //@Math Man 25.12.2013
    $CAMEMIS_NOTIFICATION = "
    {
    title: '".NOTIFICATION."'
    ,collapsible: true
    ,collapsed: false
    ,autoHeight: true
    ,style: 'padding-bottom: 5px'
    ,width: 550
    ,items:[{
        layout:'fit'
        ,bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px'
        ,border: false
        ,autoHeight: true
        ,items:[{
            xtype: 'tabpanel'
            ,tabPosition: 'top'
            ,plain:true
            ,activeTab: 0
            ,enableTabScroll:true
            ,items:[{
                title:'".EMAIL."'
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle: 'padding:10px'
                    ,items:[
                        {".CamemisField::EMailfield('SMS_DISPLAY', EMAIL)."}
                        ,{".CamemisField::Textfield('SALUTATION_ID', 'SALUTATION_EMAIL', SALUTATION)."}
                        ,{".CamemisField::Textarea('SIGNATURE_EMAIL', SIGNATURE, '68')."}
                    ]
                }]
            },{
                title: '".ACCOUNT_CREATE_NOTIFICATION."'
                ,autoHeight: true
                ,style: 'padding-bottom: 5px'
                ,items: [{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle: 'padding:10px'
                    ,items: [
                        {".CamemisField::Textfield('ACCOUNT_CREATE_SUBJECT_ID', 'ACCOUNT_CREATE_SUBJECT', SUBJECT_EMAIL)."}
                        ,{".CamemisField::Textarea('ACCOUNT_CREATE_NOTIFICATION', CONTENT, '68')."}
                    ]
                }]
            },{
                title: '".FORGET_PASSWORD_NOTIFICATION."'
                ,autoHeight: true
                ,items: [{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle: 'padding:10px'
                    ,items: [
                        {".CamemisField::Textfield('FORGET_PASSWORD_SUBJECT_ID', 'FORGET_PASSWORD_SUBJECT', SUBJECT_EMAIL)."}
                        ,{".CamemisField::Textarea('FORGET_PASSWORD_NOTIFICATION', CONTENT, '68')."}
                    ]
                }]
            }]
        }]
    }]
    }
    ";
    //////////////////////

    $PROGRAMM_OPTIONS_ITEMS = "[";
        $PROGRAMM_OPTIONS_ITEMS .= "{".CamemisField::Checkbox("ENABLE_ITEMS_BY_DEFAULT", "ENABLE_ITEMS_BY_DEFAULT", ENABLE_ITEMS_BY_DEFAULT, false, true)."}";
        $PROGRAMM_OPTIONS_ITEMS .= ",{border: false,style: 'padding-bottom: 5px'}";
        $PROGRAMM_OPTIONS_ITEMS .= ",{".CamemisField::Checkbox("SET_DEFAULT_PASSWORD", "SET_DEFAULT_PASSWORD", SET_DEFAULT_PASSWORD, false, true)."}";
        $PROGRAMM_OPTIONS_ITEMS .= ",{border: false,style: 'padding-bottom: 5px'}";
        $PROGRAMM_OPTIONS_ITEMS .= ",{".CamemisField::Checkbox("ACTIVATE_SMS_NOTIFICATION_AUTO", "ACTIVATE_SMS_NOTIFICATION_AUTO", ACTIVATE_SMS_NOTIFICATION_AUTOMATICALLY, false, false)."}";
        $PROGRAMM_OPTIONS_ITEMS .= ",{border: false,style: 'padding-bottom: 5px'}";
        $PROGRAMM_OPTIONS_ITEMS .= ",{".CamemisField::Checkbox("MULTI_BRANCH_OFFICE", "MULTI_BRANCH_OFFICE", MULTIPLE_LOCATIONS, false, true)."}";
        $PROGRAMM_OPTIONS_ITEMS .= ",{border: false,style: 'padding-bottom: 5px'}";
    $PROGRAMM_OPTIONS_ITEMS .= "]";
    
    $PROGRAMM_OPTIONS = "
    {
        title: '".PROGRAM_OPTIONS."'
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,bodyStyle: 'padding:10px'
            ,items: ".$PROGRAMM_OPTIONS_ITEMS."
        }]
    }
    ";
    
    $EDUCATION_SYSTEM = "
    {
        title: '".EDUCATION_SYSTEM."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Checkbox("GENERAL_EDUCATION", "GENERAL_EDUCATION", "".GENERAL_EDUCATION." (Display)", false, false)."}
                ,{".CamemisField::Checkbox("TRAINING_PROGRAMS", "TRAINING_PROGRAMS", "".TRAINING_PROGRAMS." (Display)", false, false)."}
            ]
        }]
    }
    ";
    
    $SUB_GENERAL_EDUCATION = "
    {
        title: '".GENERAL_EDUCATION."'
        ,id:'SUB_GENERAL_EDUCATION'
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,autoHeight: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Checkbox("TRADITIONAL_EDUCATION_SYSTEM", "TRADITIONAL_EDUCATION_SYSTEM", TRADITIONAL_EDUCATION_SYSTEM." (Display)", false,false)."}
                ,{".CamemisField::Checkbox("CREDIT_EDUCATION_SYSTEM", "CREDIT_EDUCATION_SYSTEM", CREDIT_EDUCATION_SYSTEM." (Display)", false, false)."}
            ]
        }]
    }
    ";
    
    $WORKING_DAYS = "
    {
        title: '".WORKING_DAYS."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,autoHeight: true
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Checkbox("MO","MO", MONDAY, 1, false)."}
                ,{".CamemisField::Checkbox("TU","TU", TUESDAY, 1, false)."}
                ,{".CamemisField::Checkbox("WE","WE", WEDNESDAY, 1, false)."}
                ,{".CamemisField::Checkbox("TH","TH", THURSDAY, 1, false)."}
                ,{".CamemisField::Checkbox("FR","FR", FRIDAY, 1, false)."}
                ,{".CamemisField::Checkbox("SA","SA", SATURDAY, 1, false)."}
                ,{".CamemisField::Checkbox("SU","SU", SUNDAY, 1, false)."}
            ]
        }]
    }
    ";
    
    $CAMEMIS_EDITION_CODE_ID = "
    {
        title: '".CAMEMIS_EDITION_CODE_ID."'
        ,collapsible: true
        ,collapsed: false
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Displayfield("MODUL_KEY", CAMEMIS_EDITION_CODE_ID_INFO,false)."}
            ]
        }]
    }
    ";
    
    $SCHOOL_LETTER_HEADER = "
    {
        title: '".SCHOOL_LETTER_HEADER."'
        ,collapsible: true
        ,collapsed: true
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,height: 100
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'background:#FFF; padding:3px'
            ,items: [{".CamemisField::Textarea("SCHOOL_LETTER_HEADER", false,120)."}]
        }]
    }
    ";
    
    $SCHOOL_LETTER_FOOTER = "
    {
        title: '".SCHOOL_LETTER_FOOTER."'
        ,collapsible: true
        ,collapsed: true
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,height: 100
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'background:#FFF; padding:3px'
            ,items: [{".CamemisField::Textarea("SCHOOL_LETTER_FOOTER", false,120)."}]
        }]
    }
    ";
    
    $ACCOUNT_POLICY = "
    {
        title: '".ACCOUNT_POLICY."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,height: 100
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Numberfield("ACLL", "ACLL", ACCOUNT_LOCKOUT_LOGIN, false, false, false)."}  
                ,{".CamemisField::Numberfield("ALD", "ALD", ACCOUNT_LOCKOUT_DURATION, false, false, false)."}   
            ]
        }]
    }";
    
    $PASSWORD_POLICY = "
    {
        title: '".PASSWORD_POLICY."'
        ,collapsible: true
        ,collapsed: false
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,height: 100
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Checkbox("PMCR","PMCR", PASSWORD_MUST_MEET_COMPLEXITY_REQUIREMENTS, 1, false)."}
                ,{".CamemisField::Numberfield("MAXPA", "MAXPA", MAXIMUM_PASSWORD_AGE, false, false, false)."}   
                ,{".CamemisField::Numberfield("MINPA", "MINPA", MINIMUM_PASSWORD_AGE, false, false, false)."}   
                ,{".CamemisField::Numberfield("MINPL", "MINPL", MINIMUM_PASSWORD_LENGTH, false, false, false)."}   
            ]
        }]
    }";
    
    $BACK_UP = "
    {
        title: ''
        ,border:false
        ,autoHeight: true
        ,width: 550
        ,height: 100
        ,items:[{
            layout: 'panel'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,layout: {
                type: 'hbox',
                padding: 10
            },
            defaults:{
                margins:'0 10 0 10',
                allowDepress: false
            }
            ,items: [{
                xtype:'button'
                ,width:100
                ,height:40
                ,text: '<b>".GENERATE."</b>'
                ,iconCls:'icon-table_gear'    
                ,handler:function(){
                    Ext.MessageBox.show({
                        msg: '".SAVING_YOUR_DATA_PLEASE_WAIT."',
                        progressText: 'Saving...',
                        width:300,
                        wait:true,
                        waitConfig: {interval:200},
                        icon:'ext-mb-download'
                    });
                    Ext.Ajax.request({
                        url:'/dataset/jsonsave/'
                        ,method: 'POST'
                        ,params: {cmd: 'actionBackUp'}
                        ,success: function(response, options) {
                            var jsonData = Ext.util.JSON.decode(response.responseText);
                            Ext.getCmp('FILE_NAME_ID').update('<span class=textBoldBlue14>' + jsonData.getFileName + '</span>');
                            Ext.MessageBox.hide();
                        }
                        ,failure: function(response, options) {}
                    });
                }
            },{
                xtype:'button'
                ,width:100
                ,height:40
                ,text: '<b>".SAVE."</b>'
                ,iconCls:'icon-table_save'
                ,handler: function(){
                    window.location='/dataset/backup/';
                }
            },{
                xtype:'button'
                ,width:150
                ,height:40
                ,iconCls:'icon-delete'    
                ,text: '<b>".DELETE."</b>'
                ,handler:function(){
                    Ext.Ajax.request({
                        url:'/dataset/jsonsave/'
                        ,method: 'POST'
                        ,params: {cmd: 'actionDeleteBackUp'}
                        ,success: function(response, options) {
                            var jsonData = Ext.util.JSON.decode(response.responseText);
                            Ext.getCmp('FILE_NAME_ID').update('<span class=textBoldBlue14>---</span>');
                            Ext.MessageBox.hide();
                        }
                        ,failure: function(response, options) {}
                    });
                }
            },{
                xtype:'button'
                ,disabled:true
                ,width:100
                ,height:40
                ,iconCls:'icon-database_gear'    
                ,text: '<b>Recovery</b>'
            }]
        },{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items:[{
                border: false
                ,bodyStyle: 'padding-left:25px;padding-bottom:20px;'
                ,id:'FILE_NAME_ID'
                ,html:'<span class=textBoldBlue14>".UserAuth::getFileBackUp()."</span>'
            }]
        }]
    }";
    
    $PRIVACY = "
    {
        xtype:'box'
        ,anchor:''
        ,border:false
        ,width:percentWidth(90)
        ,height: percentHeight(95)
        ,autoEl: {
            tag: 'iframe',
            style: 'height: 100%; width: 100%; border: none',
            src: '/public/data/data_privacy.pdf'
        }
    }";
    
    $FORM_ITEMS = "[";
    
    switch($target){
        case "MAIN_CONTENT":
            $FORM_ITEMS .= $DETAIL_INFORMATION;
            $FORM_ITEMS .= ",".$SHORT;
            $FORM_ITEMS .= ",".$SCHOOL_LOGO_ITEMS;
            $FORM_ITEMS .= ",".$CAMEMIS_EDITION_CODE_ID;
            $FORM_ITEMS .= ",".$EMBEDDED_URL;
            $FORM_ITEMS .= ",".$ADDRESS;
            $FORM_ITEMS .= ",".$CONTACT_INFORMATION;
            $FORM_ITEMS .= ",".$SCHOOL_LETTER_HEADER;
            $FORM_ITEMS .= ",".$SCHOOL_LETTER_FOOTER;
            $FORM_ITEMS .= ",".$EMERGENCY_CALL;
            break;
        case "SETTINGS":
            $FORM_ITEMS .= "".$PROGRAMM_OPTIONS;
            $FORM_ITEMS .= ",".$SCHOOL_TIMEZONE;
            $CHECK_EDUCATION_SYSTEM = isset($this->objectData["GENERAL_EDUCATION"])?$this->objectData["GENERAL_EDUCATION"]:0;
            $FORM_ITEMS .= ",".$EDUCATION_SYSTEM;
            if($CHECK_EDUCATION_SYSTEM){
                $FORM_ITEMS .= ",".$SUB_GENERAL_EDUCATION;
            }
            $FORM_ITEMS .= ",".$WORKING_DAYS;
            $FORM_ITEMS .= ",".$CAMEMIS_FORMAT;
            break;
        case "SECURITY":
            $FORM_ITEMS .= $ACCOUNT_POLICY;
            $FORM_ITEMS .= ",".$PASSWORD_POLICY;
            $FORM_ITEMS .= ",".$CAMEMIS_NOTIFICATION;
            break;
        case "PRIVACY":
            $FORM_ITEMS .= $PRIVACY;
            break;
        case "BACK_UP":
            $FORM_ITEMS .= $BACK_UP;
            break;
    }
    
	$FORM_ITEMS .= "]";

    $items = "
        border: false
        ,autoScroll: true
        ,id: 'FORM_ITEMS'
        ,bodyStyle: 'padding:10px'
        ,items: ".$FORM_ITEMS."
    ";
    $OBJECT_FORM->addObjectItems($items);

    switch($target){
        case "MAIN_CONTENT":
        case "SETTINGS":
        case "SECURITY":
            
            $OBJECT_FORM->addTBarItems("
                text: 'CAMEMIS-".REFRESH."'
                ,id: 'ALL_REFRESH_ID'
                ,iconCls:'icon-world_go'
                ,handler: function(){window.parent.parent.parent.location='/main?welcome';}
            ");
            
            $OBJECT_FORM->addTBarItems("
                text: '" . REFRESH . "'
                ,tooltip:'" . REFRESH . "'
                ,iconCls:'icon-reload'
                ,handler: function(){
                    ".CamemisPage::setRequestURI(false).";
                }
            ");
            
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarSimpleSave());

            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            ");
        break;
        case "BACK_UP":
        case "PRIVACY":
            $OBJECT_FORM->addTBarItems("
                text: '" . REFRESH . "'
                ,tooltip:'" . REFRESH . "'
                ,iconCls:'icon-reload'
                ,handler: function(){
                    ".CamemisPage::setRequestURI(false).";
                }
            ");
        break;
    }
    
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 170;

    $OBJECT_FORM->bodyStyle = "padding:0px";
    $OBJECT_FORM->renderJS();
    
    $DISABLED_TRANSLATION = "true";
    if (UserAuth::getACLValue("TRANSLATION_MODUL")) {
        $DISABLED_TRANSLATION = "false";
    }
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: true
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
    
    if (Ext.getCmp('GENERAL_EDUCATION')) Ext.getCmp('GENERAL_EDUCATION').on('check', function(){
        if(Ext.getCmp('GENERAL_EDUCATION').getValue() == true){
            Ext.getCmp('SUB_GENERAL_EDUCATION').show();
        }else{
            Ext.getCmp('SUB_GENERAL_EDUCATION').hide();
        }
    });
});
</script>
<?
Zend_Registry::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>