<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 21.01.2010 20:29
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'models/app_university/staff/StaffDBAccess.php';
require_once 'models/app_university/schedule/ScheduleDBAccess.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print$CAMEMIS_PAGE_OBJECT->showCamemisHeader();

//@veasna on training
$target= isset($_GET["target"])?addText($_GET["target"]):"";
$trainingId= isset($_GET["trainingId"])? (int) $_GET["trainingId"]:"";      
//
$academicId = isset($_GET["academicId"])? (int) $_GET["academicId"]:"";
$current_instructor = isset($_GET["current_instructor"])? addText($_GET["current_instructor"]):"";
$teacherId = isset($_GET["teacherId"])?addText($_GET["teacherId"]):"";
$schoolyearId = isset($_GET["schoolyearId"])?addText($_GET["schoolyearId"]):"";

$params = array();
if($target){
    switch($target){ 
        case 'training':
            $params[] = "?trainingId=".$trainingId;
            $params[] = "objectId=".$trainingId;
            $params[] = "classId=".$trainingId;
            
            break;
        case 'general':
            $params[] = "?academicId=".$academicId;
            $params[] = "academicId=".$academicId;
            $params[] = "teacherId=".$teacherId;
            $params[] = "current_instructor=".$current_instructor;
            $params[] = "schoolyearId=".$schoolyearId;
            $params[] = "target=general";
            break;
    }
}

$strParams = implode("&", $params);

if($current_instructor == Zend_Registry::get('USER')->ID){
    $IS_INSTRCTOR = true;
}else{
    $IS_INSTRCTOR = false;
}

function setItem($name, $url){
    $js = "title: '<b>" . $name . "</b>'";
    $js .= ",layout: 'fit'";
    $js .= ",iconCls:'icon-package_white'";
    $js .= ",items: [new Ext.ux.IFrameComponent({ id: '".strtoupper($name)."', url: '".$url."'})]";
    return $js;
}
?>

<script>
Ext.onReady(function() {
    function handleActivate(tab){
        switch(tab.id){
            case "SMS":
            case "COMMUNICATION":
            case "ACADEMIC_PERFORMANCES":
                window.parent.Ext.getCmp('WEST_ID').collapse();
                break;
            default:
                window.parent.Ext.getCmp('WEST_ID').expand();
                break;
        }
    }
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    switch(Zend_Registry::get('ADDITIONAL_ROLE')){
        case 1:
            $USER_TYPE = "INSTRUCTOR";
            break;
        case 2:
            $USER_TYPE = "TEACHER";
            break;
        default:
            $USER_TYPE = UserAuth::getUserType();
            break;
    }
    
    $ITEMS ="[";
    
     switch($target){ 
        case 'training':
            $ITEMS .="{".setItem(SCHEDULE,'/schedule/byclass/'.$strParams.'&target=training')."}";
                
            $ITEMS .=",{".setItem(LIST_OF_STUDENTS,'/training/studentlist/'.$strParams.'&target=TERM')."}";
            
            $ITEMS .=",{".setItem(LIST_OF_TEACHERS,'/training/teacherlist/'.$strParams.'')."}";    
            
            $ITEMS .=",{".setItem(LIST_OF_ATTENDANCE,'/attendance/byclass/'.$strParams.'&target=training')."}";   
            
            $ITEMS .=",{".setItem(LIST_BY_DISCIPLINE,'/discipline/byclass/'.$strParams.'&target=training')."}";   
            
            $ITEMS .=",{".setItem(EVENTS,'/schoolevent/classevents/'.$strParams.'')."}";
            
            break;
            
        case 'general':
            $ITEMS .="{".setItem(SCHEDULE,"/schedule/byclass/".$strParams."")."}";

            $ITEMS .=",{".setItem(LIST_OF_STUDENTS,"/academic/studentlist/".$strParams."")."}";

            $ITEMS .=",{".setItem(LIST_OF_TEACHERS,"/academic/teachersbyclass/".$strParams."")."}";    

            $ITEMS .=",{".setItem(LIST_OF_ATTENDANCE,"/attendance/byclass/".$strParams."")."}";   

            $ITEMS .=",{".setItem(LIST_BY_DISCIPLINE,"/discipline/byclass/".$strParams."")."}";   

            $ITEMS .=",{".setItem(EVENTS,"/schoolevent/classevents/".$strParams."")."}";   

            if($USER_TYPE == "INSTRUCTOR")
            $ITEMS .=",{".setItem(ACADEMIC_PERFORMANCES,"/evaluation/classperformances/".$strParams."")."}";
            
            break;
     }

    $ITEMS .="]";
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,layout: 'fit'
            ,border: false
            ,items:[{
                xtype: 'vrtabpanel'
                ,tabWidth: 200
                ,border: false			
                ,activeTab: 0
                ,plain:true
                ,width:percentWidth(25)
                ,defaults:{autoScroll: true, border: false}
                ,items: <?=$ITEMS;?>      
            }]
        }]
    }); 
});
</script>
<?
print$CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>