<?php
header('Content-type: text/html; charset=utf-8');
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$print = isset($_GET["print"]) ? $_GET["print"] : "";

$OBJECT_DATA = $this->objectData;
$staffId = $OBJECT_DATA["ID"];

$db_staffs = StaffDBAccess::getInstance();
$rows = StaffDBAccess::findStaffFromId($staffId);

$entries = array();
if ($rows) {
    $entries["STAFF_SCHOOL_ID"] = $rows->STAFF_SCHOOL_ID;
    $entries["NAME"] = $rows->LASTNAME. " ".$rows->FIRSTNAME;
    $entries["CODE_ID"] = $rows->CODE;
    //$entries["STAFF_TYPE"] = $db_staffs->getUserRoleByStaffId($rows->ID);
    $entries["JOB_TYPE"] = getJobType($rows->JOB_TYPE);
    $entries["GENDER"] = getGenderName($rows->GENDER);
    $entries["DATE_BIRTH"] = getShowDate($rows->DATE_BIRTH);
    $entries["RELIGION"] = $db_staffs->setReligion($rows->RELIGION);
    $entries["ETHNICITY"] = $db_staffs->setEthnic($rows->ETHNIC);
    $entries["PHONE"] = $rows->PHONE;
    $entries["EMAIL"] = $rows->EMAIL;
    $entries["TOWN_CITY"] = $rows->TOWN_CITY;
    $entries["POSTCODE_ZIPCODE"] = $rows->POSTCODE_ZIPCODE;
    $entries["COUNTRY_PROVINCE"] = $rows->COUNTRY_PROVINCE;
    $entries["STREET"] = $rows->STREET;
    $entries["TITLE"] = $rows->TITLE;
    $entries["STATUS"] = getStatus($rows->STATUS);

}
?>
<html>
    <head>
        <?php if ($print == 'true') {
        ?>
            <style type="text/css">
                #main {
                    margin:0 auto;
                    width:50%;
                }
                h2{
                    text-align: center;
                    margin-bottom: 30px;
                }
                #main * {
                    margin : 0 auto;
                }
                #printItemTable {
                    /*              border: 1px solid #046BCA;
                                    border-collapse:collapse; */
                    margin-left: 30px;
                }
                #printItemTable td{
                    padding: 6px 5px 6px 10px;
                    /*              border: 1px solid #046BCA;*/
                    border-right: 0;
                    border-left: 0;
                }
            </style>
        <?php
        }
        ?>
    </head>
    <body><div>
            <?php
            if ($print)
                echo "<h2>" . DETAIL_INFORMATION . "</h2>";
            ?>
            <table id="printItemTable" cellspacing="14px">
                <?php
                foreach ($entries as $key => $value) {
                    $displayKey;
                    if (constant($key)) {
                        $displayKey = constant($key);
                    } else {
                        $displayKey = $key;
                    }
                    echo "<tr>";
                    echo "<td><b>$displayKey</b></td>";
                    echo "<td>".setShowText($value)."</td>";
                    echo "</tr>";
                }
                ?>
            </table>
        </div><?php if ($print){
            ?>
            <script>    
                window.print();
                window.close();
            </script>
        <?php }
        ?>
    </body>
</html>