<?
///////////////////////////////////////////////////////////
// @Sor Veasna
// Date: 23.05.2013
// 
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_GRID = new CamemisGrid("FINANCE", "LIST");
$OBJECT_GRID->setLoadUrl("/finance/jsonload/");
$columndata = Utiles::getGridColumnData("FINANCE_LIST_ID");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

Ext.onReady(function() {
    
    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#3B5998; padding: 5px;">' + value + '</div>';
    }
    
    function cssTextBold(value, metadata, record){
        return '<div style="font-weight:bold; color:#333; padding: 5px;">' + value + '</div>';
    }
    
    function cssNumber(value, metadata, record){
        return '<div style="font-weight:bold; color:#3B5998; padding: 5px;">' + value + '</div>';
    }
        
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
     
    $OBJECT_GRID->addReadField("name: 'STUDENT_NAME'"); 
    $OBJECT_GRID->addReadField("name: 'CODE_ID'");
    $OBJECT_GRID->addReadField("name: 'LASTNAME'");
    $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
    $OBJECT_GRID->addReadField("name: 'EMAIL'");
    $OBJECT_GRID->addReadField("name: 'PHONE'");
    $OBJECT_GRID->addReadField("name: 'STUDENT_CODE'");
    $OBJECT_GRID->addReadField("name: 'CLASS_NAME'");
    $OBJECT_GRID->addReadField("name: 'CHOOSE_OPTION'");
    $OBJECT_GRID->addReadField("name: 'NALERT'");
    $OBJECT_GRID->addReadField("name: 'NPAID'");
    $OBJECT_GRID->addReadField("name: 'PAID_STATUS'");
    $OBJECT_GRID->addReadField("name: 'STUDENT_FEE_ID'");
    $OBJECT_GRID->addReadField("name: 'LAST_ALERT_DATE'");  
    $OBJECT_GRID->addReadField("name: 'LAST_PAID_DATE'");
    $OBJECT_GRID->addReadField("name: 'DUE_DAY'");
    $OBJECT_GRID->addReadField("name: 'DUE_DATE'");
        
    $OBJECT_GRID->addColumn("header: '<b>".CODE."</b>', align:'right', renderer: cssNumber, width:80, hidden:".checkColHidden(1, $columndata).", sortable: true, dataIndex: 'STUDENT_CODE'");
    $OBJECT_GRID->addColumn("header: '<b>".NAME."</b>', align:'left', renderer: cssText, width: 120, hidden:".checkColHidden(2, $columndata).", sortable: true, dataIndex: 'STUDENT_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".GRADE_CLASS."</b>', align:'left', renderer: cssText, width: 60, hidden:".checkColHidden(3, $columndata).", sortable: true, dataIndex: 'CLASS_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".PAYMENT_OPTION."</b>', align:'left', renderer: cssNumber, width: 80, hidden:".checkColHidden(4, $columndata).", sortable: true, dataIndex: 'CHOOSE_OPTION'");
    $OBJECT_GRID->addColumn("header: '<b>".NUMBER_OF_PAYMENT."</b>', align:'left', renderer: cssText, width: 80, hidden:".checkColHidden(5, $columndata).", sortable: true, dataIndex: 'NPAID'");
    $OBJECT_GRID->addColumn("header: '<b>".LAST_PAID_DATE."</b>', align:'left', renderer: cssText, width: 100, hidden:".checkColHidden(6, $columndata).", sortable: true, dataIndex: 'LAST_PAID_DATE'");
    $OBJECT_GRID->addColumn("header: '<b>".NUMBER_OF_ALERT."</b>', align:'left', renderer: cssText, width: 100, hidden:".checkColHidden(7, $columndata).", sortable: true, dataIndex: 'NALERT'");
    $OBJECT_GRID->addColumn("header: '<b>".LAST_ALERT_DATE."</b>', align:'left', renderer: cssText, width: 100, hidden:".checkColHidden(8, $columndata).", sortable: true, dataIndex: 'LAST_ALERT_DATE'");
    $OBJECT_GRID->addColumn("header: '<b>".PAID_STATUS."</b>', align:'left', renderer: cssText, width: 100, hidden:".checkColHidden(9, $columndata).", sortable: true, dataIndex: 'PAID_STATUS'");
    $OBJECT_GRID->addColumn("header: '<b>".DUE_DAYS."</b>', align:'left', renderer: cssText, width: 80, hidden:".checkColHidden(10, $columndata).", sortable: true, dataIndex: 'DUE_DAY'");
    $OBJECT_GRID->addColumn("header: '<b>".DUE_DATE."</b>', align:'left', renderer: cssText, width: 100, hidden:".checkColHidden(11, $columndata).", sortable: true, dataIndex: 'DUE_DATE'");
    
   
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'COMMUNICATION_ID'
            ,text: '".COMMUNICATION."'
            ,iconCls:'icon-email_add'
            ,scope:this
            ,disabled: false
            ,handler: function(){
                var selids = '';
                var seltexts = '';
                var selemails='';
                var selphones='';
                var sels = Ext.getCmp('FINANCE_LIST_ID').getSelectionModel().getSelections();
                for( var i = 0; i < sels.length; i++ ) {
                    if (i >0) selids += ',';
                    selids += sels[i].get('CODE_ID');
                    
                    if (i >0) seltexts += ',';
                    seltexts += i+1 + ') ' + sels[i].get('LASTNAME') +' '+ sels[i].get('FIRSTNAME');
                    
                    if (i >0) selemails += ',';
                    selemails += sels[i].get('EMAIL');
                    
                    if (i >0) selphones += ',';
                    selphones += sels[i].get('PHONE');
                }
                var url='".$this->URL_STUDENT_SEND_REMINDER."&objectId='+selids+'&objectemail='+selemails+'&objectphone='+selphones+'&objectName='+seltexts+'&fee=".$this->objectId."';
                clickOpenPage('center','".NOTIFICATION."',url);
                
        }
        }]);
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonLoadStudentFeeReminder'
        ,feeID: '".$this->objectId."'
        ,schoolyear: '".$this->schoolyear."'
        ,studentReminds: '1'
    ";
    
    $OBJECT_GRID->isQuickySearch=true; 
    
    $OBJECT_GRID->isCheckboxSelect=true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,xtype: 'panel'
            ,layout: 'card'
            ,id: 'center'
            ,activeItem: 0
            ,items:[{
                border: false
                ,title: ''
                ,layout: 'fit'
                ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
            }]
        }]
    });
    Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>