<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'models/app_university/subject/SubjectDBAccess.php';
require_once 'models/app_university/subject/SubjectTeacherDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$SUBJECT_TEACHER_ACCESS = SubjectTeacherDBAccess::getInstance();
 
$trainingId = isset($_GET["trainingId"])?$_GET["trainingId"]:"";
$teacherId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";

$ENTRIES = SubjectDBAccess::sqlSubjectsByTraining($trainingId, false, false);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<style type="text/css">
    .ux-icon-combo-icon {
        background-repeat: no-repeat;
        background-position: 0 50%;
        width: 18px;
        height: 14px;
    }
    .ux-icon-combo-input {
        padding-left: 25px;
    }
    .x-form-field-wrap .ux-icon-combo-icon {
        top: 3px;
        left: 5px;
    }
    .ux-icon-combo-item {
        background-repeat: no-repeat ! important;
        background-position: 3px 50% ! important;
        padding-left: 24px ! important;
    }
</style>
<script>
var subjectId;
Ext.onReady(function() {

    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $subjectId = "";
    $DATA = array();
    $STORE_SUBJECT = "[";
    if($ENTRIES){
        $i=1; 
        $DATA[0] = '';
        $STORE_SUBJECT .= "['', 'All Subject', 'icon-application_form_magnify']";  
        foreach($ENTRIES as $value){
            if($value->SUBJECT_ID){ 
                $CHECK = $SUBJECT_TEACHER_ACCESS->checkAssignedSubjectTeacherTraining(
                        $value->SUBJECT_ID
                        , $teacherId
                        , $trainingId
                        , false);
                switch (UserAuth::getUserType()) {
                    case "STUDENT":
                    case "ADMIN":
                    case "SUPERADMIN":
                        $DATA[$i] = $value->SUBJECT_ID;
                        $STORE_SUBJECT .= $i?",":"";
                        $STORE_SUBJECT .= "['" . $value->SUBJECT_ID . "', '(".$value->SUBJECT_SHORT.") " . $value->SUBJECT_NAME ."', 'icon-application_form_magnify']";
                        $i++;
                    break;
                    case "TEACHER":
                    case "INSTRUCTOR":  
                        if($CHECK){
                            $DATA[$i] = $value->SUBJECT_ID;
                            $STORE_SUBJECT .= $i?",":"";
                            $STORE_SUBJECT .= "['" . $value->SUBJECT_ID . "', '(".$value->SUBJECT_SHORT.") " . $value->SUBJECT_NAME ."', 'icon-application_form_magnify']";
                            $i++;
                        }
                    break;
                }   
            } 
        }
         $subjectId = isset($DATA[0])?$DATA[0]:0; 
         $SHOW_LAYOUT = "[new Ext.ux.IFrameComponent({ id: 'SHOW_SUBJECT', url: '/homework/homeworklisttraining/?subjectId=".$subjectId."&teacherId=".$teacherId."&trainingId=".$trainingId."'})]";
    }else{
        $SHOW_LAYOUT = "{
            title:'".STATUS."'
            ,layout: 'fit'
            ,border: false
            ,contentEl: 'initCenter'
        }";
    }
    
    $STORE_SUBJECT .= "]";
    $COMBO_SUBJECT = "[{
        xtype:'combo'
        ,width:280
        ,id:'COMO_SUBJECT_ID'
        ,fieldLabel:'IconCombo'
        ,store: new Ext.data.SimpleStore({
            fields: ['comboCode', 'comboName', 'comboIcon'],
            data: ".$STORE_SUBJECT."
        }),
        plugins:new Ext.ux.plugins.IconCombo()
        ,valueField: 'comboCode'
        ,displayField: 'comboName'
        ,iconClsField: 'comboIcon'
        ,triggerAction: 'all'
        ,mode: 'local'
        ,value:'".$subjectId."'
    }]";
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout: 'card' 
            ,id:'content'
            ,activeItem: 0
            ,border: false
            ,tbar:[
                '<b><?=SUBJECT?>:</b>',{
                xtype: 'buttongroup' 
                ,items:<?=$COMBO_SUBJECT;?>
            }] 
            ,items:<?=$SHOW_LAYOUT?>
        }]
    });
    var comboSubject = Ext.getCmp('COMO_SUBJECT_ID');
    comboSubject.on('select', function() {
        clickOpenPage('content','','/homework/homeworklisttraining/?teacherId=<?=$teacherId;?>&trainingId=<?=$trainingId;?>&subjectId=' + comboSubject.getValue());
    });
});
</script>
<div id="initCenter" class="x-hide-display" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="headerError">No data available .</h1>
</div>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>