<?
///////////////////////////////////////////////////////////
// Date: 05.07.2013
// Soda
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisGrid.php';
require_once setUserLoacalization(); 

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$academicId = isset($_GET["academicId"])? (int) $_GET["academicId"]:"";
$teacherId = isset($_GET["teacherId"])?addText($_GET["teacherId"]):"";
$subjectId = isset($_GET["subjectId"])? (int)$_GET["subjectId"]:"";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {
        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px;'
                ,border:false
                ,items:[{
                    xtype: 'tabpanel'
                    ,plain:true
                    ,activeTab: 0
                    ,items:[{
                        title: '<?=TEACHER;?>' 
                        ,id: 'TEACHER' 
                        ,layout: 'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'TEACHER', url: '/homework/teachershowitem/?academicId=<?=$this->academicId?>&subjectId=<?=$this->subjectId?>&objectId=<?=$this->objectId?>'})]
                    },{  
                        title: '<?=STUDENTS;?>'
                        ,id: 'STUDENTS' 
                        ,layout: 'fit'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'STUDENTS', url: '/homework/studentshowitemlist/?objectId=<?=$this->objectId?>'})]                        
                    }]      
                }]     
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>