<?
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("EVALUATION_TOPIC", "LIST");
$OBJECT_TREE->setURL("/camemisevaluation/jsontree/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>

    Ext.onReady(function() {
        
        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $OBJECT_TREE->isAsyncTreeNode = false;
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        $OBJECT_TREE->addTBarItems("
            id: 'EVALUATION_TOPIC'
            ,tooltip:'".EVALUATION_TOPIC."'
            ,scope:this
            ,iconCls:'icon-application_form_add'
            ,handler: function(){
                clickOpenPage('center','".EVALUATION_TOPIC."', '/camemisevaluation/topicshow/?objectId=new');   
            }
        ");
        
        $OBJECT_TREE->addTBarItems("
            text:''
            ,tooltip:'".CAMEMIS_HELP."'
            ,iconCls: 'icon-help'
            ,handler:function(){
                ".CamemisPage::setEmbeddedHelp("3FF0-099F")."
            }
        ");
        
        $OBJECT_TREE->setBaseParams("
            cmd: 'jsonTreeAllEvaluationTopic'
            ,showCheck:0
        ");
        
        $OBJECT_TREE->isTreeExpand = true;
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: false
                    ,split: true
                }
                ,items: [{
                    region:'west'
                    ,title:'<?=EVALUATION_TOPIC?>'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width: 310
                    ,minSize: 310
                    ,maxSize: 310
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
                },{
                    collapsible: false
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,items: [{
                        border: false
                        ,layout: 'anchor'
                        ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                        ,items: [{
                            title: ''
                            ,height:60
                            ,width:500
                            ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                            ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                        }]
                    }]
                }]
            }]
        });
        var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
        myTree.on('click', function(node, e){
            parentId = node.attributes.parentId;
            
            var contextMenu = new Ext.menu.Menu({
                items: [{
                    text: '<?=SHOW_DETAIL;?>'
                    ,iconCls:'icon-application_form_magnify'
                    ,handler:function(){
                        clickOpenPage('center','', '/camemisevaluation/topicshow/?objectId=' + node.id + '&parentId=' + parentId);   
                    }
                },{
                    text: '<?=ADD_A_NEW_ITEM;?>'
                    ,iconCls:'icon-application_form_add'
                    ,handler: function(){
                        clickOpenPage('center','', '/camemisevaluation/topicshow/?objectId=new&parentId=' + node.id);    
                    }
                }] 
            });
            e.stopEvent();
            contextMenu.showAt(e.xy);   
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>