<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 05.02.2014
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("TOPIC");
$OBJECT_FORM->setSaveUrl("/camemisevaluation/jsonsave/");
$OBJECT_FORM->setLoadUrl("/camemisevaluation/jsonload/");

$STUDENT_TREE = new CamemisTree("FILE","STUDENT_LIST");
$STUDENT_TREE->setURL('/camemisevaluation/jsontree/');

$STAFF_TREE = new CamemisTree("EVALUATION", "STAFF_LIST");
$STAFF_TREE->setURL('/camemisevaluation/jsontree/');
$USER_TYPE=UserAuth::getUserType();

if($this->objectId == "new"){
    $parentId = isset($_GET['parentId'])?addText($_GET['parentId']):'';
}else{
    $parentId = $this->facette?$this->facette->PARENT:'';
}    

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    ///////////////////////////////////////////////////////////////////////////////
    //STAFF TREE
    ///////////////////////////////////////////////////////////////////////////////
    $STAFF_TREE->isAsyncTreeNode = false;
    $STAFF_TREE->addTBarItems(CamemisBar::tbarTreeRefresh('STAFF'));
    $STAFF_TREE->addTBarItems(CamemisBar::tbarTreeExpand('STAFF'));
    $STAFF_TREE->addTBarItems(CamemisBar::tbarTreeCollapse('STAFF'));
    //if($this->objectId != "new" || $USER_TYPE=='SUPERADMIN'){
        $STAFF_TREE->setBaseParams("
            cmd: 'treeAllStaffs'
            ,objectId:'".$this->objectId."'
        ");
    //}
    
    $STAFF_TREE->backgroundColor = "#F9F9F9";
    $STAFF_TREE->isOnClickContextMenu = false;
    $STAFF_TREE->isTreeExpand = true;
    $STAFF_TREE->renderJS();
    
    //////////////////////////////////////////////////////////////////////////////
    //STUDNET TREE
    //////////////////////////////////////////////////////////////////////////////
    $STUDENT_TREE->isAsyncTreeNode = false;
    $STUDENT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh('STUDENT'));
    $STUDENT_TREE->addTBarItems(CamemisBar::tbarTreeExpand('STUDENT'));
    $STUDENT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse('STUDENT'));
     
    if($this->objectId != "new" || $USER_TYPE=='SUPERADMIN'){
        $schoolyearObject = AcademicDateDBAccess::findSchoolyearByCurrentDate();
        $STUDENT_TREE->setBaseParams("
            cmd: 'getAcademicsByEvaluation'
            ,objectId:'".$this->objectId."'
            ,SCHOOLYEAR:'".$schoolyearObject->ID."'
        ");
    }
    
    $STUDENT_TREE->backgroundColor = "#F9F9F9";
    $STUDENT_TREE->isOnClickContextMenu = false;
    $STUDENT_TREE->isTreeExpand = true;
    $STUDENT_TREE->renderJS();
    /////////////////////////////////////////////////////////////////////////////
    
    $OBJECT_FORM->addObjectItems("
        title: '".NAME."'
        ,autoHeight: true
        ,style: 'padding-bottom:5px'
        ,collapsible: true
        ,collapsed: false
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Textfield("TOPIC_NAME", "NAME", NAME, false, false, false, false)."}
            ]
        }]   
    ");

    
    $OBJECT_FORM->addObjectItems("
        title: '".DESCRIPTION."'
        ,collapsible: true
        ,collapsed: false
        ,width:550
        ,style: 'padding-bottom: 5px'
        ,items:[{
            layout: 'fit'
            ,border: false
            ,bodyStyle: 'padding:5px'
            ,items:[{".CamemisField::Textarea("DESCRIPTION",DESCRIPTION,200,false,false)."}]
        }]   
    ");
    
    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        }
    ");
    
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'jsonSaveEvaluationTopic'
        ,objectId: '".$this->objectId."'
        ,parentId: '".$this->parentId."'
    ");
    
    $OBJECT_FORM->setonEmbeddedEvents("
        XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
        window.parent.Ext.getCmp('TREE.EVALUATION_TOPIC_LIST_ID').root.reload();
        var result = Ext.util.JSON.decode(action.response.responseText);
        window.location='".$_SERVER["REQUEST_URI"]."&objectId='+result.objectId;
     ");
     
     if($this->objectId != "new"){
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleRemove());
        
        $OBJECT_FORM->setRemoveParams("
            cmd: 'jsonRemoveEvaluationTopic'
            ,objectId: '".$this->objectId."'
        ");
        
        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            XMsg('".STATUS."','".MSG_ACTION_REMOVED_ITEM."'); 
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            window.parent.Ext.getCmp('TREE.EVALUATION_TOPIC_LIST_ID').root.reload();
        ");
        
        $OBJECT_FORM->setLoadParams("
            cmd: 'jsonLoadEvaluationTopic'
            ,objectId: '".$this->objectId."'
        ");    
     }
    
    $OBJECT_FORM->isObjectDefaultOnLoad = ($this->objectId=="new")?false:true; 
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    
    $VIEWPORT_ITEMS = "[{";
        if($this->objectId == "new"){
            $VIEWPORT_ITEMS .= "
                layout:'fit'
                ,border: false
                ,items: [{xtype: '".$OBJECT_FORM->getObjectXType()."'}]    
            ";
        }else{
            $VIEWPORT_ITEMS .= "
                bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px;'
                ,border:false
                ,items:[{
                    xtype: 'tabpanel'
                    ,plain:true
                    ,activeTab: 0
                    ,items:[{
                        title:'".QUESTION."'
                        ,border: false
                        ,height:percentHeight(100)
                        ,contentEl: 'initCenter'
                    },{ 
                        title: '".STUDENT."'   
                        ,layout:'fit' 
                        ,bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px;'
                        ,height:percentHeight(100)
                        ,items: [{xtype: '".$STUDENT_TREE->getObjectXType()."'}]
                    },{
                        title:'".STAFF."'
                        ,layout:'fit'
                        ,bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px;'
                        ,height:percentHeight(100)
                        ,border: false
                        ,items: [{xtype: '".$STAFF_TREE->getObjectXType()."'}]
                    },{
                        title:'".MAIN_CONTENT."'
                        ,border: false
                        ,items: [{xtype: '".$OBJECT_FORM->getObjectXType()."'}]    
                    }]
                }]
            ";
        } 
    $VIEWPORT_ITEMS .= "}]";
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'fit'
            ,border: false
            ,items: <?=$VIEWPORT_ITEMS;?>
        }]
    });
    <?
    if($this->objectId != "new"){
        
        $js = "";
        $js .= "var myTraditionalTree = ".$STUDENT_TREE->ExtgetCmp().";";
        $js .= "if (myTraditionalTree) myTraditionalTree.on('checkchange', function(node, checked){";
        
            ////////////////////////////////////////////////////////////////////////////////////////
            $js .= "myTraditionalTree = window.parent.Ext.getCmp('TREE.EVALUATION_TOPIC_LIST_ID');";
            $js .= "myNode = myTraditionalTree.getNodeById('".$parentId."');";
            $js .= "if(myNode.parentNode==null){";
                $js .= "myTraditionalTree.root.reload();";
            $js .= "}else{";
                $js .= "var parentId = myNode.parentNode.id";
                $js .= "myPerentNode = myTraditionalTree.getNodeById(parentId);";
                $js .= "if(myNode.isLeaf()){";
                    $js .= "if(myPerentNode){";
                        $js .= "myPerentNode.reload();";
                        $js .= "myPerentNode.expand(true, false);";
                    $js .= "}else{";
                        $js .= "myTraditionalTree.root.reload();";
                    $js .= "}";
                $js .= "}else{";
                    $js .= "if (myNode.hasChildNodes()) {";
                        $js .= "myNode.reload();";
                        $js .= "myNode.expand(true, false);";
                    $js .= "}";
                $js .= "}";
            $js .= "}";
            ///////////////////////////////////////////////////////////////////////////////////////
            
            $js .= "Ext.Ajax.request({";
                $js .= "url:'/camemisevaluation/jsonsave/'";
                $js .= ",method:'POST'";
                $js .= ",params:{";
                    $js .= "cmd:'jsonActionAcademicToEvaluation'";
                    $js .= ",checked: checked";
                    $js .= ",academic: node.id";
                    $js .= ",objectId: '".$this->objectId."'";
                $js .= "}";
                $js .= ",success: function(response, options) {";
                    $js .= "result = Ext.util.JSON.decode(response.responseText);";
                    $js .= "XMsg('".STATUS."',result.msg);";
                $js .= "}";
            $js .= "});";
            
        $js .= "});";    
        print $js;   
    }
    ?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>

<html>
<body bgcolor="#FFFFFF">
    <div id="initCenter" class="x-hidden" style="border:0px silver solid;margin:30px;padding:8px;height:80px">
        <h1 class="headerError">You do not have permission to access this object.!</h1>
    </div>
</body>
</html>