<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("STUDENT_TRAINING");
$OBJECT_FORM->setLoadUrl('/training/jsonload/');
$OBJECT_FORM->setSaveUrl('/training/jsonsave/');

$entriesParentCheckbox = DescriptionDBAccess::sqlDescription(false, "STUDENT_TRAINING", 1);

$CHECKBOX_JS = "";
$CHECKBOX_DATA = array();
$CHECKBOX_ITEMS = array();
if($entriesParentCheckbox){
    foreach($entriesParentCheckbox as $value){
        if(DescriptionDBAccess::checkChild($value->ID)){
            $entries = DescriptionDBAccess::sqlDescription($value->ID, "STUDENT_TRAINING", 1);
            $CHECKBOX_JS .= "var CHECKBOX_$value->ID = new Ext.form.CheckboxGroup({";
               $CHECKBOX_JS .= "fieldLabel: '".$value->NAME."'";
               $CHECKBOX_JS .= ",columns: 2";
               $CHECKBOX_JS .= ",items:[";
                   $CHECKBOX_DATA = array();
                   foreach($entries as $v){
                       $CHECKBOX_DATA[] = "{boxLabel: '".$v->NAME."', name: 'CHECKBOX_".$v->ID."'}";
                   }
                   $CHECKBOX_JS .= implode(',',$CHECKBOX_DATA);
               $CHECKBOX_JS .= "]";
           $CHECKBOX_JS .= "});";

           $CHECKBOX_ITEMS[] = "CHECKBOX_".$value->ID."";   
        }
    }
}

$entriesParentRadiobox = DescriptionDBAccess::sqlDescription(false, "STUDENT_TRAINING", 2);
$RADIOBOX_JS = "";
$RADIOBOX_DATA = array();
$RADIOBOX_ITEMS = array();
if($entriesParentRadiobox){
    foreach($entriesParentRadiobox as $value){
        if(DescriptionDBAccess::checkChild($value->ID)){
            $entries = DescriptionDBAccess::sqlDescription($value->ID, "STUDENT_TRAINING", 2);
            $RADIOBOX_JS .= "var RADIOBOX_$value->ID = new Ext.form.RadioGroup({";
                $RADIOBOX_JS .= "fieldLabel: '".$value->NAME."'";
                $RADIOBOX_JS .= ",columns: 2";
                $RADIOBOX_JS .= ",items:[";
                    $RADIOBOX_DATA = array();
                    foreach($entries as $v){
                        $RADIOBOX_DATA[] = "{boxLabel: '".$v->NAME."', name: 'RADIOBOX_".$value->ID."', inputValue: '".$v->ID."'}";
                    }
                    $RADIOBOX_JS .= implode(',',$RADIOBOX_DATA);
                $RADIOBOX_JS .= "]";
            $RADIOBOX_JS .= "});";

            $RADIOBOX_ITEMS[] = "RADIOBOX_".$value->ID."";
        }
    }
}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    Ext.onReady(function() {

        <?
        echo $RADIOBOX_JS;
        echo $CHECKBOX_JS;
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $DETAIL_CHECKBOX = "
        {
            title: 'Check Box'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [".implode(',',$CHECKBOX_ITEMS)."]
            }]
        }
        ";
        
        $DETAIL_RADIOBOX = "
        {
            title: 'Radio Box'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [".implode(',',$RADIOBOX_ITEMS)."]
            }]
        }
        ";
        
        $DESCRIPTION = "
        {
            title: '".DESCRIPTION."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,height: 100
            ,items:[{
                layout: 'fit'
                ,border: false
                ,bodyStyle: 'padding:5px'
                ,items: [{".CamemisField::Textarea("DESCRIPTION", false,300)."}]
            }]
        }
        ";
        
        if($CHECKBOX_ITEMS && $RADIOBOX_ITEMS){
            $SET_ITEMS = "
            [
                ".$DETAIL_RADIOBOX."
                ,".$DETAIL_CHECKBOX."
                ,".$DESCRIPTION."
            ]
            ";
        }elseif(!$CHECKBOX_ITEMS && $RADIOBOX_ITEMS){
            $SET_ITEMS = "
            [
                ".$DETAIL_RADIOBOX."
                ,".$DESCRIPTION."
            ]
            ";
        }elseif($CHECKBOX_ITEMS && !$RADIOBOX_ITEMS){
            $SET_ITEMS = "
            [
                ".$DETAIL_CHECKBOX."
                ,".$DESCRIPTION."
            ]
            ";
        }else{
            $SET_ITEMS = "
            [
            ]
            ";
        }
        
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        
        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: ".$SET_ITEMS."
        ";
        $OBJECT_FORM->setLoadParams("cmd: 'loadStudentTrainingDescripton',objectId: '".$this->objectId."',studentId: '".$this->studentId."'");
        $OBJECT_FORM->setSaveParams("
            cmd: 'actionStudentTrainingDescription'
            ,objectId: '".$this->objectId."'
            ,studentId: '".$this->studentId."'
        ");
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
        ");
        $OBJECT_FORM->addObjectItems($items);
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 120;
        $OBJECT_FORM->renderJS();
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                xtype: 'panel'
                ,id: 'panel'
                ,border: false
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>