<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 13.03.2012
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisViewport.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTree("TRAINING", "LIST");
$OBJECT_TREE->setURL('/training/jsontree/');
$OBJECT_TREE->setSaveUrl('/training/jsonsave/');

$studentId = isset($_GET["objectId"])?addText($_GET["objectId"]):"";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader(); 
?>

<script>

Ext.onReady(function() {
    
    var tabs =  new Ext.TabPanel({
        autoTabs:true
        ,border:false
        ,tabPosition: 'top'
        ,enableTabScroll:true
        ,activeTab:0
        ,items:[{
            title: '&nbsp;'
            ,id: 'TAB_DEFAULT'
            ,layout: 'fit'
            /*,iconCls: 'icon-tabs'*/
            ,items: [{
                layout:'anchor'
                ,border:false
                ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                ,items:[{
                    title: ''
                    ,height:60
                    ,width:500
                    ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                    ,html:'<h1 class=\"header\"><?=PLEASE_MAKE_YOUR_SELECTIONS?></h1>'    
                }]
            }]
        }]
    });
        
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $CAMEMIS_PAGE_OBJECT->setAddTab();
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    $OBJECT_TREE->isTreeExpand = true;
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh(false));
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    
    switch(UserAuth::getUserType()){
        case "SUPERADMIN":
        case "ADMIN":
        case "INSTRUCTOR":
        case "TEACHER":
            $OBJECT_TREE->setBaseParams("
                cmd: 'jsonTreeStudentTrainings'
                ,studentId: '".$studentId."'
            ");
        break;
        case "STUDENT":
            $OBJECT_TREE->setBaseParams("
                cmd: 'jsonTreeStudentTrainings'
            ");
            break;
    }
    
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->renderJS();
    ?>
    viewport = new Ext.Viewport({
        border: false
        ,layout:'fit'
        ,items:[{
            layout:'border'
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,border: false
            ,items: [{
                title: '&nbsp;'
                ,region:'west'
                ,id: 'WEST_ID'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width: 280
                ,minSize: 280
                ,maxSize: 280
                ,layout: 'fit'
                ,items: [{xtype: '<?=$OBJECT_TREE->getObjectXType();?>'}]
            },{
                title: ''
                ,collapsible: false
                ,region:'center'
                ,margins: '3 3 3 0'
                ,id: 'center'
                ,layout:'card'
                ,activeItem: 0
                ,items: tabs
            }]
        }]
    });
    var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('click', function(node, event){
        if(node.isLeaf()){
            var contextMenu = new Ext.menu.Menu({
            items: [{
                text: '<?=SHOW_DETAIL;?> &raquo; '+ node.text  
                /*,iconCls: 'icon-tabs'*/
                ,handler:function(){
                    addTab(node.id,'<?=SHOW_DETAIL;?> &raquo; '+ node.text,'<?=$this->URL_STUDENT_TRAINING;?>objectId=<?=$studentId?>&trainingId=' + node.id);
                }
            },{
                text: '<?=SCHEDULE;?> &raquo; '+ node.text
                ,iconCls:'icon-date'
                ,handler:function(){
                    addTab(node.id,'<?=SCHEDULE;?> &raquo; '+ node.text,'/schedule/byclass/?target=training&trainingId='+node.id);
                }
            },{
                text: '<?=FEES;?> &raquo; '+ node.text
                ,iconCls:'icon-application_side_list'
                ,handler:function(){
                    addTab(node.id,'<?=FEES;?> &raquo; '+ node.text,'/finance/studentaccounthistory?objectId=<?=$studentId?>&classId='+node.id);
                }
            },{
                text: '<?=EVENTS;?> &raquo; '+ node.text
                ,iconCls:'icon-date'
                ,handler:function(){
                    addTab(node.id,'<?=EVENTS;?> &raquo; '+ node.text,'/schoolevent/classevents/?classId='+node.id);
                }
            },{
                text: '<?=LIST_OF_STUDENTS;?> &raquo; '+ node.text
                ,iconCls:'icon-group'
                ,handler:function(){
                    addTab(node.id,'<?=LIST_OF_STUDENTS;?> &raquo; '+ node.text,'/training/studentlist/?target=TERM&objectId='+node.id);
                }
            },{
                text: '<?=LIST_OF_TEACHERS;?> &raquo; '+ node.text
                ,iconCls:'icon-group'
                ,handler:function(){
                    addTab(node.id,'<?=LIST_OF_TEACHERS;?> &raquo; '+ node.text,'/training/teacherlist/?objectId='+node.id);
                }
            },{
                text: '<?=SUBJECT;?> &raquo; '+ node.text
                ,iconCls:'icon-flag_blue'
                ,handler:function(){
                    addTab(node.id,'<?=SUBJECT;?> &raquo; '+ node.text,'/training/evaluationstudenttraining/?objectId='+node.id+'&studentId=<?=$studentId;?>');
                }
            },{
                text: '<?=ATTENDANCE;?> &raquo; '+ node.text
                ,iconCls:'icon-date-time'
                ,handler:function(){
                    addTab(node.id,'<?=ATTENDANCE;?> &raquo; '+ node.text,'/attendance/byclass/?target=training&studentId=<?=$studentId;?>&classId'+node.id);
                }
            },{
                text: '<?=DISCIPLINE;?> &raquo; '+ node.text
                ,iconCls:'icon-bell'
                ,handler:function(){
                    addTab(node.id,'<?=DISCIPLINE;?> &raquo; '+ node.text,'/discipline/byclass/?target=training&studentId=<?=$studentId;?>classId='+node.id);
                }
            }]
        });
        event.stopEvent();
        contextMenu.showAt(event.xy);
        }
        
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>