<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 06.06.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisExtraClassTree.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisExtraClassTree("EXTRACLASS","LIST");
$OBJECT_TREE->setURL("/extraclass/jsontree/");
$OBJECT_TREE->setSaveUrl("/extraclass/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    
    Ext.onReady(function() {
        var tabs =  new Ext.TabPanel({
            autoTabs:true
            ,border:false
            ,tabPosition: 'top'
            ,enableTabScroll:true
            ,activeTab:0
            ,items:[{
                title: '&nbsp;'
                ,id: 'TAB_DEFAULT'
                ,layout: 'fit'
                ,items: [{
                    layout:'anchor'
                    ,border:false
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items:[{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class=\"header\"><?=PLEASE_MAKE_YOUR_SELECTIONS?></h1>'    
                    }]
                }]
            }]
        });
        <?
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $CAMEMIS_PAGE_OBJECT->setAddTab();

        $OBJECT_TREE->isAsyncTreeNode = false;

        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        
        //if (UserAuth::getACLValue("ACADEMIC_TRAINING_PROGRAMS_EDIT_RIGHT"))
        $OBJECT_TREE->addTBarItems("
            id: 'ADD_PROGRAM_ID' 
            ,tooltip:'".PROGRAM."'
            ,scope:this
            ,iconCls:'icon-application_form_add'
            ,handler: function() {
                 clickOpenPage('center', '".EXTRA_CLASS."', '/extraclass/addprogram/?template=PROGRAM&objectId=new');
            }
        ");
        
        $OBJECT_TREE->addTBarItems("
            text:''
            ,tooltip:'".CAMEMIS_HELP."'
            ,iconCls: 'icon-help'
            ,handler:function(){
                ".CamemisPage::setEmbeddedHelp("85BB-BC30")."
            }
        ");
        
        $OBJECT_TREE->setBaseParams("
            cmd: 'jsonTreeAllExtraClass'
        ");
        $OBJECT_TREE->backgroundColor = "#F9F9F9";
        $OBJECT_TREE->isTreeExpand = false;
        $OBJECT_TREE->renderJS();
        
        $html = "";
        $html .= "viewport = new Ext.Viewport({";
            $html .= "layout: 'fit'";
            $html .= ",border: false";
            $html .= ",items:[{";
                $html .= "layout:'border'";
                $html .= ",border: false";
                $html .= ",defaults: {";
                    $html .= "collapsible: true";
                    $html .= ",split: true";
                $html .= "}";
                $html .= ",items: [{";
                    $html .= "region:'west'";
                    $html .= ",id: 'WEST_ID'";
                    $html .= ",title: '&nbsp;'";
                    $html .= ",autoScroll: true";
                    $html .= ",margins: '3 0 3 3'";
                    $html .= ",cmargins: '3 3 3 3'";
                    $html .= ",width:350";
                    $html .= ",minSize:350";
                    $html .= ",maxSize:350";
                    $html .= ",layout: 'fit'";
                    $html .= ",items:[{xtype: '".$OBJECT_TREE->getObjectXtype()."'}]";
                $html .= "},{";
                   $html .= " collapsible: false";
                    $html .= ",id: 'center'";
                    $html .= ",region:'center'";
                    $html .= ",margins: '3 3 3 0'";
                    $html .= ",layout: 'card'";
                    $html .= ",activeItem: 0";
                    $html .= ",bodyStyle: 'padding:1px'";
                    $html .= ",items:tabs";
                $html .= "}]";
            $html .= "}]";
        $html .= "});";
        
        $html .= "var myTree = ".$OBJECT_TREE->ExtgetCmp().";";
        $html .= "myTree.on('click', function(node, event){";
        $html .= "switch(node.attributes.objecttype){";
            $html .= "case 'PROGRAM':";
                $html .= "var contextMenu = new Ext.menu.Menu({";
                    $html .= "items: [{";
                        $html .= "text: '".EXPAND."'";
                        $html .= ",iconCls: 'icon-expand-all'";
                        $html .= ",handler: function(){";
                            $html .= "myNode = myTree.getNodeById(node.id);";
                            $html .= "myNode.reload();";
                            $html .= "myNode.expand(true, false);";
                        $html .= "}";  
                    $html .= "},{"; 
                        $html .= "text: '".COLLAPSE."'";
                        $html .= ",iconCls: 'icon-collapse-all'";
                        $html .= ",handler: function(){";
                            $html .= "myNode = myTree.getNodeById(node.id);";
                            $html .= "myNode.collapse(true, false);";
                        $html .= "}";  
                    $html .= "},{"; 
                    $html .= "text: '".MAIN_CONTENT."'";
                        $html .= ",iconCls: 'icon-application_form_magnify'";
                        $html .= ",handler: function(){";
                            $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                            $html .= "clickOpenPage('center','".MAIN_CONTENT."', '".$this->URL_PROGRAM."objectId=' + node.id);";
                        $html .= "}";  
                    $html .= "}]"; 
                $html .= "});";
            $html .= "break;";
            $html .= "case 'LEVEL':";
                $html .= "var contextMenu = new Ext.menu.Menu({";
                    $html .= "items: [{";
                        $html .= "text: '".EXPAND."'";
                        $html .= ",iconCls: 'icon-expand-all'";
                        $html .= ",handler: function(){";
                            $html .= "myNode = myTree.getNodeById(node.id);";
                            $html .= "myNode.reload();";
                            $html .= "myNode.expand(true, false);";
                        $html .= "}";  
                    $html .= "},{"; 
                        $html .= "text: '".COLLAPSE."'";
                        $html .= ",iconCls: 'icon-collapse-all'";
                        $html .= ",handler: function(){";
                            $html .= "myNode = myTree.getNodeById(node.id);";
                            $html .= "myNode.collapse(true, false);";
                        $html .= "}";  
                    $html .= "},{";  
                    $html .= "text: '".MAIN_CONTENT."'";
                        $html .= ",iconCls: 'icon-application_form_magnify'";
                        $html .= ",handler: function(){";
                            $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                            $html .= "clickOpenPage('center','".MAIN_CONTENT."', '".$this->URL_LEVEL."objectId=' + node.id);";
                        $html .= "}";  
                    $html .= "}]"; 
                $html .= "});";
            $html .= "break;";
            $html .= "case 'TERM':";
                $html .= "var contextMenu = new Ext.menu.Menu({";
                    $html .= "items: [{";
                        $html .= "text: '".EXPAND."'";
                        $html .= ",iconCls: 'icon-expand-all'";
                        $html .= ",handler: function(){";
                            $html .= "myNode = myTree.getNodeById(node.id);";
                            $html .= "myNode.reload();";
                            $html .= "myNode.expand(true, false);";
                        $html .= "}";  
                    $html .= "},{"; 
                        $html .= "text: '".COLLAPSE."'";
                        $html .= ",iconCls: 'icon-collapse-all'";
                        $html .= ",handler: function(){";
                            $html .= "myNode = myTree.getNodeById(node.id);";
                            $html .= "myNode.collapse(true, false);";
                        $html .= "}";  
                    $html .= "},{"; 
                    $html .= "text: '".MAIN_CONTENT."'";
                        $html .= ",iconCls: 'icon-application_form_magnify'";
                        $html .= ",handler: function(){";
                            $html .= "Ext.getCmp('center').getLayout().setActiveItem(0);";
                            $html .= "clickOpenPage('center','".MAIN_CONTENT."', '".$this->URL_TERM."objectId=' + node.id);";
                        $html .= "}";
                    $html .= "}]"; 
                $html .= "});";
            $html .= "break;";
            $html .= "case 'CLASS':";
                $html .= "clickOpenPage('center','".SHOW_DETAIL."', '".$this->URL_CLASS."objectId=' + node.id);";
            $html .= "break;";
        $html .= "}";
        $html .= "event.stopEvent();";
        $html .= "contextMenu.showAt(event.xy);";
    $html .= "});";
    echo $html;
    ?>
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>