<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once 'models/app_school/AcademicDateDBAccess.php';
require_once setUserLoacalization();   

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$schoolyearId = isset($_GET["schoolyearId"])?addText($_GET["schoolyearId"]):"";
$tutor = isset($_GET["tutor"])?$_GET["tutor"]:"";
$entries = StaffDBAccess::getClassesByTutor($tutor, $schoolyearId);

$data = array();
if($entries){
    foreach($entries as $value){
        $data[$value->ID] = $value->ID;
    }
}

$Ids = implode(",",$data);

$OBJECT_GRID = new CamemisGrid("STUDENT", "ENROLLED_STUDENTS");
$OBJECT_GRID->setLoadUrl("/student/jsonload/");
$OBJECT_GRID->setSaveUrl("/student/jsonsave/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>

<script>
    Ext.onReady(function() {
        
        function cssText(value, metadata, record){
            return '<div style="font-weight:normal; color:#333; padding: 3px; height:10px;;">' + value + '</div>';
        }
        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        ///////////////////////////////////////////////////////
        /// ASSIGNED STUDENT...
        ///////////////////////////////////////////////////////
        $OBJECT_GRID->addReadField("name: 'CODE'");
        $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
        $OBJECT_GRID->addReadField("name: 'LASTNAME'");
        $OBJECT_GRID->addReadField("name: 'GENDER'");
        $OBJECT_GRID->addReadField("name: 'DATE_BIRTH'");
        $OBJECT_GRID->addReadField("name: 'PHONE'");
        $OBJECT_GRID->addReadField("name: 'EMAIL'");
        $OBJECT_GRID->addReadField("name: 'CLASS_NAME'");

        if(!SchoolDBAccess::displayPersonNameInGrid()){
            $OBJECT_GRID->addColumn("header: '<b>" . LASTNAME . "</b>', width: 120, renderer: cssText, sortable: false, dataIndex: 'LASTNAME'");
            $OBJECT_GRID->addColumn("header: '<b>" . FIRSTNAME . "</b>', width: 120, renderer: cssText, sortable: false, dataIndex: 'FIRSTNAME'");
	}else{
            $OBJECT_GRID->addColumn("header: '<b>" . FIRSTNAME . "</b>', width: 120, renderer: cssText, sortable: false, dataIndex: 'FIRSTNAME'");
            $OBJECT_GRID->addColumn("header: '<b>" . LASTNAME . "</b>', width: 120, renderer: cssText, sortable: false, dataIndex: 'LASTNAME'");
	}
        $OBJECT_GRID->addColumn("header: '<b>" . GENDER . "</b>', width: 110, renderer:cssText, sortable: true, dataIndex: 'GENDER'");
        $OBJECT_GRID->addColumn("header: '<b>" . DATE_BIRTH . "</b>', width: 120, renderer:cssText, sortable: true, dataIndex: 'DATE_BIRTH'");
        $OBJECT_GRID->addColumn("header: '<b>" . PHONE . "</b>', width: 150, renderer:cssText, sortable: true, dataIndex: 'PHONE'");
        $OBJECT_GRID->addColumn("header: '<b>" . EMAIL . "</b>', width: 150, renderer:cssText, sortable: true, dataIndex: 'EMAIL'");
        $OBJECT_GRID->addColumn("header: '<b>" .CURRENT_CLASS . "</b>', width: 150, renderer:cssText, sortable: true, dataIndex: 'CLASS_NAME'");
        
        $OBJECT_GRID->baseParams = "
            start:0
            ,limit:100
            ,classId: '" . $Ids . "'
            ,cmd: 'jsonListStudentsByClass'
        ";
        
        /////////////////////////////////////////
        $OBJECT_GRID->isQuickySearch = true;
        $OBJECT_GRID->isCheckboxSelect = false;
        $OBJECT_GRID->forceFit = "false";
        $OBJECT_GRID->removeNAME = "STUDENT_NAME";
        $OBJECT_GRID->renderJS();

        ?>                
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                border: false
                ,id:'center'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{xtype: '<?= $OBJECT_GRID->getObjectXType(); ?>'}]
            }]
        });
        <?
        $CONTEXT_ITEMS = array();
        
        $DETAIL_INFORMATION = "
        {
            text: '".DETAIL_INFORMATION." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME
            ,iconCls:'icon-application_form_magnify'
            ,handler:function(){
                clickOpenPage('center','','/student/studentmonitor/?&target=".camemisId()."&objectId=' + record.data.ID);
            }
        }
        ";
        if(UserAuth::getACLValue("STUDENT_PERSONAL_IMAGE_READ_RIGHT"))
        $CONTEXT_ITEMS[] = $DETAIL_INFORMATION;
        
        $TEACHER_COMMENTS = "
        {
            text: '".TEACHER_COMMENTS." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME
            ,iconCls:'icon-application_form_add'
            ,handler:function(){
                clickOpenPage('content',record.data.LASTNAME + ' ' + record.data.FIRSTNAME,'/note/?target=1&classId=".$this->objectId."&objectId=' + record.data.ID);
            }
        }
        ";
        if(UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT"))
        $CONTEXT_ITEMS[] = $TEACHER_COMMENTS;

        $CLASS_TRANSFER = "
        {
            text: '".CLASS_TRANSFER." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME
            ,iconCls:'icon-arrow_switch'
            ,handler:function(){
                openWinIFrame('', '/student/classtransfer/?classId=".$this->objectId."&objectId=' + record.data.ID + '&target=cancel',500,250);
            }
        }
        ";
        if(UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT"))
        $CONTEXT_ITEMS[] = $CLASS_TRANSFER;

        $STUDENT_REMOVE_FROM_CLASS = "
        {
            text: '".REMOVE." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME
            ,iconCls:'icon-delete'
            ,handler:function(){
                deleteItem(record.data.ID, $this->objectId);    
            }
        }
        ";
        if(UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT"))
        $CONTEXT_ITEMS[] = $STUDENT_REMOVE_FROM_CLASS;

        //@veasna
        $SEND_MESSAGE ="
        {
            text: '".SEND." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME
            ,iconCls: 'icon-email_add'
            ,disabled:true
            ,handler: function(){  
                openWinIFrame('Mail &raquo; '  + record.data.LASTNAME + ' ' + record.data.FIRSTNAME, '/dataset/sendemail/?objectId=' + record.data.ID,550,percentHeight(85));
            }
        }
        ";
        $CONTEXT_ITEMS[] =$SEND_MESSAGE;

        $ATTENDANCE ="
        {
            text: '".ATTENDANCE." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME
            ,iconCls: 'icon-clock_edit'
            ,disabled:true
            ,handler: function(){  

            }
        }
        ";
        $CONTEXT_ITEMS[] = $ATTENDANCE;

        $DISCIPLINE ="
        {
            text: '".DISCIPLINE." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME
            ,iconCls: 'icon-clock_edit'
            ,disabled:true
            ,handler: function(){  

            }
        }
        ";
        $CONTEXT_ITEMS[] = $DISCIPLINE;
        $SEND_SMS ="
        {
            text: '".SMS_STUDENT." &raquo; ' + record.data.STUDENT
            ,iconCls: 'icon-email_add'
            ,disabled:true
            ,handler: function(){  

            }
        }
        ";
        $CONTEXT_ITEMS[] =$SEND_SMS;
        //
        
        $CHOOSE_CONTEXT_ITEMS = implode(',', $CONTEXT_ITEMS);
        
        $js = "";
        $js .= "var myGrid = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');";
        $js .= "if (myGrid) myGrid.on('cellclick', function(grid, rowIndex, columnIndex, event) {";
            $js .= "var record = grid.store.getAt(rowIndex);";
            $js .= "var contextMenu = new Ext.menu.Menu({";
                $js .= "items: [".$CHOOSE_CONTEXT_ITEMS."]";
            $js .= "});";
            $js .= "event.stopEvent();";
            $js .= "contextMenu.showAt(event.xy);";
        $js .= "});";
        if ($CONTEXT_ITEMS) echo $js;
	
        ?>
   });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>