<?
require_once 'clients/app_admin/AdminPage.php';
require_once 'clients/app_admin/AdminPage.php';
require_once 'clients/app_admin/AdminForm.php';
require_once 'clients/app_admin/AdminGrid.php';
require_once 'clients/app_admin/AdminPage.php';
require_once 'models/app_admin/MyConfig.php';
require_once 'models/app_admin/AdminUserAuth.php';
require_once 'models/app_admin/DBWebservices.php';

$AdminPage = AdminPage::getInstance();
//$AdminPage->setLoadingMask = true;
print $AdminPage->showCamemisHeader();

$USER_PERMISSIONS = AdminUserAuth::getACLValue();

$HIDDEN_LOCAL = $USER_PERMISSIONS["LOCAL"]?"false":"true";
$HIDDEN_SETTINGS = $USER_PERMISSIONS["SETTINGS"]?"false":"true";
$HIDDEN_CAMEMIS_HELP = $USER_PERMISSIONS["CAMEMIS_HELP"]?"false":"true";

set_time_limit(120);
ini_set('memory_limit', '128M');
//DBWebservices::updateExternalLanguage("KHMER");

?>
<style>
    h1{
        font-size: 18px;
        color:#55555;
        font-weight: bold;
    }
</style>
<div id="initHeaderContent" class="x-hidden" style="padding-top: 10px;background-color:#4FACE0;color: #FFFFFF;">
    <h1 class="headerAdminTool">Welcome to VikenSoft-Administration Tools</h1>
</div>
<div id="iniSubContent" class="x-hidden" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="header">Please make your selection...</h1>
</div>
<script>
Ext.onReady(function() {
    
    Ext.state.Manager.setProvider(new Ext.state.CookieProvider());
    if (get_cookie('tokenId')) var tokenId = get_cookie('tokenId');
    <?
    $COLUMN_ITEM = "
    [{
        layout:'column'
        ,bodyStyle: 'background-color:#4FACE0'
        ,border: false
        ,items: [{
            border: false
            ,columnWidth: .50
            ,bodyStyle: 'background-color:#4FACE0'
            ,items:[{
                xtype:'box'
                ,anchor:''
                ,autoEl:{
                    tag:'div', children:[{
                        tag:'img'
                        ,style: 'margin-left: 10px; margin-top:0px'
                        ,qtip:'CAMEMIS Free Education Management Information System'
                        ,src:'".Zend_Registry::get('CAMEMIS_URL')."/public/images/camemis_default.png'
                    }]
                }
            }]
        },{
            border: false
            ,columnWidth: .50
            ,bodyStyle: 'background-color:#4FACE0'
            ,items:[{
                border: false
                ,bodyStyle: 'padding-top:10px; padding-right:15px; background-color:#4FACE0'
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,contentEl: 'initHeaderContent'
                }]
            }]
        }]
    }]
    ";
    
    $TBAR_ITEMS = "
    [{
        text: 'Localization'
        ,hidden: $HIDDEN_LOCAL
        ,iconCls: 'icon-tabs'
        ,handler: function(){
            clickOpenPage('VIEWPORT_CENTER', 'Localization', '/localization/');
        }
    },{
        text: 'CAMEMIS Help'
        ,hidden: $HIDDEN_CAMEMIS_HELP
        ,iconCls: 'icon-tabs'
        ,handler: function(){
            clickOpenPage('VIEWPORT_CENTER','', '/help/');
        }
    },{
        text: 'List of Schools'
        ,hidden:true
        ,iconCls: 'icon-tabs'
        ,handler: function(){
            clickOpenPage('VIEWPORT_CENTER', 'List of Schools', '/customer/');
        }
    },{
        text: 'Finance Management'
        ,hidden: true
        ,iconCls: 'icon-tabs'
        ,handler: function(){
            clickOpenPage('VIEWPORT_CENTER', 'Provider Management', '/provider/');
        }
    },{
        text: 'Learning Content Management'
        ,hidden:true
        ,iconCls: 'icon-tabs'
        ,menu:[{
            text: 'Category for Learning Content'
            ,iconCls: 'icon-tabs'
        },{
            text: 'Content from Youtube'
            ,iconCls: 'icon-tabs'
        },{
            text: 'Content from Vinhxuan'
            ,iconCls: 'icon-tabs'
        },{
            text: 'Content from Internet'
            ,iconCls: 'icon-tabs'
        }]
    },{
        text: 'Setting'
        ,hidden: $HIDDEN_SETTINGS
        ,iconCls: 'icon-tabs'
        ,menu:[{
            text: 'Location'
            ,hidden: $HIDDEN_SETTINGS
            ,iconCls: 'icon-tabs'
            ,handler: function(){
                clickOpenPage('VIEWPORT_CENTER', 'Local', '/main/local/');
            }
        },{
            text: 'Application User Role/Rights'
            ,iconCls: 'icon-tabs'
            ,hidden: $HIDDEN_SETTINGS
            ,handler: function(){
                clickOpenPage('VIEWPORT_CENTER', 'Application User Role/Rights', '/app/');
            }
        },{
            text: 'Database'
            ,iconCls: 'icon-tabs'
            ,menu:[{
                text: 'Add table'
                ,iconCls: 'icon-application_form_add'
                ,hidden: $HIDDEN_SETTINGS
                ,handler: function(){
                    clickOpenPage('VIEWPORT_CENTER', 'Add table', '/main/database/?type=add_table');
                }
            },{
               text: 'Delete table'
               ,iconCls: 'icon-delete'
               ,hidden: $HIDDEN_SETTINGS
               ,handler: function(){
                    clickOpenPage('VIEWPORT_CENTER', 'Delete table', '/main/database/?type=delete_table');
                }
            },{
                text: 'Add table column'
               ,iconCls: 'icon-application_form_add'
               ,hidden: $HIDDEN_SETTINGS
               ,handler: function(){
                    clickOpenPage('VIEWPORT_CENTER', 'Add table column', '/main/database/?type=add_column');
                }
            },{
                text: 'Change table column'
               ,iconCls: 'icon-pencil'
               ,hidden: $HIDDEN_SETTINGS
               ,handler: function(){
                    clickOpenPage('VIEWPORT_CENTER', 'Change table column', '/main/database/?type=update_column');
                }
            },{
                text: 'Delete table column'
                ,iconCls: 'icon-delete'
                ,hidden: $HIDDEN_SETTINGS
                ,handler: function(){
                    clickOpenPage('VIEWPORT_CENTER', 'Delete table column', '/main/database/?type=delete_column');
                }
            },{
                text: 'SQL Statements'
                ,iconCls: 'icon-page_white_text'
                ,hidden: $HIDDEN_SETTINGS
                ,handler: function(){
                    clickOpenPage('VIEWPORT_CENTER', 'SQL Statements', '/main/database/?type=statements');
                }
            }]
        }]
    ,},{
        text: 'User Management'
        ,hidden: true
        ,iconCls: 'icon-tabs'
        ,handler: function(){
            clickOpenPage('VIEWPORT_CENTER', 'List of Users', '/main/users/');
        }
    },'->',{
        text: 'Logout...'
        ,iconCls: 'icon-tabs'
        ,handler: function(){
            Ext.MessageBox.confirm('Confirmation!', 'Would you like to log off the system?', showResult);
        }
    }]
    ";
    
    if($USER_PERMISSIONS["LOCAL"]){
        $defaultUrl = "/localization";
    }elseif($USER_PERMISSIONS["CAMEMIS_HELP"]){
        $defaultUrl = "/help";
    }
    
    ?>
    Ext.QuickTips.init();
    
    if (tokenId){
        viewport = new Ext.Viewport({
            layout:'border'
            ,defaults: {
                collapsible: false
                ,split: false
                ,border: false
            },
            items: [{
                region: 'center'
                ,layout: 'fit'
                ,xtype:'panel'
                ,items:[{
                    layout:'border'
                    ,defaults: {
                        collapsible: false
                        ,split: false
                    },
                    items: [{
                        region: 'north'
                        ,id: 'VIEWPORT_NORTH'
                        ,collapsible: false
                        ,height: 60
                        ,minSize: 60
                        ,maxSize: 60
                        ,margins: '0 0 0 0'
                        ,bodyStyle: 'background-color:#4FACE0'
                        ,items: <?=$COLUMN_ITEM;?>
                    },{
                        collapsible: false
                        ,region:'center'
                        ,id: 'VIEWPORT_CENTER'
                        ,margins: '0 0 0 0'
                        ,layout: 'card'
                        ,activeItem: 0
                        ,items:[new Ext.ux.IFrameComponent({ id: 'IFRAM_ID', url: '<?=$defaultUrl;?>'})]
                        ,tbar: <?=$TBAR_ITEMS;?>
                    }]
                }]
            }]
        });
    }else{
        window.location.href='<?=Zend_Registry::get('CAMEMIS_URL')?>/';
    }
    function showResult(btn){
        if (btn == "yes"){
            Ext.Ajax.request({
                url: '/main/jsonsave/'
                ,method: 'POST'
                ,params: {cmd:'jsonLogout'}
                ,success: function(response, options) {
                    window.location.href='/';
                }
            });
        }
    };
});
</script>
<?
print $AdminPage->showCamemisFooter();
?>