<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();
$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_GRID = new CamemisGrid("HOMEWORK", "LIST");
$OBJECT_GRID->setLoadUrl('/homework/jsonload/');
$OBJECT_GRID->setSaveUrl('/homework/jsonsave/');

$classId = isset($_GET["classId"])?addText($_GET["classId"]):"";
$teacherId = isset($_GET["teacherId"])?addText($_GET["teacherId"]):"";
$subjectId = isset($_GET["subjectId"])?addText($_GET["subjectId"]):"";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<script>
var studentId;
Ext.onReady(function() {
    
    function deleteItem(Id){
        window.parent.Ext.MessageBox.show({
            title:'<?=WARNING?>'
            ,width: 350
            ,msg:'<?=DELETE_THIS_ITEM?>'
            ,buttons: Ext.MessageBox.YESNOCANCEL
            ,icon: Ext.MessageBox.QUESTION
            ,fn: function(btn){
                if (btn === 'yes'){
                    Ext.Ajax.request({
                        url: '/homework/jsonsave/'
                        ,method: 'POST'
                        ,params: {cmd: 'jsonRemoveStudentSubjectHomework',studentId:Id}                           
                        ,success: function(response, options) {Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>').store.reload();}
                        ,failure: function(response, options) {}
                    });
                }
            }
            ,icon:Ext.MessageBox.INFO
        });
    }
    
    function cssTextBold(value, metadata, record){
          return '<div style="margin: 3px 10px 3px 10px; font-weight:normal; color:#333; white-space:normal;">' + value + '</div>';
    }
    function cssText(value, metadata, record){
        return '<div style="margin: 3px 10px 3px 10px; font-weight:normal; color:#333; white-space:normal;">' + value + '</div>';
    }
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addReadField("name: 'FULL_NAME'");           
    $OBJECT_GRID->addReadField("name: 'SUBJECT_NAME'");
    $OBJECT_GRID->addReadField("name: 'TITLE_NAME'");
    $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");
    $OBJECT_GRID->addReadField("name: 'STUDENT_ID'");
    
    $OBJECT_GRID->addColumn("header: '<b>".STUDENT."</b>', hidden: false,renderer:cssTextBold, align:'left', menuDisabled : true, sortable: true, width:180, dataIndex: 'FULL_NAME'");                                                                                                                                                                  
    $OBJECT_GRID->addColumn("header: '<b>".SUBJECT."</b>',hidden: false, align:'left', menuDisabled : true, sortable: true, width:180, dataIndex: 'SUBJECT_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".HOMEWORK_NAME."</b>', hidden: false,renderer:cssTextBold, align:'left', menuDisabled : true, sortable: true, width:180, dataIndex: 'TITLE_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_DATE."</b>', hidden: false,renderer:cssTextBold, align:'left', menuDisabled : true, sortable: true, width:180, dataIndex: 'CREATED_DATE'");
    
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'CANCEL_ID'
            ,text: '".CANCEL."'
            ,iconCls:'icon-cancel'
            ,handler: function(){
                window.parent.parent.Ext.getCmp('content').getLayout().setActiveItem(0);
            }
        }]);
    ");
        
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonLoadStudentSubjectHomework'  
        ,objectId: '".$this->objectId."'
    ";
     
    $OBJECT_GRID->loadMask = false;
    $OBJECT_GRID->isQuickySearch = true;
    $OBJECT_GRID->isObjectDefaultOnLoad = true; 
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();  
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,id:'content'
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType()?>'}]
        }]
    });
    
    <?  

    switch(UserAuth::getUserType()){
        case "TEACHER":
        case "INSTRUCTOR":
                if(Zend_Registry::get('USER')->ID == $teacherId ){$active = false;}
                else{$active = true;}  
            break;
        case "SUPERADMIN":
        case "ADMIN":
                $active = true;
            break;
    }
    
    $CONTEXT_ITEMS = array(); 
    $DETAIL_INFORMATION = "
    {
        text: '".DETAIL_INFORMATION." &raquo; ' + record.data.FULL_NAME
        ,iconCls:'icon-application_form_magnify'
        ,handler:function(){
            clickOpenPage('content','".SHOW_DETAIL."','/homework/studentinfo/?studentId=' + record.data.STUDENT_ID);
        }
    }
    ";  
    $CONTEXT_ITEMS[] = $DETAIL_INFORMATION;
    
    $STUDENT_REMOVE_FROM_CLASS = "{                             
        text: '".REMOVE." &raquo; ' + record.data.FULL_NAME
        ,iconCls:'icon-delete'
        ,hidden:'".$active."' 
        ,handler:function(){    
            deleteItem(record.data.STUDENT_ID, $this->objectId); 
        }
    }";  
    $CONTEXT_ITEMS[] = $STUDENT_REMOVE_FROM_CLASS;   
             
    $CHOOSE_CONTEXT_ITEMS = implode(',', $CONTEXT_ITEMS);
    
    if(UserAuth::getUserType() != "STUDENT"){
        $js = "";
        $js .= "var myGrid = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');";
        $js .= "if (myGrid) myGrid.on('cellclick', function(grid, rowIndex, columnIndex, event) {";
        if(UserAuth::getUserType() == "INSTRUCTOR"){
            $js .="if(columnIndex>1){";
                $js .= "var record = grid.store.getAt(rowIndex);studentId=record.data.STUDENT_ID;";
                $js .= "var contextMenu = new Ext.menu.Menu({";
                    $js .= "items: [".$CHOOSE_CONTEXT_ITEMS."]";
                $js .= "});";
                $js .= "event.stopEvent();";
                $js .= "contextMenu.showAt(event.xy);";
            $js .="}";
        }else{
            $js .= "var record = grid.store.getAt(rowIndex);";
            $js .= "var contextMenu = new Ext.menu.Menu({";
                $js .= "items: [".$CHOOSE_CONTEXT_ITEMS."]";
            $js .= "});";
            $js .= "event.stopEvent();";
            $js .= "contextMenu.showAt(event.xy);";
        }
        $js .= "});";
        if ($CONTEXT_ITEMS) echo $js;
    }
    ?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>