<?
/*
$TREE_NODE = "";
$TREE_NODE .= "[";
    $TREE_NODE .= "{";
        $TREE_NODE .= "text: '".SETTING."'";
        $TREE_NODE .= ",iconCls: 'icon-application_form_magnify'";
        $TREE_NODE .= ",cls:'nodeTextBold'";
        $TREE_NODE .= ",isClick:false,leaf: true";
        $TREE_NODE .= ",url:''";
    $TREE_NODE .= "}";
    $TREE_NODE .= ",{";
        $TREE_NODE .= "text: '".STATISTIC."'";
        $TREE_NODE .= ",iconCls: 'icon-folder_magnify'";
        $TREE_NODE .= ",cls:'nodeTextBold'";
        $TREE_NODE .= ",expanded: true";
        $TREE_NODE .= ",isClick:false";
        $TREE_NODE .= ",url:''";
        $TREE_NODE .= ",children: [{
            text:'2013'
            ,id:'2013'
            ,iconCls: 'icon-date'
            ,leaf: true
            ,isClick:false
        },{
            text:'2014'
            ,id:'2014'
            ,iconCls: 'icon-date'
            ,leaf: true
            ,isClick:false
        },{
            text:'2015'
            ,id:'2015'
            ,iconCls: 'icon-date'
            ,leaf: true
            ,isClick:false
        },{
            text:'2016'
            ,id:'2016'
            ,iconCls: 'icon-date'
            ,leaf: true
            ,isClick:false
        },{
            text:'2017'
            ,id:'2017'
            ,iconCls: 'icon-date'
            ,leaf: true
            ,isClick:false
        }]";
    $TREE_NODE .= "}";

$TREE_NODE .= "]";

$OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
$OBJECT_TREE->backgroundColor = "#F9F9F9";
$OBJECT_TREE->isAsyncTreeNode = true;
$OBJECT_TREE->setAsyncTreeNode($TREE_NODE);
$OBJECT_TREE->renderJS();
*/
?>
<html>
    <head>
        <title><?= Zend_Registry::get('TITLE');?></title>
        <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/css/main.css" />
        <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/css/login.css" />
        <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/resources/css/ext-all.css" />
        <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/plugin/Cookies.js"></script>
        <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/adapter/ext/ext-base.js"></script>
        <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/ext-all.js"></script>
    </head>
    <body bgcolor="#FFFFFF">
        <div id="initCenter" class="x-hide-display" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
        <h1 class="headerExpired">Your session has expired, please log in again.</h1>
        <br>
        <a href=# onClick="javascript:parent.parent.parent.parent.parent.parent.window.location='<?=Zend_Registry::get('CAMEMIS_URL')?>/'"><b>Login...</b></a>
        </div>
        <script>
            Ext.onReady(function() {
                viewport = new Ext.Viewport({
                layout: 'fit'
                ,border: false
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,contentEl: 'initCenter'
                }]
            });
        });
        </script>
    </body>
</html>