<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 22.12.2012
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("USERROLE", "LIST");
$OBJECT_TREE->setURL("/userrole/jsontree/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
	
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    $OBJECT_TREE->setBaseParams("
    	cmd: 'jsonTreeAllRights'
        ,treeSearch:'treeall'
        ,searchParent: '".$this->searchParent."'
        ,objectId: '".$this->objectId."'
    ");
    
    $OBJECT_TREE->isTreeExpand = false;
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'fit'
            ,border: false
            ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
        }]
    });
    
    var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('checkchange', function(node, checked){

        Ext.Ajax.request({
            url: '/userrole/jsonsave/'
            ,method: 'POST'
            ,params: {
                cmd: 'jsonActionUserRight'
                ,checked:checked
                ,rightId: node.id
                ,roleId: '<?=$this->objectId;?>'
            }
            ,success: function(response, options) {
                result = Ext.util.JSON.decode(response.responseText);
                XMsg('<?=STATUS?>',result.msg);
                /*
                if(node.attributes.reloadId){
                    myNode = myTree.getNodeById(node.attributes.reloadId);
                    if(myNode){
                        myNode.reload();
                        myNode.expand(true, false); 
                    }
                }
                */
            }
        });
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>