<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

set_time_limit(120);
$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$DB_SCHOOLYEAR = AcademicDateDBAccess::getInstance();

$OBJECT_FORM = new CamemisForm("ACADEMIC");
$OBJECT_FORM->setLoadUrl('/academic/jsonload/');
$OBJECT_FORM->setSaveUrl('/academic/jsonsave/');

if(!$this->facette) {header("Location: /main/permission/");exit;}

AcademicDBAccess::mappingAcademicSchoolyear($this->facette);

$CURRENT_SCHOOLYEAR = $DB_SCHOOLYEAR->isCurrentSchoolyear($this->facette->SCHOOL_YEAR);
$TERM_NUMBER = AcademicDBAccess::findAcademicTerm($this->facette->SCHOOL_YEAR);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

class ViewportItem {

    public function __construct($objectId, $urlEncryp){
        $this->objectId = $objectId;
        $this->urlEncryp = $urlEncryp;
    }

    function getTermPanel($const, $datefield){
        $ext = "{";
            $ext .="title:'".constant($const)."'";
            $ext .=",tbar:['->','-',{text:'".CHANGE."'";
                $ext .=",iconCls:'icon-lightning'";
                $ext .=",handler:function(){";
                    $ext .="openWinIFrame('".constant($const)."', '/academic/datesetting/?camIds=".$this->urlEncryp->encryptedGet("&objectId=".$this->objectId."&target=".$const."")."', 500, 250);";
                $ext .="}";
            $ext .="}]";
            $ext .=",items:[{";
                $ext .="layout: 'form'";
                $ext .=",border: false";
                $ext .=",autoHeight:true";
                $ext .=",bodyStyle: 'padding:15px'";
                $ext .=",items:[{";
                    $ext .="".CamemisField::Displayfield("".$datefield."_START",START_DATE,false)."";
                $ext .="},{";
                    $ext .="".CamemisField::Displayfield("".$datefield."_END",END_DATE,false)."";
                $ext .="}]";
            $ext .="}]";
        $ext .="}";
        
        return $ext;
    }
}

$viewportItem = new ViewportItem(
    $this->objectId
    , $this->urlEncryp
);

?>

<script>
        
    Ext.onReady(function() {

        Ext.form.Field.prototype.msgTarget = 'side';

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        $ENROLLMENT_TYPE_STORE = "[";
            $ENROLLMENT_TYPE_STORE .= "[0, '" . ENROLLMENT_IN_SCHOOLYEAR_N_CLASS . "']";
        $ENROLLMENT_TYPE_STORE .= "]";
        
        if($this->facette->EDUCATION_SYSTEM){
            $DETAIL_INFORMATION_ITEMS = "[
                {".CamemisField::Textfield("NAME_ID", "NAME", NAME, true)."}
                ,{".CamemisField::Numberfield("NUMBER_CREDIT", "NUMBER_CREDIT", NUMBER_CREDIT, false, false, false)."}
                ,{".CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false)."}
            ]";
        }else{
            $DETAIL_INFORMATION_ITEMS = "[
                {".CamemisField::Textfield("NAME_ID", "NAME", NAME, true)."}
                ,{".CamemisField::Checkbox("USE_OF_GROUPS","USE_OF_GROUPS",USE_OF_GROUPS, 1, false, false,true)."}    
                ,{".CamemisField::Combo('ENROLLMENT_TYPE', ENROLLMENT_TYPE, $ENROLLMENT_TYPE_STORE, false, false, false, false,false)."}
                ,{".CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false)."}
            ]";
        }

        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width:550
            ,autoHeight: true
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: ".$DETAIL_INFORMATION_ITEMS."
            }]
        }
        ";

        ////////////////////////////////////////////////////////////////////////
        //@CHANGE ACADEMIC DATE - Sea Peng
        ////////////////////////////////////////////////////////////////////////
        $ACADEMIC_DATE = "
        {
            title:'".ACADEMIC_DATE."'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:15px'
                ,items:[{
                    ".CamemisField::Displayfield("SCHOOLYEAR_START",START_DATE,false)."
                },{
                    ".CamemisField::Displayfield("SCHOOLYEAR_END",END_DATE,false)."
                }]
            }]
        }
        ";
        
        $ACADEMIC_DATE_SETTING_ITEMS = "[";

        $ACADEMIC_DATE_SETTING_ITEMS .= $ACADEMIC_DATE;

        switch ($TERM_NUMBER) {
            case 1:
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('FIRST_TERM', 'TERM1');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('SECOND_TERM', 'TERM2');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('THIRD_TERM', 'TERM3');
                break;
            case 2:
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('FIRST_QUARTER', 'QUARTER1');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('SECOND_QUARTER', 'QUARTER2');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('THIRD_QUARTER', 'QUARTER3');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('FOURTH_QUARTER', 'QUARTER4');
                break;
            default:
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('FIRST_SEMESTER', 'SEMESTER1');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('SECOND_SEMESTER', 'SEMESTER2');
                break;
        }

        $ACADEMIC_DATE_SETTING_ITEMS .= "]";

        $FORMULA_TERM_RESULT_STORE = "[";
        switch ($TERM_NUMBER) {
            case 1:
                $TITLE_FORMULA_TERM_RESULT = TERM_RESULT;
                $FORMULA_TERM_RESULT_STORE .= "[0, 'AVG(M)+AVG(T)']";
                $FORMULA_TERM_RESULT_STORE .= ",[1, 'AVG(T)']";
                break;
            case 2:
                $TITLE_FORMULA_TERM_RESULT = QUARTER_RESULT;
                $FORMULA_TERM_RESULT_STORE .= "[0, 'AVG(M)+AVG(Q)']";
                $FORMULA_TERM_RESULT_STORE .= ",[1, 'AVG(Q)']";
                break;
            default:
                $TITLE_FORMULA_TERM_RESULT = SEMESTER_RESULT;
                $FORMULA_TERM_RESULT_STORE .= "[0, 'AVG(M)+AVG(S)']";
                $FORMULA_TERM_RESULT_STORE .= ",[1, 'AVG(S)']";
                break;   
        }
        $FORMULA_TERM_RESULT_STORE .= "]";
        
        $DIVISION_NUMBER_ITEMS = "[";
        $DIVISION_NUMBER_ITEMS .= "{".CamemisField::Numberfield("PERFORMANCE_MONTH_DIVISION_VALUE","PERFORMANCE_MONTH_DIVISION_VALUE", MONTHLY_RESULT, false, false, false, false, false, 50)."}";
        switch ($TERM_NUMBER) {
            case 1:
                $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("PERFORMANCE_FIRST_DIVISION_VALUE","PERFORMANCE_FIRST_DIVISION_VALUE", FIRST_TERM_RESULT, false, false, false, false, false, 50)."}";
                $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("PERFORMANCE_SECOND_DIVISION_VALUE","PERFORMANCE_SECOND_DIVISION_VALUE", SECOND_TERM_RESULT, false, false, false, false, false, 50)."}";
                $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("PERFORMANCE_THIRD_DIVISION_VALUE","PERFORMANCE_THIRD_DIVISION_VALUE", THIRD_TERM_RESULT, false, false, false, false, false, 50)."}";   
                break;
            case 2:
                $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("PERFORMANCE_FIRST_DIVISION_VALUE","PERFORMANCE_FIRST_DIVISION_VALUE", FIRST_QUARTER_RESULT, false, false, false, false, false, 50)."}";
                $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("PERFORMANCE_SECOND_DIVISION_VALUE","PERFORMANCE_SECOND_DIVISION_VALUE", SECOND_QUARTER_RESULT, false, false, false, false, false, 50)."}";
                $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("PERFORMANCE_THIRD_DIVISION_VALUE","PERFORMANCE_THIRD_DIVISION_VALUE", THIRD_QUARTER_RESULT, false, false, false, false, false, 50)."}";
                $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("PERFORMANCE_FOURTH_DIVISION_VALUE","PERFORMANCE_FOURTH_DIVISION_VALUE", FOURTH_QUARTER_RESULT, false, false, false, false, false, 50)."}";
                break;
            default:
                $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("PERFORMANCE_THIRD_DIVISION_VALUE","PERFORMANCE_THIRD_DIVISION_VALUE", FIRST_SEMESTER_RESULT, false, false, false, false, false, 50)."}";
                $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("PERFORMANCE_SECOND_DIVISION_VALUE","PERFORMANCE_SECOND_DIVISION_VALUE", SECOND_SEMESTER_RESULT, false, false, false, false, false, 50)."}";
                break;   
        }
        $DIVISION_NUMBER_ITEMS .= "]";
        
        $ACADEMIC_DATE_SETTING = "
        {
            title: '".ACADEMIC_DATE."'
            ,collapsible: true
            ,collapsed: false
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px'
                ,border: false
                ,height:160
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:".$ACADEMIC_DATE_SETTING_ITEMS."
                }]
            }]
        }
        ";

        ////////////////////////////////////////////////////////////////////////
        //@EVALUATION SETTING - Sea Peng
        ////////////////////////////////////////////////////////////////////////
        $EVALUATION_TYPE_STORE = "[
            [0, '" . NUMBER . "']
            ,[1, '".PERCENTAGE."']
        ]";

        if($this->facette->EVALUATION_TYPE){
            $HIDDEN = true;
        }else{
            $HIDDEN = false;
        }

        $AVERAGE_STORE = "[";
        switch ($TERM_NUMBER) {
            case 1:
                $AVERAGE_STORE .= "[0, 'AVG(T1+T2+T3)']";
                $AVERAGE_STORE .= ",[1, 'AVG(T1)']";
                $AVERAGE_STORE .= ",[2, 'AVG(T2)']";
                $AVERAGE_STORE .= ",[3, 'AVG(T3)']";
                break;
            case 2:
                $AVERAGE_STORE .= "[0, 'AVG(Q1+Q2+Q3+Q4)']";
                $AVERAGE_STORE .= ",[1, 'AVG(Q1)']";
                $AVERAGE_STORE .= ",[2, 'AVG(Q2)']";
                $AVERAGE_STORE .= ",[3, 'AVG(Q3)']";
                $AVERAGE_STORE .= ",[4, 'AVG(Q4)']";
                break;
            default:
                $AVERAGE_STORE .= "[0, 'AVG(S1+S2)']";
                $AVERAGE_STORE .= ",[1, 'AVG(S1)']";
                $AVERAGE_STORE .= ",[2, 'AVG(S2)']";
            break;
        }

        $AVERAGE_STORE .= "]";

        $DISPLAYING = "[";
            $DISPLAYING .= "{".CamemisField::Checkbox("DISPLAY_MONTH_RESULT","DISPLAY_MONTH_RESULT",MONTHLY_RESULT, 1, false, false)."}";
            switch ($TERM_NUMBER) {
                case 1:
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_FIRST_RESULT","DISPLAY_FIRST_RESULT",FIRST_TERM_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_SECOND_RESULT","DISPLAY_SECOND_RESULT",SECOND_TERM_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_THIRD_RESULT","DISPLAY_THIRD_RESULT",THIRD_TERM_RESULT, 1, false, false)."}";
                    break;
                case 2:
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_FIRST_RESULT","DISPLAY_FIRST_RESULT",FIRST_QUARTER_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_SECOND_RESULT","DISPLAY_SECOND_RESULT",SECOND_QUARTER_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_THIRD_RESULT","DISPLAY_THIRD_RESULT",THIRD_QUARTER_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_FOURTH_RESULT","DISPLAY_FOURTH_RESULT",FOURTH_QUARTER_RESULT, 1, false, false)."}";
                    break;
                default:
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_FIRST_RESULT","DISPLAY_FIRST_RESULT",FIRST_SEMESTER_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_SECOND_RESULT","DISPLAY_SECOND_RESULT",SECOND_SEMESTER_RESULT, 1, false, false)."}";
                    break;    
            }
            $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_YEAR_RESULT","DISPLAY_YEAR_RESULT",YEAR_RESULT, 1, false, false)."}";
            $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_GPA","DISPLAY_GPA",GPA, 1, false, false)."}";
            $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_GRADE_POINTS","DISPLAY_GRADE_POINTS",GRADE_POINTS, 1, false, false)."}";
        $DISPLAYING .= "]";
        
        $WEIGHTING = "[";
            switch ($TERM_NUMBER) {
                case 1:
                    $WEIGHTING .= "{".CamemisField::Numberfield("SEMESTER1_WEIGHTING","SEMESTER1_WEIGHTING", FIRST_TERM, true, 1, false, false, false, 50)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("SEMESTER2_WEIGHTING","SEMESTER2_WEIGHTING", SECOND_TERM, true, 1, false, false, false, 50)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("TERM1_WEIGHTING","TERM1_WEIGHTING", THIRD_TERM, true, 1, false, false, false, 50)."}";   
                    break;
                case 2:
                    $WEIGHTING .= "{".CamemisField::Numberfield("SEMESTER1_WEIGHTING","SEMESTER1_WEIGHTING", FIRST_QUARTER, true, 1, false, false, false, 50)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("SEMESTER2_WEIGHTING","SEMESTER2_WEIGHTING", SECOND_QUARTER, true, 1, false, false, false, 50)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("TERM1_WEIGHTING","TERM1_WEIGHTING", THIRD_QUARTER, true, 1, false, false, false, 50)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("TERM2_WEIGHTING","TERM2_WEIGHTING", FOURTH_QUARTER, true, 1, false, false, false, 50)."}";
                    break;
                default:
                    $WEIGHTING .= "{".CamemisField::Numberfield("SEMESTER1_WEIGHTING","SEMESTER1_WEIGHTING", FIRST_SEMESTER, true, 1, false, false, false, 50)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("SEMESTER2_WEIGHTING","SEMESTER2_WEIGHTING", SECOND_SEMESTER, true, 1, false, false, false, 50)."}";
                    break;   
            }
            
        $WEIGHTING .= "]";

        $SCHOOLYEAR_SETTINGS = "
        {
            title: '".SETTINGS."'
            ,collapsible: true
            ,collapsed: false
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,bodyStyle: 'padding:15px'
            ,width: 550
            ,items:[{
                xtype:'fieldset'
                ,width: 500
                ,title:'".SESSION_GROUP."'
                ,collapsible: true
                ,collapsed: true
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle:'padding:15px;background:#d1ddef;'
                    ,items:[{
                        ".CamemisField::Checkbox("MULTIPLE_SESSIONS","MULTIPLE_SESSIONS",MULTIPLE_SESSIONS, 1, false, false)."
                    },{
                        layout: 'column'
                        ,id:'COL_FIRST_SESSION_GROUP'
                        ,hidden:true
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle:'padding:5px;background:#d1ddef;'
                        ,items:[{
                            columnWidth:280
                            ,border:false
                            ,layout: 'form'
                            ,bodyStyle:'background:#d1ddef;'
                            ,items: [{
                                xtype:'textfield'
                                ,fieldLabel: '".SESSION_GROUP." (1)'
                                ,name: 'FIRST_SESSION_GROUP'
                                ,width:200
                            }]
                        },{
                            columnWidth:20
                            ,border:false
                            ,layout: 'form'
                            ,bodyStyle:'background:#d1ddef;'
                            ,items: [{
                                xtype:'checkbox'
                                ,fieldLabel: ''
                                ,boxLabel:''
                                ,name: 'CHECK_FIRST_SESSION_GROUP'
                            }]
                        }]
                    },{
                        layout: 'column'
                        ,id:'COL_SECOND_SESSION_GROUP'
                        ,hidden:true
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle:'padding:5px;background:#d1ddef;'
                        ,items:[{
                            columnWidth:280
                            ,border:false
                            ,layout: 'form'
                            ,bodyStyle:'background:#d1ddef;'
                            ,items: [{
                                xtype:'textfield'
                                ,fieldLabel: '".SESSION_GROUP." (2)'
                                ,name: 'SECOND_SESSION_GROUP'
                                ,width:200
                            }]
                        },{
                            columnWidth:20
                            ,border:false
                            ,layout: 'form'
                            ,bodyStyle:'background:#d1ddef;'
                            ,items: [{
                                xtype:'checkbox'
                                ,fieldLabel: ''
                                ,boxLabel:''
                                ,name: 'CHECK_SECOND_SESSION_GROUP'
                            }]
                        }]
                    },{
                        layout: 'column'
                        ,id:'COL_THIRD_SESSION_GROUP'
                        ,hidden:true
                        ,border: false
                        ,autoHeight:true
                        ,bodyStyle:'padding:5px;background:#d1ddef;'
                        ,items:[{
                            columnWidth:280
                            ,border:false
                            ,layout: 'form'
                            ,bodyStyle:'background:#d1ddef;'
                            ,items: [{
                                xtype:'textfield'
                                ,fieldLabel: '".SESSION_GROUP." (3)'
                                ,name: 'THIRD_SESSION_GROUP'
                                ,width:200
                            }]
                        },{
                            columnWidth:20
                            ,border:false
                            ,layout: 'form'
                            ,bodyStyle:'background:#d1ddef;'
                            ,items: [{
                                xtype:'checkbox'
                                ,fieldLabel: ''
                                ,boxLabel:''
                                ,name: 'CHECK_THIRD_SESSION_GROUP'
                            }]
                        }]
                    }]
                }]
            },{
                xtype:'fieldset'
                ,width: 500
                ,title:'".EVALUATION_TYPE."'
                ,collapsible: true
                ,collapsed: true
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle:'padding:15px;background:#d1ddef;'
                    ,items:[
                        {".CamemisField::Combo('EVALUATION_TYPE', TYPE, $EVALUATION_TYPE_STORE, false, false, 150, false,false)."}
                        ,{html:'&nbsp;',border:false,bodyStyle:'background:#d1ddef;'}
                        ,{".CamemisField::Radio("EVALUATION_OPTION_1", "EVALUATION_OPTION", EVALUATION_OF_ASSIGNMENT,0, false)."}
                        ,{".CamemisField::Radio("EVALUATION_OPTION_2", "EVALUATION_OPTION", EVALUATION_OF_SUBJECT,1, false)."}
                        ,{html:'&nbsp;',border:false,bodyStyle:'background:#d1ddef;'}
                        ,{".CamemisField::Radio("GRADING_TYPE_1", "GRADING_TYPE", GRADING." (".ASSESSMENT.")",0, false)."}
                        ,{".CamemisField::Radio("GRADING_TYPE_2", "GRADING_TYPE", GRADING." (".LETTER_GRADE.")",1, false)."}
                    ]
                }]
            },{
                xtype:'fieldset'
                ,width: 500
                ,title:'".DISPLAYING."'
                ,collapsible: true
                ,collapsed: true
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle:'padding:15px;background:#d1ddef;'
                    ,items: ".$DISPLAYING."
                }]
            },{
                xtype:'fieldset'
                ,width: 500
                ,title:'".WEIGHTING."'
                ,collapsible: true
                ,collapsed: false
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle:'padding:15px;background:#d1ddef;'
                    ,items: ".$WEIGHTING."
                }]
            },{
                xtype:'fieldset'
                ,width: 500
                ,title:'".FORMULA_CALCULATOR."'
                ,collapsible: true
                ,collapsed: false
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle:'padding:15px;background:#d1ddef;'
                    ,items:[
                        {".CamemisField::Combo('FORMULA_TERM', $TITLE_FORMULA_TERM_RESULT, $FORMULA_TERM_RESULT_STORE, false, false,230, false,false)."}
                        ,{".CamemisField::Combo('FORMULA_YEAR', YEAR_RESULT, $AVERAGE_STORE, false, false, 230, false,false)."}
                    ]
                }]
            },{
                xtype:'fieldset'
                ,width: 500
                ,title:'".DIVISION_NUMBER."'
                ,collapsible: true
                ,collapsed: true
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle:'padding:15px;background:#d1ddef;'
                    ,items: ".$DIVISION_NUMBER_ITEMS."
                }]
            }]
        }
        ";
        ////////////////////////////////////////////////////////////////////////
        
        $WORKING_DAYS = "
        {
            title: '".WORKING_DAYS."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,bodyStyle: 'padding:15px'
            ,width: 550
            ,autoHeight: true
            ,items:[{
                xtype: 'checkboxgroup'
                ,columns:3
                ,fieldLabel: ''
                ,labelSeparator: ''
                ,items: [
                    {boxLabel: '" . MONDAY . "', name: 'MO', disabled:false, inputValue:1}
                    ,{boxLabel: '" . TUESDAY . "', name: 'TU', disabled:false, inputValue:1}
                    ,{boxLabel: '" . WEDNESDAY . "', name: 'WE', disabled:false, inputValue:1}
                    ,{boxLabel: '" . THURSDAY . "', name: 'TH', disabled:false, inputValue:1}
                    ,{boxLabel: '" . FRIDAY . "', name: 'FR', disabled:false, inputValue:1}
                    ,{boxLabel: '" . SATURDAY . "', name: 'SA', disabled:false, inputValue:1}
                    ,{boxLabel: '" . SUNDAY . "', name: 'SU', disabled:false, inputValue:1}
                ]
            }]
        }";

        if($this->facette->EDUCATION_SYSTEM){
            $ITEMS = "[
                ".$DETAIL_INFORMATION."
                ,".$SCHOOLYEAR_SETTINGS." 
                ,".$ACADEMIC_DATE_SETTING."
            ]";
        }else{
            $ITEMS = "[
                ".$DETAIL_INFORMATION."
                ,".$SCHOOLYEAR_SETTINGS." 
                ,".$ACADEMIC_DATE_SETTING."
                ,".$WORKING_DAYS."
            ]";
        }

        if (UserAuth::getACLValue("EXAMINATION_MANAGEMENT")){
            $HIDDEN_EXAMINATION_MANAGEMENT = 'false';
        }else{
            $HIDDEN_EXAMINATION_MANAGEMENT = 'true';  
        }

        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: ".$ITEMS."
        ";

        $OBJECT_FORM->addObjectItems($items);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('ACADEMIC_ID').expand();
            }
        ");

        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
        
         $OBJECT_FORM->addTBarItems("
            text:''
            ,tooltip:'".CAMEMIS_HELP."'
            ,iconCls: 'icon-help'
            ,handler:function(){
                ".CamemisPage::setEmbeddedHelp("B0B8-8F9A")."
            }
        ");
        
        $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '" . $this->objectId . "'");
        $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '".$this->objectId."'");
        $OBJECT_FORM->setSaveParams("
            cmd: 'updateObject'
            ,objecttype: 'SCHOOLYEAR'
            ,objectId: '".$this->objectId."'
        ");

        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            var tree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            var actionNode = tree.getSelectionModel().getSelectedNode();
            actionNode.setText(action.result.text);
            actionNode.ownerTree.fireEvent('beforechildrenrendered', actionNode.parentNode);
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");

        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");
        
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 150;
        $OBJECT_FORM->renderJS();

        $js = "";
        $js .= "viewport = new Ext.Viewport({";
            $js .= "layout: 'fit'";
            $js .= ",border: false";
            $js .= ",items:[{";
                $js .= "layout:'fit'";
                $js .= ",bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px'";
                $js .= ",border: false";
                $js .= ",items:[{";
                    $js .= "xtype: 'tabpanel'";
                    $js .= ",tabPosition: 'top'";
                    $js .= ",plain:true";
                    $js .= ",activeTab: 0";
                    $js .= ",enableTabScroll:true";
                    $js .= ",items:[{";
                    	$js .= "layout: 'fit'";
                        $js .= ",title:'".MAIN_CONTENT."'";
                        $js .= ",items:[{";
                            $js .= "border: false";
                            $js .= ",id: 'CONTENT'";
                            $js .= ",xtype: 'panel'";
                            $js .= ",layout: 'card'";
                            $js .= ",enableTabScroll:true";
                            $js .= ",activeItem: 0";
                            $js .= ",items:[{xtype: '".$OBJECT_FORM->getObjectXtype()."'}]";
                        $js .= "}]";
                    $js .= "},{";
                        $js .= "title: '".PERMISSION_ASSESSMENT_ENTRY."'";
                        $js .= ",layout: 'fit'";
                        $js .= ",items: [new Ext.ux.IFrameComponent({ id: 'PERMISSION_SCORE', url:'/academic/permissionscore/?objectId=".$this->objectId."'})]";
                    $js .= "}]";
                $js .= "}]";
            $js .= "}]";
        $js .= "});";
        $js .= "if (Ext.getCmp('MULTIPLE_SESSIONS')) Ext.getCmp('MULTIPLE_SESSIONS').on('check', function(){";
            $js .= "if(Ext.getCmp('MULTIPLE_SESSIONS').getValue() == true){";
                $js .= "Ext.getCmp('COL_FIRST_SESSION_GROUP').show();";
                $js .= "Ext.getCmp('COL_SECOND_SESSION_GROUP').show();";
                $js .= "Ext.getCmp('COL_THIRD_SESSION_GROUP').show();";
            $js .= "}else{";
                $js .= "Ext.getCmp('COL_FIRST_SESSION_GROUP').hide();";
                $js .= "Ext.getCmp('COL_SECOND_SESSION_GROUP').hide();";
                $js .= "Ext.getCmp('COL_THIRD_SESSION_GROUP').hide();";
            $js .= "}";
        $js .= "});";
        
        echo $js;
        
        ?>
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>