<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

set_time_limit(120);
$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$DB_SCHOOLYEAR = AcademicDateDBAccess::getInstance();

$OBJECT_FORM = new CamemisForm("ACADEMIC");
$OBJECT_FORM->setLoadUrl('/academic/jsonload/');
$OBJECT_FORM->setSaveUrl('/academic/jsonsave/');

if(!$this->facette) {header("Location: /main/permission/");exit;}

AcademicDBAccess::mappingAcademicSchoolyear($this->facette);

$CURRENT_SCHOOLYEAR = $DB_SCHOOLYEAR->isCurrentSchoolyear($this->facette->SCHOOL_YEAR);
$TERM_NUMBER = AcademicDBAccess::findAcademicTerm($this->facette->SCHOOL_YEAR);

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

class ViewportItem {

    public function __construct($objectId, $urlEncryp){
        $this->objectId = $objectId;
        $this->urlEncryp = $urlEncryp;
    }

    function getTermPanel($const, $datefield){
        $ext = "{";
            $ext .="title:'".constant($const)."'";
            $ext .=",tbar:['->','-',{text:'".CHANGE."'";
                $ext .=",iconCls:'icon-lightning'";
                $ext .=",handler:function(){";
                    $ext .="openWinIFrame('".constant($const)."', '/academic/datesetting/?camIds=".$this->urlEncryp->encryptedGet("&objectId=".$this->objectId."&target=".$const."")."', 500, 250);";
                $ext .="}";
            $ext .="}]";
            $ext .=",items:[{";
                $ext .="layout: 'form'";
                $ext .=",border: false";
                $ext .=",autoHeight:true";
                $ext .=",bodyStyle: 'padding:15px'";
                $ext .=",items:[{";
                    $ext .="".CamemisField::Displayfield("".$datefield."_START",START_DATE,false)."";
                $ext .="},{";
                    $ext .="".CamemisField::Displayfield("".$datefield."_END",END_DATE,false)."";
                $ext .="}]";
            $ext .="}]";
        $ext .="}";
        
        return $ext;
    }
}

$viewportItem = new ViewportItem(
    $this->objectId
    , $this->urlEncryp
);

?>

<script>
        
    Ext.onReady(function() {

        Ext.form.Field.prototype.msgTarget = 'side';

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

        if($this->facette->EDUCATION_SYSTEM){
            $DETAIL_INFORMATION_ITEMS = "[
                {".CamemisField::Textfield("NAME_ID", "NAME", NAME)."}
                ,{".CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false)."}
                ,{".CamemisField::Textarea("CONTACT_PERSON", CONTACT_PERSON, 100)."}
                ,{".CamemisField::Textfield("PHONE_ID","PHONE",PHONE)."}
                ,{".CamemisField::Textfield("EMAIL_ID","EMAIL",EMAIL)."}
                ,{".CamemisField::Numberfield("NUMBER_CREDIT", "NUMBER_CREDIT", NUMBER_CREDIT, false, false, false)."}
            ]";
        }else{
            $DETAIL_INFORMATION_ITEMS = "[
                {".CamemisField::Textfield("NAME_ID", "NAME", NAME)."}
                ,{".CamemisField::Numberfield("SORTKEY", "SORTKEY", SORTKEY, false, false, false)."}
                ,{".CamemisField::Checkbox("USE_OF_GROUPS","USE_OF_GROUPS",USE_OF_GROUPS, 1, false, false,true)."}    
                ,{".CamemisField::Textarea("CONTACT_PERSON", CONTACT_PERSON, 100)."}
                ,{".CamemisField::Textfield("PHONE_ID","PHONE",PHONE)."}
                ,{".CamemisField::Textfield("EMAIL_ID","EMAIL",EMAIL)."}
            ]";
        }

        $DETAIL_INFORMATION = "
        {
            title: '".DETAIL_INFORMATION."'
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width:550
            ,autoHeight: true
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: ".$DETAIL_INFORMATION_ITEMS."
            }]
        }
        ";

        ////////////////////////////////////////////////////////////////////////
        //@CHANGE ACADEMIC DATE - Sea Peng
        ////////////////////////////////////////////////////////////////////////
        $ACADEMIC_DATE = "
        {
            title:'".ACADEMIC_DATE."'
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:15px'
                ,items:[{
                    ".CamemisField::Displayfield("SCHOOLYEAR_START",START_DATE,false)."
                },{
                    ".CamemisField::Displayfield("SCHOOLYEAR_END",END_DATE,false)."
                }]
            }]
        }
        ";
        
        $ACADEMIC_DATE_SETTING_ITEMS = "[";

        $ACADEMIC_DATE_SETTING_ITEMS .= $ACADEMIC_DATE;

        switch ($TERM_NUMBER) {
            case 1:
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('FIRST_TERM', 'TERM1');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('SECOND_TERM', 'TERM2');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('THIRD_TERM', 'TERM3');
                break;
            case 2:
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('FIRST_QUARTER', 'QUARTER1');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('SECOND_QUARTER', 'QUARTER2');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('THIRD_QUARTER', 'QUARTER3');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('FOURTH_QUARTER', 'QUARTER4');
                break;
            default:
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('FIRST_SEMESTER', 'SEMESTER1');
                $ACADEMIC_DATE_SETTING_ITEMS .= ",".$viewportItem->getTermPanel('SECOND_SEMESTER', 'SEMESTER2');
                break;
        }

        $ACADEMIC_DATE_SETTING_ITEMS .= "]";

        $FORMULA_TERM_RESULT_STORE = "[";
        switch ($TERM_NUMBER) {
            case 1:
                $TITLE_FORMULA_TERM_RESULT = TERM_RESULT;
                $FORMULA_TERM_RESULT_STORE .= "[0, 'AVG(M)+AVG(T)']";
                $FORMULA_TERM_RESULT_STORE .= ",[1, 'AVG(T)']";
                break;
            case 2:
                $TITLE_FORMULA_TERM_RESULT = QUARTER_RESULT;
                $FORMULA_TERM_RESULT_STORE .= "[0, 'AVG(M)+AVG(Q)']";
                $FORMULA_TERM_RESULT_STORE .= ",[1, 'AVG(Q)']";
                break;
            default:
                $TITLE_FORMULA_TERM_RESULT = SEMESTER_RESULT;
                $FORMULA_TERM_RESULT_STORE .= "[0, 'AVG(M)+AVG(S)']";
                $FORMULA_TERM_RESULT_STORE .= ",[1, 'AVG(S)']";
                break;   
        }
        $FORMULA_TERM_RESULT_STORE .= "]";
        
        $DIVISION_NUMBER_ITEMS = "[";
            switch ($TERM_NUMBER) {
                case 1:
                    $DIVISION_NUMBER_ITEMS .= "{".CamemisField::Numberfield("FIRST_RESULT_DIVISION_VALUE","SEMESTER1_WEIGHTING", FIRST_TERM_RESULT, false, false)."}";
                    $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("SECOND_RESULT_DIVISION_VALUE","SEMESTER2_WEIGHTING", SECOND_TERM_RESULT, false, false)."}";
                    $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("THIRD_RESULT_DIVISION_VALUE","TERM1_WEIGHTING", THIRD_TERM_RESULT, false, false)."}";   
                    break;
                case 2:
                    $DIVISION_NUMBER_ITEMS .= "{".CamemisField::Numberfield("FIRST_RESULT_DIVISION_VALUE","SEMESTER1_WEIGHTING", FIRST_QUARTER_RESULT, false, false)."}";
                    $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("SECOND_RESULT_DIVISION_VALUE","SEMESTER2_WEIGHTING", SECOND_QUARTER_RESULT, false, false)."}";
                    $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("THIRD_RESULT_DIVISION_VALUE","TERM1_WEIGHTING", THIRD_QUARTER_RESULT, false, false)."}";
                    $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("FOURTH_RESULT_DIVISION_VALUE","TERM2_WEIGHTING", FOURTH_QUARTER_RESULT, false, false)."}";
                    break;
                default:
                    $DIVISION_NUMBER_ITEMS .= "{".CamemisField::Numberfield("THIRD_RESULT_DIVISION_VALUE","SEMESTER1_WEIGHTING", FIRST_SEMESTER_RESULT, false, false)."}";
                    $DIVISION_NUMBER_ITEMS .= ",{".CamemisField::Numberfield("SECOND_RESULT_DIVISION_VALUE","SEMESTER2_WEIGHTING", SECOND_SEMESTER_RESULT, false, false)."}";
                    break;   
            }
            
        $DIVISION_NUMBER_ITEMS .= "]";
        
        $ACADEMIC_DATE_SETTING = "
        {
            title: ''
            ,collapsible: true
            ,collapsed: false
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,width: 550
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px'
                ,border: false
                ,height:160
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:".$ACADEMIC_DATE_SETTING_ITEMS."
                }]
            }]
        }
        ";

        ////////////////////////////////////////////////////////////////////////
        //@EVALUATION SETTING - Sea Peng
        ////////////////////////////////////////////////////////////////////////
        $EVALUATION_TYPE_STORE = "[
            [0, '" . NUMBER . "']
            ,[1, '".PERCENT."']
        ]";

        if($this->facette->EVALUATION_TYPE){
            $HIDDEN = true;
        }else{
            $HIDDEN = false;
        }

        $AVERAGE_STORE = "[";
        switch ($TERM_NUMBER) {
            case 1:
                $AVERAGE_STORE .= "[0, 'AVG(T1+T2+T3)']";
                $AVERAGE_STORE .= ",[1, 'AVG(T1)']";
                $AVERAGE_STORE .= ",[2, 'AVG(T2)']";
                $AVERAGE_STORE .= ",[3, 'AVG(T3)']";
                break;
            case 2:
                $AVERAGE_STORE .= "[0, 'AVG(Q1+Q2+Q3+Q4)']";
                $AVERAGE_STORE .= ",[1, 'AVG(Q1)']";
                $AVERAGE_STORE .= ",[2, 'AVG(Q2)']";
                $AVERAGE_STORE .= ",[3, 'AVG(Q3)']";
                $AVERAGE_STORE .= ",[4, 'AVG(Q4)']";
                break;
            default:
                $AVERAGE_STORE .= "[0, 'AVG(S1+S2)']";
                $AVERAGE_STORE .= ",[1, 'AVG(S1)']";
                $AVERAGE_STORE .= ",[2, 'AVG(S2)']";
            break;
        }

        $AVERAGE_STORE .= "]";

        $DISPLAYING = "[";
            $DISPLAYING .= "{".CamemisField::Checkbox("DISPLAY_MONTH_RESULT","DISPLAY_MONTH_RESULT",MONTHLY_RESULT, 1, false, false)."}";
            switch ($TERM_NUMBER) {
                case 1:
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_FIRST_RESULT","DISPLAY_FIRST_RESULT",FIRST_TERM_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_SECOND_RESULT","DISPLAY_SECOND_RESULT",SECOND_TERM_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_THIRD_RESULT","DISPLAY_THIRD_RESULT",THIRD_TERM_RESULT, 1, false, false)."}";
                    break;
                case 2:
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_FIRST_RESULT","DISPLAY_FIRST_RESULT",FIRST_QUARTER_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_SECOND_RESULT","DISPLAY_SECOND_RESULT",SECOND_QUARTER_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_THIRD_RESULT","DISPLAY_THIRD_RESULT",THIRD_QUARTER_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_FOURTH_RESULT","DISPLAY_FOURTH_RESULT",FOURTH_QUARTER_RESULT, 1, false, false)."}";
                    break;
                default:
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_FIRST_RESULT","DISPLAY_FIRST_RESULT",FIRST_SEMESTER_RESULT, 1, false, false)."}";
                    $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_SECOND_RESULT","DISPLAY_SECOND_RESULT",SECOND_SEMESTER_RESULT, 1, false, false)."}";
                    break;    
            }
            $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_YEAR_RESULT","DISPLAY_YEAR_RESULT",YEAR_RESULT, 1, false, false)."}";
            $DISPLAYING .= ",{".CamemisField::Checkbox("DISPLAY_GPA","DISPLAY_GPA","GPA", 1, false, false)."}";
        $DISPLAYING .= "]";
        
        $WEIGHTING = "[";
            switch ($TERM_NUMBER) {
                case 1:
                    $WEIGHTING .= "{".CamemisField::Numberfield("SEMESTER1_WEIGHTING","SEMESTER1_WEIGHTING", FIRST_TERM, true, 1)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("SEMESTER2_WEIGHTING","SEMESTER2_WEIGHTING", SECOND_TERM, true, 1)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("TERM1_WEIGHTING","TERM1_WEIGHTING", THIRD_TERM, true, 1)."}";   
                    break;
                case 2:
                    $WEIGHTING .= "{".CamemisField::Numberfield("SEMESTER1_WEIGHTING","SEMESTER1_WEIGHTING", FIRST_QUARTER, true, 1)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("SEMESTER2_WEIGHTING","SEMESTER2_WEIGHTING", SECOND_QUARTER, true, 1)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("TERM1_WEIGHTING","TERM1_WEIGHTING", THIRD_QUARTER, true, 1)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("TERM2_WEIGHTING","TERM2_WEIGHTING", FOURTH_QUARTER, true, 1)."}";
                    break;
                default:
                    $WEIGHTING .= "{".CamemisField::Numberfield("SEMESTER1_WEIGHTING","SEMESTER1_WEIGHTING", FIRST_SEMESTER, true, 1)."}";
                    $WEIGHTING .= ",{".CamemisField::Numberfield("SEMESTER2_WEIGHTING","SEMESTER2_WEIGHTING", SECOND_SEMESTER, true, 1)."}";
                    break;   
            }
            
        $WEIGHTING .= "]";

        $CAMEMIS_ASSESSMENT_SETTINGS = "
        {
            title: '".EVALUATION_SETTINGS."'
            ,collapsible: true
            ,collapsed: false
            ,autoHeight: true
            ,style: 'padding-bottom:5px'
            ,bodyStyle: 'padding:15px'
            ,width: 550
            ,items:[{
                xtype:'fieldset'
                ,width: 500
                ,title:'".EVALUATION_TYPE."'
                ,checkboxToggle:true
                ,collapsed: false
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle: 'padding:15px'
                    ,items:[
                        {".CamemisField::Combo('EVALUATION_TYPE', TYPE, $EVALUATION_TYPE_STORE, false, false, false, false,false)."}
                        ,{".CamemisField::Radio("EVALUATION_OPTION_1", "EVALUATION_OPTION", EVALUATION_OF_ASSIGNMENT,0, false)."}
                        ,{".CamemisField::Radio("EVALUATION_OPTION_2", "EVALUATION_OPTION", EVALUATION_OF_SUBJECT,1, false)."}
                        ,{".CamemisField::Radio("GRADING_TYPE_1", "GRADING_TYPE", GRADING." (".ASSESSMENT.")",0, false)."}
                        ,{".CamemisField::Radio("GRADING_TYPE_2", "GRADING_TYPE", GRADING." (".LETTER_GRADE.")",1, false)."}
                    ]
                }]
            },{
                xtype:'fieldset'
                ,width: 500
                ,title:'".DISPLAYING."'
                ,checkboxToggle:true
                ,collapsed: false
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle: 'padding:15px'
                    ,items: ".$DISPLAYING."
                }]
            },{
                xtype:'fieldset'
                ,width: 500
                ,title:'".WEIGHTING."'
                ,checkboxToggle:true
                ,collapsed: false
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle: 'padding:15px'
                    ,items: ".$WEIGHTING."
                }]
            },{
                xtype:'fieldset'
                ,width: 500
                ,title:'".FORMULA_CALCULATOR."'
                ,checkboxToggle:true
                ,collapsed: false
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle: 'padding:15px'
                    ,items:[
                        {".CamemisField::Combo('FORMULA_TERM', $TITLE_FORMULA_TERM_RESULT, $FORMULA_TERM_RESULT_STORE, false, false, false, false,false)."}
                        ,{".CamemisField::Combo('FORMULA_YEAR', YEAR_RESULT, $AVERAGE_STORE, false, false, false, false,false)."}
                    ]
                }]
            },{
                xtype:'fieldset'
                ,width: 500
                ,title:'".DIVISION_NUMBER."'
                ,checkboxToggle:true
                ,collapsed: false
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle: 'padding:15px'
                    ,items: ".$DIVISION_NUMBER_ITEMS."
                }]
            }]
        }
        ";
        ////////////////////////////////////////////////////////////////////////
        
        $WORKING_DAYS = "
        {
            title: '".WORKING_DAYS."'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,autoHeight: true
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'background:#FFF;padding:10px'
                ,items: [
                    {".CamemisField::Checkbox("ID1","MO", MONDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID2","TU", TUESDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID3","WE", WEDNESDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID4","TH", THURSDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID5","FR", FRIDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID6","SA", SATURDAY, 1, false)."}
                    ,{".CamemisField::Checkbox("ID7","SU", SUNDAY, 1, false)."}
                ]
            }]
        }";

        if($this->facette->EDUCATION_SYSTEM){
            $ITEMS = "[
                ".$DETAIL_INFORMATION."
                ,".$ACADEMIC_DATE_SETTING."
                ,".$CAMEMIS_ASSESSMENT_SETTINGS." 
            ]";
        }else{
            $ITEMS = "[
                ".$DETAIL_INFORMATION."
                ,".$ACADEMIC_DATE_SETTING."
                ,".$CAMEMIS_ASSESSMENT_SETTINGS." 
                ,".$WORKING_DAYS."
            ]";
        }

        if (UserAuth::getACLValue("EXAMINATION_MANAGEMENT")){
            $HIDDEN_EXAMINATION_MANAGEMENT = 'false';
        }else{
            $HIDDEN_EXAMINATION_MANAGEMENT = 'true';  
        }

        $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: ".$ITEMS."
        ";

        $OBJECT_FORM->addObjectItems($items);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                window.parent.Ext.getCmp('ACADEMIC_ID').expand();
            }
        ");

        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EXECUTE_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
        if (UserAuth::getACLValue("ACADEMIC_GENERAL_EDUCATION_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
        
        $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '" . $this->objectId . "'");
        $OBJECT_FORM->setLoadParams("cmd: 'loadObject',objectId: '".$this->objectId."'");
        $OBJECT_FORM->setSaveParams("
            cmd: 'updateObject'
            ,objecttype: 'SCHOOLYEAR'
            ,objectId: '".$this->objectId."'
        ");

        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            var tree = window.parent.Ext.getCmp('ACADEMIC_TREE_ID');
            var actionNode = tree.getSelectionModel().getSelectedNode();
            actionNode.setText(action.result.text);
            actionNode.ownerTree.fireEvent('beforechildrenrendered', actionNode.parentNode);
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");

        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            window.location='" . $_SERVER["REQUEST_URI"] . "';
        ");
        
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 150;
        $OBJECT_FORM->renderJS();

        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:[{
                    	layout: 'fit'
                        ,title:'<?=MAIN_CONTENT;?>'
                        ,items:[{
                            border: false
                            ,id: 'CONTENT'
                            ,xtype: 'panel'
                            ,layout: 'card'
                            ,enableTabScroll:true
                            ,activeItem: 0
                            ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
                        }]
                    },{
                        title: '<?=PERMISSION_ASSESSMENT_ENTRY?>'
                        ,layout: 'fit'
                        ,items: [new Ext.ux.IFrameComponent({ id: 'PERMISSION_SCORE', url:'/academic/permissionscore/?objectId=<?=$this->objectId;?>'})]
                    }]
                }]
            }]
        });

        Ext.getCmp('EVALUATION_TYPE_ID').on('select', function() {
            if(Ext.getCmp('EVALUATION_TYPE_ID').getValue() == 1){
                Ext.getCmp('DISTRIBUTION_VALUE').hide();    
            }else{
                Ext.getCmp('DISTRIBUTION_VALUE').show();  
            }
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>