<html>
    <head>
    <title><?= Zend_Registry::get('TITLE');?></title>
    <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/css/login.css" />
    <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/resources/css/ext-all.css" />
    <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/plugin/Cookies.js"></script>
    <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/adapter/ext/ext-base.js"></script>
    <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/ext-all.js"></script>
    </head>
    <body bgcolor="#FFFFFF">
    <div id="initCenter" class="x-hide-display" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="headerExpired">Your session has expired, please log in again.</h1>
    <br>
    <a href=# onClick="javascript:parent.parent.parent.parent.parent.parent.window.location='<?=Zend_Registry::get('CAMEMIS_URL')?>/'"><b>Login...</b></a>
    </div>
    <script>
    Ext.onReady(function() {
        /*
        var msgBox = Ext.MessageBox.show({
            title: 'Session Timeout'
            ,msg: 'Please log in again.'
            ,progressText: 'CAMEMIS restart in 5...'
            ,progress: true
            ,closable: false
            ,width:250
        });		
        var runTask = {
            run: function(count) {
                if(count == 5) {
                    window.parent.parent.location = '../../../<?=Zend_Registry::get('CAMEMIS_URL')?>';		  		 
                }
                msgBox.updateProgress(count/5,'CAMEMIS restart in '+(5-count)+'...');
            }
            ,interval:2000
            ,repeat:10
        };

        Ext.TaskMgr.start(runTask);
        */
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                layout: 'fit'
                ,border: false
                ,contentEl: 'initCenter'
            }]
        });
	});
    </script>
</body>
</html>