<html>
    <head>
    <title><?= Zend_Registry::get('TITLE');?></title>
    <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/css/login.css" />
    <link rel="stylesheet" type="text/css" href="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/resources/css/ext-all.css" />
    <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/plugin/Cookies.js"></script>
    <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/adapter/ext/ext-base.js"></script>
    <script type="text/javascript" src="<?=Zend_Registry::get('CAMEMIS_URL')?>/public/<?= Zend_Registry::get('EXTJS_VERSION');?>/ext-all.js"></script>
    </head>
    <body bgcolor="#FFFFFF">
    <div id="initCenter" class="x-hidden" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="headerError">Your session has expired, please login again.</h1>
    <br>
    <a href=# onClick="javascript:parent.parent.parent.parent.parent.parent.window.location='<?=Zend_Registry::get('CAMEMIS_URL')?>/'"><b>Login...</b></a>
    </div>
    <script>    
	Ext.onReady(function() {
            viewport = new Ext.Viewport({
                layout: 'fit'
                ,border: false
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,contentEl: 'initCenter'
                }]
            });
	});
	</script>
    </body>
</html>