<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("SCHEDULE");
$OBJECT_FORM->setLoadUrl('/schedule/jsonload/');
$OBJECT_FORM->setSaveUrl('/schedule/jsonsave/');

$OBJECT_DATA = $this->objectData;

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
	
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();

    $parameter = "cmd: 'teachersByClassANDSubject',academicId: '".$this->academicId."'";

    $objectTeacher = "TEACHER";
    $objectTeacher = new CamemisDynCombo("STAFF", "TEACHER");
    $objectTeacher->setLoadUrl('/staff/jsonload/');
    $objectTeacher->objectTitle = TEACHER;
    $objectTeacher->allowBlank = "false";
    $objectTeacher->varName = "TEACHER";
    $objectTeacher->setLoadParams($parameter);
    $objectTeacher->renderJS();

	
    $DESCRIPTION = "
    {
        title: '".DESCRIPTION."'
        ,autoHeight: true
        ,style: 'padding-bottom: 5px'
        ,width: 550
        ,items:[{
            layout: 'form'
            ,border: false
            ,autoHeight:true
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::Textarea("DESCRIPTION", false,60)."}
            ]
        }]
    }
    ";
    
    $items = "
    border: false
    ,id: 'FORM_ITEMS'
    ,bodyStyle: 'background:".CamemisPage::userBgColor().";padding:3px'
    ,items:[{
        xtype: 'tabpanel'
        ,enableTabScroll:true
        ,plain: true
        ,height: 250
        ,activeTab: 0
        ,items:[{
            title: '".DETAIL_INFORMATION."'
            ,bodyStyle: 'padding:10px'
            ,layout: 'form'
            ,items: [
                {".(CamemisField::ComboSubjectByGrade("SUBJECT_ID","SUBJECT", SUBJECT, true))."},
                {xtype: '".$objectTeacher->getObjectXType()."'},
                {".CamemisField::ComboRoom("ROOM_ID","ROOM", ROOM, true)."},
                {".CamemisField::Colorfield("COLOR", COLOR, false)."}
            ]
        },{
            title: '".TEACHING."'
            ,bodyStyle: 'padding:10px'
            ,layout: 'form'
            ,items: [
                {".CamemisField::ComboTeacher("SUBSTITUTE_ID", "TEACHING",NAME, false, false)."}
                ,{".CamemisField::Datefield("SUBSTITUTE_START", START_DATE, false)."}
                ,{".CamemisField::Datefield("SUBSTITUTE_END", END_DATE, false)."}
                ,{".CamemisField::ComboYesNO("SUBSTITUTE_ACTIVE", "SUBSTITUTE_ACTIVE", ACTIVE, false)."}
            ]
        },{
            title: '".NOTES."'
            ,bodyStyle: 'padding:10px'
            ,layout: 'form'
            ,items: [
                {".CamemisField::Textarea("DESCRIPTION", false,180)."}
            ]
        }]
    }]
    
    ";
    $OBJECT_FORM->addObjectItems($items);

    if ($this->objectId !="new"){
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormRemoveObject($this->remove_status));
        $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease());
    }

    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());

    $OBJECT_FORM->setLoadParams("
    cmd: 'loadObject'
    ,periodId: '".$this->periodId."'
    ,shortday: '".$this->shortday."'
    ,academicId: '".$this->academicId."'
    ");
	
    $OBJECT_FORM->setSaveParams("
    cmd: 'saveObject'
    ,periodId: '".$this->periodId."'
    ,shortday: '".$this->shortday."'
    ,academicId: '".$this->academicId."'
    ");

    $OBJECT_FORM->setonEmbeddedEvents("
    window.parent.Ext.getCmp('SCHEDULE_LIST_ID').store.reload();
    ");

    $OBJECT_FORM->setReleaseParams("
    cmd: 'releaseObject'
    ,periodId: '".$this->periodId."'
    ,shortday: '".$this->shortday."'
    ,academicId: '".$this->academicId."'
    ");
	
    $OBJECT_FORM->setOnEmbeddedReleaseEvents("
    window.parent.Ext.getCmp('SCHEDULE_LIST_ID').store.reload();
    window.parent.Ext.getCmp('OPEN_WIN_IFRAME_ID').close();
    ");

    $OBJECT_FORM->setRemoveParams("
    cmd: 'removeObject'
    ,periodId: '".$this->periodId."'
    ,shortday: '".$this->shortday."'
    ,academicId: '".$this->academicId."'
    ");

    $OBJECT_FORM->setOnEmbeddedRemoveEvents("
    window.parent.Ext.getCmp('SCHEDULE_LIST_ID').store.reload();
    window.parent.Ext.getCmp('OPEN_WIN_IFRAME_ID').close();
    ");

    $OBJECT_FORM->bodyStyle = "padding:10px";
    $OBJECT_FORM->isWindowlocation = false;
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->labelWidth = 120;
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items: [{
            xtype: 'panel'
            ,id: 'panel'
            ,border: false
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{
                layout: 'fit'
                ,border: false
                ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
            }]
        }]
    });
    
    Ext.getCmp('SUBJECT_ID').on('select', function(){
    Ext.getCmp('TEACHER_ID').setValue('');
    Ext.getCmp('TEACHER_ID').store.baseParams = {
        cmd: 'teachersByClassANDSubject'
        ,academicId: '<?=$this->academicId?>'
        ,subjectId: this.getValue()
    };
    Ext.getCmp('TEACHER_ID').store.reload();
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>