<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 25.12.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

if(!$this->facette) {header("Location: /main/permission/");exit;}

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$OBJECT_GRID = new CamemisGrid("FINANCE", "INVOICE");
$OBJECT_GRID->setLoadUrl("/finance/jsonload/");

$target = isset($_GET["target"])?addText($_GET["target"]):"";

?>
<script>
var clickId;
Ext.onReady(function() {
    
    function cssText(value, metadata, record){
        return '<div style="font-weight:normal; color:#333; padding:3px;">' + value + '</div>';
    }
    
    function cssNumber(value, metadata, record){
        return '<div style="font-weight:bold; color:#3B5998; padding: 5px;">' + value + '</div>';
    }
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addReadField("name: 'TRANSACTION_NUMBER'");
    $OBJECT_GRID->addReadField("name: 'AMOUNT'");
    $OBJECT_GRID->addReadField("name: 'EXPENSE_CATEGORY'");
    $OBJECT_GRID->addReadField("name: 'TOTAL_SESSION'");
    $OBJECT_GRID->addReadField("name: 'PAYMENT_STATUS'");
    $OBJECT_GRID->addReadField("name: 'PAYMENT_DATE'");
    $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");
    $OBJECT_GRID->addReadField("name: 'TYPE'");
    
    $OBJECT_GRID->addColumn("header: '<b>".TRANSACTION_NUMBER."</b>', align:'left', renderer: cssText, width: 140, sortable: true, dataIndex: 'TRANSACTION_NUMBER'");
    $OBJECT_GRID->addColumn("header: '<b>".AMOUNT."</b>', align:'left', renderer: cssText, width: 150, sortable: true, dataIndex: 'AMOUNT'");
    $OBJECT_GRID->addColumn("header: '<b>".EXPENSE_CATEGORY."</b>', align:'left', renderer: cssText, width: 150, sortable: true, dataIndex: 'EXPENSE_CATEGORY'");
    $OBJECT_GRID->addColumn("header: '<b>".DATE."</b>', align:'left', renderer: cssText, width: 200, sortable: true, dataIndex: 'PAYMENT_DATE'");
    $OBJECT_GRID->addColumn("header: '<b>".TOTAL_SESSION."</b>', align:'left', renderer: cssText, width: 150, sortable: true, dataIndex: 'TOTAL_SESSION'");
    $OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>', align:'left', renderer: cssText, width: 150, sortable: true, dataIndex: 'PAYMENT_STATUS'");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_DATE."</b>', align:'left', renderer: cssText, width: 150, sortable: true, dataIndex: 'CREATED_DATE'");
   
    if($target)
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);}
        }]);
    ");

    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,objectId:'".$this->objectId."'
        ,cmd: 'jsonListStaffInvoices'
    ";
    
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border:false
            ,title:'<?=MY_ACCOUNT?>'
            ,id:'content'
            ,layout: 'card'
            ,activeItem: 0
            ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
        }]
    });
    
    <?
    //if(UserAuth::getACLValue("FINANCIAL_MANAGEMENT_EDIT_RIGHT")){
        ?>
        var myGrid = Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>');
            if (myGrid) myGrid.on('cellclick', function(grid,rowIndex) {
                var record = grid.store.getAt(rowIndex);
                switch(record.data.TYPE){
                    case 1:
                        clickOpenPage('content','','/finance/staffpaymentsalary/?objectId=<?=$this->objectId?>&paymentId='+record.data.ID);
                        break;
                    case 2:
                        clickOpenPage('content','','/finance/staffpaymentsession/?objectId=<?=$this->objectId?>&paymentId='+record.data.ID);
                    break;
                }
            });
        <?        
    //}
    ?>
    
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>