<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'models/UserAuth.php';
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisDynamicCombo.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_FORM = new CamemisForm("ATTENDANCE");
$OBJECT_FORM->setLoadUrl('/attendance/jsonload/');
$OBJECT_FORM->setSaveUrl('/attendance/jsonsave/');

$GENERAL_EDU_TREE = new CamemisTree("ACADEMIC","LIST");
$GENERAL_EDU_TREE->setURL('/academic/jsontree/');
$GENERAL_EDU_TREE->setSaveUrl('/academic/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
    
    Ext.onReady(function() {

        <?
        /**
        * Extjs: s.gif
        */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $GENERAL_EDU_TREE->isAsyncTreeNode = false;
        $GENERAL_EDU_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
        $GENERAL_EDU_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
        $GENERAL_EDU_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
        $GENERAL_EDU_TREE->setBaseParams("
            cmd: 'jsonTreeAllAcademicGradeSchoolyear'
        ");

        $GENERAL_EDU_TREE->backgroundColor = "#F9F9F9";
        $GENERAL_EDU_TREE->isOnClickContextMenu = false;
        $GENERAL_EDU_TREE->isTreeExpand = false;
        $GENERAL_EDU_TREE->renderJS();

        $triggerOnClick = "
            openWinXType('SCHOOL_YEAR_OR_CLASS','".SCHOOL_YEAR_OR_CLASS."', '".$GENERAL_EDU_TREE->getObjectXType()."', 500, percentHeight(85));
            var academicTree = Ext.getCmp('".$GENERAL_EDU_TREE->getObjectId()."');
            
            academicTree.getRootNode().expand(true, false);
            academicTree.on('click', function(node, e){

                Ext.getCmp('CHOOSE_CAMPUS').setValue('');
                Ext.getCmp('CHOOSE_GRADE').setValue('');
                Ext.getCmp('CHOOSE_SCHOOLYEAR').setValue('');
                Ext.getCmp('CHOOSE_GRADE_NAME_ID').setValue('');

                if(node.attributes.objecttype == 'CAMPUS' || 
                node.attributes.objecttype == 'GRADE' || 
                node.attributes.objecttype == 'SCHOOLYEAR'){

                    /////////////////////
                    //Choose Campus
                    /////////////////////
                    if (node.attributes.objecttype == 'CAMPUS') {
                        Ext.getCmp('CHOOSE_CAMPUS').setValue(node.id);
                        Ext.getCmp('CHOOSE_GRADE_NAME_ID').setValue(node.text);
                    }
                    //////////////////////
                    //Chosse Grade
                    //////////////////////
                    if (node.attributes.objecttype == 'GRADE') {
                        Ext.getCmp('CHOOSE_CAMPUS').setValue(node.attributes.campusId);
                        Ext.getCmp('CHOOSE_GRADE').setValue(node.id);
                        Ext.getCmp('CHOOSE_GRADE_NAME_ID').setValue(node.attributes.title);
                    }
                    //////////////////////
                    //Choose Schoolyear
                    //////////////////////
                    if (node.attributes.objecttype == 'SCHOOLYEAR') {
                        Ext.getCmp('CHOOSE_CAMPUS').setValue(node.attributes.campusId);
                        Ext.getCmp('CHOOSE_GRADE').setValue(node.attributes.gradeId);
                        Ext.getCmp('CHOOSE_SCHOOLYEAR').setValue(node.attributes.schoolyearId);
                        Ext.getCmp('CHOOSE_GRADE_NAME_ID').setValue(node.attributes.title);
                    }
                    Ext.getCmp('SCHOOL_YEAR_OR_CLASS').close();
                }
            });
        ";
        
        $OBJECT_FORM->addObjectItems("
            xtype:'fieldset'
            ,collapsible:true,collapsed:false
            ,title: '".DETAIL_INFORMATION."'
            ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;font-weight: bold; padding:10px'
            ,width: 250
            ,items:[
                {".CamemisField::Textfield("CODE", "CODE", SHORT." (FEE-)", false, false, false, 200)."}
                ,{".CamemisField::Textfield("NAME", "NAME", FEE_NAME, false, false, false, 200)."}
                ,{".CamemisField::Trigger("CHOOSE_GRADE_NAME",SCHOOL_YEAR_OR_CLASS,$triggerOnClick,false, false, false, 200)."}
            ]
        ");
        //Hidden Field campus
        $OBJECT_FORM->addObjectItems(CamemisField::Hidden("CHOOSE_CAMPUS",false));
        //Hidden Field grade
        $OBJECT_FORM->addObjectItems(CamemisField::Hidden("CHOOSE_GRADE",false));
        //Hidden Field schoolyear
        $OBJECT_FORM->addObjectItems(CamemisField::Hidden("CHOOSE_SCHOOLYEAR",false));    
        $OBJECT_FORM->addTBarItems("
            text: '".RESET."'
            ,iconCls:'icon-arrow_undo'
            ,scope:this
            ,handler: function(){".CamemisPage::setRequestURI()."}
        ");
        
        $FINANCIAL_MANAGEMENT_READ_RIGHT = UserAuth::getACLValue("FINANCIAL_MANAGEMENT_READ_RIGHT")?"false":"true";
        $OBJECT_FORM->addTBarItems("
            text: '".FIND."'
            ,hidden: ".$FINANCIAL_MANAGEMENT_READ_RIGHT."
            ,formBind:true
            ,iconCls:'icon-magnifier'
            ,scope:this
            ,handler:function(){
                name = this.getForm().findField('NAME').getValue();
                code = this.getForm().findField('CODE').getValue();
                campusId = this.getForm().findField('CHOOSE_CAMPUS').getValue();
                gradeId = this.getForm().findField('CHOOSE_GRADE').getValue();
                schoolyearId = this.getForm().findField('CHOOSE_SCHOOLYEAR').getValue();
                searchString = 'name=' + name
                + '&code=' + code
                + '&campusId=' + campusId
                + '&gradeId=' + gradeId
                + '&schoolyearId=' + schoolyearId;
                clickOpenPage('center','', '/finance/searchfeeenrollment/?' + searchString);
                Ext.getCmp('WEST_ID').collapse();
            }
        ");
        if( UserAuth::getACLValue("FINANCIAL_MANAGEMENT_EDIT_RIGHT"))
        $OBJECT_FORM->addTBarItems("
            text: '".ADD_NEW_ITEM."'
            ,iconCls:'icon-application_form_add'
            ,scope:this
            ,handler: function(){
                Ext.getCmp('WEST_ID').collapse();
                clickOpenPage('center','', '/finance/showfeeenrollment/?objectId=new');
            }
        ");
        
        $OBJECT_FORM->setBodyStyle("padding:10px;background:".CamemisPage::userFormBgColor().";");
        $OBJECT_FORM->labelAlign = "top";
        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->isKeys = true;
        $OBJECT_FORM->renderJS();

        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout: 'fit'
                ,border: false
                ,id: 'CONTENT'
                ,items:[{
                    layout:'border'
                    ,border: false
                    ,defaults: {
                        collapsible: true
                        ,split: true
                    }
                    ,items: [{
                        title: '<?=GENERAL_EDUCATION?>'
                        ,region:'west'
                        ,id: 'WEST_ID'
                        ,margins: '3 0 3 3'
                        ,cmargins: '3 3 3 3'
                        ,width: 270
                        ,minSize: 270
                        ,maxSize: 270
                        ,items: [{xtype: '<?=$OBJECT_FORM->getObjectXType();?>'}]
                    },{
                        title: ''
                        ,collapsible: false
                        ,id: 'center'
                        ,region:'center'
                        ,layout: 'card'
                        ,activeItem: 0
                        ,margins: '3 3 3 0'
                        ,items:[new Ext.ux.IFrameComponent({ id: 'URL_SEARCH', url: '/finance/searchfeeenrollment/'})]
                    }]
                }]
            }]
        });
        
        //Ext.getCmp('WEST_ID').toggleCollapse(true);
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>