<?
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_TREE = new CamemisTree("HELP", "LIST");
$OBJECT_TREE->setURL("/help/jsontree/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<div id="initCenter" class="x-hide-display" style="border:0px silver solid;margin:30px;padding:8px;height:140px">
    <h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>
</div>

<script>

Ext.onReady(function() {
   
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_TREE->isAsyncTreeNode = false;
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    
    $OBJECT_TREE->setBaseParams("
    	cmd:'treeUserHelps'
        ,key:'".$this->key."'
    ");
    
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->isTreeExpand = true;
    $OBJECT_TREE->renderJS();
    
    $defaultKey = CAMEMISHelpDBAccess::findFirsKeytHelpContent($this->key);
    
    $js ="";
    $js .="viewport = new Ext.Viewport({";
        $js .="layout: 'fit'";
        $js .=",border: false";
        $js .=",items:[{";
            $js .="layout:'border'";
            $js .=",border: false";
            $js .=",defaults: {";
                $js .="collapsible: true";
                $js .=",split: true";
            $js .="}";
            $js .=",items: [{";
               	$js .="region:'west'";
                $js .=",id: 'WEST_ID'";
                $js .=",margins: '5 0 5 0'";
                $js .=",cmargins: '3 3 3 3'";
                $js .=",width: 250";
                $js .=",minSize: 250";
                $js .=",maxSize: 250";
                $js .=",layout: 'fit'";
                $js .=",items:[{xtype: '".$OBJECT_TREE->getObjectXtype()."'}]";
            $js .="},{";
               	$js .="collapsible: false";
                $js .=",id: 'center'";
                $js .=",region:'center'";
                $js .=",margins: '3 3 3 0'";
                $js .=",layout: 'card'";
                $js .=",activeItem: 0";
                
                if($defaultKey){
                    $js .=",items: [{";
                        $js .="layout: 'fit'";
                        $js .=",border: false";
                        $js .=",items: [new Ext.ux.IFrameComponent({ id: 'HELP_CONTENT', url:'/help/displaymain/?objectId=".$defaultKey."'})]";
                    $js .="}]";
                }else{
                    $js .=",items: [{";
                        $js .="layout: 'fit'";
                        $js .=",border: false";
                        $js .=",contentEl: 'initCenter'";
                    $js .="}]";
                }
                
            $js .="}]";
        $js .="}]";
    $js .="});";
    
    $js .="var myTree = ".$OBJECT_TREE->ExtgetCmp().";";
    $js .="myTree.on('click', function(node, event){";
        $js .="clickOpenPage('center','','/help/displaymain/?objectId=' + node.id);";
    $js .="});";
    
    echo $js;
    ?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>