<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
  
$classObject = AcademicDBAccess::findGradeFromId($this->classId);

if(!$classObject) {header("Location: /main/permission/");}
    
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PANEL_ITEMS = array();

        $attendanceParams = "target=general&classId=".$classObject->ID."&teacherId=".$this->objectId."";
        $ATTENDANCE_INFORMATION = "{
            title: '".ATTENDANCE_INFORMATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ATTENDANCE_INFORMATION', url: '/attendance/studentclassmain/?camIds=".$this->urlEncryp->encryptedGet($attendanceParams)."'})]
        }";
        
        //if (UserAuth::getACLTutorPermint("STUDENT_ATTENDANCE"))
        $PANEL_ITEMS[] = "" . $ATTENDANCE_INFORMATION . "";
        
        $scheduleParams = "academicId=".$classObject->ID."";
        $SCHEDULE = "{
            title: '".SCHEDULE."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'SCHEDULE', url: '/schedule/byclass/?camIds=".$this->urlEncryp->encryptedGet($scheduleParams)."'})]
        }";
        $PANEL_ITEMS[] = "" . $SCHEDULE . "";
        
        $scheduleParams = "target=general&classId=".$this->classId."";
        $EVENT = "{
            title: '".EVENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'EVENT', url: '/schoolevent/classevents/?camIds=".$this->urlEncryp->encryptedGet($scheduleParams)."'})]
        }";
        
        if (UserAuth::getACLTutorPermint("CLASS_EVENTS"))
        $PANEL_ITEMS[] = "" . $EVENT . "";
        
        $homeworkParams = "classId=".$classObject->ID."&gradeId=".$classObject->GRADE_ID."&schoolyearId=".$classObject->SCHOOL_YEAR."&teacherId=".$this->objectId."";
        $HOMEWORK = "{
            title: '".HOMEWORK."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'HOMEWORK', url: '/homework/homeworkmain/?camIds=".$this->urlEncryp->encryptedGet($homeworkParams)."'})]
        }";
        
        $PANEL_ITEMS[] = "" . $HOMEWORK . "";
        
        $subjectParams = "general&classId=".$classObject->ID."&gradeId=".$classObject->GRADE_ID."&schoolyearId=".$classObject->SCHOOL_YEAR."&teacherId=".$this->objectId."";
        $SUBJECT= "{
            title: '".SUBJECT_LIST."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ALL_SUBJECTS', url: '/subject/byclass/?camIds=".$this->urlEncryp->encryptedGet($subjectParams)."'})]
        }";
        
        $PANEL_ITEMS[] = "" . $SUBJECT . "";
        
        $teachingreportParams = "classId=".$this->classId."&teacherId=".$this->objectId."";
        $TEACHING_REPORT= "{
            title: '".TEACHING_REPORT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'TEACHING_REPORT', url: '/subjectreport/subjectreportmain/?camIds=".$this->urlEncryp->encryptedGet($teachingreportParams)."'})]
        }";
        
        if (UserAuth::getACLTutorPermint("TEACHING_REPORT"))
        $PANEL_ITEMS[] = "" . $TEACHING_REPORT . "";
        
        $assessmentParams = "classId=".$this->classId."&teacherId=".$this->objectId."";
        $ASSESSMENT = "{
            title: '".ASSESSMENT."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'ASSESSMENT', url: '/academic/scoremonitor/?camIds=".$this->urlEncryp->encryptedGet($assessmentParams)."'})]
        }";
      
        
        if (UserAuth::getACLTutorPermint("SCORES_MANAGEMENT"))
        $PANEL_ITEMS[] = "" . $ASSESSMENT . "";
        
        $disciplineParams = "target=general&personType=STAFF&classId=".$classObject->ID."";
        $DISCIPLINE_INFORMATION = "{
            title: '".DISCIPLINE_INFORMATION."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'DISCIPLINE_INFORMATION', url: '/discipline/byclass/?camIds=".$this->urlEncryp->encryptedGet($disciplineParams)."'})]
        }";
        
        //if (UserAuth::getACLTutorPermint("STUDENT_DISCIPLINE"))
        $PANEL_ITEMS[] = "" . $DISCIPLINE_INFORMATION . "";
        
        $listOfStudentsParams = "objectId=".$classObject->ID."";
        $LIST_OF_STUDENTS = "{
            title: '".LIST_OF_STUDENTS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'LIST_OF_STUDENTS', url: '/academic/studentlist?camIds=".$this->urlEncryp->encryptedGet($listOfStudentsParams)."'})]
        }";
        
        //if (UserAuth::getACLTutorPermint("LIST_OF_STUDENTS"))
        $PANEL_ITEMS[] = "" . $LIST_OF_STUDENTS . "";
        
        $listOfTeachersParams = "objectId=".$classObject->ID."";
        $LIST_OF_TEACHERS = "{
            title: '".LIST_OF_TEACHERS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'LIST_OF_TEACHERS', url: '/academic/teacherclassmain/?camIds=".$this->urlEncryp->encryptedGet($listOfTeachersParams)."'})]
        }";
        
        if (UserAuth::getACLTutorPermint("LIST_OF_TEACHERS"))
        $PANEL_ITEMS[] = "" . $LIST_OF_TEACHERS . "";
        
        $extraclassParams = "objectId=".$classObject->ID."&teacherId=".$this->objectId."";
        $EXTRA_CLASS = "{
            title: '".EXTRA_CLASS."'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'EXTRA_CLASS', url: '/extraclass/showitem/?camIds=".$this->urlEncryp->encryptedGet($extraclassParams)."'})]
        }";
        $PANEL_ITEMS[] = "" . $EXTRA_CLASS . "";
        
        $CHOOSE_ITEMS = "[".implode(',',$PANEL_ITEMS)."]";
        
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>