<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

if($this->objectId == "new"){
    $this->roleId = isset($_GET['roleId'])?$_GET['roleId']:"";
}

$REGISTRY_OBJECT = Zend_Registry::getInstance();
$OBJECT_DATA = $this->objectData;
$LOGIN_USER_OBJECT = $REGISTRY_OBJECT->USER;

$CHECK_LOGIN_SUPERUSER = $LOGIN_USER_OBJECT->SUPERUSER;

$CHECK_SUPERUSER = isset($OBJECT_DATA["SUPERUSER"])?$OBJECT_DATA["SUPERUSER"]:false;
$ROLE = isset($OBJECT_DATA["ROLE"])?$OBJECT_DATA["ROLE"]:false;

$ROLE_ADMIN = false;
if ($ROLE == 1){
    $ROLE_ADMIN = true;
}

if ($CHECK_SUPERUSER){
    $DISABLED_USER_ROLE = "true";
}else{
    $DISABLED_USER_ROLE = "false";
}

$OBJECT_FORM = new CamemisForm("USER");
$OBJECT_FORM->setLoadUrl('/user/jsonload/');
$OBJECT_FORM->setSaveUrl('/user/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    var objectId = '<?=$this->objectId;?>';
    var userId = '<?=Zend_Registry::get('USERID')?>';
    Ext.apply(Ext.form.VTypes, {
        password : function(val, field) {
            if (field.initialPassField) {
                var pwd = Ext.getCmp(field.initialPassField);
                return (val == pwd.getValue());
            }
            return true;
        },
        passwordText : 	'<?=PASSWORDS_ARE_DIFFERENT;?>'
    });
    Ext.onReady(function() {

        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
         
        if(!SchoolDBAccess::displayPersonNameInGrid()){
            $DETAIL_INFORMATION = "
            {
                title: '".DETAIL_INFORMATION."'
                ,id: 'DETAIL_INFORMATION_ID'
                ,autoHeight: true
                ,collapsible: true
                ,collapsed: false
                ,style: 'padding-bottom: 5px'
                ,width: 550
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle: 'padding:10px'
                    ,items: [
                        {".CamemisField::Textfield("LASTNAME_ID","LASTNAME",LASTNAME, true)."},
                        {".CamemisField::Textfield("FIRSTNAME_ID","FIRSTNAME",FIRSTNAME, true)."}
                    ]
                }]
            }
            ";
        }else{
            $DETAIL_INFORMATION = "
            {
                title: '".DETAIL_INFORMATION."'
                ,id: 'DETAIL_INFORMATION_ID'
                ,autoHeight: true
                ,collapsible: true
                ,collapsed: false
                ,style: 'padding-bottom: 5px'
                ,width: 550
                ,items:[{
                    layout: 'form'
                    ,border: false
                    ,autoHeight:true
                    ,bodyStyle: 'padding:10px'
                    ,items: [
                        {".CamemisField::Textfield("FIRSTNAME_ID","FIRSTNAME",FIRSTNAME, true)."},
                        {".CamemisField::Textfield("LASTNAME_ID","LASTNAME",LASTNAME, true)."}
                    ]
                }]
            }
            ";
        }

        $USER_ROLE_ITEMS = "
        {
            title: '" . USER_ROLE . "'
            ,disabled: ".$DISABLED_USER_ROLE."
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,layout: 'form'
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::ComboUserRole(NAME, true)."}
            ]
        }";
        
        $ADD_USER_ROLE_ITEMS = "
        {
            title: '" . ADDITIONAL_USER_ROLE . "'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,layout: 'form'
            ,bodyStyle: 'padding:10px'
            ,items: [
                {".CamemisField::ComboAddUserRole(NAME)."}
            ]
        }";
        
        $CHANGE_PASSWORD_ITEM = "{fieldLabel: '".NEW_LOGINNAME."',width: 250,xtype: 'textfield',name: 'LOGINNAME',id: 'LOGINNAME',allowBlank: true}";
        $CHANGE_PASSWORD_ITEM .= ",{fieldLabel: '".PASSWORD."',width: 250,xtype: 'textfield',name: 'PASSWORD',id: 'PASSWORD',inputType: 'password',allowBlank: true}";
        $CHANGE_PASSWORD_ITEM .= ",{fieldLabel: '".PASSWORD_REPEAT."',width: 250,xtype: 'textfield',name: 'PASSWORD_REPEAT',vtype: 'password',initialPassField: 'PASSWORD',inputType: 'password',allowBlank: true}";
        $CHANGE_PASSWORD_ITEM .= ",{".CamemisField::Checkbox("UMCPANL","UMCPANL", USER_MUST_CHANGE_PASSWORD_AT_NEXT_LOGIN, 1, false)."}";
        $CHANGE_PASSWORD_ITEM .= ",{".CamemisField::Checkbox("UCNCP","UCNCP", USER_CAN_NOT_CHANGE_PASSWORD, 1, false)."}";

        $PASSWORD = "
        {
            title: '".CHANGE_PASSWORD."'
            ,iconCls:'".$this->status_password_icon."'
            ,tabTip: '".CHANGE_PASSWORD."'
            ,id: 'CHANGE_PASSWORD'
            ,autoHeight: true
            ,collapsible: true
            ,collapsed: false
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,autoHeight:true
                ,bodyStyle: 'padding:10px'
                ,items: [".$CHANGE_PASSWORD_ITEM."]
            }]
        }
        ";
        
        $ITEMS = "[";
        $ITEMS .= $DETAIL_INFORMATION;
        
        if ($this->objectId !="new"){
            $ITEMS .= ",".$USER_ROLE_ITEMS;
            
            if (!$CHECK_SUPERUSER || $ROLE<>1 || $ROLE<>2){
                $ITEMS .= ",".$ADD_USER_ROLE_ITEMS;
            }
            
            $ITEMS .= ",".$PASSWORD;
        }
        
        $ITEMS .= "]";

        $formItems = "
            border: false
            ,autoScroll: true
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: ".$ITEMS."
        ";
        
        $OBJECT_FORM->addObjectItems($formItems);
        
        $OBJECT_FORM->addTBarItems("
            text: '".CANCEL."'
            ,id: 'CANCEL_ID'
            ,formBind:true
            ,iconCls:'icon-cancel'
            ,scope:this
            ,handler: function(){
                window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                if(window.parent.Ext.getCmp('WEST_ID'))
                window.parent.Ext.getCmp('WEST_ID').expand();
            }  
        ");
        
        if ($this->objectId !="new"){
            
            if (!$CHECK_SUPERUSER){
                
                if (Zend_Registry::get('USERID') == $this->objectId) {
                    if(UserAuth::getACLValue("USER_LIST_EDIT_RIGHT"))
                    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
                }else{
                    if(UserAuth::getACLValue("USER_LIST_REMOVE_RIGHT"))
                    $OBJECT_FORM->addTBarItems(CamemisBar::tbarFormRemoveObject($this->remove_status));
                    if(UserAuth::getACLValue("USER_LIST_REMOVE_RIGHT"))
                    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSetRelease($this->status));
                    if(UserAuth::getACLValue("USER_LIST_EDIT_RIGHT"))
                    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSave());
                    $OBJECT_FORM->addTBarItems("
                        text: '".SHOW_DETAIL."'
                        ,iconCls:'icon-application_form_magnify'
                        ,handler: function(){
                            var openUrl = '/staff/staffmonitor/?target=".camemisId()."&objectId=$this->objectId';
                            clickOpenPage('center','',openUrl);
                        }
                    ");
                }
            }elseif($CHECK_LOGIN_SUPERUSER){
                if (Zend_Registry::get('USERID') == $this->objectId) {
                    if(UserAuth::getACLValue("USER_LIST_EDIT_RIGHT"))
                    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
                }
            }
        }else{
            if(UserAuth::getACLValue("USER_LIST_EDIT_RIGHT"))
            $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
        }
        
        $OBJECT_FORM->setLoadParams("
            cmd: 'loadObject'
            ,objectId: '".$this->objectId."'
        ");

        $OBJECT_FORM->setReleaseParams("cmd: 'releaseObject',objectId: '".$this->objectId."'");

        if ($this->objectId == "new"){

            $OBJECT_FORM->setSaveParams("
                cmd: 'addObject'
                ,roleId: '".$this->roleId."'
                ,objectId: '".$this->objectId."'
            ");

            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                myTree = window.parent.Ext.getCmp('TREE.USERROLE_LIST_ID');
                myNode = myTree.getNodeById('".$this->roleId."');
                myNode.reload();
                myNode.expand(true, false);
                ".camemisPage::setRequestURI()."
               window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
            ");
        }else{

            $OBJECT_FORM->setSaveParams("
                cmd: 'updateObject'
                ,roleId: '".$this->roleId."'
                ,objectId: '".$this->objectId."'
            ");

            $OBJECT_FORM->setonEmbeddedEvents("
                XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
                myTree = window.parent.Ext.getCmp('TREE.USERROLE_LIST_ID');
                myNode = myTree.getNodeById('".$this->roleId."');
                myNode.reload();
                myNode.expand(true, false);
                ".camemisPage::setRequestURI()."
            ");
        }
        
        $OBJECT_FORM->setOnEmbeddedReleaseEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('TREE.USERROLE_LIST_ID');
            myNode = myTree.getNodeById('".$this->roleId."');
            myNode.reload();
            myNode.expand(true, false);
            ".camemisPage::setRequestURI()."
        ");
    
        $OBJECT_FORM->setRemoveParams("
            cmd: 'removeObject'
            ,objectId: '".$this->objectId."'
        ");

        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myTree = window.parent.Ext.getCmp('TREE.USERROLE_LIST_ID');
            myNode = myTree.getNodeById('".$this->roleId."');
            myNode.reload();
            myNode.expand(true, false);
            window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
        ");

        $OBJECT_FORM->msgError = MSG_ERROR_RELEASE_USER;
        $OBJECT_FORM->releaseError = true;
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->labelWidth = 130;
        
        if ($this->objectId == "new"){
            $OBJECT_FORM->isObjectDefaultOnLoad = false;
        }else{
            $OBJECT_FORM->isObjectDefaultOnLoad = true;
        }
        
        $OBJECT_FORM->renderJS();
        /**
         * Form end...
         */
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items: [{
                border: false
                ,layout: 'card'
                ,id: 'center'
                ,activeItem: 0
                ,items: [{
                    layout: 'fit'
                    ,border: false
                    ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
                }]
            }]  
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>