<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("USER_ONLINE");  
$OBJECT_FORM->setLoadUrl('/user/jsonload/');

$OBJECT_GRID = new CamemisGrid("USER_ONLINE", "LIST");
$OBJECT_GRID->setLoadUrl("/user/jsonload/");

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    var startDate;
    var endDate;
    Ext.apply(Ext.form.VTypes, {
        daterange : function(val, field) {
            var date = field.parseDate(val);
            if(!date){
                return false;
            }
            if (field.startDateField) {
                var start = Ext.getCmp(field.startDateField);
                if (!start.maxValue || (date.getTime() !== start.maxValue.getTime())) {
                    start.setMaxValue(date);
                    start.validate();
                }
            }
            else if (field.endDateField) {
                var end = Ext.getCmp(field.endDateField);
                if (!end.minValue || (date.getTime() !== end.minValue.getTime())) {
                    end.setMinValue(date);
                    end.validate();
                }
            }
            return true;
        }
    });
    Ext.onReady(function() {
        function cssText(value, metadata, record){
            return '<div style="color:#333; padding: 5px; height: 15px;">' + value + '</div>';
        }
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();   
        
        if(!SchoolDBAccess::displayPersonNameInGrid()){
            $OBJECT_FORM->addObjectItems("
                xtype:'fieldset'
                ,collapsible:true,collapsed:false
                ,collapsed: false
                ,title: '".PERSONAL_INFORMATION."'
                ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;padding:10px'
                ,width: 310
                ,items:[
                    {".CamemisField::Textfield("CODE", "CODE", CODE_ID, false, false, false, 150)."}
                    ,{".CamemisField::Textfield("LASTNAME", "LASTNAME", LASTNAME, false, false, false, 150)."}    
                    ,{".CamemisField::Textfield("FIRSTNAME", "FIRSTNAME", FIRSTNAME, false, false, false, 150)."}
                    ,{
                        name: 'START_DATE'
                        ,hidden: false
                        ,width: 150
                        ,fieldLabel: '" . START_DATE . "'
                        ,xtype: 'datefield'
                        ,id: 'START_DATE'
                        ,vtype: 'daterange'
                        ,endDateField: 'END_DATE'
                        ,format: '" . setExtDatafieldFormat() . "'
                        ,allowBlank: true
                    },{
                        name: 'END_DATE'
                        ,hidden: false
                        ,width: 150
                        ,fieldLabel: '" . END_DATE . "'
                        ,xtype: 'datefield'
                        ,id: 'END_DATE'
                        ,vtype: 'daterange'
                        ,format: '" . setExtDatafieldFormat() . "'
                        ,startDateField: 'START_DATE'
                        ,allowBlank: true
                    }
                ]
            ");
        }else{
            $OBJECT_FORM->addObjectItems("
                xtype:'fieldset'
                ,collapsible:true,collapsed:false
                ,collapsed: false
                ,title: '".PERSONAL_INFORMATION."'
                ,bodyStyle: 'background:".CamemisPage::userFormBgColor()."; color:#000;padding:10px'
                ,width: 310
                ,items:[
                    {".CamemisField::Textfield("CODE", "CODE", CODE_ID, false, false, false, 150)."}
                    ,{".CamemisField::Textfield("FIRSTNAME", "FIRSTNAME", FIRSTNAME, false, false, false, 150)."}
                    ,{".CamemisField::Textfield("LASTNAME", "LASTNAME", LASTNAME, false, false, false, 150)."} 
                    ,{
                        name: 'START_DATE'
                        ,hidden: false
                        ,width: 150
                        ,fieldLabel: '" . START_DATE . "'
                        ,xtype: 'datefield'
                        ,id: 'START_DATE'
                        ,vtype: 'daterange'
                        ,endDateField: 'END_DATE'
                        ,format: '" . setExtDatafieldFormat() . "'
                        ,allowBlank: false
                    },{
                        name: 'END_DATE'
                        ,hidden: false
                        ,width: 150
                        ,fieldLabel: '" . END_DATE . "'
                        ,xtype: 'datefield'
                        ,id: 'END_DATE'
                        ,vtype: 'daterange'
                        ,format: '" . setExtDatafieldFormat() . "'
                        ,startDateField: 'START_DATE'
                        ,allowBlank: false
                    }
                ]
            ");
        }
        
        $OBJECT_FORM->addTBarItems("
            text: '".RESET."'
            ,iconCls:'icon-arrow_undo'
            ,handler: function(){
                ".CamemisPage::setRequestURI()."
            }
        ");
        
        $OBJECT_FORM->addTBarItems("
            text: '".FIND."'
            ,id: 'FIND_ID'
            ,formBind:true
            ,iconCls:'icon-magnifier'
            ,scope:this
            ,handler: function(){
                form = this.getForm();
                _startDate = form.findField('START_DATE').getValue();
                _endDate = form.findField('END_DATE').getValue();
                startDate = _startDate?_startDate.format('Y-m-d'):'';
                endDate =_endDate? _endDate.format('Y-m-d'):'';
                Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.baseParams = {
                    start:0
                    ,limit:100
                    ,cmd: 'jsonUserOnline'
                    ,code:form.findField('CODE').getValue()
                    ,firstname:form.findField('FIRSTNAME').getValue()
                    ,lastname:form.findField('LASTNAME').getValue()
                    ,startdt:startDate
                    ,enddt:endDate
                    ,type:'search'
                };
                Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.load();
            }
        ");
    
        $OBJECT_FORM->setBodyStyle("padding:10px;background:".CamemisPage::userFormBgColor().";");
        $OBJECT_FORM->labelAlign = "left";
        $OBJECT_FORM->isObjectDefaultOnLoad = false;
        $OBJECT_FORM->isKeys = false;
        $OBJECT_FORM->renderJS();
        
        $OBJECT_GRID->addReadField("name: 'USER_LOGIN'");
        $OBJECT_GRID->addReadField("name: 'USER_ROLE'");
        $OBJECT_GRID->addReadField("name: 'ACTIVITY_DATE'");
        
        $OBJECT_GRID->addColumn("header: '<b>".USER."</b>', align:'left', renderer:cssText, sortable: true, width: 200, dataIndex: 'USER_LOGIN'");
        $OBJECT_GRID->addColumn("header: '<b>".USER_ROLE."</b>', width: 250, renderer:cssText, sortable: true, dataIndex: 'USER_ROLE'");
        $OBJECT_GRID->addColumn("header: '<b>".ACTIVITY_DATE."</b>', width: 150, renderer:cssText, sortable: true, dataIndex: 'ACTIVITY_DATE'");
        
        $OBJECT_GRID->baseParams = "
            start:0
            ,limit:100
            ,cmd: 'jsonUserOnline'
            ,type:'search'
        ";
        $OBJECT_GRID->objectTitle = USER_ONLINE;
        $OBJECT_GRID->isObjectDefaultOnLoad = true;
        $OBJECT_GRID->forceFit = "false";
        $OBJECT_GRID->loadMask = false;
        $OBJECT_GRID->renderJS();
        ?>
                
        var mainquoterefresh = {
        run: function(){
            Ext.getCmp('<?=$OBJECT_GRID->getObjectId()?>').store.load();
        },
            interval: 10000 //1 second
        }
        Ext.TaskMgr.start(mainquoterefresh);

        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    region:'west'
                    ,id:'WEST_ID'
                    ,margins: '3 0 3 3'
                    ,cmargins: '3 3 3 3'
                    ,width: 350
                    ,minSize: 350
                    ,maxSize: 350
                    ,layout: 'fit'
                    ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
                },{
                    collapsible: false
                    ,id: 'center'
                    ,region:'center'
                    ,margins: '3 3 3 0'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,items: [{
                        layout: 'fit'
                        ,border: false
                        ,items:[{xtype: '<?=$OBJECT_GRID->getObjectXtype();?>'}]
                    }]
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>