<?
///////////////////////////////////////////////////////////
//@Chung veng Web Developer
// Date: 22.06.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
$OBJECT_TREE = new CamemisTree("CLUB", "LIST");
$OBJECT_TREE->setURL("/club/jsontree/");

$HIDDEN_ADD_ENTRY = false;    
    switch(UserAuth::getUserType()){
        case "ADMIN":
        case "SUPPERADMIN":
            $HIDDEN_ADD_ENTRY = false;
        case "STUDENT":
        case "TEACHER":
        case "INSTRUCTOR":
            $HIDDEN_ADD_ENTRY = true;
        break;
    }
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    $CAMEMIS_PAGE_OBJECT->setAddTab();
    
    $OBJECT_TREE->isAsyncTreeNode = false;   
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeRefresh());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeExpand());
    $OBJECT_TREE->addTBarItems(CamemisBar::tbarTreeCollapse());
    $OBJECT_TREE->setBaseParams("
        cmd: 'jsonTreeAllClubs'
    ");
    
    $OBJECT_TREE->addTBarItems("
        id: 'CLUB'
        ,tooltip:'".CLUB."'
        ,scope:this 
        ,hidden:'".$HIDDEN_ADD_ENTRY."'
        ,iconCls:'icon-application_form_add'
        ,handler: function(){
            clickOpenPage('center','".CLUB."', '".$this->URL_SHOWITEM."&objectId=new&parent=0');    
        }
    ");
    $OBJECT_TREE->backgroundColor = "#F9F9F9";
    $OBJECT_TREE->labelWidth = 310;
    $OBJECT_TREE->isTreeExpand = false;
    $OBJECT_TREE->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: true
                ,split: true
            }
            ,items: [{                                                                     
                region:'west'
                ,title:'<?=CLUB;?>'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width:350
                ,minSize:350
                ,maxSize:350
                ,layout: 'fit'
                ,items:[{xtype: '<?=$OBJECT_TREE->getObjectXtype();?>'}]
            },{
                collapsible: false
                ,id: 'center'
                ,region:'center'
                ,margins: '3 3 3 0'
                ,layout: 'card'
                ,activeItem: 0
                ,items: [{
                    border: false
                    ,layout: 'anchor'
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items: [{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                    }]
                }]
            }]
        }]
    });
    
    var myTree = <?=$OBJECT_TREE->ExtgetCmp();?>;
    myTree.on('click', function(node, e){
  
        if(node.isLeaf()==1){
            var addurl='<?=$this->URL_SHOWITEM;?>objectId=new&parentId=' + node.id; 
            var chooseUrl = '<?=$this->URL_SHOWITEM;?>objectId=' + node.id;       
        }else{
            var chooseUrl = '<?=$this->URL_ADDITEM;?>objectId=' + node.id;
            var addurl='<?=$this->URL_SHOWITEM;?>objectId=new&parentId=' + node.id        
        }  
        var contextMenu = new Ext.menu.Menu({ 
            items: [{
                text: '<?=SHOW_DETAIL;?>'
                ,iconCls:'icon-application_form_magnify'
                ,handler:function(){
                    clickOpenPage('center','<?=SHOW_DETAIL?>',chooseUrl);
                }
            },{
                text: '<?=ADD_A_NEW_ITEM;?>'
                ,iconCls:'icon-application_form_add' 
                ,hidden:'<?=$HIDDEN_ADD_ENTRY?>' 
                ,handler: function(){
                    clickOpenPage('center','<?=SHOW_DETAIL?>',addurl);
                }
            }]
        });
         
        e.stopEvent();
        contextMenu.showAt(e.xy); 
    });
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>