<?
///////////////////////////////////////////////////////////
// @sor veasna
// Date: 18.02.2014
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'include/Common.inc.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<script>
    
    Ext.onReady(function() {
        
        <?
        /**
         * Extjs: s.gif
         */
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
        $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
        
        $PENEL_ITEMS = Array();
        
        $FORUM = "{
            title: 'Main'
            ,layout: 'fit'
            ,items:[new Ext.ux.IFrameComponent({ id: 'FORUM', url: '/forum/forum/?key=".camemisId()."&camIds=" . $this->urlEncryp->encryptedGet("target=".$this->target."") . "'})]
        }";
        $PENEL_ITEMS[] = $FORUM;
        
        $FORUM_CATEGORY = "{
            title: '".SEARCH."'
            ,layout: 'fit'
            ,disabled: true,
        }";
        $PENEL_ITEMS[] = $FORUM_CATEGORY;
        
        $CHOOSE_ITEMS = "[".implode(',',$PENEL_ITEMS)."]";
        ?>
        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'fit'
                ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px'
                ,border: false
                ,items:[{
                    xtype: 'tabpanel'
                    ,tabPosition: 'top'
                    ,plain:true
                    ,activeTab: 0
                    ,enableTabScroll:true
                    ,items:<?=$CHOOSE_ITEMS?>
                }]
            }]
        });
    });
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>