<?
///////////////////////////////////////////////////////////
// @sor veasna
// Date: 18.02.2014
//////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_FORM = new CamemisForm("FORUM");
$OBJECT_FORM->setLoadUrl('/forum/jsonload/');
$OBJECT_FORM->setSaveUrl('/forum/jsonsave/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>
Ext.onReady(function() {
    <?
    /**
     * Extjs: s.gif
     */
     
     //////////////////////////////////////////
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $NEW_TOPIC = "
        {
            title: 'New Topic'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'form'
                ,border: false
                ,bodyStyle: 'padding:10px'
                ,items: [{".CamemisField::Textfield("TOPIC","TOPIC","Topic",true)."}]
            }]
        }
        ";
    
    $DESCRIPTION = "
        {
            title: '".CONTENT."'
            ,autoHeight: true
            ,style: 'padding-bottom: 5px'
            ,width: 550
            ,items:[{
                layout: 'fit'
                ,border: false
                ,bodyStyle: 'background:#FFF; padding:10px'
                ,items: [{".CamemisField::Textarea("CONTENT", CONTENT, 250, false, true)."}]
                //,items: [{".CamemisField::HTML("CONTENT", 250, false)."}]
            }]
        }
        ";
    
    $FORM_ITMES = "[";
        $FORM_ITMES .= $NEW_TOPIC;
        $FORM_ITMES .= ",".$DESCRIPTION;
     $FORM_ITMES .= "]";
     
     $items = "
            border: false
            ,id: 'FORM_ITEMS'
            ,bodyStyle: 'padding:0px'
            ,items: ".$FORM_ITMES."
        ";
    
    $OBJECT_FORM->addObjectItems($items);

    if($this->targetAction!=='REPLY')
    $OBJECT_FORM->addTBarItems("
        text: '".CANCEL."'
        ,id: 'CANCEL_ID'
        ,formBind:true
        ,iconCls:'icon-cancel'
        ,scope:this
        ,handler: function(){
            window.parent.Ext.getCmp('main-tabs').getLayout().setActiveItem(0);    
        }
    ");
    if($this->targetAction!=='REPLY'){
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
            myGrid = window.parent.Ext.getCmp('FORUM_LIST_ID');
            myGrid.store.load();
            var result = Ext.util.JSON.decode(action.response.responseText);
            var objectId = result.objectId;
            window.location='".$_SERVER["REQUEST_URI"]."&objectId='+objectId;
                
        ");
        
        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."'); 
            myGrid = window.parent.Ext.getCmp('FORUM_LIST_ID');
            myGrid.store.load();
            window.parent.Ext.getCmp('main-tabs').getLayout().setActiveItem(0);
        ");  
    }else{
        $OBJECT_FORM->setonEmbeddedEvents("
            XMsg('".STATUS."','".ACTION_SUCCESSFULLY_SAVED."');
            myTreeGrid = window.parent.Ext.getCmp('TREE_GRID_FORUM');
            myTreeGrid.root.reload();
            myTreeGrid.getRootNode().expand(true, false);
            myGrid = window.parent.Ext.getCmp('FORUM_LIST_ID');
            myGrid.store.load();
            var result = Ext.util.JSON.decode(action.response.responseText);
            var objectId = result.objectId;
            window.location='".$_SERVER["REQUEST_URI"]."&objectId='+objectId;
                
        ");
        
        $OBJECT_FORM->setOnEmbeddedRemoveEvents("
            
            myGrid = window.parent.Ext.getCmp('FORUM_LIST_ID');
            myGrid.store.load();
            myTreeGrid = window.parent.Ext.getCmp('TREE_GRID_FORUM');
            myTreeGrid.root.reload();
            myTreeGrid.getRootNode().expand(true, false);
            window.parent.Ext.getCmp('OPEN_WIN_IFRAME_ID').close();
        "); 
      
    }
    
    if($this->objectId)
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleRemove());
    
    
    $OBJECT_FORM->addTBarItems(CamemisBar::tbarSingleSave());
    
    $OBJECT_FORM->setSaveParams("
        cmd: 'jsonSaveForum'
        ,objectId: '".$this->objectId."'
        ,parentId: '".$this->parentId."'
        ,CAMEMIS_TYPE: '".$this->camemisType."'
        ,OBJECT_TYPE: '".$this->target."'   
    ");
    
    $OBJECT_FORM->setRemoveParams("
            cmd: 'deleteForum'
            ,objectId: '".$this->objectId."'
        ");
    
    $OBJECT_FORM->setLoadParams("
        cmd: 'jsonLoadForum'
        ,objectId: '".$this->objectId."'     
    ");
    if($this->objectId){
    $OBJECT_FORM->isObjectDefaultOnLoad = true;
    }else{
    $OBJECT_FORM->isObjectDefaultOnLoad = false;    
    }
    $OBJECT_FORM->isObjectSend = true;
    $OBJECT_FORM->labelAlign = "left";
    $OBJECT_FORM->renderJS();
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            border: false
            ,layout: 'fit'
            ,items:[{xtype: '<?=$OBJECT_FORM->getObjectXtype();?>'}]
        }]
    });
    
    
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>