<?php
    ///////////////////////////////////////////////////////////
    // @sor veasna
    // Date: 12/17/2012
    // Adress
    ///////////////////////////////////////////////////////////
    require_once 'excel/phpexcel/Classes/PHPExcel.php';
    require_once 'excel/phpexcel/Classes/PHPExcel/IOFactory.php';
    require_once 'clients/CamemisExcelReport.php';
    require_once 'clients/CamemisExportToExcel.php';
    require_once 'models/app_school/examination/ExaminationDBAccess.php';
    require_once 'models/app_school/examination/StudentExaminationDBAccess.php';
    require_once 'models/app_school/subject/SubjectDBAccess.php'; 
    require_once 'models/app_school/academic/AcademicDBAccess.php';
    require_once 'models/app_school/AcademicDateDBAccess.php';
    require_once 'models/app_school/room/RoomDBAccess.php';
    $objectId = isset($_GET["objectId"]) ? addText($_GET["objectId"]) : "";
    $bnt=isset($_GET["bnt"])?$_GET["bnt"]:"";
    $exportToExcel=new CamemisExportToExcel();
    //school information
    $schoolObject = $exportToExcel->getSchoolInfo();
    $SchoolName = $schoolObject->NAME;
    $SchoolAdress=$schoolObject->ADDRESS;
    $schoolInfo= $SchoolName."\n".$SchoolAdress;
    //Exam Object
    $facette = ExaminationDBAccess::findExamFromId($objectId);
    
    if (!$facette) {header("Location: /main/permission/");}
    
    $exam=EXAM.": ".$facette->NAME;
    $startDate=START_DATE.': '.$facette->START_DATE;
    $examTime=START_END_TIME.': '.$facette->START_TIME.' - '.$facette->END_TIME;   
    //study year
    $academicObject=AcademicDateDBAccess::findAcademicDateFromId($facette->SCHOOLYEAR_ID);
    $academicDate= $academicObject->NAME;
    //subject
    $subjectObject=SubjectDBAccess::findSubjectFromId($facette->SUBJECT_ID);
    $subject=SUBJECT.": ".$subjectObject->NAME;
    //room
    $roomObject=RoomDBAccess::findRoomFromId($facette->ROOM_ID);    
    //class information
    $gradeObject = AcademicDBAccess::findGradeFromId($facette->GRADE_ID);
    $classInfo=$gradeObject->NAME;  
    if( $facette){
        if($facette->PARENT){//have parents or chile room
            $parentObject = ExaminationDBAccess::findExamParentFromId($objectId);   
            $params["objectId"] =  $parentObject->GUID;
            $params["roomId"]= $facette->ROOM_ID;
            $results = StudentExaminationDBAccess::getQueryAssignedStudentExamination($params);
            $academicDate .= ($bnt==3)?"":"\n".ROOM.": ". $roomObject->NAME; // room name    
        }else{//parents all students
            $params["objectId"] = $facette->GUID; 
            $results = StudentExaminationDBAccess::getQueryAssignedStudentExamination($params,false);                  
        }
    }
    //exam info
    $examinfo=$classInfo."\n".$academicDate."\n".$exam."\n".$subject."\n".$startDate."\n".$examTime; 
    $filds=array();
    $entries = array();
    //catch button 
    switch ($bnt) {
        case "1":                    
            $filds=array("NA","LASTNAME","FIRSTNAME","LASTNAME_LATIN","FIRSTNAME_LATIN","GENDER","ROOM_NAME");
            $showfilds=array("N°",LASTNAME,FIRSTNAME,LASTNAME_LATIN,FIRSTNAME_LATIN,GENDER,ROOM);
            $endCharExcel="G";
            break;
        case "2":                  
            $filds=array("NA","LASTNAME","FIRSTNAME","LASTNAME_LATIN","FIRSTNAME_LATIN","GENDER","ROOM_NAME","SIGNATURE");
            $showfilds=array("N°",LASTNAME,FIRSTNAME,LASTNAME_LATIN,FIRSTNAME_LATIN,GENDER,ROOM,SIGNATURE_STUDENT_SUBMISSION);
            $endCharExcel="H";  
            break;
        case "3":
            $filds=array("NA","LASTNAME","FIRSTNAME","LASTNAME_LATIN","FIRSTNAME_LATIN","EXAM_CODE");
            $showfilds=array("N°",LASTNAME,FIRSTNAME,LASTNAME_LATIN,FIRSTNAME_LATIN,CANDIDATE_CODE); 
            $endCharExcel="F";   
            break;
        case "4":
            $filds=array("NA","EXAM_CODE","SCORE");
            $showfilds=array("N°",CANDIDATE_CODE,SCORE); 
            $endCharExcel="C";   
            break;

    } 
    //input entries
    if($results){
        $exportToExcel->objExcel($results,$filds,$showfilds,3);
    } 
    $filename = "List of Student"; 
    $info['SCHOOL_INFO']=$schoolInfo;
    $info['CLASS_INFO']=$examinfo;  
    $exportToExcel->excelHeader($info,1,$endCharExcel); 
    $exportToExcel->excelFooter();
    $exportToExcel->save($filename);

?>

