<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'clients/CamemisPage.php';
require_once 'models/app_university/student/StudentDBAccess.php';
require_once 'models/app_university/finance/FeeDBAccess.php';
require_once 'models/app_university/finance/IncomeDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();


$Id = isset($_GET["objectId"]) ? addText($_GET["objectId"]) : "";
$incomeObject = IncomeDBAccess::findIncomeFromId($Id);

if (!$incomeObject)
    {header("Location: /main/permission/");}

$studentObject = StudentDBAccess::findStudentFromId($incomeObject->STUDENT);
$studentAcademic = StudentAcademicDBAccess::getCurrentStudentAcademic($incomeObject->STUDENT, false, false, false);
$feeObject = FeeDBAccess::findFeeFromId($incomeObject->FEE);

$school = Zend_Registry::get('SCHOOL');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

?>
<style type="text/css">

    table{
        font-weight:bold; color:#333;
        border-width: 0px;
        border-style: solid;
        border-color: silver;
        border-collapse: collapse;
    }
    
    table th.schoolHeader, table td.schoolHeader{
        width:220px;
        background-color:#FFF;
        border-width: 0px;
        padding: 6px;
        border-style: solid;
        border-color: silver;
        border-collapse: collapse;
        font-weight:bold;
    }
    
    table th.schoolBlock, table td.schoolBlock{
        width:220px;
        background-color:#FFF;
        border-width: 0px;
        padding: 6px;
        border-style: solid;
        border-color: silver;
        border-collapse: collapse;
        font-weight:bold;
    }
    
    table th.colHeader, table td.colHeader{
        width:220px;
        color:#000000;
        background-color:#d7e3f3;
        border-width: 1px;
        padding: 6px;
        border-style: solid;
        border-color: silver;
        border-collapse: collapse;
        font-weight:bold;
    }

    table th.colBlock, table td.colBlock{
        width:220px;
        background-color:#FFF;
        border-width: 1px;
        padding: 6px;
        border-style: solid;
        border-color: silver;
        border-collapse: collapse;
        font-weight:bold;
    }

</style>
<div style='margin:8px;padding:8px;'>
    <table>
        <tr>
            <th colspan="2" class="schoolHeader"><?= $school->NAME; ?></th>
        </tr>
        <tr>
            <td class="schoolBlock"><?= ADDRESS ?></td>
            <td class="schoolBlock"><?= $school->ADDRESS?$school->ADDRESS:"---" ?></td>
        </tr>
        <tr>
            <td class="schoolBlock"><?= EMAIL ?></td>
            <td class="schoolBlock"><?= $school->EMAIL?$school->EMAIL:"---" ?></td>
        </tr>
        <tr>
            <td class="schoolBlock"><?= PHONE ?></td>
            <td class="schoolBlock"><?= $school->PHONE?$school->PHONE:"---" ?></td>
        </tr>
    </table>
</div>
<div style='margin:8px;padding:8px;'>
    <table>
        <tr>
            <th colspan="2" class="colHeader"><?= PERSONAL_INFORMATION; ?></th>
        </tr>
        <?
        if(!SchoolDBAccess::displayPersonNameInGrid()){
        ?>
        <tr>
            <td class="colBlock"><?= LASTNAME ?></td>
            <td class="colBlock"><?= $studentObject->LASTNAME ?></td>
        </tr>
        <tr>
            <td class="colBlock"><?= FIRSTNAME ?></td>
            <td class="colBlock"><?= $studentObject->FIRSTNAME ?></td>
        </tr>
        <?
        }else{
        ?>
        <tr>
            <td class="colBlock"><?= FIRSTNAME ?></td>
            <td class="colBlock"><?= $studentObject->FIRSTNAME ?></td>
        </tr>
        <tr>
            <td class="colBlock"><?= LASTNAME ?></td>
            <td class="colBlock"><?= $studentObject->LASTNAME ?></td>
        </tr> 
        <?
        }
        ?>
        <tr>
            <td class="colBlock"><?= GENDER ?></td>
            <td class="colBlock"><?= getGenderName($studentObject->GENDER) ?></td>
        </tr>
        <tr>
            <td class="colBlock"><?= DATE_BIRTH ?></td>
            <td class="colBlock"><?= getShowDate($studentObject->DATE_BIRTH) ?></td>
        </tr>
    </table>
</div>
<div style='margin:8px;padding:8px;'>
    <table>
        <tr>
            <th colspan="2" class="colHeader"><?= SCHOOL_INFORMATION; ?></th>
        </tr>
        <tr>
            <td class="colBlock"><?= CAMPUS_INFORMATION ?></td>
            <td class="colBlock"><?= $studentAcademic->CAMPUS_NAME ?></td>
        </tr>
        <tr>
            <td class="colBlock"><?= CURRENT_CLASS ?></td>
            <td class="colBlock"><?= $studentAcademic->CLASS_NAME ?></td>
        </tr>
        <tr>
            <td class="colBlock"><?= CURRENT_SCHOOL_YEAR ?></td>
            <td class="colBlock"><?= $studentAcademic->SCHOOLYEAR ?></td>
        </tr>
    </table>
</div>
<div style='margin:8px;padding:8px;'>
    <table>
        <tr>
            <th colspan="2" class="colHeader"><?= SCHOOL_ENROLLMENT_FEES; ?></th>
        </tr>
        <tr>
            <td class="colBlock"><?= NAME ?></td>
            <td class="colBlock"><?= $feeObject->NAME ?></td>
        </tr>
        <tr>
            <td class="colBlock"><?= TRANSACTION_NUMBER ?></td>
            <td class="colBlock"><?= $incomeObject->TRANSACTION_NUMBER ?></td>
        </tr>
        <tr>
            <td class="colBlock"><?= TRANSACTION_DATE ?></td>
            <td class="colBlock"><?= getShowDateTime($incomeObject->CREATED_DATE) ?></td>
        </tr>
        <tr>
            <td class="colBlock"><?= TRANSACTION_AMOUNT ?></td>
            <td class="colBlock"><?= $incomeObject->AMOUNT ?> <?= Zend_Registry::get('SCHOOL')->CURRENCY ?></td>
        </tr>
    </table> 
</div>
<div style='margin:8px;padding:8px;'>
    <table>
        <tr>
            <td class="schoolBlock"><?= CREATED_DATE ?></td>
            <td class="schoolBlock"><?= getShowDateTime(getCurrentDBDateTime()) ?></td>
        </tr>
        <tr>
            <td class="schoolBlock"><?= CASHIER_SIGNATURE ?></td>
            <td class="schoolBlock">---</td>
        </tr>
    </table>
</div>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>