<?

///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once setUserLoacalization();

//$DB_ACCESS = Zend_Registry::get('DB_ACCESS');
//
//$SQL = "";
//$SQL .= " UPDATE t_health_setting";
//$SQL .= " SET";
//$SQL .= " NAME=NAME_EN";
//$DB_ACCESS->query($SQL);

Utiles::setUserPublicRoot();
Utiles::dbClean();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();

$OBJECT_TREE = new CamemisTree("MAIN", "LIST");
$OBJECT_TREE->setURL('/staff/jsontree/');

$schoolName = (Zend_Registry::get('SCHOOL')->NAME)?Zend_Registry::get('SCHOOL')->NAME:"";
$objectId = Zend_Registry::get('USER')->ID;

$HTML = "";
    $HTML .= "<div id=\"initUserNav\" class=\"x-hidden\" style=\"background:#EEE;\">";
    $HTML .= "<div class=\"container\">";
        $HTML .= "<ul class=\"ca-menu\">";
            $HTML .= "<li>";
                $HTML .= "<a id=\"IdBulletinBoard\" href=\"#\">";
                    $HTML .= "<span class=\"ca-iconBulletinBoard\">&nbsp;</span>";
                    $HTML .= "<div class=\"ca-content\">";
                        $HTML .= "<h2 class=\"ca-main\">".BULLETIN_BOARD."</h2>";
                        $HTML .= "<h3 id=\"IdBulletin\" class=\"ca-sub\"></h3>";
                    $HTML .= "</div>";
                $HTML .= "</a>";
            $HTML .= "</li>";
            $HTML .= "<li>";
                $HTML .= "<a id=\"IdCommunication\" href=\"#\">";
                    $HTML .= "<span class=\"ca-iconCommunication\">&nbsp;</span>";
                    $HTML .= "<div class=\"ca-content\">";
                        $HTML .= "<h2 class=\"ca-main\">".COMMUNICATION."</h2>";
                        $HTML .= "<h3 id=\"IdInbooxMessage\" class=\"ca-sub\"></h3>";
                    $HTML .= "</div>";
                $HTML .= "</a>";
            $HTML .= "</li>";
            $HTML .= "<li>";
                $HTML .= "<a id=\"IdMyAccount\" href=\"#\">";
                    $HTML .= "<span class=\"ca-iconMyAccount\">&nbsp;</span>";
                    $HTML .= "<div class=\"ca-content\">";
                        $HTML .= "<h2 class=\"ca-main\">".MY_ACCOUNT."</h2>";
                        $HTML .= "<h3 class=\"ca-sub\"></h3>";
                    $HTML .= "</div>";
                $HTML .= "</a>";
            $HTML .= "</li>";
            $HTML .= "<li>";
                $HTML .= "<a id=\"IdAbsence\" href=\"#\"\>";
                    $HTML .= "<span class=\"ca-iconAbsence\">&nbsp;</span>";
                    $HTML .= "<div class=\"ca-content\">";
                        $HTML .= "<h2 class=\"ca-main\">".ATTENDANCE."</h2>";
                        $HTML .= "<h3 class=\"ca-sub\"></h3>";
                    $HTML .= "</div>";
                $HTML .= "</a>";
            $HTML .= "</li>";
            if(UserAuth::getAddedUserRole() || UserAuth::getUserType()=='SUPERADMIN'|| UserAuth::getUserType()=='ADMIN'){
            $HTML .= "<li>";
                $HTML .= "<a id=\"IdUserOnline\" href=\"#\">";
                    $HTML .= "<span class=\"ca-iconUserOnline\">&nbsp;</span>";
                    $HTML .= "<div class=\"ca-content\">";
                        $HTML .= "<h2 class=\"ca-main\">".USER_ONLINE."</h2>";
                        $HTML .= "<h3 id=\"Iduseronline\" class=\"ca-sub\"></h3>";
                    $HTML .= "</div>";
                $HTML .= "</a>";
            $HTML .= "</li>";
            }
            $HTML .= "<li>";
                $HTML .= "<a id=\"IdPersonalInformation\" href=\"#\">";
                    $HTML .= "<span class=\"ca-iconPersonalInformation\">&nbsp;</span>";
                    $HTML .= "<div class=\"ca-content\">";
                        $HTML .= "<h2 class=\"ca-main\">".MY_PROFILE."</h2>";
                        $HTML .= "<h3 class=\"ca-sub\"></h3>";
                    $HTML .= "</div>";
                $HTML .= "</a>";
            $HTML .= "</li>";
        $HTML .= "</ul>";
    $HTML .= "</div>";
$HTML .= "</div>";

?>
<script>

    Ext.onReady(function() {

        var updateClock = function(){
            Ext.getCmp('clock').setText('<b><?=showCurrentDBDate();?> '+new Date().format('g:i:s A')+'</b>');
        };
        var clock = new Ext.Toolbar.TextItem({id:'clock',text: '<b><?=showCurrentDBDate();?> 00:00:00 AM</b>'});

        var task = {
            run: updateClock,//the method to run...
            interval: 1000 //every second
        };
        var runner = new Ext.util.TaskRunner();
        runner.start(task);

        Ext.state.Manager.setProvider(new Ext.state.CookieProvider());
        if (get_cookie('tokenId')) var tokenId = get_cookie('tokenId');
        <?
        $CAMEMIS_PAGE_OBJECT->setAddTab();
        $CAMEMIS_PAGE_OBJECT->setCostumerCSS();

        //@veansa
        //user online
        $USER_ONLINE="";
        $USER_ONLINE.="var userOnline = {";
             $USER_ONLINE.="run: function(){";
                $USER_ONLINE.="Ext.Ajax.request({";
                $USER_ONLINE.="url: '/user/jsonload/'";
                $USER_ONLINE.=",method: 'POST'";
                $USER_ONLINE.=",params:{cmd: 'jsonCountUsersOnline'}";
                    $USER_ONLINE.=",success: function(result, options) {";
                        $USER_ONLINE.="jsondata = Ext.util.JSON.decode(result.responseText);";
                        $USER_ONLINE.="Ext.fly('Iduseronline').dom.innerHTML='('+jsondata.totalCount+')';";
                    $USER_ONLINE.="} ";
                $USER_ONLINE.="});";
            $USER_ONLINE.="}";
            $USER_ONLINE.=",interval: 10000";
        $USER_ONLINE.="};";
        $USER_ONLINE.="Ext.TaskMgr.start(userOnline);";

        $INBOX_MESSAGE="";
        $INBOX_MESSAGE.="var inboxMessage = {";
            $INBOX_MESSAGE.="run: function(){";
                    $INBOX_MESSAGE.="Ext.Ajax.request({";
                        $INBOX_MESSAGE.="url: '/dataset/remote'";
                        $INBOX_MESSAGE.=",method: 'POST'";
                        $INBOX_MESSAGE.=",params: { ";
                            $INBOX_MESSAGE.="cmd: 'jsonLoadNewMessage'";
                            $INBOX_MESSAGE.=",type: 'INBOX'";
                            $INBOX_MESSAGE.=",recipientType: 'STAFF'";
                        $INBOX_MESSAGE.="}";
                        $INBOX_MESSAGE.=",success: function(response) {";
                            $INBOX_MESSAGE.="jsonData = Ext.util.JSON.decode(response.responseText);";
                            $INBOX_MESSAGE.="Ext.fly('IdInbooxMessage').dom.innerHTML='('+jsonData.count+')';";
                        $INBOX_MESSAGE.="}";
                        $INBOX_MESSAGE.=",failure: function() {}";
                    $INBOX_MESSAGE.="});";
                $INBOX_MESSAGE.="}";
                $INBOX_MESSAGE.=",interval: 20000";
        $INBOX_MESSAGE.="};";
        $INBOX_MESSAGE.="Ext.TaskMgr.start(inboxMessage);";

        $BULLETIN="";
        $BULLETIN.="var bulletin = {";
            $BULLETIN.="run: function(){";
                    $BULLETIN.="Ext.Ajax.request({";
                        $BULLETIN.="url: '/bulletin/jsonload'";
                        $BULLETIN.=",method: 'POST'";
                        $BULLETIN.=",params: { ";
                            $BULLETIN.="cmd: 'jsonAllBulletins'";
                            $BULLETIN.=",type:1";
                            $BULLETIN.=",start:0";
                            $BULLETIN.=",limit:100";
                        $BULLETIN.="}";
                        $BULLETIN.=",success: function(response) {";
                            $BULLETIN.="jsonData = Ext.util.JSON.decode(response.responseText);";
                            $BULLETIN.="Ext.fly('IdBulletin').dom.innerHTML='('+jsonData.totalCount+')';";
                        $BULLETIN.="}";
                        $BULLETIN.=",failure: function() {}";
                    $BULLETIN.="});";
                $BULLETIN.="}";
                $BULLETIN.=",interval: 25000";
        $BULLETIN.="};";
        $BULLETIN.="Ext.TaskMgr.start(bulletin);";
        ///

        $USER_TAB = "";
        $USER_TAB .= "var tabs =  new Ext.TabPanel({";
            $USER_TAB .= "autoTabs:true";
            $USER_TAB .= ",plain:true";
            $USER_TAB .= ",tabPosition: 'top'";
            $USER_TAB .= ",enableTabScroll:true";
            $USER_TAB .= ",activeTab:0,bodyStyle: 'background:".CamemisPage::userBgColor()."'";
            $USER_TAB .= ",items:[{";
                $USER_TAB .= "title: '".ACADEMIC_DASHBOARD."'";
                $USER_TAB .= ",id: 'ACADEMIC_DASHBOARD'";
                $USER_TAB .=",listeners: {activate: function(tab){tab.doLayout();}}";
                $USER_TAB .= ",layout: 'fit',bodyStyle:'background:".CamemisPage::userBgColor().";padding:3px'";
                $USER_TAB .= ",items: [new Ext.ux.IFrameComponent({ id: 'ACADEMIC_DASHBOARD', url:'/main/userdashboard/'})]";
            $USER_TAB .= "},{";
                $USER_TAB .= "title: '".MY_CALENDAR."'";
                $USER_TAB .= ",id: 'MY_CALENDAR'";
                $USER_TAB .=",listeners: {activate: function(tab){tab.doLayout();}}";
                $USER_TAB .= ",layout: 'fit',bodyStyle:'background:".CamemisPage::userBgColor().";padding:3px'";
                $USER_TAB .= ",items: [new Ext.ux.IFrameComponent({ id: 'MY_CALENDAR', url:'/school/calendar/'})]";
            $USER_TAB .= "}]";
        $USER_TAB .= "});";

        $USER_TAB_LOGIN = $USER_TAB;

        echo $USER_TAB_LOGIN;

        $js = "";
        $js .= "var btIdBulletinBoard = Ext.get('IdBulletinBoard');";
        $js .= "btIdBulletinBoard.on('click', function(){";
            $js .= "addTab('BULLETIN_BOARD','".BULLETIN_BOARD."','/bulletin/profilebulletin/');";
        $js .= "});";

        $js .= "var btIdCommunication = Ext.get('IdCommunication');";
        $js .= "btIdCommunication.on('click', function(){";
            $js .= "addTab('COMMUNICATION','".COMMUNICATION."','/communication/');";
        $js .= "});";

        $js .= "var btIdMyAccount = Ext.get('IdMyAccount');";
        $js .= "btIdMyAccount.on('click', function(){";
            $js .= "addTab('MY_ACCOUNT','".MY_ACCOUNT."','/finance/staffaccounthistory/?objectId=".$objectId."');";
        $js .= "});";

        $js .= "var btIdIdAbsence = Ext.get('IdAbsence');";
        $js .= "btIdIdAbsence.on('click', function(){";
            $js .= "addTab('ATTENDANCE','".ATTENDANCE."','/attendance/bystaff/?objectId=".$objectId."');";
        $js .= "});";
        if(UserAuth::getAddedUserRole() || UserAuth::getUserType()=='SUPERADMIN'|| UserAuth::getUserType()=='ADMIN'){
        $js .= "var btIdUserOnline = Ext.get('IdUserOnline');";
        $js .= "btIdUserOnline.on('click', function(){";
            $js .= "addTab('USER_ONLINE','".USER_ONLINE."','/user/useronline/');";
        $js .= "});";
        }
        $js .= "var btIdPersonalInformation = Ext.get('IdPersonalInformation');";
        $js .= "btIdPersonalInformation.on('click', function(){";
            $js .= "addTab('PERSONAL_INFORMATION','".MY_PROFILE."','/staff/staffmonitor/?objectId=".$objectId."');";
        $js .= "});";
        echo $js;

        $eventJs = "";
        $eventJs .= "function showResult(btn){";
            $eventJs .= "if (btn == \"yes\"){";
                $eventJs .= "Ext.Ajax.request({";
                    $eventJs .= "url:'/school/jsonsave/'";
                    $eventJs .= ",method: 'POST'";
                    $eventJs .= ",params: {cmd:'jsonLogout'}";
                    $eventJs .= ",success: function(response, options) {";
                        $eventJs .= "window.location.href='".Zend_Registry::get('CAMEMIS_URL')."/'";
                    $eventJs .= "}";
                $eventJs .= "});";
            $eventJs .= "}";
        $eventJs .= "};";
        echo $eventJs;
        ?>

        viewport = new Ext.Viewport({
            layout: 'fit'
            ,border: false
            ,items:[{
                layout:'border'
                ,border: false
                ,defaults: {
                    collapsible: true
                    ,split: true
                }
                ,items: [{
                    title: ''
                    ,hidden:true
                    ,id: 'app-header'
                    ,region: 'north'
                    ,height: 40
                    ,xtype: 'box'
                    ,html:'<p class="school-name"><?=$schoolName;?></p>'
                },{
                    title: ''
                    ,id:'MAIN_WEST_ID'
                    ,region:'west'
                    ,margins: '3 0 3 3'
                    ,cmargins: '0 3 3 3'
                    ,width: 210
                    ,minSize: 210
                    ,maxSize: 210
                    ,layout: 'fit'
                    ,items:[{
                        layout:'border'
                        ,border: false
                        ,defaults: {
                            collapsible: false
                            ,split: true
                        }
                        ,items: [{
                            title: ''
                            ,id:'westcenter'
                            ,collapsible: false
                            ,region:'center'
                            ,layout: 'fit'
                            ,margins: '0 3 3 3'
                            ,border:false
                            ,bodyStyle: 'padding-top:5px;background:#dee7f6;'
                            ,items: [{
                                border: true
                                ,bodyStyle: 'background:#dee7f6;'
                                ,contentEl: 'initUserNav'
                            }]
                        }]
                    }]
                },{
                    title: ''
                    ,bodyStyle: 'background:<?=CamemisPage::userBgColor();?>;padding:3px;'
                    ,collapsible: false
                    ,region:'center'
                    ,id: 'center'
                    ,layout: 'card'
                    ,activeItem: 0
                    ,margins: '3 3 3 0'
                    ,items: tabs
                    ,tbar:[<?=$this->TOOLBAR;?>]
                }]
            }]
        });
        <?
        if(UserAuth::getUserLoginActionStatus()){
            echo "openEasyWindow('".CHANGE_YOUR_PASSWORD."', '/staff/changepassword/?camIds=".$this->urlEncryp->encryptedGet("objectId=".$objectId."&refresh=main")."',500,300);";
        }
        //@veasna
        if (!Utiles::isLocalServer()){
            echo $USER_ONLINE;
            echo $INBOX_MESSAGE;
            echo $BULLETIN;
        }
        //
        ?>
    });
</script>
<style>
body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,form,fieldset,input,textarea,p,blockquote,th,td {
    margin:0;
    padding:0;
}
html,body {
    margin:0;
    padding:0;
}
table {
    border-collapse:collapse;
    border-spacing:0;
}
fieldset,img {
    border:0;
}
input{
    border:1px solid #b0b0b0;
    padding:3px 5px 4px;
    color:#979797;
    width:190px;
}
address,caption,cite,code,dfn,th,var {
    font-style:normal;
    font-weight:normal;
}
ol,ul {
    list-style:none;
}
caption,th {
    text-align:left;
}
h1,h2,h3,h4,h5,h6 {
    font-size:100%;
    font-weight:normal;
}
q:before,q:after {
    content:'';
}
    abbr,acronym { border:0;
}
body{
    background:#e6eecc  repeat top left;
    color: #333;
    font-family:verdana,tahoma,arial,sans-serif,Hanuman;
    font-size:11px;
}
.container{
    position:relative;
}
a{
    color: #dee7f6;
    text-decoration: none;
}
.clr{
    clear: both;
}
.content{
    position:relative;
}
h1{
    margin:0px;
    padding:20px;
    font-size:32px;
    color:#000;
    text-shadow:1px 1px 1px rgba(255,255,255,0.9);
    text-align:center;
    font-weight:400;
}
h1 span{
    display:block;
    font-size:11px;
    color:#666;
    font-style:italic;
    font-family:verdana,tahoma,arial,sans-serif,Hanuman;
    padding-top:5px;
}
/* Header Style */
.header{
    font-family:verdana,tahoma,arial,sans-serif,Hanuman;
    line-height: 24px;
    font-size: 11px;
    background: #000;
    opacity: 0.9;
    text-transform: uppercase;
    z-index: 9999;
    position: relative;
    -moz-box-shadow: 1px 0px 2px #000;
    -webkit-box-shadow: 1px 0px 2px #000;
    box-shadow: 1px 0px 2px #000;
}
.header a{
    padding: 0px 10px;
    letter-spacing: 1px;
    color: #ddd;
    display: block;
    float: left;
}
.header a:hover{
    color: #dee7f6;
}
.header span.right{
    float: right;
}
.header span.right a{
    float: none;
    display: inline;
}
.more{
    position:relative;
    clear:both;
    font-size: 11px;
    padding: 20px 0px;
    text-transform:uppercase;
    width: 390px;
    height:55px;
    margin: 0 auto;
}
.more ul{
    display:block;
    text-align:center;
}
.more ul li{
    display: block;
    padding: 4px 2px;
    float:left;
}
.more ul li.selected a,
.more ul li.selected a:hover{
    background:#0099c5;
    color:#dee7f6;
    text-shadow:none;
    font-weight:bold;
}
.more ul li a{
    color:#555;
    float:left;
    background:#dee7f6;
    width:64px;
    padding: 2px 5px;
    -moz-box-shadow:1px 1px 2px #aaa;
    -webkit-box-shadow:1px 1px 2px #aaa;
    box-shadow:1px 1px 2px #aaa;
}
.more ul li a:hover{
    background:#000;
    color:#dee7f6;
}
/*fdgdsgdsfgfdgdfgdfg*/
.ca-menu{
    padding: 0;
    margin: 0px auto;
    width: 220px;

}
.ca-menu li{
    width: 235px;
    height: 60px;
    overflow: hidden;
    display: block;
    background: #FFFFFF;
    color:#333;
    -webkit-box-shadow: 1px 1px 2px rgba(0,0,0,0.2);
    -moz-box-shadow: 1px 1px 2px rgba(0,0,0,0.2);
    box-shadow: 1px 1px 2px rgba(0,0,0,0.2);
    margin-bottom: 4px;
    border-left: 5px solid #4face0;;
    -webkit-transition: all 300ms ease-in-out;
    -moz-transition: all 300ms ease-in-out;
    -o-transition: all 300ms ease-in-out;
    -ms-transition: all 300ms ease-in-out;
    transition: all 300ms ease-in-out;
    margin-left: -10px;
}
.ca-menu li:last-child{
    margin-bottom: 0px;
}
.ca-menu li a{
    text-align: left;
    display: block;
    width: 100%;
    height: 100%;
    color: #333;
    position:relative;
}
.ca-iconBulletinBoard{
    background:url("/public/images/navigation/bullatin.png") no-repeat scroll 20px 20px transparent;
    color:#333;
    text-shadow: 0px 0px 1px #333;
    line-height: 90px;
    position: absolute;
    width: 90px;
    left: 0px;
    text-align: center;
    -webkit-transition: all 300ms linear;
    -moz-transition: all 300ms linear;
    -o-transition: all 300ms linear;
    -ms-transition: all 300ms linear;
    transition: all 300ms linear;
}

.ca-iconCommunication{
    background:url("/public/images/navigation/Communication.png") no-repeat scroll 20px 20px transparent;
    color:#333;
    text-shadow: 0px 0px 1px #333;
    line-height: 90px;
    position: absolute;
    width: 90px;
    left: 0px;
    text-align: center;
    -webkit-transition: all 300ms linear;
    -moz-transition: all 300ms linear;
    -o-transition: all 300ms linear;
    -ms-transition: all 300ms linear;
    transition: all 300ms linear;
}
.ca-iconMyAccount{
    background:url("/public/images/navigation/dollar.png") no-repeat scroll 20px 20px transparent;
    color:#333;
    text-shadow: 0px 0px 1px #333;
    line-height: 90px;
    position: absolute;
    width: 90px;
    left: 0px;
    text-align: center;
    -webkit-transition: all 300ms linear;
    -moz-transition: all 300ms linear;
    -o-transition: all 300ms linear;
    -ms-transition: all 300ms linear;
    transition: all 300ms linear;
}
.ca-iconAbsence{
    background:url("/public/images/navigation/calendar.png") no-repeat scroll 20px 18px transparent;
    color:#333;
    text-shadow: 0px 0px 1px #333;
    line-height: 90px;
    position: absolute;
    width: 90px;
    left: 0px;
    text-align: center;
    -webkit-transition: all 300ms linear;
    -moz-transition: all 300ms linear;
    -o-transition: all 300ms linear;
    -ms-transition: all 300ms linear;
    transition: all 300ms linear;
}
.ca-iconUserOnline{
    background:url("/public/images/navigation/userOnline.png") no-repeat scroll 20px 20px transparent;
    color:#333;
    text-shadow: 0px 0px 1px #333;
    line-height: 90px;
    position: absolute;
    width: 90px;
    left: 0px;
    text-align: center;
    -webkit-transition: all 300ms linear;
    -moz-transition: all 300ms linear;
    -o-transition: all 300ms linear;
    -ms-transition: all 300ms linear;
    transition: all 300ms linear;
}
.ca-iconPersonalInformation{
    background:url("/public/images/navigation/male.png") no-repeat scroll 20px 18px transparent;
    color:#333;
    text-shadow: 0px 0px 1px #333;
    line-height: 90px;
    position: absolute;
    width: 90px;
    left: 0px;
    text-align: center;
    -webkit-transition: all 300ms linear;
    -moz-transition: all 300ms linear;
    -o-transition: all 300ms linear;
    -ms-transition: all 300ms linear;
    transition: all 300ms linear;
}
.ca-content{
    position: absolute;
    left: 65px;
    width: 200px;
    height: 60px;
    top: 15px;
}
.ca-main{
    font-size: 11px;
    color:#596F8F;
    font-weight: bold;
    -webkit-transition: all 300ms linear;
    -moz-transition: all 300ms linear;
    -o-transition: all 300ms linear;
    -ms-transition: all 300ms linear;
    transition: all 300ms linear;
}
.ca-sub{
    font-size: 9px;
    color: #FF0000;
    margin-top: 5px;
    -webkit-transition: all 300ms linear;
    -moz-transition: all 300ms linear;
    -o-transition: all 300ms linear;
    -ms-transition: all 300ms linear;
    transition: all 300ms linear;
}
.ca-menu li:hover{
    border-color: #FFF;
    background: #4face0;
}
.ca-menu li:hover .ca-iconBulletinBoard{
    background:url(/public/images/navigation/bullatin-hover.png) no-repeat scroll 20px 15px transparent;
    color: #FFF;
    text-shadow: 0px 0px 1px #dee7f6004;
    font-size: 40px;
}
.ca-menu li:hover .ca-iconCommunication{
    background:url(/public/images/navigation/Communication-hover.png) no-repeat scroll 20px 15px transparent;
    color: #FFF;
    text-shadow: 0px 0px 1px #dee7f6004;
    font-size: 40px;
}
.ca-menu li:hover .ca-iconMyAccount{
    background:url(/public/images/navigation/dollar-hover.png) no-repeat scroll 20px 15px transparent;
    color: #FFF;
    text-shadow: 0px 0px 1px #dee7f6004;
    font-size: 40px;
}
.ca-menu li:hover .ca-iconAbsence{
    background:url(/public/images/navigation/calendar-hover.png) no-repeat scroll 20px 15px transparent;
    color: #FFF;
    text-shadow: 0px 0px 1px #dee7f6004;
    font-size: 40px;
}
.ca-menu li:hover .ca-iconUserOnline{
    background:url(/public/images/navigation/userOnline-hover.png) no-repeat scroll 20px 15px transparent;
    color: #FFF;
    text-shadow: 0px 0px 1px #dee7f6004;
    font-size: 40px;
}
.ca-menu li:hover .ca-iconPersonalInformation{
    background:url(/public/images/navigation/male-hover.png) no-repeat scroll 20px 15px transparent;
    color: #FFF;
    text-shadow: 0px 0px 1px #dee7f6004;
    font-size: 40px;
}
.ca-menu li:hover .ca-main{
    color: #FFF;
    font-size:12px;
}
.ca-menu li:hover .ca-sub{
    color: #FF0000;
    font-size: 12px;
}
</style>

<div>
    <div id="initCenter" class="x-hidden" style="background:<?=CamemisPage::userBgColor();?>;padding:5px;">
        <?=Zend_Registry::get('USER')->CODE;?>
        <br>
        <?=Zend_Registry::get('USER')->LASTNAME;?> <?=Zend_Registry::get('USER')->FIRSTNAME;?>
        <br>
        <?=str_replace(',', '<br>', Zend_Registry::get('USER')->PHONE);?>
        <br>
        <?=str_replace(',', '<br>', Zend_Registry::get('USER')->EMAIL);?>
        <br>
    </div>
</div>
<?
echo $HTML;   
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>