<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 25.11.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<link href="/public/bootstrap/css/bootstrap.css" rel="stylesheet">
<link href="/public/bootstrap/css/custom.css" rel="stylesheet">

<div style="margin: 20px;">
    <table class="table">
       <caption>Contextual Table Layout</caption>
       <thead>
          <tr  class="success">
             <th>Student</th>
             <th>Student</th>
             <th class="text-center" colspan="3">Assignment 1</th>
             <th class="text-center" colspan="2">Assignment 2</th>
             <th class="text-center" colspan="3">Assignment 3</th>
          </tr>
       </thead>
       <thead>
          <tr class="danger">
             <th>Student</th>
             <th>Result</th>
             <th class="text-center">10.05.2013</th>
             <th class="text-center">22.05.2013</th>
             <th class="text-center">10.05.2013</th>
             <th class="text-center">10.05.2013</th>
             <th class="text-center">10.05.2013</th>
             <th class="text-center">10.05.2013</th>
             <th class="text-center">10.05.2013</th>
             <th class="text-center">10.05.2013</th>
          </tr>
       </thead>
       <tbody>
          <tr class="active">
             <td>Student 1</td>
             <td class="text-center">100</td>
             <td class="text-center">50</td>
             <td class="text-center">60</td>
             <td class="text-center" >70</td>
             <td class="text-center">80</td>
             <td class="text-center">90</td>
             <td class="text-center">100</td>
             <td class="text-center">70</td>
             <td class="text-center">45</td>
          </tr>
          <tr class="active">
             <td>Student 2</td>
             <td class="text-center">100</td>
             <td class="text-center">50</td>
             <td class="text-center">60</td>
             <td class="text-center" >70</td>
             <td class="text-center">80</td>
             <td class="text-center">90</td>
             <td class="text-center">100</td>
             <td class="text-center">70</td>
             <td class="text-center">45</td>
          </tr>
          <tr class="active">
             <td>Student 3</td>
             <td class="text-center">100</td>
             <td class="text-center">50</td>
             <td class="text-center">60</td>
             <td class="text-center" >70</td>
             <td class="text-center">80</td>
             <td class="text-center">90</td>
             <td class="text-center">100</td>
             <td class="text-center">70</td>
             <td class="text-center">45</td>
          </tr>
          <tr class="active">
             <td>Student 4</td>
             <td class="text-center">100</td>
             <td class="text-center">50</td>
             <td class="text-center">60</td>
             <td class="text-center" >70</td>
             <td class="text-center">80</td>
             <td class="text-center">90</td>
             <td class="text-center">100</td>
             <td class="text-center">70</td>
             <td class="text-center">45</td>
          </tr>
       </tbody>
    </table>
</div>

<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>