<?
///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 25.11.2013
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisForm.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/UserAuth.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<style>
 @media screen and (-webkit-min-device-pixel-ratio:0) { 
    .x-grid3-cell, /* Normal grid cell */
    .x-grid3-gcell /* Grouped grid cell (esp. in head)*/
    {
        box-sizing: border-box;
    }
}
</style>

<script>
Ext.onReady(function() {
    var fields = [],
    columns = [],
    data = [],
    assignmentGroupRow = [];

    // assignmentGroupRow at this point is:
    var assignmentGroupRow = [
        {header: '&nbsp;', colspan: 1, align: 'center'},
        {header: 'Result', colspan: 1, align: 'center'},
        {header: 'Assessment', colspan: 1, align: 'center'},
        {header: 'Assignment #1', colspan: 2, align: 'center'},
        {header: 'Assignment #2', colspan: 2, align: 'center'},
        {header: 'Assignemnt #3', colspan: 2, align: 'center'},
        {header: 'Assignment #4', colspan: 2, align: 'center'},
        {header: 'Assignment #5', colspan: 2, align: 'center'},
        {header: 'Assignment #6', colspan: 1, align: 'center'}
    ]
     
    var group = new Ext.ux.grid.ColumnHeaderGroup({
        rows: [assignmentGroupRow]
    });
    
    //fields at this point is:
    var fields =  [
        {type: 'int', name: 'FULL_NAME'},
        {type: 'int', name: 'RESULT'},
        {type: 'int', name: 'ASSESSMENT'},
        {type: 'int', name: 'A11'},
        {type: 'int', name: 'A12'},
        {type: 'int', name: 'B11'},
        {type: 'int', name: 'B12'},
        {type: 'int', name: 'C11'},
        {type: 'int', name: 'C12'},
        {type: 'int', name: 'D11'},
        {type: 'int', name: 'D12'},
        {type: 'int', name: 'E11'},
        {type: 'int', name: 'E12'},
        {type: 'int', name: 'A61'}
    ]
      
    // columns at this point is:
    var columns = [
        {dataIndex: 'FULL_NAME', header: 'Fullname'},
        {dataIndex: 'RESULT', header: '&nbsp;', width: 80 ,align: 'center'},
        {dataIndex: 'ASSESSMENT', header: '&nbsp;', width: 100 ,align: 'center'},
        {dataIndex: 'A11', header: '10.05.2013' , width: 80 ,align: 'center'},
        {dataIndex: 'A12', header: '20.07.2013' , width: 80 ,align: 'center'},
        {dataIndex: 'B11', header: '10.05.2013' , width: 80 ,align: 'center'},
        {dataIndex: 'B12', header: '20.07.2013' , width: 80 ,align: 'center'},
        {dataIndex: 'C11', header: '10.05.2013' , width: 80 ,align: 'center'},
        {dataIndex: 'C12', header: '20.07.2013' , width: 80 ,align: 'center'},
        {dataIndex: 'D11', header: '10.05.2013' , width: 80 ,align: 'center'},
        {dataIndex: 'D12', header: '20.07.2013' , width: 80 ,align: 'center'},
        {dataIndex: 'E11', header: '10.05.2013' , width: 80 ,align: 'center'},
        {dataIndex: 'E12', header: '20.07.2013' , width: 80 ,align: 'center'},
        {dataIndex: 'A61', header: 'Leer' , width: 100 ,align: 'center'}
    ]
 
    var grid = new Ext.grid.GridPanel({
        title: 'Sales By Location',
        store: new Ext.data.Store({
            proxy: new Ext.data.HttpProxy({url:'/evaluation/jsonload/', method: 'POST'})
            ,baseParams:{academicId:'123'}
            ,reader:new Ext.data.JsonReader({
                id:'NAME'
                ,totalProperty:'totalCount'
                ,root:'rows'
                ,fields:[
                    {name: 'ID'}
                    ,fields
                ]
            })
        }),
//        store: new Ext.data.ArrayStore({
//            fields: fields,
//            data: data
//        }),
        columns: columns,
        viewConfig: {
            forceFit: false
        },
        plugins: group
    });
    
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'fit'
            ,border: false
            ,bodyStyle: 'padding: 20px;'
            ,items:[grid]
        }]
    });
});
</script>

<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>