<?

///////////////////////////////////////////////////////////
// @Sea Peng
// Date: 15.01.2014
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'include/Common.inc.php';
require_once 'clients/CamemisTree.php';
require_once 'clients/CamemisBar.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();
print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

    Ext.onReady(function() {

        var SaleRecord = Ext.data.Record.create([
            {name: 'full_name', type: 'string'},
            {name: 'score_date', type: 'string'},
            {name: 'state', type: 'string'},
            {name: 'month', type: 'int'},
            {name: 'quarter', type: 'int'},
            {name: 'year', type: 'string'},
            {name: 'quantity', type: 'int'},
            {name: 'value', type: 'int'}
        ]);

        var myStore = new Ext.data.Store({
            url: '/public/data/simple.json',
            autoLoad: true,
            reader: new Ext.data.JsonReader({
                root: 'rows',
                idProperty: 'id'
            }, SaleRecord)
        });

        var pivotGrid = new Ext.grid.PivotGrid({
            title: 'PivotGrid example',
            store: myStore,
            //aggregator: 'sum',
            measure: 'value',
            viewConfig: {
                title: 'Student'
            },
            leftAxis: [
                {
                    width: 90,
                    dataIndex: 'full_name'
                }
            ],
            topAxis: [
                {
                    dataIndex: 'year'
                },
                {
                    dataIndex: 'score_date'
                    ,width:50
                }
            ]
        });

        viewport = new Ext.Viewport({
            layout: 'fit'
            , border: false
            , items: [{
                    layout: 'fit'
                    , border: false
                    , items: [pivotGrid]
                }]
        });
    });
</script>
<?

print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>