<?
///////////////////////////////////////////////////////////
// @Sor Veasna
// Date: 03.05.2013
// 
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_GRID = new CamemisGrid("SUBJECTREPORT", "LIST");
$OBJECT_GRID->setLoadUrl('/subjectreport/jsonload/');

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>

<script>
Ext.onReady(function() {
    
    function showLimitText(text,limit){
         return text.substring(0, limit);
    }
    
    function cssTextBold(value, metadata, record){
        return '<div style="margin: 10px 10px 10px 10px; font-weight:bold; color:#333; white-space:normal;">' + value + '</div>';
    }
    function cssText(value, metadata, record){
        return '<div style="margin: 10px 10px 10px 10px;">' 
            +'<span style="font-weight:bold; white-space:normal; color:#061f83;">'
            +record.data.TITLE
            + '</span><br/><br/>' 
            +'<span style="font-weight:normal; white-space:normal; color:#555;"> '
            + showLimitText(value,250)
            + ' .....</span>'
            + '</div>';
    }
    function cssTextAdmin(value, metadata, record){
        return '<div style="margin: 10px 10px 10px 10px;">'
            +'<span style="font-weight:bold; white-space:normal; color:#000;">'
            +record.data.TEACHER_NAME
            + '</span><br/><br/>' 
            +'<span style="font-weight:bold; white-space:normal; color:#061f83;">'
            +record.data.TITLE
            + '</span><br/><br/>' 
            +'<span style="font-weight:normal; white-space:normal; color:#555;"> '
            + showLimitText(value,250)
            + ' .....</span>'
            + '</div>';
    }
    <?
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addReadField("name: 'CONTENT_ID'");
    $OBJECT_GRID->addReadField("name: 'CREATED_DATE'");
    $OBJECT_GRID->addReadField("name: 'TITLE'");
    $OBJECT_GRID->addReadField("name: 'CONTENT'");
    $OBJECT_GRID->addReadField("name: 'TEACHER_NAME'");
    $OBJECT_GRID->addColumn("header: '<b>".CREATED_DATE."</b>', renderer: cssTextBold, width: 150, sortable: true, dataIndex: 'CREATED_DATE'");
     
    if(UserAuth::getUserType()){ 
        switch(UserAuth::getUserType()){
            case 'INSTRUCTOR':
            case 'TEACHER':
                $OBJECT_GRID->addColumn("header: '<b>".CONTENT."</b>', renderer: cssText, width: percentWidth(95), sortable: true, dataIndex: 'CONTENT'"); 
                if($this->subjectId > 0)
                $OBJECT_GRID->addTBarItems("
                    tbar.add(['-',{
                        id: 'ADD_A_NEW_ITEM'
                        ,text: '".ADD_A_NEW_ITEM."'
                        ,iconCls:'icon-application_form_add'
                        ,handler: function(){
                            clickOpenPage('center','".ADD_A_NEW_ITEM."', '".$this->URL_SHOWITEM."?classId=".$this->classId."&subjectId=".$this->subjectId."'); 
                        }
                    }]);
                ");  
            break;
            case 'ADMINISTRATOR':
            case 'SUPERADMIN':
                $OBJECT_GRID->addColumn("header: '<b>".CONTENT."</b>', renderer: cssTextAdmin, width: percentWidth(95), sortable: true, dataIndex: 'CONTENT'");
                $OBJECT_GRID->addTBarItems("
                    tbar.add(['-',{
                        id: 'CANCEL_ID'
                        ,text: '".CANCEL."'
                        ,iconCls:'icon-cancel'
                        ,handler: function(){
                            Ext.Ajax.request({
                                url:'/staff/jsonload/'
                                ,method: 'POST'
                                ,params: {cmd: 'jsonLoadLastStaffStatus',objectId:'".$this->objectId."'}
                                ,success: function(response, options) {
                                    var jsonData = Ext.util.JSON.decode(response.responseText);

                                    if(window.parent.Ext.getCmp('STAFF_LIST_ID')){
                                        var sm = window.parent.Ext.getCmp('STAFF_LIST_ID').getSelectionModel();
                                        var record = sm.getSelected();
                                        record.set('STATUS_KEY',jsonData.data.SHORT);
                                        record.set('BG_COLOR',jsonData.data.COLOR);
                                        record.set('BG_COLOR_FONT',jsonData.data.COLOR_FONT);
                                        record.commit();
                                    }
                                    window.parent.Ext.getCmp('center').getLayout().setActiveItem(0);
                                }
                                ,failure: function(response, options) {}
                            });
                        }
                    }]);
                ");   
            break;     
        }
    }

    $OBJECT_GRID->addTBarItems("
        tbar.add('->');
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,cmd: 'jsonLoadAllSubjectTeachingReport'
        ,classId: '".$this->classId."'
        ,subjectId: '".$this->subjectId."'
        ,teacherId: '".$this->teacherId."'
    ";
    
    $OBJECT_GRID->loadMask = false;
    $OBJECT_GRID->isQuickySearch = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->isObjectDefaultOnLoad = true;
    $OBJECT_GRID->isGroupingView = true;
    $OBJECT_GRID->groupField = "CREATED_DATE";
    $OBJECT_GRID->renderJS();
    
    $VIEWPORT_TUTOR = "";    
    $VIEWPORT_TUTOR .= "viewport = new Ext.Viewport({";
        $VIEWPORT_TUTOR .= "layout: 'fit'";
        $VIEWPORT_TUTOR .= ",border: false";
        $VIEWPORT_TUTOR .= " ,items: [{";
            $VIEWPORT_TUTOR .= "xtype: 'panel'";
            $VIEWPORT_TUTOR .= ",id: 'center'";
            $VIEWPORT_TUTOR .= ",border: false";
            $VIEWPORT_TUTOR .= ",layout: 'card'";
            $VIEWPORT_TUTOR .= ",activeItem: 0";  
            $VIEWPORT_TUTOR .= ",items:[{xtype: '".$OBJECT_GRID->getObjectXtype()."'}]";
        $VIEWPORT_TUTOR .= " }]";
    $VIEWPORT_TUTOR .= "});";
     
    $EVENT_SHOW_DETAIL = "
        Ext.getCmp('SUBJECTREPORT_LIST_ID').on('cellclick', function(grid, rowIndex, columnIndex, event) {
            var record = grid.store.getAt(rowIndex);
            clickOpenPage('center','', '".$this->URL_SHOWITEM."objectId='+record.data.CONTENT_ID);
        });
    ";

    echo $VIEWPORT_TUTOR;
    echo $EVENT_SHOW_DETAIL;
            
    ?>
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>