<?
///////////////////////////////////////////////////////////
// @Kaom Vibolrith Senior Software Developer
// Date: 18.07.2009
// Am Stollheen 18, 55120 Mainz, Germany
///////////////////////////////////////////////////////////
require_once 'clients/CamemisPage.php';
require_once 'clients/CamemisField.php';
require_once 'clients/CamemisBar.php';
require_once 'clients/CamemisGrid.php';
require_once 'clients/CamemisForm.php';
require_once 'clients/CamemisTree.php';
require_once 'include/Common.inc.php';
require_once 'utiles/Utiles.php';
require_once 'models/app_school/academic/AcademicDBAccess.php';
require_once setUserLoacalization();

$CAMEMIS_PAGE_OBJECT = CamemisPage::getInstance();

$OBJECT_GRID = new CamemisGrid("ATTENDANCE", "LIST");
$OBJECT_GRID->setLoadUrl('/attendance/jsonload/');
$OBJECT_GRID->setSaveUrl('/attendance/jsonsave/');
$columndata = Utiles::getGridColumnData("ATTENDANCE_LIST_ID");

$classId = isset($_GET['classId'])?addText($_GET['classId']):"";
$trainingId = isset($_GET['trainingId'])?addText($_GET['trainingId']):"";

print $CAMEMIS_PAGE_OBJECT->showCamemisHeader();
?>
<script>

Ext.onReady(function() {
    
    function cssStatus(v, p, record){
        return String.format('<div style=\"font-weight:bold;padding:4px;background:{1};color:{2};\">{0}</div>'
            ,v
            ,record.data['BG_COLOR']
            ,record.data['BG_COLOR_FONT']
        );
    }
        
    function renderText(value, metadata, record){
        return '<div style="font-weight:normal; color:#333; padding: 3px; height:10px;;">' + value + '</div>';
    }
    <?
    /**
    * Extjs: s.gif
    */
    $CAMEMIS_PAGE_OBJECT->setCostumerCSS();
    $CAMEMIS_PAGE_OBJECT->setExtDefaultGif();
    
    $OBJECT_GRID->addReadField("name: 'ID'");
    $OBJECT_GRID->addReadField("name: 'CODE'");
    $OBJECT_GRID->addReadField("name: 'FIRSTNAME'");
    $OBJECT_GRID->addReadField("name: 'LASTNAME'");
    $OBJECT_GRID->addReadField("name: 'BG_COLOR'");
    $OBJECT_GRID->addReadField("name: 'BG_COLOR_FONT'");
    $OBJECT_GRID->addReadField("name: 'STATUS_KEY'");
    
    switch(Zend_Registry::get('SYSTEM_LANGUAGE')){
        case "VIETNAMESE": $width = 100;break;
        default: $width = 85;break;
    }
    
    $OBJECT_GRID->addColumn("header: '<b>".STATUS."</b>', align:'center', width: ".$width.", hidden:".checkColHidden(1, $columndata).", renderer:cssStatus, sortable: true, dataIndex: 'STATUS_KEY'");
    
    $OBJECT_GRID->addColumn("header: '<b>".CODE_ID."</b>', width: 80, hidden:".checkColHidden(2, $columndata).", renderer: renderText, sortable: true, dataIndex: 'CODE'");
    if(!SchoolDBAccess::displayPersonNameInGrid()){
       $OBJECT_GRID->addColumn("header: '<b>".LASTNAME."</b>', width: 120, hidden:".checkColHidden(3, $columndata).", renderer: renderText, sortable: true, dataIndex: 'LASTNAME'");
       $OBJECT_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', width: 120, hidden:".checkColHidden(4, $columndata).", renderer: renderText, sortable: true, dataIndex: 'FIRSTNAME'");
    }else{
       $OBJECT_GRID->addColumn("header: '<b>".FIRSTNAME."</b>', width: 120, hidden:".checkColHidden(4, $columndata).", renderer: renderText, sortable: true, dataIndex: 'FIRSTNAME'");
       $OBJECT_GRID->addColumn("header: '<b>".LASTNAME."</b>', width: 120, hidden:".checkColHidden(3, $columndata).", renderer: renderText, sortable: true, dataIndex: 'LASTNAME'");
    }
     
    $OBJECT_GRID->addTBarItems("
        tbar.add([{
            id: 'REFRESH_ID'
            ,text: '".REFRESH."'
            ,iconCls:'icon-reload'
            ,scope:this
            ,disabled: false
            ,handler: function(){
               Ext.getCmp('".$OBJECT_GRID->getObjectId()."').store.reload();
            }
        }]);
    ");
    
    $OBJECT_GRID->baseParams = "
        start:0
        ,limit:100
        ,classId: '".$classId."'
        ,trainingId: '".$trainingId."'
        ,cmd: 'jsonStudentAttendanceBlock'
    ";
    
    $OBJECT_GRID->isQuickySearch = true;
    $OBJECT_GRID->forceFit = "false";
    $OBJECT_GRID->renderJS();
    
    ?>
    viewport = new Ext.Viewport({
        layout: 'fit'
        ,border: false
        ,items:[{
            layout:'border'
            ,border: false
            ,defaults: {
                collapsible: false
                ,split: true
            }
            ,items: [{
                title: ''
                ,id:'WEST_ID'
                ,region:'west'
                ,margins: '3 0 3 3'
                ,cmargins: '3 3 3 3'
                ,width: 450
                ,minSize: 450
                ,maxSize: 450
                ,layout: 'fit'
                ,items: [{xtype: '<?=$OBJECT_GRID->getObjectXType();?>'}]
            },{
                title: ''
                ,collapsible: false
                ,region:'center'
                ,id: 'content'
                ,layout: 'card'
                ,activeItem: 0
                ,margins: '3 3 3 0'
                ,items: [{
                    border: false
                    ,layout: 'anchor'
                    ,bodyStyle: 'background:#FFFFFF; padding:25px;'
                    ,items: [{
                        title: ''
                        ,height:60
                        ,width:500
                        ,bodyStyle: 'background:#F9F9F9; padding:10px; border:1px dotted #999;text-align:center;'
                        ,html:'<h1 class="header"><?=PLEASE_MAKE_YOUR_SELECTIONS;?></h1>'
                    }]
                }]
            }]
        }]
    });
    <?
    if($classId){
        $params = "classId=".$classId."&target=general";
    }elseif($trainingId){
        $params = "trainingId=".$trainingId."&target=training";
    }
    
    $LIST_ATTENDANCE ="{";
    $LIST_ATTENDANCE .="text: '".SHOW_DETAIL." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME";
    $LIST_ATTENDANCE .=",iconCls: 'icon-user'";
    $LIST_ATTENDANCE .=",handler: function(){";
    $LIST_ATTENDANCE .="clickOpenPage('content','','/attendance/studentpersonblock/?".$params."&studentId=' + record.data.ID);";
    $LIST_ATTENDANCE .="}";
    $LIST_ATTENDANCE .="}";
    
    $CONTEXTMENU_ITEMS[] = $LIST_ATTENDANCE;
    
    $ADD_ATTENDANCE ="{";
    $ADD_ATTENDANCE .="text: '".ADD_ATTENDANCE." &raquo; ' + record.data.LASTNAME + ' ' + record.data.FIRSTNAME";
    $ADD_ATTENDANCE .=",iconCls: 'icon-add'";
    $ADD_ATTENDANCE .=",handler: function(){";
    $ADD_ATTENDANCE .="clickOpenPage('content','','/attendance/showbystudent/?".$params."&objectId=new&studentId=' + record.data.ID);";
    $ADD_ATTENDANCE .="}";
    $ADD_ATTENDANCE .="}";
    
    $CONTEXTMENU_ITEMS[] = $ADD_ATTENDANCE;
    
    $CHOOSE_CONTEXTMENU_ITEMS = implode(",", $CONTEXTMENU_ITEMS);
    if($CONTEXTMENU_ITEMS){
	$js = "";
	$js .="var grid = Ext.getCmp('".$OBJECT_GRID->getObjectId()."');";
	$js .="if (grid) grid.on('cellclick', function(grid, rowIndex, columnIndex, event) {";
	    $js .="var record = grid.store.getAt(rowIndex);";
	    $js .="var contextMenu = new Ext.menu.Menu({";
		$js .="items: [".$CHOOSE_CONTEXTMENU_ITEMS."]";
	    $js .="});";
	    $js .="event.stopEvent();";
	    $js .="contextMenu.showAt(event.xy);"; 
	$js .="});";
	echo $js;
    }
    ?>
    Ext.state.Manager.setProvider(new Ext.state.HttpProvider({url: '/dataset/jsonsave/'}));
});
</script>
<?
print $CAMEMIS_PAGE_OBJECT->showCamemisFooter();
?>